### ISSUE TITLE
null not considered for defaultValue

### ISSUE THREAD

**Issue by alvincrespo** [emberjs/data#1087]
During an initial test using emberdata I've found that null is not being checked and therefore the defaultValue not set.

````javascript
function getAttr(record, options, key) {
  var attributes = get(record, 'data').attributes;
  var value = attributes[key];

  if (value === undefined ) {
    if (typeof options.defaultValue === "function") {
      value = options.defaultValue();
    } else {
      value = options.defaultValue;
    }
  }

  return value;
}
````

Recommended patch:

````javascript
function getAttr(record, options, key) {
  var attributes = get(record, 'data').attributes;
  var value = attributes[key];

  if (!value) {
    if (typeof options.defaultValue === "function") {
      value = options.defaultValue();
    } else {
      value = options.defaultValue;
    }
  }

  return value;
}
````

**Comment by seanpdoyle** [comment]
@wagenet @igorT this behavior has resurfaced.

http://emberjs.jsbin.com/hujikocumu/1/edit?html,js,output

Is `null` an acceptable value for a model?

Is this the intended behavior?

Is `undefined` the only value that will be overridden by `defaultValue`?

**Comment by fivetanley** [comment]
Null is acceptable imo.

**Comment by seanpdoyle** [comment]
@fivetanley I can understand that perspective, but it's not what I'd expect out of the box.

**Comment by bmac** [comment]
I think `null` is a valid value that overrides the default value. Reading the liked pr it seems @alvincrespo issue was related to attributes not included in the response would be set to null, that behavior has been fixed.
