### ISSUE TITLE
Model find returns 404 and is cached on future attempts

### ISSUE THREAD

**Issue by abobwhite** [emberjs/data#1266]
Ember 1.0
Ember Data 1.0 Beta 2

I have been struggling with this for hours. At the heart of my issue is my complaint that ember data caches every request without any easy way to prevent it. Typically, I have found ways around this, however, this time I have not been so lucky.

The situation: I have a model that doesn't exist prior to a certain point in a workflow, however, the user has the ability to click a link that attempts the route. When the find() call returns a 404 error, the application prevents that route from completing. Later, the model is created and when attempting that route, the 404 response is cached and therefore, the route is inaccessible unless giving the app the ole F5.

I have circumvented this caching before by using the setupController method to call reload on the model, however, the actions: { error: function(){} } is catching the cached 404 on the route and setupController is never called.

Here is some relevant code:

```
App.DashboardIndexRoute = Ember.Route.extend({
  model: function(){
    return this.store.find('membership', {id});
  },

  setupController: function(controller, model) {
    model.reload().then(function(data){
      controller.set('model', data);
    });
  },

  actions: {
    error: function(reason, transition){
      this.transitionTo('dashboard.profile.edit');
      toastr.error(...);
    }
  }
});
```

Caching is absolutely killing me right now. Is there something in the works for setting a flag in Ember Data to never cache a request? Otherwise, does anyone have any suggestions?

**Comment by maheshiv** [comment]
@wycats : this issue is still there . I am using Ember-data 1.0.0-beta.11 .

**Comment by wecc** [comment]
@maheshiv I think #2467 will solve this

**Comment by maheshiv** [comment]
@wecc thanks .
