### ISSUE TITLE
Possibly add `isLoaded` to `DS.PromiseArray`

### ISSUE THREAD

**Issue by sandstrom** [emberjs/data#1274]
On `DS.RecordArray` there is a `isLoaded` flag, however the `DS.PromiseArray` has nothing of that sort.

There is a flag `isSettled` and `isFullfilled`, but apart from being promise-specific, when they fire the array doesn't have any length, e.g. still empty from the perspective of the UI/application.

Is this something that should be added to `DS.PromiseArray`?

---

_Common use-cases are loading indicators, or reading metadata from the type map, e.g._

```
Em.computed(function() {
  return this.get('store').typeMapFor(model).metadata.pagination.count;
}, 'collection.isLoaded');
```

**Comment by harianus** [comment]
I never heard of `isSettled`, it seems to solve my problem. But the thing is, I've heard a lot of `isLoading`, so I tried to use that without success. It would be logical that `isLoading` also works for `DS.PromiseArray`
