### ISSUE TITLE
findHasMany doesn't accept query parameters

### ISSUE THREAD

**Issue by abobwhite** [emberjs/data#1311]
Using Ember Data Latest - Canary Build as of 9/16/13

I have a model that lazy-loads its products so I don't have to GET them when I don't need them:

```
App.Supplier = DS.Model.extend({
  products: DS.hasMany('product', {async : true}),
});
```

However, on some templates, I call `supplier.get('products')` to show a list of that Supplier's products. The problem arises when I need to pass pagination, filter, and sorting parameters to the server from within that "get" call. I know this is possible via `find('modelName', { /* query params here */}` but this does not seem possible via the `findHasMany` which gets triggered via the "get". Is there some other way to do this? I feel like this is a very valid use-case to retrieve a filtered list of the products for a particular supplier.

Thoughts? Thanks!

**Comment by palimpsests** [comment]
Have either of you discovered a solution for this? I have the exact same need, to send a query with a findHasMany call.
