### ISSUE TITLE
[Improvement?] find should take both id and query parameters

### ISSUE THREAD

**Issue by abobwhite** [emberjs/data#1326]
I have a situation where I need to find a model via `/models/{id}` but to also provide query parameters: `/models/{id}?key=value`. The reason is that this particular model is under version control on the server. It can get "approved" and become publicly visible but another version can still be edited by the user in a "draft" state. When the user is logged in, they should be able to access the model in that "draft" state. There are two obvious solutions:

1) Enhance `find({id})` to optionally take query params: `find({id}, {/* draft : true */})`
2) Extend the model to be something like a "DraftModel" which would only serve as a wrapper to hit a different server endpoint: `/draftModels/{id}`

I prefer option 1 but I can see how opinions would be split between the options. Option 1 can be used to provide different information on the same model depending on a specific use-case and the state of the data.

Thoughts?

**Comment by thomasvanlankveld** [comment]
+1 for `find('model', id, paramsObj);`. Feels only natural with `find('model', id);` and `find('model', paramsObj);` available. Is this really an edge case?

**Comment by abobwhite** [comment]
@thomasvanlankveld I agree with you. There should be some standard way to do this. I do not believe it to be an edge case. It's fairly common practice even if it's not the most common scenario. It seems this and other related issues have been dismissed (closed) by core team members because they probably had bigger fish to fry. But currently, all solutions suggested making this work are a hack. I think the ultimate issue at hand here is that if we try ```this.store.find('myModel', {id : myId, otherParam: true})``` which used id as a param, the serializer expects the result to be an array because ```findQuery``` is invoked. If ```findQuery``` were to not assume array, then this might be a bit simpler and could conceivably be handled on the app-level rather than at an ember level.

That being said, I'm in favor of simply permitting query params on the ```find``` for a single model.

**Comment by matixmatix** [comment]
+1 for `find('model', id, paramsObj)`. It's really frustrating using `find('myModel', {id : myId, otherParam: true})`, because the result is passed as an array. I don't believe this is really such an edge case, and would gladly see it getting implemented in the near future.

**Comment by jeffjarchow** [comment]
+1 for find('model', id, paramsObj). This is something I find myself needing on many of my endpoints of my API. It just doesn't feel right having to fetch a single record as an array and extract the index I need every time.

There is possibly another option, although I don't know how much it might slow things down (and doesn't quite feel right either). A possible solution is to see if any one of the keys in the params object matches the models primaryKey. If so, return a single object instead of an array. But this might be difficult to pull off considering the id parameter can be an array of ids (if I'm not mistaken).

**Comment by thaume** [comment]
This will be possible once findQueryOne will be merged (which should be
quite soon).
https://github.com/emberjs/data/pull/2584
You'll be able to fetch with an id + parameters and get an object in
return, not an array.

**Comment by abobwhite** [comment]
@thaume Great! Glad to see something came out of this. Thanks for putting the time to develop the feature. I hope it gets merged soon. 

This issue has only been here for 1.5 years! One of the key features needed to make ED really robust.

**Comment by jeffjarchow** [comment]
Great news @thaume. Thank you for the update.

**Comment by iamjstates** [comment]
@thaume - I was looking for this today. I hope this get in the next beta release.

**Comment by tschoartschi** [comment]
I would also need this functionality. Our use case is as follows:

When I query an object just by it's ID I get all labels of this object in the default language (which is english). Now when I specify a contentLanguage as query param I get the labels in the corresponding language. But when I want to query a object by it's ID and get it in a special contentLanguage I can't do it. My first thought was also to query like the others mentioned:
```javascript
this.get('store').find('item',id,{contentLanguage: 'de'}).then(function(response) {
        // PROCESS SUCCESS
}, function(error) {
        // PROCESS ERROR
});
```
But it does not work! Is there any way to accomplish this behavior without some hack?

**Comment by abobwhite** [comment]
@tschoartschi While this use-case definitely needs to happen (I've been waiting for over 1.5 years for it), I think in your case, you could probably use the HTTP Header: 'Accept-Language' which can be defined in your adapter. On your server-side, you would just read this header and apply logic accordingly, thus removing the need for a query parameter here.

**Comment by friksa** [comment]
+1 for fitting into the real world

**Comment by wecc** [comment]
Please note that the third parameter to `store.findRecord(modelName, id, options)` is `options`, not query params. You can pass `{ adapterOptions: { /*custom things*/ } }` and they will be available to your adapter methods.

The reason for this _not_ being a plain object for query params is that we want to be able to extend the behavior of Ember Data in the future. First-class support for pagination, include and sorting are a couple of things being discussed.

We want to reserve the possibility of having something like `filter` or `include` as an option and make ED keep track of the value for refresh calls and so on.

**Comment by timmyomahony** [comment]
Another request for this feature. A common example is when you need to pass extra data to the server to annotate the result coming back. In my case, I want to annotate the distance to the returned object from the user's position (passed by query params)

**Comment by buschtoens** [comment]
With the advent of JSONAPI and the [`include`](http://jsonapi.org/format/#fetching-includes) request parameter, this is once again a much needed feature.

**Comment by buschtoens** [comment]
Could it be that this is actually already possible through the `adapterOptions`? It seems like they are already passed through to the [`buildQuery` method](https://github.com/emberjs/data/blob/v2.7.0/addon/adapters/rest.js#L1172-L1174).

**Comment by bmac** [comment]
While arbitrary query parameters are not supported include it is possible to specify the `include` parameter by doing `store.findRecord('post', 1, { include: 'comments' });`

**Comment by buschtoens** [comment]
Yup. Relevant RFC for anyone wondering. https://github.com/emberjs/rfcs/pull/99
And the [blog post](http://emberjs.com/blog/2016/05/03/ember-data-2-5-released.html#toc_code-ds-finder-include-code).

I should be more observant...
