### ISSUE TITLE
When belongsTo change, record does not set dirty.

### ISSUE THREAD

**Issue by franciscodelgadodev** [emberjs/data#1367]
I'm having a problem when a belongsTo relationship change. 

I have these models:

```javascript
App.User = DS.Model.extend({
  email: DS.attr('string')

  posts: DS.hasMany('post')
});

App.Post = DS.Model.extend({
  name: DS.attr('string')

  user: DS.belongsTo('user')
});
```

and the controller:

```javascript

get = Ember.get

App.PostController = Em.ObjectController.extend({
    userChanged:  function(){
      model = get(this, 'model')
      console.log(get(model, 'isDirty')); // => false
    }.observes('user')
});
```

When the user change in post it is not set dirty. 

I wonder if it is the expected behavior.

Thank you!

**Comment by lolmaus** [comment]
Learning Ember, stumbled upon the necessity in subj.

I resolved the necessity with a small mixin:

* https://github.com/lolmaus/ember-cli-stained-by-children/#stained-by-children
* https://github.com/lolmaus/ember-cli-stained-by-children/blob/0.x/addon/mixin.js

Do you think it's a feasible solution?

**Comment by bmac** [comment]
Re-opening because it looks like the issue this was merged into has been closed.

**Comment by Chun-Yang** [comment]
Hey @bmac , it seems this issue is being discussed at [emberjs/rfcs#21] (https://github.com/emberjs/rfcs/pull/21).

**Comment by igorT** [comment]
Tracking this under https://github.com/emberjs/data/issues/2122
