### ISSUE TITLE
Handle partial response in createRecord and updateRecord

### ISSUE THREAD

**Issue by jaaksarv** [emberjs/data#1438]
Embed Data requires that server API should return full record data in createRecord and updateRecord response, but some API-s only return id (or partial data). I know that it is bad practice, but some API-s are external and can not be changed. I propose that Ember Data should handle any subset of attributes returned by the server and merge them into existing record.

**Comment by wecc** [comment]
I'm pretty sure #2472 and #2649 have solved this issue. Would anyone be able to confirm?

ping @jaaksarv

**Comment by bmac** [comment]
Closing per @wecc's comment above. Feel free to reopen if this is still an issue.
