### ISSUE TITLE
belongsTo retrieved via "links" attribute cannot be accessed via get()

### ISSUE THREAD

**Issue by abobwhite** [emberjs/data#1443]
If I have a model "User" which has a relationship: `membership: DS.belongsTo('membership', {async :  true})` that is fetched from the links hash in the payload from the server, that membership is correctly fetched and loaded on to the User. That being said, saying `user.get('membership')` does not return the membership model. Instead, `user.get('membership').get('content')` is required to actually use the model...this seems like a bug to me. Am I missing something?

**Comment by toobulkeh** [comment]
For posterity, whatever happened to "async as default" as discussed above?

**Comment by pangratz** [comment]
@toobulkeh relationships are `async` by default in `ember-data` since `v2.x` (if I am not mistaken), see #3366.
