### ISSUE TITLE
Errors not removed when changing a belongsTo relationship

### ISSUE THREAD

**Issue by dmathieu** [emberjs/data#1472]
If at some point, the adapter returns an errors object, ember-data models go into the error state and store this errors values.

On string fields, the error is automatically cleared when the value changes, so the model can be updated by the user and resubmitted once everything has been fixed.

For belongsTo errors though, it seems errors aren't cleared.

I have the following model:

```
App.Study = DS.Model.extend
  title:          DS.attr('string')
  project:     DS.belongsTo('project')
```

And my template looks like the following:

```
{{view Ember.TextField valueBinding="model.title" required='true' class="form-control study-title" id="studyTitle" placeholder="Title"}}

{{view Ember.Select contentBinding="allProjects" valueBinding="model.project" id="studyEditProject"
        prompt="Select a project" class="form-control" optionValuePath="content" optionLabelPath="content.title"}}
```

When the server returns an error for both title and project, if I change the value of title, the error is properly cleared in the object. However, the project error never is.

I tried manually clearing the error in the model:

```
this.set('errors.project', null);
```

This does remove the error, but doesn't changes the state. So I still can't commit the record.

**Comment by pdougall1** [comment]
I'm having some trouble with this issue actually.
I'm happy to be removing the error manually but I'd rather not clear all the errors out when a single one is changed.  It would be nice to remove the errors as the user fixes each attribute.

However it looks like the method to remove errors piecemeal is deprecated.  Is there another way I don't know about? 
http://emberjs.com/api/data/classes/DS.Errors.html#method_remove
