### ISSUE TITLE
Relationships and dirtiness clarification

### ISSUE THREAD

**Issue by miguelcobain** [emberjs/data#1514]
I'm posting here after hours of frustation, so please bear with me. :)
What is the exact state of relationships and parent dirtiness right now?

I created this [SO question](http://stackoverflow.com/questions/19998523/how-do-i-make-the-parent-dirty-when-i-change-a-hasmany-belongsto-relationship-in) that explains what I need to achieve.

Right now, when I change a belongsTo or a hasMany relationship, the parent never gets dirty.
I know that by default the association is saved on the belongsTo/hasMany side, but I need them to be saved **in** the parent record.

*Why do I need this?*

In my case I have an `Order` model which can have many `Symptom` models. What I want to provide is an interface for users to **assign** `Symptoms` (multi select) to an `Order`. The symptoms already exist and are fetched from the server. Theoretically this is a ManyToMany relationship, but since I don't need to have orders on the symptom but rather symptoms on the order, I believe this is an unidirectional OneToMany?
`Symptom` doesn't "know" anything about `Order`. It just gets added to a hasMany relationship. The same happens with a belongsTo relationship!

I little code example, to illustrate what I'm trying to do.

```javascript
App.Order = DS.Model.extend({
  // Relationships
  priority : DS.belongsTo('priority'),
  symptoms : DS.hasMany('symptom',{async:true}),
});

App.Symptom = DS.Model.extend({
  // Properties
  name : DS.attr('string')
});

App.Priority = DS.Model.extend({
  // Properties
  name : DS.attr('string')
});
```

Now, when I change `priority` or `symptoms`, `Order` never gets dirty (`isDirty` is false).

I've already tried overriding the `DS.Store`'s `addRelationshipChangeFor` method, but with no success. Maybe that's the way to go?

How can this be achieved? Thank you.

**Comment by wecc** [comment]
Closing in favor of #1367.
