### ISSUE TITLE
Make full capabilities of DS.FixtureAdapter more evident in guides

### ISSUE THREAD

**Issue by markmhx** [emberjs/data#1524]
There's a page for the fixture adapter on the website:

http://emberjs.com/guides/models/the-fixture-adapter/

But:

- it's not referenced in any of the other "Models" guide pages and it doesn't have its own navigation item, so the only way to find it is apparently via Googling and links from sites like SO

- it only mentions and describes how the fixtures can be used to read/find data in lieu of a real server. It doesn't reveal or instruct how to take advantage of what IMO are its awesome full CRUD capabilities (reading and writing to a simulated server), which allows a developer to get going quickly with Ember without needing a live API in place.

BTW there is a lot more useful info about this in the API docs but not everyone rummages through there before building out new features.

I ended up custom building a bunch of server emulation code with mockjax before realizing this was available. I imagine other developers would love to learn about this, too.

I'd be happy to submit improvements to the guides here myself but I wanted to flag it first in case someone is already working on this area of the guides.

**Comment by bmac** [comment]
Closing this as Ember Data plans to deprecate the fixture adapter and the guides are being re-written with plans to remove the existing references to the fixture adapter.
