### ISSUE TITLE
DS.FixtureAdapter breaks `date` fields

### ISSUE THREAD

**Issue by ftokarev** [emberjs/data#1534]
When one creates and saves a record with a date attribute, this attribute will be of type string after the record is saved. 

Fiddle: http://jsfiddle.net/aVcT7/1/

The reason is the [mockJSON](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/adapters/fixture_adapter.js#L91) method, which delegates to a serializer, which turns Date objects into strings.

**Comment by givanse** [comment]
I like very much the idea of having a fixture adapter and I just encountered this problem, so bump.

**Comment by wecc** [comment]
The `FixtureAdapter` has been deprecated (#3091) and is no longer included in Ember Data by default.

The code for `FixtureAdapter` has been moved to [emberjs/ember-data-fixture-adapter](https://github.com/emberjs/ember-data-fixture-adapter/tree/master), please re-open in that repo if this is still an issue.
