### ISSUE TITLE
ActiveModelAdapter for Polymorphic Types Still Expects camelcase properties from response

### ISSUE THREAD

**Issue by eschan** [emberjs/data#1574]
From my testing, it looks like the ActiveModelAdapter still expects camelcasing for polymorphic references.

```javascript
App.Image = DS.Model.extend({
  imageable: DS.belongsTo('imageable', { polymorphic: true })
})

App.Imageable = DS.Model.extend({
  image: DS.belongsTo('image')
})

App.User = App.Imageable.extend({
  name: DS.attr('string')
})
```

If my server response looks like this.  The imageable property on Image.Imageable is undefined.

```json

images: [{
  id: 1,
  imageable_id: 1,
  imageable_type: 'User'
  url: 'http://test.com/photo.jpg'
}]

```

But when the server response looks like this.  The imageable property on Image.Imageable is populated with a User

```json
images: [{
  id: 1,
  imageable: 1,
  imageableType: 'User'
  url: 'http://test.com/photo.jpg'
}]

```

I understand that the changes for 1.0.0 beta 3 was to remove the underscore for the RESTAdaptor, but I also thought that underscores where supported for the ActiveModelAdapter.

I am using:
Ember Data : 1.0.0-beta.3

**Comment by bmac** [comment]
Looks like this was fixed by https://github.com/emberjs/data/pull/1662
