### ISSUE TITLE
failed destroyRecord and rollback (1.0.0-beta.5+canary.46eea851)

### ISSUE THREAD

**Issue by billxinli** [emberjs/data#1632]
Assume the following bit of code:

```
    post.destroyRecord()
      .then(function () {
        _this.transitionToRoute('posts.index');
      })
      .catch(function (error) {
        post.rollback();
        post.transitionTo('loaded.saved');
      });
```

Suppose if the server rejects the deletion for some reason, I would like to rollback the destroyRecord request. It seems `rollback()` does not call `transitionTo('loaded.saved')` and on subsequent retries to delete the record the following message appears: `Error: Attempted to handle event`deleteRecord`on <....:ember1270:2> while in state root.deleted.inFlight.`

Is this a desired behaviour?

cc @davidconnolly

**Comment by devinrhode2** [comment]
So I call destroyRecord, it successfully deletes on the server, but there's an error removing it from the local store, so the data is still displayed on the page. I get this error `You can only unload a record which is not inFlight.` I'm wondering how I can just set the record to be removed from the local store (Happen to be on Ember 2.13)

**Comment by Muniraj-Mallesh-E6144** [comment]
> So I call destroyRecord, it successfully deletes on the server, but there's an error removing it from the local store, so the data is still displayed on the page. I get this error `You can only unload a record which is not inFlight.` when calling `unloadRecord`. I'm wondering how I can just set the record to be inFlight so it can just be removed from the local store (Happen to be on Ember 2.13)

**Comment by Muniraj-Mallesh-E6144** [comment]
Facing same issure. But Below code worked for me

```
onDeleteTodo(todo) {
      const store = get(this, 'store')
      todo.destroyRecord().then(function () {
        store.unloadRecord(todo);
      }, function (response) { });
    }
```
