### ISSUE TITLE
Feature request: Adding a "type" property to DS.Model

### ISSUE THREAD

**Issue by consideRatio** [emberjs/data#1642]
I was in the process of doing a partial-template for three different Models, and ended up writing code like this for my models.

```
App.Doc = DS.Model.extend({
    type        : function() { return 'doc'; }.property(),
});
App.Collection = DS.Model.extend({
    type        : function() { return 'collection'; }.property(),
});
App.List = DS.Model.extend({
    type        : function() { return 'list'; }.property(),
});

```

I did this because i wanted my template to be able to contain generic code for each of these types:

```
{{#link-to item.type item}}a type.generic link!{{/link-to}}
```

mmum in irc helped me realize i should code it like this instead:

```
DS.Model.reopen({
  type: function() {
    return this.get('constructor.typeKey');
  }.property()
});
```

Question: What about including this straight up in the DS.Model?

PS: This would throw: Uncaught TypeError: Object function Object() { [native code] } has no method 'chain'
```
{{#link-to item.constructor.typeKey item}}a type.generic link!{{/link-to}}
```

**Comment by igorT** [comment]
Seems easy to alias `modelName` if you need it on the model, and that also means we don't have more blocked attribute names. Better docs should help a lot
