### ISSUE TITLE
[Proposal] Creation of suite of tests to be shared amongst adapters implementations

### ISSUE THREAD

**Issue by kurko** [emberjs/data#1655]
## Problem

* Official adapters (RESTAdapter, FixtureAdapter and AMS) don't share the same tests. With this, it's common for one to have bugs (due to lack of coverage), but not in another. If the same tests were used in all adapters, new bugs would be discovered automatically.
* Use cases covered by different test suites vary from adapter to adapter. So, bugs (e.g with `{async: true}` or "records get duplicated" etc) are reported for one adapter, but not for others. We end up with small hacks such as `adapter.reopen()` to fix edge-cases.
* Due to bad documentation, it's difficult to know what ED expects from an adapter in different occasions. Consider, for example, different expectations for `{async: true}` and `{async: false}` (such as one's relationship returns Promise vs no Promise), `{embedded: always}` and `{embedded: load}`, when records are not found, timeouts etc. Everyone has to think all over again for every implementation.
* When building a new adapter, you don't have a defined spec. It's such a pain to develop an adapter because you have no north to follow. What should be returned in edge cases is just unpredictable. I believe we have to fix this if we want a stable Ember Data 1.0.

## Solution

I propose we create an official suite of tests for adapters. It'd be located under Ember.js' account, such as `github.com/emberjs/adapter-specs`.

It would be used in the official adapters (FixtureAdapter, RESTAdapter and AMS), as well as in all others created by the community.

This would unite the efforts of the entire community and, in a natural way, would systematically drive the ED core to be bug free. The core team and collaborators would have a defined spec to follow. New behaviors established by the core team would be systematically spread to all adapters.

## How

Adapters should do what their name imply: have different implementations, but yield the same values.

Consider the following an example of a shared spec.

```js
function adapterSpecs() {
  // ...

  test('#find should include hasMany relationships', function() {
    expect(7);

    stop();
    store.find('person', 'p1').then(function(person) {
      equal(get(person, 'id'),   'p1',    'id is loaded correctly');
      equal(get(person, 'name'), 'Rambo', 'name is loaded correctly');
      return person.get('phones'); // 
    }).then(function(phones) {
      var phone1 = phones.get('firstObject'),
          phone2 = phones.get('lastObject');

      equal(get(phone1, 'id'),     'ph1', 'first phone id is loaded correctly');
      equal(get(phone1, 'number'), '11',  'first phone number is loaded correctly');
      equal(get(phone2, 'id'),     'ph2', 'second phone id is loaded correctly');
      equal(get(phone2, 'number'), '22',  'second phone number is loaded correctly');

      start();
    });
  });
}
```

This would be the code each adapter would have.

```js
module("Contracts/LocalStorageAdapter", {
  setup: function() {
    /** adapter specific setup, such as:
     *
     *    - set Ajax responses when RESTAdapter/Django adapter/etc
     *    - reset fixtures when FixtureAdapter
     *    - reset database when IndexedDBAdapter
     *    - reset localStorage when LSAdapter
     *    - etc
     */
  }
});

adapterSpecs(); // this would run the shared adapters.
```

Adapters shouldn't have reasons to need different specs one from another.

What do you guys think? This is a draft and your ideas are what's going to really drive this to be a solid solution. All I want is to give some order and predictability to the adapters land.

**Comment by runspired** [comment]
I agree this is a decent idea, but I believe this should be closed in favor of an RFC.

Said RFC should also detail the hooks a completely custom adapter/serializer MUST implement, and their signatures and expected returns.

cc @wecc

**Comment by wecc** [comment]
@runspired Agree, I would love to see an RFC about this 👍
