### ISSUE TITLE
findQuery fails on 204 no content

### ISSUE THREAD

**Issue by SingingBush** [emberjs/data#1732]
(moved over from https://github.com/emberjs/ember.js/issues/4303)

when doing: 
```
this.store.find('order', {customerId: customer.get('id')});
```
ember correctly calls my rest interface 
```
/api/v1/orders?customerId=12345
```

This is fine when there are results, however when there are none the rest api returns a 204 no content. This causes a problem as Ember expects an empty array and logs the following error:

The response from a findQuery must be an Array, not undefined

For the application I'm working on I can change my API to work around this but surely the findQuery should handle a 204 - it's a better response than returning an empty array

**Comment by bmac** [comment]
Closing this issue. Going forward Ember Data will follow JSON-API 1.0 http://jsonapi.org/format/ which says 
> A server MUST respond to a successful request to fetch an individual resource or resource collection with a 200 OK response.

> A server MUST respond to a successful request to fetch a resource collection with an array of resource objects or an empty array ([]) as the response document's primary data.

If you diverge from this spec you will likely need to extend and customize the adapter your application is using.

**Comment by svox1** [comment]
Good to known. Thank you!
