### ISSUE TITLE
Please add ID-less objects

### ISSUE THREAD

**Issue by wildchild** [emberjs/data#1763]
Nested ID-less records are nowadays, databases like mongo & couch still on the way. Please consider. My previous proposal https://github.com/emberjs/data/pull/1234#issuecomment-27305845

**Comment by bmac** [comment]
Hi @wildchild, I realize this is an old request but would you mind writing up your thoughts in a RFC format and submitting a pr to the https://github.com/emberjs/rfcs repo?
