### ISSUE TITLE
Polymorphism doesnt currently work with store.find.

### ISSUE THREAD

**Issue by kylenathan** [emberjs/data#1766]
```
App.Story = DS.Model.extend({
    user: DS.belongsTo('user');
    updated: DS.attr('number') 
});

App.PostStory = App.Story.extend({
   post: DS.belongsTo('post');
});

App.PhotoStory = App.Story.extend({
   photo: DS.belongsTo('photo');
});

```

Given the above models, the following returns models of the type App.Story regardless of the server response.
```
this.store.find('story', {userId: 1});
```

From what I can see this is because when defining polymorphic model relationships we have the {polymorphic: true} flag, but no such option exists for store.find (AFAIK).

I've hacked a quick, dirty fix that works by checking the data for the presence of a 'type' key and adjusting the type arg to recordForId accordingly, but that's not ideal. Should this be checking for a polymorphic flag in the args to store.find? Any other alternatives?

**Comment by igorT** [comment]
This will soon be possible to implement with #2991

**Comment by sly7-7** [comment]
I think this is implemented now, closing.

**Comment by kylenathan** [comment]
Not yet implemented but waiting on an RFC - https://github.com/emberjs/rfcs/pull/67
