### ISSUE TITLE
Embed hasMany relations on create with ActiveModelAdapter

### ISSUE THREAD

**Issue by dignoe** [emberjs/data#1768]
A common idiom in rails when creating a parent object and has_many objects at the same time is to use `accepts_nested_attributes_for`. It would be very beneficial to include this capability out of the box with the ActiveModelAdapter. From what I've tested and understand, the following changes would be needed:

- When calling `object.save()`, the serializer should embed the new hasMany objects in an array with `_attributes` added to the end of the key. The parent object ID (`contact_id`) and hasMany object IDs (`id`) should not be included.
``` json
contact: {
  first_name: "Minnie", 
  last_name: "Mouse", 
  addresses_attributes: [{
    street: "12 Mouse Ln",
    city: "Mouseville"
  }, ... ]
}
```
- The response from the server should adhere to the normal ActiveModelSerializer guidelines (sideloaded, underscored).
- The response from the server should be used to update the parent object and hasMany objects. Currently, using the `{embedded: 'always'}` trick results in duplicate hasMany objects after the response from the server comes back.

**Comment by wecc** [comment]
Closing this in favor of #1829.
