### ISSUE TITLE
Improvement ides for Ember Data

### ISSUE THREAD

**Issue by jaaksarv** [emberjs/data#1776]
I have worked with Ember-Data for almost a year for now. I’m using some third party API that I can’t change, so I have written a big custom adapter and lot of workarounds. I wanted to discuss few improvement ideas, before putting them to gitHub. Ideas are little bit of related to each other.

1. Singleton model. Sometimes there is a model that always has exactly one instance (at least on client side). Most used example of this is user session login=getSession (usually you only have exactly one active session). There are other cases too like give me some daily sales total number, give me total number of signed up users etc. Simple workaround is always to assign id 1 to this model in adapter. It would be better if there would be an option to define singleton model without having ID at all.

2. Add query to findById I have cases where I need to get one object with additional parameters. One use case is singleton object described in point 1 (sending username and password for getSession), but sometimes also for other queries. For one example I have getReport commend to get HTML report by report_id and I can pass some params there. Current workaround is doing findQuery and getting first object from the array, but it creates some extra work. I think it’s common use case and should be in Ember-Data. So findById(type, id) should be findById(type, id, query) or separate function findByIdAndQuery(type, id, query).

3. Defining findQuery params in a model and serialization for findQuery parameters There should be a way to define findQuery parameters in a model. Lets say I want to find some objects in a date range, then I want to define startDate and endDate. Object attribute is „date“, but „startDate“ and „endDate“ should be query parameters. For primitive data types it’s not a big problem, but complex types like Date, BigNumber etc need to go through serialization and transform mechanism. Currently I’m putting query parameters to the model together with model attributes, and improved findQuery code so all query parameters go through serialization process (currently this is not a case).

Ember-Data is a great library and makes things so much easier, hopefully it gets even better:)

**Comment by wecc** [comment]
@jaaksarv I think Ember Data 1.13/2.0 has solved most of these bullets.

> 1. Singleton model

There's still no concept of singleton models but you can request a single record without knowing it's ID by using `store.queryRecord()`. The Ember Data identity map requires type and id so there will always be a requirement on ID, but your server can return whatever as ID.

> 2. Add query to findById

The `store.queryRecord()` method should cover this too. If you know the ID however you can use `store.findRecord()` and by passing `adapterOptions` to your adapter you can extend the behavior.

> 3. Defining findQuery params in a model

I'm not exactly sure what this means. Would you be able to expand the use-case behind this?

**Comment by jaaksarv** [comment]
@wecc Ember-Data new versions have not changed much here. All these things still need workarounds.

1 . Singelton models are still very common in many API-s and Ember-Data should be able to handle them normally. Currently handling singelton models still requires a lot of hacking. Also sometimes it is not possible to change output of API as you suggest. I recommend something like this:

```
export default DS.Model.extend({
    isSingleton: true,
    name: DS.attr('string'),
    ....
});
```

2 . `store.findRecord` accepts `options` argument, but it's not passed to adapter. 

3 . There is often a need to find records by some parameters that are not part of the model. For example a model might have attribute `date`, but for finding records we need to provide date range as attributes `startDate` and `endDate`. API might want those dates in some strange format so we need to apply transformation to those dates, also by convention we are usually using camelCase inside Ember app, but API might want those attributes in name case `start_date` and `end_date. Currently we have to define 'startDate' and 'endDate' also part of the model to be able to benefit from Adapter transformations, but this will pollute all records in store also with those attributes that will be always NULL (as they are only used in query and never in response). I recommend that model definition should look like this:

```
export default DS.Model.extend({
    date: DS.attr('date'), // This is the real attribute
    startDate: DS.attr('date', {onlyQuery: true}), // This is only used in findMany query
    endDate: DS.attr('date', {onlyQuery: true}) // This is only used in findMany query
});
```

**Comment by bmac** [comment]
@jaaksarv do you need to save singleton models?

For point 2 there is a proposal for making it easier to pass a query into `findRecord` https://github.com/emberjs/rfcs/pull/99. This is how something like this can be achieve today using public apis https://github.com/emberjs/data/issues/3596#issuecomment-126604014.

For point 3. I think `store.query` should be able to handle this use case. It has no constraints on what properties can be passed into the `query` object.

**Comment by jaaksarv** [comment]
@bmac Yes. For exacmple some API-s might expose current user profile as singelton model without ID. Changing user profile is common use case where saving singleton model is needed.

Point 2 is not a very big problem.

For point 3, store.query parameters will not go through transformation process if they are not defined in the model. This means that I have to make API specific transformations in Route that is architecturally totally wrong. It should happen inside Adapter. I need those attributes to go through DateTransform and other conventions that are already defined in adapter.

**Comment by bmac** [comment]
Thanks for the clarification @jaaksarv.

**Comment by fivetanley** [comment]
Can you open these as separate issues? I think it'd be easier for us to track and give proper attention to. Sorry for not following up, we're triaging issues again.

**Comment by sandstrom** [comment]
Regarding singletons, our experience is that they are often a good fit for a service. Create a `SessionService` keeping track of that session model. That'll ensure you only have a single one.

Also, I don't think singletons for persisted models is common (I don't know of any server-side ORM that handles singleton models). Singleton classes are very common, but seldon for persisted models/records.
