### ISSUE TITLE
Add operation, request direction etc to customization hooks 

### ISSUE THREAD

**Issue by jaaksarv** [emberjs/data#1777]
I'm using EmberData with 3rd Party API that I cannot change. So I have lot of customization code in my custom Serializer and Adapter (extending RESTSerializer and RESTAdapter). Often I find myself in situation where I have not enough context information (operation type, request vs response, original query params) do to proper customization, so I will list some places where I had to add manually to get things working. 

1. normalizeId is missing params  "operation" as ID can be different for different operations and "recordId" as sometimes API is not returning ID for some operations.
2. keyForAttribute and keyForRelationship is missing params "operation" and "direction" (request vs response)
3. normalize needs "operation" and "recordId"
4. normalizePayload, normalizeAttributes and normalizeRelationships are missing "operation"
5. extractSingle and extractArray are sometimes missing "operation"
6. serializeAttribute, serializeBelongsTo, serializeHasMany is missing "operation"
7. buildURL is missing "operation"
8. Terms "operation" and "requestType" is mixed up in Ember-Data code. We should settle with one term and refactor code accordingly.

Maybe some generic "context" object should be used in customization hooks instead of passing different params. Context should include:
* Operation
* Direction (are we dealing with request or response)
* recordId for find, update, delete. 
* queryParams for findQuery
* Original record where available

**Comment by igorT** [comment]
@jaaksarv I think most of these have been addressed in the last year
