### ISSUE TITLE
FixtureAdapter.find() returns undefined when model not found

### ISSUE THREAD

**Issue by orospakr** [emberjs/data#1813]
Rather than throwing the appropriate model not found exception in the event of a request for a non-extant id, FixtureAdapter returns undefined which breaks an assertion in Store._find(), which is unhandleable and breaks the whole app. 

This is with ember-data 1.0.0beta7.  I'm using EAK if that matters.

```
Assertion Failed: You made a request for a mymodel with id fixture-78, but the adapter's response did not have any data
```

**Comment by wecc** [comment]
The `FixtureAdapter` has been deprecated (#3091) and is no longer included in Ember Data by default.

The code for `FixtureAdapter` has been moved to [emberjs/ember-data-fixture-adapter](https://github.com/emberjs/ember-data-fixture-adapter/tree/master), please re-open in that repo if this is still an issue.
