### ISSUE TITLE
Lifecycle of arrays returned by store queries

### ISSUE THREAD

**Issue by denisnazarov** [emberjs/data#1817]
Are arrays returned by `store.find` and `store.filter` cleaned up after they are no longer used in routes/templates/etc? What is a garbage collection strategy for this? If one uses a data-query heavy Ember application for a long period of time, the number of these arrays will continue to grow.

cc @stefanpenner

**Comment by igorT** [comment]
Store.find always returns the same array, and we are currently discussing various strategies for making filter not leak in 1.0. The main ideas for new apis were laid out in https://github.com/emberjs/rfcs/pull/23
