### ISSUE TITLE
[Bug] Sideloading relations (hasMany) on models not working!

### ISSUE THREAD

**Issue by steffenbrem** [emberjs/data#1834]
Hi,

**NOTE: I am using Ember App Kit**

Following the docs at emberjs.com you can sideload hasMany relations with one request. For me this is not working, I've tried almost every type of response and I keep getting the following error in Ember:

<code>Uncaught Error: Assertion Failed: You looked up the 'users' relationship on
'<(subclass of DS.Model):ember605:1>' but some of the associated records were not
loaded. Either make sure they are all loaded together with the parent record, or specify
t...<omitted>...`)</code>

This is the code I use to load the data:

```
// routes/customers.js
var customers = this.store.find('customer');
controller.set("customers", customers);
```

```
// templates/customers.hbs
{{#each customers}}
    <!-- this is working fine -->
    <p>{{firstName}}</p>

    <!-- Bad things happen! -->
    <p>Users:</p>
    {{#each users}}
        <p>Why am I getting errors here?</p>
    {{/each}}
{{/each}}
```

1) Scalar fields are working and I can print them out for every customer that is returned.
2) When I iterate over a relation, I receive errors.

This is the response Ember Data receives:

```
{
    "users": [
        {
            "id": 1,
            "username": "Steffen",
            "email": "email1@test.com"
        },
        {
            "id": 2,
            "username": "Krantenwijk",
            "email": "email2@test.com"
        },
        {
            "id": 3,
            "username": "Tan",
            "email": "email3@test.com"
        }
    ],
    "customers": [
        {
            "id": 1,
            "company": "Acme BV",
            "firstName": "Steffen",
            "lastName": "Brem",
            "lastModified": "2014-03-21T12:00:51+0100"
            "users": [
                1,
                2,
                3
            ]
        }
    ]
}
```

Is this a bug?

Steffen

**Comment by igorT** [comment]
@sly7-7 I am pretty sure we support both links and ids at the same time. Can you verify?

**Comment by sly7-7** [comment]
@igorT Sure, I will do that in the next couple of days

**Comment by sly7-7** [comment]
@igorT I've just added a passing test about that (here)[https://github.com/sly7-7/data/commit/f8624bf4acdb83797582d21e6d709b69a05c6017], so it seems like the error is gone, but I don't know if this behavior is expected or not. (The link takes precedence over the ids)

**Comment by steffenbrem** [comment]
@sly7-7 Hmm, but when you have the comments sideloaded, it should not hit the `links` too. Maybe it is good to test this too? Now you test both of them as async.

For example, if you let the api user decide if the `comments` needs to be loaded async or not, so the API can both return a `links` only or the comments `embedded` (but with the links in the response too!). In this case, `links` should not take precendence and should be ignored, right?

**Comment by igorT** [comment]
@sly7-7 seems like link shouldn't take precedence, can you investigate?

**Comment by sly7-7** [comment]
@igorT I think that even the has-many records are sideloaded, when we call for the relationship, [this code path](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/relationships/state/has-many.js#L171) is hit, and since the promise has not been define yet, the findLink will end up to hit the link.
Maybe we could add something like in https://github.com/emberjs/data/pull/3122 before triggering the request ?

**Comment by igorT** [comment]
@sly7-7 yes, I commented on that PR

**Comment by sly7-7** [comment]
seems like superseeded by https://github.com/emberjs/data/issues/3380.

Should we close this ?

**Comment by wecc** [comment]
Closing this in favor of #3380
