### ISSUE TITLE
Concurrency and Conditional Requests

### ISSUE THREAD

**Issue by sandstrom** [emberjs/data#1840]
When two clients work on the same object at the same time, and sends a `PUT` request they may overwrite each others data. One way to solve this is to use Etags and the `If-Match` header. If the object is stale the server may return `412` precondition failed to the client.

It would then be up to the client to handle the error, by saving a draft, merging with server state, or discard the client copy. A common etag is `model.id + model.updatedAt`.

---

The client-side part of this would be to define a standard property that holds the etag, perhaps `_etag` and then append this to any `PUT` requests back to the server.

Does this sound like a good idea? Perhaps there are better ways of solving this?

RELATED ISSUES
- https://github.com/json-api/json-api/issues/41
- https://github.com/rails-api/active_model_serializers/issues/532

REFERENCES
- http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html
- http://developer.netflix.com/docs/REST_API_Conventions [see under 'Resource Cache and Concurrency Control']
- http://blog.m.artins.net/restful-web-services-preventing-race-conditions/

**Comment by bmac** [comment]
Hi @sandstrom. Thanks for the request. I realize this is an old issue but would you mind writing up your thoughts in a RFC format and submitting it to the https://github.com/emberjs/rfcs repo?

**Comment by sandstrom** [comment]
No worries, it's kind of ancillary. @bmac do you think it's RFC-worthy? Perhaps just the fact that it has received no comments until now shows that this isn't something people are clamoring for :smile:

**Comment by bmac** [comment]
I suspect any sort of Etags aware adapter will end up being closely coupled with the backend's API. I also know form experience that how the client reacts to the 412 precondition failed error can be very application specific.

Those two reasons make me suspect that this would be a good feature to build into an adapter that one could plug into Ember Data instead of something that Ember Data supported out of the box.

**Comment by sandstrom** [comment]
The etag is entirely determined by the server. The client should only store it, and append with the PUT. Though I agree that the error handling may need coupling (unless it's standardized into json-api).

**Comment by wecc** [comment]
Kind of related https://github.com/json-api/json-api/pull/824

**Comment by artburkart** [comment]
Are there any examples of how to address metadata like the etag in ember data? I'm happy to adapt the serializer/adapter to my needs, but it's not entirely clear to me how I'd do it.

**Comment by sandstrom** [comment]
@artburkart You can override `headers` (http://emberjs.com/api/data/classes/DS.RESTAdapter.html#toc_headers-customization) or `ajax` (http://emberjs.com/api/data/classes/DS.RESTAdapter.html#method_ajax). Note that ajax is private, though I think there are (or will be made available) public methods to customize.

They use e.g. a `service` to associate models with their E-tags.

**Comment by artburkart** [comment]
@sandstrom - neat, thank you for the tips! That's exactly what I was looking for. It led me to [this strategy](http://discuss.emberjs.com/t/passing-header-information-to-rest-get-request-using-restadapter/4220/9), which I think will work for my needs :smile:

**Comment by wimleers** [comment]
#824  is related.

**Comment by runspired** [comment]
Closing as this is a purely adapter dependent behavior (so fully in the userland app code space). That said, the implementation of #7855 record links & meta support means that the e-tag can be store in the record's meta and utilized by the adapter from there instead of utilizing either a separate cache or an attr on the model for it.
