### ISSUE TITLE
hasMany record deletion attemps fail intermittently

### ISSUE THREAD

**Issue by ptmoy2** [emberjs/data#1846]
I want to delete a parent record with all its children records.  I call 'deleteRecord' followed by 'save' on the parent record.  EmberData sents a DELETE message to the server, which deletes the appropriate records in the DB (server always has correct information).  Now I want to delete the orphaned children from the store.  I tried using this code:

```
  var self = this;
  itemsToDelete.forEach (function(item){
        self.store.deleteRecord(item);
  });
```

When run, some records are deleted, while others triggered this error message:  "Cannot call method 'deleteRecord' of undefined."  But if I run the same code again, some of the records that triggered the error message in the prior run will get deleted without error.  So if I run this same code multiple times, eventually all the children records will get deleted without error.

'Item' should not come back as 'undefined' when I clearly see them in the Ember inspector.

My current work-around is just to hit the browser refresh button.  Server sends back the up-to-date information, which cleans up the store.

**Comment by Axxon** [comment]
Hi, i'm new to ember but i find a way to remove children of a parent in the data store:
in a router
```
    removeNode: function(node) {
      node.get('children').canonicalState.forEach(function(item) {
        item.destroyRecord();
      });
      node.destroyRecord();
    }
```
I work now with fixtures but is there a better way to do a cascade detete on a hasMany relationship or it's ok ?
