### ISSUE TITLE
Bulk operations support

### ISSUE THREAD

**Issue by andrewfan** [emberjs/data#1849]
From `TRANSITION.md` i understood that ember-data will handle bulk operations in future. In my project it is really critical to submit data to server in 1 http\s request. I take a look inside `store` code and looks like we can implement bulk operations right now. 

`store.flushPendingSave` (https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/store.js#L949) methods can separate records by record.type and then by operation type and call `_commit` (https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/store.js#L1761) function with new operation name f.e `createRecords`. 

after this the only thing we have to do is to add new methods to serializer that will call existing `extractArray` method and new methods to adapter.

should i start working on it, or my guesswork are incorrect?

**Comment by btecu** [comment]
@igorT any news on this?
I would really like batch PATCH or at least PUT operations.

**Comment by tim-evans** [comment]
I have a bug revolving around records needing to be committed in order. I would be delighted to use bulk commit when creating these records. (The use case is adding many items to an ordered list.)

**Comment by leejt489** [comment]
This is pretty important for apps with network latency.  Would like very much to see this integrated!

**Comment by SeyZ** [comment]
+1

**Comment by sparkrevolutions** [comment]
+1

**Comment by workmanw** [comment]
We actually do this now by implementing a custom adapter which models a [fork-join queue](https://en.wikipedia.org/wiki/Fork%E2%80%93join_queue). 

`<braindump>`

  The TL;DR; is that when `updateRecord` is called on the adapter we create a "work-item" and push it into a work queue. The "work-item" has the serialized record, the record type, the id and an instance of `Ember.RSVP.defer()`. As for the `updateRecord` we return the `defer.promise` (Defer is used because the API is more convenient). 

  Pushing things into a work queue starts a timer (we are using a 100ms duration). We also have a maximum batch size. Once the queue's timer expires or the max batch size is reached, the AJAX is fired. Once the AJAX returns it's results we loop back over the work item, matching the corresponding commit status with the proper workitem. We use that status to do `defer.resolve` or `defer.reject`.

  From an application perspective, we are just calling `record.save()` on a bunch of entities and the adapter will coalesces them properly.

  This approach is very naive in that is only batches entities of a common type and it doesn't allow the application to build it's own batch groups which could be beneficial if you wanted to have parallel transactions. 

`</braindump\>`

**Comment by kurko** [comment]
@workmanw any chance you can opensource that?

**Comment by Fenntasy** [comment]
@kurko 

If you're interested, I made somewhat of a mixin for my needs : 

```javascript
const BatchUpdatesAdapterMixin = {
  batchUpdatesTimeout: 50,
  batchUpdatesPathForType: function(type) {
    return this.pathForType(type);
  },
  batchUpdatesBuildUrl: function(type) {
    const container = this.batchUpdatesPathForType(type);
    return `${this.host}/${this.namespace}/${container}/update_all.json`;
  },
  _batchUpdates_handle: null,
  _batchUpdates_queue: [],
  _batchUpdates_resolvers: [],
  _batchUpdates(type) {
    const container = this.batchUpdatesPathForType(type);
    const records = {
      [container]: this._batchUpdates_queue
    };
    this._batchUpdates_queue = [];
    this.ajax(
      this.batchUpdatesBuildUrl(type),
      "PUT",
      {data: records}
    ).then(() => {
      this._batchUpdates_resolvers.forEach(p => p.resolve());
      this._batchUpdates_resolvers = [];
    }, () => {
      this._batchUpdates_resolvers.forEach(p => p.reject());
      this._batchUpdates_resolvers = [];
    });
  },
  updateRecord(store, type, snapshot) {
    const record = Object.assign(
      {},
      snapshot._attributes,
      { id: snapshot.id }
    );
    if (this._batchUpdates_handle) {
      clearTimeout(this._batchUpdates_handle);
    }
    this._batchUpdates_queue.push(record);
    this._batchUpdates_handle = setTimeout(
      this._batchUpdates.bind(this, type.modelName),
      this.batchUpdatesTimeout
    );

    return new Promise((resolve, reject) => {
      this._batchUpdates_resolvers.push({resolve, reject});
    });
  }
};
```
You can then use it as a mixing for your adapter and eventually overwrite `batchUpdatesTimeout`, `batchUpdatesPathForType` to change the name of your endpoint (which, for now, is the same as the container of your data that will be sent to the server), and `batchUpdatesBuildUrl` which define your endpoint url alltogether (I personnally end mine with `update_all.json`, you may want to change that to your liking).


I'm sure there's lot of improvements to be made but that seems to do the job and be similar to what @workmanw was suggesting.

**Comment by Fenntasy** [comment]
The only problem I have with this method so far is that the updated attributes of my model stay dirty. I don't know yet how to deal with that.

**Comment by workmanw** [comment]
Sorry @kurko I missed your ping months back :( . We've basically done exactly what @Fenntasy  has provided.

**Comment by kosmonaffft** [comment]
So, in which state bulk operations are now?

**Comment by perrierism** [comment]
FYI for anyone looking into using JSON API or Ember Data - it doesn't do this. It's not in the spec and there was never clear direction for it. Noticing that a question hangs for over a year without any answer from devs should also factor into "should I use this".

**Comment by dcyriller** [comment]
If not implemented in ember-data, this addon seems to provide the functionnality: https://github.com/Netflix/ember-batch-request (working with json:api spec)

**Comment by runspired** [comment]
Seeing as this is a customization specific to applications vs a general abstraction, I am going to close this ticket as something we do not intend to explicitly add as a feature.

That said, we do explicitly support your ability to create custom adapters suited to this purpose, and intend to continue improving primitives within `ember-data` to make implementing batch requests even simpler in the future.

One recently published RFC that will help in this nature is https://github.com/emberjs/rfcs/pull/403 which adds `Identifiers` which will enable users to solve race and ordering conditions prevalent in batch requests. Others are coming with improvements to overall management of the request lifecycle and improvements for communicating state updates to the store.
