### ISSUE TITLE
pushPayload doesn't update related object's relationships

### ISSUE THREAD

**Issue by ryanjm** [emberjs/data#1864]
Given the following model:

``` js
App.User = DS.Model.extend({
  name: DS.attr('string'),
  children: DS.hasMany('user', {inverse: 'parent'}),
  parent: DS.belongsTo('user', {inverse: 'children'})
});
```

When you do a `pushPayload` of users, the `belongsTo` relationship will update properly, but the `hasMany` of the related object does not.

Here is an example [jsbin](http://emberjs.jsbin.com/culaka/5/edit).

For example if you have user, "topUser", which has many `children`. If you do a `pushPayload` of objects whose parent's are "topUser", they will properly get that `belongsTo` relationship set, but `topUser` won't know about them through it's `children` relationship.

I'm not sure if this is related to #1862 or #1861.

**Comment by sebyx07** [comment]
```js
afterModel(model){
    const userId = model.user.get('id');
    Ember.$.getJSON(`${location.origin}/api/v3/users/${userId}/ads`).then((data) => {
      const adsIds = data.ads.map((ad) => {
        return ad.id;
      });

      data.users = [{id: userId, ads: adsIds}];
      this.store.pushPayload(data);
    });

    Ember.$.getJSON(`${location.origin}/api/v3/users/${userId}/staff_messages`).then((data) => {
      const staffMessagesIds = data.staffMessages.map((message) => {
        return message.id;
      });
      data.users = [{id: userId, staffMessages: staffMessagesIds}];
      this.store.pushPayload(data);
    });
  }
```

then u can use user.staffMessages for example
