### ISSUE TITLE
Ember Data DS.Store.filter always returns empty list

### ISSUE THREAD

**Issue by mlb5000** [emberjs/data#1872]
After upgrading from Ember Data 1.0.0.beta3 to 1.0.0.beta7 my previously working calls to DS.Store.filter are always returning an empty list. I can't find any mention in the release notes of such a fundamental change. What could be going wrong?

Even something as simple as this returns nothing:

``` javascript
var results = store.filter('myModel', function() { return true; });
results.get('length'); // is always 0
```

This despite the Ember Chrome extension reporting 153 of these in my data store.

**Comment by stefek99** [comment]
> feel free to amend the log

I find this type of answer ignorant.

*(no matter who is right)*

**Comment by stefek99** [comment]
The reason why I'm here is because of this thread - http://discuss.emberjs.com/t/why-does-store-createrecord-create-a-record-immediately/3161/9?u=stefek99 - I want to use ```filter``` as I don't want ```isNew``` records to be displayed.

### I managed to create a simple test case: http://plnkr.co/edit/RVICRVGAlHes0v2h97VU?p=preview that uses 3 versions:

Default (not desired):
```
      model: function() {
        return this.store.find('color');
      }
```

Filter (not working)
```
      model: function() {
        return this.store.filter('color', function(color) {
          return color.get("isNew") === false;
        })
      },

```

Hacky (thanks to @masom https://github.com/emberjs/data/issues/1872#issuecomment-63253265 )
```
      setupController: function(controller) {
          var _this = this;
          return this.get('store').find('color').then(function() {
              controller.set('model', _this.get('store').filter('color', function(color){
                  return color.get("isNew") === false;
              }));
          });
      }
```

---

---

---

![screenshot_061915_011151_pm](https://cloud.githubusercontent.com/assets/249703/8253148/c75a848c-1684-11e5-8d30-61483eee1d7b.jpg)

**Comment by wecc** [comment]
@stefek99 calling [store.filter](http://emberjs.com/api/data/classes/DS.Store.html#method_filter) without `query` only filters what's already in the store. In your example no data is present in the store (fixtures are defined but not "loaded"). Passing an empty object as `query` is the equivalent of doing a `store.findAll` before filtering.

See an example here: http://emberjs.jsbin.com/hupiqihogu/1/edit?html,js,output

I do not think calling `store.filter` with a `query` is supported by the FixtureAdapter though.

**Comment by stefek99** [comment]
@wecc Your example is awesome!

```
    return this.store.filter('author', {}, function(author) {
      return author.get('isNew') === false;
    });
```

Passing empty object - didn't know that!

And you are right with Fixture Adapter - it's not supported:
> Not implemented: You must override the DS.FixtureAdapter::queryFixtures method to support querying the fixture store.
(in general Fixture Adapter is no longer supported)

Speaking of which - I really like jQuery Mock Ajax - https://github.com/jakerella/jquery-mockjax - it uses familiar syntax, it feels like I'm already know how to use it :)

**Comment by rtm** [comment]
The page at http://emberjs.com/api/data/classes/DS.Store.html#method_filter mentions nothing about `filter` now returning a promise.

**Comment by timkellogg** [comment]
I was having similar problems and after combing through discourse's project I found a great example of filtering by attributes:  

https://github.com/discourse/discourse/blob/master/app/assets/javascripts/admin/routes/admin-groups-type.js.es6 

    model(params) {
      this.set("type", params.type);
      return Discourse.Group.findAll().then(function(groups) {
        return groups.filterBy("type", params.type);
      });
    },

Hope this helps.
