### ISSUE TITLE
Showing server side validation errors for a base object

### ISSUE THREAD

**Issue by daveroberts** [emberjs/data#1877]
Let's say I have an object Story with two properties: title and body.
I have validation rules for both the title and body, but I also have validation rules on the object as a whole, that don't apply to any one property directly.  For example, it's okay for a story to have a duplicate title, as long as the body is different.

In Rails, it's suggested that these base level validation errors are placed onto the "base" attribute (assuming your object doesn't have a base attribute already).  So the JavaScript errors that are returned look like this:

    {"errors":{"body":["can't be blank"],"title":["should begin with a capital letter"],"base":["A story with this same body and title already exist."]}}

On my Ember model for Story, if I do not add base as a property, Ember will not place the base validation errors onto my model object, and the base errors are not displayed on the page when the object is invalid.

JSBin without Base
http://jsbin.com/motuvaye/10/edit?html,js,output

1. Do not enter any information
2. Click create
3. Object is invalid.  Notice that the base error messages are not displayed on the form.
4. Fill out a new title and new body, the object changes from an invalid state to an uncommited state

JSBin with Base property:
http://jsbin.com/motuvaye/9/edit?html,js,output

If base is added as a property to the Ember model, the following behavior occurs:

1. Do not enter any information
2. Click create
3. Object is invalid.  The base error messages are displayed
4. Fill out a new title and new body.  The object does NOT change from invalid and thus an exception will be thrown by Ember if you try to save again.

The desired behavior would be to have a way to display this base error message, and let the object be saved after the user corrects both the title and body.

@alexspeller has made a pull request to allow saving objects in an invalid state.  This may help solve part of the problem at hand. https://github.com/emberjs/data/pull/1876

**Comment by bmac** [comment]
Fixed by #1984
