### ISSUE TITLE
Idea: add support for embeddable concepts

### ISSUE THREAD

**Issue by bakura10** [emberjs/data#1879]
Hi,

A lot of ORM (Doctrine 2 for PHP, Hibernate for Java...) has support for embeddable objects. This slightly differ from the terminology that seems to be used here for Rails.

An embeddable object is not a model (it cannot be saved, deleted... on its own). It would more extend from a DS.Embeddable (an Ember.Object with some more properties like validation...). This concept allows to create some objects to reduce duplicated code, while still saving those properties in the same table as the model it is embedded.

The constraint is that an embeddable object does not contain id, just properties, or associations (it's more or less like if all the properties of the embeddable were copy-pasted into the model it is used). Here is how it could be used in Ember-Data:

```js
App.Coupon = DS.Embeddable.extend({
    name: DS.attr('string'),
    percentOff: DS.attr('number')
});
```

And a model where this is injected:

```js
App.Subscription = DS.Model.extend({
    startedAt: DS.attr('date'),
    endedAt: DS.attr('date'),
    coupon: DS.embeds('coupon')
});
```

Here is an example of payload from server:

```json
{"subscription": {"id": 4, "startedAt": 2014-01-01, "endedAt": 2014-02-01, "coupon": {"name": "LAUNCH", "percentOff": 10}}
```

Of course, Ember-Data should handle all the normalization.

For those facing this issue, a possible workaround today is to simply add a simple ObjectTransform:

```js
App.ObjectTransform = DS.Transform.extend({
  deserialize: function(serialized) {
    if (serialized) {
      for (var key in serialized) {
        if (serialized.hasOwnProperty(key)) {
          var newKey = Ember.String.camelize(key);

          if (newKey !== key) {
            serialized[newKey] = serialized[key];
            delete serialized[key];
          }
        }
      }

      return serialized;
    }

    return null;
  },

  serialize: function(deserialized) {
    return deserialized;
  }
});
```

But it lacks things like validation, and does not take advantage of built-in normalization.

Thank you!

**Comment by asakusuma** [comment]
+1
This would be really useful for record metadata, like tracking information, that is specific to the model.

**Comment by igorT** [comment]
We are looking into integrating EDMF more closely post 1.0, but for now they are the solution to use
