### ISSUE TITLE
Response headers

### ISSUE THREAD

**Issue by jacoz** [emberjs/data#1880]
It'd be awesome and very very useful if I could access the response headers after saving a record via ember data.

After saving the model through save(), I get the promise but in its arguments I can only specify the data attribute, which is actually the saved record.

My content response is empty and some data are stored in my headers, according to REST specification!

**Comment by vasilakisfil** [comment]
This should be re-opened. There is no way to access the response headers in an easy way when fetching a record unless you do some crazy monkey patching in the adapter. It should be easy. My use-case is accessing max-age on Cache-Control header to figure out if I should re-fetch a record.

Related: https://github.com/emberjs/data/pull/4406

**Comment by fivetanley** [comment]
@vasilakisfil Does [handleResponse](http://emberjs.com/api/data/classes/DS.RESTAdapter.html#method_handleResponse) meet your use case?

**Comment by vasilakisfil** [comment]
@fivetanley `handleRequest` is hidden behind `_makeRequest` which is called by the public API method `findRecord`, which means that if I want to modify the record for some reason based on the headers, I have to monkey patch all 3 methods. Ideally I would like to have access to headers inside the `findRecord`. Athough I understand that headers is HTTP specific which might not appear inside other adapters (like localStorage), I feel such important data should be accessed easily by a public API somehow. What do you think ?
