### ISSUE TITLE
[feature request?] `hash` nomenclature & usage of JS Objects has hashes / associative arrays

### ISSUE THREAD

**Issue by JulianLeviston** [emberjs/data#1892]
I've noticed in several places in Ember Data that assertions are made, talking about Hashes.

One example:
https://github.com/emberjs/data/blob/ab589b32dbcb97640379b07be9d77388dc9d7cb8/packages/ember-data/lib/system/store.js#L1189

However, these aren't hashes, they're just regular javascript objects. This has mentally tripped me up a couple of times.

Should we either advocate the use of an actual hash instead?:
http://rick.measham.id.au/javascript/hash.htm

Or modify the assertions and references such that they refere to javascript objects rather than hashes? Calling them hashes feels very Ruby-ish to me and may make people think they're not just javascript objects.

One of the things that's bugging about using standard JS Objects is that you can't just say obj.keys or obj.values... maybe if Ember & Ember data made pervasive use of the aforementioned library when actually talking about and using hashes, it might make things easier?

**Comment by bmac** [comment]
Hi @JulianLeviston. I opened a small pr here https://github.com/emberjs/data/pull/2701 to replace some of the usage of hash in the documentation and the assertions with `object` to make it more clear that Ember Data is referring to JavaScript objects.

**Comment by JulianLeviston** [comment]
Thanks @bmac I'll close this issue.
