### ISSUE TITLE
[feature] "Has many through"-style associations (reified join table)

### ISSUE THREAD

**Issue by JulianLeviston** [emberjs/data#1912]
I have something in my codebase that looks roughly like the below.
An Item has many Tags, through taggings... (that's the "Rails" way of describing it). What I'd like is if Item's "tags association" and Tag's "items association" allowed adding but had some form of sensitivity for the fact that they were actually referenced through the tagging relationship, which is to say that adding a new tag would actually create a new item in Tagging as well.

I think this makes sense (at least I hope so, but if it doesn't ask and I'll clarify). Is this something Ember Data has planned, won't do, or possibly is open to? If so, I would absolutely love this feature. I realise it's probably a huge amount of work and it's also only really a problem that one encounters when one uses relational databases, but as most of us probably do, perhaps I'm not the only one who has this wish :) <3

      App.Item = DS.Model.extend({
        name: DS.attr("string"),
        taggings: DS.hasMany("tagging", inverse: "tag"),
        tags: DS.hasMany("tag", inverse: "item")
      });

  
      App.Tagging = DS.Model.extend({
        item: DS.belongsTo("item", inverse: "taggings"),
        tag: DS.belongsTo("tag", inverse: "taggings")
      });
  
      App.Tag = DS.Model.extend({
        name: DS.attr("string"),
        taggings: DS.hasMany("tagging", inverse: "tag"),
        items: DS.hasMany("item", :inverse: "tag")
      });

**Comment by JulianLeviston** [comment]
Doesn't seem to be enough interest, and I don't so much have this problem anymoe. Interested parties should open new issues if they still have them.

**Comment by Leooo** [comment]
If of interest, I created a small addon for a basic version of hasManyThrough: https://github.com/Leooo/ember-cli-has-many-through. This is my first public Addon so any feedback is welcome!
