### ISSUE TITLE
Model.reload does not refetch linked async relationships.

### ISSUE THREAD

**Issue by bmac** [emberjs/data#1913]
If I have a record with an async hasMany relationship for example the `events` property on the User model defined in the code below.

``` js
App.User = DS.Model.extend({
  name: DS.attr('string'),
  events: DS.hasMany('event', { async: true })
});

App.Event = DS.Model.extend({
  title: DS.attr('string'),
  date: DS.attr('date')
});
```

And my server returns a payload that contains a link to the endpoint containing the list of events associated with this user.

``` js
{
  id: 1,
  name: 'user1',
  links: {
    events: '/user/1/events'
  }
}
```

When I call `userModel.reload()` the list of events for this user is not re-requested.

I have put together a jsbin to demo my problem. In this jsbin the "Update Backend and Reload" button changes the state of the user record on my backend and reloads the user model. I had expected this to also re-request the list of events from the '/user/1/events' resource. The "Reset Relationships" is a hacky way to reset the events relation ship and causes the list of events to be re-requested. 
http://emberjs.jsbin.com/bemaxaqa/1/edit

I would like to get confirmation if this is a valid bug or if my assumption here is off base. Thanks.

**Comment by jackmatt2** [comment]
This is an issue for me also.

In my case the children may have been added to the colletion and therefore simply doing something like this does not work.

        	shipment.get('shipmentVehicles').forEach(function(shipmentVehicle) {
                        //The problem here is that there may be additional shipmentVehicles added on the server side.  The frontend will now know about them.
        		shipmentVehicle.reload();
        	});

I think we need a `reloadTree()` method or something.

**Comment by jagthedrummer** [comment]
+1 for `reloadTree()` or some other method to say "reload every single thing Ember knows about this model, including all relationships".

**Comment by HelloMihai** [comment]
+1 we have `reload` for a single item... but we need also a `reloadTree`.  We can have both.

**Comment by chandreshp** [comment]
+1 for reload of a single 'belongsTo' relationship.

**Comment by coreypmurphy** [comment]
+1 for reload of has_many relationships to avoid having to manually push those objects into the store.

**Comment by lalitindoria** [comment]
Do we have any method to `reload()` a collection of models? Running a `forEach` loop on the collections is not the best way though. Thoughts?

**Comment by sly7-7** [comment]
For now, we can manually reload a hasMany, also the hasMany (via link) is automatically reloaded if the link is updated.
The reload of a belongsTo is currently possible using the `ds.references` flag https://github.com/emberjs/data/blob/3e32efe8d6c0a062df9fd8314229a2575ee596a7/tests/integration/relationships/belongs-to-test.js#L1193.

I'm not sure we want to trigger an automatic reload of all record's associations (it could end up reloading the entire graph)

For reloading a collection of records (other than a hasMany), for now, I don't see other way than calling `records.invoke('reload')`. I'm not sure, but I guess if some of the records are of the same type, the calls will be coalesced into one single request.

@bmac Does this issue has been discussed recently ? Maybe it could be closed now ?

**Comment by bmac** [comment]
I created a new gist for this issue based on my original gist. And I was able to get it to reload using the reference api for the relationship in Ember Data 2.9.

http://emberjs.jsbin.com/naciqabafu/1/edit?html,js,console,output

**Comment by bmac** [comment]
I'm going to close this issue. It seems like there is a worry that automatically reloading all of the relationships on a record might lead to a performance problem in an app.

Today the best way to reload a relationship is to call `record.hasMany('relationshipName').reload()` or `record.belongsTo('relationshipName').reload()` to reload a specific relationship or use the following code to reload all relationships.

```js
record.eachRelationship(function(name, descriptor) {
  record[descriptor.kind](name).reload();
});
```

**Comment by johnunclesam** [comment]
Dear @bmac, do you think this is the better way?

And where? In `didTransition()` of the route maybe?

Before today I was thinking that Ember had a way similar to `reload: true`. Not this manually way.

What is the BEST BEST BEST way for performances?

My models are heavily edited and with many users coming in and out changing route.

**Comment by johnunclesam** [comment]
@bmac and the state of reloading? For spinner and so on?

**Comment by dilip96025** [comment]
for ember data 2.8.1
_model.get('comments').reload()_  not fetching data from server .

**Comment by rwwagner90** [comment]
@bmac you're the best! Really not sure why all the async relationships wouldn't reload when I force the parent model to reload. Seems like they should to me.

**Comment by snewcomer** [comment]
Just to put some writing down for others, one way to go about this is 


```
this.store.reloadRecord('my-model', id, { include: [...] });
```

If your api supports fetching relationships in a JSONAPI like format.

**Comment by pernambucano** [comment]
Unfortunately, I couldn't use `this.store.reload..` anymore, but you could use the method in the model itself: 

```javascript
model.reload({adapterOptions: { include: '...'}})
```

**Comment by runspired** [comment]
@pernambucano because `store.reloadRecord` has never been an API 🙈. knowing the app that @snewcomer works on, that app added a reloadRecord method to the store of its own and thats likely why he thought it was a method.

`findRecord` takes a reload option, or just use request-manager and stop caring about reload entirely :)

**Comment by pernambucano** [comment]
Thanks for the reply, @runspired ! I'll try using `findRecord` here, thanks! Btw, nothing will make me happier than using request-manager, but we're still on 4.x and trying to move forward (huge project). Is there a tutorial somewhere to implement the new features incrementally ? Thanks!
