### ISSUE TITLE
Unable to set defaultValue on belongsTo and hasMany

### ISSUE THREAD

**Issue by boazsender** [emberjs/data#1921]
In my case, I would like to set the defaultValue of a belongsTo relationship to the current user, but can think of other use cases for this.

**Comment by ChristopheBelpaire** [comment]
+1

**Comment by bmac** [comment]
Closing this issue. Now that Ember has Services they are a better place to encapsulating the logic around assigning a "default" relationship on a model.

**Comment by CostaRico** [comment]
@bmac Could u explain a little more detailed how to use services this way, please?

**Comment by elanclarkson** [comment]
+1 on getting a more detailed explanation from @bmac please.

**Comment by aexmachina** [comment]
I'd say @bmac is probably suggesting something along these lines:

```js
// app/services/foo.js
export default Ember.Service.extend({
  barFor(foo) {
    return foo.get('bar') || foo.set('bar', defaultValue())
  }
})
```
