### ISSUE TITLE
[BUG] createRecord with sideloaded data whose relationship links to the primary record

### ISSUE THREAD

**Issue by ppcano** [emberjs/data#1925]
It could be when creating a record, that the server response has a sideloaded records whose relationship is linked to the primary createRecord response.

An example  would be:

```js
    post: [{
      id: "1",
      name: 'Post name'
    }],
    comments: [{
      id: "1",
      name: "Dat Parley Letter",
      posts: [1]
    }]
```

In this case, `post` is the primary created record and `comments` are the sideloaded records where one `comment` has a `hasMany` relationship to the new `post` record.

Then, if we want to access  `comment.posts.firstObject.name`, so far the record is already saved locally into the store, it should not require to fetch the data from the server.

However, that seems not to work properly. There are two failing test in this [gist](https://gist.github.com/ppcano/0f0eb7f367ce2cbf7d2a) which show the case with either `hasMany` or `belongsTo` relationship.

```js
  var postName = "Rails is omasake";
 
  ajaxResponse({
    post: [{
      id: "1",
      name: postName
    }],
    comments: [{
      id: "1",
      name: "Dat Parley Letter",
      posts: [1]
    }]
  });
 
  Comment.reopen({ posts: DS.hasMany('post', {async: true}) });
 
  var post = store.createRecord('post', { name: postName });
  post.save().then(async(function(post) {
 
    equal(post.get('name'), postName, "post.name has assigned the expected value");
 
    var comment = store.getById('comment', 1);
    equal(comment.get('id'), "1", "sideloaded comments were saved into the store");
      
      // setup an error ajax response which should not be requested
      ajaxResponse({});
      comment.get('posts').then(async(function(posts) {
        post = posts.get('firstObject');
        equal(post.get('name'), postName, "post.name has assigned the expected value");
 
      }), function(error) {
         // It fails here, because the relationship is fetched
        ok(false, 'a created record which is present on a hasMany relationship of a sideloaded record should not be requested');
      });
 
  }));
```

It works well, when the same response is returned in a `find` or `record update`, these [tests](https://gist.github.com/ppcano/5f570793bbfd2c96b6a8) prove it.

Looking at the code, the tests passes if a `store.push` is performed at the `createRecord` promise resolution, but it makes 3 other tests fail.

```js
function _commit(adapter, store, operation, record) {
      .....
      payload = serializer.extract(store, type, adapterPayload, get(record, 'id'), operation);
      if (operation === 'createRecord') {
        store.push(type, payload);
      }
```

**Comment by igorT** [comment]
I believe this has been fixed for a while, please reopen if it's still an issue
