### ISSUE TITLE
Request a nonexistent data by id still push to the store using RestfulAdapter

### ISSUE THREAD

**Issue by luthur** [emberjs/data#1931]
While request a nonexistent data by id, the server return 404.

for example, GET `localhost:5002/#/products/some_id_not_exists` return 404

but the store still got one product with the id `some_id_not_exists`, the other fields are undefined.
![screenshot 2014-05-12 10 47 26](https://cloud.githubusercontent.com/assets/895300/2940409/d535b3b2-d97f-11e3-90fb-6dc66dbaf353.png)
![screenshot 2014-05-12 10 47 36](https://cloud.githubusercontent.com/assets/895300/2940410/d61d738c-d97f-11e3-825c-269f21753e4c.png)

**Comment by dgaus** [comment]
Is this supposed to be fixed on 1.0.0-beta.16.1? After a 404 I am getting phantom records which appear when doing store.all, but not via hasRecordForId

**Comment by jsangilve** [comment]
@dgaus @igorT @wecc  I'm also having the same problem with 1.0.0-beta.16.1. I think [#2467](https://github.com/emberjs/data/pull/2467) was merged into 1.0.0-beta.15, but after a 404 (rejected promise), the non-existent record stays in the model.

**Comment by igorT** [comment]
Does `references` branch solve this for you?
When you say `the non-existent record stays in the model.` what do you mean by that?

**Comment by jsangilve** [comment]
I mean, as detailed by the OP, if a route model's promise returns 404 (after requesting a nonexistent id), a nonexistent record is added to the store:

![screenshot_ember](https://cloud.githubusercontent.com/assets/3075974/7526328/9d2df328-f4de-11e4-8c0a-a4167aaf8890.png)

Then, If I go to a route that requests store.all, the nonexistent record is still there.

![screenshot_ember_2](https://cloud.githubusercontent.com/assets/3075974/7526400/42071816-f4df-11e4-9dd3-30dfce06d987.png)

I'll try with references branch.

**Comment by jsangilve** [comment]
@igorT `references` branch solves the problem. The record is unloaded once the promise is rejected. I also tried with 1.0.0-beta-1.5 and it also unloads the record, so I think the problem is a regression on 1.0.0-beta.1.6.x.

Should I open an issue?

**Comment by igorT** [comment]
Hoping to get `references` merged soon, does your app fully work with it?

**Comment by igorT** [comment]
@jsangilve do you want to write a failing test? That would be super helpful

**Comment by jsangilve** [comment]
@igorT 1.0.0-beta-1.7 successfully unload the record. It seems to be solved by #3043

**Comment by jsangilve** [comment]
`references` branch didn't have ```var record = store.getById(typeClass, id);``` within [_find method](https://github.com/emberjs/data/blob/references/packages/ember-data/lib/system/store/finders.js#L34) while 1.0.0-beta-1.6.x have it. That's the reason why I only had the bug with 1.6.x
