### ISSUE TITLE
Allow Store#pushPayload to delete records in store

### ISSUE THREAD

**Issue by nixpulvis** [emberjs/data#1945]
It would be nice to allow the deletion of records via a specially formatted message passed to `Store#pushPayload`. This would allow api designers to send a message for a record indicating it was deleted.

The use case for this for me at the moment is for integration with WebSockets. I'm building an adapter which calls `pushPayload` when it receives a message.

``` js
var _this = this;
var socket = new WebSocket('ws://' + window.location.host + '/api/v1/events/doors');
socket.onmessage = function(event) {
  _this.get('store').pushPayload('door', JSON.parse(event.data));
}
```

Maybe sending a message like

``` json
{
  "post": { "id": "1" },
  "_method": "delete"
}
```

Allowing this to also remove records would be awesome.

**Comment by pangratz** [comment]
I think this should definitely be supported by ember-data, but it might be a good idea to go through the process of RFC so the specific API can be fleshed out.

Closing this in favor of being discussed further at https://github.com/emberjs/rfcs

**Comment by nixpulvis** [comment]
This is how tickets get lost.

**Comment by pangratz** [comment]
@nixpulvis you're right! Reopening and will close once such a PR exists.

**Comment by stevesims** [comment]
This would indeed be very useful.
+1 from me!

**Comment by Asherlc** [comment]
Would something like this need to make it's way in to JSON API first?

**Comment by kbullaughey** [comment]
+1, I could use this too. Although I'm still stuck on the `ActiveModelAdapter` so it would be nice if it has across-the board support.

**Comment by pangratz** [comment]
@Asherlc, yep. Having such a functionality defined in JSON-API at first would definitely help this issue being moved forward.

https://github.com/json-api/json-api/issues/795#issuecomment-240385923 is a relevant comment.

**Comment by runspired** [comment]
https://github.com/emberjs/rfcs/pull/854 adds operations to the cache, all we need now is an addition to it for deletions :)

**Comment by runspired** [comment]
closing in favor of the above RFC adding it now
