### ISSUE TITLE
EmbeddedRecords with ActiveModelSerializer should append _attributes to keys

### ISSUE THREAD

**Issue by mehulkar** [emberjs/data#1950]
When I embed records for a Rails backend, it's usually because I'm using the `accepts_nested_attributes` feature of ActiveRecord. Rails expects that embedded records will come in with the key `[plural_model_name]_attributes`. 

Example:

```json
{
  "author": {
      "name": "Mark Twain",
      "books_attributes": [{"id": "1", "title": "Tom Sawyer"}]
  }
}
```

The solution would be to do modify `serializeHasMany` in EmbeddedRecordsMixin to check if the ActiveModelSerializer and append the string.

Opening up this issue to see if this an appropriate addition. To implement, I'm not sure how to check what type of the ActiveModelSerializer (or an extension of it) is being used.

**Comment by arnaldo2792** [comment]
May be I'm wrong, but I think that this issue should be solved by what you guys said in [#2138](https://github.com/emberjs/data/pull/2138)

**Comment by amedr** [comment]
Yeah I actually opted for other approaches which actually look cleaner and stop needing this.

**Comment by igorT** [comment]
This should now be much easier to customize, due to #2790 so you can customize the key in one direction. Maybe a change to AMS default(if we added keyForEmbeddedRecord?) or an addon would be great to get this out of the box.

**Comment by mmahalwy** [comment]
Sorry guys, but any solution to this?
