### ISSUE TITLE
createRecord parent with embedded records duplicates children

### ISSUE THREAD

**Issue by mehulkar** [emberjs/data#1951]
When I create an Author, and a child post, I have to manually push the new post to `author.get('posts')`. This is fine.

However, when I save the author with the post embedded as a hasMany relationship, and the post succeeds, Ember Data duplicates the post record with the response. 

Here's a JSFiddle to demonstrate: http://jsfiddle.net/mehulkar/jd6hV/

**Comment by benedikt** [comment]
It looks like this bug is back again: http://jsfiddle.net/1gy29p2q/
