### ISSUE TITLE
Cache a record when using Query Params in the call

### ISSUE THREAD

**Issue by fowl4** [emberjs/data#1966]
I have got this route retrieving 2 models:

```
App.PanelRoute = Ember.Route.extend({
    model: function(){
    var topologymin = this.store.find('topologymin');
    var metricmap = this.store.find('metricmap', { param1: 'something'})
    return Ember.RSVP.hash({
        topologymin: topologymin,
        metricmap: metricmap
    });
 });
```

This makes 2 calls:

```
http://localhost/topologymins
http://localhost/metricmaps?param1=something
```

If I go to another route and again to this one, it makes again the call with the params, not the other one:

```
http://localhost/metricmaps?param1=something
```

But, as its the same call to retrieve the same records I would like them to be cached like in the other call.

How does it know when to call the server and when its not necessary? Is it possible to do that?

My models:

```
App.Topologymin = DS.Model.extend({
siteGroup: DS.attr('string'),
sites: DS.hasMany('site')
});

App.Metricmap = DS.Model.extend({
    profile: DS.attr('string'),
    link: DS.attr('string'),
    services: DS.attr()
});
```

**Comment by wecc** [comment]
@igorT @bmac @fivetanley is caching `store.query[Record]` something we would like to do?

**Comment by bmac** [comment]
I suspect this is something we may want to explore in the future. However, for now I would like to see how people use the `shouldReload*` methods in their apps, as I suspect that they new `shouldReload*` methods would be introduced to support this feature.

**Comment by jamesdixon** [comment]
Has there been any more talk around this?

My API is adhering to the JSON API spec and therefore, we're making heavy use of the filtering, including, sorting, etc capabilities, which are query param based. It'd be great to be able to have ED cache some of these calls so they're not constantly repeated.

Keep up the great work!

**Comment by pangratz** [comment]
@jamesdixon unfortunately there hasn't been made any progress for cached queries. I've created a [`ember-twiddle`](https://ember-twiddle.com/538e9b1437442c2fd34f226c710777bd?fileTreeShown=false&numColumns=3&openFiles=controllers.application.js%2Cservices.store.js%2Ctemplates.application.hbs) with a simple implementation for a cached query. Maybe this helps until something similar is added to core...

**Comment by jamesdixon** [comment]
@pangratz much appreciated! I'll give it a go

**Comment by runspired** [comment]
FWIW, while we don't cache the "onion" (non-record) info returned with a query, you can easily add a cache for this on your own.  An advanced form of this looks like the following: https://github.com/hjdivad/ember-m3/blob/master/addon/query-cache.js

**Comment by runspired** [comment]
The request-manager RFC https://github.com/emberjs/rfcs/pull/860
and Cache RFC collectively solve this: https://github.com/emberjs/rfcs/pull/854
