### ISSUE TITLE
Document that we are not 100% compliant with JSON API

### ISSUE THREAD

**Issue by igorT** [emberjs/data#1988]
This throws people off. 
@aaronshaf thought that we were following their links convention and tried passing in:
```
model:{
  links:{
    children: [1,2,3]
  }
}
```
which didn't work.

**Comment by sarus** [comment]
Didn't see this mentioned in the main README (could have missed it of course), but is the intention for Ember-Data to be json-api compliant?  In other words, is the project working towards being 100% compliant with json-api (realizing of course that json-api itself hasn't hit 1.0).  I don't currently use ember-data but would like to be able to migrate to it at some point.  Our REST API is for the most part json-api compliant so I wanted to see how difficult the transition may or may not be.

Thanks!

**Comment by bmac** [comment]
Yes @sarus Ember Data hopes to be compliant with the json-api spec someday. The issue right now is as you pointed out that json-api is has not hit 1.0. When it hits that release and its is stable, Ember Data will begin the process of of supporting json-api.
