### ISSUE TITLE
No public API exists for reloading a hasMany

### ISSUE THREAD

**Issue by lukegalea** [emberjs/data#2002]
As far as I can tell, the only "public" way to reload a hasMany is something like this:

```
person.get('dogs').then( function(dogs) {
    return Promise.all(dogs.invoke("reload"));
}
```

That generates a ton of individual GETs, rather than a single "findMany" style request.

There's a hack posted at http://stackoverflow.com/questions/19983483/how-to-reload-an-async-with-links-hasmany-relationship

But it doesn't work for us because our API doesn't return links, just ids. It's expecting:

```
owner._data.links
```

Thanks in advance!

**Comment by embertutor** [comment]
@igorT I have an client model which has a hasMany relationship to the users model. I want to reload the users after some functionality. I have tried it doing 'client.get('users').reload()' with no luck. Help please
