### ISSUE TITLE
Expected model rollback behavior on RecordArray

### ISSUE THREAD

**Issue by vabatta** [emberjs/data#2005]
Which is the expected model rollback behavior when used on a RecordArray (or on a hasMany relationship)?
Assuming the following case:
*Colors (RecordArray)*
```colors: [{ id: 1, color: "blue" }, { id: 2, color: "red" }]```

*ColorsRoute.js*
```
actions:{
    del: function(item){
      console.log(this.modelFor('colors').indexOf(item)); //you can see that the index is different
      item.deleteRecord();
      item.save().then(null, function() {
        item.rollback();
      });
    }
  }
```
(complete JSbin [here](http://emberjs.jsbin.com/kijujifi/1/edit))
Assuming the case where the server rejects changes with a 422 response, this will cause the template on ColorsRoute to rerender due to the reorder caused by the rollback.

Is that behavior correct? Can I prevent it? (You cannot pass to rollback a index, and you cannot create a new record, I would be dirty).

**Comment by wecc** [comment]
I'm closing this since I think there's not really an issue here? Feel free to re-open if I'm mistaken.
