### ISSUE TITLE
Need Better Documentation for default RESTAdapter

### ISSUE THREAD

**Issue by ptmoy2** [emberjs/data#2020]
I found documentations for the RESTAdapter via these hyperlinks:

    http://emberjs.com/api/data/classes/DS.RESTAdapter.html
    http://emberjs.com/guides/models/the-rest-adapter

The 2nd hyperlink was not available via links found in 'Guides'.  I found it via a Google search (if this document is obsolete, it should be removed).  Neither document mentions what 'status' value the server is expected to return.  For a GET, one choice would be to return 404 for failure and 200 with content for success, which works.  'Create' and 'Update' are where I'm having the most problems.  When I 'create' a record, followed by 'save', I run into problems discussed in https://github.com/emberjs/data/issues/1829.  There are lots of advice on Stackoverflow, but I didn't see any from the core team; it's also unclear what version of Ember & EmberData these advice pertain to.

In my applications, I have full control on the server side to return whatever RESTAdapter needs, so want minimal customization on the Ember side.  It would be useful if there's a list of all possible messages default RESTAdapter can send, and the recommended server replies.

**Comment by igorT** [comment]
We will be migrating to JSON Api soon, and @bmac is working on the docs. I don't think there are specific issues to be addressed in this issue, so closing the issue, but this is an area we are actively working on.
