### ISSUE TITLE
store.adapterFor(type) returns incorrect adapter if nothing has been done with the type

### ISSUE THREAD

**Issue by jrhe** [emberjs/data#2032]
If you call store.adapterFor(type) before using the type it returns the application adapter rather than the adapter for that type.

adapterFor without using type :
http://jsbin.com/kajakohe/5/edit

adapterFor after using type:
http://jsbin.com/kajakohe/8/edit

**Comment by igorT** [comment]
`store.adapterFor` now takes strings and this originally was only an issue in unit tests so closing
