### ISSUE TITLE
Async many-to-many not making PUT request with all data

### ISSUE THREAD

**Issue by wbyoung** [emberjs/data#2055]
In a basic setup with the below models, I have a route to simply edit an employee's name. During the presentation of the view, there's no need to get the associated projects. Eventually, however, the user is able to save the `Employee` model.

```javascript
App.Employee = DS.Model.extend({
  name: DS.attr(),
  projects: DS.hasMany('project', { async: true })
});

App.Project = DS.Model.extend({
  name: DS.attr(),
  members: DS.hasMany('employee', { async: true })
});
```

When Ember generates the page, it obviously needs the information on the employee, so it does make a request to:

```javascript
// GET /api/employees/1/ is called by Ember Data
{
  "employee": {
    "id": 1,
    "name": "Whitney",
    "links": {
      "projects":"/api/v1/employees/1/projects"
    }
  }
}
```

It doesn't need the projects to show the user, so it never requests them.

```javascript
// GET /api/employees/1/projects is never called by Ember Data
{
  "projects": [{
    "id": 1,
    "name": "Learn Ember Data"
    "links": { "members": "/api/v1/projects/1/members" }
  }]
}
```

Eventually, the user decides to save, having changed the name. Ember sends a request back to the server, but is basically saying that the user has changed the employee to no longer have any projects now either.

```javascript
// PUT request to /api/employees/1
{
  "employee": {
    "name": "Whitney Young",
    "projects": [] // ← issue: the user did not change the projects!
  }
}
```

I would expect this to be a `PATCH` request with only the `name` present in the request. Alternatively, I would expect Ember Data to make a request for the projects before sending the `PUT` request so that it's able to make a proper `PUT` request & specify the projects.

I believe this could affect all relationship types.

I looked, but did not find anything that seemed related before opening this. Sorry if it's a duplicate.

**Comment by igorT** [comment]
I believe this is no longer the case, with the snapshots you will get the ids even if you never loaded the full records. Can you confirm @wecc?

**Comment by wecc** [comment]
Confirm. However in the example above the relationship is provided as a link, so no IDs are available making the relationship "unknown". Because of this, calling `snapshot.hasMany('projects')` should return `undefined` instead of an empty array. I'm unsure if the current serializers takes this into account. If the contents of a relationship is unknown (not provided or provided as a link only) it shouldn't be present in the payload at all imho.

**Comment by wbyoung** [comment]
Thanks for the updates.
