### ISSUE TITLE
Error when using Preloaded Models after App.reset() with QUnit

### ISSUE THREAD

**Issue by mutewinter** [emberjs/data#2063]
JSBin with Failing Test: http://emberjs.jsbin.com/lopabuwa/6/edit

I preload models into my data store using `store.push`. These models have a has many relationship to themselves. The app runs fine outside of test ([JSBin with app running without tests](http://emberjs.jsbin.com/yibuw/2/edit)). When run inside QUnit, the tests fail after `App.reset()` is called once. I receive the following error:

```
Error while loading route: Error: Assertion Failed: You looked up the 'relatedPosts' relationship on '<App.Post:ember345:1>' but some of the associated records were not loaded. Either make sure they are all loaded together with the parent record, or specify that the relationship is async (`DS.hasMany({ async: true })`)
```

These relationships are not async, all of the data is local and pushed into the store in an initializer.

If `App.reset()` is moved into QUnit's `setup` function, the error will occur on the first test ([JSBin demonstrating setup error](http://emberjs.jsbin.com/qeyon/2/edit)).

**Comment by wecc** [comment]
Since 1.13 original payloads shouldn't be mutated by any of the serializers anymore. Closing.
