### ISSUE TITLE
Can not add records of derived models to polymorphic hasMany

### ISSUE THREAD

**Issue by digitalplaywright** [emberjs/data#2065]
@jlauemoeller createed a gist of a problem with a polymorphic hasMany that I also bumped into today. The following gist demonstrates an assertion error when instances of derived classes are added to a hasMany relationship based on a common base class: https://gist.github.com/jlauemoeller/35a0bd6e0eb8441ee451

Is this a known limitation in ember data or are we doing something wrong? @Cyril-sf Do you have any input on this?

**Comment by jsamuel89** [comment]
Again i ran into this issue
 Ember              : 2.18.2
Ember Data         : 2.18.5
