### ISSUE TITLE
Preventing caching

### ISSUE THREAD

**Issue by jackmatt2** [emberjs/data#2085]
There needs to be a way to disable the store from loading form the cache.  I realise that the cache is a feature many people want but it is also a pain for people working with backends that can't push updates to the client easily. 

We are writing a large multi-user application and the data needs to be constantly up to date when records are retrieved.  Currently, it would require that all programmers manually reload models in the route before returning it.  People are going to forget (or not know) to do this and if we decide later down the track that we are able to support caching it would require us to locate every instance in our code where we are manually reloading, figure out if it is actually required and delete or leave it alone.

Maybe a new `DS.DontCacheMixin` could be added.  The `store` can check if the adapter contains this mixin, if it does, do a fresh request back to the server instead of retrieving from the cache.

``` javascript
export default DS.RESTAdapter.extend(DS.DontCacheMixin , {
    namespace: 'rest',
    host: 'http://localhost:4200'
});
```

**Comment by mithmatt** [comment]
I'm using ember-data 2.8.0, and I don't see the store.fetch feature in the documentation. 

I'm attempting to write a similar app as @jackmatt2 
Can anyone please point me in the right direction for achieving this with ember-data 2.8.0?

**Comment by bmac** [comment]
Hi @mithmatt with Ember Data 2.8.0 You can do `store.findRecord('type', { reload: true })` to get the same behavior as the old `store.fetch` api. Additionally adapters now have a `shouldReloadRecord` method that gets called for every `findRecord` request which can be used to programmatically decided if the store should return the record from the cache or fetch a fresh record (The `{ reload: true }` option works an an override for this check and forces a refresh).

**Comment by mithmatt** [comment]
@bmac My use case is a findAll on resource, query with query parameter fields=*
```
/api/v1/queries?fields=*
```
The doc does not mention option to pass query parameter for findAll. Any thoughts on this one?

**Comment by pangratz** [comment]
@mithmatt sounds like you want to use `store.query('query', { fields: "*" })`.

`store.findAll` should be used if you want an auto-updating array, which contains all the records of the specified type in the store. It will also trigger an API call so you get a chance to ask the adapter for all the records of the specified type:

```js
// trigger GET /records
let records = store.findAll("record");

records.get("length") === 0;

// later, when GET /records is finished and data is pushed into the store
records.get("length") === 123;

store.push({ data: { type: "record", id: 1 } });

records.get("length") === 124;
```

Also take a look at the API doc for [`findAll()`](http://emberjs.com/api/data/classes/DS.Store.html#method_findAll) and [`query()`](http://emberjs.com/api/data/classes/DS.Store.html#method_query) for further information or ask in the `-ember-data` channel in the `embercommunity` slack community.
