### ISSUE TITLE
Expected response from a save()

### ISSUE THREAD

**Issue by jefflage** [emberjs/data#2120]
I'm using the `EmbeddedRecordsMixin' with my subclass of `RESTSerializer`.  it is attempting to deserialize the response from a call to `save` and is failing if the response does not include at least on desearlizable payload (either a single or an array with one instance).

this requirement does not seem to exist if you do not use the `EmbeddedRecordsMixin`

i couldn't find any documentation on the expected/valid response form a `save` but given the discrepancy between using and not using `EmbeddedRecordsMixin`, I'm assuming this is a bug in the later.

**Comment by bmac** [comment]
Closing. @jefflage feel free to reopen if this is still an issue.

**Comment by nruth** [comment]
I just had this problem on 1.0.0-beta.18
this code in a rails controller:
```ruby
def update
   ...
  head :ok
end
```
causes

```
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at jQuery.parseJSON (http://localhost:4200/assets/vendor.js:8722:22)
    at ajaxConvert (http://localhost:4200/assets/vendor.js:9048:19)
    at done (http://localhost:4200/assets/vendor.js:9466:15)
    at XMLHttpRequest.jQuery.ajaxTransport.send.callback (http://localhost:4200/assets/vendor.js:9920:8)
```

But it was resolved by changing from 200 to 204 as suggested by @recipher .

```
def update
  ...
  head :no_content
end
```
