### ISSUE TITLE
Relationships: rollback and detecting changes

### ISSUE THREAD

**Issue by jugglinmike** [emberjs/data#2122]
`Model#save` handles persisting IDs for relationships. Other API concerning the synchronization state of a model, namely `Model#rollback` and `Model#isDirty`, do not.

This is particularly troublesome when dealing with `hasMany` relationships. In cases where elements have been added and/or removed from such a relationship (and prior to calling `model.save()`), I would expect `model.get('isDirty')` to return `true`, and `model.rollback()` to revert the changes.

If a maintainer can verify the validity of this expectation, I would be happy to contribute to an implementation. Please let me know!

**Comment by fivetanley** [comment]
closing as dup of emberjs/rfcs#21
