### ISSUE TITLE
Updating record & related records simultaneously does not clean related records.

### ISSUE THREAD

**Issue by danfinlay** [emberjs/data#2143]
Hi, using ember-data beta 8,

I have a model that I want to save some related models with at the same time.

I'm currently serializing those objects on the model in a way my server is respecting, but when the response comes back, no matter what `200` or `202` status code I send back, only the main model (the one who the `PUT` url belonged to) is set to clean.  All the related and updated models are left dirty, even when I'm including those updated records in the response.

What is the correct way to tell Ember to check if a response has cleaned some records?

**Comment by bmac** [comment]
@igorT Does ember data currently support this functionality?

**Comment by wecc** [comment]
I don't think this is supported. If models are `uncommitted` and new data is pushed to the store nothing will change except the canonical data for that model. A rollback would discard the changes and make the (updated) canonical data current.

**Comment by wecc** [comment]
Related: #2786

**Comment by sandstrom** [comment]
Possibly the same as this: https://github.com/emberjs/data/issues/1829
(I'm guessing that “Saving related models at the same time” refers to embedded records)

**Comment by runspired** [comment]
closing in favor of:

- #2786 for discussion of new state clearing dirty state
- #1540 for cleaning up isDirty 
- #1829 for discussion of perils of this approach during create
