### ISSUE TITLE
Unable to create record once find has been called

### ISSUE THREAD

**Issue by lacek** [emberjs/data#2150]
I am using FixtureAdapter for testing. I am trying to achieve the following:
- find in the store if a model with certain id 
- if such model exist, it is used for processing
- otherwise, a new model with that id is created for processing

        this.store.find('MyModel', { id: 'foo' }).then(function(model) {
            //do something with model
        }, function(reason) {
            var model = this.store.createRecord('MyModel', { id: 'foo' });
            //do something with model
        });

However, what I get is an error:
`Error: Assertion Failed: The id foo has already been used with another record of type MyModel.`

After tracing the Ember Data code, I found that:
* store.idToRecord is set after calling store.find:
    - [store.find with id=`foo`](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/store.js#L409)
    - [store.findById](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/store.js#L422)
    - [store.recordForId](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/store.js#L438)
    - [store.idToRecord['foo'] being set](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/store.js#L678)
* store.createRecord fails because store.idToRecord contains empty record of the id `foo`:
    - [store.createRecord with id=`foo`](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/store.js#L240)
    - [store.buildRecord](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/store.js#L240)
    - [assertion fails in store.buildRecord due to empty `foo` record in store.idToRecord created by store.find previously](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/store.js#L1473)

There is a similar issue in [emberFire](https://github.com/firebase/emberFire/issues/42). My temporary workaround is to call `store.dematerializeRecord` before `store.createRecord` and it is obviously undesirable because `store.dematerializeRecord` is non-public.

**Comment by kubz** [comment]
@oskarrough I got the same issue, look here : https://github.com/emberjs/data/issues/1523
and the method : @store.recordForId(type, properties.id)
