### ISSUE TITLE
findHasMany should be called instead of findMany if a has-many relationship is undefined

### ISSUE THREAD

**Issue by tomdale** [emberjs/data#2162]
Given a payload for a particular record, Ember Data currently resolves has-many relationships through the adapter using the following heuristic:
1. If the relationship is defined in the top-level `links` object, the store will call the adapter's `findHasMany` hook.
2. If the relationship is _not_ defined in the top-level `links` object, the store will call the adapter's `findMany` hook, passing it the array of IDs provided in the payload after removing the IDs of any records that are already loaded.

This behavior works well when the relationship is provided as a URL in the `links` object, or when the relationship is provided as an array of IDs.

However, there is a third, very common case, where the relationship should be populated by fetching a URL, but the URL is derived from information contained in the record, rather than being provided in the payload, hypermedia-style.

For example, imagine the following model:

``` js
// models/post.js
var attr = DS.attr,
    hasMany = DS.hasMany;
export default DS.Model.extend({
  title: attr(),
  body: attr(),
  comments: hasMany()
});
```

In this example, materializing the comments relationship by calling `post.get('comments')` should result in the client retrieving `/post/123/comments`. Thus, the server sends the following payload for the post with ID 123:

``` js
{
  "id": 123,
  "title": "Rails is Omakase",
  "body": "Trololol"
  // Note lack of comments relationship
}
```

This case is extraordinarily common (I ran into it when writing an app that uses the Portland public transit API, and Django's REST framework uses this approach), but currently getting this to work requires synthesizing a fake `links` entry in the serializer's `normalizePayload` hook and filling it with garbage data, which is a huge PITA.

@wycats and I think that it may be appropriate to add a third hook, which generates a URL for the relationship, and if that returns a value, the store will call `findHasMany` with the result. The current `links` behavior can be explained and implemented in terms of this new hook.

**Comment by psteininger** [comment]
@tomdale @igorT has this been resolved in 2.0+ ? I have a use case where the nested route produces aggregate level data, from a large dataset.
```
/widgets/:id/scores_by_month 
```

**Comment by amiel** [comment]
Having this would be super helpful for https://github.com/amiel/ember-data-url-templates, particularly to support the case @psteininger is talking about.

Is anyone else working on this? and is it still desired by others?

I'd be happy to give it a shot...

**Comment by amiel** [comment]
@tomdale It was mentioned to me by @igorT that you also wrote an RFC to this same affect? I can't find anything in emberjs/rfcs, but maybe I'm looking for the wrong keywords... If that sounds familiar, a link would be highly appreciated.

**Comment by amiel** [comment]
I have submitted an RFC for this: https://github.com/emberjs/rfcs/pull/266

**Comment by runspired** [comment]
With the refactor in #5410 it would be fairly trivial to call `findHasMany` instead of `findMany` in this particular case.

**Comment by runspired** [comment]
It's unfortunate we never fixed this; however, it's also now a moot point as the RequestManager gives users full control over fulfillment. https://github.com/emberjs/rfcs/pull/860
