### ISSUE TITLE
Unable to find inverse type if relationship isn't on abstract class

### ISSUE THREAD

**Issue by denisnazarov** [emberjs/data#2165]
Consider the following scenario:

```javascript
Widget = DS.Model.extend();

Video = Widget.extend();

Poll = Widget.extend({
  questions: DS.hasMany('question', {inverse: 'widget'})
});

Question = DS.Model.extend({
  widget: DS.belongsTo('widget', {polymorphic: true, inverse: 'questions'})
});

poll = this.store.createRecord('poll');

question = this.store.createRecord('question', {
  widget: poll
});
```

Ember Data attempts to find `questions` on the widget typeClass and fails to do so because it is defined only on Poll (which extends the Widget base class). There should be support for something like `getById(‘widget’, id).type` or finding by abstract type.

cc @krisselden @igorT

**Comment by igorT** [comment]
I think this is now solved by having support for polymorphic mixins. Please reopen if not
