### ISSUE TITLE
Clarify that metaForType is a Em.merge?

### ISSUE THREAD

**Issue by darkzeroman** [emberjs/data#2180]
Today I had to use [metaForType](https://github.com/emberjs/data/blob/v1.0.0-beta.8/packages/ember-data/lib/system/store.js#L1340) and it took me a while to look through the source code and realize that this method only merges metadata with the current metadata. I was trying to clear any metadata for a model, but couldn't!

I eventually wrote my own method in an subclassed store object, which is fine, but I'm wondering if the fact that metaForType merges with instead of overwrites the metadata should be made explicit in the documentation.

I can make a PR if you guys think it's a good idea, I'm also asking here if maybe there should be another method to clear metadata or there is some other way to do this I'm not aware of.

**Comment by bmac** [comment]
Hi @darkzeroman. Thanks for reporting this issue. @wecc has renamed `metaForType` to be `setMetadataFor` to make its intentions more clear. See https://github.com/emberjs/data/pull/2548
