### ISSUE TITLE
Chained Ember.computed.filterBy properties fail for updated records

### ISSUE THREAD

**Issue by webmonarch** [emberjs/data#2190]
I have a controller that has two `Ember.computed.filterBy` properties.  One depends on the output of the other.  I've noticed that when data gets pushed in the store what changes the value that there filters operate on, I get incorrect results.  If I manually code a computed property that delegates to `Enumerable.filterBy` it works as expected.

I've created a jsbin:

http://emberjs.jsbin.com/fesofu/5/edit

TO USE: click the tasks listed....I expect the two "Completed" counts to be the same.  The "manually" computed value is correct but the other is incorrect.

**Comment by RichardJohnn** [comment]
aye, I have been replacing Em.computed.filterBy uses with the hand written computed properties to work around this

**Comment by sly7-7** [comment]
I'm not sure if there is something to do in ember data for that case.
@igorT maybe we can close ?

**Comment by igorT** [comment]
I think this will be solved by the reduce computed removal in Ember

**Comment by wecc** [comment]
This seems fixed by https://github.com/emberjs/ember.js/pull/11513, closing.
