### ISSUE TITLE
model.data should be Object.create(null)

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/data#2206]
we have many hasOwnProperty checks, that honestly take many times more time then the cost of the function they are in

such as: https://github.com/emberjs/data/blob/master/packages/ember-data/lib/serializers/json_serializer.js#L114

with 1000 records with 5 attributes each, this takes 14ms (first page load) when removing the check it doesn't even register.

There are addition hasOwn checks on this object, i believe they are all safe to remove. Someone should sanity check this idea, but it does improve initializer serialization dramatically

**Comment by wecc** [comment]
@stefanpenner a lot of changes has been made in the serializers. I'd be happy to work on improving perf by removing hasOwnProperty checks where possible.

**Comment by sly7-7** [comment]
Maybe this one could be really reconsidered if https://github.com/emberjs/data/pull/4313 is merged

**Comment by bmac** [comment]
model.data is now an empty object. https://github.com/emberjs/data/blob/master/addon/-private/system/model/internal-model.js#L67
