### ISSUE TITLE
Regression - Polymorphic relationship to unrelated classes no longer supported

### ISSUE THREAD

**Issue by mrloop** [emberjs/data#2212]
Development builds of ember-data supported polymorphic relationship of classes which weren't subclasses of the same superclass. As of 1.0.0.beta.9 this is no longer the case.

[Working JSBin](http://emberjs.jsbin.com/cuxiva/3/edit) Using development build 1.0.0.beta.8
[Not working JSBin](http://emberjs.jsbin.com/visodu/1/edit) The same but using development build 1.0.0.beta.9

**Comment by jrhe** [comment]
If you do polymorphic relationships without inheriting from a base class of the polymorphic type, it breaks creation of new record as BelongsToRelationship.prototype.addRecord asserts that the class must be a subtype of the polymorphic relationships class.

https://github.com/emberjs/data/blob/48c02654e8a524b390d1a28975416ee73f912d9e/packages/ember-data/lib/system/relationships/state/belongs_to.js#L63


Probably mixing up my words and can't really figure out how to distil this down into a JS bin but hopefully it makes sense. I'll try and work something up.

**Comment by igorT** [comment]
@mrloop @lukegalea does https://github.com/emberjs/data/pull/2775 address your issues?

**Comment by mrloop** [comment]
@igorT I'll be able next few of days, cheers.

**Comment by mrloop** [comment]
Thanks @igorT this is working for me.

**Comment by igorT** [comment]
Awesome. Merged #2775
