### ISSUE TITLE
Better Errors for Overwriting Private Variables

### ISSUE THREAD

**Issue by flyswatter** [emberjs/data#2230]
I know Ember Data has private variables because I've stumbled into them occasionally and had trouble debugging what was wrong.

The most insanity-promoting private variable for me has been "currentState".  It's such a great variable name, I'm sure I'm not the only person who has overwritten it only to wonder what "Attempted to handle action while in state undefined" is suddenly coming from.

I don't know all of the other private variables, but if unclear errors are bugs (as I've often heard said in the Ember community), this would be a big series to fix.

**Comment by wecc** [comment]
Closing since #2886 has been merged.
