### ISSUE TITLE
set hasmany fails with read-only error in beta.9 and not in beta.7+canary...

### ISSUE THREAD

**Issue by benjamin79** [emberjs/data#2233]
trying to  controller.set('orders', orders); which is a hasmany throws the follwing error in beta.9:

"Cannot set read-only property "orders" on object". The strange thing is, it works in beta.7.. 

works (1.0.0-beta.7+canary.238bb5ce): 
http://jsbin.com/lenuwa/1/edit

doesn´t (1.0.0-beta.9):
http://jsbin.com/tapidu/1/edit

Any idea?

The difference between the two is just ember-data version

**Comment by jonnedeprez** [comment]
The new way of populating an async relation is by first 'opening' it:
```
controller.get('orders').then(function (result) {
  result.pushObjects(orders);
})
```
