### ISSUE TITLE
Embedded polymorphic assocation does not work

### ISSUE THREAD

**Issue by mxrguspxrt** [emberjs/data#2234]
I am using ActiveModelAdapter and ActiveModelSerializer.

1. It is searching KeyType not key_type
2. It gets full object in JSON response, is marked {polymorphic: true, async: false} but still makes REST GET /resource/id 
3. I think proper would be to keep type only in hash, not keyType - "key_type and key" work only for belongsTo/hasOne not with hasMany

**Comment by bmac** [comment]
Hi @mxrguspxrt. I'm not sure if you are still having that issue but if so do you mind sharing some example JSON that you are having trouble deserializing?

**Comment by mxrguspxrt** [comment]
I think this could be closed. Everything is fine now.

**Comment by bmac** [comment]
Thanks.
