### ISSUE TITLE
Fixture Adapter still mutates FIXTURES arrays on create/update/deleteRecord

### ISSUE THREAD

**Issue by fivetanley** [emberjs/data#2243]
This can lead to many gotchas while testing. As @bmac suggested we should probably have the Fixture Adapter account for this and manage state, and make some initializer that resets using the original array.

**Comment by wecc** [comment]
The `FixtureAdapter` has been deprecated (#3091) and is no longer included in Ember Data by default.

The code for `FixtureAdapter` has been moved to [emberjs/ember-data-fixture-adapter](https://github.com/emberjs/ember-data-fixture-adapter/tree/master), please re-open in that repo if this is still an issue.
