### ISSUE TITLE
wait for same/parent queries

### ISSUE THREAD

**Issue by patricklx** [emberjs/data#2256]
Could ember data wait for queries that are related?
For example i do a a query to */books* and a query to */books/15*.
Now ember data would wait for the first query to finish and check if book-15 is available. If not, it fires the second query.
Sometimes it can also happen that same queries are called at the same time. Ember data could only send one query and wait on one promise and not multiple.

**Comment by igorT** [comment]
This seems possible, but i think would add lots of complexity to the code and not sure how a good public api would look like to enable/disable. It would not be too hardy to implement a simple version, so I am happy to help create an addon for this, but not have it in core. Apologies for the late reply ;(
