### ISSUE TITLE
Handling erros for multiple models created with RSVP.hash

### ISSUE THREAD

**Issue by lessless** [emberjs/data#2259]
Hello! Currently there is an issue with handling errors in the routes which features several models created with  RSVP.hash.
Here you can see an question on SO regarding this subject http://stackoverflow.com/questions/23011039/handle-rsvp-hash-errors-from-model-hook
The error line is `Uncaught Error: Assertion Failed: Error: No model was found for 'error' `

**Comment by igorT** [comment]
This doesn't seem like an ED issue, the SO question seems succesfully answered now
