### ISSUE TITLE
DS.ArrayPromise#pushObject

### ISSUE THREAD

**Issue by mxrguspxrt** [emberjs/data#2264]
I don't know is it a real issue, but if my associations are not yet loaded and I try to push into them, i get an error "Uncaught Error: Assertion Failed: Error: Assertion Failed: The content property of DS.PromiseArray should be set before modifying it".

I have monkeypatched this issue for myself like this:

```js
DS.PromiseArray.reopen({
  pushObject: function(object) {
    this.then(function(content){
      content.pushObject(object)
    })
  }
})
```
Would not it be easier for developer not to worry what is going in background? If you think this could be a new feature, confirm that it is a good idea and I will create a pull request with tests & failing scenario also.

**Comment by fivetanley** [comment]
@pangratz has landed a feature called References, which provides an api for doing this. Check out the blog post: http://emberjs.com/blog/2016/01/12/ember-data-2-3-released.html#toc_code-ds-references-code
