### ISSUE TITLE
Determining existence of relationship without server query

### ISSUE THREAD

**Issue by sandstrom** [emberjs/data#2271]
Sometimes it's useful to determine if a relationship is present without querying the server. `child.get('mother')` will query the server if the mother isn't present.

This private API returns the answer without querying the server `!!child._relationships.mother.inverseRecord`.

**On knowledge of associated records**
Mostly, only the *1-side* in *N-1* and *1-1* relationships will know whether it's associated with another record (given how foreign keys are located). The *N-side* won't know without querying the server.

**Ways to provide this**
1. `child.isPresent('mother')` return true/false
2. `child.get('mother', { local: true })` return the record if it exists in store, otherwise null
3. `child.count('mother')` could return without querying the server for *1-side*, and could trigger a server request for the *N-side*. It's main usage would obviously be remote counting, but that way the API addition would be useful for more than probing for existence.
4. `eachRelationship` could be amended to provide info on relationship presence (similar to the current, private, API quoted above).

I think I like (3) the most, but depends on whether others think that's a useful addition. Thoughts?

**Comment by igorT** [comment]
https://github.com/emberjs/rfcs/pull/57 is aiming to address this

**Comment by pangratz** [comment]
I think this issue can be closed since an [initial implementation of references](https://github.com/emberjs/data/pull/3303) has been merged into `master`. Having the `ds-references` feature enabled, it can be checked if there is data for a relationship via `model.belongsTo("family").value() !== null` and `model.hasMany("children").value() !== null`.

**Comment by fivetanley** [comment]
Closing in favor of references!

**Comment by sandstrom** [comment]
*If anyone comes across this issue, have a look at https://github.com/emberjs/data/issues/7324 and https://github.com/emberjs/data/issues/7102.*

**Comment by runspired** [comment]
#7796 will add autotracking for this feature

**Comment by sandstrom** [comment]
awesome @runspired
