### ISSUE TITLE
Polymorphic with Embedded type key case sensitivity problems

### ISSUE THREAD

**Issue by asaf** [emberjs/data#2300]
Hey,

I have a polymorphic relation where the server returns a `type` property with capital letter value and no control over the server result, 

For example I have a model named 'person', while the type sent by the server is `PERSON`

`Store.modelFor` is invoked during serialization, so:

The line of code in `modelFor` method: 
`
factory.typeKey = factory.typeKey || this._normalizeTypeKey(key);
`

causes the factory of the `person` type to have a typeKey: `pERSON` (since `_normalizeTypeKey` camelize by default)

This causing later on problems because later on there are calls to container lookup for `model:pERSON` that doesn't resolve to any model type.

Here's the problematic piece of code:

```javascript
function extractEmbeddedHasManyPolymorphic(store, key, hash) {
...
      forEach(hash[key], function(data) {
        var typeKey = data.type;
        var embeddedSerializer = store.serializerFor(typeKey);
        var embeddedType = store.modelFor(typeKey);
        var primaryKey = get(embeddedSerializer, 'primaryKey');
...
```

By invoking `store.modelFor(typeKey);` the modelFor method creates a wrong `typeKey` for the person factory.

My `normalize` method is customized and would take care of the `type` property right but it doesn't have a chance since `store.serializerFor` is invoked first.

Suggestions how to solve this ?

Thanks.

**Comment by bmac** [comment]
Hi @asaf. Did you ever manage to come up with a solution for your problem?

I'd look at overriding the [extract method](http://emberjs.com/api/data/classes/DS.RESTSerializer.html#method_extract) of your application serializer to modify the response before any of the type specific serializers are invoked.

**Comment by igorT** [comment]
@bmac it might be easy to add a simple hook, but probably after we cleanup the serializers.

**Comment by wecc** [comment]
This should be easily solved by overriding `modelNameFromPayloadKey`, closing this.

Feel free to re-open if you're still experiencing issues with this.
