### ISSUE TITLE
Add ability to do not have id/key on EmbeddedRecordMixin serializer

### ISSUE THREAD

**Issue by vampolo** [emberjs/data#2306]
Hi

I've recently used ember-data and since i've the same model structure shared in many api requests i wanted it to be completely indipendent form different api calls. Even if i was using EmbeddedRecordMixin this was impossible because it still wants to serialize/deserialize an id/key.

I ended up with this solution to configure the serializer to generate a random id for embedded models and omit this id during serialization.

[blog article](http://vincenzo-ampolo.net/2014/09/21/ember-data-embedded-records-without-ids-ready-to-go/)
[noKeyMixin](https://gist.github.com/vampolo/8f8237cce2b8a52ab9d4)
[noKeyMixin example](https://gist.github.com/vampolo/a6d6063b612ad6f0584f)

Let me know if the feature is wanted upstream and i can work on a pull request.

**Comment by igorT** [comment]
The best way to handle this is to use https://github.com/lytics/ember-data.model-fragments or just simple DS.attrs. We are looking towards a tighter integration between model fragments and ED. The random id approach doesn't fully work, but thanks for the PR.
