### ISSUE TITLE
FixtureAdapter support for sideloading

### ISSUE THREAD

**Issue by aexmachina** [emberjs/data#2315]
Working with the FixtureAdapter is quite difficult when you use sideloading of related objects, because you need to handle pre-loading the related objects. It would be good if you could include these related objects in the fixture data and have them handled by the FixtureAdapter:

```
App.Post.reopenClass({
  FIXTURES: [
    { post: {...},
      comments: [{...}, {...}] },
    { post: {...},
      comments: [{...}, {...}] },
  ]
});
```

It's a bit more verbose, and it's a breaking change. An alternative would be to use a `_sideload` property in the hash to contain the hash of sideloaded records.

Thoughts?

**Comment by justin-hackin** [comment]
Oh my goodness, I've had soooo much problems trying to get FixtureAdapter to work properly with hasMany, lost about a day of working banging my head against it.  Here is a bin to illustrate my problem http://emberjs.jsbin.com/kuhifi/7/edit.    Can you PLEASE make it clear in the docs that FixtureAdapter should never be used with sideloading data .  Thank you for helping me understand my problem by creating a jsbin starting point with a ActiveModelAdapter, it helped me confirm the problem that I wrote about here : http://stackoverflow.com/questions/29216895/render-inside-each-ember-js

**Comment by wecc** [comment]
The `FixtureAdapter` has been deprecated (#3091) and is no longer included in Ember Data by default.

The code for `FixtureAdapter` has been moved to [emberjs/ember-data-fixture-adapter](https://github.com/emberjs/ember-data-fixture-adapter/tree/master), please re-open in that repo if this is still an issue.
