### ISSUE TITLE
`modelFor` may set an invalid typeKey

### ISSUE THREAD

**Issue by dfreeman** [emberjs/data#2318]
The change made in 14c5bba altered the observable behavior of `modelFor` slightly in beta 10. Prior to this change, the resolver was given a chance to normalize the type before the store transformed it, so a key like `'namespace.my-model'` would first become `'namespace/my-model'`, then ultimately become the typeKey `'namespace/myModel'`.

Now, because the resolver is no longer included in the process, the transformation goes straight to `'namespaceMyModel'`. Because the factory has already been looked up, the `modelFor` call will succeed, but subsequent lookups that rely on the typeKey set on the factory (such as the one in `Store#serialize`) will fail.

**Comment by jamesarosen** [comment]
I just ran into this with pod-style naming in Ember-CLI. I have `authentication/session/model.js` and `authentication/session/adapter.js`. When I do `this.store.fetch('authentication.session', 'current')`, Ember-Data finds the model, but `type.typeKey` is `authenticationSession`, so it can't find the adapter.

**Comment by stefanpenner** [comment]
> this.store.fetch('authentication.session',

although not the problem 'authentication.session' should likely be 'authentication/session'

I also believe the issue resides https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/store.js#L1779-L1781 ember-data should not be enforcing any naming conventions.

**Comment by mixonic** [comment]
@bantic made a spike to address this in https://github.com/bantic/data/pull/1.

**Comment by stefanpenner** [comment]
@mixonic nice, whats blocking?

**Comment by bmac** [comment]
ping @mixonic what's still needs to be done to get that spike ready for a pr?

**Comment by stefanpenner** [comment]
@bantic @mixonic ping?

this will likely fix https://github.com/ember-cli/ember-cli/issues/2906

**Comment by LeRiton** [comment]
Any chance to have an ETA for this entry?

**Comment by bmac** [comment]
@fivetanley has done some refactoring of `typeKey` recently which I believe fixes this issue. Feel free to reopen if its still a problem.
