### ISSUE TITLE
Async belongsTo unset after saving related model

### ISSUE THREAD

**Issue by johanneswuerbach** [emberjs/data#2341]
An assigned belongsTo relation is set to null after the related model is saved.

Failing jsbin:
http://emberjs.jsbin.com/gexidipefafa/1/edit

@sly7-7 I thought #2324 was the issue with hit in our app, but the problem only occurs after saving the related model.

**Comment by jaydev** [comment]
it appears that this issue was fixed with ember-data v1.0.0-beta.14

passing jsbin:
http://emberjs.jsbin.com/gicucuyaki/1/edit

**Comment by sly7-7** [comment]
@jaydev Thanks for the reminder, just tried the jsbin against canary, and it works.
