### ISSUE TITLE
store.find('model', ''); shouldn't query 'api/models/'

### ISSUE THREAD

**Issue by calvinmetcalf** [emberjs/data#2348]
basically if you do find with an empty string then it does a search for api/models/ with no id which leads to it downloading all of the models, [coerceID](https://github.com/emberjs/data/blob/2997e47034564aa803c1cacb0cf182ca36922fdc/packages/ember-data/lib/system/store.js#L57-L59) seems like it should be coercing empty strings to null.

**Comment by igorT** [comment]
Sorry for the late followup, but I am not sure what is the use case for passing an empty string? Would you expect it to immediately reject?

**Comment by raycohen** [comment]
The (unmerged) PR @stefanpenner recalls is https://github.com/emberjs/data/pull/518

I agree with @lukemelia's comment found in the discussion.

**Comment by igorT** [comment]
My bad. We deprecated the overloaded find but should still add the assert
