### ISSUE TITLE
clearing datastore

### ISSUE THREAD

**Issue by NickFranceschina** [emberjs/data#235]
is there a way to clear out the entire datastore?  say I have a user logged in, and they have built up some data.. then logout and login as someone else...  I need all of that data to be erased.   am I supposed to just set the original store == null and create a new one?  or is there a way to clear the cache?   if I try and blow it away and create a new one, does that screw with any of the existing observers that might be out there lingering?   not familiar with the cleanup process....

**Comment by runspired** [comment]
@wagenet This has come to be the trickiest part of working with Ember data on a mobile app.  When you do want to completely wipe data / reset the app, `App.reset()` (ember-cli) only has a globals version available, while other suggestions (such as a page refresh) don't work consistently within a cordova wrapper.  Now that there are `initializers` and `instance-initializers`, I'd think a method for tearing down the store entirely and creating a new instance should be easier to achieve.
