### ISSUE TITLE
start running tests against open source libraries / apps that use ember data

### ISSUE THREAD

**Issue by fivetanley** [emberjs/data#2372]
I'll expand on this when I can, but it'd be ncie if we even had occasional builds to let us know how we're keeping up with the ecosystem. Current libraries I can think of:
- Ember Data LocalStorage/IndexDB Adapter
- Think I saw a Hoodie somewhere
- Firebase?

cc @kurko

**Comment by igorT** [comment]
Seems related to the story or running addons against ember builds

**Comment by wecc** [comment]
Would https://github.com/kategengler/ember-try be kind of an inversed solution to this?

**Comment by kurko** [comment]
@wecc yes, "inverted". I think `ember-try` serves to test different versions for one particular lib. The issue proposes, though, a build for various libs. Perhaps if Ember released a lib that 3rd-parties could plugin and run their own tests, Ember wouldn't need to worry about unmaintained libs breaking. The "inverted" approach could be nicer.

**Comment by runspired** [comment]
@wecc @fivetanley candidate for closing?

I think this would be addressed by RFC for #1655 (which btw if no one tackles, I will be getting to in about a month)

**Comment by runspired** [comment]
Partially Addressed by https://github.com/travis-ci/travis-web/pull/877/files/946b864d921f9303f59f5d2c27e07bfd32ede2fc..c609892e27e15891a7087b9f49475bc3d9dcabe3

**Comment by kurko** [comment]
Sorry for the hiatus. I don't have bandwidth to work on this in the foreseeable future.
