### ISSUE TITLE
Saucelabs builds

### ISSUE THREAD

**Issue by fivetanley** [emberjs/data#2374]
Been a long time running, just need to dedicate some time to this. I've promised @mmun and @mixonic for a while so I'll probably be taking a day off from work this week to try and get a decent interim solution out until I can wrangle ember-secure-builder into a rails app and add some other niceties in it.

**Comment by igorT** [comment]
Is this still a thing or should we close?

**Comment by fivetanley** [comment]
closing in favor of https://github.com/emberjs/data/issues/2374

**Comment by pangratz** [comment]
To avoid an endless loop, this should be closed in favor of #3952 :wink:

**Comment by fivetanley** [comment]
lol
