### ISSUE TITLE
Async Polymorphic relations don't serialize correctly

### ISSUE THREAD

**Issue by aaronbhansen** [emberjs/data#2385]
If you have a belongsTo that is async and polymorphic, when it tries to serialize the model, it throws an error because it didn't unwrap the promise.

This can be seen here in the console assert. http://emberjs.jsbin.com/zisoba/8/edit

The quick solution locally was for me to unwrap it (https://gist.github.com/aaronbhansen/5a4bb73cf4c16b22b924), but that might be a good longterm fix.

**Comment by igorT** [comment]
SHould be fixed by #2623
