### ISSUE TITLE
beta-11 breaks hasMany (async) relationship

### ISSUE THREAD

**Issue by denzo** [emberjs/data#2391]
We have switched from beta-9 to beta-11 as the delete functionality was broken. However, the simple hasMany relationship is broken now. We noticed that it doesn't even try to make a call to the server (our hasMany are async).

I did some investigation and noticed that in beta-11 bindings are triggered before the model is materialised and then one more time after it is materialised. In beta-9 it is triggered only after it is materialised.

Our app breaks because of this as some of our computed properties rely on the existence of the properties, so when the binding is triggered before the model is materialised we get a runtime error.

I also noticed that when belongsTo relationship doesn't exist (as in it is not set) it used to be null. Now with beta-11 it is DS.PromiseObject with content set to null and isFulfilled set to true.

**Comment by igorT** [comment]
@denzo closing this for now, but please reopen if this is still an issue
