### ISSUE TITLE
Check ids of hasMany without fetching

### ISSUE THREAD

**Issue by thomassnielsen** [emberjs/data#2394]
In previous versions of Ember Data we've been able to do `this.get('data.posts')`, then get the IDs of each object (`data.id`). This would not fetch anything from the server. 

This doesn't seem to work as before in Ember Data beta 11 (and probably 10). It seems like the data under this.get('data') is no longer in sync. 

I'd guess this might be because of the new relation management. Is there a reliable way to make this work now? We need this for performance, as we can't always fetch every related object just to check if the relation is there.

**Comment by igorT** [comment]
https://github.com/emberjs/rfcs/pull/57 is aiming to address this

**Comment by aroberts** [comment]
Can anyone point to an equivalent solution in Ember Data 1.13? (1.13.11, specifically)

**Comment by wecc** [comment]
@aroberts although private I think the best way right now, until the work mentioned above is done, is to create a snapshot (`record._createSnapshot()`)

**Comment by aroberts** [comment]
I found another solution:

```javascript
  addresses: DS.hasMany('address', { async: true, inverse: null } ),
  address_ids: DS.attr(),
```
This is with the ActiveModel adapter.

Not sure how long this will continue to work, but it looks like if both properties are there, the normalize process will allow both of them to be populated.

**Comment by pangratz** [comment]
I think this issue can be closed since an [initial implementation of references](https://github.com/emberjs/data/pull/3303) has been merged into `master`. Having the `ds-references` feature enabled, the ids of a relationship can be accessed via `var childrenIds = model.hasMany("children").ids()`.

**Comment by fivetanley** [comment]
Confirm, references are the way to go!
