### ISSUE TITLE
Add support for STI

### ISSUE THREAD

**Issue by tim-evans** [emberjs/data#2407]
Having support to mark relations as having a Single Table Inheritance model would be nice.

We have STI in our app, and see performance hits because we have to fetch the base class (Person) _and_ the implementing class (Client) for ED to understand what's going on.

Any thoughts / ideas on this?

**Comment by tim-evans** [comment]
Any updates on this? I recently ran into a bug that messed up data due to the way I'm trying to hack around ED not supporting this

**Comment by leifcr** [comment]
I'm currently trying to get this working with Emberfire (https://github.com/firebase/emberfire/issues/245),  but it would be better if it was part of ED.

**Comment by tim-evans** [comment]
https://github.com/jquery/qunit/issues/632

**Comment by fivetanley** [comment]
@tim-evans What is the path forward here?

**Comment by tim-evans** [comment]
I think the path forward is to either provide the ability to mark models as STI or implicitly use STI modeling if models are inherited. One way to do this is mixins, another inheritance. I think Mixins may be the most flexible, since some backend stores may support multiple inheritance. Anyways, I'd like to be able to fetch a model of a generic type and be returned the specific type of that object instead of ED going back to the server to fetch it. (It should obviously do that if it's not in the store).

Complications include:
- Mismatched types. Fetching a model of type `Event` and getting a return type of `Workshop` may be weird to handle. The server would be correct in this case; it's just specifying the sub-type. Validations could be done on the fly for this, checking the STI tree for the model to see if they are in the same tree. If so :+1:.
- Users expecting old behavior. Not sure about this one, as I feel most users assume this is the default, but this will definitely break what has happened previously.

**Comment by leifcr** [comment]
See https://github.com/emberjs/data/issues/2407 and https://github.com/firebase/emberfire/issues/245#issuecomment-140336504

It's probably better to wait for ED to implement sti properly first.

**Comment by leifcr** [comment]
Would this be the same as proposed in this rfc https://github.com/emberjs/rfcs/pull/67

**Comment by tim-evans** [comment]
Yes and no. Same desired output, different approach. STI is a subset of polymorphism IMO. The STI support is more "magical" than the polymorphic approach. I'm fine with approach laid out in the RFC, but it doesn't address systems that use STI in a way that maps well ORM-wise. A top-level mixin on the root model may very well be "good enough", where it forces relationships with the given type to be polymorphic.

So, I think we can build first-level STI support on top of the proposals in the RFC. I'm afraid of some push-back of additional complexity from core with an STI mixin, but I think in the end, it's worth it.

**Comment by navels** [comment]
This was closed as completed . . . can someone summarize what support there actually is for STI?

**Comment by runspired** [comment]
@navels use the identifiers API for properly merging identities (see rfc, tests, or docs for the various methods https://api.emberjs.com/ember-data/4.7/functions/@ember-data%2Fstore/setIdentifierGenerationMethod)

Use the explicit polymorphic relationship APIs for polymorphic relationships: see https://rfcs.emberjs.com/id/0793-polymporphic-relations-without-inheritance

**Comment by navels** [comment]
thanks!
