### ISSUE TITLE
It seems possible for destroyed records to get into live arrays

### ISSUE THREAD

**Issue by igorT** [emberjs/data#2424]
This shouldn't be happening, need to investigate

**Comment by andorov** [comment]
I see this with Ember 1.9.1 / Ember Data v1.0.0-beta.14.1

if User hasMany Posts -
destroy (or unload) existing Post #1
create Post #2
*ok here
save Post #2
*User.posts now includes Post #1 and #2.  #1 has the state 'root.deleted.saved'

if the same record is unloaded then pushed onto the store it will appear twice

Just tested 1.0.0-beta.15-canary and I see it there as well

**Comment by quaertym** [comment]
I think this was working in  `v1.0.0-beta.12`.

**Comment by andorov** [comment]
@quaertym - just tested `v1.0.0-beta.12`.  confirmed this was not a bug there.

**Comment by quaertym** [comment]
@andorov We could not upgrade to beta.14 because of this.

**Comment by igorT** [comment]
I believe this was fixed, is this still an issue for you @quaertym @andorov ?

**Comment by quaertym** [comment]
No, it is fixed.
