### ISSUE TITLE
[rfcs] - open an RFC Memory/Resource Management (GC, etc)

### ISSUE THREAD

**Issue by fivetanley** [emberjs/data#2430]
Leaving this here for @igorT, can fill in some details later or Igor can. Just jotting down notes from the meeting as a reminder for later.

(from the October 29th, 2014 Meeting)

- Server side deletes
- Length undefined
- Don't automatically unload records you don't have this problem?
- Current work around - manually delete records
- Configurable in an elegant way

**Comment by fivetanley** [comment]
I think the last time @stefanpenner and I talked about this we came up with a couple of suggestions, one of which was returning some kind of event emitter that you could call `subscribe/unsubscribe` on. While annoying, without proper WeakMap support I don't think this is implementable without that. This may be worth bringing up at a face to face, but closing this issue for now due to staleness.

**Comment by stefanpenner** [comment]
> one of which was returning some kind of event emitter that you could call subscribe/unsubscribe on.

I don't believe we talked about ^^, but rather we spoke about multiple identity maps (to help with the record array / collection / query case).
