### ISSUE TITLE
how about provide array like api to make store possible provide a sorted hasMany as return? 

### ISSUE THREAD

**Issue by feitian124** [emberjs/data#2453]
the array has `pushOjbect(s)`, `unshiftObject(s)` to make it easy for us to mantain the array ordered.
but the store only have push, pushMany and pushPayload.

do you think it is possible and meaningful to add unshift style api to store also? thank you.

**Comment by wecc** [comment]
Has this been solved? Can this issue be closed?

**Comment by feitian124** [comment]
sure. we are maintan an array ourselfs now
