### ISSUE TITLE
Feature Request: Implement rails like dependent destroy for associations

### ISSUE THREAD

**Issue by saygun** [emberjs/data#2465]
When you destroy a record, associations still remain in the store which is not desired in my opinion.

Syntax could be like: 
```javascript
var Todolist = DS.Model.extend({
  creator: DS.belongsTo('user', { async: true});
  todos: DS.hasMany('todo', { async: true, dependent: 'destroy' });
});
```

If you are interested I can work on a PR.

**Comment by saygun** [comment]
@igorT @bmac what do you think about this? Is it worth implementing?

**Comment by bmac** [comment]
@saygun This sounds like a good feature to try and test out as a plugin to Ember Data.

**Comment by saygun** [comment]
@bmac What do you mean by plugin exactly?

**Comment by bmac** [comment]
Something along the lines of https://github.com/pixelhandler/ember-data-extensions or https://github.com/lolmaus/ember-cli-stained-by-children that is prototyped outside Ember Data to figure out API. Once it stabilizes we could bring it into Ember Data via a formal RFC.

**Comment by bmac** [comment]
Hi @saygun. I'm going to close this issue for now. I still think this this feature is still something the Ember Data team would like to see experimented with in an addon. Once it sees common use in an addon then it may make sense for Ember Data to "Pave the cowpaths" and incorporate the functionality into Ember Data.

Feel free to reopen if you disagree.
