### ISSUE TITLE
encodeURIComponent ids is difficult to handle when id contains /

### ISSUE THREAD

**Issue by taras** [emberjs/data#2480]
In beta.11, the ids are being run through encodeURIComponent for the purpose of encoding array of ids. This introduced a problem in our app because our ids have / in them which gets encoded to %2F. It's difficult to handle this scenario in Grape which we use for our Rails API. 

It might be more appropriate to only encodeURIComponent ids when they are arrays and not strings.

**Comment by igorT** [comment]
Supporting this is actually somewhat of a security concern, and it seems like if you want to do this you can just turn `%2F` back into '/' in your buildURL. I don't think we will be reverting this.
