### ISSUE TITLE
Saving with EmbeddedRecordsMixin does not update related models dirty attributes

### ISSUE THREAD

**Issue by DEfusion** [emberjs/data#2487]
I created a demo (http://jsbin.com/zejala/6/edit?js,output) simulating saving `hasMany` related models via `DS.EmbeddedRecordsMixin` and Rails' `accepts_nested_attributes_for`.

No matter what way the serializer is configured in Ember dirty attributes of the relationships records are not updated with those from the response, non dirty attributes _are_ updated though.

The only workaround I have found is to manually go through and mark them individually as `willCommit` and then `didCommit` by overriding `save` on the model - I tried doing this in the serializer for better encapsulation but couldn't get it to work.

If I've specified `serialize: 'records'` for my serializer when using `EmbeddedRecordsMixin` I would expect those records to be automatically set as saving/saved etc. along with the parent according to the normal save flow.

**Comment by lolmaus** [comment]
I ran into this issue, here's my story: http://stackoverflow.com/questions/28408274/how-to-update-child-records-in-the-store-when-parent-record-is-saved

The demo in top post broke due to some `<script>` tags linking to latest versions and others linking to fixed versions. Here's a fixed one: http://jsbin.com/finax/1/edit?html,js,output

So, are there any updates on this one?

Also, is the manual method of updating child records kindly provided by @DEfusion an optimal one? It is so low-level that i'm kinda worried to use it. Is there a less hacky way?

**Comment by lolmaus** [comment]
I've resolved the issue for me and the solution as an Ember CLI addon: https://github.com/lolmaus/ember-cli-stained-by-children

If it helps you, please star it.

PS This issue should not be considered resolved until it works out of the box.

**Comment by dogawaf** [comment]
I encounter this issue too. My usecase:
- the action willTransition prevents the transition if the parent model or an embedded model is dirty
- when the parent model is saved, a transition to the parent route need to be done
- but the transition is aborted because the embedded model remains dirty

**Comment by perlun** [comment]
:+1:, this should be fixed. It's definitely a bug with the mixin IMHO. I adapted the @lolmaus approach now (`willCommit`, clear `_attributes`, `didCommit`) but it definitely feels like a hack to have to do this manually.

/cc @emilgrip

**Comment by lolmaus** [comment]
Please send a PR containing a failing test case for this issue. It will be much easier to fix.

**Comment by perlun** [comment]
Agree, it would be good. Any pointers/hints on how to start? (I've never worked with the ember data tests) Is it a regular ember-cli project?

**Comment by fidlip** [comment]
Hi guys, is there any progress?

**Comment by fivetanley** [comment]
Please re-open (as a new issue if necessary), hopefully with a failing test case or JSBin. I suspect this has been fixed since 1.13. Sorry but we're triaging inactive issues. Re-opening lets us see if people are still running into them more easily.
