### ISSUE TITLE
How could one define `typeKey` earlier?

### ISSUE THREAD

**Issue by xcambar** [emberjs/data#2507]
Hi,
For a library of mine, I was planning to rely on `DS.Model.typeKey`, but then I discovered that it was set when `DS.Store#modelFor` was called for the first time, otherwise it __must__ be defined manually when declaring the model class.

Needless to say it is pretty inconvenient as is, so I am opening up this thread to start a discussion on how/if the `typeKey` could be defined as early as possible, be it with:

* an initializer
* right after the declaration of the class
* ??

`typeKey` is used throughout Ember Data yet it is defined lazily when the internals require it.
It makes the whole DS.Model classes pretty unusable as a 3rd party unless you patiently wait for some models to be fetched/created/whatever.

How about if it were defined first-hand and always accessible?

**Comment by igorT** [comment]
If you need the model class, you really should be using `store.modelFor` and not relying on imports, same way you would access routes/controllers/etc through the container. 
@bmac maybe we need to stress this more in the docs.
