### ISSUE TITLE
createRecord, then set belongsTo results in Transaction Error after Update to Ember Data 1.0.0-beta.11

### ISSUE THREAD

**Issue by jme783** [emberjs/data#2517]
After upgrading my application to Ember 1.8.1 and Ember Data 1.0.0-beta.11, I am getting a very strange error when trying to set a belongsTo relationship between 2 models:

`Attempted to handle event didCommit on <***@model:order::**:**> while in state root.loaded.updated.uncommitted.`

This comes when I create an order, and try to assign the current bag to that order. Here's the relevant code in the order controller:

```
assignBag: function() {
  var newOrder = this.get('model');
  var shoppingBag = this.get('bag').objectAt('0');
  newOrder.set('bag', shoppingBag);
  this.get("controllers.order").send('saveOrder', newOrder);
  this.send('fireViewedCheckoutSegmentEvent');
}.on('init'),
```

The problematic line is `newOrder.set('bag', shoppingBag);`. By the nature of the error you would think that this would be because a newly created order had not been persisted in the database. But from the code in the route, it's clear that the order is saved before setting the model in the controller:

Here is the order route:

```
var OrderRoute = Ember.Route.extend(ResetScrollMixin, {
  model: function() {
    return this.store.find('order');
  },
  afterModel: function(model) {
    if (model.get('length') < 1) {
      model = this.store.createRecord('order');
    }
  },
  setupController: function(controller, model) {
    var order = model.objectAt('0');
    order.save().then(function(savedOrder) {
      controller.set('model', savedOrder);
    });
  }
});
```
If it helps, here's the code for the two models:

Order:
```
import DS from 'ember-data';

export default DS.Model.extend({
  bag: DS.belongsTo('bag', {async: true}),
});
```

Bag:
```
import DS from 'ember-data';

export default DS.Model.extend({
  order: DS.belongsTo('order'),
});
```
I have been banging my head against the wall for days on this. Does anyone have an idea of what's going on? Am I incorrectly setting up the belongsTo relationship? Both the `order` and `bag` models use the LocalStorage adapter.

Many thanks in advance.

**Comment by wecc** [comment]
@jme783 is this still an issue?

**Comment by jme783** [comment]
I don't think so, I'll go ahead and close this
