### ISSUE TITLE
Weird uglifyjs issue on beta12.

### ISSUE THREAD

**Issue by alexBaizeau** [emberjs/data#2520]
Hi Guys,
When I upgrade to beta12 and run `ember build --environment=production` uglifyjs explodes like that 

```
ember build --environment=production

version: 0.1.2
BuildingBuilding.Build failed.
File: assets/vendor.js (61450:1)
Unexpected token: operator (<)
Error
    at new JS_Parse_Error (/var/lib/jenkins/workspace/node_modules/ember-cli/node_modules/broccoli-uglify-js/node_modules/uglify-js/lib/parse.js:189:18)
...
...
...
npm ERR! weird error 1
npm ERR! not ok code 0
```

I wonder if it's a coincidence or if it could be because of some other dependencies. 

It works like a charm on `beta.11`

**Comment by mgenev** [comment]
this is still happening with ember-data#1.0.0-beta.16.1 and the steps above don't work
