### ISSUE TITLE
Store.find/all are created as filteredRecordArrays

### ISSUE THREAD

**Issue by igorT** [emberjs/data#2542]
Not sure this is appropriate, it leads to confusion when reading the code and to subtle bugs.

**Comment by igorT** [comment]
Does someone want to tackle this, @pangratz or @sly7-7 maybe?

**Comment by pangratz** [comment]
I gave it a shot and changing `findAll` to return a `RecordArray` [breaks this assertion](http://git.io/vTAHK) (all other tests pass). As pointed out by @stefanpenner in https://github.com/emberjs/data/pull/518#issuecomment-17819789 this might be ok; if the `all()` functionality is desired, then [`store.all()`](http://git.io/vTAHZ) should be used...

**Comment by igorT** [comment]
`findAll` should still cache the array and return the same cached array each time. It's just that we don't want it to be a `filteredRecordArray` as there is really no filtering except for deletion happening. So this would refactor the recordArrayManager to care about filteredRecordArrays and something like liveRecordArrays

**Comment by sly7-7** [comment]
@pangratz I'm currently working on rebasing/fixing https://github.com/emberjs/data/pull/2491, which causes some tests to fail (store.all() would become run-loop sensible). Maybe it would be possible to include those changes https://github.com/sly7-7/data/commit/0435b64e2b81ef14a6dc70d85b25ab20472b5ea2 in your current work ? So both issues could be resolved ?

**Comment by pangratz** [comment]
@sly7-7 I try to tackle this later today ...

**Comment by sly7-7** [comment]
Closing since 3167 is merged
