### ISSUE TITLE
'meta' object not passed on POST

### ISSUE THREAD

**Issue by knownasilya** [emberjs/data#2547]
So this seems a little inconsistent, since `meta` is honored during a GET, but not during a POST.

The workaround, suggested by @bmac, is like so:

```js
App.ApplicationSerializer = DS.RESTSerializer.extend({
  serializeIntoHash: function(hash, type, record, options) {
    this._super(hash, type, record, options);
    hash.meta = record.get('meta');
  }
});
```

**Comment by igorT** [comment]
We are refactoring `meta` to better support arrays, but I am still not convinced of doing this by default. Does `JSONApi` have an opinion @wecc ?Will close for now, feel free to reopen if we want to do something

**Comment by wecc** [comment]
For JSON-API `meta` is allowed at multiple locations for responses to create/update requests, just like normal responses.

> - at the top-level
> - within resource objects
> - within relationship objects
> - within link objects
> - within resource identifier objects
> - within error objects
