### ISSUE TITLE
DS.RecordArray.update() is fine, DS.AdapterPopulatedRecordArray.update() goes boom

### ISSUE THREAD

**Issue by glennfu** [emberjs/data#2549]
I have a DS.ActiveModelAdapter connected to my Rails API, and things are mostly good. I can show a controller than renders a table, and if my router defines the model as: `this.store.find('story')` then I can call model.update() and receive remote changes and liquid-fire can animate those changes which is fantastic.

However, if I change the model to `this.store.find('story', { story_type: 'article' })` all of a sudden things go haywire:

1. The 2nd request to my server hits /api/v1/stories whereas the first went to /api/v1/stories?story_type=article.
2. After the rows get their change callbacks triggered (which seems like a bug that I can .observes('story.title') and get hundreds of them to trigger when there's literally 0 changes to the data, but that's not what I care about right now), I see the following stack trace:

        EmberError@http://0.0.0.0:4200/assets/vendor.js:27425:17
        normalizeTuple@http://0.0.0.0:4200/assets/vendor.js:31128:1
        _getPath@http://0.0.0.0:4200/assets/vendor.js:31147:17
        setPath@http://0.0.0.0:4200/assets/vendor.js:31294:1
        set@http://0.0.0.0:4200/assets/vendor.js:31213:1
        Store<.didUpdateAll@http://0.0.0.0:4200/assets/vendor.js:76894:9
        _findAll/<@http://0.0.0.0:4200/assets/vendor.js:77916:9
        tryCatch@http://0.0.0.0:4200/assets/vendor.js:60481:16
        invokeCallback@http://0.0.0.0:4200/assets/vendor.js:60493:17
        publish@http://0.0.0.0:4200/assets/vendor.js:60464:11
        @http://0.0.0.0:4200/assets/vendor.js:42609:9
        DeferredActionQueues.prototype.invoke@http://0.0.0.0:4200/assets/vendor.js:13853:11
        DeferredActionQueues.prototype.flush@http://0.0.0.0:4200/assets/vendor.js:13923:15
        Backburner.prototype.end@http://0.0.0.0:4200/assets/vendor.js:13309:11
        Backburner.prototype.run@http://0.0.0.0:4200/assets/vendor.js:13364:15
        run@http://0.0.0.0:4200/assets/vendor.js:31397:14
        __exports__.default<.ajax/</hash.success@http://0.0.0.0:4200/assets/vendor.js:67737:15
        jQuery.Callbacks/fire@http://0.0.0.0:4200/assets/vendor.js:3237:10
        jQuery.Callbacks/self.fireWith@http://0.0.0.0:4200/assets/vendor.js:3349:7
        done@http://0.0.0.0:4200/assets/vendor.js:9393:5
        .send/callback@http://0.0.0.0:4200/assets/vendor.js:9803:8
	

        method.apply(consoleObj, arguments);

        vendor.js (line 28547)
        Error: Assertion Failed: Error: Path cannot be empty
	

        var tmp = Error.apply(this, arguments);

If I try to chase this with the debugger it looks like the problem is here:

      didUpdateAll: function(type) {
        var findAllCache = this.typeMapFor(type).findAllCache;
        set(findAllCache, 'isUpdating', false);
      },

where `type` is a Class and FireBug shows it as "ajam-aje-ember@model:story:", but `findAllCache` is undefined.

Am I doing something wrong, or is this a bug?

**Comment by wecc** [comment]
Both of these examples triggers two requests without any errors (tested in ED 1.13). Closing this.

```js
store.findAll('users').then((users) => {
  users.update();
  return users;
});
```

```js
store.query('users', { foo: 'bar' }).then((users) => {
  users.update();
  return users;
});
```
