### ISSUE TITLE
A change in an element inside a hasMany dispatches a change in the full ManyArray

### ISSUE THREAD

**Issue by fernandodrumond** [emberjs/data#2555]
Hello guys,

We are updating our application to the last release of Ember Data (1.0.0-beta.12) and I'm getting an unexpected behavior when changing an item of a `hasMany` relationship.

With the previous versions of Ember Data (our last one was 1.0.0-beta.8), a change through the `replace` method would dispatch only a few observers, for each changing item, but now it is notifying a change the complete `ManyArray`.

Checking out the code, I found this in Ember Data:

```js
   Model.reopen({
      notifyHasManyAdded: function(key, record, idx) {
        var relationship = this._relationships[key];
        var manyArray = relationship.manyArray;
        manyArray.addRecord(record, idx);
        //We need to notifyPropertyChange in the adding case because we need to make sure
        //we fetch the newly added record in case it is unloaded
        //TODO(Igor): Consider whether we could do this only if the record state is unloaded
        this.notifyPropertyChange(key);
      },
```

Is it really necessary to notify a change in the full property? I'm not sure that's the behavior expected by most of the applications, since this wouldn't happen for an ordinary array.

In our case, it is an issue because of our visual representation, we use  `Ember.computed.union` to prevent views from re-rendering when swapping objects inside a collection and it turns out with this version all the views are re-created when doing it, nulling all the transition we stablished.

I created a jsfiddle to reproduce it, you can notice add an item to a `hasMany` relationship dispatches a change in the relationship itself.

http://jsfiddle.net/fernandodrumond/842xesgc/9/

Thanks in advance for any help!

**Comment by edborden** [comment]
I'm running into this breaking my UI as well. Each time a relationship is added, a view depending on the hasMany is rerendering every element.

**Comment by edborden** [comment]
Is this related to https://github.com/emberjs/data/issues/2611 ?

**Comment by fernandodrumond** [comment]
I'm not sure if it is related to this issue, since in the version 1.0.0-beta.12 `addRecord` is still available.
But I figured out by trying to update Ember Data to 1.0.0-beta.14.1 that this version will break my fix above.

**Comment by ursm** [comment]
I had the same issue in 1.0.0-beta.15.

**Comment by hibariya** [comment]
Hi, I have (probably) same issue.

I have created another [example](http://emberjs.jsbin.com/dilixisece/1/edit?html,js,output). It works with current canary.

There are two models. Room has many Messages  (Please imagine a chat app).
When I clicked the "Post Message" button, a new message was added. It's OK.
But in HTML, all elements of message were deleted entirely, and they were re-rendered.

**Before button click:**
![selection_169](https://cloud.githubusercontent.com/assets/43346/6502295/95bf0456-c365-11e4-90af-d450463445b0.png)


**After button click:**
![selection_170](https://cloud.githubusercontent.com/assets/43346/6502296/98e08db2-c365-11e4-861a-2be34d422cb3.png)



It seems that it is due to [this arrayContentWillChange](https://github.com/emberjs/data/blob/df3c26f4919550b097c7337a97efa787d17db81d/packages/ember-data/lib/system/record_arrays/many_array.js#L76). But I'm not sure what's the real problrem.

Any ideas? Thanks.

**Comment by edborden** [comment]
@hibariya Exactly. I'm currenty using a hacky workaround to create a "stable" hasMany array:

```javascript
	positions: DS.hasMany 'position'

	## TEMPORARY FIX FOR EMBER DATA WONKINESS. HAS_MANY RELATIONSHIPS RELOAD ON ANY CHANGE CAUSING VIEWS TO RE-RENDER, BREAKING GRIDSTER.
	stablePositions: null

	loadedPositions:false

	+observer positions
	onPositionChange: ->
		unless @loadedPositions
			if @positions.length > 0
				@stablePositions = Ember.A []
				@stablePositions.addObjects @positions
				@loadedPositions = true

	syncStablePositions: ->
		@positions.forEach (position) =>
			@stablePositions.addObject position unless @stablePositions.contains position
	##

**Comment by hibariya** [comment]
@edborden Thank you. At the moment I'll try that, too.

**Comment by jmar910** [comment]
I'm experiencing (i'm pretty sure) the same issue in 1.0.0-beta.16. I am using `createRecord` to create an item, and then immediately calling `save` on it. In my template, I have an `{{each}}`` helper looping over a different model's `hasMany` items... which happen to be the same type of item I just created and saved. When the components render in the `{{each}}`` loop, they render twice... Once when `createRecord` was called and once when `save` is called.

**Comment by edborden** [comment]
With Glimmer in Ember 1.13 and Ember-Data 1.13 this is no longer an issue for me. Recommend closing.
