### ISSUE TITLE
EmbeddedRecordsMixin issue with belongsTo deserialize: 'records' + serialize: 'id' 

### ISSUE THREAD

**Issue by j15e** [emberjs/data#2556]
When you want to load embedded records but save relation with id on a model with the ActiveRecord adapter, the EmbeddedRecordsMixin seems to break the expected behaviour of ActiveRecord.

It should serialize `provider_id: 3` but it serialize `provider: 3` and it seems to be because it only relies ont the `deserialize` attr to set the key during the serialize process.

Specifically, it seems to be because the [`EmbeddedRecordsMixin#serializeBelongsTo][l1] method rely on [`EmbeddedRecordsMixin#keyForRelationship`][l2] method which in turn rely on the [`EmbeddedRecordsMixin#hasDeserializeRecordsOption`][l3] option value to set the key for the relation. But the key set during the serialization should solely depend on the `serialize` option, not the `deserialize`.

See demo here : http://emberjs.jsbin.com/teweposowu

cc @jbourassa

[l1]: https://github.com/emberjs/data/blob/v1.0.0-beta.12/packages/ember-data/lib/serializers/embedded_records_mixin.js#L183-L194

[l2]: https://github.com/emberjs/data/blob/v1.0.0-beta.12/packages/ember-data/lib/serializers/embedded_records_mixin.js#L126-L132

[l3]: https://github.com/emberjs/data/blob/v1.0.0-beta.12/packages/ember-data/lib/serializers/embedded_records_mixin.js#L374

**Comment by agrobbin** [comment]
I just ran into this problem as well, would love to get it fixed!

**Comment by Romanior** [comment]
many thanks @agrobbin !!

**Comment by agrobbin** [comment]
@Romanior glad to have helped!
