### ISSUE TITLE
FindHasMany calls buildURL using the parent type/id 

### ISSUE THREAD

**Issue by igorT** [emberjs/data#2564]
It's a bug that we do that here 
https://github.com/emberjs/data/blob/master/packages/ember-data/lib/adapters/rest_adapter.js#L410

**Comment by karanjthakkar** [comment]
@igorT The url in description is broken. Any update on how to proceed with this?

**Comment by bmac** [comment]
@karanjthakkar I believe this is an updated link: 

https://github.com/emberjs/data/blob/56196f656b3ad3d86f125b7235eb656bddd86629/packages/ember-data/lib/adapters/rest-adapter.js#L493

**Comment by Serabe** [comment]
I might have time to dig into this. Is it still without contributor?

**Comment by Serabe** [comment]
Digging into this issue, I see that the constructed URLs for `hasMany` and `belongsTo` relationship are indistinguishable from the one to get the parent type.

In `build-url-mixin`, `urlForFindHasMany` and `urlForFindBelongsTo` only receive an `id` and a `modelName`; there is no relationship information available. As of JSONAPI specification, the suggested relationship URL with the related data looks like `/parentType/id/relationshipName`: there are at least one 

On the other hand, the `adapter.buildURL = function() {...}` in some test leaks to the rest of the tests.

**Comment by runspired** [comment]
@wecc this should be combined with whatever other issues we have around fixing hasMany relationships to always hit findHasMany and urlForHasMany

**Comment by wecc** [comment]
Yeah, I'm closing this in favor of #2162.
