### ISSUE TITLE
Fetching an object that has been created by a reference previously throws error

### ISSUE THREAD

**Issue by kimroen** [emberjs/data#2569]
An example: http://emberjs.jsbin.com/vukoli/1/edit?html,js

In this example, we load the books, which contains a reference to their author, and then fetch the author with `store.fetch`, which throws an error.

```
Error while processing route: index Attempted to handle event `reloadRecord` on <App.Author:ember306:2> while in state root.empty.
```

**Comment by kimroen** [comment]
Does anyone familiar with the states have any input on this? Poking because we were bitten by this again today.

**Comment by svox1** [comment]
I have the same error with ember-data 1.0.0-beta.14.1.
