### ISSUE TITLE
Boolean attribute serialization

### ISSUE THREAD

**Issue by lfridael** [emberjs/data#2572]
When serializing a record to a JSON payload, boolean attributes are cast to Boolean by `DS.BooleanTransform`. This means that `null` and `undefined` values automatically become `false`.

For applications that handle booleans tristate-style  (i.e. `true`, `false`, and  `null` or  `undefined` signifying the  "indeterminate" state) this behaviour changes the meaning of the value.

Workaround: supply your own `transform:boolean` implementation in the container. Still, the default behaviour surprised me. (Then again, there might be a good reason for not supporting nullable booleans.)

**Comment by bmac** [comment]
Hi @lfridael. 

You are correct that Ember Data's built in boolean transform doesn't play nicely with tristate booleans. However I don't think this is something that will change since many APIs do enforce non-nullable booleans. 

Your workaround is a good one. You could also supply a `transform:nullable-boolean` so you can use the tristate boolean along side a normal boolean.

```js
App.User = DS.Model.extend({
  isAdmin: attr('boolean'),
  isStaff: attr('nullable-boolean'),
  email: attr('string')
});
```

**Comment by lfridael** [comment]
@bmac Thanks for the feedback. I was not aware of the fact that you can define your own attribute types through `transform:xyz`. Cool! That opens up a world of possibilities.

**Comment by arcreative** [comment]
For me, it's more of a "don't serialize something if I didn't set it" issue.  My server checks for the existence of said property, and if not null, throws an attribute error.  I'll probably fix this on the server in the interest of keeping requests idempotent, but I still don't think that null should be casted to false.

**Comment by daibhin** [comment]
The `allowNull` property can also be used here:
```
value: DS.attr('boolean', { allowNull: true }),
```
