### ISSUE TITLE
RestAdapter .ajax private method?

### ISSUE THREAD

**Issue by blimmer** [emberjs/data#2582]
In several places, we have the need to do a simple AJAX request not through an Ember Data model in the store. We're doing something like this in a few, unique places:

```coffeescript
adapter.ajax(url, 'POST',
  data: postData
).then (result) =>
  # success logic
, (reason) =>
  # failure logic
```

It's really nice that the `ajax` method wraps `jquery.ajax` in a very Ember-y way. 

When we upgraded to beta12, we noticed that [this changeset](https://github.com/emberjs/data/commit/4884933497adb4894a3621ad8726cc63c7d910d2) modified the way we were handling `InvalidError` on a few of our calls (it stopped camel-casing the errors array). 

We've worked around this issue and taken note that `.ajax` is a private method. However, I wonder if `.ajax` should be accessible in the public API for uses like this. It seems like a common use-case on a lot of apps to need to do API interactions without a backing Ember Data model.

**Comment by bmac** [comment]
Hi @blimmer. For the time being I believe it would be best to keep adapter.ajax as a private method. That way Ember Data can refactor it (if needed) to best support the use case of making CRUD rest calls. 

If you would like to preform arbitrary ajax calls from your ember app wrapped in an Ember-y way you may want to check out https://github.com/instructure/ic-ajax.
