### ISSUE TITLE
Nested model error attributes are ignored

### ISSUE THREAD

**Issue by amedrz** [emberjs/data#2583]
API responses like this:

```
{
  "errors": {
    "username": ["This username is already taken!"],
    "email": ["Doesn't look like a valid email."]
  }
}
```

Are correctly handled as described [here](http://emberjs.com/api/data/classes/DS.Errors.html).

However, with a response like this:

```
{
  "errors": {
    "username": ["This username is already taken!"],
    "email": ["Doesn't look like a valid email."],
    "address.street": ["Can't be blank"]
  }
}
```

For some reason "address.street" isn't available within the `model.errors` array.

Any ideas of why?

Thanks!

**Comment by mxrguspxrt** [comment]
There are two issues with that that come to my mind:

1. It is problem that Errors only gets keys that are defined for model 
2. "." is translated as subobject in ember calls (you could use "/" instead of ".")

**Comment by wecc** [comment]
Will most likely be fixed by #2583

**Comment by mxrguspxrt** [comment]
Wecc, you refered to the same issue has we are having here #2583  :)

If needed and with some advice (1. where would be the correct place to implement the fix (arhitecture?), 2. where would be the correct place to write tests), I could make a pull request with fix & tests.

**Comment by wecc** [comment]
My bad, brain fart. I meant #1984 :)

**Comment by mxrguspxrt** [comment]
Cool!

**Comment by petermumford** [comment]
I see #1984 has been merged into **1.0.0-beta.15** but this still isn't working. I must be missing something or is this still ignored?

My response is as follows and you'll see I also have a sub sub model (`manufacturers`):
```
{"errors":
  {
    "name":["can't be blank"],
    "url":["can't be blank","is invalid"],
    "email":["can't be blank"],	
    "company_locations.title":["can't be blank"],
    "company_locations.email":["can't be blank"],
    "company_locations.manufacturers.title":["can't be blank"]		
  }
}
```
The response is coming from a Rails API. The more I research this issue the more I'm starting to think its not an easy issue to solve? How do you get `company_locations` errors to apply the DS.Errors on the `company_locations` model from the response. Also, there might be more than one `company_locations` to validate. This also seems to be an issue with Rails as it will validate one object in the array at a time when using the `accepts_nested_attributes_for` method. So this will be a problem if there are 2 `company_locations.title` on the form.

I think I might need to re-think my form designs so it does each model one at a time. The problem with that is a hate form wizards. ha.

Please let me know if I'm missing something.

**Comment by amedr** [comment]
@petermumford I'd opt for using [Form Objects](http://blog.codeclimate.com/blog/2012/10/17/7-ways-to-decompose-fat-activerecord-models/) instead, that way you wouldn't longer need this functionality.

**Comment by mxrguspxrt** [comment]
@amedrz if you have embedded submodels one to hasMany assocation, how to you solve this with form objects? The answer is, you can't.

**Comment by amedrz** [comment]
@mxrguspxrt yeah I agree

**Comment by mxrguspxrt** [comment]
Do you need PR or what is the issue? EmbeddedObjects are heavily used(?) and it is disturbing that it does not work. :(

**Comment by andreiciceu** [comment]
As error extraction has moved into serializers, what is the correct way for setting errors in nested & embedded models?

**Comment by runspired** [comment]
At this point I think we can close this because errors are handled opaquely. It may be the case that the default `errors` property on `@ember-data/model` still does not handle this well, but the cache would receive and the cache can be asked for the original errors and so any model implementation or customization could address this.

When we replace @ember-data/model we should likely discuss how to fit validation errors into the picture for presentation. It might be the case that this is something best left fairly opaque always. Even in JSON:API format error shapes and utility vary widely and are difficult to generalize. I'd expect an RFC for the Model replacement to be written in the next month or so, feel free to chime in on it with thoughts.
