### ISSUE TITLE
EmbeddedRecordsMixin fails when using a store other then 'store:main'

### ISSUE THREAD

**Issue by jmurphyau** [emberjs/data#2588]
I have a situation where I'm not using 'store:main' because the purpose of my application is to compare objects in different environments - so I'm using 'store:production' and 'store:test'.

The EmbeddedRecordsMixin uses ['this.store'](https://github.com/emberjs/data/blob/a83aea92457fc1c34a3277f811ea91f5b12664b8/packages/ember-data/lib/serializers/embedded_records_mixin.js#L123) which is [injected](https://github.com/emberjs/data/blob/d5f19518cb7b7e62b650ce6ce2329f9d0f1557e1/packages/ember-data/lib/initializers/store_injections.js#L11), whereas every function on a serializer (that I can see anyway) appears to use a store variable that is provided externally.

**Comment by bmac** [comment]
Merged as https://github.com/emberjs/data/pull/2915
