### ISSUE TITLE
How hard would it be to remove the dependency of ember from ember-data?

### ISSUE THREAD

**Issue by vegetabill** [emberjs/data#2596]
I really like ember-data, esp that it feels familiar for Rails devs (hasMany, etc) and its overall design. but have to use React as my view layer for other reasons.

Would it even be feasible to modify EmberData to be standalone and not depend on Ember?

**Comment by artburkart** [comment]
Were there any learnings from this?

**Comment by oriSomething** [comment]
@rearadmiral it's not ember data but it may suite you better: [orbit](https://github.com/orbitjs/orbit.js). but still i think with react it might be better to use more "reactish" tools
