### ISSUE TITLE
Deprecate `store.find` acting as findQuery/findAll to use store.findAll and findQuery

### ISSUE THREAD

**Issue by fivetanley** [emberjs/data#2607]
Currently, store.find supports several function signatures:

`store.find('type')` => `store.findAll`
`store.find('type', {queryParam: 'hi'})` => `store.findQuery`
`store.find('type', '1')` => `store.find`

We should only support the last version of this form for 1.0, and deprecate until then.

**Comment by SirZach** [comment]
I would like to disagree. I'm not sure why breaking every single ember-data app out there is worth this.

**Comment by Samsinite** [comment]
It will be deprecated until then, making it easy to find the issues, and fix. I personally like the clarity here as well. Before with `#find` I would have to jump through multiple dispatch logic just to figure out what was happening when debugging.

**Comment by drogus** [comment]
> I would like to disagree. I'm not sure why breaking every single ember-data app out there is worth this.

You can automate such changes:

* for findAll: `sed "s/\.find(\([[:space:]]*['\"][^'\"]*['\"][[:space:]]*\))/.findAll(\1)/g"`
* for findQuery: `sed "s/\.find(\([[:space:]]*['\"][^'\"]*['\"][[:space:]]*,[[:space:]]*{.*}[[:space:]]*\))/.findQuery(\1)/g"`

Of course it will not cover situations like `find('post', params)`, but it should make the transition easier anyway.

**Comment by bmac** [comment]
> `store.find('type', {queryParam: 'hi'})` => `store.findQuery`

Should we call this `fetchQuery` instead since it will always load fresh data from the adapter?

**Comment by wecc** [comment]
@bmac I think that makes sense. I've added a comment over at https://github.com/emberjs/rfcs/pull/27#issuecomment-73754288

**Comment by yonjah** [comment]
@fivetanley  What was the reason for breaking the current `find` method ?
I mean this could be easily changed to have `findOne`, `findAll`, `findQuery`, keeping the `find` method as wrapper that can decide between the different methods (and optionally display a deprecated message if you think that in the future you will want to completely remove the `find` method)

**Comment by jamesarosen** [comment]
Rails went through this with `Model.find(:all)`, `Model.find(:first)`, etc. In general, it's better to have multiple methods that each do one thing than to send in a "behavior" flag. +1 on @yonjah's suggestion for `findOne`, `findAll`, `findQuery`, and `findMany` (though this last one could reasonably be rolled into `findQuery` with `id: [ 1, 2, 3 ]`).

**Comment by wecc** [comment]
New finders have been implemented, closing.
