### ISSUE TITLE
Relationship descriptor does not seem to be documented (and it's parentType property isn't obvious)

### ISSUE THREAD

**Issue by gabrielgrant** [emberjs/data#2616]
The contents of the relationship descriptor passed to [DS.Model's eachRelationship callback](http://emberjs.com/api/data/classes/DS.Model.html#method_eachRelationship) (and exposed elsewhere in the public API) does not seem to be documented.

It appears to contain:

- `key`: (string) the name of this relationship on the Model
- `kind`: (string) "hasMany" or "belongsTo"
- `options`: (object) the original options hash passed when the relationship was declared
- `parentType`: (DS.Model) the type of the Model
- `type`: (DS.Model) the type of the related Model

I must be misunderstanding something, though, because it seems `parentType` isn't fully usable as I'd expect. When defining a [`serializeHasMany` method](http://emberjs.com/api/data/classes/DS.RESTSerializer.html#method_serializeHasMany) on a custom serializer, I'm not able to use the `parentType` to get any info about relationships:

    Ember.get(relationship.parentType, 'relationships')
    TypeError: Cannot call method 'modelFor' of undefined

This appears to be because `store` isn't properly defined. Possibly addressed by https://github.com/emberjs/data/issues/2528 ?
I'm avoiding this by using `record.constructor` instead

    Ember.get(record.constructor, 'relationships')
    MapWithDefault

**Comment by bmac** [comment]
Hi @gabrielgrant. Thanks for opening this issue. I have open a pr to document the relationship descriptor here https://github.com/emberjs/data/pull/2700 please let me know if you have any feedback.

As for the second issue of `relationship.parentType` not working correctly. Could I ask how you declared your relationship? Did you pass in a string or a model class into the `DS.hasMany` or DS.belongsTo` function?

**Comment by gabrielgrant** [comment]
Not sure why this just popped into my notifications... a wee bit delayed, but thanks for addressing this :)

**Comment by gabrielgrant** [comment]
Oh, and yes: it was declared as a string passed in. Haven't worked on this in a while, so not sure if this is still an issue. I may be working on something similar again soon, though, so I'll check it out update here if it is.
