### ISSUE TITLE
isSaving stays true after 422 response

### ISSUE THREAD

**Issue by mxrguspxrt** [emberjs/data#2638]
For me it not expected behaviour - I would like to use isError or isDirty, because save action had return from server.

**Comment by wecc** [comment]
@mxrguspxrt would you be able to test using Ember canary? https://github.com/emberjs/ember.js/pull/10215 from @bmac should most likely solve this.

**Comment by wecc** [comment]
Sorry, the PR above won't fix this but #2697 most likely will, my bad :)

**Comment by wecc** [comment]
@mxrguspxrt #2697 has been merged, could this be closed?
