### ISSUE TITLE
An adapter cannot assign a new id to a record that already has an id.

### ISSUE THREAD

**Issue by kgish** [emberjs/data#2640]
According to the HTTP specifications, the `PUT` method deletes the original resource, creates a new one resource, and returns the new resource in the response body with a `new` ID.

On the other hand, the `PATCH` method preserves the original resource in place, changing only those attributes set in the request, thereby preserving the same ID.

However, I notice that when I do this and call `product.save()` the following error message is generated:

```
ProductAdapter: ajaxSuccess(jqXHR={"readyState":4,"responseText":"{\"product\":{\"id\":8,\"links\":[{\"rel\":\"self\",\"href\":\"/products/8\"}]}}","responseJSON":{"product":{"id":8,"links":[{"rel":"self","href":"/products/8"}]}},"status":200,"statusText":"OK"},jsonPayload={"product":{"id":8,"links":[{"rel":"self","href":"/products/8"}]}}) => {"product":{"id":8,"links":[{"rel":"self","href":"/products/8"}]}}
ProductSerializer: normalizePayload() => do nothing
ProductSerializer: typeForRoot(root=product) => product
ProductSerializer: normalize(type=undefined,hash={"id":8,"links":[{"rel":"self","href":"/products/8"}]},property=product) => {"id":8,"links":[{"rel":"self","href":"/products/8"}]}
Error: Assertion Failed: An adapter cannot assign a new id to a record that already has an id. <App.Product:ember608:3> had id: 3 and you tried to update it with 8. This likely happened because your server returned data in response to a find or update that had a different id than the one you sent.
```

**Comment by bmac** [comment]
Hi @kgish. Where you able to work around this issue in your adapter?

Currently Ember Data assumes that once a record is loaded into the store with an id that record will never change its id. 

Could you provide some more background on your usecase and the API you are using that has this behavior?

**Comment by kgish** [comment]
We can close this issue, thanks.
