### ISSUE TITLE
EmbeddedRecordsMixin doesn't handle sparse trees very well

### ISSUE THREAD

**Issue by BryanCrotaz** [emberjs/data#2651]
I have a deep tree on the server. Each node has child objects. I can request a node + a depth of children nodes.

Using EmbeddedRecordsMixin I can either supply the children as ids or records. If I choose to use ids, I have to only load a depth of 2 and convert children objects to ids (discarding the data). If I choose to use records I have to load the entire tree (otherwise the max depth nodes have an empty child list in ED).

If I could specify 'mixed' to EmbeddedRecordsMixin (ERM), I could solve this problem.

In this mode, when ERM finds a child in the JSON it looks at its type:

string or int: it's an id (treat as async)
object with only id: it's an id (treat as async)
object with only type+id: it's a polymorphic id (treat as async)
object with more properties: it's an embedded record (treat as sync)

Thoughts?

**Comment by Kuzirashi** [comment]
That would be nice to see in Ember Data. For example, in mongoose, you get array `subdocuments: [id, id, id]` when you get document from mongodb with subdocuments, but - when you try to limit subdocuments collection(eg. limit 2) - you get `subdocuments: [{id: id}, {id: id}]` and that might be problematic to handle.

**Comment by Twinkletoes** [comment]
Problematic for my design, or problematic without my proposed change?

**Comment by Kuzirashi** [comment]
@Twinkletoes Without your proposed change. You have to parse results array to to `[id, id]` structure when you limit child documents. By the way, it's not so easy to get mongoose working with ember-data.

**Comment by fivetanley** [comment]
This seems very specific to Mongoose/Mongo. I think this would make a great addon using the new serializer API, but without going through the https://github.com/emberjs/rfcs process, I don't think we can support it in core as it doesn't feel very well specified. I don't think we'd be inclined to support it either as it seems specific to Mongo.
