### ISSUE TITLE
ember-data#1.0.0-beta.14.1 self.store is undefined

### ISSUE THREAD

**Issue by zyllorion** [emberjs/data#2656]
ember#canary
ember-cli#0.1.5

When setting up the model in the route, the store seems to be unavailable - "self.store is undefined" in FF, "Cannot read property 'find' of undefined" in Chrome.  The best I can tell this is caused by ember-data beta 14 but I'm unable to revert to beta 12 to check right now.  This all worked fine with ember-cli 0.1.4, ember data beta 12 and ember 1.9.0.  Cache has been cleared, bower_components and node_modules rebuilt.
```
model: function(params) {
var self = this;
return new Ember.RSVP.Promise(function(resolve) {
new Ember.RSVP.hash({
myModelName: self.store.find('the-model-name', params.some_id),
nextModel...
```

This is also referenced with older versions that worked fine for me [here](http://stackoverflow.com/questions/27597790/ember-not-initializing-store-properly-cannot-read-property-find-of-undefined).

**Comment by igorT** [comment]
Can you reproduce in a newly created app? Or submit a failing jsbin/is your app open source? Not sure how to reproduce/help

**Comment by igorT** [comment]
I am happy to screenshare and take a look if you ping me on irc when i am around

**Comment by zyllorion** [comment]
Thanks for looking.  Seems to be fixed in latest canary ember/dependencies, closing.
