### ISSUE TITLE
Loading one-to-many relationships with beta-14.1

### ISSUE THREAD

**Issue by Flip** [emberjs/data#2660]
**INTRO**
Say we have a model where an album has many tracks:
```javascript
App.Album = DS.Model.extend({
	title: DS.attr(),
    tracks: DS.hasMany('track', { async: true })
});
App.Track = DS.Model.extend({
  artist_name: DS.attr("string"),
  title: DS.attr("string"),
});
```

We can then get associated items with album.get('tracks'), i.e.:
```javascript
this.get('store').find('album', 1).then(function(album) {
  album.get('tracks').then(function(tracks) {
    console.info(tracks);
  });
});
```

**ISSUE**
But something has apparently changed with beta 14 when loading associated items compared to beta 12. With Beta 12, album.get('tracks') returns:
```javascript
tracks => Class {type: function, content: Array[3], store: Class, relationship: o, isPolymorphic: undefined…}
```
But with Beta 14, album.get('tracks') returns:
```javascript
tracks => Class {canonicalState: Array[3], store: Class, relationship: ut, type: function, record: Class…}
```

There no longer is a 'content' attribute in beta 14, only 'canonicalState' and 'currentState' that actually contain the data of all tracks associated with the respective album.

Please also take a look at these two JSFiddles:
*Beta 12*: http://jsbin.com/forewexaga/2/edit?html,js,output
*Beta 14.1*: http://jsbin.com/lopidoqelu/2/edit?html,js,output

Is this the desired new behavior or some kind of bug?

Thanks!

**Comment by aquamme** [comment]
I think the ```content``` attribute was removed during refactoring in favor of ```canonicalState``` and ```currentState```, although I don't see these new properties in the documentation. Regardless, these properties are implementation details.

> Is this the desired new behavior or some kind of bug?

What behavior are you referring to? The jsbins appear to behave the same on cursory inspection. E.g. ```tracks.getEach('title')``` produces the same results in each example.

**Comment by igorT** [comment]
`album.get('tracks')` is an Ember Array that you can use. If you need an actual native array, you can always call toArray() on it
