### ISSUE TITLE
ember canary build is broken due to more Ember.Map issues....

### ISSUE THREAD

**Issue by fivetanley** [emberjs/data#2661]
https://github.com/emberjs/ember.js/commit/685d9e36fee7a8d99f3811a9f99758a1231ffaa7

We'll need to add these to packages/ember-data/lib/system/map.js

**Comment by rwjblue** [comment]
Dangit.  I'm sorry :(

**Comment by fivetanley** [comment]
@rwjblue no worries, this is a change i saw coming.

**Comment by fivetanley** [comment]
due to us trying to make Map/Set more congruent with es6
