### ISSUE TITLE
Removed 'content' property from relationships

### ISSUE THREAD

**Issue by engma** [emberjs/data#2665]
This used to work just fine in ember
```js
//each segment has many messages
var messages = segment.get("messages");

//then to get the plain array
var messagesArray = messages.get("content");
```

But now I need to do this

```js
var messagesArray = messages.get("currentState");
```

I have some old JS code that needs to see plain arrays, for indecies and things like that, Removing this feature caused me to change alot of my code

**Comment by igorT** [comment]
What you actually want to do is segment.toArray() and messages.toArray()

**Comment by igorT** [comment]
I thought we covered this in changelog/blog post but apparently we didn't. Do you want to make a PR to call out that relationships are no longer ArrayProxies so you can just directly access them

**Comment by engma** [comment]
I think I will make a PR to note this in the CHANGELOG, because it really broke my code

**Comment by Twinkletoes** [comment]
Can we have a deprecation warning for this? I've spent days chasing a bug down because we were using get("content") in one place

**Comment by mgenev** [comment]
So how am I supposed to get the data out of the relationship now? I need to do a computed property on it and instead of an array of data I get a DS.manyArray which is really awkward and undocumented so i I filed a bug.
https://github.com/emberjs/data/issues/3061

**Comment by igorT** [comment]
ManyArray is the array. If you want a JS array you can simply `.toArray()`. @BryanCrotaz that sounds like a good idea, sorry I missed your message before

**Comment by IanVS** [comment]
Should `toArray()` be included in the [API Docs](http://emberjs.com/api/data/classes/DS.ManyArray.html)?

**Comment by igorT** [comment]
Hm, It should be there as it extends MutableArray, seems like we have a doc bug

**Comment by IanVS** [comment]
I can submit an issue, what repo does it belong in?

**Comment by igorT** [comment]
I would guess https://github.com/emberjs/api

**Comment by IanVS** [comment]
According to the top of the page, it says:

> DS.MANYARRAY
EXTENDS: EMBER.OBJECT
USES: EMBER.MUTABLEARRAY

So, does it matter that manyArray only uses, not extends, mutibleArray?

**Comment by igorT** [comment]
`mutableArray` is a mixin so it can't extend it, can only use it.
