### ISSUE TITLE
fix windows CI

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/data#2668]
this will give us more confidence that it is possible to contribute from windows.

**Comment by bmac** [comment]
@stefanpenner I have a windows vm where I can produce the broken builds but I don't really know where to go from there. Who could I talk to that has experience with broccoli on windows?

**Comment by stefanpenner** [comment]
@bmac, @raytiley is a good a good bet.

As both ember-cli and broccoli work on windows, i suspect it is just something funky with the ember-data build. My recommendation would be to start from a minimal brocfile and slowly add functionality back until you track down the issue.

**Comment by raytiley** [comment]
Here we go again :)

Where is the appveyor build. I see the config file, but not a badge in the readme. My experience with ember-cli is that most of the problems are with line endings and tests expecting unix like behavior with line endings. 

I'll try to pull down ember data on my windows VM and take a stab at things later this week.

**Comment by wecc** [comment]
Related: #2652

**Comment by bmac** [comment]
Closing as I believe this was fixed by https://github.com/emberjs/data/pull/2762
