### ISSUE TITLE
ManyArray no longer has allows save on collection

### ISSUE THREAD

**Issue by aaronbhansen** [emberjs/data#2669]
We previously would retrieve a hasMany relation, then save the relation and all records associated with it. Now that no longer works in ember data 14. It appears the methods we used to use on RecordArray are no longer there for the ManyArray.

You can see it here in this bin. http://jsbin.com/jisufu/1 

Looking at the other bug tickets, I'm guessing it's probably related to the other tickets about many array and using .content.

**Comment by igorT** [comment]
Yes, a ManyArray is not a RecordArray anymore. I am happy to merge a PR that implements `save` on it, but it is kinda misleading, as `post.get('comments').save()` will just save all the comments, while people might be under the impression that it will save the comments relationship. Not really sure what to do about that

**Comment by fivetanley** [comment]
`store.saveRecords` as sugar for:

```javascript
store.saveRecords = function(records) {
  records.forEach(function(record){
    record.save();
  });
};
```

Is that the desired behavior?

**Comment by igorT** [comment]
Well currently you can do `records.save()` on anything thats a record array, but not on a ManyArray, so we might want to bring save back.

**Comment by aaronbhansen** [comment]
Right, it was nice to be able to add records or update records off of an entity relation and then save them all at once. Maybe the api documentation needs to be updated as well, since it states 
```A ManyArray is a RecordArray that represents the contents of a has-many relationship```

or combine ManyArray and RecordArray into a single class as they feel like they have similar uses.

**Comment by igorT** [comment]
Splitting RecordArrays from Many arrays actually cleaned up a lot of code. Do you want to make a PR that brings `save` back?

**Comment by aaronbhansen** [comment]
I can do that, is ```update``` something we also want to have shared between the two collections?

**Comment by igorT** [comment]
ManyArrays already have reload.

**Comment by wecc** [comment]
@aaronbhansen did you get a chance to have a look at a PR for this?

**Comment by aaronbhansen** [comment]
I had reopened the class and copied the code over from the [record array](https://github.com/emberjs/data/blob/v1.0.0-beta.14.1/packages/ember-data/lib/system/record_arrays/record_array.js#L161) and that seemed to work, but we reverted back to 12 shortly after because of the other issues with deleted records remaining on has_many relations. 
I haven't had time yet to go back and create the pull request, add tests, and fully test it.
