### ISSUE TITLE
Set DS_NO_WARN_ON_UNUSED_KEYS to true by default

### ISSUE THREAD

**Issue by cloke** [emberjs/data#2670]
Currently Ember.ENV.DS_NO_WARN_ON_UNUSED_KEYS is undefined by default which means these warnings are logged. This seems to be counter to all the other logging options which have to be turned on and are off by default (LOG_TRANSITIONS, LOG_TRANSITIONS_INTERNAL, etc). Would it make sense to change this to be consistent with other loggers?

Related to this the variable sits on the ENV object. Other loggers are enabled by passing them into app.create with a true value. Should this be changed for consistency as well?

**Comment by igorT** [comment]
This isn't a log though, this is a warning of something that shouldn't be really happening.
Any thoughts @trek @tomdale @wycats

**Comment by cloke** [comment]
If you mean extra keys from a data source shouldn't be happening I would disagree with that statement. In many cases when consuming API's (especially 3rd party API's) there can be a huge amount of data returned in the JSON response that is irrelevant to the applications needs or even keys that appear based on additional values (iTunes is a good example) which the developer has no control over. Having these warnings on by default make for a very chatty log and provide very little value.

**Comment by igorT** [comment]
Hm, I agree, though on the other hand this is super useful if you screw up somewhere in the normalization process. Maybe off by default is the best we can do :(

**Comment by sly7-7** [comment]
also, about this option, I think it would be simpler if it was DS_WARN_ON_UNUSED_KEYS, and set the the default to what we want. Maybe I'm just an idiot, but having the negation in the name sounds more complicated..

**Comment by igorT** [comment]
@sly7-7 fixed

**Comment by eccegordo** [comment]
How do you set this in an Ember CLI project in an environment config?

Neither of these seem to work.

```
    ENV.DS_NO_WARN_ON_UNUSED_KEYS = true;
    ENV.APP.DS_NO_WARN_ON_UNUSED_KEYS = true;
```

**Comment by sly7-7** [comment]
@eccegordo This has been changed to `DS_WARN_ON_UNUSED_KEYS`, see https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/store.js#L1435

**Comment by eccegordo** [comment]
@sly7-7 Thanks. OK dumb question how to I disable this in an ember cli project? None of the following seem to work but maybe I am missing something obvious. I am just trying to remove some of the noise in my console log.

```
// ember cli project => config/environment.js

  if (environment === 'development') {
    ENV.DS_WARN_ON_UNKNOWN_KEYS = false;
  }
```

```
  if (environment === 'development') {
    ENV.APP.DS_WARN_ON_UNKNOWN_KEYS = false;
  }
```

```
  // This would require that I import Ember which doesn't seem right

  if (environment === 'development') {
    Ember.ENV.APP.DS_WARN_ON_UNKNOWN_KEYS = false;
  }
```

**Comment by wecc** [comment]
@eccegordo What version of ED are you on?

**v1.0.0-beta.12**
Enabled by default, no option to disable

**v1.0.0-beta.14.1**
Enabled by default, set `Ember.ENV.DS_NO_WARN_ON_UNUSED_KEYS = true` to disable

**canary**
Disabled by default, set `Ember.ENV.DS_WARN_ON_UNKNOWN_KEYS = true` to enable

To disable in Ember CLI (using ED v1.0.0-beta.14.1) you do:

```javascript
if (environment === 'development') {
  ENV.EmberENV.DS_NO_WARN_ON_UNUSED_KEYS = true;
}
```

**Comment by eccegordo** [comment]
@wecc Perfect! That worked. Exactly what I was looking for. I am on v1.0.0-beta.14.1.

Thanks so much for the clarification.
