### ISSUE TITLE
Leverage the emberjs-build Pipeline

### ISSUE THREAD

**Issue by seanpdoyle** [emberjs/data#2683]
Reusing the build pipeline (https://github.com/emberjs/emberjs-build) would allow for sharing build/linting/etc improvements across projects.

What would something like that take?

I've added the `emberjs-build` package to the dependencies and copied the [Brocfile.js](https://github.com/emberjs/ember.js/blob/dca9c74de7136deff79b9cb2f2de4f6b6b8237c7/Brocfile.js)  from the main repository.

Is this even a good idea?

**Comment by rwjblue** [comment]
Unsure, ATM it is fairly tailored to Ember itself, but most of the concepts could be easily made to work here too I believe...

**Comment by seanpdoyle** [comment]
@rwjblue fair enough, I'll try looking into that in the future.

Could you point me to the part that resolves es6 modules in the test suite? `emberjs/data` doesn't seem to support `import` and `export` in test files.

**Comment by bmac** [comment]
Closing as Ember Data now uses the Ember CLI build pipeline.
