### ISSUE TITLE
Causing a find while you are flushing fetches puts the record in a limbo state.

### ISSUE THREAD

**Issue by tonysherbondy** [emberjs/data#2688]
For example, accessing a relationship inside the serializer hooks will cause the new record to be scheduled onto the _pendingFetches array, but because we are already iterating and flushing that array the newly added record never gets processed.

**Comment by wecc** [comment]
@tonysherbondy I'm a bit lost as how to reproduce this. Would you be able to provide a JSBin demonstrating the issue?

**Comment by igorT** [comment]
I can tomorrow

**Comment by wecc** [comment]
@igorT did we sort this out? can't remember what it was about but I guess snapshots solves this?

**Comment by wecc** [comment]
Closing, should be solved by snapshots.

**Comment by igorT** [comment]
It's less likely now, but I think technically still a bug until we fix coalescing

**Comment by fivetanley** [comment]
@igorT @tonysherbondy is this still an issue?

**Comment by runspired** [comment]
I believe this is fixed

**Comment by runspired** [comment]
Closing as I'm fairly certain this is resolved
