### ISSUE TITLE
setDiff doesn't work with async hasMany relationships

### ISSUE THREAD

**Issue by bgentry** [emberjs/data#2689]
Please forgive anything that doesn't make sense or isn't explained fully enough in here as I'm very new to Ember and ember-data :)

I've been struggling to figure out why I can't get the items in this select list to update as expected. I want the list to show me the full set of Asset Classes that hasn't already been added to the Portfolio:

![](http://cl.ly/image/3G2n1617462T/data)

![](http://cl.ly/image/2J2P3Q2m3z0n/data)

The following controller snippet is where I'm pulling the list of items from:

``` js
export default Ember.ObjectController.extend({
  allAssetClasses: function() {
    return this.store.find('asset-class');
  }.property(),

  assetClassToAdd: null,
  onAssetClassToAddChange:function(){
    var assetClass = this.get('assetClassToAdd');
    if(assetClass === null) {
      return;
    }
    var portfolio = this.get('model');
    var allocation = this.store.createRecord('allocation', {
      assetClass: assetClass,
      portfolio: portfolio
    });
    portfolio.get('allocations').addObject(allocation);
    this.set('assetClassToAdd', null);
  }.observes('assetClassToAdd'),

  remainingAssetClasses: Ember.computed.setDiff('allAssetClasses', 'model.assetClasses'),
   ...
}
```

Specifically, the `remainingAssetClasses` list is what's passed to the `Ember.Select` dropdown. It doesn't seem to update when `model.assetClasses` changes, though. At least not with the ActiveModelAdapter.

To try and debug this issue, I've done my best to create a JSBin that matches my actual code, except that it uses the FixtureAdapter instead of the ActiveModelAdapter: http://jsbin.com/nadece/1/edit?html,js,output

To my surprise, the FixtureAdapter version works as expected:

![](http://cl.ly/image/44073R070l17/data)

![](http://cl.ly/image/342E3y3h1R2G/data)

Which leads me to believe that the problem is something to do with the `hasMany` relationship with the `ActiveModelAdapter` or `RestAdapter`. I've dug through Ember inspector and the console, and afaict, `model.assetClasses` is in fact updating as expected. And yet `remainingAssetClasses` never changes.

I think that this is really a problem with `setDiff` not being able to tell that items included in that array are already in the `allAssetClasses` array.

The code for this project is all open source (see [here](https://github.com/bgentry/portfolio/blob/56b847706378300f61a250bfe0c7db652316e137/app/controllers/portfolios/new.js) ) so I won't paste all of its source in this issue.

If there's any better way to help diagnose the issue, please let me know what I can do. I'm not sure how to create a JSBin that more accurately reflects the real issue (since I don't have a live server to query against, though I suppose I could just put one on Heroku).

Apologies if this is hard to understand or if it reflects an existing issue :)

**Comment by bgentry** [comment]
Oh, may also be relevant.. My current serializer for Portfolio uses embedded attributes for its Allocations like so:

```js
export default DS.ActiveModelSerializer.extend(DS.EmbeddedRecordsMixin, {
  attrs: {
    allocations: {embedded: 'always'}
  }
});
```

**Comment by bgentry** [comment]
Nope, still happens without the embedded Allocations. It also still happens using `RESTAdapter` rather than `ActiveModelAdapter`. So either it's an ember-data issue, or I'm doing something non-obvious incorrectly.

**Comment by wecc** [comment]
@bgentry Your JSBin works using FixtureAdapter and here's a simplified working version using the RESTAdapter: http://jsbin.com/romiqujade/1/edit?html,js,output. Here's another one using ActiveModelAdapter: http://jsbin.com/jedavujeda/1/edit?html,js,output

Could you create a failing JSBin? mockjax is great for faking HTTP requests.

**Comment by bgentry** [comment]
Thanks, that helps a lot. I'll see if I can narrow down what's different in my code base.

**Comment by bgentry** [comment]
@wecc ok, so I figured out what's breaking this. If I just set `async: true` on the Allocation's `assetClass` definition in the example you shared, the select list no longer changes: http://jsbin.com/nodege/1/edit?html,js,output

So I merely change this:

```js
App.Allocation = DS.Model.extend({
  assetClass: DS.belongsTo('asset-class')
});
```

to this:

```js
App.Allocation = DS.Model.extend({
  assetClass: DS.belongsTo('asset-class', {async: true})
});
```

Does that mean this is a bug w/ async relationships? Or am I supposed to do something differently if I'm using async?

**Comment by bmac** [comment]
@bgentry This looks like a problem with how async relationships get wrapped in promise proxies. This causes setDiff to compare the original relationship objects from the `find('asset-class')` look up with promise proxies objects wrapping the `assetClass` records on the `Allocation` record.

One work around you could use is to grab the `content` out of the promiseProxies in your `assetClasses` computed.
```js
App.Portfolio = DS.Model.extend({
  allocations: DS.hasMany('allocations'),
  assetClasses: Ember.computed.mapBy('allocations', 'assetClass.content')
});
```

**Comment by bgentry** [comment]
@bmac great, I had a hunch that's what the bug was related to :) That workaround does help me out for now, thank you!

Is there another issue for this bug, or is this the place to track it? Is it likely an ember-data issue, or just Ember?

**Comment by bmac** [comment]
This is defiantly an Ember Data issue. I don't think there is any one issue for tracking it. There are a bunch of issue floating around that all result from the awkwardness of PromiseProxies wrapping models.

**Comment by JackEllis** [comment]
@bmac Did things ever change here? I'm also finding that I can't use Ember.computed.setDiff() with 2 different relationships (that aren't embedded)...

**Comment by stefanpenner** [comment]
I believe we have sorted these out:

1. hasMany array promise proxies are now stable
2. changes are diff'd and applied
