### ISSUE TITLE
coalesceFindRequests: true got ignored when trying to get a hasMany relationshipts

### ISSUE THREAD

**Issue by Romanior** [emberjs/data#2690]
After upgrading to Ember-data 1.0.0-beta.14, the one request to server from

`parentModel.get(childrenModel)` where just

``` 
parentModel = DS.Model.extend
  childrenModel: DS.hasMany('child', async: true)
```

Ember-data now sends instead of one, n-requests, where n - is a length of childrenModel array of ids. 
I have set `coalesceFindRequests: true` on my adapter.

**Comment by wecc** [comment]
I'm unable to reproduce this, see http://emberjs.jsbin.com/paqovamore/1/edit

If you comment out the last mockjax you can see the coalesced request in your browser's debugger.

**Comment by Romanior** [comment]
Thanks, I'm pretty sure I'm doing everything right,  I'd try to put a JsBin asap.

**Comment by pboutin** [comment]
the coalesceFindRequests is ignored when the parent happens to have only one children. I crashed @wecc's JSbin by replacing the mockjaxs with the following :

```javascript
$.mockjax({
  type: 'GET',
  url: '/authors/1',
  status: '200',
  dataType: 'json',
  responseText: {
    author:
      { id: 1, name: "Mark Twain", books: [1] }
  }
});

$.mockjax({
  type: 'GET',
  url: '/books',
  data: {
    ids: [1]
  },
  status: '200',
  dataType: 'json',
  responseText: {
    books: [
      { id: 1, title: 'Tom Sawyer'}
    ]
  }
});
```

**Comment by wecc** [comment]
@pboutin If there's only one book to request ED won't coalesce because... there's only one book to request. The JSBin crash because no data is returned for `/books/1`. Do you mean that you'd want ED to request `/books?ids[]=1` instead?

**Comment by pboutin** [comment]
@wecc yes, (I updated the jsBin too fast, sorry for that).

Before I upgrade to beta-14 this is how things used to work. I think the `/books?ids[]=1` is better for some cases since it's more a more consistent way to load a relation. Now, my API can be poked from 2 URIs for the very same relation.

For now, I just implemented the missing endpoints in my API for I suggest that `coalesceFindRequests: true` applies to **all** `hasMany`

**Comment by Romanior** [comment]
OK, I have found the cause of my issue, simple override `buildURL` breaks the coalesceFindRequests
See JSbin
http://emberjs.jsbin.com/vobiluyacu/2/edit

**Comment by wecc** [comment]
@Romanior I think this is due to `_stripIDFromURL` doesn't understand the `/resource/:id.test` pattern in your JSBin and because of that it cannot coalesce the requests. The method is private, might need e hook to override this.

**Comment by Romanior** [comment]
ok adding `.test` was a bit unrelated, in real life it used to be `.json` for hitting rails API, which is legitimate case.

**Comment by harianus** [comment]
> I don't know the true cause of it, can quess, that overrode 'buildURL' breaks runloop and adapter can not properly create a glued URL. @wecc I consider this is a serious issue.

Wow, I'm so happy I found this issue. I just wanted to have .json at the end of every url. Never expected the `buildURL`-function was related to `coalesceFindRequests: true`

**Comment by wecc** [comment]
@Romanior I got your JSBin working with #2885. Having `buildURL()` return `/books/1.test`, `/books/2.test` and `/books/3.test` results in a coalesced call to `/books.test?ids[]=1&ids[]=2&ids[]=3`

**Comment by Romanior** [comment]
Yes this is was the issue, Thanks!
