### ISSUE TITLE
401 Unauthorized thowing Uncaught TypeError

### ISSUE THREAD

**Issue by arenoir** [emberjs/data#2694]
I am getting the following error whenever  the backend returns a 401 Unauthorized code.

````
Uncaught TypeError: Cannot assign to read only property '__reason_with_error_thrown__' of Unauthorized
````

I don't know if this is an ember-data, ember, or RSVP issue.

Ember : 1.10.0-beta.4
Ember Data : 1.0.0-beta.15-canary

![screen shot 2015-01-13 at 1 00 54 pm](https://cloud.githubusercontent.com/assets/113590/5729067/42f644be-9b24-11e4-95a8-223a30c1d989.png)

**Comment by bmac** [comment]
@arenoir I attempted to put together a quick jsbin to test this and I was unable to reproduce this TypeError. Could you take a look at this jsbin and let me know if I'm missing something? http://emberjs.jsbin.com/lefavenoqu/1/edit?html,js,console

**Comment by wecc** [comment]
Probably related: https://github.com/emberjs/data/issues/2638#issuecomment-68319353

**Comment by arenoir** [comment]
@bmac thanks for putting that jsbin together.  I can't reproduce it either.  Perhaps it is ember simple auth. adding a call back to the ajax method somewhere.

**Comment by bmac** [comment]
It looks like @wecc is on to something since his jsbin http://emberjs.jsbin.com/cicejusaja reproduces the error that you described.  

@stefanpenner do you have any insight into the magic of `__reason_with_error_thrown__`?

**Comment by rwjblue** [comment]
@bmac - ic-ajax

**Comment by bmac** [comment]
Digging into it a little more and it looks the the `TypeError` only occurs when `errorThrown` is a string instead of an Error object.

**Comment by arenoir** [comment]
@bmac that was it, I pulled in the latest build and all is good.  :beers:

**Comment by bmac** [comment]
Awesome. Thanks for the bug report.
