### ISSUE TITLE
Observing isDirty flag is not possible until first access 

### ISSUE THREAD

**Issue by iamolivinius** [emberjs/data#2695]
I've got a "weird" behavior in DS.Model when I try to observe the `isDirty` flag. My goal is to autosave the a model as soon as a property is changed. A simple model looks like

```js
App.Person = DS.Model.extend({
  name: DS.attr('string'),
  
  whenDirty: function () {
    console.log('I\'m so dirty');
  }.observes('isDirty')
});
```

In a route I pull one record out of the storage and pass it to an `ObjectController`. The ObjectController has a method to change the `name` property.

```js
App.IndexRoute = Ember.Route.extend({
  model: function() {
    var store = this.store;
    
    return this.store.find('person').then(function (persons) {
      var person;
      if (Ember.isEmpty(persons.get('firstObject'))) {
        person = store.createRecord('person', { name: 'Oliver' });
        person.save();
      } else {
        person = persons.get('firstObject');
      }
      return person;
    });
  }
});

App.IndexController = Ember.ObjectController.extend({
  actions: {
    changeName: function () {
      if (this.get('name') === 'Oliver')
        this.set('name', 'Felix');
      else
        this.set('name', 'Oliver');
    }
  }
});
```

The template looks like this

```hbs
<script type="text/x-handlebars">
  {{outlet}}
</script>

<script type="text/x-handlebars" data-template-name="index">
  <p {{action "changeName"}}>{{name}}</p>
  {{!-- <p>is dirty: {{isDirty}}</p> --}}
</script>
```

Until I uncomment the second line of the index template the `whenDirty` method is not called. As soon as I uncomment this line or fire up ember inspector and check the data record the method is called and text is printed to the console as assumed. 

Is this behavior `as it should be` and I'm doing it wrong or is there an even better way to observe the isDirty status of an ember model?

JSBIN example: http://emberjs.jsbin.com/cosetolila/5/edit?html,js

Thanks in advance

**Comment by wecc** [comment]
I don't think this is a bug in Ember Data. Have a look at http://emberjs.com/guides/object-model/observers/#toc_unconsumed-computed-properties-do-not-trigger-observers

**Comment by iamolivinius** [comment]
Well, I guess you're right. Looks like `isDirty` is a computed property. I added the following snippet to the model and everything went fine :+1: 

```js
setupModel: function () {
  this.get('isDirty');
}.on('init')
```
