### ISSUE TITLE
Should `deleted.inFlight` support `becameInvalid`?

### ISSUE THREAD

**Issue by ppcano** [emberjs/data#2708]
Currently, when the server response of DELETE is a validation error, the record state (deleted.inFlight) does not manage the `becameInvalid` event.

I am not sure, if this implementation is missing or is a design choice, so `deletion` should only response to normal errors, avoiding validation errors.

Right now, rollback the record state may be solved as:
```
    item.destroyRecord().then(function() {
      ....
    }).catch(function(error) {
      if (error instanceof InvalidError) {
        self.store.recordWasError(item, error);
      }
      item.rollback();
   });
```

**Comment by wecc** [comment]
Duplicate of #2126, open PR at #2169.

**Comment by ppcano** [comment]
Closing in favour of #2710
