### ISSUE TITLE
Reloading a many to many relationship from server.

### ISSUE THREAD

**Issue by responsis** [emberjs/data#2713]
I've got a many to many reflexive(not sure if this matters) relationship that I want to get fresh up to date data from the server.

If I add a Record A from Record B's of the relationship, then reload Record B, Record A still has the entry for Record B, so it is then added to Record B's array again. To get the functionality I want, I've found that i have to disconnect the relationships, reload all the records, then reconnect them, like so:

```
var component = this;
this.get('model.parents.content.relationship').disconnect();
this.get('model').reload().then(function (model) {
    return model.get('parents').reload();
}).then(function () {
    component.get('model.parents.content.relationship').reconnect();
});
```

This means I have to reload every record in the many/many, and tinker with some internals that I've only read briefly.

I've got 2 of these kind of relationships one of my models, and it seems to pain to overload reload() to add in this functionality.

**Comment by bmac** [comment]
Hi @responsis this defiantly sounds like a bug. Any chance you could put together a simplified jsbin showing your relationships and the server response? It would really help with debugging this issue.

**Comment by joeruello** [comment]
@bmac, accidentally flagged this on the org account, will try to get a JSBin to you sometime today.

**Comment by joeruello** [comment]
@bmac Here's a JSBin showing current behaviour (jsbin)[http://jsbin.com/lawolovixe/2/edit?html,css,js,output]. If you remove the parents, press reload, the parents won't be re-added into the relationship even though they are in the reloaded response.

Also seems to be something weird happening with the bindings/rendering in this example as well if you reload after removing the first parent. Not sure what the deal with that is.

**Comment by bmac** [comment]
Hi @joeruello. Thanks for the jsbin. I made some progress today on fixing this issue and I opened a pr for it https://github.com/emberjs/data/pull/2723. I will try to add some tests to that pr tomorrow to finish it up.

**Comment by joeruello** [comment]
Amazing, thanks a lot for your work.
