### ISSUE TITLE
Debug version seems to have a bug

### ISSUE THREAD

**Issue by TauranJanitor** [emberjs/data#2716]
The simple page below with no components defined starts with an error, "Uncaught SyntaxError: Unexpected token typeof" on line 11348, while changing the the ember data version to prod or min shows no error. Maybe this is a minor issue because one can develop with the other two versions.

Tags didn't come through, so I'm paraphrasing the html.
doctype tag
html tag
head tag
script tag for jquery-1.11.2.min.js
script tag for handlebars-2.0.0.js
script tag for ember-1.9.1.debug.js
script tag for ember-data-1.0.0-beta.14.1.debug.js
script tag for localstorage_adapter.js

close head tag
body tag
close body tag
close html tag

**Comment by bmac** [comment]
Thanks for opening this issue @TauranJanitor. It looks like the version of ember data on the [builds] page has a rouge `Â` character causing this invalid JavaScript syntax.

```js
Ember.assert("The first argument to DS.belongsTo must be a string representing a model type key, not an instance of " + Ember.inspect(type) + ". E.g., to define a relation to the Person model, use DS.belongsTo('person')", typeof type === 'string' ||Â typeof type === 'undefined');
```

For a temporary workaround you can use the `ember-data-1.0.0-beta.14.1` file hosted on [bower](https://raw.githubusercontent.com/components/ember-data/7dd377bae744124c248449d306f76030b89a8a16/ember-data.js) which appears to be unaffected by this issue.

@rwjblue @fivetanley Any theory how the `Â` ended up in the file on http://builds.emberjs.com/beta/ember-data.js? Also would it be possible to upload a the non broken version?

**Comment by rwjblue** [comment]
I retriggered the build on https://travis-ci.org/emberjs/data/builds/42149315 (which should push a new build), but I'm unsure how that char got into the build so it may just repeat the issue.

@bmac - Can you check once https://travis-ci.org/emberjs/data/builds/42149315 is done?

**Comment by bmac** [comment]
@rwjblue I've been restarting the build at https://travis-ci.org/emberjs/data/builds/42149315 it seems to get to the `testem-stable` step then hang until travis cancels it for timing out. I'll try again in the morning.

**Comment by bmac** [comment]
@rwjblue I can't figure out how to make the build not stall out. Is there another way to re-upload the beta file?

**Comment by wecc** [comment]
@bmac @rwjblue See #2727
