### ISSUE TITLE
Loading detail version crashes Ember-Data

### ISSUE THREAD

**Issue by flyswatter** [emberjs/data#2733]
Hi there, running ember-data beta 14 here.

I'm getting an error `calling set on destroyed object` when I receive a detailed (with relationships) version of a model I already had loaded.

See, I load up an index page like this:
```
GET /ears.json
{
  ears:[{ id: 1, ownerId: 1},
           { id: 2, ownerId: 1},
           { id: 3, ownerId: 2},
           { id: 4, ownerId: 3},
           { id: 5, ownerId: 3},
           { id: 5, ownerId: 3}]
}
```
And then I might want to look at some details of a model, and in my detail route's model, I check if the model has any relationships loaded (that it should have), and if it doesn't, I reload it, which returns more data, like this:
```
GET /ears/1.json
{
  ears:[
    id: 2,
    ownerId: 1,
    earwigs:[2,5,10]
  ],
  earwigs:[{id:2, earId: 2, poisoned:true},
                {id:5, earId: 2, poisoned:true},
                {id:10, earId: 2, poisoned:true},
  ]
}
```
Now for whatever reason, on receiving this, I get a bug thrown, saying I'm calling `set` on a destroyed object!

My stack trace looks like this:
![screen shot 2015-01-28 at 4 52 46 pm](https://cloud.githubusercontent.com/assets/542863/5950381/2cf60b9a-a70e-11e4-855c-b133b8e5fc16.png)

I was thinking maybe when Ember-data gets a new copy of the old object, it deletes it, but first takes a reference of it that it then tries to assign all the new relationships to?  Maybe that would explain how this would happen?

Any help would be greatly appreciated, thanks!

**Comment by bmac** [comment]
Hi @flyswatter. How are you checking to see if the relationship is loaded? What happens if you include an empty array for `earwigs` in your `GET /ears.json` response?

**Comment by flyswatter** [comment]
Well this is an earwig tracking application, so I only have ears containing earwigs in the database.

For that reason, I never get an empty `earwigs` array when making a detailed `ear` request, and so I can just check for any members to know if it's loaded.

I know the popular thing to do is to include the array of IDs on the original index list, but I'm loading a large enough initial list of ears, with enough earwigs per ear, that this can really slow down the request, and I was hoping to be able to provide all the relationship data on the detail request.

I thought this approach might work well, since beta-14 [now supports partial payloads](http://art-u2.infcdn.net/articles_uploads/0/967/Bear%20Hacker.jpg), but so far it seems like it doesn't know what to do when it loads a duplicate record.

**Comment by bmac** [comment]
Hi @flyswatter I attempted to put together a jsbin using the data you provided and I was unable to reproduce your issue. http://emberjs.jsbin.com/zudeku/4/edit?html,css,js,output. 

I did have to change the json for the `GET /ears/1.json` request. It appeared to be missing some `{}` around the `ears` object and it was returning data for id 2 instead of 1 but I suspect that could have been a copy and past error. 

Please check out the above jsbin and let me know what I'm missing.

**Comment by wecc** [comment]
ping @flyswatter, is this still an issue?

**Comment by flyswatter** [comment]
I've since worked around this and updated Ember, and wouldn't know how to replicate it anymore.
