### ISSUE TITLE
why no jsonp demo

### ISSUE THREAD

**Issue by clownvary** [emberjs/data#2735]
like title
- most api need cors,so jsonp is necessary
- I am a novice, I read several times the document, but are not related to the introduction
- I hope you can be a tutorial

## thanks

**Comment by wecc** [comment]
Does Ember Data even support JSONP? I don't see how that would work :confused:

**Comment by bmac** [comment]
I think it would be possible if you overwrote http://emberjs.com/api/data/classes/DS.RESTAdapter.html#method_ajaxOptions. Maybe that method should be made public?

**Comment by wecc** [comment]
Yeah, that would give you the possibility to make JSONP requests. However, to be able to handle POST/PUT/DELETE and status codes you'll have to make tightly coupled customizations with your backend and even if it _would_ be possible to do all verbs via GET (i.e. `_method`) having destructive actions over GET is generally a very bad idea.

That said, I think making `ajaxOptions` public is a good idea.

**Comment by jamiechong** [comment]
I agree that a public interface to ajaxOptions or something similar would be nice to have. You can of course still override this method as I've suggested here: 
http://stackoverflow.com/questions/14828478/ember-js-ember-data-restadapter-fail-to-load-json/28663581#28663581

**Comment by albertovasquez** [comment]
To @wecc comment.   I believe the approach of overriding the GET methods only with 

find: function(store, type, id, snapshot) {
     return this.ajax(this.buildURL(type.typeKey, id, snapshot), 'GET', { dataType: 'jsonp'});
}

then overriding ajaxOptions
ajaxOptions: function(url, type, options) {
      var dataType = options.dataType || "json";
      var hash = this._super(url, type, options);
      hash.dataType = dataType;
      return hash;
  }
