### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by aruseni** [emberjs/data#2738]
http://emberjs.com/guides/models/finding-records/#toc_querying-for-records

For some reason, there’s a comment with an example of a URL where the parameter in the query string is put into quotes.

    // => GET to /persons?name='Peter'

That’s misleading because actually strings are serialized as-is.

**Comment by wecc** [comment]
Nice catch @aruseni, would you like to create a PR fixing this at https://github.com/emberjs/website?

**Comment by aruseni** [comment]
Thanks! Yeah, sure, done that.

**Comment by teddyzeenny** [comment]
Fixed by https://github.com/emberjs/website/pull/1967
