### ISSUE TITLE
Model.save() errors when missing related objects

### ISSUE THREAD

**Issue by thomasvanlankveld** [emberjs/data#2739]
Calling `this.get('user').save();` results in

```javascript
Uncaught Error: Assertion Failed: You looked up the 'login' relationship
on a 'user' with id 3 but some of the associated records were not loaded.
Either make sure they are all loaded together with the parent record, or
specify that the relationship is async (`DS.belongsTo({ async: true })`)
```

It works when I make the login relationship async, but that's not how my app is supposed to work

**Comment by wecc** [comment]
@thomasvanlankveld if the relationship is not async you need to make sure that the related data is loaded, as the error message states. Make sure that the user with id 3 has been loaded and is available in the store.

**Comment by thomasvanlankveld** [comment]
It is available, calling `this.get('user')` gets me the user with id 3.

**Comment by wecc** [comment]
@thomasvanlankveld Would you be able to replicate this issue in a [JSBin](http://emberjs.jsbin.com/qovara/edit?html,js,output)?

**Comment by thomasvanlankveld** [comment]
Good call! I'll see if I can...

**Comment by bmac** [comment]
@thomasvanlankveld have you had a chance to create a jsbin for this error?  It sounds like Ember Data is expecting a `login` relationship to be loaded into the store for your user. Is that included in the response payload when you call `this.get('user')`?

**Comment by thomasvanlankveld** [comment]
Allright, this [jsbin](http://emberjs.jsbin.com/biramuwodo/4/edit) is not exactly the problem I mentioned before, but it does illustrate the bigger problem.

Basically, I want to declare relationships on my models to use in my app, but I don't need my app to try to fetch them for every single use case. In this JSBin I just want to be able to edit the title of the post, and the author has nothing to do with it. I need to declare the relationship though to use it in other parts of my application. But now the app crashes in the change-title page if the author is not present.

**Comment by wecc** [comment]
It looks like the serializer tries to serialize the author relationship right before saving and tries to do `get()` on it. This causes the assert to trigger since the relationship is not fully loaded, only the ID.

This is exactly the kind of issue that the Snapshot API will solve (#2623) by passing a snapshot instead of the real record to the serializer.

**Comment by lolmaus** [comment]
I'm going to have a parent-child relationship where a parent can have thousands of children. I was hoping to paginate the display of children of a parent.

But it seems that this issue will make it impossible! According to @thomasvanlankveld's JSBin, a parent record, when saved, tries to fetch all children. But my backend will refuse to give out more than a hundred children per request.

Is there a workaround for this? :worried:

**Comment by lolmaus** [comment]
I've tossed a JSBin: http://emberjs.jsbin.com/yeriga/2/edit?html,js,output

Surprisingly, it works fine with synchronous relationships. The parent record saves fine, without trying to request related records.

But if i change the relationship to async http://emberjs.jsbin.com/yeriga/3/edit?html,js,output , it tries fetching related records. Removing references to related records' ids from the template allows the app to start, but when i try saving the model, related records are also requested.

A user can have thousands of comments. I don't want to load all of them from the backend to the client's memory whenever a users updates his nickname! That's insane.

Does Ember have a solution/workaround for this, other than the unfinished Snapshot API?

**Comment by lolmaus** [comment]
Okay, i've discovered that the problem happens only with `belongsTo` relationships!

This works until you uncomment `pet: '1'` in the fixture: http://emberjs.jsbin.com/yeriga/5/edit?html,js,output

This means that i can implement pagination without any issues. And loading individual belongsTo dependencies is a bearable burden.

**Comment by lolmaus** [comment]
Thank you @bmac! Which version will it land into?

**Comment by bmac** [comment]
This will be in Ember Data 1.0.0-beta.15.
