### ISSUE TITLE
Using pushPayload to add child to the store with async parent-child relationship creates duplicates

### ISSUE THREAD

**Issue by kamal** [emberjs/data#2740]
Here's [the JSBin](http://emberjs.jsbin.com/wubevahuco/3/edit?html,js,output) illustrating the bug.

Press the "Add books" button. You'll see the books are duplicated twice.

**Comment by bmac** [comment]
Looking at the model in the Ember inspector shows the correct number of records in the relationship. I suspect this is related to as that issue also has a similar rendering bug. https://github.com/emberjs/data/issues/2713

**Comment by bmac** [comment]
I tried out pr https://github.com/emberjs/data/pull/2723 with this jsbin and it fixes the this issue.

**Comment by bmac** [comment]
Fixed by #2723
