### ISSUE TITLE
Incorrect Documentation for DS.RESTAdapter

### ISSUE THREAD

**Issue by suchitpuri** [emberjs/data#2745]
The documentation for DS.RESTAdapter says in correct behaviour.

```
Comments for a post can be loaded by post.get('comments'). The REST adapter will send a GET request to /comments?ids[]=1&ids[]=2&ids[]=3.
```
at  http://emberjs.com/guides/models/the-rest-adapter/

The above call for the relationship will happen only when coalesceFindRequests is set to true .

the default behaviour is that REST adapter will send individual get calls for each id 

```
GET /comments/1
GET /comments/2
GET /comments/3
```

**Comment by wecc** [comment]
Well spotted! Would you like to create a PR at https://github.com/emberjs/website fixing this?

**Comment by igorT** [comment]
@wecc has this been fixed?

**Comment by wecc** [comment]
@igorT open PR at https://github.com/emberjs/guides/pull/280
