### ISSUE TITLE
Warn on One to One relationships without inverse key

### ISSUE THREAD

**Issue by bmac** [emberjs/data#2748]
Occasionally, Ember Data will infer a One to One relationships that doesn't really exist. When this happens Ember Data will often set one side of the `belongsTo` relationships to null in order to keep the One to One relationship valid when a new record is introduced pointing to the (now shared) One to One relationship. This behavior can be confusing to developers because they often have a better mental model of what the relationships are suppose to look like then what Ember Data assumes the relationships look like.

I've run into this recently with my co-workers and it has also shown up recently in the form of issues in this repo https://github.com/emberjs/data/issues/2742 https://github.com/emberjs/data/issues/2744.

I could be off base here but in my experience One to One relationships are rare, As a result I think it would make sense to log a warning when Ember Data infers a One to One relationship. 

Thoughts?

Also see: https://github.com/emberjs/data/pull/2712

**Comment by wecc** [comment]
I'm :+1: on this. I just hit this exact issue a couple of days ago.

**Comment by eccegordo** [comment]
@bmac 
Good idea. Anything that adds more clarity is good. Ember data is still such a bag of hurt in part because it is too much of a black box, IMHO. 

> confusing to developers because they often have a better mental model of what the relationships are  suppose to look like then what Ember Data assumes the relationships look like.

Very much this! I think this very scenario accounts for a wide range of ember data issues, whether perceived or real.

**Comment by igorT** [comment]
Feel like we addressed this by #2712, @bmac feel free to reopen
