### ISSUE TITLE
One to one polymorphism: Cannot read typeKey of undefined

### ISSUE THREAD

**Issue by joshpfosi** [emberjs/data#2752]
I know there are lots of posts about this already but all seem to either claim its been resolved or involved a one-to-many. I am currently using `ember-data 1.0.0-beta.12` and have the following (simplified) models:

```javascript
// app/models/user.js
import DS from 'ember-data';

export default DS.Model.extend({
  email:                DS.attr('string'),
  password:             DS.attr('string'),
  passwordConfirmation: DS.attr('string'),
  role:                 DS.attr('string'),
  meta:                 DS.belongsTo('meta', { polymorphic: true, async: true })
});

// app/models/meta.js
import DS from 'ember-data';

export default DS.Model.extend({
  user: DS.belongsTo('user', { async: true })
});
```

When I try querying for a user (`this.store.find('user', 3)`), I get this stack trace:

```javascript
"TypeError: Cannot read property 'typeKey' of undefined
    at Ember.Object.extend.modelFor (http://localhost:4200/assets/vendor.js:83610:22)
    at Ember.Object.extend.recordForId (http://localhost:4200/assets/vendor.js:83065:25)
    at deserializeRecordId (http://localhost:4200/assets/vendor.js:84055:27)
    at http://localhost:4200/assets/vendor.js:84032:11
    at http://localhost:4200/assets/vendor.js:81775:20
    at Map.forEach.cb (http://localhost:4200/assets/vendor.js:29124:13)
    at OrderedSet.forEach (http://localhost:4200/assets/vendor.js:28918:13)
    at Map.forEach (http://localhost:4200/assets/vendor.js:29128:19)
    at Function.Model.reopenClass.eachRelationship (http://localhost:4200/assets/vendor.js:81774:42)
    at normalizeRelationships (http://localhost:4200/assets/vendor.js:84028:12)"
```

Does anyone know why this is happening / how to resolve it? I cannot figure it out, I've tried stepping through but I am not familiar enough with ember-data!

**Comment by csprocket777** [comment]
What does the data structure look like coming from the server?

**Comment by joshpfosi** [comment]
Sorry meant to post this too:

```javascript
{
   "user":{
      "id":3,
      "email":"mentor0@zaggle.com",
      "password":null,
      "role":"mentor",
      "tag_list":[

      ],
      "notification_ids":[

      ],
      "tags":[

      ],
      "meta":{
         "id":1,
         "name":"Jaida O'Reilly",
         "email":"mentor0@zaggle.com",
         "phone":"1-949-541-6161",
         "gender":"male",
         "picture":"/assets/face6.jpg",
         "school_id":1,
         "program_id":1,
         "has_sent_form":false,
         "is_interviewable":false,
         "student_score_avg":1.7272727272727273,
         "student_recent_score_avg":1.4285714285714286,
         "student_ids":[
            8,
            10,
            12,
            14,
            21,
            23,
            24,
            26,
            28,
            29,
            30
         ],
         "lesson_ids":[
            3,
            5,
            6,
            7,
            8,
            10,
            12,
            13,
            24,
            25,
            30,
            35,
            39,
            47,
            49
         ]
      }
   }
}
```

**Comment by csprocket777** [comment]
The meta property of the model needs only a type key so that ember data knows what type of model the relationship requires and an id. Since it's async it will look up the model of the type in the type key by the I'd you pass.

**Comment by joshpfosi** [comment]
Oh I see, this payload is coming from a rails backend using active model serializer. Any convention I'm missing to get the correct format?

**Comment by joshpfosi** [comment]
I added the fields to the serializer and it worked like a dream! Thanks

**Comment by joshpfosi** [comment]
Actually it is still not working.

The payload is:

```javascript
{"user":{"id":3,"email":"mentor0@zaggle.com","password":null,"role":"mentor","tag_list":[],"meta":{"id":1,"type":"Mentor"},"notification_ids":[],"tags":[]}}
```

If I instead return `meta_id` and `meta_type` I get no error but the `meta` field on the model is not correctly populated.

**Comment by csprocket777** [comment]
Is the model file name initial capped? Case matters I believe.

**Comment by joshpfosi** [comment]
Not sure which your asking about. Everything's copied directly if thats helpful

**Comment by csprocket777** [comment]
Then the value in type should be "mentor" instead of "Mentor". Try that.

**Comment by joshpfosi** [comment]
That didn't have any affect :(

**Comment by csprocket777** [comment]
Hmmmm. Maybe update ember data to 14.1?

**Comment by joshpfosi** [comment]
Sorry for the noobish question but what is the best way to do that? I always end up with dependency issues if I manually change my package.json or bower.json

**Comment by csprocket777** [comment]
Not sure if it's been fixed or not but I know there was an issue with the dependency checker module throwing errors. You can comment that out in your package file. Change the version numbers and the run npm install and bower install

**Comment by joshpfosi** [comment]
Both 

```javascript
{"user":{"id":3,"email":"mentor0@zaggle.com","password":null,"role":"mentor","tag_list":[],"meta":{"id":1,"type":"Mentor"},"notification_ids":[],"tags":[]}}
```

and 

```javascript
{"user":{"id":3,"email":"mentor0@zaggle.com","password":null,"role":"mentor","tag_list":[],"meta":{"id":1,"type":"mentor"},"notification_ids":[],"tags":[]}}
```

failed still

**Comment by joshpfosi** [comment]
Also, serializing the type and id as in:

```javascript
{"user":{"id":3,"email":"mentor0@zaggle.com","password":null,"role":"mentor","tag_list":[],"meta_id":1,"meta_type":"Mentor","notification_ids":[],"tags":[]}}
```

allows the `find()` promise to resolve but the `meta` field on the returned `user` is still null and the sensical warning

```
WARNING: The payload for 'user' contains these unknown keys: [meta_id,meta_type]. Make sure they've been defined in your model.
```

I just don't know what format Ember Data is expecting the payload

**Comment by csprocket777** [comment]
Here is what Ember-Data is expecting:
```
{
   "user":
             {
               "id":3,
               "email":"mentor0@zaggle.com","password":null,"role":"mentor","tag_list":[],"meta_id":1,"meta_type":"Mentor","notification_ids":[],"tags":[]}}

```

**Comment by joshpfosi** [comment]
But what DS.Model format plays nicely with that? I tried that exact format with the models in the OP and got that warning. Must I make meta a computed property based on the id and type I receive from the server?

**Comment by joshpfosi** [comment]
I've updated to 14.1 beta and still experience this issue :(

**Comment by jcope2013** [comment]
any reason why you are using the root key of meta? this is used for pagination info, etc.
I would guess that might have something to do with it

"By default, Ember Data's JSON deserializer looks for a meta key"

http://emberjs.com/guides/models/handling-metadata/

**Comment by joshpfosi** [comment]
Ooh, thank you, was not aware of that. I was following a rails convention I found online, i.e. meta for associated "role" like data. I'll rename it and try again

**Comment by bmac** [comment]
@joshpfosi did you have any luck with moving the `type` property out of the `meta` object and on to the `user` object?

**Comment by joshpfosi** [comment]
I didn't try that. Not sure I understand what you mean. Mind elaborating?

**Comment by lolmaus** [comment]
@bmac, `user` is not polymorphic.

**Comment by bmac** [comment]
Oops. Looking at the original model you posed I now see that `meta` is a belongsTo relationship. What does your `UserSerializer` look like?  I suspect it should look something like this to get the embedded `meta` relationship working.

```js
// app/serializers/user.js
// replace RESTSerializer with ActiveModelSerializer if you are using the ActiveModelAdapter
export default DS.RESTSerializer.extend(DS.EmbeddedRecordsMixin, {
  attrs: {
    meta: { embedded: 'always' }
  }
});
```

**Comment by joshpfosi** [comment]
I currently don't have a serializer. I am using the active model adapter, but no serializers. I don't feel like they should be necessary, but maybe they are?

**Comment by bmac** [comment]
Embedded records (like the `meta` object in your json response) are not supported by default in Ember Data. You need to include the `DS.EmbeddedRecordsMixin` in your serializer in order to extract embedded records from a server response.

**Comment by lolmaus** [comment]
A sidenote: when combining `DS.EmbeddedRecordsMixin` with polymorphism, the `type` property is treated both as a model attribute and a polymorphism flag. I ended up using adding `type: DS.attr('string')` to my polymorphic models to suppress "unknown attirbute" warnings.

**Comment by jorgedavila25** [comment]
Hey all, just to chime in as I had a similar problem, I got this sort of relationship by having my payload look like this: 

```javascript
{
	"artists": [{
		"id": 1,
		"name": "Papercut"
	}],
	"user": {
		"id": 2,
		"email": "jorge@goog.me",
		"metable": {
			"type": "artist",
			"id": 1
		}
	}
}
```

**Comment by wecc** [comment]
@joshpfosi does a payload like the one posted by @jorgedavila25 work? can this be closed?

**Comment by joshpfosi** [comment]
I'm not totally sure on the payload I'm using now (it is working fine). Basically, it involves manually setting `metable_type` and `metable_id` fields in the payload.
