### ISSUE TITLE
Custom Adapter fails to resolve in tests.

### ISSUE THREAD

**Issue by cah-briangantzler** [emberjs/data#2761]
When executing tests, custom adapters with dashes fail to resolve and instead return the application adapter.

https://github.com/cah-briangantzler/ember-cli-custom-adapter.git

is a repo with a failing test demonstrating this.

Originally opened on ember-cli as [Issue 3178](https://github.com/ember-cli/ember-cli/issues/3178).

**Comment by wecc** [comment]
This should no longer be an issue after ED has gone full-on dash.
