### ISSUE TITLE
jsbin in CONTRIBUTING.md is pointing to the wrong version

### ISSUE THREAD

**Issue by bmac** [emberjs/data#2764]
https://github.com/emberjs/data/blob/master/CONTRIBUTING.md

Should likely point to http://emberjs.jsbin.com/qovara/2/edit?html,js,output

**Comment by sly7-7** [comment]
@bmac seems like @wecc tried to do it in https://github.com/emberjs/data/pull/2719. Is that possible to remove the trailing "/2/edit..." in jsbin ? I mean could we tell jsbin to "save" as http://emberjs.jsbin.com/qovara/ so that we never have to update that link again and agin ?

**Comment by wecc** [comment]
I changed it to point to the "latest" version to easy future changes in the JSBin, but it seems @rwjblue has updated it to something different so yeah, specifying `/2/` would probably be a good idea.

**Comment by sly7-7** [comment]
Also, what about http://emberjs.jsbin.com/?html,js,output ? Maybe we can use it as well ? (need to add the template compiler by the way)
