### ISSUE TITLE
Relations of model in `extractSingle` method of `RESTSerialize` are not serialized

### ISSUE THREAD

**Issue by Rastopyr** [emberjs/data#2767]
If i get payload from server like this:
```javascript
{
  'user': {
    status: 1,
    type: 2
  },
  'status': {
    id: 1
  },
  'type': {
    id: 2
  }
}
```
`extractSingle` return instance of `DS.Model` with instances of `status` and `type` in `_data` property but not push they into store.
And when i tried to render handlebars template like this:
```handlebars
{{user.status.id}}
```
throwing error in console:
`Assertion Failed: You looked up the 'status' relationship on a 'admin' with id 1 but some of the associated records were not loaded. Either make sure they are all loaded together with the parent record, or specify that the relationship is async (`DS.belongsTo({ async: true })`)`

I found a reason of this error.
There are these lines in `extractSingle`:
https://github.com/emberjs/data/blob/master/packages/ember-data/lib/serializers/rest_serializer.js#L283-L287
```javascript
if (isPrimary && Ember.typeOf(value) !== "array" ) {
    primaryRecord = this.normalize(primaryType, value, prop);
    continue;
}
```
`isPrimary` is boolean flag, that shows a model which has relations. And then serialization of array is coming at the moment, if variable `value` is array.

I fixed it in a local serializer as follows:
```javascript
if (isPrimary && Ember.typeOf(value) !== "array" ) {
  primaryRecord = this.normalize(primaryType, value, prop);

  continue;
}

// if value is not primary and `typeof value === 'object'`
if(!isPrimary && Ember.typeOf(value) === "object" ) {
  var typeSerializer = store.serializerFor(type);

  store.push(type, typeSerializer.normalize(type, value, prop));
}
```

If it's a bug but not a feature, i can create a pull request with a link to this issue with fixes such as those that I wrote above.
Thanks!

**Comment by wecc** [comment]
To sideload status and type in this scenario I believe Ember Data expects the following payload:

```js
{
  'user': {
    status: 1,
    type: 2
  },
  'statuses': [{
    id: 1
  }],
  'types': [{
    id: 2
  }]
}
```

**Comment by lolmaus** [comment]
Works for me: http://emberjs.jsbin.com/noxafu/1/edit?html,js,output

**Comment by wecc** [comment]
@lolmaus Asserts are stripped in the ember-data.min.js version.

**Comment by lolmaus** [comment]
@wecc, thx for pointing that out. Indeed it stops working with a dev version of Data.

And your suggestion resolves it: http://emberjs.jsbin.com/noxafu/2/edit?html,js,output

**Comment by Rastopyr** [comment]
@lolmaus thanks. I use not latest version of library.
Ember-CLI `0.1.2` and Ember-Data `1.0.0-beta.10`
I close issue.
