### ISSUE TITLE
store.unloadAll does not reset meta data

### ISSUE THREAD

**Issue by runspired** [emberjs/data#2772]
Using ember-cli, given type `conversation-preview`, after calling `this.get('store').unloadAll('conversationPreview')` a call to `this.get('store').metadataFor('conversation-preview');` returns the stale meta data.

**Comment by bmac** [comment]
Seems like a reasonable change. @runspired would you like to submit a pr for this behavior?

**Comment by runspired** [comment]
I should be able to put one together, but I may need some additional info.

When trying to fix this locally within my app:

```
var store = this.get('store');
store.metadataFor('conversation-preview');
//{"total":10,"per_page":25,"current_page":1,"last_page":1,"from":1,"to":10}

store.typeMapFor.call(store, 'conversation-preview').metadata;
//{}

store.unloadAll('conversation-preview');

store.metadataFor('conversation-preview');
//{"total":10,"per_page":25,"current_page":1,"last_page":1,"from":1,"to":10}

store.typeMapFor.call(store, 'conversation-preview').metadata;
//{}

```

I would think these would return the same thing based on: https://github.com/emberjs/data/blob/v1.0.0-beta.14.1/packages/ember-data/lib/system/store.js#L1081-L1084

**Comment by bmac** [comment]
I think your demo example is missing [this line](https://github.com/emberjs/data/blob/v1.0.0-beta.14.1/packages/ember-data/lib/system/store.js#L1082) where the store uses the first argument to get the Model class for `'conversation-preview'` and uses that as the key for `typeMapFor`.

**Comment by runspired** [comment]
Thanks, that was all it was.
