### ISSUE TITLE
Update to the latest ember-inflector

### ISSUE THREAD

**Issue by bmac** [emberjs/data#2777]
We should update this to get the new HTMLbars helpers. 
https://github.com/stefanpenner/ember-inflector/blob/994c9a2a1759925286afbd2d16b2c50602223f35/packages/ember-inflector/lib/helpers.js#L18-L20

@fivetanley don't let me forget about this when I ask you how to do a release.

**Comment by rwjblue** [comment]
Needs https://github.com/stefanpenner/ember-inflector/issues/63 to be fixed first.

**Comment by bmac** [comment]
Closed by https://github.com/emberjs/data/pull/2778
