### ISSUE TITLE
DS.ManyArray no longer inherits from RecordArray - breaks `save()`

### ISSUE THREAD

**Issue by variousred** [emberjs/data#2782]
you can no longer call save on a manyArray like the docs demonstrate here
http://emberjs.com/api/data/classes/DS.ManyArray.html#method_save
```
var messages = store.all('message');
messages.forEach(function(message) {
  message.set('hasBeenSeen', true);
});
messages.save();
```

**Comment by wecc** [comment]
This should be fixed in canary, see #2729

**Comment by variousred** [comment]
thanks @wecc

**Comment by sly7-7** [comment]
@variousred I'm closing since it seems to be fixed on canary. Please reopen if I missed something.
