### ISSUE TITLE
store.fetch('record-type', id) with Ember.Select causes select > selection to nullify

### ISSUE THREAD

**Issue by shwoodard** [emberjs/data#2783]
description: store.fetch + view 'select' => value of selection in select set to null after fetch

str (as code snippet) here,
https://gist.github.com/shwoodard/ace3a079f144ecd9b69c

actual: model.get('key') // null
expected: model.get('key') // correct value from response

Removing select from template results in expected behavior.

Please ping me to request more info, if needed.

**Comment by shwoodard** [comment]
work around, add,

``` js
model.set('key', model._data.key);
```

where key is the selection binding on the select view.

to route or controller action in callback from fetch, or continuation of promise, e.g. `then`

**Comment by bmac** [comment]
My guess is when the page is originally loaded the `devices` array used by the `content` binding in the select view is empty. This is causing the select to choose the default value of null which sets `null` as the records's `device` property and moves it into the dirty state.

Once the real value for `device` is loaded after the fetch Ember Data's state machine detects the record has an unsaved change on the `device` property Ember Data will not overwrite this unsaved change. 

@shwoodard could you move the fetch into the `model` or `afterModel` hook? This way the page (and the select box) does not render until that fetch is complete. 

Alternately you could call `offer.rollback()` to revert any unsaved changes after the fetch is complete.

**Comment by shwoodard** [comment]
Moving to `afterModel` and returning the promise worked, but I still don't think the behavior should be this way--imho.

**Comment by fivetanley** [comment]
Ember.Select is deprecated, I don't think this is an ember data bug.
