### ISSUE TITLE
Release automation / Checklist

### ISSUE THREAD

**Issue by fivetanley** [emberjs/data#2789]
Things I can think of as @bmac and I are doing this:

* Changelog (`PRIOR_VERSION=v2.0.0 HEAD=release ./bin/changelog`)
* Bump version in package.json
* Git tag version
* Bower
* Rubygems (`gem build ember-data-source.gemspec; gem push ember-data-source-v1.0.0-beta.17.gem`)
* NPM `npm publish` or `npm publish --tag beta` (If publishing a 1.13 release update latest to be 2.x `npm dist-tag add ember-data@2.1.0 latest`)
* Website API docs
* Blog Post ( Commits since last release: `git log --oneline release..beta | wc -l`. Contributors since last release: `git shortlog -s -n release...beta | wc -l`)
* Ember-CLI (per request by @rwjblue and is also a great idea to make upgrading/new apps easier)
* Bump version in package.json back to a canary version
* (For new beta releases, branch beta from master and update https://github.com/emberjs/data/blob/master/config/features.json to have `false` values instead of `null` and update the version in package.json)

I think a lot of these could be automated using Travis CI's encrypted credentials feature.

**Comment by wecc** [comment]
@fivetanley @bmac is this still being worked on?

**Comment by bmac** [comment]
I don't know of any active work to automate this list. However, I refer to this issue all the time when doing a release and try to edit the issue to make sure its up to date.

**Comment by acorncom** [comment]
Would this tool be of any use? http://webpro.github.io/release-it/
