### ISSUE TITLE
Coalescing large requests results in 'undefined' properties in Ember Data

### ISSUE THREAD

**Issue by crsrusl** [emberjs/data#2792]
Using:
1.11.0-beta.1
1.0.0-beta.14.1

When I call the API with  

```
coalesceFindRequests: true
```

The batched JSON results are correct, but it appears that the results are not being correctly populated in Ember Data. Can confirm that this does not happen when *coalesceFindRequests* is set to *false*.

It seems that the batches some batches are being populated into Ember Data correctly, others are not. See image for template view. The text towards the bottom of the table is from a batch and is going into Ember Data correctly, whilst the rows above are blank. Looking at Ember data in the console confirms that all the properties for that batch are blank.

![screenshot 2015-02-16 11 03 45](https://cloud.githubusercontent.com/assets/1391215/6210874/fac5f6f4-b5cb-11e4-92f2-d01c9fa57f2c.png)

Take a look at Ember Data in the inspector:
![screenshot 2015-02-16 11 07 56](https://cloud.githubusercontent.com/assets/1391215/6210882/2706bb90-b5cc-11e4-91bf-5f83c3c90f8a.png)

That is not representative of the data coming back down from the server.

**Comment by bmac** [comment]
Thanks for the bug report @crsrusl. I know this is kinda a pain but would you be able to set up a simplified jsbin demonstrating this problem? Here is one to start with: http://emberjs.jsbin.com/qovara/2/edit?html,js,output 

I'll try to look into this if I can but I haven't worked with a backend that supports `coalesceFindRequests` so I don't have much experience.  @igorT if you have time could you take a look at this issue?

**Comment by crsrusl** [comment]
So it turns out the probldem was the number of results returnable by the server per request was limit to 20. Ember was expected over 50. Have increased the default number of objects the server can return.

Are we able to set the batch size ember requests?

**Comment by sly7-7** [comment]
@crsrusl for now I think you only have [maxUrlLength property](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/adapters/rest_adapter.js#L675), and then ED will determine the batch size.
Maybe having the batch size would be to consider ?

**Comment by bmac** [comment]
Ember Data should probably assert if the number of results returned by the server doesn't match the expected number requested.
