### ISSUE TITLE
"EmbeddedRecordsMixin belongsTo serialize" used "records" instead of "record"

### ISSUE THREAD

**Issue by Chun-Yang** [emberjs/data#2794]
When a comment belongsTo a user, we should be able to embed user inside comment and configure CommentSerializer like the following:
```
App.CommentSerializer = DS.RESTSerializer.extend( DS.EmbeddedRecordsMixin, {
  attrs: {
    user: {
      serialize: 'record',   // this is NOT working. However 'records' works.
      deserialize: 'record'
    }
  }
});
```
However 'record' does not work and 'records' works which is confusing.

I will probably create a PR later.

**Comment by bmac** [comment]
@igorT @wycats thoughts?

**Comment by igorT** [comment]
Is this still an issue? Can someone double check/pr?

**Comment by wecc** [comment]
All code and docs refer to this as `'records'`, not `'record'`. Is this issue just about the aesthetics?

Correction, there is one instance of `'record'` in the docs: https://github.com/emberjs/data/blob/master/packages/ember-data/lib/serializers/embedded-records-mixin.js#L72
