### ISSUE TITLE
Snapshot not being injected on beta.15

### ISSUE THREAD

**Issue by kurko** [emberjs/data#2801]
After updating to beta.15, snapshots are blocking me. It looks like they're not being passed into the serializer by ED. 

### Additional info

Although I'm using [ember-json-api](https://github.com/kurko/ember-json-api), which currently descends from RESTAdapter, the adapter has no code adapter code for fetching data.

### Code where problem happens

This is `#serializeAttribute` inside JSONSerializer:

![](http://cl.ly/image/411R3b0x251W/Image%202015-02-19%20at%208.54.58%20AM.png)

Here's some information about it.

![screen shot 2015-02-19 at 8 55 47 am](https://cloud.githubusercontent.com/assets/70312/6265416/34fdaa60-b815-11e4-8bc1-ab1370014966.png)

I expected snapshots to respond to `attr()`, but it seems not to be a snapshot at all. Does anyone has the slightest idea about what's going on? @wecc?

### Update 1

**Backtrace:**

```
TypeError: undefined is not a function↵
    at eval (eval at evaluate (unknown source), <anonymous>:1:10)↵
    at Object.InjectedScript._evaluateOn (<anonymous>:777:55)↵
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:710:34)↵
    at Object.InjectedScript.evaluateOnCallFrame (<anonymous>:828:21)↵
    at ember$data$lib$system$serializer$$default.extend.serializeAttribute (http://localhost:4200/assets/vendor.js:71884:11)↵
    at null.<anonymous> (http://localhost:4200/assets/vendor.js:71815:16)↵
    at null.<anonymous> (http://localhost:4200/assets/vendor.js:77769:20)↵
    at Map.forEach.cb (http://localhost:4200/assets/vendor.js:27723:22)↵
    at OrderedSet.forEach (http://localhost:4200/assets/vendor.js:27518:13)↵
    at Map.forEach (http://localhost:4200/assets/vendor.js:27731:19)"get stack: function () { [native code] }
```

Here's the line that's calling `serializeAttribute` (`vendor:71815`):

```js
var ember$data$lib$serializers$json_serializer$$default = ember$data$lib$system$serializer$$default.extend({
  // ...  
  serialize: function(snapshot, options) {
    var json = {};

    if (options && options.includeId) {
      var id = snapshot.id;

      if (id) {
        json[ember$data$lib$serializers$json_serializer$$get(this, 'primaryKey')] = id;
      }
    }

    snapshot.eachAttribute(function(key, attribute) {
      this.serializeAttribute(snapshot, json, key, attribute); // <============
    }, this);

    snapshot.eachRelationship(function(key, relationship) {
      if (relationship.kind === 'belongsTo') {
        this.serializeBelongsTo(snapshot, json, relationship);
      } else if (relationship.kind === 'hasMany') {
        this.serializeHasMany(snapshot, json, relationship);
      }
    }, this);

    return json;
  },

  // ...
}
```

**Comment by wecc** [comment]
@kurko hrm, would you be able to provide a stack trace? Something seem to be calling `serializeAttribute()` with a DS.Model instead of a DS.Snapshot.

**Comment by kurko** [comment]
Added **Update 1**.

**Comment by wecc** [comment]
@kurko thanks! can we trace this further back? what's calling `serialize()`? somewhere in the chain, something is passing a record instead of a snapshot.

**Comment by kurko** [comment]
Just found the issue. [ember-sync](https://github.com/kurko/ember-sync) calls record.serialize. I have to create a patch to conform with beta.15.

Thanks very much. Will reopen if I find any other place with problems.

**Comment by esbanarango** [comment]
I just updated to `beta.15` and I'm getting this same behaviour. @kurko what did you do to fix it?

**Comment by wecc** [comment]
@esbanarango are you using ember-sync or any custom adapter/serializer? I would suspect that there's a code path somewhere that passes the model itself instead of a snapshot to the serializer.
