### ISSUE TITLE
BelongsTo wrong type assertion should be more clear

### ISSUE THREAD

**Issue by igorT** [emberjs/data#2802]
The hasMany one is much nicer. We should make the belongsTo one follow it's format.

**Comment by omarismail** [comment]
Hey @igorT, I would like to work on this. Could I perhaps have more direction?

**Comment by wecc** [comment]
@omarismail I think it's [this](https://github.com/emberjs/data/blob/v1.0.0-beta.15/packages/ember-data/lib/system/relationships/state/belongs_to.js#L63) vs. [this](https://github.com/emberjs/data/blob/v1.0.0-beta.15/packages/ember-data/lib/system/relationships/state/has_many.js#L88).

**Comment by omarismail** [comment]
thanks @wecc, working on it now.

**Comment by bmac** [comment]
Closing because it looks like this was fixed by #2810. Feel free to reopen if I'm wrong.
