### ISSUE TITLE
Deprecate FixtureAdapter

### ISSUE THREAD

**Issue by bmac** [emberjs/data#2804]
move FixtureAdapter into a plugin. The motivation is described in this rfc https://github.com/fivetanley/rfcs/blob/ember-data-testing-helpers/active/0000-ember-data-testing-helpers.md

**Comment by knownasilya** [comment]
Should this be an ember-cli addon?

**Comment by knownasilya** [comment]
Looks like the work was started here https://github.com/emberjs/ember-data-fixture-adapter

**Comment by igorT** [comment]
I think this was done, cc @fiv
