### ISSUE TITLE
Correct way to set content on model in afterModel hook on ember data beta 1.0.0-beta.15?

### ISSUE THREAD

**Issue by jcope2013** [emberjs/data#2805]
in the past, i did something like this

```
afterModel: function(model, transition) {
    var filteredStaff = model.toArray().filter(function(item, index, self) {
  			if (!Ember.isEqual(item.get('firstName'), 'Admin')) { return true; }
		});
      model.set('content', filteredStaff);
   }
```

now with the changes to the ManyArray that mention not relying on the underlying content

"ManyArray, the object Ember Data uses to represent DS.hasMany relationships has been changed so it no longer extends from RecordArray. This means if you were relying on the RecordArray's content property to access the underlying array you will now need to use the .toArray() method."

the above code is problematic as the controller is an arrayController with a table in the template and you can delete record's, this removes the record from the store but not from the underlying controller property in the template as it's still hanging around inside the content of the model, removing this code or using it on ember data beta 1.0.0-beta.12 confirm my observations, what is now the correct way to set the model content in the afterModel hook?

**Comment by stefanpenner** [comment]
i do not believe this is any longer supported.

**Comment by jcope2013** [comment]
@stefanpenner so there is no longer a way to set the model content in the afterModel hook? what is the recommend solution moving forward?

**Comment by wecc** [comment]
@jcope2013 In this case, I think it would make sense to define a CP in your controller/component and use that property instead of `model` directly:

```
filteredStaff: Ember.computed.filter('model', function(item) {
  return !item.get('firstName') === 'Admin';
})
```

**Comment by jcope2013** [comment]
@wecc but in the case, if an item get's deleted that was in filteredStaff using deleteRecord and save using a modal action on the table  and the content for my table is filteredStaff, then it will get messed up and have a row with null values or blank values as that won't get triggered on deletion

**Comment by sly7-7** [comment]
@jcope2013 Wouldn't it be possible to do this stuff in the model hook, by returning the filtered stuff from the promise chain ?

**Comment by jcope2013** [comment]
my mistake

**Comment by sly7-7** [comment]
@jcope2013 I'm interrested on the solution you've found :)

**Comment by jcope2013** [comment]
@sly7-7 

'''
afterModel: function(model, transition) {
    var filteredStaff = model.toArray().filter(function(item, index, self) {
            if (!Ember.isEqual(item.get('firstName'), 'Admin')) { return true; }
        });
      model.set('content.content', filteredStaff);
   }
'''

originally i had this before upgrading to beta 1.15 and at some point somehow switched it out to just set model.content, it wasn't working then I eventually realized that an extra content got taken out and it was fixed so ended up not being caused by upgrade, stupid mistake for sure
