### ISSUE TITLE
[Feature request] Generate node express api from ember-data model

### ISSUE THREAD

**Issue by QuantumInformation** [emberjs/data#2808]
I am building a client side app using only ember+ember-data and ember-cli generated mocks, but want to persist it on the server without manually writing an express server api. It would be nice to be able to generated a node express server from an ember data model.

Could we generate code that exposes the express api with a separate layer that contains the logic for persisting to the persistance layer(eg mongo or postgresql), so that we could write separate adapters to this without effecting the express layer.

**Comment by tkellen** [comment]
Yes!  You're looking for http://github.com/endpoints/endpoints

**Comment by tkellen** [comment]
It's not quite ready, but it's coming along well.

**Comment by fivetanley** [comment]
There is also http://fortunejs.com/ which you should keep an eye on. Please keep in mind that the jsonapi spec recently underwent some changes, so I don't know if endpoints or fortunejs is up to date, but they both look like good projects that should suit your needs. I don't think we'll be maintaining a server for ember data at this time, but hooray for everyone stepping up to it!

@wecc has recently started work on a JSONAPI adapter, and we'll keep you posted with progress. Thanks!

**Comment by QuantumInformation** [comment]
@fivetanley  Why would we need a server for ember data, can't we just generate what you fortunejs needs from the ember-data object once each time the ember model changes changes its structure?
