### ISSUE TITLE
appveyor is broken again

### ISSUE THREAD

**Issue by bmac** [emberjs/data#2813]
https://ci.appveyor.com/project/embercli/data/build/393

@johanneswuerbach any chance you have some time to look into this again?

**Comment by johanneswuerbach** [comment]
You can copy https://github.com/ember-cli/ember-cli/pull/3322 before https://github.com/airportyh/testem/pull/505 is fixed

**Comment by bmac** [comment]
Thanks. I'll try it out

**Comment by bmac** [comment]
Worked great. Thanks again
