### ISSUE TITLE
belongTo relationship on new record wiped when parent is reloaded async

### ISSUE THREAD

**Issue by hlogmans** [emberjs/data#2819]
Ember Data               : 1.0.0-beta.12

I found an interesting situation, I could not find if this was an known or solved issue (there are quite some issues open with the obvious keywords). I am using the ActiveModelAdapter.

In my router I create a new child record for a 'hasMany' relationship. Of course the parent is known. But the parent of the parent is not, and it is being loaded for the breadcrumbs. When this 'grandparent' is loaded, it's childs are sideloaded to speed up tje navigation tree. But this sideloading causes the parent on my new record to be cleared, probably because new child_ids of the parent are updated, and of course it does not know of the new record. 

I have found a workaround (setting the parent on save), but I was curious if this should not happen or not.

Thanks for all the effort you all put in this project!

**Comment by bmac** [comment]
Hi @hlogmans thanks for opening the issue. It sounds to me like something that should not happen. Would it be possible for you to put together a js bin demoing the issue? That would be extremely helpful in helping me track down the root problem. Here is an example jsbin to get you started. http://emberjs.jsbin.com/qovara/2/edit?html,js,output

**Comment by hlogmans** [comment]
I'll try to, I'm a novice on Ember so it could take some time :) I think the first problem will be how to simulate the background fetch of the record that will override the child ids. Maybe you have some example link?

**Comment by pangratz** [comment]
I am going to close this, as I think this is resolved in [`ember-data v2.x`](https://github.com/emberjs/data/blob/v2.4.3/addon/-private/system/many-array.js#L80-L84) and it has been backported to [`ember-data v1.13.x`](https://github.com/emberjs/data/blob/v1.13.16/packages/ember-data/lib/system/many-array.js#L80-L84).

@hlogmans please feel free to open a new issue if you are still running into this. Also feel free to ping me when you need help to reproduce this in an [`ember-twiddle`](https://ember-twiddle.com/0e1a24aabb8fa7c1fdd8/copy?fileTreeShown=false&numColumns=2&openFiles=initializers.pretender.js%2Cmodels.person.js).
