### ISSUE TITLE
store.push doesn't work with embedded records

### ISSUE THREAD

**Issue by 1pete** [emberjs/data#2826]
I have a serializer for an article model like this
```
ArticleSerializer = DS.RESTSerializer.extend(DS.EmbeddedRecordsMixin, {
  attrs: {tags: {embedded: 'always'}}
})
```

Before payload from server has embedded object, I can write ```store.push``` like this
```
return this.store.push('article', articleObj);
```
But when server return article payload with embedded object, I've got assert error from [deserializeRecordId](/emberjs/data/blob/b8aff0910775f864d6f918ecda1333491a3c001f/packages/ember-data/lib/system/store.js#L1887).

My workaround is to change ```push``` to ```pushPayload```
```
this.store.pushPayload('article', {articles: articleObj});
return this.store.find('article', articleObj.id);
```
Everything is as expected, but somehow I feel not good to writing code this way.
Is ```store.push``` supported for embedded records, and am I writing this correctly?

Thanks

**Comment by bmac** [comment]
Before you push the record into the store you need to `normalize` the Data first to extract the embedded record. http://emberjs.com/api/data/classes/DS.Store.html#method_normalize.
```js
return this.store.push('article', this.store.normalize('article', articleObj));
```

**Comment by 1pete** [comment]
Thank you ;)
