### ISSUE TITLE
Nested isDirty flag not being cleared on reverting changes to data

### ISSUE THREAD

**Issue by zyllorion** [emberjs/data#2827]
Ember Canary
ED b15

```
function() {
return this.get('isDirty') || this.get('nestedModel.isDirty');
}
.property('isDirty','nestedModel.isDirty')
```
Works great, mostly.  If I make a change to parent model and undo the isDirty is cleared, but if I make a change to the nested model and undo the isDirty persists (the computed function doesn't get called again).

The models relationship is defined as belongsTo<>belongsTo with the inverse option set on both sides.

**Comment by zyllorion** [comment]
With further testing seems to be a bug in the both the main and embedded models individual status with a specific field - there's still something strange going on but I can't isolate yet and the above does seem to work fine.  Closing to avoid confusion.

**Comment by lolmaus** [comment]
Works for me: http://emberjs.jsbin.com/bijimo/1/edit?html,js,output

**Comment by lolmaus** [comment]
@zyllorion, by the way, check out this: https://github.com/lolmaus/ember-cli-stained-by-children/
