### ISSUE TITLE
Predefined query URLs difficult in RESTAdapter

### ISSUE THREAD

**Issue by jamesarosen** [emberjs/data#2834]
I have a model, `User`. In addition to supporting things like `GET /users` and `GET /users?page=1`, my server has some predefined optimized filters like `/users/active`, `/users/inactive`, and `/users/recently-created`.

I'm trying to write a `UserAdapter` that supports this, but I'm having trouble.

### Attempt 1

My first instinct was to define `buildURL`, but that function doesn't get the `query`. `RESTAdapter.prototype.findQuery` looks like [this](https://github.com/emberjs/data/blob/c13a61bab6662255b7195f98dc0af0c5802228e3/packages/ember-data/lib/adapters/rest_adapter.js#L388-L393):

```js
findQuery: function(store, type, query) {
  if (this.sortQueryParams) {
    query = this.sortQueryParams(query);
  }
  return this.ajax(this.buildURL(type.typeKey), 'GET', { data: query });
}
```

That is, it just tacks the query on to the _all_ URL as query parameters.

### Attempt 2

My second idea was to override `findQuery` itself. Its surface area is fairly small, so that would be pretty easy:

```js
findQuery: function(store, type, query) {
  if (this.sortQueryParams) {
    query = this.sortQueryParams(query);
  }
  var url = this.buildURL(type.typeKey);
  if (query.subset) {
    url += '/' + subset;
    delete query.subset;
  }
  return this.ajax(url, 'GET', { data: query });
}
```
This works -- in theory. The problem is that `findQuery` is _private_, which means I'm not allowed to override it in my adapter.

### Recommendation

Either

 1. change the API of `buildURL` to `buildURL(type, id, record, query)`
 2. make `findQuery` protected or public

**Comment by hcatlin** [comment]
Agreed that this would be awesome. I tend to deal with these not as cleanly... by using pushPayload and an Ajax request that I manage. ;P

**Comment by jamesarosen** [comment]
@hcatlin thanks for the suggestion of a workaround! I'll use that for now :)

**Comment by hcatlin** [comment]
Actually, I have discovered a much, much easier way to do this. In Ember Data, the relationship between the query and the response is pretty loose. That is, the `RESTSerializer` will deal with a lot of different types of data coming back... plurals, singulars... (almost) whatever!

I just realized today, that if I define `/projects/current` on my API, then issue `this.store.find('project', 'current');`, the store will happily hit the path above, and then deal with a non-matching id coming back. I'm using it for singulars, but after looking at how `RESTSerializer` works, it seems that it should be just fine with a list of `projects` coming back.

**I don't think you have to do any magic overriding to get this working**

Let me know if that works!

**Comment by hcatlin** [comment]
And, shit, I think I was wrong. *sigh*.

**Comment by hjdivad** [comment]
FWIW I'm also overriding `findQuery`.  It's an obvious place to support these kinds of queries; it makes sense to me for this (or perhaps something similar) to be public.

**Comment by wecc** [comment]
@jamesarosen @hcatlin @hjdivad there's been work done in the [BuildURLMixin](http://emberjs.com/api/data/classes/DS.BuildURLMixin.html) that I suspect would make this a lot easier. Would any of you be able to confirm if the `query` sent to `buildURL` or alternatively override `urlForFindQuery` solves this?

**Comment by hjdivad** [comment]
@wecc what's the reason for making this a mixin rather than having it in the base adapter?

**Comment by wecc** [comment]
@hjdivad an adapter doesn't necessarily have to talk to the storage with AJAX

**Comment by hjdivad** [comment]
@wecc makes sense; still, if the app adapter is already extending `DS.ActiveModelAdapter` the mixin is an implementation detail app authors don't need to know about right?

**Comment by wecc** [comment]
@hjdivad confirm

**Comment by wecc** [comment]
@jamesarosen @hcatlin @hjdivad did overriding `urlForQueryRecord` work? can this issue be closed?

**Comment by hjdivad** [comment]
@wecc can't say, still on an older version of ember-data, I'm afraid.

**Comment by CarlosV89** [comment]
Overwriting the urlForFindRecord worked for me ie: ```javascriptreturn \`${namespace}/collection/${id}?${includeItemParam}&${includeLastModifiedUserParam}/`; `

**Comment by fivetanley** [comment]
Seems to be satisfied by the new buildURL hooks @wecc linked to above.
