### ISSUE TITLE
pushPayload and meta data

### ISSUE THREAD

**Issue by hcatlin** [emberjs/data#2836]
I'm using websockets to send data back to my application, and so I'm using `pushPayload` to update the store. My data looks something like this:

````
{
  "user": { 
    "id": "hcatlin"
  },
  "meta": {
    "online": 12
  }
}
````

That response works great for `store.find` and the like, but totally fails on `pushPayload`.

````
this.store.pushPayload('user', data);
````

I get the error, "can't find model metum", which is pushPayload adorably thinking that `meta` isn't something special.

So! I have to do this to get it working.

````
this.store.setMetadataFor('user', data.meta);
delete data.meta;
this.store.pushPayload('user', data);
````

Seems like `pushPayload` should know how to deal with metadata... if that's the go-to entry point for things like WS.

Am I crazy?

**Comment by fivetanley** [comment]
@igorT says this should be fixed by the new serializer API in https://github.com/emberjs/data/pull/2837, please re-open if it's still an issue.
