### ISSUE TITLE
if a relationship is not sideloaded, load it asynchronously

### ISSUE THREAD

**Issue by r4m** [emberjs/data#2839]
Generally ember-data launches an error if a non-async-declared relationship isn't sideloaded in a json response.

I do not understand why the default behavior is not to try to load it asynchronously instead of throwing an exception; or, at least, I'd like to specify programmatically in a model that in a first attempt when a object is deserialized Ember looks for a sideloaded relationship, then it tries to download it asynchronously. Moreover, the relationship in both cases has to be treated in the same way, i.e. being a reference to a stored object (which is not actually the case because if it is declared async it is considered a promise object, otherwise it is a "content"... which forces you to customize your model, properties and observers taking into account if the relationship is async or not)

Suppose for example that there is a user A create a todo T1 that belongs to a project P2. the user B by hypothesis can access T1 but not P1. I'd like to serialize T1 preserving the id of P1 as projectId attribute of T, but I do not want to sideload P1 since its content isn't available to B. What I can do with ember-data is declare the relationship async, in this way when ember requests P1 the server replies with a 403 error.

However if I do that it means that every time I try to download a todo, its model expects to deal with async related project. Instead, I'd like that in general the project can be sideloaded and when it cannot be sideloaded (e.g. if the project is private) ember automatically tries to load it asynchronously instead of complaining with an assertion failure.

**Comment by bmac** [comment]
Hi @r4m. I believe one of the reasons why Ember Data chose to throw an error instead of asynchronously loading is to prevent sublet errors that can happen as your navigate around in your application. For example, in common flow you might see a relationship get loaded asyncrously as your navigate from page to page until you arrive on a page that assumes the relationship has already been loaded. However, if you were to reload the page, your code may break because relationship has not been previously loaded.

As Ember Data gets better tools for working with async relationships I think we will see Ember Data encouraging async relationships for most relationships which should hopefully alleviate this issue.

**Comment by r4m** [comment]
@bmac yes I see. But I pose another question: suppose that the sideloaded data cannot always be present. For example: you a permission system that sideload data depending on the "readable" property of the data. Ember data will throw an exception just because it founds a foreign key but it does not found a sideloaded object. How can I silently handle this dynamic behaviour? Probably a solution is to always consider data as async loaded to avoid that someone can access associated data that it is not authorized to read, even if you are force to deal with more requests that can fail.

**Comment by igorT** [comment]
That seems like a very strange api, where it gives you a foreign key but doesn't let you access the object itself? Have you actually seen this case in a reallapp?

**Comment by r4m** [comment]
@igorT the use case is the following:
consider to have two users, called A and B, and two entities, E1 and E2, where E2 belongs to E1. Consider that there are two users roles: "R1", where a user can read all the data (both E1 and E2), "R2", where a user can only read E1.
- user A has role R1, user B has role R2.
- user A create an instance of E1, linked to an instance of E2, hence a foreign key for E2 (e.g. e2_id) is stored in E1. User A can read E1 and also E2, since it has role R1.
- user B instead, can read E1, it can see the value of the foreign key for E2 (which is not nil), but I cannot read E2 attributes, due to its role R2. Potentially, E2 isn't sideloaded neither readable by a get request by id.

this is a real case where different read permissions take place.
do you agree? is it right or am I missing something?

**Comment by runspired** [comment]
Just some input as this is all hashed out, I async my side-loaded relationships and then queue them up to be loaded later.  I've found that scheduling the processing of side-loaded data is often preferable.

**Comment by fivetanley** [comment]
This API seems to have a lot of edge-cases that I don't think we can implement in a general manner. @runspired @r4m maybe I just misunderstand the request, but this feels like the use case `hasMany({async: true})` was designed for. Feel free to re-open if you think there is a path forward here. Perhaps [references](http://emberjs.com/blog/2016/01/12/ember-data-2-3-released.html#toc_code-ds-references-code) can help you implement this in your own app.
