### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by tchak** [emberjs/data#2840]
- [ ] add different type of errors (`AdapterError`, `ValidationError`)
- [ ] always reject in the adapter with custom errors (stop leaking jQuery)
- [ ] align `extractErrors` with `json:api` and new typed semantics
- [ ] reject with custom errors on fetch operations

Some discussion in progress in #2658
Some work in progress in https://github.com/tchak/data/tree/errors-with-types with @twokul

**Comment by twokul** [comment]
- [ ] add fetch polyfill

**Comment by bmac** [comment]
Closing per @twokul request.

**Comment by twokul** [comment]
@tchak feel super bad closing it but I need to be able to edit checklist, sorry :(
