### ISSUE TITLE
coalesceUpdates/bulkCommit functionality missing

### ISSUE THREAD

**Issue by zyllorion** [emberjs/data#2845]
Hi,

I need to do a simple value swap of two records, "order", and persist this through REST/JSON.  If one of the value updates fails, the data becomes corrupted (both records cannot have the same value for "order").

Ember used to support transactions, now does not.

Ember currently supports http://ember-doc.com/classes/DS.RESTAdapter.html#property_coalesceFindRequests but no equivalent for updates, creates or deletes (obviously I'm specifically interested in updates).  Adding the coalesceFindRequests: true to DS.RESTAdapter does nothing.

Ideally this would be supported by ember-data in some way.  Given that's not likely to happen in the short term, how can I manually serialise an array of records and send those to the adapter?

Thanks

**Comment by bmac** [comment]
Hi @zyllorion. I think you hit the nail on the head and this is likely not going to be a feature that Ember Data will include in the short term. If you'd like to take a stab at designing an api for this and submitting an [RFC](https://github.com/emberjs/rfcs) that would be appreciated. As a workaround for today, the only way I can think of sending multiple records to the server at the same time would be to create custom Adapter that knows how to serialize multiple records then include all of the records you want to serialize in an `hasMany` relationship on a model.

**Comment by fivetanley** [comment]
closing as dup of https://github.com/emberjs/data/issues/1849, but an RFC would be awesome!
