### ISSUE TITLE
Async manyToOne relationships not serialized

### ISSUE THREAD

**Issue by knownasilya** [emberjs/data#2847]
```js
// plan model
export default DS.Model.extend({
  name: attr('string'),
  workouts: hasMany('workout', { async: true, inverse: 'plan' })
});

//workout model
export default DS.Model.extend({
  name: attr('string'),
  routines: hasMany('routine', { async: true }),
  plan: belongsTo('plan', { async: true, inverse: 'workouts' })
});
```

So if I create a workout with a plan, and then access that plan where the workout is loaded it shows all of the plans workouts. If i access the plan afterwards directly (no loading workouts first), the plan doesn't load the workouts. There is no request to the server.

In beta.14.1 and beta.15

**Comment by knownasilya** [comment]
I'll try to create a jsbin..

**Comment by bmac** [comment]
ping @igorT do we support `async: true` relations on both sides of the relationship? I know that was an issue in the past.

**Comment by knownasilya** [comment]
@bmac if ED doesn't, what's the alternative? Just remove the inverse and set them in both places?

**Comment by bmac** [comment]
@knownasilya I think you can remove the async from one side of the relationship and the inverse property will automatically figure itself out.

**Comment by knownasilya** [comment]
@bmac do I have to set the plan on one and add the workout on the other? Or can I add the plan, and then just save it? This is a confusing workflow..

```js
workout.set('plan', plan);

workout.save()
  .then(function (saved) {
    plan.get('workouts').addObject(workout);
    plan.save();
  });
```
```

**Comment by igorT** [comment]
@bmac I don't think that has been an issue for a very long time, we have tests for those I think.  Unless I missed something. A link to an issue? @knownasilya  A JSbin would be most helpful

**Comment by knownasilya** [comment]
With inverse on one side I get this error:

```
Uncaught TypeError: Cannot read property 'destroy' of undefinedember.debug.js:41069 ContainerView.extend.arrayWillChangeember.debug.js:40988 (anonymous function)ember.debug.js:18642 applyStrember.debug.js:12794 sendEventember.debug.js:16219 notifyBeforeObserversember.debug.js:15995 propertyWillChangeember.debug.js:16501 setember.debug.js:16565 trySetember.debug.js:14639 (anonymous function)ember.debug.js:12684 tryableember.debug.js:18402 tryFinallyember.debug.js:12687 suspendListenerember.debug.js:15329 _suspendObserverember.debug.js:14638 onNotifyember.debug.js:17427 Stream._notifySubscribersember.debug.js:17389 Stream.notifyExceptember.debug.js:17528 merge._syncember.debug.js:854 Queue.invokeember.debug.js:919 Queue.flushember.debug.js:724 DeferredActionQueues.flushember.debug.js:149 Backburner.endember.debug.js:204 Backburner.runember.debug.js:16638 runrest_adapter.js:820 ember$data$lib$system$adapter$$Adapter.extend.ajax.Ember.RSVP.Promise.hash.successjquery.js:3143 jQuery.Callbacks.firejquery.js:3255 jQuery.Callbacks.self.fireWithjquery.js:9309 donejquery.js:9713 jQuery.ajaxTransport.send.callback
```

**Comment by igorT** [comment]
A JSbin?

**Comment by knownasilya** [comment]
I created a [jsbin](http://jsbin.com/tawegi/6/edit) but wasn't able to recreate. Going to try and go through my code tonight and try to fix it again..

**Comment by knownasilya** [comment]
So the put to plans doesn't get the workouts attribute

**Comment by knownasilya** [comment]
So the plan looks fine while the workouts are in the store,  but if you just load the plan it only loads the workouts that are in the `workouts` attribute already (hard coded).

**Comment by knownasilya** [comment]
Even without any inverses, seems like the snapshot API doesn't return the hasManys,when using `record._createSnapshot();` in `updateRecord` of the RESTAdapter.

**Comment by knownasilya** [comment]
So in `serializeHasMany` the `relationshipType` is a 'manyToOne', which doesn't get serialized..

**Comment by knownasilya** [comment]
Ping @bmac @igorT

**Comment by igorT** [comment]
I am a bit lost. So `ManyToOne` are not serialized by default, it's easily overwritable. Is there a different bug, with the `destroy` message you mentioned?

**Comment by knownasilya** [comment]
Couldn't recreate the destroy message.

So if manyToOne are not serialized, is the user supposed to do all the work on the many side then? What are the conventions for this kind of setup?

**Comment by knownasilya** [comment]
For anyone experiencing this, see this [SO question/answer](http://stackoverflow.com/a/24619032/483616). The other answers are valid also.

I like the suggestion of one of the commenters:
> For serialization, best would perhaps be that relationship.options have "serialize" : true/false

**Comment by igorT** [comment]
You can now also say `{serialize: true}` and don't need the embeddedRecordsMixin

**Comment by knownasilya** [comment]
@igorT like `workouts: hasMany('workout', { serialize: true })`?

**Comment by knownasilya** [comment]
@igorT and that will serialize the ids only?

**Comment by igorT** [comment]
correct. It is not. Keep in mind that the serialize options is in the serializer attrs hash

**Comment by knownasilya** [comment]
Yes, this still doesn't work for me:

```js
// plan model
import DS from 'ember-data';

const {
  attr,
  hasMany,
} = DS;

export default DS.Model.extend({
  name: attr('string'),
  workouts: hasMany('workout', { async: true })
});
```

```js
//plan seriailizer
import DS from 'ember-data';

export default DS.RESTSerializer.extend({
  attrs: {
    workouts: { serialize: true }
  }
});
```

I do `plan.get('workouts').addObject(workout);` but `workouts` don't come across the wire, just `name`.

**Comment by igorT** [comment]
Are you on canary?

**Comment by knownasilya** [comment]
No, 19.2 with ember 1.12.1

**Comment by igorT** [comment]
This hasn't been released yet, should be soon

**Comment by knownasilya** [comment]
Confirmed working on canary.

P.S. Can we remove ember-data from package.json? Seems like it doesn't matter, since I didn't change that to canary..
