### ISSUE TITLE
Duplicate records when saving new embedded records

### ISSUE THREAD

**Issue by jakesjews** [emberjs/data#2850]
When we save a new record with a new embedded record field in a hasMany relationship duplicate records are being created after the server responds with an embedded record with a non-null id.  So after the save, we have one version of the record with a null id, and another with the id from the server (they aren't being merged correctly).

This is issue is not present in beta 12.

A JS Bin replicating the issue can be found [here](http://jsbin.com/vejuha/2/edit)

**Comment by jnfisher** [comment]
+1 I'm seeing the same problem since beta 14.

**Comment by yokree** [comment]
+1

**Comment by jeanettehead** [comment]
+1

**Comment by 20v100** [comment]
+1

**Comment by wcurtis** [comment]
+1 Issue still exists with beta 16

**Comment by sandstrom** [comment]
Probably a duplicate of https://github.com/emberjs/data/issues/1829 (I'd say close this issue in favour of the existing one).

More details:
- https://github.com/emberjs/data/issues/1829#issuecomment-42551445
- https://github.com/json-api/json-api/issues/202

**Comment by edson-** [comment]
From above: "This is issue is not present in beta 12."

I'm seeing this in beta 12 also.

**Comment by DanLeininger** [comment]
+1

**Comment by ericop** [comment]
+1

**Comment by abulrim** [comment]
You can use this temporary solution:
```javascript
this.get('model').save().then(function(levelOne) {
  levelOne.get('levelTwo').filterBy('isNew').invoke('unloadRecord');
});
```

**Comment by Gowiem** [comment]
+1 Just updated from beta-12 to beta-16.1 in an effort to get my Rails asset pipeline code on the same version of some new EmberCLI code and ran into this.

**Comment by WooDzu** [comment]
@abulrim your workaround did the trick for me. Thanks!

**Comment by tamarasaurus** [comment]
+1

**Comment by sdahlbac** [comment]
+1 (the workaround by @abulrim works though)

**Comment by wecc** [comment]
Closing as a duplicate of #1829. Please reopen if not.
