### ISSUE TITLE
Unloading record with loaded relationship causes error

### ISSUE THREAD

**Issue by piotrpalek** [emberjs/data#2851]
Hey I have an issue when I unload a model that has models in it's relationship, and the reload the route. It's a bit hard to explain I've put up a jsbin example here: http://emberjs.jsbin.com/mazopeburo/2/edit

I am not sure if I am doing something wrong, but there's nothing in the docs that indicate I have to unload relationships first before unloading the main record so I am assuming this could be some unresolved issue.

**Comment by igorT** [comment]
We are tracking this under https://github.com/emberjs/data/issues/3296
Should be fixed soon. Thanks!

**Comment by piotrpalek** [comment]
@igorT just heads up I think this issue: https://github.com/emberjs/data/issues/3039 might be fixed as well (didn't test yet). Sorry if I duplicated the same problem in two issues (wasn't aware of it).
