### ISSUE TITLE
Order of hasMany relationship is not maintained when serializing

### ISSUE THREAD

**Issue by seanrucker** [emberjs/data#2852]
Consider the model:

````javascript
App.Post = DS.Model.extend({
  comments: DS.hasMany('comment') 
})
````

And the payload:

````json
{
  "post": {
    "comment_ids": [1, 2, 3]
  }
}
````

When *deserializing*, the order of the comment IDs is respected. For example:

````javascript
var ids = post.get('comments').map(function(comment) {
  return comment.get('id')
})
console.log(ids.join(', ')) // 1, 2, 3
````

If you modify the order of the comments using methods such as `removeObject` and `insertAt`, the order of the IDs is *not* respected during serialization. For example:

````javascript
store.find('comment', 3).then(function(comment) {
  post.get('comments').removeObject(comment)
  post.get('comments').insertAt(0, comment)
  post.save()
})
````

In previous versions of Ember Data the resulting payload would have been:

````json
{
  "post": {
    "comment_ids": [3, 1, 2]
  }
}
````

In the latest version the order of the IDs is seemingly random. I suspect the previous functionality may have been an unsupported side effect but was quite useful. When using a NoSQL store such as Mongodb the comment_ids property is an actual document property stored in the database and the order has meaning. 

From digging through the source code it appears that the serializer uses the `relationship.members` property and the order of the comments attribute does not have any affect on serialization.

**Comment by seanrucker** [comment]
@wecc adding you to this discussion as requested. 

I was able to "hack" around this issue by reordering the members in a custom serializer:

````javascript
serializeHasMany: function(snapshot, json, relationship) {
  if (relationship.key === 'comments') {
    var relationship = snapshot.record._relationships['comments']
    var list = Ember.get(relationship, 'members').list
    list.splice(0, list.length)
    snapshot.record.get('comments').forEach(function(comment) {
      list.push(comment)
    })
  }
  this._super(snapshot, json, relationship)
}
````

Far from ideal but works for the time being. Solving this properly is beyond my knowledge of Ember Data but let me know if I can be of assistance in any way.

**Comment by wecc** [comment]
@seanrucker I've submitted a PR solving this issue.

**Comment by seanrucker** [comment]
Nice! Thanks so much for looking into this! Should I close this in favour of the PR? Is that the correct protocol?

**Comment by wecc** [comment]
You can leave it open, if the PR gets merged it will auto-close this.
