### ISSUE TITLE
didDelete is not invoked for newRecords

### ISSUE THREAD

**Issue by cibernox** [emberjs/data#2853]
I am calling `model.deleteRecord();` in the teardown of a controller. At this point the record is not yet persisted, but I want to remove it from the store.

I was expecting the `didDelete` event to be fired to clean other associated objects but it wasn't.

```js
  deleteAssociatedStuff: function() {
    /* my code */
  }.on('didDelete'),
```

Legit bug?

**Comment by bmac** [comment]
Looks like a bug to me. 

I believe `record.send('invokeLifecycleCallbacks');` should be called after transitioning to the `deleted.saved` state in this method https://github.com/emberjs/data/blob/1.0.0-beta.15/packages/ember-data/lib/system/model/states.js#L410-L413

@cibernox would you like to put together a pr with a test?

**Comment by cibernox** [comment]
Sure. I should have some time tonight.

**Comment by fivetanley** [comment]
closed by https://github.com/emberjs/data/pull/2857
