### ISSUE TITLE
Slow hasMany relation with links field in ember-data-1.0.0-beta.15

### ISSUE THREAD

**Issue by mbrendler** [emberjs/data#2856]
HasMany relations in ember-data-1.0.0-beta.15 are slow, when the resource uses a link to describe the related resources:

```
{
  "post": {
    "id": 1,
    "links": {comments: "/posts/1/comments"}
}
```

[This](http://emberjs.jsbin.com/xopacemula/3/edit?html,js,console,output) illustrates the issue. The example needs a very long time to display all comments.
With ember-data-1.0.0.beta.12 it renders fast.

**Comment by igorT** [comment]
Thanks for filing the issue! Can you try out this branch:https://github.com/emberjs/data/commit/1dcbb5c43d56

Keep in mind that using dev vs production is still going to be a bit slower, as we added a lot of assertions in dev mode

**Comment by mbrendler** [comment]
Looks good.  It's fast.

**Comment by lolmaus** [comment]
I'm sorry, where's `links` documented? The best i could find is [this mention](http://www.toptal.com/emberjs/a-thorough-guide-to-ember-data#emberLinks).

**Comment by ahx** [comment]
@lolmaus See http://emberjs.com/api/data/classes/DS.RESTAdapter.html#method_findHasMany

**Comment by lolmaus** [comment]
@ahx, thank you, that's awesome!

But shouldn't it be documented more explicitly? Mentioned in `DS.Model` and in [Defining Relationships](http://emberjs.com/guides/models/defining-models/#toc_defining-relationships) section of the guides?

The same seems to be true for `async` and `polymorphic`.

Can someone please confirm whether it's worth opening an issue?

**Comment by igorT** [comment]
Paging @bmac re:docs

**Comment by bmac** [comment]
The links `links` object is defiantly under documented. @lolmaus feel free to open an issue.
