### ISSUE TITLE
Serializers don't follow models inheritance chain.

### ISSUE THREAD

**Issue by cibernox** [emberjs/data#2858]
I've found a place where the convention over configuration seems to be missing, and I wonder if it's for a reason. 

Given that my models have some basic inheritance:

```js
// This is just pseudocode
class User extends DS.Model
class Student extends User
class Teacher extends User
```

And this serializers inheritance:
```js
class ApplicationSerializer extends DS.ActiveModelSerializer
class UserSerializer extends ApplicationSerializer
```

I was expecting *convention over configuration*™ to do it's magic and that `Student` and `Teacher`, since both inherit from `User`, would use `UserSerializer` unless I define another behaviour. 

Apparently it's not the case. The indeed are serialized with the `ApplicationSerializer` as expected, but not with the `UserSerializer`.

That surprised me. It's intentional?

**Comment by tomdale** [comment]
@cibernox Sorry this behavior was confusing for you.

Our initial instinct is that implementing this to work intuitively for users would be very complex. That complexity probably doesn't pay its way given that the workaround is quite simple: just mirror your model class hierarchy in the serializer layer:

```
class UserSerializer extends ApplicationSerializer
class StudentSerializer extends UserSerializer
class TeacherSerializer extends UserSerializer
```

That being said, if you have an idea for how this could be implemented simply, we would love to hear it.

**Comment by cibernox** [comment]
You mean that is complex/confusing from user's perspective? As I said, that was what I intuitively thought it would be the default behaviour. I can live with the idea of mirroring the same hierarchy in the controllers.

From an implementation perspective I have no clue if it's a trivial change or something really complicated. 

In any case, it's not a big deal, let it be. There is indeed many other areas to improve in ED where we should focus.
I haven't even started looking at the code
