### ISSUE TITLE
We do not destroy records that have been unloaded

### ISSUE THREAD

**Issue by igorT** [emberjs/data#2862]
We probably should?

**Comment by bmac** [comment]
Sounds like the correct move. It also looks like we don't remove the `unloaded` record from the store unless we are calling `store.unloadAll`. Is that something we should be doing?

**Comment by aaronbhansen** [comment]
As far as I have seen, if you delete a record, but don't destroy it, when you need to save that delete later there isn't an easy way to get all records that have been deleted in ember and save the deletes to the server. The only easy way is to keep a reference of the deleted models somewhere. In our app, we try to save everything at once before the page transition, and this is one issue we have. Seems like it's related to this ticket. It would be great if there was a way to specifically get deleted records, or on a has many save, save the deleted records first.

**Comment by drogus** [comment]
@aaronbhansen I think this is not quite that case. This is only talking about unloading records, so when you run `record.unloadRecord()`. Deleted records should be unloaded as well, but even in this case it will happen only when the change is persisted, ie. when the record goes in `deleted.saved` state

**Comment by aaronbhansen** [comment]
Okay, maybe mine is a separate issue then. It sounded similar but I wasn't sure. I didn't see another issue about saving deleted records at a later point in time, but this sounded close. If this issue if purely about unloading, I can create a separate issue.

**Comment by givanse** [comment]
I think that destroying records that have been unloaded would break the workaround that I have for this scenario: https://github.com/emberjs/data/issues/2982 If you can tell me how to push this forward I'll do some more tinkering.

**Comment by igorT** [comment]
tracking this under https://github.com/emberjs/data/issues/3296
