### ISSUE TITLE
ManyArray is not a RecordArray

### ISSUE THREAD

**Issue by knownasilya** [emberjs/data#2865]
[Here](http://emberjs.com/api/data/classes/DS.ManyArray.html) it says that `ManyArray` extends `RecordArray`, but it doesn't: https://github.com/emberjs/data/blob/1.0.0-beta.15/packages/ember-data/lib/system/record_arrays/many_array.js#L46

**Comment by igorT** [comment]
Wanna make a PR that updates the docs?

**Comment by knownasilya** [comment]
Ah, looks like it's fixed in master https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/record_arrays/many_array.js#L10
