### ISSUE TITLE
ember-data breaks all production sourcemaps

### ISSUE THREAD

**Issue by ef4** [emberjs/data#2871]
Any app that includes ember-data will end up with broken production sourcemaps, because `ember-data.prod.js` includes this sourcemap reference:

```js
//# sourceMappingURL=ember-data.js.map
```

which points to a sourcemap file that's only valid for `ember-data.js`, the dev build. This attempt in ember-data's index.js to hide the dev sourcemap in production:

```js
    this.app.import({
      development: app.bowerDirectory + '/ember-data/ember-data.js',
      production: app.bowerDirectory + '/ember-data/ember-data.prod.js'
    }, options);
    // Source maps
    this.app.import({
      development: app.bowerDirectory + '/ember-data/ember-data.js.map'
    }, {destDir: 'assets'});
```

does not work, because sourcemap files do not need to be imported explicitly, they are discovered via relative URLs.

ember-data needs to ship with a valid sourceMappingURL in ember-data.prod.js, or leave it off entirely. Pointing to an invalid file breaks the sourcemap for any file that appears in the vendor bundle later than ember-data.

**Comment by fivetanley** [comment]
Seems like we should just remove it for production. I can hotfix this to the bower components repo but this should be removed in core until we can get it right.

**Comment by fivetanley** [comment]
I hotfixed this on the ember data components repo. I'll post in the other thread.

**Comment by bmac** [comment]
@fivetanley will this be fixed by using the ember build pipeline?
