### ISSUE TITLE
[FEATURE OFFERING] code generator for ember data models

### ISSUE THREAD

**Issue by QuantumInformation** [emberjs/data#2872]
I'm planning to write a code generator for ember data models based off an input of json (example of server response). Before I start I wanted to know if anyone else was coding one before I re-invent the wheel.

I want this because it will save time every time I need to update my model or add new ones.

**Comment by csantero** [comment]
Are you planning on using [JSON API](http://jsonapi.org/) for the example server responses?

**Comment by aaronbhansen** [comment]
We wrote one we use, you can see it [here](https://github.com/unchartedcode/describe-models/blob/master/addon/utils/load-models.js). We actually generate the json file based off of our rails models in this [project](https://github.com/unchartedcode/ember-schema). It's based on Restpack serializers, but we also had an older version I could probably find for ActiveModel Serializers.

**Comment by QuantumInformation** [comment]
@csantero yeah thats the plan.

@aaronbhansen cool, any chance you could put it online? If not could I put it in my online project?

**Comment by aaronbhansen** [comment]
Put our ActiveModel Serializers json generation for rails online?

**Comment by QuantumInformation** [comment]
@aaronbhansen  Well basically I want to have a text input that people can put code in and then in another text area the code for an ember data model will be generated, possible a zip file if multiple realtionships are needed. It would either take json or in your case some rails code.

**Comment by aaronbhansen** [comment]
Sounds like yours might be a different use case than ours. We generate our model schema from rails based on our serializers, than generate / create those models in our ember app in an initializer based on that json schema file from rails.

**Comment by wecc** [comment]
@QuantumInformation You might want to post this question in http://discuss.emberjs.com/

**Comment by bmac** [comment]
I'm going to close this issue since it isn't really a bug in Ember Data. As @wecc suggests  http://discuss.emberjs.com/ is a good place to continue this conversation.
