### ISSUE TITLE
Deprecate typeKey and replace with modelName

### ISSUE THREAD

**Issue by fivetanley** [emberjs/data#2874]
modelName is a dasherized typeKey that we can be more rigorous about it being dasherized vs camelcased/snake cased/whatever.

This allows us to be more consistent in internals when accessing models via the container.

**Comment by stefanpenner** [comment]
When we move away from factories having concrete references and all API consume strings only. I think it is possible to stop polluting factories with a string name of any kind

**Comment by tim-evans** [comment]
I'm using this in production code to DRY up some actions. I would *love* for this to be a deprecation notice before giving it the axe.

**Comment by igorT** [comment]
It will definitely be deprecated first.

**Comment by tim-evans** [comment]
@igorT thank ya! :heart:

**Comment by fivetanley** [comment]
closed by https://github.com/emberjs/data/pull/3033
