### ISSUE TITLE
Rename internal flags (such as isEmpty)

### ISSUE THREAD

**Issue by leepfrog** [emberjs/data#2876]
Internal flags should be hidden away from user-space.  One good example is if you have a "isEmpty" property on your model that evaluates to false -- it will silently never attempt to fetch the record (even with a findById).

**Comment by wecc** [comment]
Dupe, see #602, #2230 and #2328

**Comment by leepfrog** [comment]
Thanks.. didn't search for the right thing and was flailing my arms in the air after debugging a silent failure for a few hours :)
