### ISSUE TITLE
We should rename the local files to use dashes instead of underscores

### ISSUE THREAD

**Issue by igorT** [emberjs/data#2877]

**Comment by fivetanley** [comment]
if you do this, please use git mv

**Comment by stefanpenner** [comment]
:+1:

**Comment by jakesjews** [comment]
I made an attempt at this in pr #2880

**Comment by sly7-7** [comment]
Closing since #2880 is merged. Just out of curiosity, is this a "new" convention for file naming ? Or is it a choice made in the ember-cli ecosystem ?
