### ISSUE TITLE
Documention clarification

### ISSUE THREAD

**Issue by atomkirk** [emberjs/data#2887]
Here: http://emberjs.com/api/data/classes/DS.InvalidError.html

It says: 
>This function should return the entire payload as received from the server. Error object extraction and normalization of model errors should be performed by extractErrors on the serializer.

The example:
```js
App.ApplicationAdapter = DS.RESTAdapter.extend({
  ajaxError: function(jqXHR) {
    var error = this._super(jqXHR);

    if (jqXHR && jqXHR.status === 422) {
      var jsonErrors = Ember.$.parseJSON(jqXHR.responseText);
      return new DS.InvalidError(jsonErrors);
    } else {
      return error;
    }
  }
});
```

Requiring format:
```js
return new DS.InvalidError({
  length: ['Must be less than 15'],
  name: ['Must not be blank']
});
```

1. What exactly does Ember do with what I return from my overridden `extractErrors`?
2. "Error object extraction and normalization of model errors should be performed by extractErrors on the serializer." makes it sound like I should not be doing that here, but then how do I pass the extracted and normalized errors into `DS.InvalidError` in the format that it expects?
3. If `extractErrors` will extract and normalize the payload that is returned `ajaxError`, assuming the status code is NOT 422 and `DS.InvalidError` is not returned, how do the errors get associated with the model when `DS.InvalidError` is designated as the mechanism for that purpose?
4. "This function should return the entire payload as received from the server." needs clarification if not correction. In either case in the example above, `ajaxError` does not return the entire payload as returned from the server. Nor does `new DS.InvalidError(…)`, of which this documentation is for.
5. This same confusing phrase "This function should return the entire payload as received from the server." appears here as well: http://emberjs.com/api/data/classes/DS.RESTAdapter.html#method_ajaxError
So what is "This function" referring to?

Hopefully these questions help illustrate how confusing these particular docs are. Most Ember docs are great, but this one has me totally confused. Those are the best questions I could come up with, there are more questions I don't even know how to ask. Please clean up these docs.

**Comment by bmac** [comment]
Thanks for the feedback @atomkirk. You are right the ajax error docs defiantly needs to be updated. I think part of the problem is many of the pieces have been changed (or added) since this section was originally written so it no longer flows correctly. I'll take a stab at rewriting this sometime this week.
