### ISSUE TITLE
primaryKey and still have an id attr

### ISSUE THREAD

**Issue by jbrown** [emberjs/data#2894]
I'm trying to integrate with a backend that has a model with a different primary key than `id`.

```javascript
import DS from 'ember-data';

export default DS.RESTSerializer.extend({
  primaryKey: 'systemId'
});
```

On the server, this model also has a field that is not the primary key called `id`. If I understand correctly, `primaryKey` is only utilized for serializing/deserializing, the `id` attribute is where it would still be stored. Therefore, I could not also have a separate `id` attribute coming from the backend?

**Comment by bmac** [comment]
The default implementation of Ember Data will end up clobbering the non primary key attribute called `id`. The easiest workaround might be to override the `normalize` method can move the server's `id` key to a new attribute.

```js
App.ApplicationSerializer = DS.RESTSerializer.extend({
  normalize: function(type, hash) {
    // The server's id property will now live on the `newIdProp` attribute.
    hash.newIdProp = hash.id;
    return this._super.apply(this, arguments);
  }
});
```

**Comment by jbrown** [comment]
@bmac Thanks for the tip, that did the trick.
