### ISSUE TITLE
snapshot hasMany id order not preserved

### ISSUE THREAD

**Issue by knownasilya** [emberjs/data#2906]
Using `snapshot.hasMany(attr, { ids: true })` [here](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/serializers/embedded-records-mixin.js#L303) in the embedded-records-mixin does not preserve the order if you programmatically change the order of the records in an async hasMany, and then save. 

The interesting thing is that I move only one model, and it always moves to the bottom. I'm assuming it's because of how the relationship is retrieved:

this:
```js
// from here: https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/snapshot.js#L264
var relationship = this.record._relationships[keyName];
Ember.get(relationship, 'members');
// Incorrect order, probably since it's an OrderedSet?
```

vs this:
```js
this.record.get('workouts.arrangedContent').toArray()
// return correctly ordered items
```

additional context: #2847

**Comment by igorT** [comment]
Can you try canary? Seems like a dupe of #2852

**Comment by knownasilya** [comment]
Fixed! Sweet.
