### ISSUE TITLE
Consequences of allowing ids to change (when using slugs)

### ISSUE THREAD

**Issue by venkatd** [emberjs/data#2912]
We have been using the slug as the primary key in our App. This is fine most of the time except when we update the title of a record which means we need to update the slug.

https://github.com/emberjs/data/blob/7ab063f54552db356a2ef353b21d1d5aea865115/packages/ember-data/lib/system/store.js#L1320
```javascript
  updateId: function(record, data) {
    var oldId = get(record, 'id');
    var id = coerceId(data.id);

    Ember.assert("An adapter cannot assign a new id to a record that already has an id. " + record + " had id: " + oldId + " and you tried to update it with " + id + ". This likely happened because your server returned data in response to a find or update that had a different id than the one you sent.", oldId === null || id === oldId);

    this.typeMapFor(record.constructor).idToRecord[id] = record;

    set(record, 'id', id);
  }
```

If I override the above code to

```javascript
DS.Store.reopen({
  // Overriding to allow changing ids
  updateId: function(record, data) {
    var id = coerceId(data.id);
    this.typeMapFor(record.constructor).idToRecord[id] = record;
    record.set('id', id);
  }
});
```

What are the possible consequences of doing that?

Thanks!

**Comment by bmac** [comment]
I believe Ember Data's store has some assumptions internally that the id will never change and it uses these assumptions to keep track of the record. When the id changes its possible for the store to get confused and create 2 records that represent the same resource on the backend. This can lead to some subtle bugs where changes to a record may not propagate correctly throughout an application.

**Comment by florent-blanvillain** [comment]
I would be interested to know the consequences too. I don't have much choice for now.

**Comment by fivetanley** [comment]
I imagine stuff would get out of sync and relationships would begin to break very fast. That's about all I can offer as a hypothetical, sorry. I don't think this is something we'll support.

To work around, you could unload the old record and then find the record with the new slug.

**Comment by florent-blanvillain** [comment]
@fivetanley good idea, thanks for the work around.
