### ISSUE TITLE
Edit support for "disconnected" models (or snapshots)

### ISSUE THREAD

**Issue by MiguelMadero** [emberjs/data#2913]
We have scenarios where we don't want to edit the instance of a model directly, but instead a clone or `snapshot`. The scenario is simple, let's say we have a list of users, we select my user and decide to change the email. As we're typing the new name, I don't want the login button at the top to change as I type. I also don't want the details on the list to change. See GitHub as a reference. 

![image](https://cloud.githubusercontent.com/assets/47388/6770678/d8825b22-d084-11e4-905b-e947300af7bd.png)

Instead I want to do my changes, if I press "Save" then flush the changes back to the original record and then call `user.save()` to also persist them to the server. Right now the pattern looks something like: 

edit/route.js

```
model: function () {
   var user = this.store.find('user', id);
   return user.clone();
}
```

edit/controller.js

```
cancel: function () {
   // Don't do anything, simply discard the clone and go back to the list. 
   this.transition.... 
}, 
save: function (userClone) {
   var user= this.store.find('user', userClone.id);
   user.setProperties(userClone);
   user.save();
}
```

This works fine for objects with only simple attributes. It gets more complicated once we also edit relationships. clone could inadvertently load relationships, instead we could probably use [DS.Snapshot](https://github.com/emberjs/data/blob/1.0.0-beta.15/packages/ember-data/lib/system/snapshot.js#L7), however the constructor is currently private. Even if we used Snapshots, we're still missing an easy way to flush the changes back to the original model.

**Comment by BenjaminHorn** [comment]
+1

**Comment by runspired** [comment]
I've wanted to achieve this for some time, and I believe it's necessary to achieve in order for ember-data to offer folks either an immutability story or a "lightweight model" story should they want it.

Achieving this within ember-data itself is on my radar of "nearish term" goals; however, I suspect pairing direct use of the adapter with something like ember-changesets could allow you to achieve this sooner.

One reason this is hard is the same reasons that make dirty-tracking for relationships hard: if you enforce immutability in a model, and provide an editable version, at what point do you stop "pulling the thread"? E.g. given `foo` has a `bar` has a `baz`, and we make `foo` editable, how do we handle editing the relationships and grandchild relationships?

A few approaches to this problem include:

-  A `transaction` primitive that allows you to coalesce a set of records together for editing, but such a transaction would need to be "fluid" to accommodate adding and removing records.

- Embracing `references` on editable versions. You can only edit a model by adding / removing a reference, or if you want to edit more comprehensively you must use the reference to fetch an editable copy. Bonus, this allows manipulation of records with unloaded relationships.

- Forking the whole store

- Keeping two store versions alive at all times, one with edited state and one with canonical state.

For complete transactional safety and offline support, you also likely need a third "in flight" state, but whichever approach is taken for solving the dual states should be easy enough to extend to three states.

cc @machty @mmun

**Comment by runspired** [comment]
This is covered by both store forking and custom record classes (either or both). The former is available when https://github.com/emberjs/rfcs/pull/854 is implemented, the latter is available today (`instantiateRecord` hook on the store)
