### ISSUE TITLE
willDestroy missed in documentation?

### ISSUE THREAD

**Issue by svox1** [emberjs/data#2914]
Hi,

I use store.willDestroy() to clean my models after the user is logged out. This works already fine.
I find this method after reading:
https://github.com/emberjs/data/blob/1.0.0-beta.15/packages/ember-data/lib/system/store.js#L1766

If this method is for public use, I was surprised that this method isnt in the documentation:
http://emberjs.com/api/data/classes/DS.Store.html

Or is this method not for public use?

Regards and thanks all Ember contributors!

**Comment by bmac** [comment]
The willDestroy comes form Ember.Object which the store extends (http://emberjs.com/api/classes/Ember.Object.html#method_willDestroy). It looks like when the Ember Data API doc are built they aren't pulling in classes from Ember itself. I wonder if it would be possible for the API docs to know about Ember classes they depend on without those classes showing up in the Ember Data sidebar.

**Comment by wecc** [comment]
@svox1 `store.willDestroy()` is not public API and not intended to be called manually. It's called by Ember internals when the store is being destroyed.

Could you explain more about your use-case? `store.unloadAll(type)` should be able to unload the models for you?

**Comment by svox1** [comment]
>> I use store.willDestroy() to clean my models after the user is logged out.

I dont want to manually remove every model for himself. 
So that is why I need a foreach like in willDestroy:
```javascript
forEach(types, this.unloadAll, this);
```

I have create a pull request:
https://github.com/emberjs/data/pull/2995
with this change, the method is still working in ember-data v1.0.0-beta.16.1

Or are there better alternatives with public methods?

**Comment by wecc** [comment]
Thanks for the PR! I'm afraid messing with `willDestroy` is not the right way to solve this problem, it's not supposed to be called at all.

Perhaps a better way would be to provide a public API for unloading all records of all types. We currently have methods for unloading a single record as well as all records for a specific type. I think a method to unload all records of all types would make more sense.

@bmac @fivetanley @igorT thoughts?

**Comment by igorT** [comment]
@wecc I just proposed the exact same solution in the other thread :) 
`willDestroy` is a hook thats called when the store is being destroyed, it's not meant to be called directly.

**Comment by svox1** [comment]
I have create a pull request for this. 
https://github.com/emberjs/data/pull/2999
I hope everything is well.
