### ISSUE TITLE
Snapshot doc say snapshot.attributes() returns an array, but sample indicates object

### ISSUE THREAD

**Issue by tp** [emberjs/data#2923]
Doc: http://emberjs.com/api/data/classes/DS.Snapshot.html#method_attributes
Source: https://github.com/emberjs/data/blob/5a47172a36e3a71951f9f0fda46f7b3ffc064de8/packages/ember-data/lib/system/snapshot.js#L146

I think the return type is supposed to be Object instead of Array.

**Comment by wecc** [comment]
Nice catch! You're right, it should be Object instead of Array in the docs.

Would you like to submit a PR fixing it?
