### ISSUE TITLE
ember data 1.0.0-beta.16 with ember 1.10.0-beta.4 fails

### ISSUE THREAD

**Issue by danielspaniel** [emberjs/data#2927]
Using the newly released beta.16  with ember 1.10.0-beta.4 is not working because of a few lines like this:

Ember.HTMLBars._registerHelper 

 I am guessing its because this method ( _registerHelper ) on HTMLBars is only in ember 1.11.0 ?? 
because in my environment, Ember.HTMLBars exists, just not that method.

I am using npm: 
 ember-cli@0.2.0
 ember-cli-htmlbars@0.7.4

and bower: 
ember#1.10.0-beta.4 
handlebars#3.0.0

**Comment by igorT** [comment]
Are you sure it's a beta.16 problem, we don't really call out to HTMLBars

**Comment by rwjblue** [comment]
@igorT - The inflector does setup helpers if I recall correctly (could be wrong though).

**Comment by wecc** [comment]
We're getting `Ember.HTMLBars._registerHelper('singularize'...` and `Ember.HTMLBars._registerHelper('pluralize'...` from `ember-inflector/helpers`

**Comment by bmac** [comment]
Ember inflector, which Ember Data includes as part of its release build will attempt to register helpers if Ember.HTMLBars exists. https://github.com/stefanpenner/ember-inflector/blob/e19798c3759f2e46bc2b9ce7de36b85397b5d824/addon/lib/helpers.js#L4

**Comment by danielspaniel** [comment]
Yes, I checked the source .. there are a few lines like this:

Ember.HTMLBars._registerHelper('pluralize', Ember.HTMLBars.makeBoundHelper(function(params) {

 line 2022... but yeah .  @bmac just mentioned same thing

**Comment by danielspaniel** [comment]
ember-data.1.10.0-beta.16  works fine on new version of ember like 1.11.0-beta.5 , so I am trying upgrade asap.

**Comment by danielspaniel** [comment]
Should I submit a PR for this ? ( not sure if anyone is already fixed ) .. 
 I am stuck on ember 1.10 because list-view is broken on 1.11

**Comment by rwjblue** [comment]
The fix has landed upstream in the inflector https://github.com/stefanpenner/ember-inflector/pull/71.  Now it needs to be incorporated here, then there will likely be another release to get it published.

**Comment by danielspaniel** [comment]
@rwjblue .. thanks for the update
