### ISSUE TITLE
[suggestion] store.adapterFor should progressively fallback on adapters instead of jumping to ApplicationAdapter when [modelName]Adapter isn't found

### ISSUE THREAD

**Issue by foxnewsnetwork** [emberjs/data#2928]
Suppose I have the following app structure:

```bash
app
  ...
  -- adapters
    -- fires.js
    -- rails.js
    -- application.js
  -- models
    -- fires
      -- icecandidate.js
      -- offer.js
      -- answer.js
      -- session.js
    -- rails
      -- user.js
      -- dog.js
      -- cat.js
      -- mom.js
  ...
```

Right now, we have:

``` coffeescript
type = container.lookupFactory "model:fires/offer"
store.adapterFor type 
# Gets me ApplicationAdapter since I don't have a fires/offer adapter
```

So, if I want all my models in the models/fires directory to use the FiresAdapter, I have no choice but to submit to the humiliation of making an adapter for all of them in adapter/fires... Instead, can we get:

```livescript
type = container.lookupFactory "model:fires/offer"
store.adapterFor type 
# Gets me FiresAdapter
```

All that needs to be done for this is to change the following from:
```javascript
// packages/ember-data/lib/system/store.js

adapterFor: function(type) {
    type = this.modelFor(type);

    var adapter = this.lookupAdapter(type.typeKey) || this.lookupAdapter('application');

    return adapter || get(this, 'defaultAdapter');
  },
```
to something like

```javascript
// packages/ember-data/lib/system/store.js
function tailsOf (delimiter, string) { 
  return [] if Ember.isBlank(string)
  return [string].concat(tailsOf(delimiter, string.split(delimiter).slice(1)))
}

... // other stuff

adapterFor: function(type) {
    type = this.modelFor(type);

    var adapter = tailsOf("/", type.typeKey).find(this.lookupAdapter.bind(this)) || this.lookupAdapter('application');

    return adapter || get(this, 'defaultAdapter');
  },
```

Please let me know if this is something you guys will approve of, that way, I know if I should commit time into testing and pull-requesting.

**Comment by stefanpenner** [comment]
this sounds extremely crazy to debug when you don't expect it.

**Comment by foxnewsnetwork** [comment]
In what way? I mean, it seems reasonably sane to me since Ember does something like this with its routes (and controllers); for example, if you have:

```bash
app
  -- routes
    -- kennels
      -- dog
        -- status.js
      -- dog.js
    -- application.js
    -- kennels.js
```
And you go to '/kennels/dog/4/status', the Ember hamster runs through and patronizes all the routes you have declared in status.js, dog.js, and kennels.js before finally slinking away to the route declared in application.js. So why not also do it for models looking for adapters?

**Comment by fivetanley** [comment]
I agree with stef, this seems pretty confusing to debug if you run into it. I don't think this is that common of a use case to incorporate into core. As a workaround, you can use `extend` and make an adapter for each thing you want to fall back to, sorry.
