### ISSUE TITLE
Error Handling Refactor

### ISSUE THREAD

**Issue by twokul** [emberjs/data#2931]
Idea behind this refactor is to have a sane way to deal with different types of errors. `Adapters` will read the payload, create an appropriate error (`ValidationError`, `AdapterError`, `TimeoutError`) and pass it down to `Serializers` (or other consumers). It will also deprecate passing `jqXHR` object around. 

- [x] remove `InvalidError` from [adapter code](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/adapter.js#L7)
- [ ] likely `parseErrors` method is needed on `BaseAdapter` to parse json and extract errors
- [ ] likely `extractErrors` method is needed on `serializers`
- [ ] make sure `store` rejects with errors ([here](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/store.js#L1310) and [here](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/store.js#L1323))
- [ ] make sure `activeModelAdapter` rejects with errors ([here](https://github.com/emberjs/data/blob/master/packages/activemodel-adapter/lib/system/active-model-adapter.js#L143))
- [ ] make sure `restAdapter` rejects with errors ([here](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/adapters/rest-adapter.js#L710))
- [ ] add different types of errors (reject with an error with details, yay types)
  - `AdapterError` 
  - `ValidationError`
  - `TimeoutError`
- [ ] adapter should reject with errors, not `xhr` object from jQuery
  - `jqXHR` should not be passed around
- [ ] `json:api` error type sematics should be supported OOB (might be a part of this [PR](https://github.com/emberjs/data/pull/2904))
- [ ] add `fetch` polyfill
- [ ] `Ember.Enumerable` -> `EmberArray` ([here](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/model/errors.js#L91))

Original https://github.com/emberjs/data/issues/2840

**Comment by twokul** [comment]
cc @igorT @tchak

**Comment by tchak** [comment]
@twokul most stuff on this check list were implemented/merged. I think we can close this.
