### ISSUE TITLE
Model's property observer is triggered after save although value isn't changed by response

### ISSUE THREAD

**Issue by olivierlesnicki** [emberjs/data#2937]
I have an observer on a model's property. 

When the model is saved, and only if the API returns the property (unchanged) as part of the payload, then the observer is being triggered.

Since the property hasn't changed - same type, same value - I'm left confused as to why my observer is being triggered after save.

**Comment by fivetanley** [comment]
Can you post an example model definition and payload?

**Comment by olivierlesnicki** [comment]
Note, this is similar to:
https://github.com/emberjs/data/issues/2334#issuecomment-57425994

@stefanpenner do we have an ETA for this?

**Comment by fivetanley** [comment]
Most of the attrs/relationships don't use Ember Computed Properties for performance reasons, so I don't think this is similar to the other issue.

**Comment by olivierlesnicki** [comment]
`model/lead`
```js
import DS from 'ember-data';
export default DS.Model.extend({
  accountNumbers: DS.attr('string',{defaultValue: ''}),
});
```

`request`
```js
{
  "lead": {
    "accountNumbers": "911000319219,851002826770,851002826771"
  }
}
```
`response`
```js
{
  "status": "SUCCESS",
  "data": {
    "lead": {
      "accountNumbers": "911000319219,851002826770,851002826771"
    }
  },
  "errors": {},
  "meta": {}
}
```

**Comment by olivierlesnicki** [comment]
The observer on the accountNumbers get triggered after save. Although console.logging the value gives exactly the same.

**Comment by wecc** [comment]
I can see why this is happening. When you set attributes on a record we store those changes internally in `_attributes`. However, in `setupData()` we call `mergeAndReturnChangedKeys()` with the newly received data and the canonical `_data`, not `_attributes`.

See https://github.com/emberjs/data/pull/2649#issuecomment-68499321

I still have a vision™ of completing my branch fixing this...

**Comment by olivierlesnicki** [comment]
Does it mean that `_data` is an empty object just before save?

**Comment by wecc** [comment]
Yes, if the record is newly created. `_data` contains canonical data that we receive from the server. `_attributes` contains the local changes to attributes.

**Comment by igorT** [comment]
Can you provide a failing test? I think this shouldn't be too hard to solve. I think we probably just need to move https://github.com/emberjs/data/pull/2649/files#diff-4cc9f4885e8425eeaa555ef3648588aeR866 couple lines up
