### ISSUE TITLE
`store.findAll` behaves differently in firefox.

### ISSUE THREAD

**Issue by cibernox** [emberjs/data#2941]
I've faced this bug yesterday. An app is working in chrome/safari but failing in firefox, and I tracked the bug util this code:

```js
import Ember from 'ember';

export default Ember.Route.extend( {

  model: function(){
    return Ember.RSVP.hash({
      dashboardClients: this.store.findAll('dashboardClient'),
      exercises: this.store.findAll('exercise'),
      messages: Ember.A([])
    });
  },

  afterModel(model) {
    console.log('exercises.length', model.exercises.length);
    // Here in firefox the collection is empty. In chrome/firefox/opera it contains many records
  }
});
```

I haven't had time yet to come up with a jsbin example, but I'll try to do it by the end of the day.

**Comment by bmac** [comment]
Hi @cibernox what version of Ember, Ember Data and Firefox are you using? Here is the jsbin I put together to try and reproduce this issue: 
http://emberjs.jsbin.com/veneneyani/1/edit?html,css,js

**Comment by cibernox** [comment]
ED beta 16.1
Firefox Aurora 38

That JS bin works for me too. I'll pair with @wecc this afternoon to localise the root of the problem. I don't see how it can be a problem in my code, but you never know.

**Comment by wecc** [comment]
Awesome JSBin @bmac, I'm aldo unable to reproduce in Firefox 35.0.1, 36.0.1, 36.0.4 and 38.0a2 (2015-03-26).

Pairing got postponed, will try to see what might be causing this with @cibernox at a later time.

**Comment by igorT** [comment]
Ping

**Comment by cibernox** [comment]
I haven't had much time for this lately, sorry. I'll try to reproduce it again tomorrow and come up with a example.

**Comment by igorT** [comment]
@cibernox ping?

**Comment by cibernox** [comment]
Sorry, unable to reproduce it now. I tried to go back to a commit of that time and all seems to work. I really don't know what was causing the misbehaviour in firefox, but it's probably very edgy.

I'll close this.
