### ISSUE TITLE
Look into moving attributes off of the record

### ISSUE THREAD

**Issue by bmac** [emberjs/data#2942]
Ember Data has a large surface area of reserved names that are taken for attributes.  https://github.com/emberjs/data/commit/f5b471dd46bda5d3263b56f7f345b810e658f52f#commitcomment-10411788 

Its been proposed in the past that Ember Data could move attributes into its own namespaced property (like actions on an Ember Route). https://github.com/emberjs/data/issues/2328#issuecomment-57305737 Lets look into the feasibility of this change before 1.0.

@igorT @wycats @tomdale @stefanpenner Have there been past efforts to explore this type of API in ED?

**Comment by igorT** [comment]
I think @krisselden might have thoughts about this as well

**Comment by igorT** [comment]
I think we have decided not to do this
