### ISSUE TITLE
hasMany property not getting serialized when many side has new entries

### ISSUE THREAD

**Issue by spruce** [emberjs/data#2947]
Hey,
if got a problem with async hasMany Relations again. This is one of my models:
(Child exists before all of this happens and toys will be created in the process)
Child:
```
...
toys: DS.hasMany('toys', {
    async: true
  }),
...
```
and the other one looks like this (Toy)
```
...
child: DS.belongsTo('child', {
    async: true
  }),
...
```
Before saving them I got correct references between them. When I save the toys first the get the correct ref to the child serialized and send to the server. But after saving the child model so the backend also knows that this child has new toys it clears the toys property from the child and also doesn't send that to the server. 

~~Also on the first save it rejects the promise which is also kinda strange but my server always returns a 200 status code~~ See below changed server while debugging

I checked it like this:
```
console.log('toys:', me.get('model.toys.content')); // canonicalState: Array[1]
me.get('model').save().then(function() {
console.log('toys:', me.get('model.toys.content')); // canonicalState: Array[0]
```
So I know it must be the saving. But I just return a 200 (changed that back to returning full object, its not rejecting for now)

What am I doing wrong?

**Comment by igorT** [comment]
Sorry for missing this issue, is this still a problem for you?

**Comment by spruce** [comment]
I didn't do anything for the project where this problem did occur in the last 2 month. Will write back here when I do (next 30 days)

**Comment by spruce** [comment]
As I now see it still is an issue.
I have read something about having to having to specifiy DS.EmbeddedRecordsMixin as the mixin or something. 

I want to mention that before I save the child with hasMany toys these get saved to the server first. 

```
// console output
// length of toys property from child
afterPromise 1 // Ember.RSVP.all(promiseArray), promiseArray contains all promises of toy.save()
afterSave 0 // save of the child removes the property and not sending it to the server.
```

Can you point me to a documentation where it stats how one saves hasMany also on the child so to speak?

**Comment by spruce** [comment]
The Problem was that it didn't send the relationship to the server and than the server responded with relation: null. Which resulted in ember deleting the relation completly. (Reminder to self: server should require that relation is set.)

After consulting @wecc in slack. It was a pretty easy fix. just create for the model in question a custom serializer and extend it with attr:{relation: {serialize: true}}. 
E.g.:

`app/serializers/child.js`
```javascript
import DS from 'ember-data';

export default DS.RESTSerializer.extend({
  attrs: { toys: { serialize: true } }
});

```
