### ISSUE TITLE
We wrongly assert that `relationships`, `relationshipsByName`, `relatedTypes` are reserved props on model

### ISSUE THREAD

**Issue by igorT** [emberjs/data#2948]
They are not, they are defined on the class not on the instances. 
We should assert for `eachRelationship`, `relationshipFor`, `inverseFor` instead
cc @bmac
cc @omarestrella

**Comment by omarestrella** [comment]
Thanks for the quick fix! This really bit us when trying to upgrade.

**Comment by bmac** [comment]
Sorry about that @omarestrella.
