### ISSUE TITLE
Custom property name for relation DS.belongsTo

### ISSUE THREAD

**Issue by glagola** [emberjs/data#2951]
Hi, I can't give property with value of ```DS.belongsTo(...)``` other name, only underscored name of the model is working, while hasMany has no restrictions like this. Here is an example:
```
export default DS.Model.extend({
    event_rating:   DS.belongsTo('event-rating'), // works
});
```

```
export default DS.Model.extend({
    rating:   DS.belongsTo('event-rating'), // NOT works
});
```

If it is not a bug, then it would be great to mention about the naming convention in documentation.

**Comment by bmac** [comment]
@glagola Ember Data doesn't have any restrictions on relationship names. By default it assumes relationship names match 1 to 1 with the json payload returned by your server. It sounds like the server is returning the `rating` relationship under the `event_rating` key in its payload. If you'd like to use a custom name like `rating` you will need to define a custom serializer to map the key on the Ember Data model side to the key in the json payload. 

```js
// app/serializer/model-name.js or app/model-name/serializer.js
export default DS.RESTSerializer.extend({
  attrs: {
    rating: 'event_rating',
  }
});
```

**Comment by glagola** [comment]
Sorry, I didn't mentioned that I'm using ActiveModelAdapter with ActiveModelSerializer. My server returns "event_rating_id", and as a payload:
```
{
    event: {
           ...
           event_rating_id: 4
    },
    event_ratings: [{
           "id": 4,
           ...
    }]
}
```

**Comment by wecc** [comment]
Are you using Ember CLI? If not, does `DS.belongsTo('eventRating')` work?

**Comment by glagola** [comment]
@wecc Yes, I'm using Ember CLI

**Comment by igorT** [comment]
If I am reading correctly, your key from the server is "event_rating_id". There is no way for ED to guess which key it should use if they don't match. If you want to customize the key, you can do that by modifying your serializer:
```
var PersonSerializer = DS.ActiveModelSerializer.extend({
  attrs: {
     rating: {key: 'event_rating_id'}
  }
});
```

**Comment by igorT** [comment]
Let us know if this doesn't work! Will close the issue for now

**Comment by glagola** [comment]
@igorT Thanks. By the way, why you are using model property name as source of key name? IMHO, model name from first argument of belongsTo/hasMany would be more suitable, and gives more flexibility to developer. Let me explain, in my database I have several "ratings" tables for a different items, to distinguish them I've used table's name as a prefix (e.g. event_rating, comment_rating and etc), foreign keys will have same name as the table and suffix "_id" (e.g. event_rating_id, comment_rating_id ...). This approach is just a workaround of database structure limitations, and I do not want to inherit them on my frontend app.
