### ISSUE TITLE
Built-in serializers should not mutate payloads

### ISSUE THREAD

**Issue by tomdale** [emberjs/data#2952]
Currently, our serializers mutate in place the payloads they are given into the form that the adapter expects. This decision was largely driven by concerns around the costs of cloning large payloads before the serializer began normalizing them.

As @hcatlin points out, though, this can be very surprising to developers as they may push a payload into the store, then afterwards expect to be able to retrieve its original properties (https://github.com/emberjs/data/pull/2837#discussion_r26140438).

We would like to change serializers to never mutate the original payload when building the new deserialized form, but we should ensure that this does not introduce large performance regressions.

/cc @igorT

**Comment by hcatlin** [comment]
I'm happy to pitch in on this. What's the best way to test those kinds of performance metrics / regressions? Or, do you just prefer to have some kind of comparison / benchmark between the implementations? This seems to be my pet issue and I want to give back. ;) /cc @malrase

**Comment by hcatlin** [comment]
Updated my pull request to cover this!

**Comment by wecc** [comment]
The new Serializer API should no longer mutate the original payload.

**Comment by bmac** [comment]
:tada:
