### ISSUE TITLE
inverseRecord.get('isEmpty') is being called on objects that aren't arrays

### ISSUE THREAD

**Issue by tonytamps** [emberjs/data#2957]
So I had a bit of an issue where this assertion was being raised because my model has an `isEmpty` property on it. 

```
} else {
  Ember.assert("You looked up the '" + this.key + "' relationship on ... )", this.inverseRecord === null || !this.inverseRecord.get('isEmpty'));
  return this.inverseRecord;
}
```

I had a discussion with some other team members and we realised that the code here would handle both models and arrays, which would mean that `isEmpty` is intended to be called on the arrays. Correct?

Would it be possible to check if `this.inverseRecord` is an array before getting `isEmpty`?

https://github.com/emberjs/data/blob/87dec3e56b6b1744c49103417cc8cacc8f1edb23/packages/ember-data/lib/system/relationships/state/belongs-to.js#L139

I have seen similar issues like #2328 but I'm not positive removing the internal properties off the models will resolve this issue I can't see any mention of removing the properties from arrays, which would still cause issues here.

**Comment by igorT** [comment]
This code is on a `belongsTo` its not meant to be called on arrays in this place. It's specifically for checking if the belongsTo record has been loaded. I would recommend against overwriting `isEmpty` for now at least, you might get subtle errors in other cases (I think `find` cares about it as well)

**Comment by tonytamps** [comment]
Yeah that was our solution for now. I guess in that case it should no longer be an issue once the ember internal properties are moved (like in the linked issue).

Thanks.
