### ISSUE TITLE
Model does not exist (http 404 not found)

### ISSUE THREAD

**Issue by pjlammertyn** [emberjs/data#296]
if you try to find an object by id 

``` javascript
App.store.find(App.Firm, 54)
```

and the rest server returns a 404 not found, the model remains in the loading state. 
It would be better if goes to an error state.

a solution is to extend the rest_adapter

``` javascript
    find: function(store, type, id) {
        var root = this.rootForType(type);

        this.ajax(this.buildURL(root, id), "GET", {
            success: function(json) {
                this.sideload(store, type, json, root);
                store.load(type, json[root]);
            },
            error: function(jqXHR, textStatus, errorThrown) {
                store.load(type, id, 'error');
                //do some aditional stuff to set the model in an error state or modify the load state
            }
        });
    }
```

any suggestions?

**Comment by jdurand** [comment]
I'm experiencing this issue with 1.0.0-beta.16.1

**Comment by igorT** [comment]
Could you submit a failing jsbin or a test case? You can find starting jsbins in https://github.com/emberjs/data/blob/master/CONTRIBUTING.md

**Comment by jdurand** [comment]
Here's the JS Bin : 
http://emberjs.jsbin.com/qecubaqiva/6/edit?js,output

If click on **Inspect Authors** after trying to access *Arthur C. Clarke* you'll see that the record is in the store even though it returned a 404.

**Comment by pangratz** [comment]
> If you click on Inspect Authors after trying to access Arthur C. Clarke you'll see that the record is in the store even though the adapter returned a 404.

I think this is related to https://github.com/emberjs/data/issues/3013#issuecomment-98764683

**Comment by jdurand** [comment]
@pangratz Yep, seems spot on. Thanks for linking!

**Comment by jdurand** [comment]
Looks like https://github.com/emberjs/data/pull/3043 fixed this (for real) @pangratz :+1:
