### ISSUE TITLE
Accessing nested properties through multiple async relationships does not load records into store

### ISSUE THREAD

**Issue by leejt489** [emberjs/data#2963]
I am using v 1.0.0-beta.16.1 and the RESTAdapter

Suppose I am in the route `users/1/priveleges/`.

`user` belongsTo `role` which hasMany `privilege`s and `privilege` belongsTo `role`.  All async.

I would think I could do this:

```javascript
//In route.js
model: function() {
  return this.modelFor('user').get('role.privileges');
}

//In template.hbs
{{#each privilege in model}}{{privilege.description}}{{/each}}
```

But `{{privilege.description}}` is null.  Note that if I use `{{privilege.id}}` it shows the `id`.

Looking at the network, there is no call to get the `privileges` endpoint on my server.

If I do

```javascript
//In route.js
model: function() {
  return this.store.find('privilege', {role: this.modelFor('user').get('role.id')});
}

//In template.hbs
{{#each privilege in model}}{{privilege.descriptions}}{{/each}}
```

Then it works fine.

I would think you should be able to reference deep using get, and that records would be automatically loaded into the store if they are not there yet, rather than having to look up the appropriate id and query the store explicitly.

**Comment by fivetanley** [comment]
Feel free to re-open or open a new issue if you can reproduce in a JSBin or if it is still happening to you. This seems like basic ember data behavior that should be working, so please let us know if it isn't. Sorry for the late response. :(
