### ISSUE TITLE
getting 'DS' is undefined error in ie8

### ISSUE THREAD

**Issue by dshrestha** [emberjs/data#2969]
Does ember-data still support ie8? I would be really happy if it were not( I can just tell my managers oh well its not supported anymore and then go for vacation ) but if it is still supported then, I have been getting  'DS' is undefined error in ie8 with ember-data beta 15 or higher with ember 1.10.0. I have included the polyfill libs for ie8(shim and sham) but I am still seeing this error. It seems like ie-8 is unable to include the ember-data.js.

Here is a demo jsbin : http://jsbin.com/dupejehiqa/1/
We can see this issue even when running in compatibility mode set to 8 in ie11. 

![untitled](https://cloud.githubusercontent.com/assets/3169439/6943800/56276ae6-d85e-11e4-8b34-ab27154ead11.png)

**Comment by bmac** [comment]
Seems like a bug. @dshrestha do you see anything in your dev console when you load the page with Ember Data?

**Comment by bmac** [comment]
It might be an issue with the `es5-sham` and `es5-shim` scripts. When I removed them the page loads fine for me in IE8. When they are on the page the browser crashes in my vm :(. http://emberjs.jsbin.com/vizusecafa/1/edit?html,css,js,output

**Comment by dshrestha** [comment]
Updated the post, added the log errors I see. Seems like related to http://stackoverflow.com/questions/6280469/script28-out-of-stack-space-on-website-using-ie9

**Comment by igorT** [comment]
Paging dr @fivetanley

**Comment by MichaelVdheeren** [comment]
We've been supporting IE8 with our platform (built on Ember) for a while now. Things I know:

* shim/sham is not needed, it's polyfilled by Ember and Ember-Data.
* You will need it if you want additional things like .bind() on a function, then you must prepend it to the vendor file (using Brocfile) and we only include the shim for that purpose, not the sham

**Comment by dshrestha** [comment]
I tried in new vm with win 7 and its working there so I'll just close this for now.
