### ISSUE TITLE
model.toJSON !== model.serialize

### ISSUE THREAD

**Issue by seanpdoyle** [emberjs/data#2971]
Is this intended behavior?

http://emberjs.jsbin.com/xovutalaqe/1/edit?html,js,output

Should  [toJSON](https://github.com/emberjs/data/blob/58a00dbe6564cd994ef26f01a7bb9bf55f11d119/packages/ember-data/lib/system/model/model.js#L444)  lookup the proper serializer instead of hardcoding to `JSONSerializer`?

**Comment by bmac** [comment]
cc @igorT

**Comment by seanpdoyle** [comment]
If the argument in favor of `toJSON` is:

> This will return the JSON representation, regardless of how you serialize to the server

I'd question the purpose / use of `toJSON`

**Comment by igorT** [comment]
Yes, it's on purpose, I know @wycats and @tomdale really liked it, I think it was useful when having complex serializers to have easily debuggable data in the console for just the record props. Not quite sure how useful it still is, but this is not a bug.
