### ISSUE TITLE
Ember 1.8+ version check breaks on incremental improvement ember versions.

### ISSUE THREAD

**Issue by gregbillings** [emberjs/data#2974]
The Ember Data Version check uses `/1\.[0-7]\./` to check the Ember Version. If using a latest build, the Ember version can be something like `1.11.0.2ec768af` which matches the above regex.

Said regex should instead be `/^1\.[0-7]\./`. This does not match `1.11.0.2ec768af` but still matches `1.7.0.2ec768af`.

**Comment by wecc** [comment]
This has been in master by #2965.
