### ISSUE TITLE
Latest Ember Data can break custom inflection rules.

### ISSUE THREAD

**Issue by raytiley** [emberjs/data#2978]
Just discovered that some custom inflector logic we had defined in our models was not being respected. I imagine this broke recently when Ember data started using the ES6 version of ember-inflector.  Not sure why this happened, just throwing this inhere in case there is an easy fix / help other people who's apps break.

I got around the issue by moving my inflection logic to an initializer.

```javascript
import Ember from 'ember';

export default {
  name: 'inflector-rules',

  after: 'store',

  initialize: function(container, app) {
    Ember.Inflector.inflector.irregular('media', 'media');
  }
};
```

**Comment by igorT** [comment]
Hm, we did change the initializer logic somewhat, but I think @bmac or @fivetanley might know a bit more?

**Comment by bmac** [comment]
I'm not sure why this happened. ping @fivetanley @stefanpenner

**Comment by igorT** [comment]
Any news on this, ping @raytiley @fivetanley

**Comment by dennismende** [comment]
:+1:

**Comment by raytiley** [comment]
@igorT not sure. I haven't gone back and tested after I initially got it working with an initializer. Since there doesn't seem to be a lot of other complaints maybe this can be closed?

**Comment by igorT** [comment]
@dennismende have you run into this issue?

**Comment by dennismende** [comment]
Yes after upgrading to beta.18 my inflections didn't work anymore. 

Now I use serializer->modelNameFromPayloadKey

**Comment by igorT** [comment]
@dennismende can you ping @fivetanley on Slack, and debug this with him, I would love for this to get fixed

**Comment by dennismende** [comment]
Sorry but today doesn't work for me. Tomorrow should be possible.

**Comment by jcbvm** [comment]
I have the same issue with `beta.18`. Camelized inflector rules are completely ignored. 
For example when using `inflector.uncountable('deliveryStatistics')` in an initializer, ember data looks for the model `delivery-statistic` when handling a payload. 

Dasherizing all inflectors does work, but that causes troubles when using the `pathForType` method from an adapter, which is using the camelized inflector rule instead.

Currently I've defined both dasherized and camelized inflector rules as workaround.

**Comment by igorT** [comment]
Can you ping @fivetanley on slack to help figure out what the issue is

**Comment by jcbvm** [comment]
I've little time atm, will do soon.

**Comment by jcbvm** [comment]
Found the problem, in one of my addons `pathForType` was being overwritten in the `applicationAdapter` causing wrong output.

**Comment by fivetanley** [comment]
@dennismende are you still running into this?

**Comment by dennismende** [comment]
@fivetanley Yes and I have time for debugging. I'm available at Slack in a minute

**Comment by fivetanley** [comment]
Can you post an example payload and your custom inflections?

**Comment by fivetanley** [comment]
Also are you overriding `typeForRoot` in any serializers?

**Comment by dennismende** [comment]
I found my problem. My inflector rule was wrong because of change of our backend services. That was not dependent to Ember. Sorry for that.
