### ISSUE TITLE
Unloaded record is not removed from hasMany association

### ISSUE THREAD

**Issue by rupurt** [emberjs/data#2984]
Howdy all,

I'm encountering an issue when unloading a record and re-pushing data for the same record at a later time. When the data is re-pushed the `hasMany` relationship is repopulated with the old record instance and a new record instance.

```javascript
App.Course = DS.Model.extend({
   // ...
   sections: DS.hasMany("section")
});
App.Section = DS.Model.extend({
   // ...
   course: DS.belongsTo("course")
})

// Assuming course:id=1, section:id=2
course = store.find("course", 1);
course.get("activities.length"); // 1

store.unloadRecord(section);
course.get("activities.length"); // 0

store.push("section", store.normalize("section", { id: 2, course_id: 1 });
course.get("activities.length"); // 2. Should be 1
```

I've narrowed down what seems to be the cause and was hoping to get some guidance so that I can create a PR to fix it. `ManyRelationship#removeRecordFromOwn` doesn't remove the object from `cononicalState` or `canonicalMembers`. I was thinking that I would modify `ManyRelationship#removeRecordFromOwn` so that it removes the object from `canonicalMembers` and also change `ManyArray#internalRemoveRecords` so that it removes the object from `canonicalState`. Does that seem reasonable?

**Comment by raytiley** [comment]
Pretty sure I ran into this a few days ago. A fix would be awesome :)

**Comment by igorT** [comment]
This seems like two different bugs tied together. First one is some wonkiness in the relationship handling code, and the other is illdefinedness(is this a word?) of unloading records that are referenced by foreign keys. I think what we actually want to happen, is that unloading a record should turn that record into a reference, so the next time you push it, you would get the same reference back. We removed references from ED(basically thin models, that were not Ember Objects) a while ago to simplify the code base, but we should probably bring them back, both for performance and for cases like these. I am closing this in favor of #2991

**Comment by rupurt** [comment]
@igorT any idea how complicated that is and how long it would take?
