### ISSUE TITLE
Save of modified object serializes polymorphic association with just ID

### ISSUE THREAD

**Issue by technomage** [emberjs/data#2985]
Given objects A and B are associated with polymorphic many to many 'x' then unrelating them and saving A will serialize the 'x' targets as just ID not type and ID.

Is this expected behavior?

For polymorphic targets the type can be critical in locating the target object or updating the targets of the relationship.

**Comment by igorT** [comment]
I am having a bit of trouble following your example, not sure what x refers to. Could you please write out in a bit more detail? Thanks!

**Comment by technomage** [comment]
// models/a.js
export default DS.Model.extend({
  x: DSL.hasMany('b'...

**Comment by fivetanley** [comment]
I'm doing some triaging of the issues. As this hasn't been updated in a while, I'm inclined to close it. If this is still causing you issues, please feel free to re-open or open a new issue.
