### ISSUE TITLE
Ember Data is keeping deleted elements even if I use fetchAll

### ISSUE THREAD

**Issue by countingtoten** [emberjs/data#2987]
I'm using fetch all to get a fresh collection from the server, but the ember data isn't updating when an element is deleted server side. This only happens when I navigate using #link-to. If I hard refresh the page, it updates correctly.

How to reproduce:
1) Start the Rails/Ember app and navigate through the menus. 
2) Observe the HTTP Response and Ember Data matching using the Chrome Ember plugin
![pre-delete-httpresponse](https://cloud.githubusercontent.com/assets/78622/7094731/a76af22e-df89-11e4-952b-5c295c8eb668.png)
![pre-delete-ember-data](https://cloud.githubusercontent.com/assets/78622/7094736/abeea232-df89-11e4-91bd-69f9c40ce170.png)
3) Delete an item in the rails console. (In my app another user is doing the deleting)
4) Observe that the http response is missing the deleted item, but that the ember data still has the item and it is still shown
![post-delete-httpresponse](https://cloud.githubusercontent.com/assets/78622/7094738/b1a5a054-df89-11e4-80c0-14518c556311.png)
![post-delete-ember-data](https://cloud.githubusercontent.com/assets/78622/7094739/b35039aa-df89-11e4-9be5-6af65af0447b.png)

Versions:
DEBUG: Ember      : 1.11.1
DEBUG: Ember Data : 1.0.0-beta.16.1
DEBUG: jQuery     : 1.11.2

I created a sample application to showcase this bug at https://github.com/countingtoten/ember-data-test

**Comment by jmurphyau** [comment]
So are you explicitly deleting the object in Ember? Or are you expecting that because it's missing in the second call to fetchAll that it should be deleted?

**Comment by stefanpenner** [comment]
IMHO `fetchAll !== syncAll`

Scenario specific data-sync is something that can be layered successfully on top of ember-data, some-day ember-data might support a general solution for this but currently it does not.

**Comment by wycats** [comment]
@countingtoten more specifically, while you think that not including the data in the second payload is telling Ember Data that "an element is deleted server side", that's really just a quirk of your setup. Just because the record isn't included in the response to `fetchAll` doesn't mean that the server has deleted it. Many servers, for example, truncate the response after N records to avoid unbounded load.

All of that said, it should definitely be possible to tell Ember Data specifically what you're trying to do. I'll let @igorT chime in with more.

**Comment by igorT** [comment]
If you want to specifically opt into this behavior, you can delete/unload records in your serializer. After processing the findAll payload you can intersect the payload results and the current records in store.all for that type and unload/delete the ones that are missing. Let me know if you run into any issues doing this. Maybe this could be a good addon for the serializers, seems pretty easy to generalize

**Comment by countingtoten** [comment]
@igorT If I delete the element through Ember Data using two different users/sessions it correctly registers the delete. If something is deleted on the server how could I communicate to Ember through the serializer that it was deleted?

Also, is there a good explanation, blog post, or documentation of what Ember Data is? I thought it was just a convenience wrapper around your RESTful data.

**Comment by igorT** [comment]
We have guides on the ember website, also the readme, and the api docs. @bmac is working on redoing the guides actually. 
You can say `store.unloadRecord`, but we should probably add a better hook on the store for server side deletes.
