### ISSUE TITLE
v1.0.0-beta.16.1 (and canary) - error after willDestroy 

### ISSUE THREAD

**Issue by svox1** [emberjs/data#2988]
Ember-cli 0.2.3
Ember 1.12.0-beta.1

With v1.0.0-beta.15 everything works finde.

With v1.0.0-beta.16.1 I get an error after call
```javascript
this.store.willDestroy()
```

If I try to make a request:
```javascript
this.store.find("user", 1);
```

I get the error:

Uncaught TypeError: Cannot read property 'adapter:user' of undefinedstore.js:1901 ember$data$lib$system$store$$Service.extend.retrieveManagedInstancestore.js:1914 ember$data$lib$system$store$$Service.extend.lookupAdapterstore.js:1831 ember$data$lib$system$store$$Service.extend.adapterForstore.js:702 ember$data$lib$system$store$$Service.extend._flushPendingFetchForTypeember.debug.js:13590 Map.forEach.cbember.debug.js:13387 OrderedSet.forEachember.debug.js:13598 Map.forEachstore.js:696 ember$data$lib$system$store$$Service.extend.flushAllPendingFetchesember.debug.js:878 Queue.invokeember.debug.js:943 Queue.flushember.debug.js:748 DeferredActionQueues.flushember.debug.js:173 Backburner.endember.debug.js:576 (anonymous function)

**Comment by igorT** [comment]
You are trying to find something after you destroyed the store? It seems ok that it errors out. Why are you trying to do this?

**Comment by svox1** [comment]
I use `this.store.willDestroy()` to logged out current user. - to clean all models

After this I use the Login for a new user and get this error (I call this.store.find('user') after login).

With v1.0.0-beta.15 this works as expected.

**Comment by igorT** [comment]
`this.store.willDestroy` is meant to be called once the store is being destroyed, it's not a public method. What you probably want is `store.unloadAll`
Can you try that?

**Comment by svox1** [comment]
Thanks for the quick response.

If I change it to unloadAll I get this error:

Uncaught TypeError: Cannot read property 'typeKey' of undefinedstore.js:1462 
ember$data$lib$system$store$$Service.extend.model  Forstore.js:1062 
ember$data$lib$system$store$$Service.extend.unloadAll  auth-manager.js:185 
logout  application.js:180 
logout  ember.debug.js:23670 
triggerEvent  ember.debug.js:44818 
trigger  ember.debug.js:43542 
Router.trigger  ember.debug.js:23165 
EmberObject.default.extend.send   ember.debug.js:26854 
mixin.Mixin.create.send   ember.debug.js:18354 
runRegisteredAction    ember.debug.js:224 
Backburner.run   ember.debug.js:15813 
run   ember.debug.js:18352 
ActionHelper.registerAction.ActionManager.default.registeredActions.(anonymous function).handler   ember.debug.js:36563 
(anonymous function)   jquery.js:4430 
jQuery.event.dispatch   jquery.js:4116 
jQuery.event.add.elemData.handle


In auth-manager 185 is this:
`this.store.unloadAll();`

**Comment by wecc** [comment]
@svox1 You have to provide a `type` to the `unloadAll` method. See http://emberjs.com/api/data/classes/DS.Store.html#method_unloadAll

**Comment by svox1** [comment]
Ah sorry for that... that was the reason why I have study the ember-data code and used willDestroy because I didnt want to manually remove each model.

Here I was asking this question:
"Or is this method not for public use?" ;)
https://github.com/emberjs/data/issues/2914

What a pity that this doesnt work anymore with With v1.0.0-beta.16.1

**Comment by svox1** [comment]
I found a "fix".

Can you please change the line:
https://github.com/emberjs/data/blob/v1.0.0-beta.16.1/packages/ember-data/lib/system/store.js#L1933
(in willDestory)
From:
```javascript
delete this._containerCache;
```
To:
```javascript
this._containerCache = Ember.create(null);
```

After that, everything is clean and I can use willDestroy();
Its a win win situation ;)

**Comment by igorT** [comment]
I think instead of messing with willDestroy, we should provide a method that clears all data, which iterates over the types and calls `unloadAll`.  That method should then be called by `willDestroy`. @svox1 could you make a PR that does that instead?

**Comment by svox1** [comment]
Gladly, but I doesn't know enough about the internal ember-data handling.
Whats is recordArrayManager?
```javascript
 this.recordArrayManager.destroy();
```
and the containerCache?
```javascript
   for (var cacheKey in this._containerCache) {
      this._containerCache[cacheKey].destroy();
      delete this._containerCache[cacheKey];
    }

    delete this._containerCache;
```
Maybe this is enough:
```javascript
// reset or better clear?
reset: function() {
    var typeMaps = this.typeMaps;
    var keys = Ember.keys(typeMaps);

    var types = map(keys, byType);

    forEach(types, this.unloadAll, this);

    function byType(entry) {
      return typeMaps[entry]['type'];
    }
  },
```

And maybe we can call this.reset(); in willDestroy(); if the order of the call  this.recordArrayManager.destroy(); is not important.

Sorry Im not familiar with the ember-data code... Iam only a consumer ;)

**Comment by wecc** [comment]
You're on the right track! Move the parts responsible for unloading all types to a separate function (`reset` in your example) and call that method from `willDestroy`, after the call to `this.recordArrayManager.destroy()`.

I agree that `unloadAll` is a better suited name for this method and that we should rename the current `unloadAll` to `unloadType`. We can check if a parameter is provided to `unloadAll`, show a deprecation warning and call `unloadType` if that is the case. If no parameter is provided to `unloadAll`, we proceed with unloading all types.

Feel free to ping me on IRC, I'd be happy to help.
