### ISSUE TITLE
Bring back references

### ISSUE THREAD

**Issue by igorT** [emberjs/data#2991]
A reference is a javascript object that has data for a particular record object, particularly the id and the foreign key data. It is used so we do not have to instantiate a DS.Model for every single foreign key, and to support more advanced unloading cases. 

We used to have them, but they were removed to simplify the code base and because they were a massive pain in the old non promise based ED. It is time to bring them back, as foreign key creation of records is a huge perf bottleneck.

The main issue when considering implementing them is to make sure all internal ED methods *either* deal with record objects or with references but never with both, as that makes code very hard to reason about.

**Comment by wycats** [comment]
:+1: assuming the last paragraph of the description:

> The main issue when considering implementing them is to make sure all internal ED methods either deal with record objects or with references but never with both, as that makes code very hard to reason about.

**Comment by igorT** [comment]
Work ongoing at https://github.com/emberjs/data/tree/references

**Comment by mphasize** [comment]
Would this also support some kind of lazy casting of polymorphic relationships?

I have a situation where an API (which I cannot change) has polymorphic relationships, but neither embeds the records nor supplies a type alongside the ID. Since we already have a "parent" type for polymorphic relationships, I was wondering if the related record could be known to Ember Data just as the ID and the parent type until it gets fetched from the API. When we finally have the complete information, the type could be recast to the child type. (I should also mention that all records are accessible through the same endpoint, so it's not necessary to build a specific URL.)

Does that fit here or should this go into a separate issue?

**Comment by igorT** [comment]
Yes, do you want to write tests for that feature?

**Comment by mphasize** [comment]
Where would I start? (I've been using Ember a lot, but I haven't done much development for Ember yet... but I can give it a shot.)

**Comment by igorT** [comment]
Look at polymorphic tests, like https://github.com/emberjs/data/blob/master/packages/ember-data/tests/integration/relationships/has-many-test.js#L630 
and try to write new tests that use the api you proposed, and assert that it works. 
This would be a great chance to also clean up the tests, and move polymorphic stuff into their own files.
I think the rest adapter integration tests have a bunch of polymorphic stuff that should be moved out

**Comment by mphasize** [comment]
Ok, I will see what I can do there and take a look what I can learn from the rest adapter tests.

**Comment by mphasize** [comment]
Quick question: this behavior is expected to be independent of the adapter/serializer being used, right?

**Comment by igorT** [comment]
Yup. Thats why I was saying that there are probably tests in integration
adapter/serialzier that don't belong there

**Comment by mphasize** [comment]
@igorT So this is my first try at writing such a test. Any guidance on how to improve and expand this would be welcome! https://github.com/emberjs/data/pull/3087

**Comment by mmoonport** [comment]
@igorT Well this correct the issue where when i call store.find('model') on a polymorphic model type that the recordArray comes back empty but the models where pulled and put into the store correctly. I am having this problem currently in my production code.

**Comment by igorT** [comment]
@mmoonport this adds support for that, but doesn't actually guarantee it. Can you write a test for the behavior please?

**Comment by mmoonport** [comment]
@igorT I would be glad to. Should i add this test to the record array tests or create a separate file for this all together

**Comment by igorT** [comment]
There will be bunch of tests for this new polymorphism, so it should be a separate file. It isn't just record arrays as well, you want to be able to fetch a single record with a polymorphic type as well

**Comment by mmoonport** [comment]
@igorT Okay I have implemented the tests... I believe. I haven't written js tests before so please excuse my boorish attempt. Let me know how I can make them better as I am a huge fan of Ember and use it daily and would like to contribute more.  #3105

**Comment by igorT** [comment]
@mmoonport will take a look now that the refactor has been merged

**Comment by igorT** [comment]
fixed by #3094
