### ISSUE TITLE
`extractMeta` is processed pre-normalization.

### ISSUE THREAD

**Issue by nathanhammond** [emberjs/data#3009]
1. `extract` is the entry point.
2. In a `specificExtract` the first step is to call `normalize`.
3. However, `extractMeta` doesn't operate on a normalized payload. It's called first inside of `extract`.

Here is the code: [extractMeta](https://github.com/emberjs/data/blob/v1.0.0-beta.16.1/packages/ember-data/lib/serializers/json-serializer.js#L728)

Would you like me to code up a fix?

**Comment by igorT** [comment]
We are probably gonna move away from this API pretty soon, in favor of passing meta to the store together with the response. Not sure it's worth breaking people's apps twice for this. Is there a backwards compatible fix you could do?

**Comment by nathanhammond** [comment]
The implication here is that anybody who was using `extractMeta` at all was either:
- Overriding it without calling super.
- Had their API designed as Ember Data expects it to be from the start.
- Did something strange with a serializer normalizing data for an embedded record.

With that premise, simply running `extractMeta` through `normalize` and `normalizePayload` would likely be non-breaking for nearly everybody. Are there other use cases you can think of?

**Comment by igorT** [comment]
But wouldn't they get different payload if it were normalized? How would that work? Like for example currently
```js
{ meta: 'hello'
  comments: [...],
  posts: [...] }
```
returns 
```
[...comments...]
```
How would `meta` work? Maybe I am misunderstanding your proposal?

**Comment by igorT** [comment]
@nathanhammond we refactored the serializers, they now return json api format and I believe are much more sane. Please let us know if this is still an issue

**Comment by nathanhammond** [comment]
We worked around it in other ways, and the move to JSON API should handle this for us. :)

/cc @dxprog
