### ISSUE TITLE
`store.hasRecordForId` and `store.recordIsLoaded` do the exact same thing

### ISSUE THREAD

**Issue by igorT** [emberjs/data#3012]

**Comment by pangratz** [comment]
Should `hasRecordForId` be `true` when a record exists for the given id (regardless if it is loaded or not) and `recordIsLoaded` return `true` if `hasRecordForId() && record.get('isLoaded')`? This would contradict https://github.com/emberjs/data/pull/2659#issuecomment-72246238 but I think this would be consistent in regards of naming ...

**Comment by igorT** [comment]
Oops, sorry missed your comment here, `hasRecordForId` is the public api, so it should hide the existence of unloaded records

**Comment by igorT** [comment]
I think the `references` branch might address this issue

**Comment by fivetanley** [comment]
They do not appear to do the same thing anymore:

![new recordForId/recordIsLoaded](https://dl.dropboxusercontent.com/s/r2vq4wslyaxwili/2016-01-15%20at%2011.12%20PM.png)
