### ISSUE TITLE
Consider moving `normalize` to the `adapter` as well 

### ISSUE THREAD

**Issue by bmac** [emberjs/data#3014]
Removed from the 1.0 issue (https://github.com/emberjs/data/issues/2545) since this is an api change that could be added later if we decide it will be a useful addition.

**Comment by pangratz** [comment]
Does somebody remember what exactly this is about and add more context?

**Comment by wecc** [comment]
@emberjs/ember-data-contributors is this something we still should consider?

**Comment by pangratz** [comment]
I am triaging issues and since there hasn't been any progress on this, and also I am not aware of any other issues around this, I am closing this issue.

Feel free to reopen!
