### ISSUE TITLE
Lazily resolve promise proxies

### ISSUE THREAD

**Issue by chancancode** [emberjs/data#3025]
@tomdale asked to open an issue against this and flag it for discussion, I hope it hasn't missed the boat :S

Test case: http://emberjs.jsbin.com/kimaxofeti/4/edit?html,css,js,output

As you can see, Ember (Data) already has enough information to generate both the link as well as the comment count (they work, you can see them on the screen), but it would materialize the relationship anyway. (The fetch endpoints for these are intentionally left broken.)

For certain use cases, this is not ideal – for example, if you are building a basic CRUD admin page displaying a table of records, you might want to display a counts of relationships or link to them by ID. Materializing all of them would be an unfortunate side-effect, especially considering that something like:

```
{{#each model as |post|}}
  <tr>
    <td>{{post.title}}</td>
    <td>{{#link-to post.comments post}} {{post.comments.length}} comments {{/link-to}}</td>
  </tr>
{{/each}}
```

...would result in upto `m*n` requests (m: # posts, n: # comments per post) if you cannot consolidate them via `findMany`.

From what I can tell, this is a side-effect of the current implementation of the `PromiseProxyMixin`, which immediately "tap" the promise as soon as it is set. Conceptually, it seems like it would be possible to defer that until the promise is actually being "tapped" by the user by calling `then`, etc. That way, when you are only accessing information that is already available on the `PromiseObject/Array`, it wouldn't have to resolve the underlying promise and causing the side-effect reported in this issue.

**Comment by stefanpenner** [comment]
I agree with the fundamental problem, but not the solution.

`tap` of the promise, is not what initiates the materialization. Once the promise is provided to the proxy, it has already begun the realization. The `then` is not in anyways lazy, if you have a `then` already more then likely the underlying materialization has already begun, or is queued up to begin.

**Comment by chancancode** [comment]
Sorry, should have kept it more generic. Heading to the ✈️ now, feel free to edit the title etc if it helps!



—

**Comment by igorT** [comment]
I believe this would be solved by making the hasMany `objectAt` actually fetch the record, this would allow you to get the length/relationship without fetching the records themselves. We had a spike of this at some point, should probably revive

**Comment by BW-AdrianG** [comment]
Probably it isn't best practice, but I do the following to get the length of an async hasMany relationship without fetching the records themselves.
```
{{model._internalModel._relationships.initializedRelationships.[relName].manyArray.length}}
```
The nice thing is that it will also be updated when objects are added or removed.

**Comment by runspired** [comment]
@wecc I'm pretty sure this is closable as we've got about 12 dozen of these for this issue ;)

**Comment by wecc** [comment]
👍 

Basically with references we now have a public API to access relationships without triggering fetches. Closing this.
