### ISSUE TITLE
flushCanonical broken, resurrecting oneToMany relationship changes

### ISSUE THREAD

**Issue by drewcovi** [emberjs/data#3027]
When removing items from a manyToOne relationship and persisting the child record ember data resurrects all old relationship in the parent once a new child is added to the relationship.

The hack right now is to **save the parent record along with the child record**

**Comment by cody-lettau** [comment]
@drewcovi thanks for pointing me to this new bug! I'll continue to watch for a fix. Also, appreciate you pointing out the workaround (albeit, not ideal)!

**Comment by wecc** [comment]
Is this still an issue?

**Comment by masciugo** [comment]
I am still experiencing this

**Comment by gregattra** [comment]
i am also still experiencing this

**Comment by runspired** [comment]
This should get cleaned up in the relationship refactor I've been working on

**Comment by runspired** [comment]
This should be resolved on master, with a remaining edge case handled by #5269.

If you still see this, it is likely a bug in the relationship payload being returned. There's a possibility that this is also another manifestation of #5006.

**Comment by drewcovi** [comment]
O em gee 🙂
