### ISSUE TITLE
Polymorphic hasMany links

### ISSUE THREAD

**Issue by MattMSumner** [emberjs/data#3028]
I'm struggling to get a polymorphic `hasMany` relationship to work using links. I've made a [JSBin] showing the problem. I'm using a comment mixin for my polymorphic models, video and text, which `belongTo` a post. However, I never get a video or text model, I only get `(subclass of DS.Model)`. How do I get ember data to push the correct model type into the store for this relationship?

[JSBin]: http://emberjs.jsbin.com/tawoxa/2/edit?html,js,output

**Comment by artych** [comment]
Look at http://emberjs.jsbin.com/yiroritilu/1/edit. This is simplifyed version but you can see that links work well.

**Comment by MattMSumner** [comment]
So the links are working fine but ember data isn't creating the correct models. If you open your jsbin http://emberjs.jsbin.com/lecoqa and checkout the ember inspector, on the data tab you can see 1 post but 0 videos or text.

**Comment by artych** [comment]
Try to add `type: DS.attr()` to CommentMixin

**Comment by artych** [comment]
Found that it works with modified server payload: http://jsbin.com/gaharupowe/2.

**Comment by MattMSumner** [comment]
While that does load the models into the store, the hasMany array does not have the records loaded correctly. In your JSBin I would expect changing `{{comment.type}}` to `{{comment.url}}` to have nothing for one of the models and a url for the other, but in fact it is blank for both.

**Comment by MattMSumner** [comment]
So if I patch store with the following I get the desired behavior:

```js
App.ApplicationStore = DS.Store.extend({
  push: function(typeName, data) {
    if(typeName.toString() === "(subclass of DS.Model)") {
      typeName = data.type;
    }
    return this._super(typeName, data);
  }
});
```

Here is the update JSBin http://emberjs.jsbin.com/tawoxa/6/edit

This obviously isn't right but if someone knows where this should be handled I could try writing some tests?

**Comment by igorT** [comment]
The reason this didn't work is because you were returning data as comments while they were not comments, but `video` and `text`. If you reassign them in your serializer to the correct keys it should work. I think this form should also work pretty soon, I think with my work on references and @wecc on the serializers. Do you want to make a test that fails with this form, and we can look into merging it into the WIPs

**Comment by MattMSumner** [comment]
Thanks @igorT and great work!
