### ISSUE TITLE
One-way belongsTo is broken

### ISSUE THREAD

**Issue by BryanHunt** [emberjs/data#3029]
If you have a model with a one-way belongsTo, the first time you access the relationship, it works fine.  The second time you access the relationship, you get null.  Here is an example user model:

```javascript
{
  fullName : DS.attr(),
  manager : DS.belongsTo('user', {async : true})
}
```

In the controller, if you call twice:

```javascript
this.get('model.manager').then(function(manager) {
  console.log(manager.get('fullName');
  return manager;
});
```
the first call succeeds, the second call fails because manager is null.

I debugged this a bit and noticed that the on the first call, inside `BelongsToRelationship.prototype.findRecord`, `this.inverseRecord` evaluated to `true` and on the second call, it evaluated to `false`

If you create an explicit inverse, it works correctly:
```javascript
{
  fullName : DS.attr(),
  manager : DS.belongsTo('user', {async : true, inverse: 'directReports'}),
  directReports: DS.hasMany('user', {async: true, inverse: 'manager'})
}
```

**Comment by igorT** [comment]
Do you  have a warning in your console that is saying that you need to declare inverses because you have a self referential relationship?

**Comment by BryanHunt** [comment]
No, there are no console warnings.  And a related question:  How would you declare an inverse on a one-way relationship?

**Comment by igorT** [comment]
There should a warning in the console. Which version are you on?
`{ inverse: null }` would be a way to do it

**Comment by BryanHunt** [comment]
I'm using beta 16.1

`{ inverse: null}` works
