### ISSUE TITLE
cannot refresh route after unloading record

### ISSUE THREAD

**Issue by piotrpalek** [emberjs/data#3039]
Hey, if I try to unload a record and then refresh a route I get an exception, it's shown in this jsbin:
http://emberjs.jsbin.com/mazopeburo/2/edit?html,css,js,output

**Comment by fivetanley** [comment]
Seems to be fixed in the latest ember data. Had to update to use mockjax since the fixture adapter has been removed: http://emberjs.jsbin.com/wekehedesa/edit?html,css,js,console,output
