### ISSUE TITLE
model hook does not push data to store

### ISSUE THREAD

**Issue by zion03** [emberjs/data#3041]
DEBUG: Ember : 1.10.1
DEBUG: Ember Data : 1.0.0-beta.16.1

The code below works fine:

    export default Ember.Route.extend({
        model: function(param){
           return this.store.find('user', 100);
         }
     });
But when I changed `return this.store.find('user', 100);` -> `return this.store.find('user', {'id': 100});` REST request was made, but record was not pushed to data store.

**Comment by wecc** [comment]
Would you be able to provide a JSBin that demonstrates the issue?

Note that `this.store.find('user', { 'id': 100 });` triggers `findQuery()` that expects an array to be returned in contrast to `this.store.find('user', 100)` that expects a single resource object.

I suspect doing something like this will solve your problem:

```js
export default Ember.Route.extend({
  model: function(param) {
    return this.store.find('user', { id: 100 }).then(function(data) {
      return data.get('firstObject');
    });
  }
});
```

**Comment by zion03** [comment]
I recieve json object from REST server but `data` from `.then(function(data) {});` is not contain objects.

**Comment by bmac** [comment]
@zion03 what does the JSON response from your server look like?

**Comment by zion03** [comment]
Format look like this:

user: {
filed1: "value",
filed2: "value",
}

Strange, because I call the same API but in different ways

**Comment by wecc** [comment]
When you're using `this.store.find('user', { 'id': 100 });` it expects the result to be an array.

```js
{
  users: [
    {
      id: '1',
      username: 'tomster'
    }
  ]
}
```

**Comment by zion03** [comment]
thanks, it's works with array
