### ISSUE TITLE
Various Methods Still Calling serializerFor with type.typeKey

### ISSUE THREAD

**Issue by drewcovi** [emberjs/data#3042]
for updateRecord and createRecord, the serializer is called with type.typeKey rather than just type.  It would seem that in these cases, we already have the factory, so we shouldn't need to do the lookup.  

This also causes a few issues with edge cases and nesting models in folders.

**Comment by fivetanley** [comment]
We're making all store methods with a public (or public-ish) API take strings. Right now it's sort of confusing that you can pass a factory or a string to any of these methods. Serializer and Adapter methods will still receive the factory when called by the store, but to do any sort of object lookup you will need to use a string.

https://github.com/emberjs/data/pull/3038
