### ISSUE TITLE
Having to use content property of async relationships to get expected behavior.

### ISSUE THREAD

**Issue by arenoir** [emberjs/data#3044]
I am having issues moving my application to using all async relationships. 

example

```
//models/job.js
import Ember from 'ember';
export default DS.Model.extend({
  address: DS.belongsTo('address', {async: true)
});


//templates/job.hbs
{{#if address}}
  {{address.lineOne}}
{{else}}
  No address!
{{/if}

```

The `if` statement behaves inconsistently.  If the address is an unresolved promise it evaluates false.  The work around is to change `address` to `address.content`.  I am hesitant to change all associations references to to the `content` property, unless this is the intended way to access relationships.

**Comment by fivetanley** [comment]
Yeah, @cowboyd and I are going to tackle this as part of https://github.com/emberjs/data/issues/3025. Although the if statement I believe depends on some of glimmer becoming promise-aware.

Maybe @wycats and @rwjblue can weigh in on work left to do on this in glimmer?

**Comment by jherdman** [comment]
My understanding is that you're supposed to do this:

```handlebars
{{#if address.id}}
  {{address.lineOne}}
{{else}}
  No address!
{{/if}}
```

**Comment by arenoir** [comment]
@fivetanley @jherdman It is not only in the context of templates for example assigning a new address on create I am having to add the `content` property.

````

//router/job.js

export default Ember.Route.extend( {
  model: function() {
    return this.store.createRecord('job', {
      address: this.store.createRecord('address')
    });
  },

  actions: {
    save: function() {
      var _this = this;
      var model = this.get('currentModel');
      var addr  = this.get('address.content');
    
      addr.save().then( 
        function() {
          model.set('address', addr);
          model.save().then( function() {
            _this.send('dismissModal');
            _this.transitionTo('jobs.show', model);
          });
        }
      );
    }
}

**Comment by igorT** [comment]
Could you submit a failing jsbin? I am happy to investigate.

**Comment by arenoir** [comment]
@igorT  http://emberjs.jsbin.com/sijodaxofu/2

**Comment by fivetanley** [comment]
closing in favor of https://github.com/emberjs/data/issues/3044

**Comment by fivetanley** [comment]
i mean https://github.com/emberjs/ember.js/issues/12825 lol
