### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by btecu** [emberjs/data#3048]
@wycats mentioned pagination is too common and special and it will be included in Ember Data when it's released in June.

Any news about it? What the `api` looks like?

**Comment by igorT** [comment]
cc @wecc

**Comment by wecc** [comment]
We're refactoring the serializers to make it easier to handle metadata and pagination with that. The API for how to handle pagination is still unknown though. I'll make sure we update #2905 when it comes to the implementation of pagination.

Even though the issue linked is very JSON-API centric we're using JSON-API as guidance but even if you're not using JSON-API I suspect it to be fairly trivial to hook into the pagination API in your serializer.

**Comment by mharris717** [comment]
@wecc first off, thanks for all your hard work!

I maintain ember-cli-pagination, a popular ember addon for pagination. I know nothing about what's coming for pagination in ember-data, and figured for everybody's benefit I probably should. Who would be the best person to talk to about this?

**Comment by wecc** [comment]
@mharris717 sorry for slow response. I'd be happy to talk about pagination as I'll try to take a stab at those part in a couple of weeks.

**Comment by wecc** [comment]
Closing as we're tracking the JSON API implementation in #2905
