### ISSUE TITLE
[Proposal] Resolving an adapter-less model should cache the 'application adapter' resolution.

### ISSUE THREAD

**Issue by runspired** [emberjs/data#3050]
I'm not sure if this belongs here, in ember-cli, or in ember-resolver.  Currently I have the problem where I load 3 conversations with 20 messages each.  These 63 records all use the default `application` adapter.  Since no explicit adapter is ever found, each one triggers the resolver to seek the adapter at each possible path each time, leading to 3 lookups per record and a minimum of 189 lookups.

This is a lot of excess when the first lookup attempt could have stashed the application resolver.

The bigger issue arises in safari which seems fragile to this and can get stuck in a perpetual loop trying to resolve the adapters.

**Comment by fivetanley** [comment]
This seems fine to me. Seems like we should have an escape hatch if we want to eventually support dynamic code loading.

**Comment by igorT** [comment]
@stefanpenner might be interested in this, but I think a cache for adapterFor/serializerFor makes sense. Wanna try implementing?
