### ISSUE TITLE
no documented way to get the array of data for a hasMany relationship

### ISSUE THREAD

**Issue by mgenev** [emberjs/data#3061]
I have a status model. I `find('status')`. I get an array of statuses as my model, I do a `#each` loop in hbs and I pass each status model to the `status-card` component, then I want to pass the `status.likes` which is a hasMany relationship to the user and amounts to an array of users. I can do `#each` in the hbs for the likes component and iterate that way, but the problem is I need to do a computed on this and in the javascript instead of an array of users I get a useless `DS.manyArray` object which doesn't give me the data unless I do `record._data.likes` which doesn't look right. 

This DS.manyArray is barely documented. I'm finding that my data also lives in 2 properties called `canonicalState` and `currentState`, none of which exist in the api docs for this object or produce any results when you search for them in the docs, so I have no idea what to expect when I use them.

Confusing, and wastes time. If there is a purpose to this strange object, I don't know what it is, because it's undocumented. Please fix or document a proper usage of  hasMany relationship data.

**Comment by igorT** [comment]
Hi, the manyArray is the array. What are you tyrying to do with the CP that you are finding it hard to do?

**Comment by mgenev** [comment]
get the data, I guess toArray() on it works, I just found out

**Comment by igorT** [comment]
What do you mean by get the data? The manyArray is the data? You wouldn't need to call toArray in most cases

**Comment by mgenev** [comment]
it's not the data, it's not the array, it's an object which has .record._data.likes where the actual data is...

**Comment by igorT** [comment]
Uhm, no it's an Ember.MutableArray it is the array. What are you trying to do with it?

**Comment by mgenev** [comment]
this is what I had to do, but it wasn't obvious at all
```
computed('likes')
  displayList(l) {
    l = l.toArray() || [];
    switch(l.length){
      case 0: return 'no one likes this'; break;
      case 1: return l[0].get('fullName') + ' likes this'; break;
      case 2: return l[0].get('fullName') + ' and ' + l[1].get('fullName') + ' like this'; break;
      case 3: return l[0].get('fullName') + ', ' + l[1].get('fullName') + ' and ' + l[2].get('fullName') + ' like this'; break;
      default: return l[0].get('fullName') + ', ' + l[1].get('fullName') + ' and ' + (l.length - 2) + ' others like this';
    }
  }

```

**Comment by igorT** [comment]
```
computed('likes')
  displayList(l) {
    switch(l.length){
      case 0: return 'no one likes this'; break;
      case 1: return l.objectAt(0).get('fullName') + ' likes this'; break;
      case 2: return l.objectAt(0).get('fullName') + ' and ' + l.objectAt(1).get('fullName') + ' like this'; break;
      case 3: return l.objectAt(0).get('fullName') + ', ' + l.objectAt(1).get('fullName') + ' and ' + l.objectAt(2).get('fullName') + ' like this'; break;
      default: return l.objectAt(0).get('fullName') + ', ' +l.objectAt(1).get('fullName') + ' and ' + (l.length - 2) + ' others like this';
    }
  }
```
?

**Comment by mgenev** [comment]
This is the weird object I get:
http://i.imgur.com/fQ1ojgq.png

**Comment by mgenev** [comment]
Needs to be documented how to work with this...

**Comment by igorT** [comment]
Yes and that object is an Ember array. http://emberjs.com/api/classes/Ember.MutableArray.html

**Comment by igorT** [comment]
Can you write a comment that would've helped you understand this better?

**Comment by mgenev** [comment]
> Yes and that object is an Ember array. http://emberjs.com/api/classes/Ember.MutableArray.html
Which isn't an array xD and the docs also don't tell you how to get the data out :facepalm:

**Comment by mgenev** [comment]
Here's the comment:

"When you populate a hasMany relationship, in your model you will get an array-like object, which to try like an array in your Javascript computed properties you need to use obj.toArray() on or use Ember methods which are documented here: http://emberjs.com/api/classes/Ember.Array.html"

Overall this just trips up developers, giving them an object instead of an array. What is the merit of it?

**Comment by goto-bus-stop** [comment]
> the docs also don't tell you how to get the data out

http://emberjs.com/api/classes/Ember.MutableArray.html#method_objectAt ?

`Ember.Array`s can be observed, for one, so templates can auto-update. Array-like classes can also be extended with different methods, eg. with the `.save()` method on a `ManyArray` to save all records.

**Comment by neojp** [comment]
Most arrays used on Ember aren't plain arrays, but inherited instances of Enumerable objects.
http://emberjs.com/api/classes/Ember.Enumerable.html

They still have `forEach`, `map`, `any` and other array like methods; they are very powerful and incredibly useful to use. But it comes with a few drawbacks:

1. `data[0]` is not possible anymore, you must use `data.objectAt(0)`
2. `console.log(data)` won't return the data per se, but the object instance

It gets some use to, but I believe it's pretty well known around Ember tutorials. Maybe we need to explain this more in the how to get started documentation.
