### ISSUE TITLE
Boolean values not respected during store.push

### ISSUE THREAD

**Issue by runspired** [emberjs/data#3062]
This behavior is in ember-data beta 14.1, I'm not sure if it's fixed in newer releases (currently can't upgrade, but I may try to whip up a JSBin later to test this on).

**Issue**
Pushing a record with a boolean property that is `false` into the store *often* results in that value being `true` on the newly created record.

**foo Model**
```
DS.Model.extend({
  foo: DS.attr('boolean', { defaultValue: false})
})
```

**Usage**
```
var record = this.store.push('foo', { bar: false });
```

record.foo will now be `true`.

**Comment by igorT** [comment]
Can you submit a jsbin that demonstrates the issue please?

**Comment by runspired** [comment]
@igorT sure, I figured I needed to but I'm about to head to bed.  Will work on it tomorrow, I removed the call to `record.save()` and the value is `true` still so that rules out interference from the local storage adapter during the save.

**Comment by runspired** [comment]
This issue seems to have great Heisenberg uncertainty, every time I think I'm close to nailing it down it stops.  Since it's fairly phantom I'm going to close this for now.
