### ISSUE TITLE
DS.RESTAdapter.buildURL receives query instead of id in 1.0.0-beta.17 

### ISSUE THREAD

**Issue by yaroshevych** [emberjs/data#3064]
buildURL signature is documented as ```buildURL (typeKey, id, snapshot, requestType)```, but in beta 17 query object is passed instead of id. See findQuery() in rest-adapter.js.

Beta 16.1 works fine.

**Comment by igorT** [comment]
What is the behavior in beta.16 for the query case? Is the `id` null?

**Comment by yaroshevych** [comment]
It was ```undefined``` and my ```buildURL``` function returned something like ```/api/v1.0/users/552f635dd5fbc1fdf5f6295c/documents```, and REST call was ```http://localhost:3000/api/v1.0/users/552f635dd5fbc1fdf5f6295c/documents?currentPage=1&sorters%5B%5D=id%3Adesc```.

In beta.17 my function returns ```/api/v1.0/users/552f635dd5fbc1fdf5f6295c/documents/[object Object]```, and REST call is ```http://localhost:3000/api/v1.0/users/552f635dd5fbc1fdf5f6295c/documents/[object%20Object]?currentPage=1&sorters%5B%5D=id%3Adesc```

My code:

    buildURL: function(type, id) {
        var host = Ember.get(this, 'host'),
            namespace = Ember.get(this, 'namespace'),
            url = [];

        if (host) {
            url.push(host);
        }

        if (namespace) {
            url.push(namespace);
        }

        url.push('users');
        url.push(App.get('userId'));

        if (type !== 'user') {
            url.push(Ember.String.pluralize(type));

            if (id) {
                url.push(id);
            }
        }

        url = url.join('/');

        if (!host) {
            url = '/' + url;
        }

        return url;
    }

I can easily change my code, but it looks like an issue when query is still added after ```buildURL```.

**Comment by jaswilli** [comment]
Here's the discussion on the PR where the change was introduced:  https://github.com/emberjs/data/pull/2966#discussion-diff-28162729

It's certainly problematic to pass around something that's not the id in the `id` argument for people that are overriding `buildURL`.

**Comment by fivetanley** [comment]
Yeah it sucks that it's overloaded.

**Comment by igorT** [comment]
@fivetanley I don't think we should be overloading here, we should pass it as a separate param or something. Nows the time to clean it up, and in the meantime we don't break existing apps. I've seen multiple people complain about this, maybe we should release it as part of beta.18
