### ISSUE TITLE
ActiveModelSerializer errors hash expecting camelcased properties instead of underscored properties in beta.17

### ISSUE THREAD

**Issue by jimmay5469** [emberjs/data#3067]
When I upgrade to beta.17 my tests for server-side errors begin failing to show up, specifically errors for properties which are more than one word (`first_name` fails, `email` doesn't).  I tried changing the response in the test to `firstName` and they began showing up again.

**Comment by jimmay5469** [comment]
Just found that there _is_ a [test](https://github.com/emberjs/data/blob/master/packages/activemodel-adapter/tests/integration/active-model-serializer-test.js#L332) for this in the suite  so I'm gonna make sure it isn't something on my end.  Has anyone else seen this issue?

**Comment by jimmay5469** [comment]
Does anyone know how to get the test here https://github.com/emberjs/data/blob/master/packages/activemodel-adapter/tests/integration/active-model-serializer-test.js#L332 to run?  `npm test` does not seem to be running it for me...

**Comment by pangratz** [comment]
Looks like this is related to changes I made in #3036. Can you post the body of your `422` response?

**Comment by pangratz** [comment]
I think you're right, this seems buggy: http://emberjs.jsbin.com/jutoxuqagi/2/edit?html,js,output. Clicking on save in this JSBin should print the errors under the `firstName` key and not `first_name`. I will investigate ...

**Comment by pangratz** [comment]
So, the problem is that `reason.errors` is passed to the serializer [here](https://github.com/emberjs/data/blob/v1.0.0-beta.17/packages/ember-data/lib/system/store.js#L2046), where `reason.errors` is the errors object looks like `{ first_name: ["invalid firstName"] }`, but the `extractErrors` in the serializer only normalizes the keys of the `errors` property of the passed object [here](https://github.com/emberjs/data/blob/v1.0.0-beta.17/packages/ember-data/lib/serializers/json-serializer.js#L1022)...

**Comment by jimmay5469** [comment]
I haven't dug in to the source enough to completely understand your conclustion, but the 422 response you used in your JSBin is almost identical to the response in my project's test.

What seems slightly more alarming to me at this point is that I don't think the test I mention above is running when executing `npm test`.  I have made modifications to the test so that it should absolutely fail but the suite still completely passes when I run `npm test`, making me think that the test is not run at all.  I checked the Travis build and the test output is the same as what I am seeing locally.  Can you confirm that the test _is_ actually running, and if so what are you running to get the test to execute?

**Comment by pangratz** [comment]
I'm running the tests by starting `ember server` and navigating to [http://localhost:4200](http://localhost:4200). The test is running, as changing the assertion will show a failed test.

The behavior for the passed payload to `InvalidError` changed from [v1.0.0-beta.16.1](https://github.com/emberjs/data/blob/v1.0.0-beta.16.1/packages/activemodel-adapter/lib/system/active-model-adapter.js#L140-L148) to [v1.0.0-beta.17](https://github.com/emberjs/data/blob/v1.0.0-beta.17/packages/activemodel-adapter/lib/system/active-model-adapter.js#L140-L151) in d051616bb0b372f45913c32900e5ef29a22fbc36.

**Comment by jimmay5469** [comment]
Ok, that is very re-assuring, I was just able to do the same.  Thanks!

**Comment by pangratz** [comment]
@jimmay5469 a quick patch before this is fixed upstream in ember-data would be:

``` js
DS.ActiveModelSerializer.reopen({
  extractErrors: function(store, typeClass, payload, id) {
    if (payload && !payload.errors) {
      // JSONSerializer only normalizes the keys of
      // the `errors` property of the payload
      payload.errors = payload;
    }
    return this._super.apply(this, arguments);
  }
});
```

**Comment by jimmay5469** [comment]
Much appreciated @pangratz!

**Comment by bdvholmes** [comment]
I'll be putting together a pull request to address this shortly.

**Comment by pangratz** [comment]
> I'll be putting together a pull request to address this shortly.

:+1:

**Comment by fivetanley** [comment]
@pangratz @bdvholmes hate to bother y'all on the weekend but i'd love to release beta.18 with a fix on monday.

**Comment by bdvholmes** [comment]
I'm putting the fix together tomorrow, does that give you enough time?

Enviado desde mi iPhone
