### ISSUE TITLE
Uncaught TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by ChrisHonniball** [emberjs/data#3071]
Receiving: `Uncaught TypeError: Cannot read property 'map' of undefined | embedded-records-mixin.js:485` on beta.17 with Ember 1.12.0.

This prevents the `model.save()` request from being sent to the server.

**Comment by ChrisHonniball** [comment]
Here is my serializer:

```javascript
export default DS.RESTSerializer.extend(DS.EmbeddedRecordsMixin, {
  primaryKey: 'lead_id',
  
  attrs: {
    addresses: { embedded: 'always' },
    phones: { embedded: 'always' },
    emails: { embedded: 'always' },
    notes: { embedded: 'always' },
    reminders: { embedded: 'always' },
    calls: { embedded: 'always' },
    customFields: { embedded: 'always' }
  }
});
```

**Comment by igorT** [comment]
Which line causes it? Can you maybe reproduce your error in a JSBin? There is a sample one in the CONTRIBUTING.md

**Comment by jakesjews** [comment]
This JSBin should replicate the issue. http://jsbin.com/cehelabiqe/4/edit
It looks like the error happens when the response from saving a record with an embedded array doesn't include the array. It doesn't seem to throw the error when using beta-16 in the same situation.

**Comment by jkatsnelson** [comment]
I think I ran into the same situation, but the error came out like this for me:

https://www.dropbox.com/s/f1qbpy85o3mfw70/Screenshot%202015-05-15%2020.13.09.png?dl=0

**Comment by jkatsnelson** [comment]
reverting back to beta-16 works like a charm.

**Comment by ChrisHonniball** [comment]
I'll make a JSBin as soon as I get a chance but mine doesn't even get to the API when I get this error. I'm assuming it's happening for me at serialization.

**Comment by ChrisHonniball** [comment]
Reverting to beta-16.1 flags a lot of deprecation warnings for your `DS.attr` calls when using Ember 1.12.0.

**Comment by jakesjews** [comment]
I was wrong in my previous comment. it looks like its happening before it sends anything to the server on the save.

**Comment by igorT** [comment]
You really should normalize your embedded payloads and pass back a `[]` for an empty array, but I do agree we should probably guard here. 
cc @wecc

**Comment by jakesjews** [comment]
I agree. We just had some cases where it was unnoticed and it was kinda hard to find the issue. Maybe an assert would be helpful?

**Comment by igorT** [comment]
Ping @wecc

**Comment by ChrisHonniball** [comment]
This seems to have returned in 2.0.1.

**Comment by simo163** [comment]
I am running into the same error when trying to override the serializeBelongsTo.
