### ISSUE TITLE
Assertion failed: You must use Ember.set() to set the `propertyName` property (of [object Object]) to `value` when loading model _again_

### ISSUE THREAD

**Issue by aars** [emberjs/data#3077]
When ember-data fetches a model for a second time and tries to find changed keys it apparently touches the model without using `Ember.set()`, about which ember complains and breaks with the Assertion Failed message.

I've narrowed it down to this line in `mergeAndReturnChangedKeys`: 
https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/model/model.js#L64

Replacing that assignment with a use of `Ember.set()` resolves the issue:
```
// original[key] = val;
ember$data$lib$system$model$model$$set(original, key, val);
```

I think this is a bug, but I might be mistaken. I guess my first question would be: I should be able to run `store.find('someModel', someId)` for the same model/id as many times as I want, right? 

(I'm using ember-data 1.0.0-beta.17. It seems beta.18 doesn't touch this issue.)

**Comment by igorT** [comment]
This seems pretty bad that `_data` became an Ember object. Are you using `modelFragments` by any chance? Or doing anything else funky?

**Comment by aars** [comment]
I am using `modelFragments` ! Let's see if disabling that has any effect.

**Comment by aars** [comment]
@igorT I have completely removed `ember-data.model-fragments` from my project and still have the same issue.

As far as I know I'm not doing anything funky. What kind of funk should I be looking for?

**Comment by igorT** [comment]
can you put a getter on store._data and breakpoint whenever it gets set, and see when it gets replaced by an ember object?

**Comment by aars** [comment]
@igorT a getter? Setter, right? As in, `this.__defineSetter__('_data', function (val) { debugger; this._data = val; })`

**Comment by igorT** [comment]
yeah except you need to save it off to something else other than `_data` that will make you have in infinite loop

**Comment by aars** [comment]
Infinite loops were made :)

I've found the culprit, but I'm not sure why. It was this:
```
export default Ember.Controller.extend({
  // The order we'd like to list entities.
  entitySortOrder: [
    'data.driver',
    'data.person',
    'data.car',
    'data.location'
  ],

  sortedEntities: Ember.computed('something', function () {
    return Ember.ArrayProxy.createWithMixins(Ember.SortableMixin, {
      sortProperties: this.get('entitySortOrder'),
      sortAscending: false,
      content: this.get('something')
    });
  }),

});
```

I think I followed the docs/examples on the Sortable mixin. I'll go figure out what's wrong with it :) Thanks for helping!

Is there maybe a way to catch this behaviour in Ember-data and error on it before it becomes a problem?

**Comment by igorT** [comment]
what is data in the above controller?

**Comment by aars** [comment]
How would I check that? This controller get's multiple models set on it, and only when I reference the `sortedEntities` does it break.

This is the route that uses this controller:
```
export default Ember.Route.extend({
  setupController: function (controller, model) {
    // We are just a wrapping view. Most data used by ContractController.
    controller.set('contract', model);

    // Get components for this product and entities for this contract.
    var components = this.store.find('ProductComponent', {product: model.get('product').get('id')});
    var entities   = this.store.find('ContractEntity', {contract: model.get('id')});

    // Contract controller.
    this.controllerFor('contract').setProperties({
      contract: model,
      components: components,
      something: entities
    });
  }
});
```

(`something` normally has a better name, `entities`. I changed that to something else in my tests, checking to see if I wasn't overwriting/using the `entities` property that exists in my Contract model (being set as `model` in this route)

**Comment by igorT** [comment]
I meant in `data.driver` what does `data` refer to?

**Comment by aars** [comment]
Oh sorry, that is my current (and horrible) method of sorting these. The `contractEntities` fetched here are actually custom joinTables to link many types of `entities` to a `contract`. These fields are the foreign keys for the actual entity model. So by checking if that field (the actual id, not the relation) is set (or, not falsy), I sort them in that order.

**Comment by igorT** [comment]
What is the type of the object under the key `data`? Is it an an ED model?  A Json object?

**Comment by igorT** [comment]
I suspect that you are passing a single model to an array proxy and that it ends up using ED's internal `data` property because its just proxying

**Comment by aars** [comment]
`entities` is not a single model, so `content: this.get('something')` isn't either. But it's pretty clear I'm doing something wrong with this ArrayProxy :)

I might just need to make a seperate controller for these `entities`, make that sortable, and `{render}` that controller into my `contract` controller/template.

Thanks for all the help so far!
