### ISSUE TITLE
No easy way to serialize ids

### ISSUE THREAD

**Issue by amk221** [emberjs/data#3078]
My use case is our API requires the `id` in a JSON payload to be an integer not a string.

* Would like to be able to use `serializeAttribute`, but it doesn't get called with `id`
* Could use a combination of `serialize`, `serializeBelongsTo`, and `serializeHasMany` but still requires you to go through all relationships to alter the IDs.

**Comment by igorT** [comment]
`serializerAttribute` isn't the correct place as an `id` isn't an attribute. Hm, not sure of a nice api that would work with both foreign and primaryKeys. Any ideas?

**Comment by amk221** [comment]
Looks like this used to exist:
https://github.com/emberjs/data/commit/1c55815c37e9946300708634c91c44414dd9a695#diff-49cdc5d5d7a7aa701bcb75661b0d4865L406

**Comment by wecc** [comment]
Closing this as we're tracking the issue in #4477 (should be fixed by #4620)
