### ISSUE TITLE
npm/bower publish v1.0.0-beta.18 plz

### ISSUE THREAD

**Issue by jayphelps** [emberjs/data#3080]
[v1.0.0-beta.18](https://github.com/emberjs/data/releases/tag/v1.0.0-beta.18) has not yet been published to npm or bower, preventing ember-cli users from consuming this new version as normal.

Cc/ @fivetanley 

Edit: I actually incorrectly thought it was published to npm, but turns out it isn't there either. Perhaps release publishes are staggered and I'm not aware..

**Comment by tricknotes** [comment]
Also rubygems too.

**Comment by fivetanley** [comment]
Not yet released. Probably sometime early tomorrow, sorry.

**Comment by givanse** [comment]
release please :pager:

**Comment by fivetanley** [comment]
http://emberjs.com/blog/2015/05/21/ember-data-1-0-beta-18-released.html

**Comment by truenorth** [comment]
:+1:

**Comment by jayphelps** [comment]
Thanks @fivetanley!
