### ISSUE TITLE
Snapshot returns deleted ids in hasMany call

### ISSUE THREAD

**Issue by aaronbhansen** [emberjs/data#3081]
We have a situation where we delete a record, and then the main model is saved (that contains a hasMany relation for the record that was just deleted). When it goes to serialize the hasMany ids in that relation, the deleted records (but not yet saved), are included in that list. 

It seems like if a record is marked as deleted, it shouldn't be included in the snapshot hasMany along with the live records. The snapshot when gathering the ids doesn't do any filtering, but feels like it should check isDeleted before including it in the snapshot.

https://github.com/emberjs/data/blob/v1.0.0-beta.17/packages/ember-data/lib/system/snapshot.js#L276

https://www.dropbox.com/s/lijhqe0gy37t0q7/Screenshot%202015-05-18%2016.31.29.png?dl=0

**Comment by igorT** [comment]
That shouldn't be happening, we remove records from their opposite relationships once they are deleted. Could you maybe reproduce in a jsbin? Can you post your model definitions?

**Comment by aaronbhansen** [comment]
Still trying to replicate this in a jsbin, but haven't been able to yet. Here is another screen shot right after deleting a reward selections. I had 3, deleted 1, and then backer shows 2 if I view the relation. When I view the snapshot, it shows 3.

https://www.dropbox.com/s/43eex2hmphqtnhq/Screenshot%202015-05-19%2014.58.36.png?dl=0

A screen shot of the relations current state. 

https://www.dropbox.com/s/67fm63rn4oj873d/Screenshot%202015-05-19%2015.06.49.png?dl=0

It is a pretty standard relation. We have a backer model that has multiple reward selections.  The manyArray has the correct information, but members doesn't.
