### ISSUE TITLE
Allow adapter populated record arrays to update themselves

### ISSUE THREAD

**Issue by vinilios** [emberjs/data#3082]
Calling `update` method on an adapter populated record array has no effects to the contents of the array as a result of the way update method is implemented. The change to resolve this seems to be trivial and with minor side effects, excluding of course existing misuse of the method.

**Comment by nik045** [comment]
:+1:

**Comment by bmac** [comment]
I believe this is fixed by https://github.com/emberjs/data/pull/4050.
