### ISSUE TITLE
Rejected record (Not found/Unauthorized) remains in store

### ISSUE THREAD

**Issue by Emrvb** [emberjs/data#3085]
When loading a record by id using ajax, if it fails (it is not found or access has been denied) a rejection is fired. This rejection is responsible for unloading the record which was created before the ajax call was executed.

This commit https://github.com/emberjs/data/commit/190133837451b076cf31549d8940084e3f5a62b8 changed the behaviour of the method hasRecordForId causing the rejection to assume there is no record to unload. This results in an odd incomplete record in the store causing subsequent "finds" to fail to update the record (e.g. after the user authenticates and the route is refreshed). 

I have a two proposals to fix this issue but I'm not too familiar with the ember-data internals to oversee the consequences.

1. Revert the commit introducing this issue
2. On rejection, assume there's always record and use recordForId()
3. Abstract finding the record in recordForId() to its own method, use this method to retrieve the record and if it's there unload it.

**Comment by pangratz** [comment]
What version of ember-data are you using? Does the issue described in #1931 sound similar to your problem? If so, it looks like this is solved by the `references` branch, as pointed out here https://github.com/emberjs/data/issues/1931#issuecomment-100173293. Can you confirm?

**Comment by Emrvb** [comment]
Jup, that's it, and looking at the code it should be fixed. Weird it didn't popup in my search.
