### ISSUE TITLE
reload() and fetchById don't restore changed belongsTo

### ISSUE THREAD

**Issue by artych** [emberjs/data#3089]
It is known that if you change record's `belongsTo` property without saving, record doesn't become `dirty` and can't be restored by `rollback()`  emberjs/rfcs#21.

But it was unexpected for me that it also can't be restored by `reload()`, and can't be reloaded by `store.fetchById()`. The only way works for me is `record.unloadRecord()` and then `store.find(..)`.  See http://jsbin.com/qoyacagigi/edit?html,js,output.

Feel free to close if this is expected behavior.

**Comment by pangratz** [comment]
The related test is [`unit/model/merge-test`](https://github.com/emberjs/data/blob/2f8024be6863b7a2b3768588760686239b7208d0/packages/ember-data/tests/unit/model/merge-test.js#L128-L152) which checks that locally modified attributes are not reset after a merge. The test (currently) doesn't have assertions for relationships, so I guess the correct behavior is yet to be decided. I definitely think it should be the same as for attributes, so locally changed relationships are not reset after a `reload`.

**Comment by artych** [comment]
@pangratz, thanks. And what about `fetchById`? http://emberjs.com/api/data/classes/DS.Store.html#method_fetchById. I expected it to be "hard reset version" of `find` method (that fetch model from backend and then create/override model in store).

**Comment by pangratz** [comment]
According to the doc [`fetchById` only calls `reload`](https://github.com/emberjs/data/blob/02706ec5e43e05f66a0b4d226337b86bc4f78d23/packages/ember-data/lib/system/store.js#L531-L532) so the same semantics apply. Looking at the code actually a `findById` is triggered, but this does no hard-reset of local modifications either.

Restoring local relationship changes via `rollback` should eventually work; it is on the [meta list for `1.0` (first entry)](https://github.com/emberjs/data/issues/2545).

**Comment by artych** [comment]
I mean is my expectation about `fetchById` wrong or not? 
Looks like I am not alone, for example see last comment in http://discuss.emberjs.com/t/force-store-to-reload-data-from-api/4441/12.

**Comment by pangratz** [comment]
> I mean is my expectation about fetchById wrong or not?

Your confusion is justified as the naming of the methods is not consistent at the moment. There is [an open RFC](https://github.com/emberjs/rfcs/pull/27) which discusses the semantics of the various methods to get a consistent naming.

**Comment by artych** [comment]
@pangratz, thanks for link.
After reading emberjs/rfcs#27 it is clear that `fetchById` is expected  to load data from the server, even if it's already in the local store.
Therefore I think this is valid issue in case `findById` method.

**Comment by artych** [comment]
about  `reload()`: "locally modified attributes are not reset after a merge..."

as for me `reload()` is very confusing name for such a behavior

**Comment by pangratz** [comment]
That method documentation is highly outdated and has been [last updated at 22. April 2013](https://github.com/emberjs/data/blame/v1.0.0-beta.18/packages/ember-data/lib/system/model/model.js#L1076) :open_mouth: Want to submit a PR?

**Comment by artych** [comment]
Technically I can, and I'd like to, but it is not clearly for me what such a behavior for, so I do not know what description should be written. May be somebody can explain me...

**Comment by artych** [comment]
I could propose to add option `force` with `defaultValue: false`, 
so `model.reload()` and  `model.reload(false)` behaves as now, 
but `model.reload(true)` overrides/resets all locally modified attributes and associations.

Is this sound reasonable?

**Comment by artych** [comment]
As an alternative just to implement fetching with "hard reset" merging strategy. Something like this:
````javascript
	fetchOriginById: function(modelName, id, preload) {
	    if (this.store.hasRecordForId(modelName, id)) {
	    	this.store.getById(modelName, id).unloadRecord();
	    }
	    return this.store.find(modelName, id, preload);
	},
````

**Comment by artych** [comment]
closed since no confirmation
