### ISSUE TITLE
Rendering a hasMany {async:true} in an {{each}} re-renders all items when new item added

### ISSUE THREAD

**Issue by lukesargeant** [emberjs/data#3093]
I am loading a 'dashboard' model, that hasMany 'widget' children {{async:true}}.
I render these widgets using the {{each}} helper on the dashboard template:

    {{#each model.widgets as |widget|}} 
      {{my-widget config=widget}}
    {{/each}}

I add a widget in my dashboard route:
(The widget model has a belongsTo relationship to the dashboard model.)

    actions: {
        addWidget() {
          this.store.createRecord('widget', {
            dashboard: this.modelFor('dashboard.index')
          });
        }
      }

All widgets re-render, and I am sad :-(

By hacking the dashboard response to include the widgets AND removing the {{async:true}}, it works as expected: the {{each}} helper adds the new widget to the screen without re-rendering all widgets.

UPDATE::: This appears to be a bug with Ember Data {{async:true}} hasMany relationships and the events that are fired during the update.

When using {async:true} the ContainerView (managing the {{each}} helper) is having its arrayDidChange hook fired twice. Once with the initial added record, and then again with The whole lot. arrayWillChange is also being fired once for the initial change, then once for removing all items, and then once again to add all items. Unfortunately I climbed the call stack to the Backburner and am not sure how to figure out exactly what is causing this odd sequence of operations in the case of adding to an async relationship.

ANOTHER UPDATE::: I've tracked this down to ManyRelationship.prototype.getRecords, where if the relationship isAsync === true, it will return a PromiseManyArray (where promise = this.findRecords()), rather than this.manyArray. I believe a side effect of this, is the multiple array change events that in turn are causing the {{each}} block to re-render.

**Comment by Kilowhisky** [comment]
I am also encountering this problem. if you use the `.arrangedContent` property in your `{{each}}` iterations this odd behavior doesn't occur and only the new element is rendered.

**Comment by stefanpenner** [comment]
this should be fixed in glimmer.
