### ISSUE TITLE
Async relationships performance issue

### ISSUE THREAD

**Issue by technomage** [emberjs/data#3103]
When loading an object with a large async relationship target set, each target is fetched separately.  This results in 100s of requests to the server to fetch those objects.  Some form of batching should be supported by the adapter interface if not the RESTAdapter.  Given the URL pattern for single object get, either a list of ids in the url or a new url pattern is probably required.  In any case it would be useful if the basic API for adapters allowed the full set of target ids to be provided in a single request.

**Comment by igorT** [comment]
Have you tried turning `coalesceFindRequests` to true?

**Comment by technomage** [comment]
I will look into it. I was not aware of that option. Thanks.

**Comment by igorT** [comment]
@technomage is there anywhere in docs/guides/etc where you would've expected to see it, but didn't? Please do make a PR for docs if you find it helpful, as it does exactly what you asked for.
