### ISSUE TITLE
Allow lookup of hasMany relationship by inverse if supplied.

### ISSUE THREAD

**Issue by mmoonport** [emberjs/data#3106]
I have a hasMany relationship that can potentially have hundreds of records in it. This poses an issue with the way ember data calls the findMany and places all the ids in the query string. I propose there be a way to call the api with the inverse if supplied. That way the call is much smaller and would seem to be much more efficient. 

For example.

var Project = DS.Model.extend({
  groups: DS.hasMany('group', {'inverse': 'project'});
});

instead of calling my api with HOST/api/groups/?ids[]=1&ids[]=2&ids[]=3&ids[]=4...

it would call the query by the inverse

HOST/api/groups/?project=project_id

Any thoughts on how this could be implemented?

**Comment by igorT** [comment]
It seems like https://github.com/emberjs/data/issues/2162 should work for this case
