### ISSUE TITLE
URLs not being built properly after updating to 1.0.0-beta.17

### ISSUE THREAD

**Issue by Azdaroth** [emberjs/data#3108]
After updating from 1.0.0-beta.16.1 to 1.0.0-beta.17 I have problems with URLs not being built properly when using query params, e.g. `this.store.find('client', { name: 'John' })` should build the following URL: `/clients/?name=John`. However, after update it generates ``clients/%5Bobject%20Object%5D&name=John`. As a temporary fix I modified `_buildURL` method in application adapter (to be precise: changed this line: https://github.com/emberjs/data/blob/v1.0.0-beta.17/packages/ember-data/lib/adapters/build-url-mixin.js#L94 into `if (id && typeof id !== "object") { url.push(encodeURIComponent(id)); }`), but it just feels wrong. I'm using `ember-json-api`, but I don't see how it could break, everything was working fine until the update. Has such issue ever happened before?

**Comment by fivetanley** [comment]
Can you try beta.18?

**Comment by timtwomey** [comment]
Same here with 1.0.0-beta.17. Updating to 1.0.0-beta.18 resolved the issue.

**Comment by sly7-7** [comment]
@timtwomey Thanks for the heads up. I'm closing. @Azdaroth Feel free to reopen if upgrading to beta.18 doesn't resolve your issue.

**Comment by pangratz** [comment]
Looks like 3b4b136d99b519c01008fd89aa3b6ba9a26a3374 is the commit which solves this ...

**Comment by Azdaroth** [comment]
Yeah, updating to beta.18 solves the problem, thanks.
