### ISSUE TITLE
After update to beta18, ActiveModelSerializer dasherize model instead of undercorizing them

### ISSUE THREAD

**Issue by karellm** [emberjs/data#3112]
I have a very simple `ApplicationSerializer`:

```javascript
import DS from 'ember-data';

export default DS.ActiveModelSerializer.extend({
  normalizePayload: function(payload) {
    delete payload.errors;
    delete payload.message;
    delete payload.code;
    return payload;
  }
});
```

After updating to beta18 though, my app started crashing when saving models with a dash in them. So a `chart-metric` model would call the `/chart_metric` endpoint, and it now call the `/chart-metric`, causing many places in my app to crash.

I looked at the changelog but this doesn't seem like a wanted behaviour, especially not with the `ActiveModelSerializer`.

Any idea what is going on? Thanks!

**Comment by fivetanley** [comment]
Are you overriding buildURL anywhere?

**Comment by fivetanley** [comment]
or `pathForType` https://github.com/emberjs/data/blob/f5f15dfe8d6cd6729f380bcc048f9c4a17d7eece/packages/activemodel-adapter/lib/system/active-model-adapter.js#L118

**Comment by karellm** [comment]
I am calling manually `buildUrl` at couple place where the serializer didn't work. Though I do not override it.

I don't override `pathForType` either. I read the changes in the changelog before posting to see if I was doing something wrong but couldn't figure it out.

**Comment by fivetanley** [comment]
> I am calling manually buildUrl

Do you see any deprecations for using `typeKey`?

**Comment by karellm** [comment]
@fivetanley I'm not sure what you mean. Also the code that breaks doesn't make use of `buildUrl`.

And calling `_super` in `normalizePayload` didn't help (which would have been weird anyway). I will leave it there though, thanks for the catch!

**Comment by fivetanley** [comment]
Do you see any deprecation warnings when you open the developer tools? It shows up in the console tab.

**Comment by karellm** [comment]
No deprecation warnings no :(

**Comment by karellm** [comment]
@fivetanley I'm sorry for the trouble, I had a `pathForType` override in my code that I totally missed in my search. Thanks a lot for the support!
