### ISSUE TITLE
isReloading flag not set on hasMany relationships

### ISSUE THREAD

**Issue by barelyknown** [emberjs/data#3115]
When you reload a model, its `isReloading` flag is set. But, when you reload a relationship, there is no flag. The flag would be helpful for adapters that suppress API calls for relationships that were previously loaded.

**Comment by igorT** [comment]
Yes, we would also need to support this for `belongsTo` relationships, I think https://github.com/emberjs/rfcs/pull/57 should help us get there

**Comment by kabirsikand** [comment]
+1
