### ISSUE TITLE
{async : true} relationship and .then() not working with new records

### ISSUE THREAD

**Issue by jackmatt2** [emberjs/data#3117]
ember-data: 1.0.0-beta.12

I am creating a model such as the following in my routes model hook, (the address property is {async : true})

```javascript
    return this.store.createRecord('user', {
      address : this.store.createRecord('address'),
    });
```

The problem is that in the controller code I am doing

```javascript
//The following works fine when editing an existing a record
this.get('model.address').then(function(address) {
   //It says that the get(...).then is undefined when creating a record
});
```

The reason for using .then() is that the same controller is used for editing existing records as well as adding new ones.

Is there a workaround for this?  I can't update past beta.14 because of other issues where my Ember.Select controls no longer work.

**Comment by jackmatt2** [comment]
I got it working this way, but it seems a little weird to have to do this:

```javascript
    return this.store.createRecord('user', {
      address : new Promise(function(resolve, reject) {
        resolve(this.store.createRecord('address'));
      }.bind(this)),
    });
```

**Comment by jmurphyau** [comment]
I'm unable to replicate your issue... http://emberjs.jsbin.com/hunefe/1/edit?html,js,console,output

**Comment by jackmatt2** [comment]
@jmurphyau 

Thanks for you help, I feed like a total idiot now because the object I was creating in `this.sore.createRecord()` was not the correct record type.
