### ISSUE TITLE
Is there a word for this?

### ISSUE THREAD

**Issue by tonywok** [emberjs/data#3118]
Pardon if this is a silly question, but is there a word for defining functions separated by dollar sign. For example, https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/relationships/state/has-many.js#L7

I see it used in some of the internals, but haven't been able track down a name for this, and we don't seem to be consistent.

I'm guessing it's just for short circuiting the prototype inheritance lookups in hot code paths for perf?

I know this isn't a bug or feature request, but it might be a documentation issue for those of us reading through the code. Either way, apologies if this isn't the appropriate avenue.

**Comment by igorT** [comment]
Not sure, @stefanpenner told me to use it.
