### ISSUE TITLE
Find a solution for JSHint / ESLint regarding async / await

### ISSUE THREAD

**Issue by tchak** [emberjs/data#3129]
There is two solutions to this :

* fork `jshint` to support `async` / `await`
* write or find a tool to convert `jshint` configuration to `eslint` configuration

@fivetanley you have some ideas about this?

**Comment by rwjblue** [comment]
I believe that both @jonathankingston and @teddyzeenny have converted projects from JSHint to ESLint.  Perhaps, they could offer some guidance.

**Comment by jonathanKingston** [comment]
@teddyzeenny did the grunt work of updating [ember-inspector](https://github.com/emberjs/ember-inspector) to support ES6.

However the work done here can be seen here:
https://github.com/emberjs/ember-inspector/blob/master/.eslintrc

Using babel-eslint was the easiest way to support this.

The config also uses a setup which I hope to become de-facto Ember setup (Which is friendlier to lower how strict the setup is, as seen in ember-inspector setup):
https://github.com/jonathanKingston/eslint-config-ember

**Comment by tchak** [comment]
@jonathanKingston for what I understood, the core team stand is that using `eslint` in ember-cli is a no go without `.jshintrc` file support...

**Comment by tchak** [comment]
@rwjblue sorry if it was not clear from the issue. It is not about internal usage in `ember-data`. It is about exposing public/application api that needs `async`/`await`. Which means, we need support for `async`/`await` in `ember-cli`. So it is about using `eslint` as default in `ember-cli` or bundle our own version of forked `jshint`...

**Comment by igorT** [comment]
cc @fivetanley

**Comment by Turbo87** [comment]
FYI `ember-cli` has lately moved from JSHint/JSCS to using ESLint internally and will likely suggest the same for new Ember projects in the future too.

I've used https://www.npmjs.com/package/polyjuice for the conversion from `.jshintrc` to `.eslintrc` and it worked quite well, but a few manual adjustments were still needed.

see https://github.com/ember-cli/ember-cli/pull/5455 for details.

**Comment by bmac** [comment]
`ember-cli` is moving to ESLint. This issue can be closed.
