### ISSUE TITLE
addCanonicalRecord should assert record._records[this.inverseKey] is not null

### ISSUE THREAD

**Issue by technomage** [emberjs/data#3135]
The logic for handling inverseKey needs to validate that there is a relationship at the provided key, and assert to indicate where the error exists.  Currently a mismatch in inverseKey will raise an exception with no indication which record type or relationship is involved.

**Comment by igorT** [comment]
Want to add a failing integration test? We should probably be asserting in an earlier step when we get the class def. The inverse finding is a great candidate to be taken out, isolated and unit tested more.

**Comment by fivetanley** [comment]
Closing due to lack of response. Please feel free to re-open or open a new issue.
