### ISSUE TITLE
Consider optimizing `transitionTo`

### ISSUE THREAD

**Issue by igorT** [emberjs/data#3142]
https://github.com/emberjs/data/pull/3094#discussion_r31473097

**Comment by wecc** [comment]
@igorT would you be able to elaborate?

**Comment by stefanpenner** [comment]
@igorT share your thoughts sir!

**Comment by runspired** [comment]
I optimized it a bunch here https://github.com/emberjs/data/pull/4562/ and I think again in a later PR but I think there is still some function optimizing that could be done.

**Comment by runspired** [comment]
Closing in favor of the already completed optimizations as soon the state machine will be killed off.
