### ISSUE TITLE
RecordArray#addRecord is unused

### ISSUE THREAD

**Issue by bmac** [emberjs/data#3153]
@igorT can this code be removed?

https://github.com/emberjs/data/blob/6d6c6462fe597be556d358585e9445513cbc662d/packages/ember-data/lib/system/record-arrays/record-array.js#L121-L136

**Comment by igorT** [comment]
do we use removeRecord?

**Comment by bmac** [comment]
yes

**Comment by sly7-7** [comment]
@bmac It turns out that recordArrayManager [uses the deprecated _pushRecord](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/record-array-manager.js#L127). So I think this could be closed as soon as I remove the deprecated function
