### ISSUE TITLE
DS.Model.relationshipNames is untested

### ISSUE THREAD

**Issue by bmac** [emberjs/data#3163]
https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/relationships/ext.js#L349-L391

**Comment by bmac** [comment]
DS.Model.eachRelatedType also needs a test
https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/relationships/ext.js#L521-L536

**Comment by yratanov** [comment]
@bmac in what file should these test be?

**Comment by bmac** [comment]
These tests can go in https://github.com/emberjs/data/blob/master/packages/ember-data/tests/unit/model-test.js.
