### ISSUE TITLE
Implement `filterBy` on results of `store.find` that listens for changes and recomputes

### ISSUE THREAD

**Issue by igorT** [emberjs/data#3171]

**Comment by wecc** [comment]
#3263 was reverted in #3648

From https://github.com/emberjs/data/pull/3263#issuecomment-129531675:

> We talked about this issue in a recent team meeting and it sounds like this is a regression that we want to fix. The current fixing is we will back out the filterBy changes and replace it with a new name or a more limited API.

Unsure if this has been re-implemented with another name? ping @bmac @pangratz

**Comment by pangratz** [comment]
This has been implemented in an addon https://github.com/ember-data/ember-data-live-filter-by
