### ISSUE TITLE
Consider refactoring the attrs hash for 1.0

### ISSUE THREAD

**Issue by igorT** [emberjs/data#3186]
Serializers are currently customized using the `attrs` hash
For example: http://emberjs.com/api/data/classes/DS.RESTSerializer.html#property_attr
However the `attrs` hash grew out organically and applies to both relationships and attributes. The attrs name can be confusing, should we change it to options or smth?

**Comment by bmac** [comment]
Is this the attrs hash on the serializer?

**Comment by igorT** [comment]
Yes, it's weird its called attrs yet works for both attributes and relationships
