### ISSUE TITLE
Assertion Failed for InternalModel, Please pass a dasherized string

### ISSUE THREAD

**Issue by givanse** [emberjs/data#3192]
Changes related to 61928c8b1d4543a63f1c4b68e386c0cd5223a3e3 instruct us to use dasherized strings.

In `deserializeRecordId` when the call for `store._internalModelForId` is made, the argument isn't a dasherized string. Printing the object shows that its an `InternalModel`.

```js
InternalModel
_relationships:
  initializedRelationships: Object
  record: InternalModel
modelName: "column"
type: mvc-tree@model:column: // needs to be dasherized
```

Should `_internalModelForId` receive `modelName`? Or, during the instantiation of the InternalModel `type` is receiving the wrong value?

**Comment by givanse** [comment]
I tried a hack:

```js
if ( typeof id.type !== 'string' ) {
  data[key] = store._internalModelForId(id.modelName, id.id);
} else {
  data[key] = store._internalModelForId(id.type, id.id);
}
```

It worked just fine.

**Comment by sly7-7** [comment]
@givanse If you could reproduce in a jsbin or in a test it would be great

**Comment by iamjstates** [comment]
I'm getting the same error - @givanse where did you place your hack?

**Comment by igorT** [comment]
@iamjstates can you reproduce it in a jsbin or test?

**Comment by iamjstates** [comment]
I fixed the error - it was with my codebase.

Thanks

**Comment by igorT** [comment]
Thanks! What was it?

**Comment by jcbvm** [comment]
I have the same error, looks like the same point where it is failing. @iamjstates what was going wrong in your codebase?
