### ISSUE TITLE
Cannot read property '_attributes' of undefined on Canary using Ember 1.9.1

### ISSUE THREAD

**Issue by jcope2013** [emberjs/data#3200]
InternalModel gets passed to hasValue which is undefined which then cause this error

var internalModel = this._internalModel; //undefined
if (hasValue(internalModel, key)) 

```
Cannot read property '_attributes' of undefined
```

https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/model/attributes.js#L304
https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/model/attributes.js#L221

**Comment by igorT** [comment]
Can you submit a jsbin or test reproducing please?

**Comment by jcope2013** [comment]
seems like it is a ember validations (https://github.com/dockyard/ember-validations) issue, i will file an issue there

**Comment by knownasilya** [comment]
I'm seeing this issue, but not using ember-validations.

```
TypeError: Cannot read property '_attributes' of null
    at getValue (attr.js:37)
    at Class.set (attr.js:156)
    at ComputedProperty.computedPropertySet [as _set] (ember.debug.js:19397)
    at ComputedProperty.computedPropertySetWithSuspend [as setWithSuspend] (ember.debug.js:19377)
    at ComputedProperty.computedPropertySetEntry [as set] (ember.debug.js:19355)
    at new Class (ember.debug.js:38489)
    at Function._ClassMixinProps.create (ember.debug.js:38704)
    at FactoryManager.create (ember.debug.js:3766)
    at Proxy.create (ember.debug.js:3250)
    at InternalModel.getRecord (-private.js:6553)
```

I'm using a `normalizeFindAllResponse` hook with the `RESTSerializer`, i.e.

```js
import RESTSerializer from 'ember-data/serializers/rest';

export default RESTSerializer.extend({
  normalizeFindAllResponse(store, primaryModelClass, payload) {
    let type = 'optout';

    return {
      data: payload.map(id => {
        return {
          type,
          id,
          attributes: {
            propertyId: id
          }
        };
      })
    };
  }
});
```

Any ideas on what the issue might be? The JSON API structure looks good.
Where can I put a breakpoint to see if the record is created?

**Comment by knownasilya** [comment]
@bmac @runspired @stefanpenner any thoughts on this?

**Comment by knownasilya** [comment]
Here's the data going in:

![screen shot 2017-07-06 at 11 12 36 am](https://user-images.githubusercontent.com/34726/27918157-194b42f4-623c-11e7-8e25-e929d1a6433a.png)

**Comment by knownasilya** [comment]
Here's another screenshot:

![screen shot 2017-07-06 at 11 20 33 am](https://user-images.githubusercontent.com/34726/27918513-2d871274-623d-11e7-81e8-bb1814576753.png)

**Comment by knownasilya** [comment]
This seems to happen when a service is being injected via an initializer, i.e.

```js
  application.inject('model', 'community', 'service:community');
```
