### ISSUE TITLE
Store#findHasMany behavior

### ISSUE THREAD

**Issue by sozuuuuu** [emberjs/data#3210]
The doc says Store#findHasMany accepts `type` either a string or a subclass of DS.Model but...

### Does not work

- With a subclass of DS.Model: store.findHasMany(owner, 'relationships', this.container.lookupFactory('model:relationship'))
- With a string: store.findHasMany(owner, 'relationships', 'relationship')

### Works

It successfully requests to `/owners/x/relationships`

- store.findHasMany(owner, 'relationships', owner.relationshipFor('relationships'))

Am I doing something wrong?

**Comment by bmac** [comment]
Looks like a do bug. It should say the 3rd argument is the relationship object. @sozuuuuu would you like to open a pr to fix the docs?
