### ISSUE TITLE
Uncaught ReferenceError: DS is not defined

### ISSUE THREAD

**Issue by jrm2k6** [emberjs/data#3219]
npm ember-data 1.0.0-beta.19
bower ember-data 1.0.0-beta.18
ember-cli 0.2.7
ember 1.12.0

```
import Ember from 'ember';
import DS from 'ember-data';

export default Ember.Route.extend({
});
```

Error: Uncaught ReferenceError: DS is not defined

I tried to uninstall/reinstall the bower and npm packages. What should I try now?

**Comment by fivetanley** [comment]
try setting it to beta.19 in your bower.json?

**Comment by fivetanley** [comment]
window.DS seems to get defined in globals mode so I'm a bit confused here, as the addon should just load that.

**Comment by jrm2k6** [comment]
I was going to try that either have both a 18 or 19. Why are they different though? The bower package hasn't been updated?

**Comment by jrm2k6** [comment]
window.DS is undefined. 
Switching both to 19 or 18 doesn't change a thing.

**Comment by fivetanley** [comment]
Bower should be updated.

**Comment by jrm2k6** [comment]
This is what the bower installation shows though

https://gist.github.com/jrm2k6/b3292b624ea33ebd23cd

Something interesting in there? I chose the second option both time.

**Comment by fivetanley** [comment]
Does changing both package.json and bower.json to beta.18 make a difference?

**Comment by jrm2k6** [comment]
I tried already both 18. Will try again. But it didn't make a difference

**Comment by fivetanley** [comment]
Are you sure you're not getting any other errors in your DevTools console?

**Comment by fivetanley** [comment]
Also if the stack is available for your current error that would be great as well.

**Comment by jrm2k6** [comment]
DevTools:

![Uploading Screen Shot 2015-06-05 at 4.19.52 PM.png…]()


Stack:
![screen shot 2015-06-05 at 4 20 47 pm](https://cloud.githubusercontent.com/assets/1088099/8016896/dcc6611a-0b9e-11e5-8c33-a784b293c239.png)

**Comment by jrm2k6** [comment]
I just generate a new project, and it seems to be working with beta-18/beta-19 for both. I don't know why it doesn't work in my other project though.

**Comment by jrm2k6** [comment]
It seems to be related to my current project only, creating some ember projects on their own, included or not in another npm based project seems to be fine (I was suspecting some ember-cli magic). It seems to be problematic even with a fresh ember project in my current one. Any idea how I should start to debug what is going on?

**Comment by jrm2k6** [comment]
The issue is with this package https://github.com/unionups/ember-cli-bootstrap-sass. Removing it works and DS is required correctly.

**Comment by Intelliarts** [comment]
I don't use `ember-cli-bootstrap-sass`, but have the same issue. 

model:  

```coffeescript
`import DS from 'ember-data'`

User = DS.Model.extend {
  email: DS.attr('string')
}

`export default User`
```

route:

```coffeescript
`import User from 'frontend/models/user'`
```

In console: `ReferenceError: DS is not defined` in  vendor.js:57300:4

code in vendor.js:

```coffeescript
define('ember-data', [], function() {
  "use strict";

  return {
    'default': DS
  };
});
})();
```

Error caught in  `'default': DS` line

Any thoughts?

**Comment by jrm2k6** [comment]
Are you using some specific package? U would try to run the node REPL and
import ember data, and check if DS is defined. If if works I would remove
my npm package one by one to see if one is problematic.

**Comment by mattma** [comment]
I have run into the same issue here. 

I am using "Ember@2.0.0-beta.1" and "Ember-cli@0.2.7"

When I have `ember-data@1.0.0-beta.18` in **bower.json** and **package.json** as dependency, I run into the problem below:

```bash
Uncaught TypeError: Cannot read property 'indexOf' of undefined(anonymous function) @ adapter.js:486(anonymous function) @ main.js:131
app-shims.js:15Uncaught ReferenceError: DS is not defined
```

When I have `ember-data@1.0.0-beta.19.2` in **bower.json** and **package.json** as dependency, I run into the problem below:

```bash
Uncaught TypeError: Cannot read property 'indexOf' of undefined(anonymous function) @ fixture-adapter.js:10(anonymous function) @ main.js:130
app-shims.js:15Uncaught ReferenceError: DS is not defined
```

Different errors on different version. Trying to remove one package at the time is not ideal since app requires most of them. I have to remove the related code to avoid other errors as well. Any thoughts?

**Comment by jrm2k6** [comment]
@mattma I agree that removing one package at a time is annoying. What I would do in your case, to rule-out an issue caused by another package is to create a new project, and add the same package as you have one by one. That is my only idea so far.

**Comment by mattma** [comment]
@jrm2k6 @fivetanley 

After play around for an hour, I think the issue is coming from "Ember" core. There is nothing broken or need-to-be-fixed in Ember-data side. Or any other npm modules or ember-cli dependencies. 

simply switch to a different version of Ember-core in "bower.json", then run 'bower install'. You should have a working app. 

Then switch back to a latest "Ember@2.0.0-beta.1". run "bower install". Now you should have a latest greatest working app with latest "Ember-data@1.0.0-beta.19.2".

I believe when running "bower install", the dependencies order have been messed up.

**Comment by bmac** [comment]
@mattma Is correct. Ember Data does not currently work with Ember 2.0 beta. Ember has removed some deprecated IE8 support code in the Ember 2.0 branch that Ember Data was relying on for IE8 support. 

In the next few days there will be an Ember Data 2.0 beta release that is compatible with the current Ember 2.0 beta.

**Comment by mattma** [comment]
@bmac Thank you for the confirmation. I cannot wait to use Ember Data 2.0 beta release. Mainly because I am on the alpha wagon and ready for the latest 2.0 one way binding goodness. Is there an ETA on the release date?

**Comment by visoft** [comment]
I'm getting the same problem with Ember 1.13.2 + Ember Data beta 1.0.0-beta19.1. I can't upgrade Ember Data yet because I'm blocked [by this bug](https://github.com/emberjs/data/issues/3449).

**Comment by bmac** [comment]
@visoft. Is there another error on the page before the "DS is not defined"?

**Comment by visoft** [comment]
Nope, just that error.
