### ISSUE TITLE
Make async relationships default

### ISSUE THREAD

**Issue by igorT** [emberjs/data#3220]
In current ember data throw a deprecation on any relationship that is not `async:false`. Write an Ember Watson helper to add `{async:false}` to each one

**Comment by igorT** [comment]
@tomdale @wycats **we are keeping the sync relationships, but changing the defaults

**Comment by abuiles** [comment]
@igorT just released https://github.com/abuiles/ember-watson/releases/tag/v0.5.1 to help with this, thanks to @Serabe

**Comment by Serabe** [comment]
This is still open. Anything I can help with?

**Comment by sly7-7** [comment]
Hm, I'm closing since https://github.com/emberjs/data/pull/3488 has been merged. 
@Serabe Thanks for the heads up :+1:

**Comment by sly7-7** [comment]
Well, I thinks this could probably be closed, the Ember Watson exists, and https://github.com/emberjs/data/pull/3488 has been merged. 
@igorT c/d ?

**Comment by bmac** [comment]
I agree @sly7-7 this issue can be closed.
