### ISSUE TITLE
Convert internal tests to use json api format for `store.push`

### ISSUE THREAD

**Issue by igorT** [emberjs/data#3223]
Everywhere where we do,
`store.push(type, data)` in tests, we need to convert to `store.push(jsonApiFormat)`
We can also break this up in multiple PRs and merge to a branch.

**Comment by igorT** [comment]
Instead of pushing something like
```
store.push('user', { 
  id:1, 
  name: 'bmac', 
  friends: [1,2,3], 
  links: { 
    other: 'hello' 
  }
})
```
should push

```
```
store.push('user', { 
  id:1, 
  name: 'bmac', 
  locations: [1,2,3], 
  links: { 
    other: 'hello' 
  }
})
```
store.push({ 
  id:1, 
  type: 'user',
  attributes: {
    name: 'bmac'
  },
  relationships: { 
    friends: {
       data: [{ type: 'location', id:1}, { type: 'location', id:2}, { type: 'location', id:3}]
     },
     other: {
       links: { 
         related: 'hello' 
       }
    }
})
```

**Comment by igorT** [comment]
Will need to temporarily comment out  `Ember.assert('Passing classes to store methods has been removed. Please pass a dasherized string instead of '+ Ember.inspect(modelName), typeof modelName === 'string');`

**Comment by fivetanley** [comment]
Why?

**Comment by Serabe** [comment]
Sorry, I've been in a plane for most of my weekend. I see @stevenwu has started to tackle the issue. If it is too big for one person and you decide to split it in several, or if @stevenwu needs some help, just let me know.
