### ISSUE TITLE
typeForRoot on serializer no longer being called

### ISSUE THREAD

**Issue by jkblgithub** [emberjs/data#3225]
We are currently on Ember Data 1.0.0-beta.18, Ember 1.12 and CLI 0.2.7.

Since this last update, we are getting ember data assertion warnings like the following:
```
[Warning] WARNING: Encountered "open_requests" in payload, but no model was found for model name "open-request" (resolved model name using vault@serializer:appuser:.typeForRoot("open_requests")) (vendor.js, line 15423)
```
I also noticed that a console log we included in the appuser serializer is no longer called:
```
export default DS.RESTSerializer.extend( {
    typeForRoot: function(root) {
        console.log('appuser serializer called', root);
        if (root === 'open_requests') return this._super('openrequest');
        return this._super(root);
    },
});
```
I can confirm that TypeForRoot was called prior to this update. We have had a number of other issues since upgrading and it seems that they could all be related in some way to the serializers, so the questions are why are we getting these warnings and why is typeForRoot no longer being called?

**Comment by jcope2013** [comment]
"POTENTIALLY BREAKING CHANGE if you override typeForRoot currently introduce modelNameFromPayloadKey and deprecate typeForRoot @fivetanley
RESTSerializer#typeForRoot has been deprecated. You can use RESTSerializeer#modelNameFromPayloadKey instead.
Added RESTSerializer#payloadKeyFromModelName. This allows you to
typeKey on Snapshots and Model classes has been deprecated. Use modelName instead. specify the outgoing root key for a JSON payload."

https://github.com/emberjs/data/blob/master/CHANGELOG.md

"DS.RESTSERIALIZER.TYPEFORROOT IS NOW DS.RESTSERIALIZER.MODELNAMEFROMPAYLOADKEY

To gain more consistency in the naming change of typeKey to modelName, typeForRoot has been renamed to modelNameFromPayloadKey. The function serves the same purpose, so this should be a quick refactor you can achieve via search and replace in your project. While calling typeForRoot will trigger a deprecation warning, overriding in a subclass won't."

http://emberjs.com/blog/2015/05/21/ember-data-1-0-beta-18-released.html
