### ISSUE TITLE
`store.findAll(type)` should be made public

### ISSUE THREAD

**Issue by bmac** [emberjs/data#3227]
store.[findAll](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/store.js#L1000) is currently private. It should be made public and the docs should be updated to use this method.

`store.find(type)` should be deprecated and suggest the use of `store.findAll` instead.

`fetchAll` should be deprecated and suggest the use of `store.findAll` instead.

**Comment by HeroicEric** [comment]
I'm on it
