### ISSUE TITLE
Add findByRecord and deprecate findById

### ISSUE THREAD

**Issue by bmac** [emberjs/data#3228]
Rename [findById](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/store.js#L616) to `findByRecord`. Update all internal references of `findById` to `findByRecord`.

Add a new `findById` method that logs a deprecation warning then delegates to `findByRecord`.

**Comment by igorT** [comment]
https://github.com/emberjs/rfcs/pull/27#issuecomment-109627841  calls it `findRecord` and not `findByRecord` ?

**Comment by HeroicEric** [comment]
@igorT I believe those are to be two separate methods (`findByRecord` and `findRecord`). 

I asked @bmac about the differences and he said "`findByRecord` does some extra bookkeeping and should be private"

**Comment by igorT** [comment]
Ah is this just an internal cleanup?

**Comment by bmac** [comment]
Oops this should have been findRecord. My mistake
