### ISSUE TITLE
Add store.query method

### ISSUE THREAD

**Issue by bmac** [emberjs/data#3229]
Rename [store.findQuery](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/store.js#L980) to `query`. 

Update internal references to `findQuery` and make sure they use the new `query` method.

Update [store.find(type, {query: 'object'})](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/store.js#L534) to log a deprecation warning that recommends the use of `store.query`.

Add a new `store.findQuery` method which logs a deprecation warning and delegates to store.query.

**Comment by csantero** [comment]
I'm working up a PR for this.
