### ISSUE TITLE
Deprecation warnings from RESTSerializer in canary

### ISSUE THREAD

**Issue by bmac** [emberjs/data#3231]
In Canary I'm seeing the RESTSerialzer trigger the "Passing classes to store methods has been removed. Please pass a dasherized string instead of App.Author" deprecation warning. 

http://emberjs.jsbin.com/gexuhevefi/3

The offending line is 
https://github.com/emberjs/data/blob/43710498765c02f6dc2ad65f43003811c51978ad/packages/ember-data/lib/serializers/rest-serializer.js#L454

It should be passing `modelName` instead of `type`.

**Comment by wecc** [comment]
I thought I fixed this :confused:
