### ISSUE TITLE
Promises responses returns internalModels in app code instead of DS.Models.

### ISSUE THREAD

**Issue by charlatan154** [emberjs/data#3240]
Promises responses, such responses from `find`, exposes internalModels to app code instead of DS.Model. Shouldn't internalModels used only from ember-data internally as mentioned [here](https://github.com/emberjs/data/commit/4a0447427c7b02806520b256aca210eefbb30ae1)?
[Example JSBin](http://emberjs.jsbin.com/bokatifopa/1/edit?js,console,output)
[Stackoverflow question](http://stackoverflow.com/questions/30680516/ember-data-1-0-0-beta-19-store-find-returns-ds-internalmodel-instances/30689564#30689564)

**Comment by igorT** [comment]
I only see `App.Event` in your jsbin results?

**Comment by charlatan154** [comment]
i guess my mistake was using `this.get('events.content')`, in my app code, which returns internalModels now. so now i have to change it to `this.get('events')` to work. right?

**Comment by igorT** [comment]
Yup, you shouldn't be poking inside `.content`
