### ISSUE TITLE
private methods that don't start with underscore

### ISSUE THREAD

**Issue by fivetanley** [emberjs/data#3249]
Some of these should be public; some of these need to have underscores added. If you have commit bit, feel free to edit this. If you don't, please comment below.

Once each item in this list has an actionable item, our plan of action is to

1: Move the method to its underscored form
2: Deprecate the should-be-private methods.
- [x] packages/activemodel-adapter/lib/system/active-model-serializer.js
  - [x] normalizeRelationships
- [ ] packages/ember-data/lib/adapters/build-url-mixin.js
  - [ ] urlPrefix
- [ ] packages/ember-data/lib/adapters/rest-adapter.js
  - [ ] findAll - public 
  - [ ] findQuery - public 
  - [ ] ajax
  - [ ] ajaxOptions - public
- [ ] packages/ember-data/lib/serializers/json-serializer.js
  - [ ] applyTransforms
  - [ ] normalizeAttributes - public
  - [ ] normalizeRelationships - public
  - [ ] normalizeUsingDeclaredMapping
  - [ ] normalizeId - public
  - [ ] normalizeErrors - public
  - [ ] transformFor
- [ ] packages/ember-data/lib/system/model/errors.js
  - [ ] unknownProperty
  - [ ] nextObject
- [x] packages/ember-data/lib/system/model/internal-model.js
  - [x] createSnapshot
  - [x] loadingData
  - [x] loadedData
  - [x] notFound
  - [x] pushedData
  - [x] adapterWillCommit
  - [x] adapterDidDirty
  - [x] send
  - [x] transitionTo
  - [x] clearRelationships
  - [x] updateRecordArrays
  - [x] updateRecordArraysLater
  - [x] adapterDidInvalidate
  - [x] adapterDidError
- [x] packages/ember-data/lib/system/model/model.js
  - [x] send
  - [x] transitionTo
  - [x] unloadRecord
  - [x] adapterDidDirty
  - [x] trigger
  - [x] create
- [x] packages/ember-data/lib/system/record-arrays/adapter-populated-record-array.js
  - [x] load
  - [x] loadRecords
- [x] packages/ember-data/lib/system/record-arrays/filtered-record-array.js
  - [x] updateFilter
- [ ] packages/ember-data/lib/system/record-arrays/record-array.js
  - [ ] objectAtContent
  - [ ] addInternalModel
  - [ ] removeInternalModel
- [ ] packages/ember-data/lib/system/adapter.js
  - [ ] findAll
  - [ ] findQuery
- [x] packages/ember-data/lib/system/many-array.js
  - [x] loadingRecordsCount
  - [x] loadedRecord
  - [ ] createRecord
- [ ] packages/ember-data/lib/system/store.js
  - [x] init (private, but not sure how to document)
  - [x] serialize (private)
  - [ ] findById (public)
  - [ ] findByIds (public? ask @igorT)
  - [x] fetchRecord (private)
  - [x] reloadRecord (private)
  - [ ] recordForId (deprecate?? ask @bmac)
  - [ ] findMany (private)
  - [ ] findHasMany (private)
  - [ ] findBelongsTo (private)
  - [x] findAll (public)
  - [x] didUpdateAll (private)
  - [x] dataWasUpdated (private)
  - [ ] scheduleSave (private)
  - [ ] flushPendingSave (private)
  - [ ] didSaveRecord (private)
  - [ ] recordWasInvalid (private)
  - [ ] recordWasError (private)
  - [ ] updateId (private)
  - [x] typeMapFor (private)
  - [x] buildRecord (private)
  - [x] dematerializeRecord (should be public, but is deprecated)
  - [x] adapterFor (should be public - fivetanley)
  - [x] serializerFor (should be public - fivetanley)
  - [x] retrieveManagedInstance (should be private - fivetanley)

**Comment by igorT** [comment]
`packages/ember-data/lib/adapters/fixture-adapter.js`
is deprecated anyhow

**Comment by bmac** [comment]
I think it is safe to deprecate `recordForId`.

**Comment by tchak** [comment]
I am thinking that internal-model should not have underscored methods as the instance in itself is private. It just makes things more confusing in the internal code. There is also a lot of things that could be simplified in terms of API surface in `internal-model`/`states`. If can make a pass if we agree on principle.
