### ISSUE TITLE
prefix private methods with underscore - store.js

### ISSUE THREAD

**Issue by fivetanley** [emberjs/data#3250]
Steps to fixing this issue:

1) deprecate the method. You can use `Ember.deprecate('serialize was documented as private and will be removed in the next version of Ember Data.')`
2) move the method to an underscored method (for example `_serialize`) and update usages in the codebase

If the item is labeled in parenthesis as `(public)`, the `@private` yuidoc tag should be removed. Otherwise, if it is `private`, take the steps above to deprecate and rename the method.
- [ ] packages/ember-data/lib/system/store.js
  - [ ] init (private, but not sure how to document)
  - [ ] serialize (private)
  - [ ] findById (public)
  - [ ] findByIds (public? ask @igorT)
  - [ ] fetchRecord (private)
  - [ ] reloadRecord (private)
  - [ ] recordForId (deprecate?? ask @bmac)
  - [ ] findMany (private)
  - [ ] findHasMany (private)
  - [ ] findBelongsTo (private)
  - [ ] findAll (public)
  - [ ] didUpdateAll (private)
  - [ ] dataWasUpdated (private)
  - [ ] scheduleSave (private)
  - [ ] flushPendingSave (private)
  - [ ] didSaveRecord (private)
  - [ ] recordWasInvalid (private)
  - [ ] recordWasError (private)
  - [ ] updateId (private)
  - [ ] typeMapFor (private)
  - [ ] buildRecord (private)
  - [ ] dematerializeRecord (should be public, but is deprecated)
  - [ ] adapterFor (should be public - fivetanley)
  - [ ] serializerFor (should be public - fivetanley)
  - [ ] retrieveManagedInstance (should be private - fivetanley)

**Comment by gevious** [comment]
I'm going to give this one a go. PR will follow soon

**Comment by gevious** [comment]
buildRecord is actually named buildInternalModel. I've changed the yuidoc.

I've sent PR #3254

**Comment by runspired** [comment]
`recordForId` is pretty heavily relied on by most hacks I've seen trying to get around ED edge cases.  You can deprecate it because `peekRecord` is a direct substitute, but you'll likely need to keep `hasRecordForId` which I don't see mentioned here.

**Comment by Dan-Ste** [comment]
Anybody working on it?

**Comment by pete-the-pete** [comment]
Is this still open? @bmac commented on @gevious's PR saying we missed the window since 2.0 was released ([3254#issuecomment-147510113](https://github.com/emberjs/data/pull/3254#issuecomment-147510113))

**Comment by yogipatel** [comment]
Does this still need work?

**Comment by stefanpenner** [comment]
This seems to have gone stale
