### ISSUE TITLE
unknown injection: `service:store` in instance initailizer

### ISSUE THREAD

**Issue by amk221** [emberjs/data#3256]
This code in a fresh CLI app doesn't work in Ember-data v1.0.0-beta.19, whereas it did in .18
http://jsfiddle.net/amk221/r4L4q0h4/

**Comment by sly7-7** [comment]
@amk221 Would it be possible to debug here ? https://github.com/emberjs/data/blob/master/packages/ember-data/lib/instance-initializers/initialize-store-service.js#L28 Is this app initializer called ?

**Comment by amk221** [comment]
Never gets there

**Comment by martndemus** [comment]
you need a `after: 'ember-data'` on the initializer.

**Comment by amk221** [comment]
aww man. Thanks
[what changed?]

**Comment by martndemus** [comment]
Ember data started using instance initializers. 
Before ember data was still initialised in an app initializer, which are run before instance initializers.

Assume that initialisers of the same time run at random order unless you use before/after declarations.

**Comment by sly7-7** [comment]
@martndemus explanations in the code:
https://github.com/emberjs/data/commit/c1324d7de18e6c46684987c8587a342bb8eddea1

**Comment by amk221** [comment]
Ok thanks. But I don't really want to have to dig through Ember data's code base each time I upgrade.

I would have been nice to learn this from the changelog or the Ember blog post

**Comment by martndemus** [comment]
@amk221 see http://emberjs.com/deprecations/v1.x/#toc_access-to-instances-in-initializers

**Comment by amk221** [comment]
Yes I've read that and I already use them. But there was no notice in the ember-data change.
Just saying. Want to avoid making issues all the time.

**Comment by martndemus** [comment]
Sorry I removed my previous comment, because after submitting it I immediately realised it was stupid. But for readers it was:
> See: http://emberjs.com/deprecations/v1.x/#toc_access-to-instances-in-initializers

**Comment by sly7-7** [comment]
@amk221 I think the core team tries as much as possible to avoid breaking changes, and when it's not possible, they usually refer it, maybe this use case hast just been forgotten.

cc/ @bmac @fivetanley I quicky put something in the post blog: https://github.com/emberjs/website/pull/2194

@amk221 Would you understand that ?

**Comment by amk221** [comment]
Of course!

**Comment by sly7-7** [comment]
No pb :), thanks for reporting :)

**Comment by fivetanley** [comment]
Probably worth adding to the changelog, but using `after: 'ember-data'` is the way we should be recommending things like this in the guides. Otherwise there's no way to guarantee ordering.

**Comment by bmac** [comment]
Thanks for reporting this issue @amk221. I agree with you that this should be added to the change log and website. I'm going to leave this issue open until that happens.

**Comment by bmac** [comment]
The release bog post has been updated to mention this change: http://emberjs.com/blog/2015/06/05/ember-data-1-0-beta-19-released.html#toc_services-depending-on-the-store

**Comment by amk221** [comment]
:+1:

**Comment by sly7-7** [comment]
This evening, I will try to find a place in the docs to mention the `after: 'ember-data'`
