### ISSUE TITLE
PUT vs PATCH in ActiveModelAdapter

### ISSUE THREAD

**Issue by Fryie** [emberjs/data#3259]
Apologies if this has been asked before (couldn't find anything specific), but what is the rationale for using PUT instead of PATCH in the ActiveModelAdapter for updateRecord?

As far as I understand, PATCH has been the preferred Rails verb for updates since 4.0. Is this due to backwards compatibility? If so, would it be possible to add some configuration setting in order to specify the use of PATCH instead of PUT? Of course it should be possible to just extend the adapter and override the method, but then one has to duplicate the whole method.

**Comment by btecu** [comment]
`PATCH` is not available in `IE8`.
Also, unlike `PUT`, `HTTP/1.1` did not define the `PATCH` method.

**Comment by Fryie** [comment]
Sometimes I forget I'm dealing with browsers... Yes, I guess that would make sense. In that case I'll just have to move over to PUT. Thanks for the info.
