### ISSUE TITLE
Error thrown when using EmbeddedRecordsMixin since beta.19

### ISSUE THREAD

**Issue by jcbvm** [emberjs/data#3260]
I get an error when trying to save a record with an embedded belongsTo relationship.
The error is thrown at `typeForRelationship` where the second parameter `store` seems to be `undefined`.

I created a JSBin:
http://emberjs.jsbin.com/degezazozi/1/edit?html,js,output

**Comment by bmac** [comment]
Looks like inverseFor is expecting `store` to be passed to it here which is resulting in this error: https://github.com/emberjs/data/blob/4f0176fa0d3caed29389a462c4a244ef673ffea0/packages/ember-data/lib/serializers/embedded-records-mixin.js#L349

@jcbvm would you be interested in submitting a pr with a test to fix this issue?

**Comment by jcbvm** [comment]
@bmac Will see if I can create some time to create a PR.

**Comment by igorT** [comment]
cc @fivetanley and @wecc

**Comment by bmac** [comment]
@jcbvm We have release Ember Data v1.0.0-beta19.1 with a fix for this issue: http://emberjs.com/blog/2015/06/09/ember-data-1-0-beta-19-1-released.html

**Comment by jcbvm** [comment]
Really nice thank you!
