### ISSUE TITLE
Implement queryRecord

### ISSUE THREAD

**Issue by bmac** [emberjs/data#3261]
@thaume Any chance you have time to implement this one?

```js
  /**
   `queryRecord` asks the adapter to fetch a single record using a query object.

   This method is asynchronous.

   @method queryRecord
   @param {String} type
   @param {Object} query
   @param {Object} options
   @return {DS.PromiseObject} record
   */
  queryRecord: function(type, query, options),
```

**Comment by HeroicEric** [comment]
If this is going to be added, would it be more consistent to have `store.query` be named `store.queryAll`?

**Comment by HeroicEric** [comment]
If this is going to be added, would it be more consistent to have `store.query` be named `store.queryAll`?

**Comment by thaume** [comment]
@bmac I'm working on it over here https://github.com/emberjs/data/pull/2584/files

**Comment by bmac** [comment]
There was some talk about using `queryAll` for consistency with the `findAll` and `peekAll` however it was decided to stay with `query` because the records returned from the server by a `query` are likely a subset of all the record.

**Comment by bmac** [comment]
Closed by https://github.com/emberjs/data/pull/2584
