### ISSUE TITLE
Testing REST serializer in v1.0.0-beta.19

### ISSUE THREAD

**Issue by amk221** [emberjs/data#3266]
I had this in my test suite:

    var serializer = this.subject();
    var payload = ..etc..
    var store = this.container.lookup('store:application');
    var Party = store.modelFor('party');
    var result = serializer.extractSingle(store, Party, payload);
    assert.deepEqual...

After upgrading from beta.18 it fails with "Cannot read property 'modelFor' of undefined". I think [here](https://github.com/emberjs/data/blob/4f0176fa0d3caed29389a462c4a244ef673ffea0/packages/ember-data/lib/serializers/embedded-records-mixin.js#L125)

I don't know what it means or if I should be concerned, but thought I'd report it anyway

**Comment by igorT** [comment]
Can you test latest master? I believe this should be fixed

**Comment by amk221** [comment]
![screen shot 2015-06-09 at 11 42 19](https://cloud.githubusercontent.com/assets/382061/8056068/9f66127e-0e9c-11e5-9daa-297553460523.png)

**Comment by igorT** [comment]
Can you try and reproduce the issue in a jsbin or a test please?

**Comment by amk221** [comment]
beta.18 broken: http://jsfiddle.net/amk221/6g3rc8z2/
beta.19 fixed: http://jsfiddle.net/amk221/6g3rc8z2/

So, not sure why its failing for me. Will have a dig

**Comment by fivetanley** [comment]
Passes on canary so I'm closing. If you find it to be a bug in Ember Data please re-open.
