### ISSUE TITLE
Deprecate pushing real models in relationships into store.push

### ISSUE THREAD

**Issue by igorT** [emberjs/data#3271]
https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/store.js#L2059

this should deprecate

**Comment by fivetanley** [comment]
This seems like a useful feature. What is the cost of supporting it?

**Comment by igorT** [comment]
Its not in json api

**Comment by igorT** [comment]
We could add a workaround if people really want it, but would want to wait
and see

**Comment by fivetanley** [comment]
Oh wait, this is store.push. I agree. `store.createRecord` is the hook I use the most, if we support it there I'm happy. It's not a JSONApi hook per-se either.

**Comment by igorT** [comment]
Yes this is for push, not creating. This is much more useful when creating
