### ISSUE TITLE
Consider whether store.push/pushPayload should copy

### ISSUE THREAD

**Issue by igorT** [emberjs/data#3275]

**Comment by aldhsu** [comment]
Not sure if this is a related issue. I think it would make sense if `store.pushPayload` returned the models pushed into the store.

At the moment on master 
[link](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/store.js#L1910-#L1926) there is no return statement and `store.pushPayload` returns undefined. 

![screen shot 2015-06-18 at 5 02 27 pm](https://cloud.githubusercontent.com/assets/6347283/8225766/d6f233bc-15db-11e5-8419-040b3bf23250.png)

Contrast to `store.push`, [link]((https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/store.js#L1779-#l1801), where the model pushed in is returned. 
![screen shot 2015-06-18 at 5 03 14 pm](https://cloud.githubusercontent.com/assets/6347283/8225782/f24bd6e0-15db-11e5-92d7-13734e392d19.png)

**Comment by wecc** [comment]
@aldhsu There's a feature named `ds-pushpayload-return` that enables `pushPayload` to return the result.

**Comment by pangratz** [comment]
@aldhsu also see [RFC #161](https://github.com/emberjs/rfcs/pull/161)

**Comment by aldhsu** [comment]
@wecc @pangratz ok thanks!

**Comment by runspired** [comment]
We could probably do this in `dev` for safety but seems like unnecessary work overall.

**Comment by runspired** [comment]
as I've thought on this more, this is a Cache detail. Currently the cache does not retain this object (it copies, though by artifact and not design as it deconstructs resources into more granular caches) so it doesn't matter, if a Cache did retain this object it would likely want to deep-freeze it in dev as opposed to copying.
