### ISSUE TITLE
Version string of 19.1 is just 19 in console.

### ISSUE THREAD

**Issue by martndemus** [emberjs/data#3288]
I get `DEBUG: Ember Data : 1.0.0-beta.19` while verified using 19.1.

**Comment by igorT** [comment]
cc @fivetanley

**Comment by fivetanley** [comment]
Can you run `rm -rf node_modules && rm -rf bower_components && npm cache clean && bower cache clean && npm i && bower i` ?

The file seems to be correct in bower. https://github.com/components/ember-data/blob/v1.0.0-beta.19.1/ember-data.js#L4543

**Comment by martndemus** [comment]
Yep that fixed it.
