### ISSUE TITLE
Observers on model properties no longer working with beta 19

### ISSUE THREAD

**Issue by jcope2013** [emberjs/data#3293]
the behavior with beta 18 and before, the observer runs when the initial records get loaded into the store, the bullet points will show the prettyTitle computed property

http://emberjs.jsbin.com/cozibezica/1/edit?html,js,console,output

the behavior with beta 19, the observer no longer runs, the bullet points will all be empty

http://emberjs.jsbin.com/ragihibuza/1/edit?html,js,console,output

**Comment by igorT** [comment]
Adding an `.on('init')` to the observer makes them run. Similar to all Ember observers, the actual property needs to be accessed at least once in order for the observer to fire.
