### ISSUE TITLE
Don't unload records that are confirmed deleted

### ISSUE THREAD

**Issue by igorT** [emberjs/data#3295]
Context/previous discussion: When the store confirms a deleteRecord we now automatically unload a record. Previous discussion with Tom and Yehuda has indicated that we should not do this automatically, and should let the user opt in via a hook or something into unloading records. Is this a thing we want to do. We must change the default this week for Backcompat, but can come up with a hook later. This just means that by default deleting will not unload a record and that if you delete a bunch of things, you might get memory leaks(this might be fine though, i am not sure many apps delete do this).

**Comment by bmac** [comment]
This issue was discussed during the Ember Data meeting today and it was decided that Ember Data should keep the current behavior of unloading deleted records after the adapter confirms the record has been deleted on the backend.

**Comment by fivetanley** [comment]
Talking with Tom I think we want:

- `destroyRecord` unloads the record because it acknowledges from the server
- `deleteRecord` does not go to the server, and does not unload the record.

**Comment by fivetanley** [comment]
srry for late response, wrote during yesterday's meeting and didn't post apparently

**Comment by igorT** [comment]
deny, neither of them unload, until we receive a confirmed delete, in which case both unload
