### ISSUE TITLE
Unload issue with relationships

### ISSUE THREAD

**Issue by igorT** [emberjs/data#3296]
It is not clear what unloading should do with regards to relationships. It seems to me that it should dematerialize a record, but keep the internalModel intact if it has SSOT foreign key references(removing foreign keys seems obviously incorrect).
This is problematic though, because internalModels will still leak memory. How do we let users unload a bunch of related records? Does this mean we have to write a mini Garbage Collector, that will anytime you unload a record, check the foreign key dependencies and unload things it can. This doesn't sound too bad, can you confirm it is the right thing to do?

**Comment by wycats** [comment]
@igorT This seems acceptable. Do you mean something more than refcounting? Do you end up needing a cycle collector?

**Comment by igorT** [comment]
The algorithm needed to be implemented is:
1. `store.unloadRecord` only dematerializes the record (internalModel.dematerialize()) which destroys the DS.Model
2. We treat the record and relationships as a graph. Starting at the record do a breadth first search through the relationships, and see if you can reach a record that has not been dematerialized. If you can reach a live record, do nothing.
3. If the graph is fully dematerialized, go and unload(destroy internalModel, remove from identity map) all reachable records including the current one

**Comment by Kilowhisky** [comment]
I can't quite wrap my head around this issue but would a symptom of this problem be that unloaded records are still being returned from `store.findAll`?
