### ISSUE TITLE
Store.query/queryRecord url behavior

### ISSUE THREAD

**Issue by igorT** [emberjs/data#3297]
Currently if you do 
```js
store.queryRecord('user', {options})
``` 
those options are passed to the adapter, and inserted as query params. However a supper common use case is to want to trigger a request to
```
/users/current
```
However we have no semantic way of differentiating between query params and url options when they are passed in to the adapter.  Should we add namespacing to the options object passed in to the query?
We could do the same, with adapterOptions, pagination etc. However, currently all the other adapter methods take a snapshot(remember discussion at https://hackpad.com/RecordArray-Snapshot-JO55bGRbwsn), and will look up the adapterOptions from the snapshot. Should these as well? It is not clear to me that they should as we will never have local data for a query. If they are not

**Comment by thaume** [comment]
@igorT how can I help you with this issue ?

**Comment by fivetanley** [comment]
We ended up using `adapterOptions` to namespace options.
