### ISSUE TITLE
Change `isDirty` flag to something like `hasDirtyAttributes`

### ISSUE THREAD

**Issue by igorT** [emberjs/data#3299]
Same rationale as https://github.com/emberjs/data/issues/3273

**Comment by HeroicEric** [comment]
I went to work on this but I'm not sure how to deprecate `model.get('isDirty')`. Any guidance?

**Comment by sly7-7** [comment]
maybe implementing the unknownProperty method and throwing deprecation if the passed property is ìsDirty`?

**Comment by wecc** [comment]
Fixed by #3351
