### ISSUE TITLE
.get('currentState.stateName’) returning undefined when operating on has many record objects

### ISSUE THREAD

**Issue by jcope2013** [emberjs/data#3308]
```
invoice.get('lineItems').get('firstObject').get('currentState.stateName’); 
```

beta 18 - "root.loaded.saved"
beta 19 - undefined

in beta 19 i have to use private apis to make it work

```
invoice.get('lineItems').get('firstObject')._internalModel.currentState.stateName
```

simple example that logs out the state to the console

beta 18 - http://emberjs.jsbin.com/tomivoduto/1/edit
beta 19 - http://emberjs.jsbin.com/weyuwamulo/1/edit

**Comment by bmac** [comment]
@jcope2013 I just released `Ember Data beta-19.2` with a fix for this regression.
