### ISSUE TITLE
question about onLoad and when all relationships are ready

### ISSUE THREAD

**Issue by danielspaniel** [emberjs/data#3309]
Before this release, I could access relationships in and 'onLoad' callback

```js
  doThingsWhenLoaded: function() {
     // doing things when loaded
     this.get('relationship1')
  }.on('didLoad'),
```

now, it looks like the relationships are still there and all all setup, but in the _internalModel attribute. 

I think you are trying to wait for all relationships to load ( treat them as async ) before you allow them to be visible? ( guessing ) 
 I am nervous to use the _internalModel to access those relationships, so, would it be possible to setup a callback like 'didFinishLoadingEverythingAndYouAreGoodToGoBro'  or simple 'didFinishLoading' 
 
 know what I mean? 

 or maybe is there some better way ( different ) way to wait for the model ( and its relationships ) to be fully ready before I do some setup stuff?

**Comment by igorT** [comment]
Your questions is a really good one, and will be addressed shortly as part of our 1.0/2.0 push. Please wait a couple of days :)
