### ISSUE TITLE
Implement queryRecord hooks for new Serializers

### ISSUE THREAD

**Issue by igorT** [emberjs/data#3331]

**Comment by thaume** [comment]
Hey @wecc any tips on this one before I start a PR ? Thanks !

**Comment by wecc** [comment]
@thaume just remember to implement it for the new Serializer API too, as the `extractX` hooks will be deprecated. Should be something like `normalizeQueryRecordResponse`. Ping me on Slack if there's anything else I can help with!

**Comment by thaume** [comment]
@wecc Okay thanks ! I already made the old hook (`extractQueryRecord`) for making tests pass. I'll ping you on Slack if I hit a wall !

**Comment by thaume** [comment]
Work ongoing over here https://github.com/emberjs/data/pull/3338

**Comment by wecc** [comment]
#3338 has been merged, closing.

**Comment by dustinfarris** [comment]
@igorT how does this work when the response is an array?

**Comment by thaume** [comment]
@dustinfarris when the response is an array the first record of the array is picked, check the tests file you'll get a better idea

**Comment by thaume** [comment]
@dustinfarris it is also important to note that all the other records of the array are cached client side

**Comment by dustinfarris** [comment]
Thanks @thaume.  I'm having trouble understanding how that works.

In normalizeQueryRecordResponse, the payload is passed to normalizeSingleReponse which treats it as a single item.  How is the first item picked?

I'm asking because I maintain an adapter and we are having trouble figuring out what to override to normalize a paginated response when queryRecord is used.

**Comment by thaume** [comment]
@dustinfarris I think it happens here : https://github.com/emberjs/data/blob/master/packages/ember-data/lib/serializers/rest-serializer.js#L274

If the `documentHash.data` is empty the record is pushed in `documentHash.data` and if `documentHash.data` is already loaded, then the current record is pushed into `documentHash.included.data`.

The results of the operation is that the first record is returned but all the other records are cached through the `included` object.

**Comment by dustinfarris** [comment]
Thanks @thaume.  I think I've managed to sort out how to override this for our adapter in a simple way.  If you have a spare moment, could you take a look at this PR and let me know if I'm doing anything obviously wrong?  https://github.com/dustinfarris/ember-django-adapter/pull/130

**Comment by thaume** [comment]
I'm not sure to understand why you need to override the initial hook. It seems that what you do here https://github.com/dustinfarris/ember-django-adapter/blob/query-pagination/addon/serializers/drf.js#L134 is a simplified version of what happens in the rest serializer of ED.

**Comment by dustinfarris** [comment]
The data comes in as an array from our backend.  Without converting that array to a JSON API object, ED doesn't seem to be able to handle it.

ED cannot natively handle this response for queryRecord:

```json
[
  {"id": 1, "title": "My Post"},
  {"id": 2, "title": "My Other Post"}
]
```

ED cannot handle this either as far as I've been able to tell:

```json
{
  "data": [
    {"id": 1, "title": "My Post"},
    {"id": 2, "title": "My Other Post"}
  ]
}
```

This seems to work, and is what I am coercing to in the pull request:

```json
{
  "data": {"id": 1, "title": "My Post"},
  "included": [
    {"id": 2, "title": "My Other Post"}
  ]
}
```

**Comment by dustinfarris** [comment]
edited

**Comment by thaume** [comment]
Ok, could you open an issue in the Ember Data repo ? I'll look into it.

**Comment by thaume** [comment]
@dustinfarris I was just talking with @wecc and he made the remark that you extend the "JSONserializer" when you might want to extend the "RESTserialier".

The RESTserialiser does extend the JSONserializer and also adds a lot of useful behaviour like the one you're looking for (loading arrays for single records and sideloading). Let me know what you think.
