### ISSUE TITLE
Docs: store.find returns PromiseArray, but content shouldn't be used

### ISSUE THREAD

**Issue by MichaelVdheeren** [emberjs/data#3359]
In the PromiseArray documentation (http://emberjs.com/api/data/classes/DS.PromiseArray.html) it says that ```When the promise is resolved the resulting value will be set to the PromiseArray's content property.```

However, the content should not be fetched via a get. Instead the array itself should be used to when pushing objects in an array.

wrong way:
```
var array = []
this.store.find('post').then(function(posts) {
    array.addObjects(posts.get('content'));
});
```

correct way:
```
var array = []
this.store.find('post').then(function(posts) {
    array.addObjects(posts);
});
```

The documentation is somewhat conflicting about this.

**Comment by MichaelVdheeren** [comment]
In addition I found out that this is also somewhat conflicting if you use i.e. `forEach` on a `PromiseArray`.

You get the Class (which is correct) for each element, but if you want to add that to another array (fetched from the store) using `insertAt` you're mixin InternalModels and Class in the same array. This results in a getRecord() error when using that array in the template.

There is no alternative like addObject with index that would solve this.

**Comment by fivetanley** [comment]
This seems to be resolved in the latest API documentation.
