### ISSUE TITLE
PhantomJS global failure using query as parameter

### ISSUE THREAD

**Issue by cdoornink** [emberjs/data#3372]
I just updated to EmberData 1.13 and renamed all my methods to the new naming conventions.

Everything is working well except when I try to run tests with PhantomJS I am getting a global failure: `SyntaxError: Cannot declare a parameter named 'query' in strict mode`.

Seems like this has to be related to `findQuery` now being called `query` since I didn’t make any other changes, but its unclear where this is being triggered. The tests run just fine in a browser.

I also turned off `use strict` in my phantom configs and it still errors.

**Comment by igorT** [comment]
![image](https://cloud.githubusercontent.com/assets/715175/8220272/052608a2-151f-11e5-9c25-bcc2d41fa578.png)
