### ISSUE TITLE
Is there a deprecation guide for Ember Data v1.13.0?

### ISSUE THREAD

**Issue by sarus** [emberjs/data#3378]
Just upgraded to Ember Data v1.13.0 and I'm getting the following deprecations:

```
DEPRECATION: The default behavior of `shouldBackgroundReloadRecord` will change in Ember Data 2.0 to always return true. If you would like to preserve the current behavior please override `shouldBackgroundReloadRecord` in you adapter:application and return false.
        at Ember.Object.extend.shouldBackgroundReloadRecord (https://neontetra.breach/assets/vendor.js:88631:15)
        at ember$data$lib$system$store$$Service.extend._fetchOrResolveInternalModel (https://neontetra.breach/assets/vendor.js:99820:21)
        at ember$data$lib$system$store$$Service.extend._findByInternalModel (https://neontetra.breach/assets/vendor.js:99789:41)
        at ember$data$lib$system$store$$Service.extend.findRecord (https://neontetra.breach/assets/vendor.js:99779:21)
        at ember$data$lib$system$store$$Service.extend.find (https://neontetra.breach/assets/vendor.js:99675:21)
```

and

```
DEPRECATION: Your custom serializer uses the old version of the Serializer API, with `extract` hooks. Please upgrade your serializers to the new Serializer API using `normalizeResponse` hooks instead.
        at ember$data$lib$system$store$serializer$response$$normalizeResponseHelper (https://neontetra.breach/assets/vendor.js:93888:15)
        at https://neontetra.breach/assets/vendor.js:95517:25
        at Object.Backburner.run (https://neontetra.breach/assets/vendor.js:10776:25)
```

Is there a guide (available now or planned) to help with resolving these deprecations? For example my custom serializers currently override `keyForAttribute` and `serializeAttribute` but I don't know if these are part of the `extract` hooks mentioned in the deprecation (I assume they must be, hence the deprecation but previously I've had addons or things like ember inspector throw deprecations and often the deprecation stacktrace doesn't point back to my application code but stops somewhere deep within ember core or debug)

Something similar to the core ember deprecation guide found here which has been immensely useful in resolving ember deprecations (http://emberjs.com/deprecations/v1.x/).  

Thank you!

(Sorry if this exists and my google fu is just weak)

**Comment by adam-knights** [comment]
+1 for this, my RESTSerializer is simply

    export default DS.RESTSerializer.extend({
      serializeIntoHash: function (hash, type, record, options) {
        Ember.merge(hash, this.serialize(record, options));
      }
    });

But I have no idea whether this deprecation effects me or the action to take to resolve it. Would be alot better if the deprecations linked to urls with code examples that would help remove the deprecations, like Ember does.

**Comment by ixtli** [comment]
I found this little bit: https://github.com/emberjs/data/blob/v1.13/packages/ember-data/lib/system/serializer.js#L28 Also the docs on the site are broken because they all link to github blob/v1.13.1/ but that tag doesn't exist.

**Comment by turtleguyy** [comment]
+1

Especially in regards to this `Serializer extract hooks` nonsense. I've tried everything short of ritual sacrifice to get rid of this deprecation notice, with no luck.

**Comment by wecc** [comment]
A guide explaining the transition in detail is in the making and it's a bummer it has taken so long :disappointed:  The ED 1.13 blog post alone took way longer than we anticipated but there was simply so much new stuff to cover.

The major steps needed to transition to the new Serializer API are outlined in the 1.13 blog post:
http://emberjs.com/blog/2015/06/18/ember-data-1-13-released.html#toc_transition-to-the-new-jsonserializer-and-restserializer-apis

Please feel free to ping me on the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/) and I'll be happy to help you out in the meantime.

**Comment by Keeo** [comment]
+1

**Comment by fuse-mars** [comment]
+1

**Comment by turtleguyy** [comment]
Like he said, definitely check out the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/). The thing is a wealth of info and goodness for all things Ember.

/cc @Keeo @fuse-mars

**Comment by workmanw** [comment]
The downside of the slack is conversations only last a few days before reaching their 10K threshold. It's a shame that there is a lot of potential answers to questions that aren't viewable / searchable.

**Comment by bmac** [comment]
The Ember Data 1.13 blogpost is the best resource for learning how to deal with the deprecations in 1.13. http://emberjs.com/blog/2015/06/18/ember-data-1-13-released.html#toc_transition-to-the-new-jsonserializer-and-restserializer-apis

**Comment by jreading** [comment]
If anyone still hasn't migrated and has the `extract` hooks warning in 1.13. just set the isNewSerializerAPI to true.

```js

var ApplicationSerializer = DS.RESTSerializer.extend({
    isNewSerializerAPI: true,
...
```

Worked for me.
