### ISSUE TITLE
Support DS.Store#findAll(DS.Model)

### ISSUE THREAD

**Issue by pangratz** [emberjs/data#338]
As asked in http://stackoverflow.com/q/11590906/65542, it would be nice if one could do a `findAll` on a common record type. For example:

``` javascript
App.Model = DS.Model.extend({title: DS.attr('string')});
App.Foo = App.Model.extend();
App.Bar = App.Model.extend();

App.store.load(App.Foo, {id: 1, title: 'foo'});
App.store.load(App.Bar, {id: 2, title: 'bar'});

var records = App.store.findAll(App.Model);
```

 Is this intended to be supported and if not, is there a workaround for this?

**Comment by RomanPerin** [comment]
Hi!
I'm interested in such functionality.
Is it supported now? It seems to me that it was removed..
If it so.., may be there is another way to implement such behavior?

**Comment by igorT** [comment]
Yes, we want this, the main challenge is to have a clear api as to when you want this behavior and when not
