### ISSUE TITLE
Embedded records mixin triggers store.push(type, data) deprecation

### ISSUE THREAD

**Issue by ixtli** [emberjs/data#3382]
When using embedded records mixin with a `hasMany` relationship, this line https://github.com/emberjs/data/blob/master/packages/ember-data/lib/serializers/embedded-records-mixin.js#L450 triggers this deprecation: ```DEPRECATION: store.push(type, data) has been deprecated. Please provide a JSON-API document object as the first and only argument to store.push.``` which is located at https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/store.js#L1789

**Comment by igorT** [comment]
This is on purpose, we will be publishing an upgrade guide in a few days
