### ISSUE TITLE
Link warning can be noisy

### ISSUE THREAD

**Issue by bmac** [emberjs/data#3393]
I have a JSON-API backend that returns both links and ids in its response payload. This results in a bunch of warnings in my console.

![screen shot 2015-06-19 at 11 35 47 am](https://cloud.githubusercontent.com/assets/54056/8256981/881839c4-1678-11e5-8168-6208d67e35f5.png)

Maybe Ember Data could include an environmental flag to disable this warning here:

https://github.com/emberjs/data/blob/0a4aba5642355ad82e3a2be81b5f646f7fa003eb/packages/ember-data/lib/system/relationships/state/relationship.js#L199

**Comment by igorT** [comment]
I think we should change the warning to only warn if you push links but not ids

**Comment by wecc** [comment]
This should be fixed by #4599
