### ISSUE TITLE
meta not available in 1.13.3

### ISSUE THREAD

**Issue by raytiley** [emberjs/data#3401]
The `meta` object that usually gets passed through from `query` calls is an empty object on 1.13.3. This essentially has broken all the pagination in my app. I see there was a recent fix on `master` regarding meta: https://github.com/emberjs/data/pull/3398, but I can't tell if it just applies to the new JSONAPI sterilization stuff or not.

**Comment by rounders** [comment]
I can also confirm that pagination on my app no longer works since upgrading to 1.13.3.

**Comment by wecc** [comment]
`store.metadataFor` and `queryResults.get('meta')` is broken in 1.13.3 if you're using the new Serializer API. The new Serializer API is active when you 1.) are using default uncustomized serializers, 2) by setting `isNewSerializerAPI` or 3) if you're using the new JSON-API adapter/serializer.

#3398 solves this for all serializers, not only the JSON-API one. [This JSBin](http://emberjs.jsbin.com/selode/edit?html,js,output) works with canary but not with release.

**Comment by wecc** [comment]
@raytiley @rounders can you confirm if 1.13.4 works better?

**Comment by rounders** [comment]
@wecc working well for me in 1.13.4 :heart: Thanks!

**Comment by wecc** [comment]
:tada:
