### ISSUE TITLE
store.push always expects a json-api formatted payload

### ISSUE THREAD

**Issue by bcardarella** [emberjs/data#3405]
With `store.pushPayload` going away in favor of `store.push` the current code bombs out when the incoming payload doesn't have the expected meta data.

**Comment by intuitivepixel** [comment]
Yeah the refactor of `store.push` will be a pain in the a** for most production apps

**Comment by bcardarella** [comment]
It probably should be treated as a bug if 1.13 was intended to work with existing applications. The push towards json-api as default is good but premature for the 1.x branch IMO.

If the expectation is to force all normalization towards the json-api spec that is OK. We just need more of a heads up about this.

**Comment by igorT** [comment]
`store.pushPayload` isn't going away. 
`store.push` in 1.13 supports the old format, and we will be making an Ember.Watson helper to automatically convert all your test push formats, and also exposing helpers for the old formats.

**Comment by wecc** [comment]
1.13 supports both `store.push(modelName, payload)` (with deprecations) and `store.push(payload)` when that `payload` is JSON-API.

Apps using `store.push(modelName, payload)` can transition to the new Serializer API and do `store.push(store.normalize(modelName, payload))` to get rid of the deprecations.

`store.pushPayload(modelName, payload)` will continue to work as is.
