### ISSUE TITLE
createRecord response with sideloaded hasMany records doesn't populate store with those records

### ISSUE THREAD

**Issue by samcic** [emberjs/data#3406]
JSBin:

http://emberjs.jsbin.com/hovisewafa/edit?html,js,console,output

In short: let's say I have a Parent model which has many Child records (async false, because I want to do sideloading). If I do a 'find' on the store for a parent and the adapter returns some sideloaded Child records, then all is fine (the template iterates through the children, rendering the ids).

If I instead do a store.createRecord('parent') and then a save() and tell the adapter's createRecord method to return those same sideloaded Child records, I get an error ("Uncaught Error: Assertion Failed: You looked up the 'childs' relationship on a 'parent' with id 2 but some of the associated records were not loaded."). A check of the store after the adapter response seems to show that no child records were loaded into the store.

In the JSBin you can swap the code in the index route's model hook to see it working for the 'find' case.

In my 'real' app my tests are using jQuery Mockjax to stub the server POST call, so I hope I've done it correctly in the JSBin with overriding the createRecord method to simulate this.

Sorry if I've missed something here (I'm relatively new)...perhaps this is by design and it's not "best practice" to have a server return sideloaded records on a POST response? I'd be happy to explain our use case if there's any interest in it.

**Comment by steffenbrem** [comment]
Aren't the internals of Ember Data changed, I see you are using ember data canary. I am not sure if you have to side load it like that.

**Comment by samcic** [comment]
Thanks @steffenbrem . I changed to the latest 'release' version of ember data from the Ember builds page. Seems to be working as expected now. Updated jsbin:

http://emberjs.jsbin.com/lerumasumi/edit?html,js,console,output

I'm happy to close this now. Sorry for the hassle :(.

**Comment by steffenbrem** [comment]
@wecc Is there any documentation on how to sideload with the new serializer api stuff? He is using the `RESTSerializer` and the previous way of sideloading does not work anymore with the canary. It would be helpful if somewhere it is documented on how to do it in the latest ember data.

**Comment by wecc** [comment]
This is a bug with the new Serializer API. We're currently not pushing sideloaded records to the store when saving.

See http://emberjs.jsbin.com/mebupo/edit?html,js,output

**Comment by steffenbrem** [comment]
@wecc Is this postponed because of the issue that when you have a non-identified local record in your store (so without an ID) and you then get an identified record back from the server, you will end up with duplicated records (#1829)?

**Comment by wecc** [comment]
@steffenbrem No, this is because previously the serializer pushed sideloaded records to the store but with the new Serializer API sideloaded records are returned in the JSON-API Document in `included`. However, the store does not currently do anything with `included`.
