### ISSUE TITLE
Enhancement - consider adding version number in the header.

### ISSUE THREAD

**Issue by stefek99** [emberjs/data#3407]
Because other files from Ember family have a header.

And it is easier to find a version by just opening a file, rather than looking for:
```
 var ember$data$lib$core$$DS = Ember.Namespace.create({
      VERSION: '1.13.3'
    });
```

![builds_emberjs_com_tags_v1_13_3_ember-data_js_and_builds_emberjs_com_tags_v1_13_2_ember_debug_js](https://cloud.githubusercontent.com/assets/249703/8273071/82bc905e-1855-11e5-89c7-91c65de9a6e8.png)

**Comment by wecc** [comment]
I'm closing this in favor of #2753.

**Comment by bmac** [comment]
@stefek99 I'd just like to say in case this wasn't clear wasn't clear. This a great idea and something the Ember Data team very much intends to do.

**Comment by wecc** [comment]
Sorry if I came off a bit short, really appreciate that you brought this to our attention. We definitely want to fix this!

**Comment by stefek99** [comment]
Yeah sure. 

The other item - #2753 - is more generic.
