### ISSUE TITLE
Possible to query the server with an extra parameter on async hasMany relation?

### ISSUE THREAD

**Issue by harianus** [emberjs/data#3412]
In our app we have a model for `user` and for `project`. Both of them can have the `setting` `hasMany` relation. The server has to know if it is for a `user` or for a `project` (does it need valid auth or not).

Is it possible to query the server with something like `settings?ids[]=1&ids[]=2&project=true`?

Maybe this is a feature request?

```js
// models/project.js
import DS from 'ember-data';
export
default DS.Model.extend({
  settings: DS.hasMany('setting', {
    async: true,
    project: true
  }),
  ...
});
```

```js
// models/user.js
import DS from 'ember-data';
export
default DS.Model.extend({
  settings: DS.hasMany('setting', {
    async: true,
    user: true
  }),
  ...
});
```

Or can it be done differently?

**Comment by steffenbrem** [comment]
@harianus I think I would do it like this: You can a specific adapter for your model, you will have two adapters, `adapters/project.js` and `adapters/user.js`. Then you override the `findMany` method (see: http://emberjs.com/api/data/classes/DS.Adapter.html#method_findMany).

**Comment by harianus** [comment]
If you overwrite the `findMany` method in `adapters/project.js` is does not get triggered because it should be `adapters/setting.js`, but in `adapters/setting.js` you don't know if it was the `project` or the `user`.

**Comment by pangratz** [comment]
Sorry for the overdue response @harianus 😔  Currently it is not possible to query a `hasMany` relationship with additional parameters in core `ember-data`. I don't know if you have seen this but the [ember-data-has-many-query](https://github.com/mdehoog/ember-data-has-many-query) should help you here in the meantime.

I am triaging issues and I am closing this in favor of #3700. Please chime in over there if you have any news regarding workarounds or thoughts. Thanks!

**Comment by harianus** [comment]
Don't need the solution now and it is a little too long ago to find out how we solved this. Thanks for the response anyway 😉
