### ISSUE TITLE
Issue with polymorphic type on 1.13

### ISSUE THREAD

**Issue by jcope2013** [emberjs/data#3414]
i have an object that looks like this returned from the response, it is sideloaded

```

patient_plans: [{
id: 3, 
member_id: "43", 
first_name: "test",
created_at: "2015-06-22T10:28:11.084-04:00"
date_of_birth: "2015-02-25"
type: "RegularPatientPlan"
updated_at: "2015-06-22T10:28:11.084-04:00"
}]

```

but when it comes into the store push method

```
{
    data: {
    attributes: Object
    id: "3"
    relationships: Object
    type: "patient-plan"
    }
}
```

the type doesnt seem to be getting coerced correctly and there doesnt seem to be a place i can grab the type off attributes either as i would expect it to be type regular-patient-plan

i am on canary and using new serializer api, for reference this was working up until 1.13 

also mentioned here https://github.com/emberjs/data/issues/2749 @jackmatt2 you get it working?

**Comment by bmac** [comment]
ping @wecc, looks like a polymorphic case that the new serializer isn't handling correctly.

**Comment by wecc** [comment]
@jcope2013 This is unfortunately not supported. You would have to put that record in the `regular_patient_plans` root key of your payload.

With the introduction of references (InternalModel) and JSON-API as the internal format, we have taken some very important steps towards supporting this but we're not quite there yet, sorry.

**Comment by bmac** [comment]
Hey @jcope2013. Thanks for opening this issue. Would you be able to do me a favor and put together a jsbin demonstrating the issue? Here is one to get you started: http://emberjs.jsbin.com/leseho/edit 

I'm interested to see how it worked before `1.13` because the polymorphic case can sometimes be pretty unintuitive without the surrounding context.

Thanks

**Comment by jackmatt2** [comment]
@jcope2013 I had this working with a custom store, but that no longer works in the most recent version of ember-data.  Still don't have a solution.

**Comment by jackmatt2** [comment]
igorT said this is not possible on my issue but I can't see how.

**Comment by jcope2013** [comment]
@bmac here is two examples, basically the issue comes down to now in the store push method when type.data comes in, you only have access to the 'patient-plan'  original type and cant also look at the records polymorphic type under the attributes hash, previously with the betas before 1.13 you could access the polymorphic type by looking at data.type and look at the original type by looking at the type argument

beta 19.1

http://emberjs.jsbin.com/kotudenera/1/edit?html,css,js,output

1.13/canary

http://emberjs.jsbin.com/wamojozilu/edit?html,css,js,output

i might now be able to get away with sticking an explicit type: DS.attr('string') on the polymorphic root model so i can access it inside the store.push and manipulate it accordingly

**Comment by jackmatt2** [comment]
@jcope2013 yeah that was the same issue I was having when I was looking at this issue, I was no longer able to access the "type" key from the json payload because it was not an attribute of the model.  Can you post your custom store when/if you get this working?

**Comment by jcope2013** [comment]
@jackmatt2 this seems to be working with my testing so far, you might be able to get rid of the second else, its legacy at this point and i have a length check which will prolly not be needed after https://github.com/emberjs/data/issues/3425 gets fixed, just stick type: DS.attr('string') on the root model that the polymorphic ones extend from 

```
export default DS.Store.extend({
 push : function(type, data) {
    var dataType, modelType, oldRecord, oldType;
    if(type.data)
    {
      if(Ember.isArray(type.data) && type.data.length === 0)
      {
        return this._super(type, data);
      }
      else
      {
        modelType = oldType = type.data.type;

        if(type.data.attributes.type)
        {
          dataType = type.data.attributes.type.dasherize(); 
        }

        if(dataType && (this.modelFor(oldType) !== this.modelFor(dataType))) {
          type.data.type = dataType;

          if(oldRecord = this.peekRecord(oldType, type.data.id)) {
            this.unloadRecord(oldRecord);
          }

        }

        return this._super(type, data);
      }
    }
    else
    {
      modelType = oldType = type;
      if(data)
      {
        dataType = data.type; //The type parameter is required in the payload with the subclass name
      }

      if(dataType && (this.modelFor(oldType) !== this.modelFor(dataType))) {
        modelType = dataType;

        if(oldRecord = this.peekRecord(oldType, data.id)) {
          this.unloadRecord(oldRecord);
        }

      }

      return this._super(modelType, data);
    }
  }
});
```

**Comment by jackmatt2** [comment]
@jcope2013 great thanks, I will give it a try.

**Comment by jackmatt2** [comment]
@jcope2013 working again cheers.
