### ISSUE TITLE
ToString not showing model id

### ISSUE THREAD

**Issue by snwfog** [emberjs/data#3415]
![screen shot 2015-06-22 at 11 41 43 am](https://cloud.githubusercontent.com/assets/682969/8285790/b1d78762-18d3-11e5-8e70-e1218b5eb96e.png)

I am stepping inside of a resolved promise; the model has id, but the toString method is not showing id. Is this intended? Am I suppose to reload my model?

**Comment by stefanpenner** [comment]
I suspect something coerced the model into a string early, causing the toString to cache before the `id` was known.

**Comment by snwfog** [comment]
@stefanpenner yea, `core_object#toString` does it.

**Comment by pangratz** [comment]
@snwfog I tried to reproduce this but had no look. Can you take a look at [this ember-twiddle](https://ember-twiddle.com/3b1feb13e8850814934fc275cdb88219?fileTreeShown=false&numColumns=2&openFiles=routes.application.js%2Ctemplates.application.hbs) and check what needs to be changed so it demonstrates the issue? Or can you confirm that this has been solved in the meantime? Thanks!

**Comment by snwfog** [comment]
Resolved. Thanks for looking into this.
