### ISSUE TITLE
JSON:API data with underscored parameters - how to make it work?

### ISSUE THREAD

**Issue by kottenator** [emberjs/data#3416]
Hi!

I didn't find the answer so here is my question: can `JSONAPISerializer` automatically convert underscored keys to camelized and vice verse?

I use `ember-data#canary` (commit _4c5fcf6_)

I have JSON API v1.0 structure like this:

```json
{
    "data": {
        "type": "user",
        "id": "1435d80609114121bf7a0ada912e739d",
        "attributes": {
            "full_name": "Helene Holloway",
            "email": "helene.holloway@uniworld.org"
        }
}
```

And I have `app/models/user.js`:

```js
import DS from 'ember-data';

export default DS.Model.extend({
    fullName: DS.attr('string'),
    email: DS.attr('string'),
});
```

When I use `JSONAPISerializer`, it gets `email` but skips `fullName` field. 

As I understand, you have `ActiveModelSerializer` to handle this, but it's inherited from `RESTSerializer`, not `JSONAPISerializer`...

Or maybe I'm missing something and this feature is easy to enable for `JSONAPISerializer`?

**Comment by kottenator** [comment]
I see that you do `dasherize(key)` for attributes and relations. What I need is to do `decamelize(key)` instead... So I need to override two methods:

```js
// app/serializers/application.js
export default DS.JSONAPISerializer.extend({
    keyForAttribute: function(key) {
        return Ember.String.decamelize(key);
    },

    keyForRelationship: function(key) {
        return Ember.String.decamelize(key);
    }
});
```

Is it the correct and official solution? :)

**Comment by snwfog** [comment]
@kottenator `json-api` don't seems to restrict the key to be dasherized or underscored (their examples are dasherized for example: [here](http://jsonapi.org/format/#document-resource-identifier-objects). Whereas `activemodel` does specify that the key should be underscored.

**Comment by bmac** [comment]
@kottenator The application serializer in you example is the correct and official solution. 

Although JSON API does not require the attributes and relationships be dasherized the `JSONAPISerializer` that Ember Data ships with assumes the attributes/relationships are dasherized to be consistent with the examples on http://jsonapi.org/format and the popular https://github.com/cerebris/jsonapi-resources implementation of the JSON API spec.

**Comment by kottenator** [comment]
Sure, I'm not telling that it's a part of JSON:API, I'm just asking - what is the correct way to handle my problem? 

**Q1:** is it correct and safe way - to override those two methods? Is it enough?
**Q2:** maybe it's reasonable for you to implement some configuration option for `JSONAPISerializer`, like:

```js
// app/serializers/application.js
export default DS.JSONAPISerializer.extend({
    keyNaming: "underscored" // "camelized", "dashed", undefined
});
```

Maybe it's reasonable

**Comment by wecc** [comment]
The nice thing about `keyForAttribute` and `keyForRelationship` is that they give you full control how you want your keys. A solution with `keyNaming` would be limited to whatever methods are implemented in ED.

**Comment by kottenator** [comment]
Yes, I agree with you that there should be maximum flexibility. But there should be also reasonable defaults.

In my proposal there is `undefined` choice which could be default one (to pass attributes as-is)

But I believe that usually developers support consistent _underscored_, _camelized_ or _dashed_ naming convention and don't use _mixed_ naming. So it'd be good to specify just one config option rather than to override two methods.

**Comment by bmac** [comment]
@kottenator I think this is a great idea for an addon.
