### ISSUE TITLE
JSON:API serializer: normalizeHash doesn't work

### ISSUE THREAD

**Issue by kottenator** [emberjs/data#3417]
It seems that `normalizeHash` doesn't work in `JSONAPISerializer`

I use `ember-data#canary` (commit 4c5fcf6)

Here is my example: 

```json
// JSON API data
{
    "data": [
        {
            "type": "member",
            "id": "176a71f3397643e08a4bfd25ba75f41b",
            "relationships": {
                "user": {
                    "data": {
                        "type": "user",
                        "id": "1e4b1262b98740ddade68f7a61e6730e"
                    },
                    "meta": {
                        "title": "Selena Whitaker",
                        "email": "selena.whitaker@veraq.io"
                    }
                }
            }
        }
    ]
}
```

```js
// app/models/member.js
import DS from 'ember-data';

export default DS.Model.extend({
    fullName: DS.attr('string'),
    email: DS.attr('string')
});

```

```js
// app/serializers/application.js
import DS from 'ember-data';

export default DS.JSONAPISerializer.extend({
    normalizeHash: {
        member(hash) {
            hash.fullName = hash.relationships.user.meta.title;
            hash.email = hash.relationships.user.meta.email;
            return hash;
        }
    }
});
```

In this example, `normalizeHash.member(...)` isn't triggered (but it works in `RESTSerializer`). Shouldn't it work in `JSONAPISerializer`?

I could override `normalize(...)` method and manually call `normalizeHash.member(...)` but it doesn't seem right

**Comment by kottenator** [comment]
Another note:

I've overridden `normalize` method so `normalizeHash` started working, but now I have to do a bit weird transformation inside `normalizeHash.member(...)`:

```js
export default DS.JSONAPISerializer.extend({
    normalize: function(modelClass, resourceHash) {
        let name = modelClass.modelName;
        if (name in this.normalizeHash) {
            resourceHash = this.normalizeHash[name](resourceHash);
        }
        return this._super(modelClass, resourceHash);
    },

    normalizeHash: {
        member(hash) {
            hash.attributes["full-name"] = hash.relationships.actor.meta.title; // attributes["full-name"] will be converted to model.fullName that I need 
            hash.attributes.email = hash.relationships.actor.meta.email; // attributes.email will be converted to model.email that I need
            return hash;
        }
    }
);
```

**Comment by wecc** [comment]
`normalizeHash` is only implemented in the `RESTSerializer` and is not a part of the `JSONAPISerializer`. I believe the initial idea with `normalizeHash` was to be able to do transformations based on the root key of your payload, which isn't really applicable for JSON-API.

You should be able to override `normalize` for your `serializer:member` and set the attributes there before calling `_super`, like this:

```js
// app/serializers/member.js
export default DS.JSONAPISerializer.extend({
  normalize: function(modelClass, resourceHash) {
    resourceHash.attributes["full-name"] = resourceHash.relationships.user.meta.title; 
    resourceHash.attributes.email = resourceHash.relationships.user.meta.email;
    return this._super(modelClass, resourceHash);
  }
});
```

**Comment by kottenator** [comment]
Thanks, now I get it :)

But in your example it should be:
```js
// app/serializers/member.js
export default DS.JSONAPISerializer.extend({
    normalize: function(modelClass, resourceHash) {
        if (modelClass.modelName == 'member') {
            resourceHash.attributes["full-name"] = resourceHash.relationships.user.meta.title; 
            resourceHash.attributes.email = resourceHash.relationships.user.meta.email;
        }
        return this._super(modelClass, resourceHash);
    }
});
```

And it's only for one `member` model. 

And if I have more models to process than there will be a lot of `if...else` statements. I think that having some kind of `normalizeHash` is not a bad idea. But it would be more convenient to have something like:

```js
normalizeModel: {
    member(model, hash) {
        model.set("fullName", hash.relationships.user.meta.title);
        model.set("email", hash.relationships.user.meta.email);
    }
}
```

How do you think, it it a good idea?

**Comment by wecc** [comment]
The `normalize` function in `app/serializers/member.js` will only be called with a payload for a Member resource.

If you want everything in the same place, in the application serializer, you can implement your own `normalizeHash` based on `modelName` (like in your second comment).

**Comment by kottenator** [comment]
Yes, I did it. But I think that this is pretty common functionality, applicable to all types of Serializers and could be implemented in the core

**Comment by kottenator** [comment]
Sorry, I misunderstood your example from above, I thought it's in `application.js` but it's in `member.js` which is pretty good solution, as for me. 

You solved my problem and I'm closing this ticket. Thank you for such a great framework ;)
