### ISSUE TITLE
createRecord doesn't keep relationship attributes

### ISSUE THREAD

**Issue by givanse** [emberjs/data#3421]
`createRecord` somehow removes the `user` attribute when it does `record.setProperties(properties);`
https://github.com/emberjs/data/blob/v1.13.3/packages/ember-data/lib/system/store.js#L336

After `createRecord` I expected:

    title: "foobar", user: 1

got:

    title: "foobar", user: null

test case: http://emberjs.jsbin.com/jatayoviva/edit?html,js,console,output

**Comment by givanse** [comment]
Documentation bug: http://emberjs.com/api/data/classes/DS.Store.html#method_createRecord

> The createRecord api take a full record instead of a record id. http://emberjs.jsbin.com/fiseyi/edit?js,console

**Comment by sly7-7** [comment]
I don't think passing relationship ids to createRecord has ever worked. For now you can pass record, as you can see in your second example.
That beeing said, I don't know if passing ids as relationships could now be implemented given there are been major refactors. @wecc any thought ?

**Comment by wecc** [comment]
@sly7-7 Uncertain. It might work in some cases but providing just an ID will most likely not work in polymorphic cases.
