### ISSUE TITLE
Inconsistent behaviour of embedded/async records when retreiving id of async relation

### ISSUE THREAD

**Issue by novtor** [emberjs/data#3423]
I have a model like follows:
```javascript
App.Mymodel = DS.Model.extend({
   asyncmodel: DS.belongsTo('asyncmodel', {async: true}),
   embeddedmodels: DS.hasMany('embeddedmodel', {async: false}
});
```
With its serializer:
```javascript
App.MymodelSerializer = DS.RESTSerializer.extend(DS.EmbeddedRecordsMixin, {
    isNewSerializerAPI: true,
    attrs: {
         embeddedmodels: { embedded: 'always' }
    }
});
```
Mymodel entity is always loaded with asyncmodel asynchronous.

If a Mymodel entity does not have embeddedmodels entities, calling mymodelentity.get('asyncmodel.id') returns the asyncmodel's id even if it is not loaded.

In contrast, if a Mymodel entity has embeddedmodels in payload, calling mymodelentity.get('asyncmodel.id') returns undefined

Ember-data v. 1.13.2

**Comment by wecc** [comment]
Hi @novtor, would you be able to replicate this issue in a JSBin? Makes it a lot easier to debug.

Here's a preconfigured JSBin with Ember 1.13.2 and Ember Data 1.13.4: http://emberjs.jsbin.com/niwule/1/edit?html,js,output

**Comment by novtor** [comment]
I will try to reproduce it on jsbin by the end of this week

**Comment by novtor** [comment]
@wecc I think I will not be able to reproduce the issue, you can close it. Sorry for disturbing
