### ISSUE TITLE
Deprecate `normalizePayload` and `normalizeHash`

### ISSUE THREAD

**Issue by wecc** [emberjs/data#3428]
`normalizePayload` and `normalizeHash` is implicitly going away in 2.0 so we have to deprecate them in the next 1.13.x release.

**Comment by igorT** [comment]
To be clear, they have been deprecated already, it's just that we thought that the deprecation in the entry point of the serializer in `extract` was good enough, but it seems good to also warn people once they moved away from extract they have leftover methods

**Comment by wecc** [comment]
Closed by #3437

**Comment by jdhines** [comment]
I am hung up on this right now as I move from 1.11 to 1.13. The [API docs](http://emberjs.com/api/data/classes/DS.RESTSerializer.html#method_normalize) still mention `normalizeHash` and it's even in the example for the `normalize` method. My code practically mirrors this example (which I take to be the "how it should be done") but I'm still getting the deprecation warning, and if I just use `normalize` it give me an error that `normalize` is not a function.
