### ISSUE TITLE
Inflector not working for irregular plural name

### ISSUE THREAD

**Issue by rhyek** [emberjs/data#3429]
I'm having trouble with an irregular plural name for a model. The singular name is 'tomaAsistencia' and the plural should be 'tomasAsistencia', but I keep getting errors where ember data expects 'tomaAsistencium'. I have a jsbin here: http://emberjs.jsbin.com/delewoyetu/edit?html,js,console.

I have other model names similar to this, where they are composed of two words and in plural the first word contains the 's'. None have given me this problem. other examples are 'centroDeTrabajo' -> 'centrosDeTrabajo'. That works fine.

**Comment by pangratz** [comment]
I'm not sure if this is the final solution but a current workaround would be to change the irregular rule to `Ember.Inflector.inflector.irregular('toma-asistencia', 'tomas-asistencia');`. This also allows you to drop the model name from the `hasMany()` definition: http://emberjs.jsbin.com/navumuguvu/1/edit?html,js,output

**Comment by rhyek** [comment]
Using dasherized names completely solved my issue. Thanks.

**Comment by pangratz** [comment]
I would put them in an initializer ...
