### ISSUE TITLE
pushPayload no longer able to bootstrap sideloaded data

### ISSUE THREAD

**Issue by billpull** [emberjs/data#3434]
I have an initializer that reads some json data from a variable in the applications HTML and just updated to data `1.13.4` and it no longer accepts the side loaded data only the explicitly named type.

example data:
```
var BOOTSTRAP_DATA = {
    'vendor': {
         'id': 0,
         'name': 'Sub Shop #2',
         'categories': [0,1]
     },
     'categories': [
         {
           'id': 0,
           'name': 'subs',
           'slug': 'subs'
          },
          {
            'id': 1,
            'name': 'drinks',
            'slug': 'drinks'
           }
     ]
}
```

initializer
```
export function initialize(container/*, application*/) {
  var store = container.lookup("store:main");
  store.pushPayload('vendor', BOOTSTRAP_DATA);
}

export default {
  name: 'bootstrap-payload',
  after: "ember-data",
  initialize: initialize
};
```

error

`You must include an 'id' for undefined in an object passed to 'push'`

for ember-data version `1.13.2` I get the error
`Cannot read property 'type' of undefined` and when inspecting the method in chrome I see that the specified type was read correctly but any data afterwards is passed in as undefined.

**Comment by billpull** [comment]
seems to be a problem interpreting one of my model types rather than the method itself.

**Comment by billpull** [comment]
Problem is I have a custom serializer for `category` that sets the `primarKey` to `slug` but trying to side load data only uses the specified serializer type in this case `vendor` AFAIK. this did work in previous versions

**Comment by wecc** [comment]
@billpull I'm suspecting some of your serializers uses the old Serializer API and some uses the new one.

What serializers do you have and have you defined all of them?

**Comment by billpull** [comment]
@wecc my serializers in this example looked like this

`/serializers/category.js`
```
import DS from 'ember-data';

export default DS.RESTSerializer.extend({
	primarKey: 'slug'
});
```
I only had a serializer for the category object not all the objects being loaded/side-loaded since there was nothing special about their structure.

**Comment by wecc** [comment]
@billpull OK, thanks. Can you add `isNewSerializerAPI: true` to your category serializer, does that solve the error?

**Comment by billpull** [comment]
@wecc yes it does thank you
