### ISSUE TITLE
JSONAPIAdapter override headers seems to not work with async relationships

### ISSUE THREAD

**Issue by bluk** [emberjs/data#3444]
My main application adapter is like the following:

```
import DS from 'ember-data';

export default DS.JSONAPIAdapter.extend({
  headers: {
     "HeaderName": "HeaderValue"
  }
});
```

I have an async relationship on my `Foo` model like the following:

```
import DS from 'ember-data';

export default DS.Model.extend({
  relatedModels: DS.hasMany('relatedModel', { async: true} )
});
```

In my handlebars template:

```
{{#each this.model.relatedModels as |relatedModel|}}
{{relatedModel.randomProperty}}
{{/each}}
```

The server side is powered by the jsonapi-resources Rails gem.

If I have the `headers` property set in my `JSONAPIAdapter`, this will cause an incorrect `OPTIONS` XHR request to be made when trying to access the `relatedModels` property (also the HTTP headers specified do not seem to be set). The main request (to get the `Foo` model which has the async hasMany relationship) does have the HTTP header specified in the adapter.

If I remove the `headers` property in the adapter, a `GET` XHR request is correctly made (and the data is used as expected where it loops over the relatedModels).

I'm using Ember Data 1.13.4 and Ember 1.13.2

**Comment by wecc** [comment]
This seems related to how CORS and `Access-Control-*` headers works. Is the API you're connecting to located on another domain than your Ember app?

**Comment by bluk** [comment]
Yup, it seems to be a CORS issue (the API is on a different domain). I was trying to just use the `ember serve --proxy http://localhost:3000/` but apparently in this scenario it triggers an issue. I'll try to fix up my API and respond with the correct headers. Thanks!

**Comment by serv** [comment]
@wecc Sorry to resurrect an old thread.

So is there no way for Ember to handle custom header for cases where the domain for the API and the domain for the webapp are different?
