### ISSUE TITLE
1.13.x may have malformed output 

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/data#3445]
related issues:

* https://github.com/ember-cli/ember-cli/issues/4338
* https://github.com/ember-cli/ember-cli/issues/4296

a `;` after ED appears to fix it.

also note: `(function(){}.call(this));`  vs `(function(){}).call(this);` the former is more resilient then the later. Unsure if that is the source of the issue.

A quick skim doesn't offer an obvious problem though. I'll try to get access to a code example and get more info

**Comment by igorT** [comment]
cc @fivetanley

**Comment by thoov** [comment]
@stefanpenner @igorT to reproduce:

```
ember addon foo
```

Then change bower.json to this:

```json
{
  "name": "foo",
  "dependencies": {
    "ember": "components/ember#beta",
    "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.3",
    "ember-cli-test-loader": "ember-cli-test-loader#0.1.3",
    "ember-data": "1.0.0-beta.18",
    "ember-load-initializers": "ember-cli/ember-load-initializers#0.1.4",
    "ember-qunit": "0.3.3",
    "ember-qunit-notifications": "0.0.7",
    "ember-resolver": "~0.1.15",
    "jquery": "^1.11.1",
    "loader.js": "ember-cli/loader.js#3.2.0",
    "qunit": "~1.17.1"
  },
  "resolutions": {
    "ember": "beta"
  }
}
```

And when you run `ember s` you will get this error:

![screen shot 2015-06-25 at 2 25 50 pm](https://cloud.githubusercontent.com/assets/166909/8366015/193f820a-1b46-11e5-9a20-447eb96f4a01.png)

**Comment by stefanpenner** [comment]
I'll take a look now.

**Comment by thoov** [comment]
Then if you create a file within the addon folder and you import import it like so:

```js
import foo from 'foo/my-file';
```

you will get this error:

![screen shot 2015-06-25 at 2 47 04 pm](https://cloud.githubusercontent.com/assets/166909/8366354/3525b93c-1b49-11e5-8bbe-042576375513.png)

However if you remove ember-data from bower and restart ember the error goes away.

**Comment by stefanpenner** [comment]
mystery solved.

ember-data 1.13 does not work with ember#canary or ember#beta, ember-data#canary does, and is likely just in need of a ember-data#beta release.

**Comment by stefanpenner** [comment]
i suspect we can close this, @fivetanley @igorT thoughts?
