### ISSUE TITLE
fallback serializer appears deficient for any actual usage

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/data#3446]
https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/store/serializers.js#L8-L12

for example, it is missing at-least `normalizeResponse`. This fallback feels funky in general.

**Comment by stefanpenner** [comment]
related: https://github.com/emberjs/ember-data-fixture-adapter/issues/7

**Comment by stefanpenner** [comment]
i suspect if this serializer is ever hit, we should just throw. (or investigate in a better fallback) This really just tricks you into believing everything is going to be ok.

**Comment by igorT** [comment]
We can also implement normalizeResponse, this slipped by in the refactor

**Comment by brendanoh** [comment]
I was under the impression reading the code that this didn't require a serializer as the data in fixtures could just be passed through. So when my code exploded this morning I was surprised.

Is there a quick hack fix to keep working as this is currently a blocker for me?

**Comment by stefanpenner** [comment]
it seems like this should just fallback to the -default serializer. @igorT thoughts?

**Comment by stefanpenner** [comment]
> Is there a quick hack fix to keep working as this is currently a blocker for me?

fixing it :P

**Comment by stefanpenner** [comment]
need to run to a meeting, i got all tests green. Was just about to add you scenario to the tests.

**Comment by brendanoh** [comment]
OK will test now with branch

**Comment by stefanpenner** [comment]
thanks :)

**Comment by brendanoh** [comment]
And boom goes the dynamite. All working.

**Comment by stefanpenner** [comment]
> And boom goes the dynamite. All working.

:+1:

**Comment by wecc** [comment]
Closing since this has been fixed by https://github.com/emberjs/ember-data-fixture-adapter/pull/9 and added deprecation in #3505.
