### ISSUE TITLE
components/ember-data missing #release branch

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/data#3447]
related issue: https://github.com/components/ember-data/issues/30

**Comment by igorT** [comment]
cc @fivetanley

**Comment by bmac** [comment]
Looks like this was happening because there was no existing `release` branch on bower, so the the git checkout of the bower repo failed. I have created a `release` branch on bower and I am in the process of re-running the release travis build to see if that fixes the issue.

**Comment by bmac** [comment]
Travis build succeeded and published to https://github.com/components/ember-data/tree/release
