### ISSUE TITLE
ActiveModelSerializer#pushPayload uses the deprecated Store#pushMany method

### ISSUE THREAD

**Issue by foxnewsnetwork** [emberjs/data#3450]
In the ActiveModelSerializer (RestSerializer) code:

https://github.com/emberjs/data/blob/v1.13.4/packages/ember-data/lib/serializers/rest-serializer.js#L667

we have:
```javascript
pushPayload: function(store, rawPayload) {
  ...
  store.pushMany(modelName, normalizedArray);
...
```
But in the store code:
https://github.com/emberjs/data/blob/v1.13.4/packages/ember-data/lib/system/store.js#L2009

```javascript
pushMany: function(modelName, datas) {
    Ember.assert('Passing classes to store methods has been removed. Please pass a dasherized string instead of '+ Ember.inspect(modelName), typeof modelName === 'string');
    Ember.deprecate('Using store.pushMany() has been deprecated since store.push() now handles multiple items. You should use store.push() instead.');
    ...
```
We see that `pushMany` has been deprecated

This is an issue because `store.pushPayload`, which appears to still be canonical api, calls the serializer which in turn uses the deprecated code.

Should I do a pr where I switch the serializer's call to `store.pushMany` to just regular `store.push` ?

**Comment by igorT** [comment]
Hm, I thought we fixed this. Please do. cc @wecc

**Comment by foxnewsnetwork** [comment]
@igorT I just double-checked and you're absolutely right, this is indeed fixed on the master branch:

https://github.com/emberjs/data/blob/master/packages/ember-data/lib/serializers/rest-serializer.js#L405

My mistake, I was looking at the 1.13.4 tag
