### ISSUE TITLE
store.query and store.queryRecord should namespace query options

### ISSUE THREAD

**Issue by igorT** [emberjs/data#3453]
In particular, currently you call `store.query('type', { options })`, but it should be `store.query('type', { query : {options} })`

**Comment by thaume** [comment]
Need help on that ?

**Comment by igorT** [comment]
Yes please, do you have time?

**Comment by igorT** [comment]
Raised it in the community slack

**Comment by thaume** [comment]
Okay, yep I'll work on it on sunday night (long trip home)

**Comment by igorT** [comment]
Sounds great

**Comment by thaume** [comment]
Hey @igorT the PR is up over here https://github.com/emberjs/data/pull/3459

**Comment by Kuzirashi** [comment]
What's the status of this issue?

**Comment by bmac** [comment]
This change didn't end up making it into 2.0. I'm going to close it because we are unlikely to add a breaking change like this until 3.0.
