### ISSUE TITLE
buildUrl params receiving blank params after upgrading from 1.0.0-beta.17 to 1.13.0

### ISSUE THREAD

**Issue by matixmatix** [emberjs/data#3456]
In my adapter I had to add support for nested resources by overriding `buildURL` method. This is how it looked like before upgrading:

![image](https://cloud.githubusercontent.com/assets/273660/8397039/daf12812-1dbd-11e5-9a0a-512881a27e44.png)

After upgrading params are blank:
![image](https://cloud.githubusercontent.com/assets/273660/8397034/d36f186a-1dbd-11e5-9752-572746feeca6.png)

Is this a bug, or am I missing something?

By the way, this is the URL for this route: `http://localhost:4200/#/dashboard/urls/17674/keywords`

**Comment by wecc** [comment]
The signature for `buildURL` has changed to:

```js
buildURL: function(modelName, id, snapshot, requestType, query)
```

See http://emberjs.com/api/data/classes/DS.BuildURLMixin.html#method_buildURL for more details.

If you only want to modify URLs for `store.query` calls you can override `urlForQuery` instead.
See http://emberjs.com/api/data/classes/DS.BuildURLMixin.html#method_urlForQuery

**Comment by matixmatix** [comment]
Thank you @wecc, you're a gentleman and a scholar
