### ISSUE TITLE
Ember.keys and Ember.create deprecated in 1.13

### ISSUE THREAD

**Issue by bmac** [emberjs/data#3465]
Using release Ember Data with release Ember currently causes a bunch of deprecation warnings in the console.

http://output.jsbin.com/losona

**Comment by stefanpenner** [comment]
`keys = Object.keys || Ember.keys` would allow for IE8 compat, while all ie9+ browsers getting no deprecations in dev.

**Comment by sly7-7** [comment]
Will tackle this asap :)

**Comment by sly7-7** [comment]
Hm, seems like this has already been done in https://github.com/emberjs/data/pull/3432, that beeing said, no IE8 compat

**Comment by stefanpenner** [comment]
@sly7-7 that is on master, which is slated for 2.0. My above approach should be applied to the stable release, and release as part of the next 1.13.x

**Comment by bmac** [comment]
What @stefanpenner says is correct. This pr will need to target the https://github.com/emberjs/data/tree/release branch instead of `master`.

**Comment by sly7-7** [comment]
Ok, thanks both of you :smile:

**Comment by bmac** [comment]
Fixed by https://github.com/emberjs/data/pull/3475
