### ISSUE TITLE
assertPolymorphicType problems with DS.EmbeddedRecordsMixin

### ISSUE THREAD

**Issue by iamjstates** [emberjs/data#3476]
I'm using the embeddedRecordsMixin and assertPolymorphicType causes failure as addedRecord is undefined in this method.
<code>
var ember$data$lib$utils$$assertPolymorphicType = function (record, relationshipMeta, addedRecord) 
<code>

**Comment by canufeel** [comment]
Why is this one closed? What is the solution? I have the same problem here:

```
TypeError: Cannot read property 'type' of undefined
    at ember$data$lib$utils$$assertPolymorphicType
```

at line: `var addedType = addedRecord.type.modelName;`

**Comment by fivetanley** [comment]
What version are you using, and what does the payload look like @canufeel?

**Comment by canufeel** [comment]
@fivetanley Hi you are so fast to answer. I am not sure even how to catch this error properly as the stack doesn't have it. My version is 2.2.0 for both ember-data and ember.

**Comment by canufeel** [comment]
Ok i have investigated this issue further and it came out that i get this error when i do try to `set(model,'hasManyRelationshipName',value);` and the value itself is an array with promises inside. I know i should put the actual ember-data records in this array but still some assertion would be usefull in this case.

**Comment by pangratz** [comment]
@canufeel such an assertion exists [here](https://github.com/emberjs/data/blob/v2.3.3/addon/-private/system/relationships/has-many.js#L150-L152), so you should have bumped into that... What ember-data version are you using?

**Comment by canufeel** [comment]
@pangratz True. Now i see it. v.2.2.0 that i am using doesn't have this. Would consider upgrading.
