### ISSUE TITLE
Update Documentation about Errors

### ISSUE THREAD

**Issue by nicolas-dular** [emberjs/data#3480]
In the [Ember Data documentation](http://emberjs.com/api/data/classes/DS.Errors.html) the json response for errors is:
````

{
  "username": ["This username is already taken!"],
  "email": ["Doesn't look like a valid email."]
}
````

but due to the changes for [JSON API Error Objects](http://jsonapi.org/format/#error-objects)  and with this [commit](https://github.com/emberjs/data/commit/893e2af813c16786ba6d9296cf3aa27b7407872e)  for `1.13.4` the json response for errors is now:

````
{
  errors: {
    "username": ["This username is already taken!"],
    "email": ["Doesn't look like a valid email."]
  }
}
````

Please update the documentation for this change!

**Comment by philipp-spiess** [comment]
:+1:
