### ISSUE TITLE
[1.13] Attributes that are camelCase behave weirdly with JSON API documents from normalizeResponse

### ISSUE THREAD

**Issue by XrXr** [emberjs/data#3486]
JSON API document returned from `normalizeResponse` in `DS.RESTSerializer` seem to yield different result than if that same document is received as payload in `DS.JSONAPISerializer`.

If you have a document
```json
{
  "data": {
    "id": 1,
    "type": "foo",
    "attributes": {
      "foo-bar": "1970-01-01T00:00:00.000Z"
    }
  }
}
```

And a model 
```js
// models/foo.js
export default DS.Model.extend({
   fooBar: DS.attr('date')
});
```

and that document is returned from `normalizeResponse` in a `RESTSerializer`  `fooBar` would be `undefined` in the model.

If that exact same document is returned from the server as payload, and `JSONAPISerializer` is used, `fooBar` gets the correct date object.

What's more weird is if `"foo-bar"` in the document is renamed to `"fooBar"`, `fooBar` in the model gets the raw ISO date string, not a date object.

From what I can gather, which is basically just the 1.13 blog post, `normalizeResponse` is suppose to return a JSON API document. Even though not explicitly stated, I expect the document to be treated as if it were a payload from the server and `JSONAPISerializer` is used .

Am I missing something here? I would love to see more documentation about these new hooks.

Here is a [jsbin](http://emberjs.jsbin.com/lufiya/edit?html,js,output) demoing this behavior.

**Comment by wecc** [comment]
Hi @XrXr,

So, this might be a bit confusing but the internal Ember Data JSON API format and the one that JSONAPISerializer defaults to are a little bit different.

- The internal Ember Data JSON API format uses **camelcased attributes** (`fooBar`) and **singular, dasherized type** (`my-model`)
- The JSONAPISerializer defaults to **dasherized attributes** (`foo-bar`) and **plural, dasherized type** (`my-models`).

The reason for this is that we wanted the JSONAPISerializer to Just Work out of the box with any of the examples on jsonapi.org while internally we still want to use camelcase.

However, all the built-in serializers handles this for you automatically if you just call `this._super()` after doing your customizations to the payload. This also makes sure any transformations are run when normalizing each item. You should never really have to "create" the JSON API Document yourself.

In your example you seem to be using a JSON API payload with the RESTSerializer. I would instead recommend you to use the JSONAPISerializer if your payload is of JSON API format. If you want to use the format expected by the RESTSerializer, you can do that as long as you remember to call `this._super()` in normalizeResponse (you can do any modifications before of after calling super, that's up to you).

**Comment by XrXr** [comment]
The key thing I didn't realize was that the `super` of `normalizeResponse()` would generate a JSON API object. Unfortunately I already spent a lot of time putting together code that convert REST format into JSON API. It didn't occur to me, from just reading the blog post, that just calling `super` was enough

Regardless, very happy to be finally with the transition to 1.13.4 for my app :). Still, I would love to see more documentation around these new hooks on http://emberjs.com/api/data/ though. Right now one kind of have to ask around in order to correctly update, which in my opinion is not a good sign.

Thank you for your help!
