### ISSUE TITLE
ember-data error does not contain http status code

### ISSUE THREAD

**Issue by jsedlacek** [emberjs/data#3491]
After upgrade to ember-data `1.13.4` I am not able to find the http status code of failed request.

Here is an example when an API does not exist:

```javascript
// models/user.js:
export default DS.Model.extend({});
```

```javascript
// routes/index.js:
export default Ember.Route.extend({
  model() {
    return this.store.find('user', 1);
  },
  actions: {
    error(err) {
      assert.equal(err.status, 404);
    }
  }
});
```

Result:
```
expected undefined to equal 404
```

Note 1: This works correctly in `1.0.0-beta.18`.

Note 2: This behavior is documented on http://guides.emberjs.com/v1.12.0/routing/loading-and-error-substates/

**Comment by tchak** [comment]
We need to fix the documentation, thank's for the pointer.
We are now rejecting with normalized `DS.AdapterError` instead of `xhr` object
If you want to access some information about the error, you need to use `err.errors[0]`.

**Comment by jsedlacek** [comment]
Thanks @tchak. However `err.errors[0]` does not contain the status code.

Do I understand it correctly that there's no way to get the status code any more?

**Comment by tchak** [comment]
@jsedlacek what kind of error is the backend returning? It may be possible that you will need to customize the adapter hook `handleResponse`. This is intended. In most cases it is a bad idea to leek http details to you app. You probably want to reject with a specific type of error.

**Comment by jsedlacek** [comment]
@tchak I'd like to handle `401` (Unauthorized) error to transition to login route when the auth token expires.

The error body looks like this:
```json
{
    "errors": {
        "base": ["You're not authorized to access this resource"]
}
```

**Comment by tchak** [comment]
@jsedlacek you should override `handleResponse(status, headers, body)` on the adapter and reject with `UnauthorizedError`.

**Comment by jsedlacek** [comment]
Perfect, let me try that. Thanks for quick responses.

**Comment by tchak** [comment]
Something like this

```
handleResponse(status, headers, body) {
  if (status === 401) {
    return new UnauthorizedError();
  } else {
    return this._super(status, headers, body);
  }
}

**Comment by jsedlacek** [comment]
The proposed solution works like a charm. Thanks for your help @tchak.

**Comment by albertpak** [comment]
This looks to be a closed issue - I'm trying to handle a 401 error in my app, and trying to use proposed solution [above](https://github.com/emberjs/data/issues/3491#issuecomment-119327684) - but running into an issue where I'm getting an error that says `TypeError: UnauthorizedError is not a constructor`

I'm using Ember 2.12 / Ember Data 2.11

**Comment by alexlafroscia** [comment]
@albertpak where are you trying to import `UnauthorizedError` from?
