### ISSUE TITLE
[1.13] Remove use of pushMany in extractArray in 1.13

### ISSUE THREAD

**Issue by kenips** [emberjs/data#3492]
In 1.13, [extractArray still uses store.pushMany](https://github.com/emberjs/data/blob/1-13-3/packages/ember-data/lib/serializers/rest-serializer.js#L624) which breaks serializers opting in with the new API. Manually switching that to a loop using store.push works. Am I missing something?

/cc @wecc

**Comment by bmac** [comment]
I believe the serializer should call `normalizeArray` instead of `extractArray` when `isNewSerializerAPI: true`. @kenips any chance you can track down whats causing `extractArray` to be called?

**Comment by kenips** [comment]
Right. Sorry I had an override calling `extract` on the serializer. Switching it to `normalizeResponse` works. Thanks!
