### ISSUE TITLE
Ember Data 1.13.4: Rejected promise error on model.save() has no responseJSON

### ISSUE THREAD

**Issue by sarus** [emberjs/data#3493]
When using the following versions:

```
ember.debug.js:4888DEBUG: Ember                     : 1.12.0
ember.debug.js:4888DEBUG: Ember Data                : 1.0.0-beta.18
ember.debug.js:4888DEBUG: jQuery                    : 1.11.3
ember.debug.js:4888DEBUG: Ember Simple Auth         : 0.8.0-beta.3
ember.debug.js:4888DEBUG: Ember Simple Auth Testing : 0.8.0-beta.3
```

A failed call (Bad Request HTTP Code 400) to `model.save` returns an error object in the promise that contains the responseJSON so the following works:

```javascript
        this.model.save().then(function (model) {
          // save worked
        }, function (error) {
          // error object contains responseJSON so I can get access to the server response 
          self._showErrorMessage(error.responseJSON.userMessage);
        })
```

When upgrading to v1.13:

```
ember.debug.js:4888DEBUG: Ember                     : 1.13.2
ember.debug.js:4888DEBUG: Ember Data                : 1.13.4
ember.debug.js:4888DEBUG: jQuery                    : 1.11.3
ember.debug.js:4888DEBUG: Ember Simple Auth         : 0.8.0
ember.debug.js:4888DEBUG: Ember Simple Auth Testing : 0.8.0
```

The `error` object returned by the rejected promise is a totally different object and I don't see the servers responseJSON anywhere in it.

Is this intentional?  How can I get access to the server response in the latest ember data?  Thank you!

**Comment by sarus** [comment]
To update @tchak mentioned in slack that Ember Data used to reject with the xhr object but now rejects with a normalized error.  The suggestion was look in `error.errors[0]`.

```
        this.model.save().then(function (model) {
          // save worked
        }, function (error) {
          console.info(error.errors[0]);
        })
```
However that just contains the following including the string `[object Object]` which seems like a serialization issue?

```
details: "[object Object]"
status: "400"
title: "The backend responded with an error"
```

**Comment by tchak** [comment]
@sarus yes `normalizeErrorResponse` will assume that if the error payload is not in JSON-API format (`errors: []` form) the payload is a string. I am open to discuss what the default should be. In the mean time, you can override `parseErrorResponse` in order to return a string that will be interpreted as error detail.

**Comment by tchak** [comment]
I am going to close this, since there is a working solution for the problem. @sarus ping me on Slack if I can help with more details. We manage to solve it for some other folks there.
