### ISSUE TITLE
Use `detail` instead of `details` for JSON API errors

### ISSUE THREAD

**Issue by sebastianseilund** [emberjs/data#3494]
The [current implementation](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/adapters/errors.js#L145) reads the `details` property on JSON API errors.

[The JSON API spec](http://jsonapi.org/format/#error-objects) mentions a field named `detail`, which error objects "MAY" contain.

Shouldn't Ember Data use the same name (`detail`)? I had implemented my JSON API per the spec, and it took me a while to figure out why my error messages were blank.

I can make a PR, if you agree.

**Comment by igorT** [comment]
cc  @tchak

**Comment by igorT** [comment]
Thanks for the issue, we should be following the spec, so it seems like an oversight

**Comment by sebastianseilund** [comment]
Thanks. I submitted a PR. Closing this one.
