### ISSUE TITLE
pushObject in hasMany/belongsTo doesn't set type and id

### ISSUE THREAD

**Issue by lessless** [emberjs/data#3495]
It's and idiomatic hasMany/belongsTo polymorphic example where email can belongs to the many types of Contactable ('profile' is one of them) http://emberjs.jsbin.com/sibecasiga/1/edit?js,output, which was perfectly described in the http://www.toptal.com/emberjs/a-thorough-guide-to-ember-data

The problem is that after profile.get('emails').pushObject(email); email's 'contactable' and 'contactableType' are empty. This is not how it is supposed to be, right?

Also issue may be related to #2985

**Comment by bmac** [comment]
In your jsbin I'm getting an error "Uncaught TypeError: Cannot read property 'modelFor' of undefined" because this line is passing the undefined into `determineRelationshipType`. https://github.com/emberjs/data/blob/cf428d4f5d1cda0414a96cb7daaf2eabb7cd5d39/packages/ember-data/lib/serializers/json-serializer.js#L806

This looks defiantly like a bug to me, although I'm unsure if its the same bug you are describing.

**Comment by sly7-7** [comment]
Hm, it seems like there has something to do with the serializer itself. Using the JSONAPI one to serialize, all seems to be ok.
http://emberjs.jsbin.com/cigimif/2/edit?js,output

Maybe @wecc could be able to quick debug this one.

**Comment by sly7-7** [comment]
I cleaned up a bit the example, and even use the JSONAPI format.
http://emberjs.jsbin.com/cigimif/edit?js,output

I don't know if it's a new bug, or it it has ever worked. That beeing said, as a workaround, you can set the inverse, and that works.

**Comment by lessless** [comment]
thank you @sly7-7   for the tip! will keep an eye on the topic.

**Comment by wecc** [comment]
Is this still an issue on 2.x?

#3500 was closed in favor of #3975

**Comment by pete-the-pete** [comment]
I don't think this is an issue anymore: [https://ember-twiddle.com/0cf9034428370e344f6d0cda8eb529ff](.)  If not, can we close this?

**Comment by runspired** [comment]
@pete-the-pete Relationships "are complicated" BAHAHAHAHAHAHAHA 😂

**Comment by lessless** [comment]
@pete-the-pete shouldn't `email.set('contactable', profile);` and `profile.get('emails').pushObject(email);` produce identical results?

**Comment by sly7-7** [comment]
@pete-the-pete I could probably update my failing PR to if it pass now. Will try that

**Comment by pete-the-pete** [comment]
Sorry about that. I was hoping to help move this along/close out some old tickets, but didn't pay close enough attention.  At least we might be able to remove the "Needs Bug Verification" label?

@runspired, glad you enjoyed that, but I can't take credit for it. I just copied @sly7-7's jsbin.

**Comment by sly7-7** [comment]
I've investigated a bit, I'm not sure but I think it's related with the fact that the key for the implicit relationship is wrong (it's build using the concrete type, not the polymorphic one). So I guess when doing `record.get('polymorphicRel')`ember-data is not able to find out what the corresponding record is. Maybe we are encountering this https://github.com/emberjs/data/blob/master/addon/-private/system/relationships/state/relationship.js#L68

**Comment by runspired** [comment]
We resolved this issue :)
