### ISSUE TITLE
model rollback doesn't clear model.errors.attribute

### ISSUE THREAD

**Issue by smcclstocks** [emberjs/data#3498]
Steps to reproduce:

1. dirty model
2. save model
3. get validation errors populating model.errors
4. model.rollbackAttributes()
5. model.errors.attribute.length != 0 but model.errors.length == 0

This leave the UI displaying errors when the model has been rolled back & the validation errors should no longer be present. In my case the attribute is name firstName so in step 5 above model.errors.attribute.length is model.errors.firstName.length. I could be missing something so sorry for the waste of time if so.. i can't seem to work around this although model.get('errors').has('firstName') does return false after the rollback even though the array of messages are still present.

When I transition away & come back the UI no longer shows the errors so I wasn't sure if this was something to do with my templates instead. Thanks ahead of time.

**Comment by smcclstocks** [comment]
DEBUG: -------------------------------
ember.debug.js:5361DEBUG: Ember                          : 1.13.2
ember.debug.js:5361DEBUG: Ember Data                     : 1.13.4
ember.debug.js:5361DEBUG: jQuery                         : 1.11.3
ember.debug.js:5361DEBUG: Ember Simple Auth              : 0.8.0
ember.debug.js:5361DEBUG: Ember Simple Auth Cookie Store : 0.8.0
ember.debug.js:5361DEBUG: Ember Simple Auth OAuth 2.0    : 0.8.0
ember.debug.js:5361DEBUG: -------------------------------

**Comment by tchak** [comment]
looking in to it

**Comment by tchak** [comment]
@smcclstocks what is the exact value of `model.get('errors.attribute.length')` in your case? I have run some tests and I am getting `null` which is expected. Using != 0 in such cases is usually a bad idea. You should use `Ember.isEmpty(model.get('errors.attribute'))`.

**Comment by smcclstocks** [comment]
I was only using != 0 for illustration & don't use that in my app at all. But I notice the same thing you said with is model.get('errors.attribute.length') is null after the rollbackAttributes(). But the templates don't reflect that for some reason. The template will properly reflect the rollback by setting the value back to the original but the template never reflects the fact that the attributes error length is no null. Here's my example:

                  <p>{{model.errors.street}}</p>
                  <p>{{model.errors.street.length}}</p>
                  {{#each model.errors.street as |err|}}
                    <p>{{err.message}}</p>
                  {{/each}}

In that case the attribute I'm testing with is obviously named street & after the rollback I get what you said in the console logs:

        console.log @get('controller.model.errors.length')
        console.log @get('controller.model.errors.street.length')

        0
        null

But the template instead continues to show:

                  <p>[object Object]</p>
                  <p>1</p>
                  <p>>150 characters & required</p>

Do you see that in your testing as well?
