### ISSUE TITLE
store.queryRecord not implemented by ActiveModelAdapter

### ISSUE THREAD

**Issue by justinbburris** [emberjs/data#3508]
I seem to be running into an issue when trying to use `queryRecord` in Ember Data 1.13.4

```
> this.store.queryRecord('some-record', {query: 'query'})
Error: Assertion Failed: You tried to make a query but your adapter does not implement `queryRecord`
```

I am using the ActiveModelAdapter, which inherits from the RestAdapter. The function isn't defined in either. 

Is there something obvious I'm missing? Thanks!

**Comment by thaume** [comment]
Hey @justinbburris it will be there soon, we're still fixing a couple things about queryRecord at the store level.
PRs for the RESTAdapter and the ActiveModelAdapter will come soon.

**Comment by thaume** [comment]
Closing in favor of https://github.com/emberjs/data/issues/3514

**Comment by wecc** [comment]
Closing as `ActiveModelAdapter` will be fixed automatically when `queryRecord` is implemented `RESTAdapter`.

**Comment by justinbburris** [comment]
Thanks for the fast response. Good to know I wasn't going crazy :)
