### ISSUE TITLE
Implement queryRecord in the RESTAdapter

### ISSUE THREAD

**Issue by thaume** [emberjs/data#3514]

**Comment by Panman8201** [comment]
Tried it not knowing it wasn't implemented, glad to see it [seems to be coming](https://github.com/emberjs/data/issues/3508#issuecomment-119363191). This will be great once implemented, I have a few places where I have to use `afterModel` to get the single instance back out.

**Comment by thaume** [comment]
Work is in progress over [here](https://github.com/emberjs/data/pull/3554)

**Comment by Panman8201** [comment]
FYI, this issue can be closed thanks to ember-data 1.13.7. :+1:
