### ISSUE TITLE
Ember-Data 1.13.4 not respecting string casing

### ISSUE THREAD

**Issue by visoft** [emberjs/data#3517]
I've upgraded from Ember-Data 1.0.0.beta.19.1 >> 1.13.4. I'm having a problem where completely capitalized strings in my JSON are being converted to lowercase, thus look ups by that property are failing. I've traced the problem down inside `findBy` where I see my property as being all lowercase.

**Comment by sly7-7** [comment]
It would be great if you could provide a an example demonstrating your issue. Snippet would be helpful, jsbin (starting point here http://emberjs.jsbin.com/?html,js,output) would be great, or even a failing test would be awesome :smile:

**Comment by visoft** [comment]
I'm not able to reproduce the problem in a jsbin so it must be something specific to my application. Sorry for wasting your time. I'll see what else I can find. If I'm able to reproduce it in the simple case, I'll reopen the issue.

**Comment by sly7-7** [comment]
No problem, thank you.
