### ISSUE TITLE
Association URL mapping document for the jsonapi adapter

### ISSUE THREAD

**Issue by krzkrzkrz** [emberjs/data#3522]
Its hard trying to guess what url endpoints are expected for a model association.

For example. assuming `model` is an `article`. `{{model.comments}}` is expected to hit `articles/1/comments`

Another example. If `model` is a `comment`. `{{model.article.author}}` is expected to hit what endpoint?

**Comment by krzkrzkrz** [comment]
Spoke to @wecc on the Ember Data slack channel. To summarize:

> If you don't provide any information about your relationship at all (no `links:related`, no `data`) Ember Data will not make a request at all
> If you provide `data` (with IDs) ED will make a requests to `/type/:id`
> If you provide a link, that link will be followed

Thanks again Wecc! Keep it up!

**Comment by pixelhandler** [comment]
@krzkrzkrz  Perhaps that would make for a good contribute to the guides.
