### ISSUE TITLE
Set Content-Type: application/vnd.api+json by default

### ISSUE THREAD

**Issue by krzkrzkrz** [emberjs/data#3523]
When using the JSONAPIAdapter. Should the client automatically send the following in a header:

    Content-Type: application/vnd.api+json

As mentioned at http://jsonapi.org/format/#content-negotiation-clients

Or does it make sense for the developer to set this up in `/app/adapters/application.js`? i.e.

    headers: function() {
      var headers = {};
      headers['Content-Type'] = 'application/vnd.api+json';
      ...
      return headers;
    }

**Comment by wecc** [comment]
Hi @krzkrzkrz!

This should be done automatically for you if you're using the `JSONAPIAdapter` (see [here](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/adapters/json-api-adapter.js#L28)). Are you experiencing cases where this is not working?

**Comment by krzkrzkrz** [comment]
The request headers have: `Accept:application/vnd.api+json`, but not `Content-Type:application/vnd.api+json`. Is that normal?

**Comment by wecc** [comment]
It is normal if the request does not have any content. If there's content with the request there should be a Content-Type header.

**Comment by krzkrzkrz** [comment]
Thanks for clearing that up
