### ISSUE TITLE
When calling store.push on JSONApi payload the store can't find model

### ISSUE THREAD

**Issue by kempchee** [emberjs/data#3527]
I have a user model defined in the file 'user.js' with name, admin, and email attributes defined in an Ember 1.13.3 and data 1.13.3 Ember-Cli project.  My server returns the following payload:
    {"data":
      {"id":"1","type":"users",
        "attributes":{"email":"fotingkempchee@gmail.com","admin":true}
       }
     }
However, when I call store.push(payload), ember gives me the following error:
Uncaught Error: No model was found for 'users'

Of course when I switch the model file to 'users.js', the problem goes away.  My understanding of JSONApi is that the resource type should always be the pluralized form of the actual resource name so this is a bug.  Please let me know if I am incorrect.

**Comment by wecc** [comment]
One thing that can be a little bit confusing is that even though Ember Data supports JSON API as it's internal format there are some requirements. These requirements also differs slightly when it comes to the built-in JSON API Adapter/Serializer.

This is the format Ember Data uses internally:

```json
{
  "data": {
    "type": "ember-user",
    "id": "1",
    "attributes": {
      "firstName": "Christoffer",
      "lastName": "Persson"
    }
  }
}
```

This is the format JSON API Serializer uses (by default):

```json
{
  "data": {
    "type": "ember-users",
    "id": "1",
    "attributes": {
      "first-name": "Christoffer",
      "last-name": "Persson"
    }
  }
}
```

So, as you can see the internal JSON API format uses **singular, dasherized** types and **camelCased** attributes while the JSON API Serializer uses **plural, dasherized** types and **dasherized** attributes (same goes for relationship names).

The JSON API Serializer does however convert the JSON API payload to the JSON API format used by Ember Data internally.

This means that to be able to push your raw payload to the store, it has to be normalized by the serializer first. This can be done using `store.push(store.normalize('user', payload))` or simply `store.pushPayload(payload)`.

**Comment by kempchee** [comment]
Thanks it works just as you described except that with normalize you actually need to pass in payload.data.
