### ISSUE TITLE
ActiveModelSerializer errors hash was changed in 1.13.x

### ISSUE THREAD

**Issue by jimmay5469** [emberjs/data#3528]
The format for errors has unexpectedly changed in 1.13.x when catching errors after a save action.
`model.save().catch(function(res) { /*res.errors property here has changed*/ })`

**422** validation errors `res.errors` used to be:
```
{
  firstName: ['Server says: Invalid first name.']
  lastName: ['Server says: Invalid last name.']
  email: ['Server says: Invalid email.']
  newPassword: ['Server says: Invalid password.']
}
```

now it is this:
<img width="1254" alt="screen shot 2015-07-10 at 12 23 57 pm" src="https://cloud.githubusercontent.com/assets/781752/8623342/f3de1818-26fe-11e5-8a59-f9c6f0c2ac37.png">

**500** error `res.errors` used to be `null`, now it is this:
<img width="355" alt="screen shot 2015-07-10 at 12 22 39 pm" src="https://cloud.githubusercontent.com/assets/781752/8623339/ecbcc28c-26fe-11e5-81f4-570436e7f839.png">

Looks to me like this probably happened after the internal errors representation changed to JSON API (https://github.com/emberjs/data/commit/893e2af813c16786ba6d9296cf3aa27b7407872e).  It looks like it needs translated out of that new internal representation for ActiveModelSerializer.

**Comment by jimmay5469** [comment]
Am I going about this wrong?  Maybe i should be accessing the errors off of the saved object rather than from the params?
<img width="339" alt="screen shot 2015-07-10 at 12 47 27 pm" src="https://cloud.githubusercontent.com/assets/781752/8623874/fa3b43f4-2701-11e5-812e-b2144ae5a287.png">

**Comment by tchak** [comment]
@jimmay5469 yes you should access errors on the model not on the error passed in te reject from the adapter. We changed internal representation of errors. Public API `record.errors` is unchanged.

**Comment by jimmay5469** [comment]
Sorry, didn't realize the `.catch()` param was private api.  Thanks for the clarification.  I'm just gonna go ahead and close this issue then.
