### ISSUE TITLE
Support a more complete rollback of records

### ISSUE THREAD

**Issue by forgetboy** [emberjs/data#3536]
I would propose we do something along these lines to provide a more comprehensive rollback -

	rollback(record) {
               if (!record) {
			return;
		}
				
		record.eachRelationship((name, descriptor) => {
			if (descriptor.kind === 'hasMany') {
				let hasManyRecords = record.get(name);
				let hasManyRecordsSize = hasManyRecords.length;
				for (let i = hasManyRecordsSize - 1; i >= 0; i--) {
					this.rollback(hasManyRecords.objectAt(i));
				}
			} else if (descriptor.kind === 'belongsTo') {
				this.rollback(record.get(name));
			}
		});

		record.rollbackAttributes();
	}

**Comment by wecc** [comment]
I'm closing this as we're tracking dirtyness/rollback of relationships in https://github.com/emberjs/rfcs/pull/21
