### ISSUE TITLE
extractId breaking change in 1.13.5

### ISSUE THREAD

**Issue by simonjefford** [emberjs/data#3538]
#3477 just broke my custom serializer. It's a simple change, so this hasn't burnt *too* much of my time, but what I'm not understanding is why this change was merged when the discussion on the PR correctly pointed out that this would be a breaking change.

**Comment by wecc** [comment]
Hi @simonjefford. Sorry about that. It was identified as a breaking change but I think we simply figured since it was just introduced and undocumented we could get away with it.

Sorry it caused you problems though, really :(

**Comment by bmac** [comment]
I'm really sorry about that @simonjefford. The hope was that because `extractId` was never documented it wouldn't be considered public api. Unfortunately, I think reverting this the `extractId` change at this point would lead to more breakage then it solves. So I'm going to close this issue.
