### ISSUE TITLE
Assert that type is found when doing store.push

### ISSUE THREAD

**Issue by wecc** [emberjs/data#3542]
We should add an assert in `store._pushInternalModel` checking that `type` is found.

**Comment by Serabe** [comment]
`store.modelFor` [raises an `Ember.Error`](https://github.com/emberjs/data/blob/db1c1bd8be436ae1ca1249d97211942cf831feaf/packages/ember-data/lib/system/store.js#L1576) if no model could be found. What is the difference? Should the assert be in `store.modelFor`?
