### ISSUE TITLE
Support nested attributes in JSON API responses

### ISSUE THREAD

**Issue by devinus** [emberjs/data#3546]
According to https://github.com/json-api/json-api/blob/gh-pages/format/index.md#attributes- JSON API allows nested attributes:

> Complex data structures involving JSON objects and arrays are allowed as attribute values. However, any object that constitutes or is contained in an attribute MUST NOT contain a relationships or links member, as those members are reserved by this specification for future use.

**Comment by fivetanley** [comment]
By "nested attribute" do you mean a JS array or Object value? You can do this today by excluding an argument to DS.attr, e.g. `foo: DS.attr()`

**Comment by Baukereg** [comment]
Note that DS.attr() will actually cause trouble with the isDirty flag.

**Comment by rmharrison** [comment]
I used [nesting feature](https://github.com/lytics/ember-data-model-fragments#nesting) of model fragments via the addon [ember-data-model-fragments](https://github.com/lytics/ember-data-model-fragments). YMMV.

**Comment by runspired** [comment]
Relates to #1540 for `isDirty` calculations. Keeping both tickets as the other also poses a question for the more general problem of `123` vs `"123"` being considered dirty.

**Comment by sandstrom** [comment]
You can do this today with a custom transform, e.g.

```js
import { typeOf } from '@ember/utils';
import Transform from '@ember-data/serializer/transform';

export default Transform.extend({
  // Plain dict/hash/object

  deserialize(serialized) {
    if (typeOf(serialized) === 'object') {
      return Object.assign({}, serialized);
    } else if (serialized === null || serialized === undefined) {
      return null;
    } else {
      throw new Error(`Could not deserialize plain object`);
    }
  },

  serialize(deserialized) {
    if (typeOf(deserialized) === 'object') {
      return Object.assign({}, deserialized);
    } else if (deserialized === undefined || deserialized === null) {
      return null;
    } else {
      throw new Error(`Could not serialize plain object`);
    }
  },
});

```

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? If it isn't, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.
