### ISSUE TITLE
[Bug] Polymorphic won't work

### ISSUE THREAD

**Issue by marcemira** [emberjs/data#3547]
Hello, I'm trying to work with polymorphic relations, the problem seems to be that it ignores the payload "type" attribute, It will use the payload primary key as modelType instead.

Here is a JsBin: http://emberjs.jsbin.com/wilavu/edit?html,js,output

Let me know what am I doing wrong, if is not a bug I'm really sorry, please close this issue.

Thanks

**Comment by bmac** [comment]
This is a bug. 

It looks like the issue is the serializer is calling `normalize` using the polymorphic superclass's serializer instead of the serializer for the specific record type that is being returned.

https://github.com/emberjs/data/blob/master/packages/ember-data/lib/serializers/rest-serializer.js#L242

**Comment by marcemira** [comment]
:+1:  thanks!

**Comment by SeyZ** [comment]
:+1:

**Comment by marcemira** [comment]
What about this [RFCS](https://github.com/emberjs/rfcs/blob/polymorphism/text/0000-find-polymorphism.md)?

**Comment by wecc** [comment]
@marcemira I think that RFC will solve this bug. And I suspect it will be very hard to fix until then. We can make it use the correct serializer but that's only one part of it.

**Comment by marcemira** [comment]
@wecc In order to continue working on my app, can I do something to patch it until then? What would you suggest me to do?. Thanks man

**Comment by wecc** [comment]
Hm, I though this was about doing `store.findAll('base-type')` with polymorphic results... polymorphic relationships should work. We should be able to solve this... I'm surprised that we don't have tests for this already.

**Comment by marcemira** [comment]
Hello @wecc can I help in any way? How does the payload is supposed to look like today(assuming it's working)?. I think it's has something to do with ED not serializing the payload when it doesn't represent a primary type, It just returns an empty serialized data... isn't that correct? Thanks
