### ISSUE TITLE
With createRecord. Am I supposed to parse through data.relationships.product.data.id?

### ISSUE THREAD

**Issue by krzkrzkrz** [emberjs/data#3548]
Using Ember Data JSONAPIAdapter.

An item has: `product_id`, `count`, `status`. When doing:

```  
item = this.store.createRecord('item');
  item.setProperties({
    product: product,
    count:   0
  });
  item.save();
```

Is it normal that the request creates the following payload to `http://localhost/api/v1/items` as `POST`:

```
{
  "data": {
    "attributes": {
      "count":  0,
      "status": null
    },

    "relationships":{
      "product": {"data":{"type":"products","id":"1619"}}
    },

    "type":"items"
  }
}
```

Which means, in the API, in order to assign the `Item` object/record with the `product_id`. I need to parse through `data.relationships.product.data.id`?

**Comment by IsaiahJTurner** [comment]
I was wondering this myself.

**Comment by wecc** [comment]
Hi! Yes, this is what the JSON API specification expects. See http://jsonapi.org/format/#crud-updating-resource-relationships for more details. It should not be `POST` though, it should be `PATCH`. Are you experiencing issues where Ember Data JSONAPIAdapter saves records using `POST`?

**Comment by krzkrzkrz** [comment]
Hi @wecc, no real issue. My main concern was whether the API should access `product_id` from `data.relationships.product.data.id`. From our chat on Slack, the answer was "yes" :+1:
