### ISSUE TITLE
Ghost data issue

### ISSUE THREAD

**Issue by thehydroimpulse** [emberjs/data#3551]
This is the second time I've had this issue, moving to ember-data 1.0.0-beta-18 fixed the issue, but now that I upgraded to 1.3.4 for Ember, I did the same with Ember data and it triggered again.

I have a simple list that loops on a collection of "Reps":

```hbs
<div class="reps-container">
  {{#each reps as |rep|}}
    <div class="user-profile list">

      {{#link-to 'app.user.overview' rep.user}}
      <div class="name">
        {{rep.firstName}} {{rep.lastName}}
      </div>
      {{/link-to}}

      <div class="profile">
        <ul>
          <li>
            <span class="stat">
              $0
            </span>
            <span class="type">
              Net MRR
            </span>
          </li>
        </ul>
      </div>
    </div>
  {{/each}}
</div>
```

And this is *exactly* how it renders with the broken versions:

<img width="476" alt="screenshot 2015-07-15 17 34 58" src="https://cloud.githubusercontent.com/assets/565790/8712297/f439fc4c-2b17-11e5-8552-bcd7e29e50ad.png">

The first and last names of reps should be rendering in the brighter red section. The ghost nature is the correct iterations on the array, and upon inspection (using the Ember Inspector), the models are loaded correctly from the server, the rendering seems to be the issue. Logging from the template produces `undefined`, but logging from JavaScript correctly logs the `InternalModel`

(While this could very well be an Ember exclusive bug, it's only happened with a specific Ember data version.) 

Thoughts?

Ember version: 1.3.4#release
Ember data version: 1.3.5

**Comment by jcope2013** [comment]
can you provide the javascript for how reps is populated?

**Comment by thehydroimpulse** [comment]
Here's my route where I query the reps:

```js
import Ember from 'ember';

export default Ember.Route.extend({
  model() {
    let team = this.session.get('currentUser.team.id');
    return this.store.query('rep', {
      team: team
    });
  },

  setupController(controller, model) {
    controller.set('reps', model.content);
  }
});
```

This all seems to work correctly (until it renders), I can successfully log the `model.content` and it returns a fully valid collection with all the right properties.

**Comment by thehydroimpulse** [comment]
I guess I was using storing `model.content` directly into my controllers (which worked on previous versions). Replacing them to store the RecordArray itself as the model fixes the issue!
