### ISSUE TITLE
findRecord options

### ISSUE THREAD

**Issue by btecu** [emberjs/data#3552]
According to the Ember Data 1.13 blog post, `findRecord` signature is `findRecord(type, id, options)`, however, it looks like no query params are being passed.

It would be very useful if we could pass query params with `findRecord`.

**Comment by wecc** [comment]
`options` for `findRecord` does not take query params. You can use `store.query()` and `store.queryRecord()` to pass query params.

`options` do however take `adapterOptions` that you can access on the snapshot in your adapter.

**Comment by btecu** [comment]
`queryRecord` sounds good, but it doesn't seem to take an id. Shouldn't it?

**Comment by wecc** [comment]
You could probably pass an ID as part of the query, but it's not required since `queryRecord` can be used to fetch a single record by slug for example.

**Comment by btecu** [comment]
Are we supposed to implement `queryRecord`?
I'm getting *You tried to make a query but your adapter does not implement `queryRecord`*.

**Comment by wecc** [comment]
It's unfortunately missing, https://github.com/emberjs/data/issues/3514

**Comment by btecu** [comment]
`findRecord` doesn't pass query params because it would be too difficult to keep track of query param changes for caching purposes, right?
