### ISSUE TITLE
errorsArrayToHash and errorsHashToArray functions looking for data/attributes/ instead of /data/attributes (missing trailing slash?)

### ISSUE THREAD

**Issue by jcope2013** [emberjs/data#3557]
"pointer: a JSON Pointer [RFC6901] to the associated entity in the request document [e.g. "/data" for a primary data object, or "/data/attributes/title" for a specific attribute]."

http://jsonapi.org/format/#errors-processing

https://github.com/emberjs/data/blob/master/packages/ember-data/lib/adapters/errors.js#L125
https://github.com/emberjs/data/blob/master/packages/ember-data/lib/adapters/errors.js#L145

**Comment by tchak** [comment]
I am sorry I don't understand the problem here. Can you explain a bit more?

**Comment by jcope2013** [comment]
@tchak it is just a slight change ```/``` is missing before data according to the spec

errorsHashToArray currently sets pointer to this 

```
source:  {
          pointer: `data/attributes/${key}`
         }
```

but according to the spec (http://jsonapi.org/format/#errors-processing) it should instead look like this

```
source:  {
          pointer: `/data/attributes/${key}`
         }
```

https://github.com/emberjs/data/blob/master/packages/ember-data/lib/adapters/errors.js#L125

**Comment by tchak** [comment]
Oh right. I agree. Will fix it.
