### ISSUE TITLE
Cannot read property '_internalModel' of undefined when resolve belongsTo relationship

### ISSUE THREAD

**Issue by jpoiri** [emberjs/data#3566]
Hi there,

I am getting an "Cannot read property '_internalModel'"  error only when I am trying to resolve a belongsTo relationship between to models. 

For example, when I load just the benefit model by itself there is no problem:

import Ember from 'ember';
export default Ember.Route.extend({
    model: function() {
        return this.store.findAll('benefit');
    }
});

![image](https://cloud.githubusercontent.com/assets/6857740/8778887/b014fca2-2ed6-11e5-9528-fe8688571b6e.png)

However, when I load the league model that reference a benefit object I get "Cannot read property '_internalModel'"  error and the benefit model only has the key filled.

import Ember from 'ember';
export default Ember.Route.extend({
    model: function() {
        return this.store.findAll('league');
    }
});

![image](https://cloud.githubusercontent.com/assets/6857740/8778949/0f092508-2ed7-11e5-83df-bfd13367c9fe.png)

I have defined a serializer for both the benefit and the league to deal with API responses. I am new to Ember Data, is there something I am configuring wrong?

Benefit Model:

import DS from 'ember-data';
export default DS.Model.extend({
    policy: DS.attr('string')
});

League Model:

import DS from 'ember-data';
export default DS.Model.extend({
    admins: DS.hasMany('user'),
    max_team_size: DS.attr('number'),
    steps_per_point: DS.attr('number'),
    name: DS.attr('string'),
    name_fr: DS.attr('string'),
    description: DS.attr('string'),
    description_fr: DS.attr('string'),
    slogan: DS.attr('string'),
    slogan_fr: DS.attr('string'),
    lingual: DS.attr('string'),
    avatarUrl: DS.attr('string'),
    benefit: DS.belongsTo('benefit', {async: true})
});

Benefit Serializer:

import DS from 'ember-data';
export default DS.RESTSerializer.extend({
    primaryKey: 'benefit_id',
    isNewSerializerAPI: true,
    attrs: {
        policy: {
            key: 'policy_id'
        }
    }
});

League Serializer:

import DS from 'ember-data';
export default DS.RESTSerializer.extend(DS.EmbeddedRecordsMixin, {
	primaryKey: 'league_id',
	isNewSerializerAPI: true,
    attrs: {
        admins: {
            key: 'admin_list',
            embedded: 'always'
        },
		benefit: {
			key: 'benefit_id'
		}
    }
});

League JSON Response:

{
	"leagues": [{
		"league_id": 1,
		"admin_list": [],
		"max_team_size": 25,
		"steps_per_point": 100,
		"name": "name",
		"name_fr": null,
		"description": "Momentum was created to help you get moving and stay motivated. \r\n\r\nThe goal? Make physical activity part of your daily routine, whether it’s walking, cycling or taking a fitness class—whatever moves you. \r\n\r\nThe result? A healthier you—and the chance to come out on top in the  Momentum standings.(fr)\r\n\r\nTeam up and let’s go!(fr)",
		"description_fr": null,
		"slogan": "The best project you'll ever work on is you.(fr)",
		"slogan_fr": null,
		"lingual": null,
		"avatarUrl": "/avatar/league/cross.jpg",
		"benefit_id": 3
	}]
}

Benefit JSON response:

{"benefit_id":3,"policy_id":"0000239000"}

**Comment by trianglegrrl** [comment]
@jpoiri what ended up being your problem here?

**Comment by constantm** [comment]
Would like to know as well? I'm running into the same issues with AMS.

**Comment by pangratz** [comment]
Can you post a JSBin / Ember Twiddle demonstrating the issue?

**Comment by constantm** [comment]
Okay so my issue was caused by the [AMS Ember addon](https://github.com/ember-data/active-model-adapter) while on the Rails side, AMS was set to use JSON API. Not sure what the exact cause was, but I now have JSON API set up on both Ember and Rails and it works just fine.

**Comment by pangratz** [comment]
Glad to hear!
