### ISSUE TITLE
cannot install ember-data#1.13.6 from bower

### ISSUE THREAD

**Issue by oriSomething** [emberjs/data#3573]
<img width="835" alt="screen shot 2015-07-22 at 12 54 26" src="https://cloud.githubusercontent.com/assets/2685242/8822834/d0f15db2-3070-11e5-838b-11a6c625d828.png">
<img width="531" alt="screen shot 2015-07-22 at 12 54 18" src="https://cloud.githubusercontent.com/assets/2685242/8822833/d0ed9916-3070-11e5-8361-11f21d6f5c91.png">

**Comment by fpauser** [comment]
Seems to be fixed right now, version 1.3.6 was released 1 minute ago: https://github.com/components/ember-data/blob/master/bower.json

**Comment by wecc** [comment]
Confirm, has been published now!
