### ISSUE TITLE
Have this.store.pushPayload(type, payload) return records

### ISSUE THREAD

**Issue by bcardarella** [emberjs/data#3576]
It would be a nice convenience if `pushPayload` returned the resulting records. Otherwise we have to go through the manual process of normalizing the payload and using `this.store.push`

**Comment by bcardarella** [comment]
Here is a bit more about my use case:

We are using `torii` for authentication. In the torri adapter we make a `$.get` request to our backend's `sessions` endpoint. The response comes back in the json-api format. The torii adapter needs to return the account model as the currentUser to indicate the authenticated state. We get the raw payload as the response from the server so we need a way to deserialize/normalize that data, get it into the store, and retrieve the record for telling torii that this is the currentUser.

`this.store.push` will return the record as we need but we have to go through the overhead of something like:

```js
let modelClass = this.store.modelFor('account');
let serializer = this.store.serializerFor('account');
let normalizedPayload = serializer.normalizeSingleResponse(this.store, modelClass, payload, null, true);
let account = this.store.push(normalizedPayload);
```

`this.store.pushPayload` will encapsulate all of that overhead but does not return any record:

```js
let account = this.store.pushPayload('account', payload);
account === undefined
```

If it is not desirable to break the current API (as this request would) then could we get some other convenience function to handle this use case?

**Comment by wecc** [comment]
This and #3576 seem very related.

**Comment by workmanw** [comment]
Bump. It seems odd to me that `store.push` returns "{DS.Model|Array} the record(s) that was created or updated." while `store.pushPayload` doesn't.

Looking at the code, it seems easy enough to update the store and serializers. Would a PR be accepted to fix this?

**Comment by karellm** [comment]
We ran into the same problem couple times in our app. It would be a really appreciated addition!

**Comment by sly7-7** [comment]
Closing since the PR was merged

**Comment by pangratz** [comment]
Cross-Linking to [RFC#161](https://github.com/emberjs/rfcs/pull/161), which addresses the problem raised in this issue.

**Comment by bbansalWolfPack** [comment]
any updates on this? facing the same issue because pushPayload does not return anything back. So how can I use normalized response?

**Comment by runspired** [comment]
@bbansalWolfPack we decided not to move forward with pushPayload return. We intend on deprecating `pushPayload`, and will eventually introduce an improved push API.

**Comment by jagthedrummer** [comment]
As best I can tell this seems to the currently suggested approach: https://www.emberjs.com/blog/2018/04/13/ember-3-1-released.html#toc_feature-flag-code-ds-pushpayload-return-code-4-of-4
