### ISSUE TITLE
How can one access a specific item in a RecordArray?

### ISSUE THREAD

**Issue by spruce** [emberjs/data#3578]
Currently I use this code:
```javascript
me.store.all('user').objectAtContent(0),
```
but `objectAtContent` is marked as private (http://emberjs.com/api/data/classes/DS.RecordArray.html#method_objectAtContent)

Is there a better way to do this?

**Comment by bmac** [comment]
[objectAt](http://emberjs.com/api/classes/Ember.ArrayProxy.html#method_objectAt) is the supported method for accessing an item at a specific index.

```js
me.store.all('user').objectAt(0)
```

**Comment by spruce** [comment]
Thanks.
