### ISSUE TITLE
Possible bug with ember$data$lib$system$store$$deserializeRecordId

### ISSUE THREAD

**Issue by villeneuve-michael** [emberjs/data#3581]
I upgrade this week to the latest version of ember/ember-data/ember-cli from a version that was like 9 months old ( I beleive it was 1.0.7beta). Needless to say it was a lot of work! 

Anyway, I had a trouble unserializing a pretty big response containing lots of embedded record (it's just too big for me to paste it, but the JSON was totally standard). I was receiving the following error :

```javascript
Error while processing route: catalogue.produits Assertion Failed: Passing classes to store methods has been removed. Please pass a dasherized string instead of undefined Error: Assertion Failed: Passing classes to store methods has been removed. Please pass a dasherized string instead of undefined
    at new Error (native)
    at Error.EmberError (http://localhost:4200/assets/vendor.js:24565:21)
    at Object._emberMetalCore.default.assert (http://localhost:4200/assets/vendor.js:14754:13)
    at ember$data$lib$system$store$$Service.extend.modelFor (http://localhost:4200/assets/vendor.js:79928:15)
    at ember$data$lib$system$store$$Service.extend._internalModelForId (http://localhost:4200/assets/vendor.js:79232:30)
    at ember$data$lib$system$store$$deserializeRecordId (http://localhost:4200/assets/vendor.js:80460:20)
    at http://localhost:4200/assets/vendor.js:80470:16
    at Array.map (native)
    at ember$data$lib$system$store$$deserializeRecordIds (http://localhost:4200/assets/vendor.js:80469:47)
    at http://localhost:4200/assets/vendor.js:80444:44
```
I digged threw the stack and found out that ember$data$lib$system$store$$deserializeRecordId was sending id.type to _internalModelForId and that it was undefined. My object was valid, but did not have "type". I look at the other parameters and found that "relationship" had access to the type and changing the parameter value fixed the possible bug. 

```javascript
    function ember$data$lib$system$store$$deserializeRecordId(store, key, relationship, id) {
      if (ember$data$lib$system$store$$isNone(id)) {
        return;
      }

      Ember.assert("A " + relationship.parentType + " record was pushed into the store with the value of " + key + " being " + Ember.inspect(id) + ", but " + key + " is a belongsTo relationship so the value must not be an array. You should probably check your data payload or serializer.", !Ember.isArray(id));

      //TODO:Better asserts
     // return store._internalModelForId(id.type, id.id); Current way
     return store._internalModelForId(relationship.type, id.id); My way
    }   
```

I have never submitted a pull request and I don't really feel confident enough to contribute (yet!). I'm sure there must have been a reason why it was this way.

Thanks alot for y'alls time. Ember is a kick ass project.

**Comment by villeneuve-michael** [comment]
Ok actually it did fix the error message but it did not hydrate the objects into the store. I kept digging and finally found the real solution.

I had to add my relationship to the RESTSerializer with the DS.EmbeddedRecordsMixin.

**Comment by igorT** [comment]
Hi, thanks for reporting an issue. Can you please submit a reproducible test case. You can use the jsbin in https://github.com/emberjs/data/blob/master/CONTRIBUTING.md or just write one in your ED fork

**Comment by villeneuve-michael** [comment]
Will do as soon as I got a minute this week.

**Comment by ewalti** [comment]
I also just bumped in to an issue with `ember$data$lib$system$store$$deserializeRecordId` using my django rest adapater. 

Specifically this bit:

```
else if (typeof id === 'object') {
  // hasMany polymorphic
  // Ember.assert('Ember Data expected a number or string to represent the record(s) in the `' + relationship.key + '` relationship instead it found an object. If this is a polymorphic relationship please specify a `type` key. If this is an embedded relationship please include the `DS.EmbeddedRecordsMixin` and specify the `' + relationship.key +'` property in your serializer\'s attrs object.', id.type);
  data[key] = store.recordForId(id.type, id.id);
}
```

According to the method, my `id` parameter is the embedded record, which doesn't have a `type` key. I can circumvent this by using: `key.type.typeKey` to get the `typeKey` for the model instance, which is then dispatched to `store.recordForId` which works.

**Comment by danielfc** [comment]
I'm still facing this problem with a `DS.belongsTo` relationship when using ember-data `2.1.0-beta.2`.

```js
    function ember$data$lib$system$store$$deserializeRecordId(store, key, relationship, id) {
      if (ember$data$lib$system$store$$isNone(id)) {
        return;
      }

      Ember.assert("A " + relationship.parentType + " record was pushed into the store with the value of " + key + " being " + Ember.inspect(id) + ", but " + key + " is a belongsTo relationship so the value must not be an array. You should probably check your data payload or serializer.", !Ember.isArray(id));

      //TODO:Better asserts
      return store._internalModelForId(id.type, id.id); // <------ id.type gets undefined
    }
```

I agree with @villeneuve-michael, this shouldn't be `relationship.type` instead of `id.type`?

**Comment by matomesc** [comment]
+1 i have the same issue.

Ember: 2.0.2
Ember Data: 2.0.0
jQuery: 2.1.4

My model:

```js
// extend base product model
export default Product.extend({
  options: DS.hasMany('option')
});
```

My serializer for the above model:

```js
export default DS.RESTSerializer.extend({
  attrs: {
    options: {
      deserialize: 'records', // expect embedded options when receiving JSON
      serialize: 'ids' // serialize options to ids when sending JSON
    }
  }
});
```

Getting the following stack error:

```
Error: Assertion Failed: Passing classes to store methods has been removed. Please pass a dasherized string instead of undefined
    at new Error (native)
    at Error.EmberError (https://dev.ogpo.com:8000/static/store/assets/app.js?shop=options-products.myshopify.com:24465:21)
    at Object._emberMetalCore.default.assert (https://dev.ogpo.com:8000/static/store/assets/app.js?shop=options-products.myshopify.com:14605:13)
    at ember$data$lib$system$store$$Service.extend.modelFor (https://dev.ogpo.com:8000/static/store/assets/app.js?shop=options-products.myshopify.com:71962:15)
    at ember$data$lib$system$store$$Service.extend._internalModelForId (https://dev.ogpo.com:8000/static/store/assets/app.js?shop=options-products.myshopify.com:71319:30)
    at ember$data$lib$system$store$$deserializeRecordId (https://dev.ogpo.com:8000/static/store/assets/app.js?shop=options-products.myshopify.com:72407:20)
    at https://dev.ogpo.com:8000/static/store/assets/app.js?shop=options-products.myshopify.com:72417:16
    at Array.map (native)
    at ember$data$lib$system$store$$deserializeRecordIds (https://dev.ogpo.com:8000/static/store/assets/app.js?shop=options-products.myshopify.com:72416:18)
    at https://dev.ogpo.com:8000/static/store/assets/app.js?shop=options-products.myshopify.com:72391:44
```

**Comment by wecc** [comment]
@danielfc @matomesc Would any of you be able to create a minimal JSBin or Ember Twiddle demonstrating the issue? Would help troubleshooting a lot.

**Comment by matomesc** [comment]
Hey @wecc I've reproduced this issue in the latest canary build on [jsbin](http://emberjs.jsbin.com/qozeleguwo/1/edit?html,js,output) (check the console output)

**Comment by benoittgt** [comment]
I'm having the same issue using @matomesc similar implementation with ED 2.0.0

**Comment by chrsvl** [comment]
Yep, me too :(

**Comment by benoittgt** [comment]
@ewalti does you implementation fix this error ?

**Comment by wecc** [comment]
@matomesc Thanks! Looks like your serializer was missing the `EmbeddedRecordsMixin`, here's a modified working JSBin: http://emberjs.jsbin.com/ceyabu/1/edit?html,js,output

**Comment by benoittgt** [comment]
Fixed for me too. Thanks @wecc :clap:

**Comment by matomesc** [comment]
Haha thanks @wecc!

**Comment by pangratz** [comment]
@danielfc @villeneuve-michael @ewalti can you post your serializer definition and a sample JSON payload, with which you run into this issue?

**Comment by chrisccerami** [comment]
Is there any progress on this issue?

**Comment by danielfc** [comment]
@pangratz it's working for me, sorry for the delayed response.

**Comment by fivetanley** [comment]
@chrisccerami Have you tried including the EmbeddedRecordsMixin as listed above? What versions of Ember and Ember Data are you using?

**Comment by pangratz** [comment]
@danielfc no problem; glad it works for you! Do you recall the solution to your problem?

**Comment by danielfc** [comment]
not exactly, but it was something related to the serialization. the API was written in java so it was a little bit different from the convention ember expects, by default.

**Comment by pangratz** [comment]
kk, thanks for the heads up @danielfc
