### ISSUE TITLE
Relative paths in links relationship

### ISSUE THREAD

**Issue by wolodarsky** [emberjs/data#3583]
Using ember-data 1.13.6 and the JSONAPIAdapter,  relative paths in links relationships behave as described in #1365.

Is this desired behavior for the JSONAPIAdapter?  I would be happy to write some documentation if so.

Could not find a prescription of this behavior in the [json api](http://jsonapi.org/format/#fetching-relationships) spec (may have missed it).

**Comment by bmac** [comment]
Hi @wolodarsky. I believe this is the desired behavior for the JSONAPIAdapter. Writing some documentation describing the behavior would be very appreciated.
