### ISSUE TITLE
Add API docs and info in the guides about `ds-extended-errors`

### ISSUE THREAD

**Issue by tchak** [emberjs/data#3585]
see #3493 for an example of confusion

**Comment by zyllorion** [comment]
Please also document how to handle timeouts from requests. E.g. hook, retry 3 times and redirect to an error page.

So far the only documentation I've ever been able to find is around 422 field level validations, not 4xx and 5xx errors or timeouts in the newer ED builds.

Thank you.

**Comment by zyllorion** [comment]
Please also document how to handle timeouts from requests. E.g. hook, retry 3 times and redirect to an error page.

So far the only documentation I've ever been able to find is around 422 field level validations, not 4xx and 5xx errors or timeouts in the newer ED builds.

Thank you

**Comment by locks** [comment]
I'm closing this since https://github.com/emberjs/data/pull/4632 has been merged for a while. Reopen if I missed something!
