### ISSUE TITLE
1.13.5 removeObjects on hasMany relationship doesn't work

### ISSUE THREAD

**Issue by dmagunov** [emberjs/data#3589]
Coffee
```coffeescript
parent.get('children_ids').then (childrens)=>
  # doesn't work
  parent.get('children_ids').removeObjects(childrens)
  #works
  childrens.forEach (children)->
    parent.get('children_ids').removeObject(children)
```

**Comment by pangratz** [comment]
I cannot reproduce this using Ember 1.13.x and Ember-Data 1.13.x, see [this ember-twiddle](https://ember-twiddle.com/c42116227464433a868ebc9647a4291b?fileTreeShown=false&numColumns=3&openFiles=routes.application.js%2Cmodels.person.js%2Ctemplates.application.hbs).

Feel free to reopen this issue if you can reproduce this.

Thanks!
