### ISSUE TITLE
Deprecated method store.findQuery documented as @method query

### ISSUE THREAD

**Issue by codefox421** [emberjs/data#3597]
Both [`store.query`](https://github.com/emberjs/data/blob/v1.13.7/packages/ember-data/lib/system/store.js#L1099) and [`store.findQuery`](https://github.com/emberjs/data/blob/v1.13.7/packages/ember-data/lib/system/store.js#L1159) are documented as `@method query`, at least in v1.13.7.

This causes `store.findQuery` to show up as `store.query` in the api docs, and `store.query` to not show up at all. It also leads to the confusing message that "query is deprecated, use `store.query` instead" (paraphrased from http://emberjs.com/api/data/classes/DS.Store.html#method_query).

**Comment by wecc** [comment]
Should be fixed by #3591

**Comment by codefox421** [comment]
Yep. Didn't find that when I did a search, but I don't think I checked closed issues. My mistake. Thanks!
