### ISSUE TITLE
Serializer#normalizeResponse appears to not be in the API docs

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/data#3598]
it appears documented in the code:

https://github.com/emberjs/data/blob
/3c6bc3356ffaa0d052db9ccd43e96fef11042f8a/packages/ember-data/lib/system/serializer.js#L38-L52

**Comment by wecc** [comment]
We forgot `/*` => `/**` when releasing 1.13

**Comment by stefanpenner** [comment]
it does not seem to appear in https://github.com/emberjs/website/blob/master/data/data_api.yml#L4381

**Comment by stefanpenner** [comment]
@wecc ah awesome.

**Comment by stefanpenner** [comment]
https://github.com/emberjs/data/pull/3600

**Comment by stefanpenner** [comment]
lol @bmac beat me.
