### ISSUE TITLE
Object-level errors are ignored

### ISSUE THREAD

**Issue by dustinfarris** [emberjs/data#3602]
There should be support for object-level validation errors if pointer is `/data`.

In ember-django-adapter we want to support a response from our backend which may look like:

```json
{"non_field_errors": ["Your first name and last name cannot begin with the same letter"]}
```

This is for errors that involve multiple fields, or for non-field-level errors.

[The adapter translates this](https://github.com/dustinfarris/ember-django-adapter/blob/master/addon/adapters/drf.js#L120) into JSON API compliant objects for DS.InvalidError, for example:

```js
{
  source: { pointer: "/data" },
  detail: "Your first name and last name cannot begin with the same letter",
  title: "Validation Error"
}
```

Our use of `/data` comes from the JSON API [error object spec](http://jsonapi.org/format/#error-objects) example that reads:

> pointer: a JSON Pointer [RFC6901] to the associated entity in the request document [e.g. __"/data" for a primary data object__, or ...

Current ED implementation does not seem to do anything with this.

In #3524, @tchak mentions the possibility of a baseErrorKey.  Would that work for /data pointers as well?  Would this be the usage?:

```hbs
{{#each post.errors.base as |error|}}
{{error.message}}
{{/each}}
```

**Comment by adam-knights** [comment]
@bmac @tchak Any update on this? Is https://github.com/emberjs/data/pull/3859 expected to resolve this or would this need to be a separate fix? If I return anything from my api with the pointer '/data' it is lost by the time I interact with `record.errors`.
