### ISSUE TITLE
Some public methods should assert for reasonable return values

### ISSUE THREAD

**Issue by mike-north** [emberjs/data#3603]
@stefanpenner and I were just helping someone debug some ember-data 1.13.7 serializer stuff, and it turned out that their `normalizeResponse` method was calling `this._super....` at the end (returning nothing) instead of returning a valid JSON-API document. 

Although this is obviously a developer mistake, in dev mode, it would be nice to validate that valid things are returned, especially when dealing with methods like `normalizeResponse` that are designed for developers to customize.

Potentially, the following could be validated to at least return something truthy

* normalizeResponse
* normalizeFindRecordResponse
* normalizeQueryRecordResponse
* normalizeFindAllResponse
* normalizeFindBelongsToResponse
* normalizeFindHasManyResponse
* normalizeFindManyResponse
* normalizeQueryResponse
* normalizeCreateRecordResponse
* normalizeDeleteRecordResponse
* normalizeUpdateRecordResponse

**Comment by bmac** [comment]
This sounds like a great idea @truenorth. Would you have time to work on a pr for this?

**Comment by wecc** [comment]
Agree, :+1: 

All of the methods mentioned would go through `normalizeResponse`. This is the only method called by the store and it's done using a `normalizeResponseHelper` [here](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/store/serializer-response.js#L18). Should be pretty easy to assert it's an object and contains `data`, `errors` or `meta` (according to the spec).

**Comment by truenorth** [comment]
Yeah I could take this on. @stefanpenner suggests validating a JSON-API document as

* an object
* has at least one key

It's probably easier to validate more after we see what this looks like.

**Comment by stefanpenner** [comment]
> has at least one key

at-least a data key

**Comment by wecc** [comment]
> at-least a data key

a `data` key is not required. `data`, `errors` or `meta` is required.
