### ISSUE TITLE
`DS.BuildURLMixin#urlForFindRecord` overrides `DS.BuildURLMixin#urlForFind` in docs

### ISSUE THREAD

**Issue by codefox421** [emberjs/data#3606]
DS.BuildURLMixin#urlForFindRecord is [mistakenly marked `@method urlForFind`](https://github.com/emberjs/data/blob/v1.13.7/packages/ember-data/lib/adapters/build-url-mixin.js#L123), so DS.BuildURLMixin#urlForFind is [improperly documented (and not marked as deprecated)](http://emberjs.com/api/data/classes/DS.BuildURLMixin.html#method_urlForFind) in the API documentation.

**Comment by wecc** [comment]
Nice catch, would you like to submit a PR fixing it?
