### ISSUE TITLE
[JSONAPI] Not respecting  Links

### ISSUE THREAD

**Issue by kasperhelweg** [emberjs/data#3611]
Given a payload such as 

    {
    ...,
        "included": [
            {
                "attributes": {
                    "email": "email@example.com"
                },
                "id": "2",
                "links": {
                    "self": "http://example.com/api/parent/1/location"
                },
                "type": "locations"
            },
         ...
        ]
    }

calling `reload( )` on the "included model" results in a GET request to 

    http://example.com/api/locations/2

I would expect a request for: 

    http://example.com/api/parent/1/location

**Comment by wecc** [comment]
Confirm, `self` links are not yet implemented in Ember Data.

**Comment by wecc** [comment]
I'm closing this as we're tracking relationship `self` links in #2905
