### ISSUE TITLE
Status of store.pushPayload

### ISSUE THREAD

**Issue by jevanlingen** [emberjs/data#3612]
I am in the middle of updating to the latest versions of Ember, Ember Data, Ember CLI etc. As stated by @wecc at [issue 3405 | comment-116880748](https://github.com/emberjs/data/issues/3405#issuecomment-116880748) the `store.pushPayload(modelName, payload)` will continue to work as is.

But if I use that function, I get a deprecated warning (having set `isNewSerializerAPI` to `true`). After reading the [code](https://github.com/emberjs/data/blob/v1.13.7/packages/ember-data/lib/serializers/rest-serializer.js) I saw the following:

```javascript
pushPayload: function(store, rawPayload) {
  if (this.get('isNewSerializerAPI')) {
     _newPushPayload.apply(this, arguments);
      return;
  }
        
   .... //code for old serializer; also throws an Ember deprecate warning
}

function _newPushPayload(store, rawPayload) {
  let documentHash = {
    data: [],
    included: []
  }
      
  Ember.deprecate('`serializer.normalizePayload` has been deprecated. Please use `serializer.normalizeResponse` with the new Serializer API to modify the payload.', this.normalizePayload === JSONSerializer.prototype.normalizePayload);
  let payload = this.normalizePayload(rawPayload);

  .... // rest of the code
}
```

So my question is, is the `pushPayload` function really gonna last? And if so, why does both the `pushPayload` and the `_newPushPayload` throw a deprecation warning?

*N.B.* The deprecation warning for `_newPushPayload` has been added since Ember Data 1.13.5, see #3437.

**Comment by wecc** [comment]
The deprecation in `_newPushPayload` is for `normalizePayload`. It's `normalizePayload` that has been deprecated and the deprecation is only shown if you have overridden `normalizePayload`.

**Comment by jevanlingen** [comment]
Thank you very much for the clarification. Now I get it (I had indeed overridden the `normalizePayload`).

Problem solved :).
