### ISSUE TITLE
Enhancement: Copying a model to the database (ReplicableMixin)

### ISSUE THREAD

**Issue by joelalejandro** [emberjs/data#3613]
For an app I'm building, I've made this mixin:

https://gist.github.com/joelalejandro/22bd25bbf53d28e2643a#file-replicable-without-fragments-js

Basically it iterates through all of a model's relationships and attributes, copying its data to a new instance of the same model type.

I think it is an useful feature for easy entity replication, specially for models with lots of fields.

If enough interest arises, I'd be happy to make a PR.

Although I've tested it with an older version of Ember Data, I think it should work out-of-the-box with the current version as well.

**Comment by pangratz** [comment]
Hey @joelalejandro, I am triaging issues and I stumbled upon this quite old one. Sorry for the long overdue response 😔 

I don't think that replicating a model is something currently needed within ember-data core. I think it would be good if this is available via an addon, so folks can add this with a simple `ember install ember-data-replicate-model` or something...

I am inclined to close this issue, feel free to reopen if you think this is still something needed in core, so we can get a discussion going. Thanks!
