### ISSUE TITLE
Missing relationships between sideloaded entities with JSON API adapter

### ISSUE THREAD

**Issue by kalien** [emberjs/data#3617]
When using the new JSON API adapter relationships are not respected for entities in the "included" section i.e. for sideloaded entities. Let's say the response contains model1 as primary model and then model1 has references to model2 where model2 has references to model3. Both - model2 and model3 instances are present in the "included" section i.e. they are sideloaded.
The relationships between model1 and model2 are properly maintained however the relationships between model2 and model3 are missing. Tried with two different scenarios one-to-many and many-to-many. In both cases the relationships were not present.
These are the versions:
Ember: 1.13.5
Ember Data: 1.13.7
Ember CLI: 1.13.5

**Comment by Kilowhisky** [comment]
Sounds exactly like my issue: https://github.com/emberjs/data/issues/3614

**Comment by wecc** [comment]
I've written a reply on #3614 that I think would apply to this issue too.

**Comment by kalien** [comment]
I am aware of #3614. In case I do not provide references from both sides then none of the relationships would appear. Even model1 to model2. Once I provide info at all ends then the relationships between model1 and model2 are visible (as mentioned above) however the relationship model2 to model3 is still missing. Looks like when relationships touch models in the "included" section only then they are not properly handled. I think the two tickets cover two different problems (... or at least two different manifestations of the same root problem)

**Comment by wecc** [comment]
Got it. Did you look at the JSBin? This one: http://emberjs.jsbin.com/surulu/edit?html,js,output

I'm only providing relationships on "one" side and have `author` as primary data and both `book` and `chapter` included. Relationships seem to be setup correctly.

Would you be able to provide another JSBin demonstrating the issue?

**Comment by kalien** [comment]
This JSBin works fine. I also modified it to match precisely the relationships I have in my app and it still works fine. However in my application the model2-model3 relationships are missing. I also tried with Ember Data 1.13.4 i.e. with the version from the JSBin (hoping for easy to catch regression in Ember Data) but still no luck. I can't provide easy to reproduce JSBin for the problem I have. 
If I have time I will debug the framework and try to find out why model1-model2 is present but model2-model3 is not.

**Comment by kalien** [comment]
I think I found the root cause. Please take a look at this JSBin http://emberjs.jsbin.com/cotepe/edit?html,js,output 
Note that I renamed "Book" to "AuthorBook". In such cases "extractRelationships" is not able to properly determine the property that holds the relationship(s). 
Very likely both tickets #3614 and this one have the same root cause.

**Comment by wecc** [comment]
The `JSONAPISerializer`expects **dasherized, plural** types and **dasherized** attribute/relationship names by default. Change your payload to:

```
...
relationships: {
  'author-books': {
    data: [
      { type: 'author-books', id: '1' }
    ]
  }
}
...
```

Or, if you want to use something else you can override `modelNameFromPayloadKey`, `payloadKeyFromModelName`, `keyForAttribute` and/or `keyForRelationship` to change the default behavior.

**Comment by kalien** [comment]
I tried dasherizing the types and property names but I could not make the JSBin work. Could you please clone the JSBin and modify it so it works but please keep the model name "AuthorBook" so it needs dasherizing.
Thanks.

**Comment by wecc** [comment]
See http://emberjs.jsbin.com/qefexo/edit?html,js,output

**Comment by kalien** [comment]
Thanks! My bad. I was too focused on the JS section in the JSBin and I didn't realize I had forgotten to change {{#each author.books as |book|}} to {{#each author.authorBooks as |book|}}
I will adjust the serializers/deserializers in my app and confirm that the relationships are respected there as well.

**Comment by kalien** [comment]
All good. The app is fine as well. Thanks for the support!

**Comment by wecc** [comment]
Glad to hear! Closing this.
