### ISSUE TITLE
[bug] When a record doesn't have the key for polymorphic relationship, an assertion error is triggered.

### ISSUE THREAD

**Issue by Robdel12** [emberjs/data#3630]
When a record doesn't have the key for polymorphic relationship, an assertion error is triggered. This is not the case for non-polymorphic relationships.

Example payload:

```js
  {
    books: [
      { id: 1, title: 'Tom Sawyer'},
      { id: 2, title: 'A Farewell To Arms'},
      { id: 3, title: 'The Old Man And the Sea'},
      { id: 4, title: 'The Shining'},
      { id: 5, title: 'The Stand'},
      { id: 6, title: 'The Long Walk'}
    ],
    authors:[
      { id: 1, name: "Mark Twain", book_ids: [1] },
      { id: 2, name: "Ernest Hemingway", book_ids: [2, 3] },
      { id: 3, name: "Stephen King", book_ids: [4, 5, 6]}
    ]
  }
```

In this case, the Author `hasMany` users, but the key (`users`) is not present. You can see the JSBin for more details on the model definition.

Example JSBin: http://emberjs.jsbin.com/tonevazave/3/edit?html,js,output

The assertion is triggered here: https://github.com/emberjs/data/blob/v1.13.7/packages/ember-data/lib/system/store/serializer-response.js#L130

If the key isn't present in the payload (it is extracted here https://github.com/emberjs/data/blob/v1.13.7/packages/ember-data/lib/system/store/serializer-response.js#L101), it will be undefined. The lack of the key being present hasn't caused any issues in any previous releases of Ember Data. 

It seems like this will affect master as well: https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/store/serializer-response.js#L153

**Comment by Robdel12** [comment]
This only seems to affect the active model serializer. We can open an issue there.

**Comment by wecc** [comment]
Thanks for the awesome bug report @Robdel12!

It seems [`normalizeRelationships`](https://github.com/emberjs/data/blob/v1.13.7/packages/activemodel-adapter/lib/system/active-model-serializer.js#L272-L301) in `ActiveModelSerializer` does not check if a relationships are present in the payload before it tries to normalize it. [This](https://github.com/emberjs/data/blob/v1.13.7/packages/activemodel-adapter/lib/system/active-model-serializer.js#L294) causes it to set the relationship to `undefined` in the payload, which in turn causes the deprecation.

**Comment by wecc** [comment]
I'm unable to replicate using the new Serializer API (`isNewSerializerAPI: true`), which makes sense since it uses `extractRelationships` and in there we do check for existence in the payload.

**Comment by wecc** [comment]
This should be fixed in the [active-model-adapter](https://github.com/ember-data/active-model-adapter) repo but most likely patched in `release` here too.

**Comment by marcemira** [comment]
@wecc is this related to #3547 ?
