### ISSUE TITLE
Ember Data result sets don't play nicely with Lodash

### ISSUE THREAD

**Issue by johnhamelink** [emberjs/data#3632]
Hey there,

I was looking for a way to group my ember model by a certain column - I attempted to use lodash to do this, but lodash doesn't seem to be able to grok the resultset (it can't find `get` on each element):

``` javascript
import Ember from 'ember';
import DealAndTimeFilterable from '../../mixins/deal-and-time-filterable';
import _ from "npm:lodash";

export default Ember.Controller.extend(DealAndTimeFilterable, {
  groupedModel: Ember.computed('model.@each.scheme.id', function(){
    let model = this.get('model');
    return _.groupBy(model, function (n) {
      return n.get('scheme.id');
    });
  })
});
```

I was looking for an alternative on the Ember slack group, but I was told that this was most likely a bug in ember-data.

Best,
JH

**Comment by bcardarella** [comment]
Some additional context: with the effort in Ember itself to reduce its Array prototypes in favor of reliance on external libraries like lodash it would stand to reason that Ember Data's RecordArray class should work with these libraries.

**Comment by fivetanley** [comment]
I don't know if this is something we can implement performantly. AFAIK, lodash just uses the length property and then uses property accessors `[]` to do its operations. We'd have to use `Object.defineProperty` to achieve something similar in RecordArray.

As a workaround, you can use `.toArray()` and those produce normal JavaScript arrays that should work gracefully with lodash.

**Comment by locks** [comment]
Closing as a possible resolution was given by @fivetanley. Feel free to re-open in case of new developments!

**Comment by bcardarella** [comment]
@locks is there a link to a PR or discussion for reference on the path forward?

**Comment by locks** [comment]
@bcardarella I was referring to using `.toArray()`, which I completely acknowledge is a bandaid solution. Relatedly, there has been a lot of activity in the internals of Ember Data and I believe the team has some plans that intersect this issue, but you should confirm with them ^_^;

**Comment by bcardarella** [comment]
@locks ok, thank you :)
