### ISSUE TITLE
ember-data in 2.0.0 beta causes addons to fail to load modules

### ISSUE THREAD

**Issue by BryanCrotaz** [emberjs/data#3634]
Full example at https://github.com/BryanHunt/ember-split-view/pull/29

Works in release, fails in beta

When it fails, we get this error in vendor source:
```
import { keysFunc, create } from "ember-data/system/object-polyfills";
var EmberError = Ember.Error;  <==== Error here
var forEach = Ember.ArrayPolyfills.forEach;
var SOURCE_POINTER_REGEXP = /^\/?data\/(attributes|relationships)\/(.*)/; /**
```
Error is `Uncaught TypeError: Cannot read property 'forEach' of undefined`

This causes the addon test to fail:

```
not ok 15 PhantomJS 1.9 - SplitViewComponent: it renders
    ---
        actual: >
            null
        message: >
            Error: Could not find module 'ember-split-view/components/split-view' imported from 'dummy/components/split-view'
        Log: |
    ...
```

**Comment by BryanCrotaz** [comment]
Confirmed that removing `ember-data` from dependencies in addon makes addon's tests work in beta and canary

**Comment by stefanpenner** [comment]
@BryanCrotaz you need to also use ember-data beta

**Comment by stefanpenner** [comment]
https://github.com/emberjs/data/pull/3652 will fix this

**Comment by BryanCrotaz** [comment]
Great

**Comment by bmac** [comment]
https://github.com/emberjs/data/pull/3652 has been merged and this issue is now fixed.
