### ISSUE TITLE
complex InternalModel attributes may want to become lazy

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/data#3644]
* https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/model/internal-model.js#L51
* https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/model/internal-model.js#L56-L58
* https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/model/internal-model.js#L90

**Comment by stefanpenner** [comment]
some more details.

currently we have:

```js
export default function InternalModel(type, id, store, container, data) {
  // ...
  this._data = data || new EmptyObject();
  this._attributes = new EmptyObject();
  this._deferredTriggers = [];
  this._attributes = new EmptyObject();
  this._inFlightAttributes = new EmptyObject();
  this._relationships = new Relationships(this);
  //..
}
```

If for complex attributes that not every InternalModel uses upfront, we made them lazy. 

First step, shape the object:

```js
export default function InternalModel(type, id, store, container, data) {
  // ...
  this._data = data || undefined;
  this._attributes = undefined;
  this._deferredTriggers = undefined;
  this._attributes = undefined;
  this._inFlightAttributes = undefined;
  this._relationships = undefined;
  //..
}
```

then make accessors for each property, something like that.

```js
InternalModel.prototype.getData = function() {
  if (this._data) { return this._data;}
  return (this._data = new EmptyObject());
};
```

Then update internal usage accordingly.

We can mitigate unused early allocations.

**Comment by pangratz** [comment]
Closing due to the work done by @runspired in #4562 🚀
