### ISSUE TITLE
jsonapi serializer save

### ISSUE THREAD

**Issue by sebyx07** [emberjs/data#3645]
Records get saved with type dasherized even if i specify in the application serializer.

`
 keyForAttribute: function(key) {
    return Ember.String.camelize(key);
  }
`

I have no problem loading data, but the saving is problem for the server

ex:

from server 
`
  { data: {type: 'userNotifications'}}
`

from client

`
  { data: {type: 'user-notifications'}}
`

**Comment by wecc** [comment]
You should be able to override `modelNameFromPayloadKey` and `payloadKeyFromModelName` to change the default behavior of the `type` formatting.

**Comment by sebyx07** [comment]
thanks did the job
`
  payloadKeyFromModelName: function(key){
    let camel = Ember.String.camelize(key);
    return Ember.String.pluralize(camel);
  }
`
