### ISSUE TITLE
pluralize, singularize helpers no longer available after inflector update

### ISSUE THREAD

**Issue by typeoneerror** [emberjs/data#3658]
I am getting an error after upgrading to latest ember data: 

`Uncaught Error: Assertion Failed: A helper named 'pluralize' could not be found`

Doesn't appear that the helper is being registered as it was previously based on this commit. 

https://github.com/stefanpenner/ember-inflector/commit/ca707a6ab43d72ad95b5f1c722bf48c3a5033dfe

**Comment by typeoneerror** [comment]
Seems to work again if I add ember-inflector to npm modules.

**Comment by bmac** [comment]
@typeoneerror what version of Ember Data are you using?

**Comment by typeoneerror** [comment]
@bmac 1.13.13

**Comment by bmac** [comment]
Thanks @typeoneerror. This is defiantly a regression.

**Comment by joebartels** [comment]
fwiw also issue on 1.13.15 . Do we know if this is fixed in 2.x versions?

**Comment by bmac** [comment]
I just tried this with Ember Data 2.6 and Ember CLI 2.6 and the issue appears to be fixed.
