### ISSUE TITLE
hasMany meta property not proxied

### ISSUE THREAD

**Issue by mike-post** [emberjs/data#3671]
So if I have a model that declares a hasMany relationhsip:

```
// models/stuff.js
export default DS.Model.extend({
  things: DS.hasMany('thing', { async: true })
});

// models/thing.js
export default DS.Model.extend({
  name: DS.attr('string'),
  owner: DS.belongsTo('stuff')
});
```

I can obviously iterate over the hasMany by using it directly:

```
<ul>
  {{#each stuff.things as |thing|}}
    <li>{{thing.name}}</li>
  {{/each}}
</ul>
```

But then when I want to access the meta object associated with that hasMany relationship, I have to switch to the content property:

```
<div>Page {{stuff.things.content.meta.currentPage}} of {{stuff.things.content.meta.totalPages}}</div>
```

It seems like the meta object for the hasMany relationship should be proxied or somehow made available so I can instead write:

```
<div>Page {{stuff.things.meta.currentPage}} of {{stuff.things.meta.totalPages}}</div>
```

Right now the API is inconsistent and unintuitive.

edit: I should mention this is with ember 2.0.0 and ember-data 2.0.0-beta.2

**Comment by sarus** [comment]
Ran into this same issue.  

```
    this.store.findRecord('book', params.id, {adapterOptions: {query: params}}).then((book) =>{
        let meta = book.get('chapters.content.meta'); //get('chapters.meta') doesn't work
    });
```

**Comment by wecc** [comment]
Would you be able to reproduce this issue in a JSBin or Ember Twiddle?

**Comment by sarus** [comment]
@wecc sure.  Is there an example anywhere of how to mock the json api response for the store?

**Comment by wecc** [comment]
@sarus: Great, thanks! There are a pre-configured JSBins available here: https://github.com/emberjs/data/blob/master/CONTRIBUTING.md#reporting-a-bug

**Comment by sarus** [comment]
Thanks wecc.  Not surprisingly I haven't been able to reproduce in my simplified fiddle.  Will keep playing around with it to see if I can recreate whatever it is I'm doing in my actual application.

**Comment by sarus** [comment]
@wecc Here is an example that illustrates the issue.  

http://emberjs.jsbin.com/viwurizule/1/edit?html,js,output

The key is that 'async' on the `hasMany` relationship has to be set to true (or not explicitly set to false).  In that case you can only access meta through `content`

```
    controller.set('meta', model.get('books.meta')); // doesn't work
    controller.set('meta_content', model.get('books.content.meta')); //works
```

**Comment by runspired** [comment]
You can access meta on async relationships at this time.
