### ISSUE TITLE
No way to requery linked relationships with different metadata

### ISSUE THREAD

**Issue by mike-post** [emberjs/data#3673]
Given a model ('stuff') with a hasMany relationship onto another model ('things'), if you have a large number of items on the hasMany side of the relationship then the guidance seems to be to use `links` in your response, like so:

````json
{
  "stuff": {
    "id": "123",
    "links": {
      "things": "/api/stuff/123/things"
    }
  }
}
````

It's then reasonable for the server to respond with only the first page of data (because there's a lot). As of ED 1.13, the meta object is attached to the hasMany relationship (so you can do things like `stuff.get('things').then(things => { return things.get('meta'); })`).  However, there's no way to tell the server to move to the next page (or change the filtering/sorting criteria etc).  Indeed, the private findHasMany function [doesn't pass query parameters along](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/adapters/rest-adapter.js#L524). This renders meta objects on relationships fairly limited in practical use.

I would expect either the ability specify the query params when getting the relationship (e.g., `stuff.get('things', { page: 2, filter: 'foo' })`) or some way to tell the store what I'm looking for (e.g., `store.find('things', owner: instanceOfStuff, { page: 2, filter: 'foo' })`).  Regardless of how I get there, I'd further expect the generated ajax call to build upon the one returned from the server (e.g., `/api/stuff/123/things?page=2&filter=foo`).

ember: 2.0.0
ember-data: 2.0.0-beta.2

**Comment by mdehoog** [comment]
Does this help? https://github.com/mdehoog/ember-data-has-many-query

**Comment by mike-post** [comment]
Thanks, I think that does help!

**Comment by pangratz** [comment]
Currently this isn't possible in core `ember-data`, but the addon by @mdehoog should help you here @mike-north.

I am triaging issues and closing this in favor of #3700.
