### ISSUE TITLE
store.push API documentation outdated

### ISSUE THREAD

**Issue by knownasilya** [emberjs/data#3687]
Still references passing a type, and nothing about the JSON API.

Looking at the JSON API the examples show plural types, but for ED it seems like singular types are needed.

**Comment by bmac** [comment]
See http://emberjs.com/api/data/classes/DS.Store.html#method_push for a specific example of outdated docs.

**Comment by Kuzirashi** [comment]
Resources to create pull request for this?

- http://emberjs.com/blog/2015/06/18/ember-data-1-13-released.html#toc_internal-format-change-to-json-api
- source code

anything else useful and specific to ember data?
