### ISSUE TITLE
destroyRecord fails for a new unsaved record if it is not valid

### ISSUE THREAD

**Issue by sergetab** [emberjs/data#3688]
After creating a new record with store.createRecord I might need to destroy it if user prefers not to save. If the new record is valid then destroyRecord deletes it (but the record still remains in the store???). But if the record is NOT valid then store is trying to make a DELETE request to the server. The url in this case is wrong, e.g. for a 'user' it makes a call to api/users/ without any id (new record doesn't have an id).
After some debugging  I think the problem is [here](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/store.js#L1318). 'currentState' in case of invalid record would be "root.deleted.inFlight", not 'root.deleted.saved'

**Comment by typeoneerror** [comment]
Just saw this behavior in 2.4.3. Call `save()` on a record. Server responds with 422 error. Then call `destroyRecord` and a DELETE call is made to `api/users`, not like `api/users/1`.

**Comment by pangratz** [comment]
@typeoneerror the bugfix from #4293 is available since `2.6`. Can you upgrade ember-data to that version and check if the error persists? Thanks!
