### ISSUE TITLE
Dynamically set DS.Model id's don't seem to be serialized in a createRecord POST request

### ISSUE THREAD

**Issue by acburdine** [emberjs/data#3694]
[JSBin example](http://emberjs.jsbin.com/tijuwoveyu/1/edit?html,js,console,output)

I was working on one of my applications and it appears, since ember-data 1.0.0-beta.19, dynamically set id's are no longer being serialized with a POST request.

In that JSBin example, the input field value is mapped directly to the model ID, and when "save" is clicked, the mocked request outputs the POST data. In Ember-Data version 1.0.0-beta.18, "id" is included. Switching it to any version above that (I tried release, beta, and canary versions of ember-data) results in the same issue.

I tried messing around with the internal ember-data code in my applications and as I was able to find out it has something to do with the internal model's ID not being set correctly before a save occurs.

If I did the model creation/save process wrong in the JSBin, I would appreciate feedback so that I can fix it in my real application.

**Comment by acburdine** [comment]
cc @bmac @fivetanley

**Comment by fivetanley** [comment]
I think we should be sending this. I don't think this is the happy path as the client has no idea what IDs have been taken, and it seems odd for the server to return a different one. That said, since this is a regression we should probably fix it.

**Comment by acburdine** [comment]
In theory, the server would return the same ID, unless the ID had to be sanitized for some reason. If the ID matched one already in the database, the server could return an invalid error. With this too, it makes the `{includeId: true}` option in the serializer pretty much useless.
