### ISSUE TITLE
Many-to-Many sends relationship in PATCH, One-to-Many does not

### ISSUE THREAD

**Issue by jebukowski** [emberjs/data#3695]
I have two models: user and enterprise. 
#### Many-to-Many:

user model:

```
export default DS.Model.extend({
  enterprises: DS.hasMany('enterprise'),
});
```

enterprise model:

```
export default DS.Model.extend({
  users: DS.hasMany('user'),
});
```

I create an enterprise record (called enterprise below) and have access to the current user saved record (called currentUser below). Then, when implementing the following code...

```
enterprise.get('users').addObject(currentUser); 
enterprise.save().then(savedEnterprise => {
  currentUser.get('enterprises').addObject(savedEnterprise);
  currentUser.save();
});
```

...there is an enterprise POST request that correctly creates the new enterprise; and there is a user PATCH request sent whose request payload includes "attributes" and "relationships" and all is fine and well.

However, with the One-to-Many relationship... 
#### One-to-Many:

user model: (same as before)

```
export default DS.Model.extend({
  enterprises: DS.hasMany('enterprise'),
});
```

enterprise model:

```
export default DS.Model.extend({
  owner: DS.belongsTo('user'),
});
```

...when using the following code...

```
enterprise.set('owner', currentUser);
enterprise.save().then(savedEnterprise => {
  currentUser.get('enterprises').addObject(savedEnterprise);
  currentUser.save();
});
```

...the enterprise POST requests works properly, like before; but the user PATCH request sent **does not** include "relationships" in its payload, which is very problematic. 

In both cases (Many-to-Many and One-to-Many) the Ember Inspector shows that Ember Data has the attribute and relationship information set correctly. It is only when the relationship is One-to-Many that the user PATCH request seems to ignore the relationship information from Ember Data. (One-to-One is also working properly in Ember Data and the PATCH, but was not included since this post is already long.)

Could this be an issue with Ember Data?

**Comment by wecc** [comment]
By default you have to save One-to-Many relationships by saving the record on the "many" side.

If you want to force serialization you can use the `attrs` property in your serializer and set `serialize: true`. See http://emberjs.com/api/data/classes/DS.JSONSerializer.html#property_attrs for more info.

Does that solve the issue?

**Comment by jebukowski** [comment]
I believe that I am saving the records on both "sides": enterprise.save() and currentUser.save().
(currentUser is a saved user record, so when it is saved once more the PATCH request is sent). Is this not what the code is doing?

No luck with the "force" serialization...

**Comment by bmac** [comment]
@jebukowski do you mind making a https://ember-twiddle.com/ or http://emberjs.jsbin.com/sarobu/1/edit?html,js,output demonstrating the issue?

**Comment by wecc** [comment]
ping @jebukowski

**Comment by rstudner** [comment]
I believe I am seeing this right now:
Model Objects:
```
customer-device.js
export default Model.extend({
  name: attr(),
  location: attr(),
  customer: belongsTo('customer', { inverse: 'customerDevices' }),
  vendorDevices: hasMany('vendor-device', { inverse: 'customerDevice' })
});
```
```
vendor-device.js
export default Model.extend({
  contactUrl: attr(),
  deviceType: attr(),
  vendorName: attr(),
  customer: belongsTo('customer', { inverse: 'vendorDevices' }),
  customerDevice: belongsTo('customer-device', { inverse: 'vendorDevices' }),
  vendorAlerts: hasMany('vendor-alert', { inverse: 'vendorDevice' })
});
```

when I do a customerDevice.save(); the patch body is:
```

{ data:
   { id: '32e94499-9916-4ee5-8128-75bff3e496f7',
     attributes: { name: 'fun_times', location: 'Reston, va' },
     type: 'customer-devices' 
    } 
 }
```

**Comment by jfbaquerocelis** [comment]
Hi everyone :smiley:, Just now I have the same problem. I've two models:

`models/route.js`
```javascript
export default DS.Model.extend({
  name: DS.attr('string'),
  shortName: DS.attr('string'),
  line: DS.attr('number'),
  board: DS.attr('string'),
  color: DS.attr({ defaultValue : { line : "", background : "", letter : "" } }),
  trips: DS.hasMany('trip')
});
```
`models/trip.js`
```javascript
export default DS.Model.extend({
  name: DS.attr('string'),
  orientation: DS.attr('number'),
  way: DS.attr('number'),
  points: DS.attr({ defaultValue : [] }),
  milestones: DS.hasMany('milestone'),
  route : DS.belongsTo('route'),
  polyline: DS.attr('string')
});
```
But, when I send the `.save()` action like this:

```javascript
actions : {
    save(model) {
      model.save()
      .then((trip) => {
        let route_id = trip.get('route').get('id');
        let route = this.store.peekRecord('route', route_id);

        route.get('trips').pushObject(trip);
        return route.save();
      })
      .then(() => {
        this.transitionToRoute('trips.index');
      })
    },
    cancel() {
      this.transitionToRoute('trips.index');
    }
  }
```

The **PATCH** request has not the `relationships` key and obviusly the `trip data` doesn't appear on my `route model` when the response come.

I don't know if I'm doing it wrong but I need help. Thanks :pray: :+1:

**Comment by jfbaquerocelis** [comment]
After a thousand tests, I could resolved it. Only set on `trips` property `{ inverse : null }`. :tada: :tada:

**Comment by runspired** [comment]
closing as this is a user-land specific serializer configuration.
