### ISSUE TITLE
JSONAPIAdapter - undefined properties with camelcased attributes in payload

### ISSUE THREAD

**Issue by fpauser** [emberjs/data#3706]
ember-cli: 1.3.8
ember: 2.0.0
ember-data: 2.0.0

/app/adapters/application.js:
```javascript
import DS from 'ember-data';

export default DS.JSONAPIAdapter.extend({
  namespace: 'api'
});
```

/app/models/system.js:
```javascript
import DS from 'ember-data';

var attr = DS.attr;

export default DS.Model.extend({
  sysName: attr('string')
});
```

Payload for `this.store.findAll('system');` (GET /api/systems):
```json
{
  "data": [{
    "id": 1,
      "type": "system",
      "attributes": {
        "sysName": "Sys1"
      }
    },{
      "id": 2,
      "type": "system",
      "attributes": {
        "sysName": "Sys2"
      }
  }]
}
```

Outputting the two loaded systems works partly - id is available, `name` is empty.
Ember-Inspector shows the same: 2 loaded systems, `name` is `undefined` for both.

Setting the JSONAPISerializer under `/app/serializers/application.js` as application-default-serializer changes nothing. What am I doing wrong?

**Comment by wecc** [comment]
I'm unable to reproduce this, see http://emberjs.jsbin.com/copofatela/1/edit?html,js,output

**Comment by fpauser** [comment]
Thanks for looking at this. The problem seem to be camelcased attributes in the json-payload, I changed your example to use camelcased attributes, see http://emberjs.jsbin.com/hokebu/1/edit?html,js,output

Camelcased attribute-keys seem to be problematic... Is this intended behavior? As I understand the jsonapi-spec camelcased attribute-keys should be just ok - as okay as dasherized and underscored keys.

**Comment by wecc** [comment]
The JSONAPISerializer defaults to the recommendations and format used in the examples at jsonapi.org, therefor it assumes dasherized member keys by default.

You can easily change this behavior by overriding [keyForAttribute](http://emberjs.com/api/data/classes/DS.JSONAPISerializer.html#method_keyForAttribute) and [keyForRelationship](http://emberjs.com/api/data/classes/DS.JSONAPISerializer.html#method_keyForRelationship) in your application serializer.

**Comment by fpauser** [comment]
Ah, I now I see - thanks for pointing me in the right direction!
