### ISSUE TITLE
it's unclear what the resolved value that DS.Adapter#updateRecord suppose to return

### ISSUE THREAD

**Issue by oriSomething** [emberjs/data#3712]
i notice it works with the promise when resolved with `undefined`, but it's unclear what it suppose to resolve if some data changed in the model because of the save

**Comment by bmac** [comment]
Hi @oriSomething. I opened a pr to better document the resolved value of DS.Adapter#updateRecord. Please let me know if it answers your question. https://github.com/emberjs/data/pull/3713

**Comment by oriSomething** [comment]
first of all, thanks!
second, yes and no, because the `serialized` format is still unclear explanation to me. and i can't say if it's not another issue, but for example i get an error when i return JSON-API format. i'm not sure what's happen another the hood and what functions are called for the returned data and get a blank error.
