### ISSUE TITLE
JSONSerializer, and by extension RESTSerializer do not allow sideloaded objects

### ISSUE THREAD

**Issue by lmcardle** [emberjs/data#3716]
For the JSONSerializer, and by extension the RESTSerializer, the *_normalizeResponse* method takes individual objects and is supposed to extract both the data and included elements from the payload.  However, the *included* elements will never be extracted/included.

lines 438 and 445 in the JSONSerializer assign *data* and *included* to the response from a call to the *normalize* method.
```
let { data, included } = this.normalize(primaryModelClass, payload);
```

However, if you look at the *normalize* method, only the *data* is being returned:
```
return { data }
```

The whole implementation for extracting the included is nowhere in this method:

```
  normalize: function(modelClass, resourceHash) {
    let data = null;

    if (resourceHash) {
      this.normalizeUsingDeclaredMapping(modelClass, resourceHash);

      data = {
        id:            this.extractId(modelClass, resourceHash),
        type:          modelClass.modelName,
        attributes:    this.extractAttributes(modelClass, resourceHash),
        relationships: this.extractRelationships(modelClass, resourceHash)
      };

      this.applyTransforms(modelClass, data.attributes);
    }

    return { data };
  },
```

I am unsure if this is intentional or if this is a bug.  Should the enduser who is using the JSONSerializer or RESTSerialize have to implement their own *normalize* method if they want sideloaded records loaded?

**Comment by lmcardle** [comment]
There is another issue related to this.  I can implement my own *normalize* method, mentioned above, to massage the data so that both *data* and *included* are returned.  However when doing this, once the serializer returns back to the *_normalizeResponse* method, again the serializer will not merge the relationships/included.  So far I have only looked at this for array responses, not ones that are single.

Within the *_normalizeResponse* method, after the *normalize* call has completed, everything goes well until the *if (included)* statement.  This statement is true and thus the following block of code is executed:

```
 if (included) {
   var _documentHash$included;

  (_documentHash$included = documentHash.included).push.apply(_documentHash$included, included);
}
return data;
```

This block of code has no affect:
```
(_documentHash$included = documentHash.included).push.apply(_documentHash$included, included);
```

I believe what should be happening is the *included* object should be merged into *documentHash.included*

**Comment by wecc** [comment]
Embedded records are not supported by default in JSONSerializer/RESTSerializer, it's enabled by the `EmbeddedRecordsMixin`.

When you use `EmbeddedRecordsMixin` the `normalize` method of your serializer is overridden by  and it will return both `data` (with the primary resource) and `included` (with embedded resources).

**Comment by greyhwndz** [comment]
@wecc: Is it ok to ask where this is found in the documentation?

**Comment by wecc** [comment]
@greyhwndz The `EmbeddedRecordsMixin` is documented here: http://emberjs.com/api/data/classes/DS.EmbeddedRecordsMixin.html

**Comment by greyhwndz** [comment]
@wecc thanks!

**Comment by lmcardle** [comment]
Digging into ```EmbededRecordsMixin```, you are correct that the ```normalize``` method is overridden, however the same problem exists.  Here is the ```normalize``` method from ```EmbededRecordsMixin```:

```
normalize: function(typeClass, hash, prop) {
  var normalizedHash = this._super(typeClass, hash, prop);
  return this._extractEmbeddedRecords(this, this.store, typeClass, normalizedHash);
},
```

The first line within this normalize function calls ```this._super()```.  This ```normalizedHash```, which is returned and then passed to the following ```_extractEmbeddedRecords``` method, comes from ```JSONSerializer``` and thus is never going to include the relationships.  As stated above that ```_super``` call will only return:

```
return { data };
```

So when the ```_extractEmbeddedRecords``` method is called, the passed hash only includes the data.  The embedded records have been filtered out by this point.

**Comment by wecc** [comment]
@lmcardle if you look at `_extractEmbeddedRecords` and follow the code paths into `_extractEmbeddedHasMany` and `_extractEmbeddedBelongsTo` you can see that both of those are populating `included` (and creating if it doesn't exist). See [here](https://github.com/emberjs/data/blob/v2.0.0/packages/ember-data/lib/serializers/embedded-records-mixin.js#L433-L437) and [here](https://github.com/emberjs/data/blob/v2.0.0/packages/ember-data/lib/serializers/embedded-records-mixin.js#L457-L461). You can also see that it takes care of both `data` and `included` returned from `_normalizeEmbeddedRelationship` and puts them all in `hash.included` to allow for recursive embedded.

**Comment by lmcardle** [comment]
Ahh, yes it works. After adding ```EmbeddedRecordsMixin```, the issue I was having had to do with the ```attrs``` property.  Because our server keys are snake_case, I had defined a ```key``` in the ```attrs``` property.  Something like this:

```
attrs: {
  accountList: {
    embedded: 'always',
    key: 'account_list'
  }
}
```

That is why, when I looked at the ```normalizedHash``` variable, the sideloaded data was not there. Getting rid of ```key: 'account_list'``` fixed it.

Thanks so much @wecc.
