### ISSUE TITLE
Side loading with async: true

### ISSUE THREAD

**Issue by jagthedrummer** [emberjs/data#3718]
Is it possible to get side loading to work with a `hasMany` with `async` set to `true`?

I have this `Order` model:

```javascript
//...
var Order = DS.Model.extend({
  number: DS.attr('string'),
  lineItems: DS.hasMany('line-item', { async: true })
});
//...
```

And I've set up the `model` hook in `orders.edit` to make an API call that includes the line items for the order. I can see that the line item data is coming back in the response, and is getting pushed into the store. However, when I try to access the `lineItems` on an order it generates another request to the server to get '/orders/1/line-items'.

If I change to `async: false`, then the line items included in the request are loaded into the store and hooked up to the order model correctly.

Is there a way to keep `async: true` and also avoid a second request to populate the line-items if they are included in the first request? (I want to keep them async so that if you enter the app at `/orders` and load the whole list of orders, you're not also loading line items for each order.)

FTR, I'm using the JSONAPIApapter/Serializer and the initial response for loading an order looks like this:

```json
{
    "data": {
        "attributes": {
            "date": null,
            "number": "TEst order!!"
        },
        "id": "1",
        "links": {
            "self": "http://localhost:5000/orders/1"
        },
        "relationships": {
            "line-items": {
                "data": [
                    {
                        "id": "1",
                        "type": "line-items"
                    }
                ],
                "links": {
                    "related": "http://localhost:5000/orders/1/line-items",
                    "self": "http://localhost:5000/orders/1/relationships/line-items"
                }
            }
        },
        "type": "orders"
    },
    "included": [
        {
            "attributes": {
                "quantity": 2
            },
            "id": "1",
            "links": {
                "self": "http://localhost:5000/line-items/1"
            },
            "relationships": {
                "order": {
                    "links": {
                        "related": "http://localhost:5000/line-items/1/order",
                        "self": "http://localhost:5000/line-items/1/relationships/order"
                    }
                },
                "product": {
                    "links": {
                        "related": "http://localhost:5000/line-items/1/product",
                        "self": "http://localhost:5000/line-items/1/relationships/product"
                    }
                }
            },
            "type": "line-items"
        }
    ]
}
```

**Comment by wecc** [comment]
Currently a relationship's `links.related` takes precedence over `data`. See #3380

**Comment by jagthedrummer** [comment]
Ah-ha! I looked around for an open issue about this, but didn't manage to find it. Thanks for pointing me to it.
