### ISSUE TITLE
[JSONAPI] extending class does not apply namespace

### ISSUE THREAD

**Issue by quantumlicht** [emberjs/data#3719]
In ember 1.12 and before I could do something like

``` javascript
store = DS.Store.extend
    adapter: DS.RESTAdapter.extend
      namespace: 'v1/crm'
      auth: container.lookup('auth-manager:main')
      headers: (->
        'Authorization': @get('auth.token')
        'Content-Type': 'application/json'
        'Accept': 'application/json-ember'
      ).property('auth.token')
```

Now if I do that in ember 1.13:

``` javascript
store = DS.Store.extend
    adapter: DS.JSONAPIAdapter.extend
      namespace: 'v1/crm'
      auth: container.lookup('auth-manager:main')
      headers: (->
        'Authorization': @get('auth.token')
        'Content-Type': 'application/json'
        'Accept': 'application/json-ember'
      ).property('auth.token')
```

The namespace and other parameters are not applied.

I tried adding an application adapter that extend the rest adapter, but I run into problems when I try to reuse it for multiple stores

```
store = DS.Store.extend
    adapter: CustomRestAdapter.reopen
      namespace: 'v1/crm'
      auth: container.lookup('auth-manager:main')
      headers: (->
        'Authorization': @get('auth.token')
        'Content-Type': 'application/json'
        'Accept': 'application/json-ember'
      ).property('auth.token')
```

Works for that store, but if I try to reopen for another store, it keeps the same namespace.

**Comment by wecc** [comment]
Custom stores changed a bit in 1.13 and I suspect this could be related to where your `store.js` is located. Can you try moving it to `app/services/store.js` (if you haven't done that already).

See http://emberjs.com/blog/2015/06/18/ember-data-1-13-released.html#toc_custom-stores for more info.

**Comment by quantumlicht** [comment]
I opened a StackOverflow question, because I am really confused about how I should do that. Any help would be greatly appreciated. By the way, please let me know if opening a SO question was the right way to go about this.

**Comment by wecc** [comment]
@quantumlicht do you have a link to the SO question?

Posting a question on SO or raising it in the Ember Forum or Community Slack is definitely a great way of asking questions. We prefer to keep the issue tracker to bugs only.

**Comment by quantumlicht** [comment]
Sorry, totally forgot to include the link ;) : http://stackoverflow.com/questions/32356858/refactoring-stores-from-initializers-to-services

**Comment by wecc** [comment]
@quantumlicht sorry for the (very) late response, did you sort this out?

**Comment by stefanpenner** [comment]
I don't believe this is supported in 2x.
