### ISSUE TITLE
[JSONAPI] Using EmbeddedRecordsMixin puts the embedded records in the wrong place

### ISSUE THREAD

**Issue by jagthedrummer** [emberjs/data#3720]
I'm trying to send a `Product` and a collection of `Screenshot`s to the server in one request.

My product serializer looks like this:

``` javascript
// app/serializers/product.js
import DS from 'ember-data';
export default DS.JSONAPISerializer.extend(DS.EmbeddedRecordsMixin,{
  attrs: {
    screenshots: { embedded: 'always' }
  }
});
```

When I save a `Product` that has one `Screenshot` in the collection I'm getting this payload:

``` ruby
{
  "data"=>{
    "attributes"=>{
      "name"=>"embedded save test",
      "price"=>"42",
    },
    "relationships"=>{
      "category"=>{
        "data"=>{"type"=>"categories", "id"=>"1"}
      }
    },
    "screenshots"=>[{
      "data"=>{
        "attributes"=>{
          "name"=>"testing the screenshots",
          "description"=>"heloo there",
          "cloudinary-image-id"=>"g3ljvsgc1j0jskrgmexd"
        },
        "relationships"=>{
          "product"=>{"data"=>{"type"=>"products", "id"=>nil}}
        },
        "type"=>"screenshots"
      }
    }],
    "type"=>"products"
  }
}
```

The `screenshots` object is part of the root `data` object instead of being in the `relationships` object along with `category`.

**Comment by wecc** [comment]
I would say that the `EmbeddedRecordsMixin` does not support `JSONAPISerializer` right now as the JSON API spec itself doesn't mention anything about embedding resources (are they relationships? keep them as complex attributes?). It shouldn't be too hard to fix but it's currently very untested.

**Comment by fivetanley** [comment]
I would say that if you're using JSONAPI you shouldn't be using embedded records. You should be able to move those records to `included`

**Comment by csantero** [comment]
JSON API does not define any semantics for using `included` in a POST/PATCH. The way I've dealt with saving multiple related records in one request is to turn the related records into complex attributes on the primary record. It's ugly, but I haven't found any better way to do it.

There is [discussion](https://github.com/json-api/json-api/issues/795) about how to support this use case and it's milestoned for the next version of the spec, but nothing concrete yet.

**Comment by MiracleBlue** [comment]
Darn, so this is what I have been dealing with all morning.  Glad to have found this thread.  I'll switch to just not using embedded records for the time being and side-load it in included.

**Comment by vladimir-e** [comment]
I ran into same problem today. 
If you use JSONAPISerializer and you need to save a record and update its hasMany relationships in one request, `DS.EmbeddedRecordsMixin` is still okay, if you really need to make it work.

Here's a monkey patch I ended up creating:

I created `mixin/embedded-jsonapi-records.js` that overrides key parts of `DS.EmbeddedRecordsMixin` to serialize relationships in a way json-api expects:

``` JavaScript
import Ember from 'ember';

export default Ember.Mixin.create({

  _serializeEmbeddedHasMany: function(snapshot, json, relationship) {
    let serializedKey = this.keyForRelationship(relationship.key, 'serialize');

    // ...

    if (!json['relationships']) {
      json['relationships'] = {}
    }
    json['relationships'][serializedKey] = { data: [] }
    json['relationships'][serializedKey].data = this._generateSerializedHasMany(snapshot, relationship);
  },

  _generateSerializedHasMany: function(snapshot, relationship) {
    let hasMany = snapshot.hasMany(relationship.key);
    return Ember.A(hasMany).map((embeddedSnapshot) => {
      var embeddedJson = embeddedSnapshot.record.serialize({ includeId: true });
      this.removeEmbeddedForeignKey(snapshot, embeddedSnapshot, relationship, embeddedJson);
      // my server (`jsonapi-resources` gem) only needs an array of id and type for relationships to be updated
      return { id: embeddedJson.data.id, type: embeddedJson.data.type };
    });
  },

});

```

**Comment by bmac** [comment]
I have opened a pr so Ember Data will warn in the future when `JSONAPISerializer` and `EmbeddedRecordsMixin` are combined. https://github.com/emberjs/data/pull/4259

I don't think `JSONAPISerializer` and `EmbeddedRecordsMixin` will work together out of the box until JSON API has a more detailed specification on how it supports embedded records. https://github.com/json-api/json-api/issues/795

**Comment by michaeljbishop** [comment]
Do we necessarily need something more from JSON-API at this point for this to work? Why couldn't the payload in the above example look like this?

```
{
  "data"=>{
    "attributes"=>{
      "name"=>"embedded save test",
      "price"=>"42",
      "screenshots"=>[{
        "name"=>"testing the screenshots",
        "description"=>"heloo there",
        "cloudinary-image-id"=>"g3ljvsgc1j0jskrgmexd"
      }],
    },
    "relationships"=>{
      "category"=>{
        "data"=>{"type"=>"categories", "id"=>"1"}
      }
    },
    "type"=>"products"
  }
}
```
In other words, if the value of the "attribute" is an embedded record, why don't we serialize it as a JSON blob and submit (and retrieve) that as the value?

**Comment by taras** [comment]
@bmac is it possible to suppress this error for those who're using JSONAPI & EmbeddedRecordsMixin intentionally?

**Comment by danilovaz** [comment]
anything about it? this is very frustrating. I use JSONAPISERIALIZER. I have a User model containing many Tags. What can I do when I need to make a Patch request, which can be editing the user name and selected Tags ids?

**Comment by fivetanley** [comment]
@taras I don't think we'll allow disabling the warning until JSONAPI takes a stance on this. The JSONAPI adapter/serializer's goals are to only support stuff in the spec or in a spec extension. A better route for now might be to fork or copy the EmbeddedRecordsMixin into your app and make the changes you need there for now.

I know this is kind of not the greatest response in the world, and I apologize. EmbeddedRecordsMixin has in the past been pretty complex to support across a variety of APIs, so we want to reduce the maintenance burden until something is standardized so everyone has an idea of what their server should be sending.

**Comment by fivetanley** [comment]
We should come up with something in the short term so at least IDs can be serialized to the server.

**Comment by sandstrom** [comment]
FWIW here is the discussion on embedded records in json-api:

https://github.com/json-api/json-api/issues/795#issuecomment-245016601

**Comment by taras** [comment]
> I know this is kind of not the greatest response in the world, and I apologize.

No worries, it makes sense. 

Would it make sense to pull EmbeddedRecordsMixin mixing into an addon? It can stay in Ember Data and people who want to use it can use it without the warning can use the addon. It'll make their opt-in explicit.

**Comment by sandstrom** [comment]
This PR may have solved this issue: https://github.com/emberjs/data/pull/7126

(I haven't tested myself yet though, saw it only a few minutes ago)

**Comment by runspired** [comment]
Closing as both identifiers resolved much of the original issues faced here and because serializers are an antiquated pattern that are optional today and don't have a lasting future (see https://github.com/emberjs/rfcs/pull/860)
