### ISSUE TITLE
Should Store#findRecord return a promise for a record that is loading?

### ISSUE THREAD

**Issue by sclaxton** [emberjs/data#3721]
In [`system/store.js:795`](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/store.js#L795), the boolean return value of `hasRecordForId` is computed by the `isLoaded` method of the internalModel of the record. Shouldn't this also be computed by `isLoading` so that relatively "simultaneous" `findRecord` calls don't result in multiple fetches?

Basically I feel like [`system/store.js:795`](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/store.js#L795) should be:

```
return !!internalModel && (internalModel.isLoaded() || internalModel.isLoading());
```

**Comment by wecc** [comment]
Sounds reasonable to me, @bmac @igorT ?
