### ISSUE TITLE
relationshipNames not avaible in ready()

### ISSUE THREAD

**Issue by shaunc** [emberjs/data#3728]
I'm using ember-data 2.1.0-beta-1.

In a mixin of a model, in `ready()`, I want to get the names of the models' relationships. However,

    this.get('relationshipNames')

returns `undefined`.

In fact:

    Ember.get(this.constructor, 'relationshipsByName')._keys.list

works, but that is obviously not part of the API :).

**Comment by fivetanley** [comment]
The relationship info is stored on the class. You should be able to use `Ember.get(this.constructor, 'relationshipNames')` to access that information.

**Comment by shaunc** [comment]
That works -- thanks!
