### ISSUE TITLE
Creating and Removing records from has many does not perform JSON API spec requests

### ISSUE THREAD

**Issue by danmcclain** [emberjs/data#3733]
When using a `links` attribute with a `hasMany` relation, I would expect that removing/adding items to said relation to preform the requests declared here: http://jsonapi.org/format/#crud-updating-to-many-relationships

Example: Adding comments to a article would make the following request on save:
```
POST /articles/1/relationships/comments HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "data": [
    { "type": "comments", "id": "123" }
  ]
}
```

And deleting comments from an article would make the following request on save:
```
DELETE /articles/1/relationships/comments HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "data": [
    { "type": "comments", "id": "12" },
    { "type": "comments", "id": "13" }
  ]
}
```

**Comment by wecc** [comment]
Ember Data does, for the moment, not support `links.self` links.

ED does support saving relationships together with their resource objects, see http://jsonapi.org/format/#crud-updating-resource-relationships

**Comment by danmcclain** [comment]
@wecc Figured this was something to come, but wanted an issue to track it as well, will be manually managing this on the project I am working on in the mean time

**Comment by wecc** [comment]
@danmcclain got it! it's kind of tracked in #2905 under "Improve link handling" but should probably be expanded upon.

**Comment by SeyZ** [comment]
:+1: for this feature. It would be awesome :)

**Comment by dbbk** [comment]
Am I right in thinking this is still an issue? I've been trying for hours to simply have a POST request when adding a record to hasMany and no dice.

**Comment by danilovaz** [comment]
This is really frustrating. I believe it was best to leave the REST as standard, instead of putting the JSONAPI as standard and one fine morning, you find that does not work many essential stuff to your project.

**Comment by dbbk** [comment]
This issue is now over a year old and seems to be a fundamental flaw with Ember Data's implementation of JSON:API. Is any work being done to resolve it?

**Comment by wecc** [comment]
I'm closing this issue as `self` link support for relationships are tracked in #2905
