### ISSUE TITLE
JSONSerializer.extractRelationships() is now failing when a relationship is not set in the model

### ISSUE THREAD

**Issue by sebweaver** [emberjs/data#3736]
Hello,

I added a commented on the PR which has introduced this issue (worked previously in ED 1.13). Please see https://github.com/emberjs/data/pull/3345#diff-for-comment-38619627 for more detail.

Sébastien

**Comment by wecc** [comment]
I'm unsure how you can end up in that code path when the key is missing in the payload, there's a check for this here: https://github.com/emberjs/data/pull/3345#discussion-diff-38619627R600

**Comment by wecc** [comment]
Hm, I'm a bit confused. `store.push()` doesn't use serializers so the change in JSONSerializer shouldn't be affecting the issue you're describing.

**Comment by wecc** [comment]
Can you provide a minimal JSBin or Embed Twiddle demonstrating the issue you're experiencing?

**Comment by sebweaver** [comment]
As a matter of fact the problem has nothing to do with the `push` but with the `normalize` (when you fetch data with undefined relationships).

I edited my comment https://github.com/emberjs/data/pull/3345#diff-for-comment-38619627 and added the 2 following JSBins:

* ED 1.13: http://emberjs.jsbin.com/puguhi/edit?html,js,console,output
* ED 2.0: http://emberjs.jsbin.com/towofa/edit?html,js,console,output

**Comment by wecc** [comment]
Yeah, this definitely looks like a bug. Would you be able to provide a PR fixing it?

**Comment by sebweaver** [comment]
Done.

**Comment by pangratz** [comment]
This issue can be closed since https://github.com/emberjs/data/pull/3747 got merged ...

**Comment by Turbo87** [comment]
I'm getting very confused by this change... Is there any documentation on the expected behavior when a relationship key is `null`? I would assume that it does not change anything, but it seems that in v1.13 it actually empties the array.

see https://github.com/rust-lang/crates.io/pull/208#issuecomment-155714465 for a more detailed description of the bug
