### ISSUE TITLE
CP based on model.hasDirtyAttributes not firing in ED 1.13.11 / E 1.13.10

### ISSUE THREAD

**Issue by zyllorion** [emberjs/data#3737]
Currently have a model with numerous hasMany's, e.g.
```
myModel
--otherModel1
--otherModel2
--otherModel3
```
It is initialised in the pod route, and `controller.set('model', model);` so it is visible in the controller and template, which it is through the usual model.myModel.

When I create a CP with the structure;
```
isTreeDirty: Ember.computed([the conditions],
        function() {[return t or f based on status of related entities]
```
or
```
isTreeDirty: function() {
[return t or f]
    }.property([conditions])
```
where conditions are all combinations of;
```
model.myModel.hasDirtyAttributes
model.myModel.otherModel1.hasDirtyAttributes
model.myModel.otherModel1.[].hasDirtyAttributes
model.myModel.otherModel1.@each.hasDirtyAttributes
...
```
the CP does not fire when there is a change to the model or nested models.  The change is visible in Ember Inspector.

This worked with the same ED 1.13 but Ember v1.12, and for the upgrade of this CP initially I added [] references which caused things to break, then on reverting to just the @each (first and last lines in list above) it worked again.

There doesnt seem to be an explanation of [] on http://guides.emberjs.com/v1.13.0/object-model/computed-properties-and-aggregate-data/

Any ideas? Thanks

**Comment by fivetanley** [comment]
> This worked with the same ED 1.13 but Ember v1.12

Does this mean it worked on 1.11 but not 1.12?

**Comment by zyllorion** [comment]
All but the [] example worked on 1.9 thru 1.12, the addition of a [] watcher broke the whole CP, I can't test if adding [] to Ember 1.12 breaks it as project is now migrated

**Comment by svox1** [comment]
Same problem with Ember 2.0.2.

I cant bind:
```
model.myModel.@each.hasDirtyAttributes
```

We need the `hasDirtyRelationships ` as mention at the Ember 1.13 release:
http://emberjs.com/blog/2015/06/18/ember-data-1-13-released.html
:)

**Comment by toovy** [comment]
I found with Ember and EmberData 2.1.0 we cannot bind to ANY property with @each for hasMany relationships (in addition to the report from @svox1.). Won't work:

    Book = DS.Model.extend
        pages: DS.hasMany 'page', async: true
        sorted_pages: Ember.computed 'pages.@each.idx', ->
            # resort, won't be triggered if any page idx changes

I believe that this worked once and I think this is a major bug. Happy to help if I can support.

**Comment by toovy** [comment]
Related to https://github.com/emberjs/ember.js/issues/12475

**Comment by bmac** [comment]
I believe this has been fixed in Ember by https://github.com/emberjs/ember.js/pull/12908
