### ISSUE TITLE
Ability to reload hasMany conditionally

### ISSUE THREAD

**Issue by elidupuis** [emberjs/data#3740]
I have an async `hasMany` relationship that I want to reload every time a route is loaded (to ensure I'm in sync with the server). The relationship is defined via a `links` object (see below).

@bmac mentioned (on Slack) that there's currently no public API to accomplish this (`shouldReload*` methods only apply to `DS.store` methods).

**models/foo.js**
```
bars: hasMany('bar', { async: true })
```

**models/bar.js**
```
bar: belongsTo('foo', { async: true })
```

**foo links payload**
```
foo: {
  id: '123',
  links: { bars: 'path/to/bars' }
}
```

**routes/foo/bars.js**
```
model() {
  let foo = this.modelFor('foo');

  // option 1)
  // works first time, but won't be fresh next time route is loaded.
  // return foo.get(‘bars’);

  // option 2)
  // works (always fresh), but triggers 2 XHRs on first load.
  // return foo.get(‘bars’).reload();

  // option 3)
  // suggestions or workarounds?
}
```

I tried checking the `isFulfilled` property on the `foo.get('bars')` promise but that doesn't not seem reliable. 

Any advice is greatly appreciated!

**Comment by wecc** [comment]
This will most likely be solved when https://github.com/emberjs/rfcs/pull/57 is done

**Comment by pangratz** [comment]
I think this issue can be closed since an [initial implementation of references](https://github.com/emberjs/data/pull/3303) has been merged into `master`. Having the `ds-references` feature enabled, a `hasMany` relationship can be reloaded via `model.hasMany("children").reload()`.

**Comment by pangratz** [comment]
@elidupuis I am going to close this as this can be achieved via references (see http://emberjs.com/blog/2016/01/12/ember-data-2-3-released.html#toc_code-ds-references-code and http://emberup.co/references-api-in-ember-2-4/).
