### ISSUE TITLE
Namespace of adapters cant be dynamically set properly

### ISSUE THREAD

**Issue by jcope2013** [emberjs/data#3741]
changing the namespace of the adapter dynamically doesn't seem to change it properly, this seemed to work for awhile but has completely stopped in the 1.13 series, I am not sure of another way to do it without using the container 

```
this.container.lookup('adapter:application').set('namespace', 'api/admin/v1');
```

http://emberjs.jsbin.com/bigigozado/1/edit?html,css,js,output

oddly the snippet below does work in a CLI app, cant get it working in jsbin but this actually changes the namespace correctly, but doing anything on the __proto__ seems like a real bad idea

```
this.container.lookup('adapter:application').__proto__.set('namespace', 'api/admin/v1');
```

**Comment by wecc** [comment]
I'm pretty sure `this.container.lookup('adapter:application')` returns a new instance and therefor any modifications to it does not affect the instances used by the store.

You should be able to make `namespace` a computed property and have it return a value dynamically.

If you only want to modify the namespace for certain models you can override `namespace` in their specific adapters.

**Comment by fivetanley** [comment]
> I'm think this.container.lookup('adapter:application') returns a new instance

No, adapter instances are singletons.

**Comment by jcope2013** [comment]
this works

```
this.store.adapterFor('application').set('namespace', "api/admin/v1");
```

**Comment by bmac** [comment]
`this.store.adapterFor('application').set('namespace', "api/admin/v1");` is the recommend way of doing this.

To clear up some misconceptions, adapter instances are not singletons. A new adapter is made for each store in your application. Most users will only have one store in their application so it will may appear that the adapter is a singleton, however, if you look it up by the container you will get a new adapter instance each time.
