### ISSUE TITLE
Should didUpdate be triggered on reload?

### ISSUE THREAD

**Issue by jcbvm** [emberjs/data#3748]
I stumbled across an issue in my current app, I was under the impression that a reload would trigger a didUpdate event of a model, but it only seems to be triggered when calling save. Looks like I'm not the only one #1441. 

Shouldn't didUpdate be triggered when the model gets updated from the server (either via reload, save, pushPayload etc...)?

**Comment by st-h** [comment]
I was running into the same issue, being unable to properly observe changes to a current record that is initiated by the server via pushPayload: https://discuss.emberjs.com/t/observe-reload-changes-to-model/13182

I noticed emberfire is currently having an open issue with a similar issue: https://github.com/firebase/emberfire/issues/497

I have been trying to find out if there is a reason for ember data to not trigger any hooks via pushPayload, however nobody was able to come up with a reason so far. I think it would make things a lot easier if we had a consistent behaviour for something like didUpdate (which actually sounds like it should trigger every time the record gets updated on the server - and hence the client). At least it seems to be possible to work around this issue by using a customised adapter, as described in the ember fire issue.

**Comment by danielspaniel** [comment]
I notice that the when the store does a background reload or even store.findRecord({reload: true}) the  ready or didLoad hooks are not called again, which I think is a flaw. 
 But I am curious about what others think.

**Comment by reppa-fe** [comment]
I think it makes sense to trigger `didUpdate` whenever a model is updated "externally." We too receive data from a live data source and update it by pushing it into the store. `didUpdate` not being called in this case was both surprising and lead us to build a workaround that somewhat break separation.

**Comment by st-h** [comment]
Yes! I would really like to get this resolved. It makes it quite difficult to use things like ember changeset together with server push. Or write components that display data of a record without getting out of sync. Do we need an application that shows the issue? I think it should be sufficient to agree on the wanted behavior - and then have a look at the existing tests?

**Comment by danielspaniel** [comment]
@wecc any conclusions from team discussions?  need help implementing this if you are ok with the basic idea of calling didLoad after reload, pushPayload etc.

**Comment by runspired** [comment]
We are looking to deprecate record events/event-hooks in favor of using promises and functional patterns. Closing this because we do not with to add more complexity to a layer we are seeking to remove.

**Comment by reppa-fe** [comment]
@runspired Is there an Issue or RFC to track this pattern change?

**Comment by ro0gr** [comment]
I just found `didUpdate` hooks doesn't work with `pushPayload(`, and it was surprising, cause  `didUpdate` is mentioned in docs as a public API docs https://api.emberjs.com/ember-data/3.16/classes/Model/events/didUpdate?anchor=didUpdate

Also `didLoad` seems to work properly to me, which is inconsistent.

Is there any alternative to `didUpdate`? Should `didUpdate` be removed from the docs?

**Comment by runspired** [comment]
@ro0gr didUpdate does work, more likely this wasn't a situation in which an update was performed.

**Comment by ro0gr** [comment]
Oh, then that is probably related to version of ED@3.12 which I'm currently pinned to. I'll check. Thanks for letting me know `didUpdate` is supposed to work!
