### ISSUE TITLE
json serializer's `normalizePayload` method never called

### ISSUE THREAD

**Issue by minasmart** [emberjs/data#3750]
Hey guys!

The method documented here: https://github.com/emberjs/data/blob/v2.0.0/packages/ember-data/lib/serializers/json-serializer.js#L632 appears to me as a hook that you can override to customize your payload, on a per-serializer basis, however, this method is not called anywhere in ember data.

```javascript
/**
    You can use this method to normalize all payloads, regardless of whether they
    represent single records or an array.
    For example, you might want to remove some extraneous data from the payload:
    ```app/serializers/application.js
    import DS from 'ember-data';
    export default DS.JSONSerializer.extend({
      normalizePayload: function(payload) {
        delete payload.version;
        delete payload.status;
        return payload;
      }
    });
    ```
    @method normalizePayload
    @param {Object} payload
    @return {Object} the normalized payload
  */
```
The docs state `You can use this method to normalize all payloads` but that's not true if you are using any of the stock serializers.

I don't know if this is an API bug, or maybe a documentation bug, but removing the hook from the docs, or re-phrasing it could save others from overriding it and expecting it to have any side-effects.

I'm happy to make a PR adding the call in to the existing serializers, but if this is just an artifact that shouldn't be there, that won't be of much use.

**Comment by wecc** [comment]
Thanks for reporting @minasmart!

`normalizePayload` was deprecated in 1.13.5 and the deprecation was removed for 2.0 but it seems the method itself wasn't. Feel free to create a PR removing it!

**Comment by minasmart** [comment]
Will do. posting shortly.

**Comment by minasmart** [comment]
I would add a test, but it's weird to ensure a method doesn't exist? I'll add one if anyone thinks it's necessary.

**Comment by wecc** [comment]
@minasmart looks great, no test needed
