### ISSUE TITLE
Any chance we could get a v1.13.12? 

### ISSUE THREAD

**Issue by workmanw** [emberjs/data#3752]
One of our enterprise customers has their user's locked to Firefox 31 (I realize this is generally not supported). They're completely unable to use our app at the moment due to an issue with Ember Inflector that has since been fixed. See: https://github.com/stefanpenner/ember-inflector/pull/89 . The app is completely crashing for all users at this customer site :(

I'd really like to get a new build of Ember-Data that includes this fix. I did a local build from the 1.13 release branch and confirmed it does fix this issue. 

I'd be happy to do all the leg work. I'm just not sure how to formally go about this. Should I submit a PR w/ build to the https://github.com/components/ember-data repo?

**Comment by bmac** [comment]
Hi @workmanw. I can do a build and a release. Before I do would you mind submitting a pr to ensure Ember Data has the requires a version of ember-inflector in its pacakge.json with that fix https://github.com/emberjs/data/blob/release-1-13/package.json#L59?

Thanks

**Comment by workmanw** [comment]
@bmac Yeap, I'm on it. Thank you!!!

**Comment by bmac** [comment]
`v1.13.12` has been released and published to bower.

**Comment by workmanw** [comment]
Thanks again! I owe you :beers:
