### ISSUE TITLE
Port pr #3725 to master branch

### ISSUE THREAD

**Issue by bmac** [emberjs/data#3755]
See https://github.com/emberjs/data/pull/3725

**Comment by ppcano** [comment]
The port is also missing at `2.0.1`

**Comment by bmac** [comment]
Oops thanks for the comment. I missed this issue in the shuffle of releasing. I'll likely do a `2.0.2` release with this pr.

**Comment by bmac** [comment]
#3725 has been cherry-picked into the `master`, `beta` and `release` branch. It will make it into the 2.0.2 release.
