### ISSUE TITLE
Should Ember Data unregister `service:store` on the master branch?

### ISSUE THREAD

**Issue by bmac** [emberjs/data#3756]
For context see: https://github.com/emberjs/data/pull/3690. 

I suspect if we change the initializer to use unregister instead of has it will break this usecase: https://github.com/emberjs/data/pull/3460

**Comment by fivetanley** [comment]
unregistering may affect fastboot apps in a negative way, if it is unregistering it for the whole container. cc @dgeb @rwjblue does that sound right?

**Comment by rwjblue** [comment]
In a fastboot scenario initializers are only ran once (not once for each request).

Instance initializers are ran for each request.
