### ISSUE TITLE
bower install fails because of git protocol usage

### ISSUE THREAD

**Issue by eccegordo** [emberjs/data#3759]
```
# bower install
bower ember-data#1.13.12    not-cached git://github.com/components/ember-data.git#1.13.12
bower ember-data#1.13.12       resolve git://github.com/components/ember-data.git#1.13.12
bower ember-data#1.13.12       ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/components/ember-data.git", exit code of #128 fatal: unable to connect to github.com: github.com[0: 192.30.252.130]: errno=Operation timed out
```

Some of us sit behind proxied corp firewalls and git:// causes problems.
Please make the bower plumbing use https:// instead

**Comment by pangratz** [comment]
I don't know if this is an option for you but as workaround you can [configure `git` to replace the protocol](http://stackoverflow.com/a/15684898/65542): `git config --global url."https://".insteadOf git://`.

**Comment by fivetanley** [comment]
Do you have a bower.json for reference? This seems like a bower issue. We aren't declaring any dependencies as git protocol afaik.

**Comment by bmac** [comment]
@eccegordo Are you having this issue?

**Comment by eccegordo** [comment]
This is really just corporate firewall that is the underlying cause for me. @pangratz I am aware of that work around, but thanks for the tip, that does work around the problem but...

I just thought the plan was to ensure that dependency management were not strictly going to be tied to git. And furthermore I thought ember cli had as one of its goals to make git not strictly required. ping @stefanpenner 

This might not be a reasonable goal. But that is only reason why I point this out, in case there was some configuration somewhere that was the cause of the problem.

My view is that this kind of stuff has just enough inertia to discourage adoption of open source tools within a corporate and government environment who have onerous firewalls. But realize there might not be any easy solutions than to apply the https workaround.

I just did a new project initialization and here is what happened. (Note this works if I apply pangrantz's workaround)

```
... Go off fire walled network (e.g. connect via my cell phone) ...

run
ember new blank

rm -rf bower_components/

... go back onto network and try to do bower install ...

in blank/ on master 
› more bower.json 
{
  "name": "blank",
  "dependencies": {
    "ember": "1.13.7",
    "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.3",
    "ember-cli-test-loader": "ember-cli-test-loader#0.1.3",
    "ember-data": "1.13.8",
    "ember-load-initializers": "ember-cli/ember-load-initializers#0.1.5",
    "ember-qunit": "0.4.9",
    "ember-qunit-notifications": "0.0.7",
    "ember-resolver": "~0.1.18",
    "jquery": "^1.11.3",
    "loader.js": "ember-cli/loader.js#3.2.1",
    "qunit": "~1.18.0"
  }
}

in blank/ on master 
› bower install          
bower cached        git://github.com/ember-cli/ember-load-initializers.git#0.1.5
bower validate      0.1.5 against git://github.com/ember-cli/ember-load-initializers.git#0.1.5
bower cached        git://github.com/ember-cli/ember-cli-shims.git#0.0.3
bower validate      0.0.3 against git://github.com/ember-cli/ember-cli-shims.git#0.0.3
bower cached        git://github.com/ember-cli/loader.js.git#3.2.1
bower validate      3.2.1 against git://github.com/ember-cli/loader.js.git#3.2.1
bower cached        git://github.com/components/ember.git#1.13.7
bower validate      1.13.7 against git://github.com/components/ember.git#1.13.7
bower cached        git://github.com/components/ember-data.git#1.13.8
bower validate      1.13.8 against git://github.com/components/ember-data.git#1.13.8
bower cached        git://github.com/rwjblue/ember-qunit-builds.git#0.4.9
bower validate      0.4.9 against git://github.com/rwjblue/ember-qunit-builds.git#0.4.9
bower cached        git://github.com/stefanpenner/ember-jj-abrams-resolver.git#0.1.21
bower validate      0.1.21 against git://github.com/stefanpenner/ember-jj-abrams-resolver.git#~0.1.18
bower cached        git://github.com/dockyard/ember-qunit-notifications.git#0.0.7
bower validate      0.0.7 against git://github.com/dockyard/ember-qunit-notifications.git#0.0.7
bower cached        git://github.com/jquery/jquery.git#1.11.3
bower validate      1.11.3 against git://github.com/jquery/jquery.git#^1.11.3
bower cached        git://github.com/jquery/qunit.git#1.18.0
bower validate      1.18.0 against git://github.com/jquery/qunit.git#~1.18.0
bower cached        git://github.com/ember-cli/ember-cli-test-loader.git#0.1.3
bower validate      0.1.3 against git://github.com/ember-cli/ember-cli-test-loader.git#0.1.3
bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://github.com/components/ember.git", exit code of #128 fatal: unable to connect to github.com: github.com[0: 192.30.252.130]: errno=Operation timed out

Additional error details:
fatal: unable to connect to github.com:
github.com[0: 192.30.252.130]: errno=Operation timed out


```

**Comment by pangratz** [comment]
@eccegordo I am going to close this as it really seems that this should be solved upstream in bower itself (see bower/bower#756, bower/bower#250, bower/bower#2116, bower/bower#1489; also http://stackoverflow.com/questions/15669091/bower-install-using-only-https).

Until this is fixed in bower, I think another approach could be to use a [custom resolver](http://bower.io/docs/pluggable-resolvers/) in `.bowerrc` which replaces `git://` protocol with `https://`. Maybe [bower-git-resolver](https://github.com/arshtepe/bower-git-resolver) can help with that...
