### ISSUE TITLE
[Request] deprecate `defaultValue: primitiveValue`

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/data#3766]
https://github.com/emberjs/data/blob/c208f2c299ecd5566ad9d0eee0a89f9913e924c6/packages/ember-data/lib/system/model/attributes.js#L231

It is quite common to see: `defaultValue: []` but this results in a shared array between all instances, obviously nearly never something a user actual intends.

An alternative, and likely the better option, is to only allow primitive values, and require functions for complex objects. If someone wants the old behavior, that can close over a shared complex object.

**Comment by fivetanley** [comment]
:+1:

**Comment by workmanw** [comment]
FWIW Ember Model Fragments handles this by calling `Ember.copy` on default values. But the function solution is just as viable. [fragments/attributes.js#L314-L332](https://github.com/lytics/ember-data.model-fragments/blob/master/packages/model-fragments/lib/fragments/attributes.js#L314-L332).
