### ISSUE TITLE
Add { backgroundReload: false } to store.findRecord() and store.findAll()

### ISSUE THREAD

**Issue by HeroicEric** [emberjs/data#3772]
This feature is mentioned in http://emberjs.com/blog/2015/06/18/ember-data-1-13-released.html#toc_better-caching-defaults-for-code-findall-code-and-code-findrecord-code but is not yet implemented.

I was going to work on adding it but I could not find a full description of the intended behavior and it was not clear to me when I began working on an implementation.

What is the desired behavior when the record is **not already present in the store**? Should it behave like `{ reload: true }` and wait for data to be fetched from the server or should nothing be returned?

**Comment by pangratz** [comment]
Hey @HeroicEric, sorry for the late response :pensive: 

> What is the desired behavior when the record is not already present in the store? Should it behave like { reload: true } and wait for data to be fetched from the server or should nothing be returned?

I think the case your'e describing is currently handled [here](https://github.com/emberjs/data/blob/v2.5.2/addon/-private/system/store.js#L469-L471): if there is no record, then it is loaded from the adapter and no check for the passed `reload` and `backgroundReload` options are made. This is the current state in the code as of `v2.5.2`. You opened this issue last year, so this functionality might have been added in the meantime.

I will bring this up in the next team meeting to check the path which should be taken here. I will get back to you, so you can start implementing this (if you are still interested, which would be highly appreciated :wink: )

Does that sound good to you?

**Comment by HeroicEric** [comment]
@pangratz yes :smile:

**Comment by pangratz** [comment]
Hey @HeroicEric, we discussed this and it would be lovely if the `backgroundReload` option is considered as well in `findAll` and `findRecord` 😉
