### ISSUE TITLE
Publish ember data 2.0 to npm

### ISSUE THREAD

**Issue by jcope2013** [emberjs/data#3775]

**Comment by bmac** [comment]
I just ran `npm install ember-data@2.0.0 --save` and was successful. 

`npm view` shows 2.0.0 as published on August 20th.
![screen shot 2015-09-16 at 2 54 56 pm](https://cloud.githubusercontent.com/assets/54056/9915062/f312e2d8-5c82-11e5-92e7-645ceb188278.png)

However, the [npm page](https://www.npmjs.com/package/ember-data) shows `1.13.12` as the latest release. Which is true it was the most recent chronological release. I'm not sure if there is a way to change that.

@jcope2013 is there a specific issue you are seeing?

**Comment by jcope2013** [comment]
no, the npm page was just throwing me off

**Comment by sethkinast** [comment]
npm uses the magic tag `latest` to identify the most current version. You can retag a different version of your package with the latest tag to make it show up correctly on NPM.

When you publish a package, by default it's always set to latest unless you override using `--tag=whatever`

```
$ npm dist-tag ls ember-data
beta: 2.1.0-beta.2
latest: 1.13.12
$ npm dist-tag add ember-data@2.0.0 latest
```

**Comment by bmac** [comment]
Thanks @sethkinast. I have updated `latest` tag on npm.
