### ISSUE TITLE
BelongsTo relation called 'type' in combination with a link returns error

### ISSUE THREAD

**Issue by jevanlingen** [emberjs/data#3784]
Today I was updating Ember Data from 1.13.8 to 1.13.13. As #3725, the `type` attribute can be used again. My case is a little different, as I have a belongs-to relation. This still shouldn't be a problem as @tschoartschi in ticket #3769 also has a `type` belongs-to relation and the fix worked for him.

I got following file model:
```javascript
export default DS.Model.extend({
    name: attr(),
    size: attr(),
    lastModified: attr(),
    created: attr(),
    
    directory: DS.belongsTo('directory', { async: true }),
    type: DS.belongsTo('file-type', { async: true })
}
```

The type property belongs to a `file-type` model, which is loaded async with an own given link. So I made a file serializer:
```javascript
export default DS.RESTSerializer.extend({
    isNewSerializerAPI: true,

    normalize(typeClass, hash, prop) {
        hash.links = {
            type: `link-to-another-system?type_id=${hash.type}`
        };
             
        return this._super(...arguments);
    }
});
```

--

Yet, I still seem to face a problem regarding the `type` property. Pull #3725 just fixes the problem for attributes (by adding the `primaryHasTypeAttribute` variable).

Maybe my own serializer is the problem, but 
```javascript
var primaryHasTypeAttribute = get(modelClass, 'attributes').get('type');
```
returns `undefined` for me. I find that logicly, as a belong-to relation is not a attribute (to be honest I don't understand how it's possible pull #3725 fixes #3769).

Whaterever the case. if a set `primaryHasTypeAttribute` to `true` by hand, the problem is solved! Maybe the check should also take relation properties into account?

**Comment by jevanlingen** [comment]
Nobody?

**Comment by pangratz** [comment]
@jevanlingen can you confirmed that #3814 solves your issue, so this one can be closed?

**Comment by jevanlingen** [comment]
@pangratz Yeah, I can confirm #3814 does fix this issue. Added the `get(modelClass, 'relationshipsByName').get('type');`line to my local code, problem was fixed!

**Comment by pangratz** [comment]
won der ful! Good to hear! :sparkles:

**Comment by jevanlingen** [comment]
I still face one problem with the `type` atrribute. When I tested this back in october, I just checked if no errors occured.

But today I noticed the related link does not work. The serializer should return something like this for an async relation according to the JSON API spec:

```javascript
data: {
  id: "something",
  ... // other props
  relationships: {
    type: {
      links: {
        related: "link-to-another-system"
      }
    }
  }
}
```

For every other attribute name the JSONSerializer does just that! But in case the `type` attribute is used, the JSONSerializer returns:
```javascript
data: {
  id: "something",
  ... // other props
  relationships: {
    type: {
      date: {
        id: "something",
        type: "associated-related-model" //in my case 'file-type'
      }
    }
  }
}
```
This is plainly wrong, the JSONSerializer ignores the links property!

**Comment by pangratz** [comment]
Can you create an ember-twiddle demonstrating the issue you're having? You can use [this](https://ember-twiddle.com/977d75c718a8cc0c01e5?fileTreeShown=false&numColumns=2&openFiles=application.route.js%2Capplication.template.hbs) as a starting point...

**Comment by jevanlingen** [comment]
I was wrong about this. After creating the Twiddle, I understood my problem was of a different kind. The `type` belongsTo relationship did work in itself, it was another issue i ran into. See #4292!
