### ISSUE TITLE
BooleanTransform should allow null values

### ISSUE THREAD

**Issue by jaaksarv** [emberjs/data#3785]
Currently BooleanTransform converts null values to false. This should not be default behavior. It is common to have nullable boolean values in database that represent situation where value is not yet defined. StringTransform, NumberTransform and DateTransform all support null values, so should BooleanTransform to make things consistent.

**Comment by bmac** [comment]
Hi @jaaksarv. I think you raise a very good point that `BooleanTransform` is the only transform that doesn't support null. Unfortunately, because of semver I don't think this is a change Ember Data could make until 3.0. For now I think the best work around is to define a custom transform that supports nulls. 

```js
// app/transforms/nullable-boolean.js
export default DS.BooleanTransform.extend({
  deserialize: function(serialized) {
    if (serialized === null) {
      return null;
    }
    return this._super(serialized);
  },

  serialize: function(deserialized) {
    if (deserialized === null) {
      return null;
    }
    return this._super(deserialized);
  }
});
```
```js
// app/models/user.js
export default DS.Model.extend({
  isAdmin: attr('boolean'),
  isStaff: attr('nullable-boolean'),
  email: attr('string')
});
```

**Comment by bmac** [comment]
Hi @jaaksarv. I'm going to close this issue because I don't think we can change the behavior of the `BooleanTransform` at this time.

Feel free to reopen or create a new pr if you would like to add a new Transform that supports null.

**Comment by jaaksarv** [comment]
bmac Why closing? It should be fixed in 3.0 as you described above.

**Comment by bmac** [comment]
Ok I will leave it open.

**Comment by fivetanley** [comment]
We should add support for this feature when emberjs/rfcs#1, assuming:

1) Feature flag the deprecations
2) Decide later whether this should be the default
3) Opt in with `{allowNull: true}`

**Comment by bmac** [comment]
This should be solved by https://github.com/emberjs/data/pull/4022 which will be enabled in the next beta.
