### ISSUE TITLE
[Regression] JSONSerializer embedded relationships don't get proper type assignment

### ISSUE THREAD

**Issue by wagenet** [emberjs/data#3786]
When a relationship is embedded the JSON serializer doesn't properly set the `type` key when converting to JSONAPI format.

The issue is at https://github.com/emberjs/data/blob/master/packages/ember-data/lib/serializers/json-serializer.js#L573. `relationshipHash.type` should _always_ get set, even if it wasn't present to begin with.

The fix is super straight-forward, but I'm happy to have someone else take it as it could take a little bit to get through legal review on my current project.

**Comment by wecc** [comment]
The reason for being pretty "relaxed" about the type is that objects (without a type) usually mean there's an embedded record and the normalize hook will take care of it.

Would you be able to provide an example payload causing this to fail? I'd be happy to improve this but I'm unsure if always forcing a type at this stage is the best solution.

**Comment by wagenet** [comment]
I'll investigate this more. The app I'm working on has some customer serializer stuff so it's possible it's accidentally overwriting something it shouldn't be.

**Comment by wagenet** [comment]
While this may be a bug, I don't have enough evidence of it to be sure. Closing for now.
