### ISSUE TITLE
store.push throws with JSONAPI document { data: null } 

### ISSUE THREAD

**Issue by mitchlloyd** [emberjs/data#3790]
The [JSONAPI spec](http://jsonapi.org/format/#fetching-resources-responses-200) indicates that the following payload is a valid response when asking for a has-one relationship from a server:

```json
{"data": null}
``` 

However, when that normalized response makes it to `store.push`, ED throws the following error:

```
Assertion Failed: You must include an 'id' for undefined in an object passed to 'push'"
```

It should be simple to add a failing test case for this in `store-test.js` but I'm getting timeout errors when trying to install the ED dependencies at the moment.

**Comment by wecc** [comment]
Agree, we should fix this.

**Comment by phcoliveira** [comment]
I was just about to post the same thing. I am glad I have found this first.

Just to be sure, JSON API also states that ```{ "data": [] }``` is a valid response for querying collections.

I felt there was something wrong when Ember Data throws the error mentioned by @mitchlloyd, although I am not certain about how this case should be handled.

@wecc, could you explain how the fix should behave? I am guessing that the appropriate callback will be ```.then()``` instead of ```.catch()```.

**Comment by Ramblurr** [comment]
Any idea when this fix will make it into a release?

**Comment by jherdman** [comment]
Perchance did this land in 2.2.0?

**Comment by pangratz** [comment]
@Ramblurr this should be fixed in `2.2.1`.

**Comment by jherdman** [comment]
I think there may be a regression in 2.4.0 with respect to behaviour described in this pull request. I have a model hook like this in an acceptance test:

```javascript
return this.store.queryRecord('some-model', { limit: 1 });
```

Whereas this model hook works with Ember Data 2.3.3, the same test now fails with 2.4.0. I'll see if I can put together a reproduction mini app today.

**Comment by jherdman** [comment]
Like this:

```json
{ "plural_model_name": [] }
```

**Comment by jherdman** [comment]
Apologies for the delay, but I have a reproduction available now.

* Ember Data 2.4 failing https://github.com/jherdman/issue-3790-reproduction/commit/137d9a830b1c7883f39739beca8f06562e8717c7
* Ember Data 2.3.3 working https://github.com/jherdman/issue-3790-reproduction/commit/1f265eae7ab2c4282399ebbd18f534e189da401a

The repo lives here: https://github.com/jherdman/issue-3790-reproduction. Run the app, hit the index page in your browser. Note the Ember Data 2.4 complains about the empty response, whereas 2.3.3 does not.

**Comment by jherdman** [comment]
Hey friends. Should I open a brand new ticket for this?

**Comment by bmac** [comment]
Yes please.
