### ISSUE TITLE
Ember Data should use Ember.create in the 1.13 branch

### ISSUE THREAD

**Issue by bmac** [emberjs/data#3791]
Pr https://github.com/emberjs/data/pull/3689 ported the EmptyObject work into the 1.13 branch used Object.create. Unfortunately, Object.create is not supported by IE8.  We should replace this with Ember.create.

https://github.com/emberjs/data/blob/release-1-13/packages/ember-data/lib/system/empty-object.js#L6

**Comment by pangratz** [comment]
This issue can be closed since #3825 got merged.

**Comment by sly7-7** [comment]
Thanks :)
