### ISSUE TITLE
Ember data DELETE request is being automatically followed by failed GET

### ISSUE THREAD

**Issue by rox163** [emberjs/data#3798]
I have an Ember app with Ember data hooked up to a mirage db for mock data. I'm trying to make a delete request but there is an issue. The Delete request is actually successful but immediately after it, a Get request is made for the same object id that was just deleted. This throws an error as the object cannot be found anymore. 
In my controller - 

```
selectedUsers: Ember.A(),
actions: {
    deleteUser() {
        _.forEach(this.get('selectedUsers'), (user) => {
            this.get('store').find('user', user.get('id')).then((record) => {
                record.destroyRecord();
        }}
}}
```

If I remove the find() call and directly call user.destroyRecord(), it works perfectly. 
After a few days of digging, it seems internally in store.js, the fetch for the find() promise is being flushed after the save [on delete] resulting in the erroneous GET request.

**Comment by alexander-alvarez** [comment]
As a workaround if you already have the user record in store you could try using `this.get('store').peekRecord('user', user.get('id') ) ... `
However, seeing as this is a forEach you might even consider using store.[filter](http://emberjs.com/api/data/classes/DS.Store.html#method_filter)

**Comment by wecc** [comment]
The reason for this is that the user is already present in the store which makes Ember Data resolve the promise immediately and then fire off a backround reload.

I would skip the `find` call and just call `destroyRecord()` – what's the reason for not doing that?

**Comment by runspired** [comment]
Use peek, or override `shouldBackgroundReload`
