### ISSUE TITLE
Difference between normalize and extract?

### ISSUE THREAD

**Issue by FreemanHsu** [emberjs/data#3800]
I was trying to connect to a non-standard rest api backend and met with such problems like, when I tried to **findAll()** I got http response like **{rtn: rtnValue, resourceName: {id: Id, ...}}**, and when I tried to **createRecord()**, I got response like **{rtn: rtnValue, id: newId}**.
I think this is where adapter comes into play but I am not sure which are the proper functions to overwrite. Though there are serveral ways to make it work, but what's the intended way? There are normalize-* functions and extract-* functions and I think they both serve for the same purpose and I am kinda confused...
Thank you in advance!

**Comment by wecc** [comment]
Most of the `extract` hooks have been replaced by the `normalize*Response` hooks that are a part of the New Serializer API.

You can read more about the New Serializer API and the renamed hooks a bit down here http://emberjs.com/blog/2015/06/18/ember-data-1-13-released.html#toc_new-serializer-api-for-custom-serializer-authors

In your case I think `normalizeFindAllResponse` and `normalizeCreateRecordResponse` would be the appropriate hooks to use.

**Comment by pangratz** [comment]
I am going to close this as @wecc has answered the question. If you still have questions I recommend to join the `#-ember-data` channel in the [ember community slack](https://embercommunity.slack.com/).
