### ISSUE TITLE
Automatically inferred inverse relationships potentially harmful?

### ISSUE THREAD

**Issue by Fryie** [emberjs/data#3804]
So while this is [in the docs](http://guides.emberjs.com/v1.13.0/models/defining-models/#toc_explicit-inverses) and so I should have known it, Ember will try to figure out explicit inverse relationships. This caused me some major headaches where I couldn't diagnose why my hasMany relationship would sometimes be emptied out.

Basically I had a model `vendor` with `subjects: hasMany('subjects')` and a model `subject` with `topVendors: hasMany('vendors')` and I didn't expect Ember to relate the two.

So while disabling this behaviour would be backwards incompatible, maybe raising a warning when Ember tries to guess a relationship would be a good idea? Something like `it seems like you didn't specify the inverse relationship for ..., so Ember assumed ...`. Of course, I could be the only person who ran into this issue, but I suspect there might be others. :)

**Comment by pangratz** [comment]
I think a warning in the console wouldn't hurt...

**Comment by wecc** [comment]
I'm unsure how we would communicate such a change since most of the times the "guess" is correct and this change would display a lot of warnings in many users apps.

**Comment by runspired** [comment]
@wecc @igorT this sort of thing is what I was attempting to combat in my defense of moving to an "always explicit" relationship setup.

**Comment by bmac** [comment]
We currently have a warning for when Ember Data auto infers a reflexive relationship. https://github.com/emberjs/data/blob/c9d8212c857ca78218ad98d11621819b38dba98f/tests/integration/inverse-test.js#L129-L145

**Comment by wecc** [comment]
PR: #2712 ^

**Comment by hjdivad** [comment]
@wecc @bmac can we close this?

**Comment by runspired** [comment]
There are still situations where this trolls people I believe. @hjdivad

**Comment by stefanpenner** [comment]
> There are still situations where this trolls people I believe. @hjdivad

this is true, but looks to have gone stale. If someone wants to improve apon this, I welcome them. But no need hoarding this issues forever:P

**Comment by runspired** [comment]
@stefanpenner I think when I looked into it those warnings are swallowed for anyone who extends adapters or some such
