### ISSUE TITLE
Polymorphic belongs-to relation model is not serialized in Ember-data v1.13

### ISSUE THREAD

**Issue by maheshiv** [emberjs/data#3806]
Hi team, we moved our app to ember-data v1.13.8 (We are using rest adapter) everything is working as expected but polymorphic belongs-to relation model is not serialized. I followed this https://github.com/emberjs/data/blob/master/TRANSITION.md#polymorphic-relationships. But when i changed data from  
{
  "message": 12,
  "messageType": "post"
}
to 
{
  "message": {id: 12, type: 'post'}
}
it will work. This may be an issue or is there any work around for this?

**Comment by pangratz** [comment]
I am not too familiar with the polymorphic stuff, but can you show me your use case? Here is a JSBin for a start: http://emberjs.jsbin.com/xigilu/edit?html,js,output
