### ISSUE TITLE
JSONAPI Adapter not sending undefined attributes.

### ISSUE THREAD

**Issue by webPapaya** [emberjs/data#3807]
Hey JSONAPI adapter is removing attributes from the payload when they're undefined. In the application I'm working on right now I need to unset an attribute in our database. 

````javascript
  this.get('group').set('disabledAt', undefined);
  this.get('group').save();
````

In the request payload the disabledAt is not sent to the server. The stange thing is that this.get('group') serialize includes the disabledAt attribute.

Is there any way to prevent the removal of the disabledAt attribute from the payload? Thanks

I'm on Ember 1.13.6 and Ember-Data 1.13.13

**Comment by topaxi** [comment]
Thing is, [JSON](http://json.org/) does not know `undefined`, therefore no value will be sent. Have you tried setting it to `null`?

**Comment by webPapaya** [comment]
The issue is that the serializer automatically converts null to undefined. 

````javascript
this.get('group').set('disabledAt', null);
this.get('group').serialize(); // {..., attributes: {disabledAt: undefined}}
````

**Comment by webPapaya** [comment]
To fix this issue I overwrote the application serializer that he automatically converts all undefined into null. 
I actually think that this should be the default behaviour.

**Comment by webPapaya** [comment]
> null values being serialized to undefined sounds like a bug to me. @wecc

I actually thought that this is the desired behaviour, that everything is converted to undefined.

**Comment by wecc** [comment]
Using `JSONAPIAdapter` + `JSONAPISerializer` with Ember 2.0.0 and Ember Data 2.0.0 I'm getting the following results:

```js
author.set('name', null);
author.serialize(); // => { ..., attributes: { name: null } }
```

```js
author.set('name', undefined);
author.serialize(); // => { ..., attributes: { name: null } }
```

**Comment by webPapaya** [comment]
ok sorry i didn't mention I'm on Ember 1.13.6 and Ember-Data 1.13.13 I'll create a jsbin this afternoon to replicate this.

**Comment by bmac** [comment]
I made a jsbin to demonstrate the existing attribute serialization behavior. http://emberjs.jsbin.com/cirifa/edit?html,css,js,output

Currently the only case where an undefined attribute does not get serialized is when there is no transform defined for the attribute (no transform is always treated as a noop). 

Defining a transform for an attribute that converts `undefined` to `null` is the recommended solution for this problem.

I'm going to close this issue. Feel free to re-open if I missed something.
