### ISSUE TITLE
Ember model with a property named "type" is wrongly mapped 

### ISSUE THREAD

**Issue by fabienbk** [emberjs/data#3822]
This only happens when the property value is equal to another Model name.

Example:

    MyApp.Foo = DS.Model.extend({
	    type: DS.attr('string')
        ...
    }

    MyApp.Bar = DS.Model.extend({
	    type: DS.attr('string')
        ...
    }

And Given this JSON:

    foo : {
        ...
        type : 'BAR'
        ...
    }
      

Ember Data seems to be confused and won't map correctly the Foo instance. All other fields except the id will be null. 

Renaming the property to something else will fix the problem.

Apologies if it's already logged/documented.

PS: tested on Ember 2.0.2.

**Comment by pangratz** [comment]
What version of ember-data are you using? Looks like #3725 addressed this in `1.13`, and has been ported to `2.x` in #3788 (which is available in `v2.2.0-beta.1`)...

**Comment by fabienbk** [comment]
Oh, okay, i'm just in between: 2.0.2
Thanks!

**Comment by bmac** [comment]
Ember Data 2.1.0 should also include the fix for this issue.

**Comment by pangratz** [comment]
@bmac yep, it [is in `2.1.0` as well](https://github.com/emberjs/data/blob/v2.1.0/packages/ember-data/lib/serializers/rest-serializer.js#L152) :+1:

**Comment by pangratz** [comment]
I think this issue can be closed since a fix is available in `2.1.0`.
