### ISSUE TITLE
Creating a new record not updating model.

### ISSUE THREAD

**Issue by jpoiri** [emberjs/data#3826]
Hi there,

I have an issue when I create a new challenge it's persisted however when I transition back to challenges route it doesn't not display the newly created challenge.  I am using Ember Data 1.13.12

          //new.js controller

          let excluded = new Ember.A();

          if (this.get('activityType') !== 'all') {
                 // Checks if the user has  excluded some activities from the list
                 excluded = this.getExcludedActivities(this.get('jsTreeObject').jstree(true));
          }

          var challenge = this.store.createRecord('challenge', {
				name_en: this.get('model.name_en'),
				name_fr: this.get('model.name_fr'),
				description_en: this.get('model.description_en'),
				description_fr: this.get('model.description_fr'),
				end_date: this.get('model.end_date'),
				start_date: this.get('model.start_date'),
				points_cap: this.get('model.points_cap'),
				points_goal: this.get('model.points_goal'),
				challenge_type: 1,
				short_description_en: this.get('model.short_description_en'),
				short_description_fr: this.get('model.short_description_fr'),
				excluded_activities: excluded
			});

           // Attempt to find the league.
          this.store.findRecord('league', this.get('userProfile.league_id')).then((league) => {
			
                      //set the league.
	              challenge.set('league', league);

                       // Persist record.
		      challenge.save().then((challenge) => {
			     this.transitionToRoute('challenges')
		      }).catch((error) => {
			     this.handleError(error, 'error.system_error');
		      });
          });

          // challenges.js route
          import Ember from 'ember';
          import AuthenticatedRouteMixin from 'simple-auth/mixins/authenticated-route-mixin';
          import UserProfile from '../models/user-profile';

          export default Ember.Route.extend(AuthenticatedRouteMixin,{

	         userProfile: UserProfile.create(),

 	         model: function() {
		      return this.store.query('challenge', {league_id: this.get('userProfile.league_id')});
                 },
          });

         //router.js
          import Ember from 'ember';
          import config from './config/environment';

          var Router = Ember.Router.extend({
              location: config.locationType
          });

       Router.map(function() {
            this.route('challenges', function() {
            this.route('new');
               this.route('challenge', {
                    path: ':challenge_id'
               }, function() {
                    this.route('delete');
                     this.route('edit');
               });
         });
      });

     export default Router;

**Comment by pangratz** [comment]
As far as I can tell, you are getting all challenges via `store.query()`, which asks the server for the list of challenges. Can you confirm that the created challenge is included in the response of the `query()`, when you transition back into the `challenges` route?

Having a working example would be awesome in tracking the issue down. Can you reproduce your issue in a JSBin http://emberjs.jsbin.com/lavacavige/edit?html,js,output?

**Comment by pangratz** [comment]
Here is a minimal, working sample of your use case, as far as I understand: http://emberjs.jsbin.com/yidudo/1/edit

**Comment by jpoiri** [comment]
From what I can tell the new challenge is returned from the store. When I refresh the screen the new challenge is displayed in the list. Its only when I create a new challenge transition to challenges route its not displayed

**Comment by pangratz** [comment]
> Its only when I create a new challenge transition to challenges route its not displayed

Can you confirm that the newly created challenge is in the response for `this.store.query('challenge', {league_id: this.get('userProfile.league_id')});`?

**Comment by jpoiri** [comment]
Yes the new recorded is in the response, however its look like model hook is not called when I transition to challenges.

**Comment by jpoiri** [comment]
The only way I am able to get it to be added to the list after creating the record is doing push the object in the challenges route model but that causes a issue when I try to delete the record after

//this.get('challenges.model').pushObject(challenge._internalModel);

**Comment by pangratz** [comment]
What does your `router.js` look like? Can you update the JS Bin so your route hierarchy is represented? As you already said, the model hook is not called, so I assume that the `challenges` route is a parent route of your `new` route, where you create the new challenge?

**Comment by jpoiri** [comment]
I have updated the post with my router.js. Yes the new challenge route is parent of the challenges route

**Comment by pangratz** [comment]
Ok, so as you already said, the model hook is no more called. One solution would be to return the result of [`store.filter`](http://emberjs.com/api/data/classes/DS.Store.html#method_filter), which' content gets updated when a new record is added to the store. Something like (untested):

``` js
// routes/challenges.js
model: function() {
  const leagueId = this.get('userProfile.leagure_id');
  return this.store.filter('challenge', {
    league_id: leagueId
  }, function(challenge) {
    return challenge.get('league_id') === leagueId;
  });
}
```

**Comment by jpoiri** [comment]
Ok I will try that, is there a different internally between filter and the query method?

**Comment by pangratz** [comment]
The result of a `query` is never updated; the result of `filter` updates based on the passed filter function and is re-evaluated every time a record of the specified type is added or modified.

**Comment by jpoiri** [comment]
Thank you, that fixed my problem :)

**Comment by pangratz** [comment]
Nice! Glad it works now!
