### ISSUE TITLE
JSON:API Loaded data not retrievable in template 

### ISSUE THREAD

**Issue by Finhas** [emberjs/data#3836]
The app route:

````
model: function(params) {
    return this.store.queryRecord('app', {
      'include': 'responsibilities',
      filter : {
        id : params.app_id
      }
    });
}
````

The model:

````
import DS from 'ember-data';

export default DS.Model.extend({
  name: DS.attr('string'),
  description: DS.attr('string'),
  responsibilities: DS.hasMany('responsibility', {async : false})
});
````

The request:

`http://localhost:3000/api/v3/apps?filter%5Bid%5D=3539&include=responsibilities`

````javascript
{
"data": [
{
"id": "3539",
"type": "apps",
"links": {
"self": "http://localhost:3000/api/v3/apps/3539"
},
"attributes": { … }
}
],
"included": [
{
"id": "2182",
"type": "responsibilities",
"links": { … },
"attributes": { … },
"relationships": { … }
},
{
"id": "36729",
"type": "responsibilities",
"links": { … },
"attributes": { … },
"relationships": { … }
},
....
````

But this 

````
{{#each model.responsibilities as |responsibility|}}
    <p>{{responsibility.id}}</p>
{{/each}}
````
returns nothing.

Ember inspector for Chrome also sees the responsibilities. Not sure what is going on. This is also happening for other `hasMany` attributes for records.

Ember 2.1.0
Ember Data 2.1.0

**Comment by jcope2013** [comment]
just a stab at a fix 

```
app/serializers/app.js

import DS from 'ember-data';

export default DS.JSONSerializer.extend(DS.EmbeddedRecordsMixin, {
  attrs: {
    responsibilities: {
      serialize: false,
      deserialize: 'records'
    }
  }
});
```

**Comment by Finhas** [comment]
Thanks @jcope2013 but that didn't work... I tried something similar to that earlier today too.

If the record and attributes are already in the store, why wouldn't it 'pull out' the embedded records?

**Comment by wecc** [comment]
`this.store.queryRecord()` expects a single record back, not an array (`data: {}` vs `data: []`).

I can see that your primary data does not have any relationships, how are you connecting apps with responsibilities? What does the responsibilities' `relationships` look like?

**Comment by Finhas** [comment]
Thanks @wecc-- changed the route to findRecord which returns the single data object `{}`: 
`return this.store.findRecord('app', params.app_id, { adapterOptions: { query: { include: 'responsibilities' } } });`

Used your 'fix' for `findRecord` from here:
https://github.com/emberjs/data/issues/3596#issuecomment-126604014

As far as the relationships, yes, the primary data does not contain any. Unless ember-data explicitly needs the relationship top-level membership, json:api says it's optional:

 `http://jsonapi.org/format/#document-resource-objects`

`In addition, a resource object *MAY* contain any of these top-level members: … relationships`

The `responsibilities` relationships are listed below (which do not reference the app):
```
relationships": {
-"asset": {
+"links": { … }
},
-"party": {
+"links": { … }
},
-"role": {
+"links": { … }
},
-"versions": {
+"links": { … }
},
-"modifications": {
+"links": { … }
}
}

**Comment by Finhas** [comment]
So the answer is yes, ember-data's json:api serializer requires the `relationship` membership...

**Comment by wecc** [comment]
> So the answer is yes, ember-data's json:api serializer requires the relationship membership...

If you want Ember Data to be able to connect your relationships you have to specify them somewhere. Either on the primary or the related side. Putting resources in `included` doesn't automatically connect them to the primary data.

**Comment by Finhas** [comment]
Understood but the behavior was different in ember-data 1.x; `included` resources weren't fetched from the store but calling them in the template would trigger `get` based on the linked data of the resource. 

Yes, this is more efficient.

**Comment by wecc** [comment]
That was due to a bug where ED used links even if local data was present (see #3380). This was fixed in #3762 and cherry-picked to 1.13 in 1.13.13.

**Comment by Finhas** [comment]
Makes sense. I actually had modified ED to look at the local store for the included data before trying to fetch the data through the links. Thanks for the explanation @wecc

**Comment by wecc** [comment]
np @Finhas, can this be closed?
