### ISSUE TITLE
JSONAPI - Remove relationships from a record

### ISSUE THREAD

**Issue by SeyZ** [emberjs/data#3877]
According the the JSONAPI spec, I would like to delete relationships from a record.

> If the client makes a DELETE request to a URL from a relationship link the server MUST delete the specified members from the relationship or return a 403 Forbidden response.

The example of the spec is exactly my usecase:

```
DELETE /articles/1/relationships/comments HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "data": [
    { "type": "comments", "id": "12" },
    { "type": "comments", "id": "13" }
  ]
}
```

How can I do this in Ember-data? Is it possible?

**Comment by salmanahmad** [comment]
I'm facing the same issue and would love to know how / if this is possible as well.

**Comment by SeyZ** [comment]
Ping ?

**Comment by wecc** [comment]
ED does not support DELETE requests to relationship's `self` links at the moment.

**Comment by SeyZ** [comment]
Is there a plan/roadmap to implement this? Is there a workaround? Thanks for help :)

**Comment by ryrych** [comment]
@wecc ping :)

**Comment by wecc** [comment]
There's currently no roadmap on when this is going to be implemented.

**Comment by wecc** [comment]
I'm closing this issue as `self` links for relationships are tracked in #2905
