### ISSUE TITLE
Wrong adapter used for retrieving related records

### ISSUE THREAD

**Issue by dguettler** [emberjs/data#3878]
Scenario: 

`File` belongs to `User`, user association is provided via `{ links: { user: url } }` in the payload for file.
When file tries to retrieve user `file.get('user')` the adapter for `file` is used instead of the adapter for `user`.
This result in call to wrong API end point if adapter for file and user originate from different API end points.

**Comment by pangratz** [comment]
Hey @dguettler, sorry for the long overdue response.

The adapter of the "parent" of a relationship is used for finding a `belongsTo` or `hasMany` relationship, so I would say `fileAdapter#findBelongsTo` is correctly called here.

One solution for your issue with different API origins would be to use absolute links for the relationships.

Does that help in your case?

**Comment by jmar910** [comment]
@pangratz I'm running into a case where I am using the `links` property, but I need to change the headers for the related resource. Since it is using the parent adapter, it is just going to use the headers for that adapter. Any way around this?

**Comment by pangratz** [comment]
@jmar910 that will be possible with the [`ds-improved-ajax` feature](https://github.com/emberjs/data/pull/3099), which allows you to specify custom headers for a request. See [this ember-twiddle](https://ember-twiddle.com/dfd981a9784ea3a7d932d3b21a9e9f1c?fileTreeShown=false&numColumns=2&openFiles=adapters.person.js%2Croutes.application.js) for an example on how to do that.

**Comment by wecc** [comment]
I'm closing this issue since the solution from @pangratz should work, feel free to re-open if not.
