### ISSUE TITLE
Is the JSONAPIAdapter is not following the JSON API standard request headers?

### ISSUE THREAD

**Issue by tsteuwer** [emberjs/data#3880]
Per the specification:

> http://jsonapi.org/format/#content-negotiation-servers
> Servers **MUST** respond with a `406 Not Acceptable` status code if a request's `Accept` header contains the JSON API media type and all instances of that media type are modified with media type parameters

**Example Request Headers**
```
POST /api/people HTTP/1.1
Host: 127.0.0.1:3000
Connection: keep-alive
Content-Length: 170
Accept: application/vnd.api+json
Origin: http://127.0.0.1:4200
CSP: active
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.132 Safari/537.36
Content-Type: application/vnd.api+json
Referer: http://127.0.0.1:4200/
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8
```

Or, am I not understanding this correctly? Should the Accept header not be there or is it only supposed to respond 406 if it includes type parameters like `version=1.0` or something?

**Comment by wecc** [comment]
> Servers **MUST** respond with a 406 Not Acceptable status code if a request's Accept header contains the JSON API media type _and all instances of that media type are modified with media type parameters_

This means that the `Accept` header has to contain `application/vnd.api+json` once without media type parameters. If you want to provide `version=1.0` as a parameter the correct `Accept` header would be:

```
Accept: application/vnd.api+json, application/vnd.api+json; version=1.0
```

**Comment by tsteuwer** [comment]
Thanks.
