### ISSUE TITLE
Inflector rules

### ISSUE THREAD

**Issue by fsmanuel** [emberjs/data#3881]
@corrspt reported https://github.com/stefanpenner/ember-inflector/issues/91

I did some digging and found an inconsistency in the way we use `pluralize`.
Sometimes we use `Ember.String.pluralize` ([here](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/adapters/build-url-mixin.js#L282) and [here](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/adapters/json-api-adapter.js#L111)) and in the serializer we import from `ember-inflector` ([here](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/serializers/json-api-serializer.js#L7)).

It seems that they use different instances. `Ember.String.pluralize` doesn't use the new inflection rules.

related #3802, #3730

**Comment by fsmanuel** [comment]
as i posted in slack:

```js
// inside an app:
console.log(Ember.Inflector.inflector);
// => ember$inflector$lib$lib$system$inflector$$Inflector

// inside ember data
console.log(Ember.Inflector.inflector);
// => Inflector
```

**Comment by fivetanley** [comment]
fixed by https://github.com/emberjs/data/pull/3888
