### ISSUE TITLE
#extractMeta documentation references deprecated method

### ISSUE THREAD

**Issue by Fryie** [emberjs/data#3882]
It appears the documentation for [#extractMeta](http://emberjs.com/api/data/classes/DS.JSONSerializer.html#method_extractMeta) is outdated. It references the store#setMetadataFor method, but that appears to be deprecated, at least in [1.13](https://github.com/emberjs/data/blob/v1.13.14/packages/ember-data/lib/system/store.js#L1502). In more recent versions, that method seems to have been removed entirely?

**Comment by wecc** [comment]
Yeah, the example is outdated. `extractMeta` is supposed to return an object with the metadata instead of calling `setMetadataFor`

**Comment by Fryie** [comment]
thanks @wecc. Can you maybe give me a more complete example? My use case is the following: I want to save a "rating", and the response should return an "averageRating" property that I can access afterwards. I couldn't get it to work so far.

(btw the same outdated example also appears in the RESTSerializer's apidoc, and probably elsewhere too. Maybe even in the guides, I'm not sure.)

**Comment by wecc** [comment]
I'm closing this issue since #4274 has been merged.
