### ISSUE TITLE
Pass query params to `normalizeResponse` method?

### ISSUE THREAD

**Issue by trentmwillis** [emberjs/data#3884]
Currently there are a variety of params being [passed through to the `normalizeResponse`](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/store/serializer-response.js#L73) method on serializers, but nothing related to queries.

I was wondering if it would be possible to add support for passing query params into the `normalizeResponse` method? We have run into an issue where it would be nice for the serializer to have information about the query params sent for a request in order to normalize the data properly. If this is not possible, then why?

**Comment by JackCA** [comment]
I've stumbled upon this issue when trying to figure out why or how `normalizeQueryResponse` and `normalizeQueryRecordResponse` do not include a `query` object representing...

**Comment by bstro** [comment]
+1, would love support for this.

**Comment by bstro** [comment]
+1, would love support for this. @JackCA @trentmwillis anyone find a workaround?

**Comment by nrcjbarry** [comment]
I'm needing access to the query params in `normalizeResponse` as well.

**Comment by nrcjbarry** [comment]
With the help of Avrohom Katz in on the Ember Slack channel, here is the workaround I'm using.

You need to override the `query` method of your `adapter` for that specific model, and add the query params to the response:
```js
query (store, type, query) {
  return this._super(...arguments).then((response) => {
    response.queryParams = query;
    return response;
  });
}
```

Now, back in the `normalizeResponse` method, you can pluck off that parameter and then remove it from the payload:

```js
normalizeResponse(store, primaryModelClass, payload, id, requestType) {
  let queryParams = payload.queryParams;
  delete payload.queryParams;
}
```

**Comment by barryofguilder** [comment]
With the help of Avrohom Katz in on the Ember Slack channel, here is the workaround I'm using.

You need to override the `query` method of your `adapter` for that specific model, and add the query params to the response:
```js
query (store, type, query) {
  return this._super(...arguments).then((response) => {
    response.queryParams = query;
    return response;
  });
}
```

Now, back in the `normalizeResponse` method, you can pluck off that parameter and then remove it from the payload:

```js
normalizeResponse(store, primaryModelClass, payload, id, requestType) {
  let queryParams = payload.queryParams;
  delete payload.queryParams;
}
```

**Comment by runspired** [comment]
After discussion we feel it would be too complex to continue to add arguments to the method signature.  We are going to close this issue in favor of replacing the current adapter/serializer paradigm with one that preserves more context around the request being processed.
