### ISSUE TITLE
ember 2.X this.get('model').addObjects(records); throw excption "Uncaught TypeError: internalModel.getRecord is not a function"

### ISSUE THREAD

**Issue by tomarsamar** [emberjs/data#3886]
Afrer updating to ember 2.X, this.get('model').addObjects(records); throw excption "Uncaught TypeError: internalModel.getRecord is not a function"

```
 load_more: function(){
 var self = this;
  this.get("store").query("actor",{pg: 1}}).then(function(records) {

    self.get('model').addObjects(records); // this throw excepton 
   
  }
}
```
this was working perfectlly but now self.get('model').addObjects(records); throw excption "Uncaught TypeError: internalModel.getRecord is not a function" in record-array.js at line 86 "return internalModel && internalModel.getRecord()". I tried using self.get('model').pushObjects(records) but it also give same error

**Comment by jcope2013** [comment]
https://github.com/emberjs/data/issues/3530

**Comment by fivetanley** [comment]
Closing because as @tchak said in #3530, query adapter populated record arrays are intended to be immutable. I opened #4045 to improve the error messaging. You can use `toArray()` if you want to copy it and then mutate that.

**Comment by ckl1989** [comment]
@fivetanley Hi, should the error message be updated for this.findAll() as well? I am getting the same error for a recordArray returned from findAll().
