### ISSUE TITLE
JSON API not serializing hasMany relationship 

### ISSUE THREAD

**Issue by sescobb27** [emberjs/data#3892]
Hi, we are upgrading to Ember 1.13 using Ember Data 1.13 and we have the following models

models/order.js
```js
import DS from 'ember-data';

var attr = DS.attr;

export default DS.Model.extend({
  orderType: attr('string'),
  plan: DS.belongsTo('plan', {
    async: false
  }),
  details: DS.hasMany('order-detail', {
    async: true,
    inverse: 'order'
  }),
  customer: DS.belongsTo('customer', {
    async: true,
    inverse: 'orders'
  })
});
```

models/order-detail.js
```js
import DS from 'ember-data';

var attr = DS.attr;

export default DS.Model.extend({
  sku: attr('string'),
  quantity: attr('number'),
  price: attr('number'),
  total: Ember.computed('quantity', 'price', function () {
    return this.get('price') * this.get('quantity');
  }),
  size: attr('string'),
  product: DS.belongsTo('product', {
    async: true
  }),
  order: DS.belongsTo('order', {
    async: true,
    inverse: 'details'
  })
});
```
when we try to create an order detail `orderDetail.save()` it makes a POST request with the following payload
```json
{
  "data":{
  "attributes":{
    "sku":"FC-fey-11-00",
     "quantity":1,
     "price":4000,
    "size":"00"
  },
  "relationships":{
    "product":{
      "data":{
        "type":"products",
        "id":"1"
      }
    },
    "order":{
      "data":{
        "type":"orders",
        "id":"1445972727491"
      }
    }
  },
  "type":"order-details"
  }
}
```

but if we try to save an order `order.save()` it omits `details` key in relationships
```json
{
  "data":{
  "attributes":{
    "order-type":"subscription",
    "production-state":"0",
    "payment-state":"0",
    "shipment-state":"0",
    "created-at":null,
    "ship-date":null,
    "season":"FA15"
  },
  "relationships":{
    "plan":{
      "data":{
        "type":"plans",
        "id":"1-shirt"
      }
    },
    "coupon":{"data":null},
    "address":{"data":null},
    "customer":{"data":null}
  },
  "type":"orders"
  }
}
```

what are we doing wrong? how could we achieve this?
thanks.

**Comment by sescobb27** [comment]
I have tried modifying serializer, but without success. The last thing I have made was this

serializers/order.js
```js
import DS from 'ember-data';

export default DS.JSONAPISerializer.extend({
  extractRelationships: function (modelClass, resourceHash) {
    var relationships = this._super(...arguments);
    console.log('RELATIONSHIPS: ', relationships);
    return relationships;
  }
});
```
and it prints `RELATIONSHIPS:  Object {plan: Object, coupon: Object, address: Object, customer: Object}` it doesn't recognize `details` as a relationship and I don't want to manually serialize that relationship it should be handled automatically by ember-data

**Comment by wecc** [comment]
By default you have to save One-to-Many relationships by saving the record on the "many" side.

If you want to force serialization you can use the `attrs` property in your serializer and set `serialize: true`. See http://emberjs.com/api/data/classes/DS.JSONSerializer.html#property_attrs for more info about the `attrs` property.

**Comment by sescobb27** [comment]
@wecc thanks, that solved the issue. that information should appear in documentation.

**Comment by sescobb27** [comment]
@wecc I'm having another situation, I did what you said but now I'm having this weird behavior:

app/serializers/order.js
```js
import DS from 'ember-data';

export default DS.JSONAPISerializer.extend({
  attrs: {
    details: {
      serialize: true
    }
  }
});
```
![screen shot 2015-10-31 at 9 23 29 am](https://cloud.githubusercontent.com/assets/1157892/10864120/1f8d39b6-7fb1-11e5-8b96-50f873da8f75.png)

![screen shot 2015-10-31 at 9 27 59 am](https://cloud.githubusercontent.com/assets/1157892/10864129/ca04d778-7fb1-11e5-9cb5-ce1587763d47.png)

Is there something I'm forgetting or what I'm doing wrong?. thanks

**Comment by wecc** [comment]
@sescobb27 can you explain a bit more what you are trying to do?

**Comment by sescobb27** [comment]
@wecc sorry for wasting your time, it was my fault I was sending a wrong serialized response to ED.

**Comment by sly7-7** [comment]
@sescobb27 If I understand, this issue could be closed ?
