### ISSUE TITLE
JSON API Errors Object

### ISSUE THREAD

**Issue by sescobb27** [emberjs/data#3893]
Hi, we are migrating to Ember 1.13 and Ember Data 1.13 but we are having issues with JSON API error objects in tests:

``` js
test('Error on contact us form submition', function (assert) {
  server.respondWith('POST', apiUrl + '/customer-supports', function (xhr) {
    xhr.respond(422, {
      'Content-Type': 'application/vnd.api+json'
    }, JSON.stringify({
      errors: [
        {
          status: '422',
          title: 'Error Sending Email, Please try again!!!',
          detail: 'Error Sending Email, Please try again!!!',
          source: {
            pointer: 'data/attributes/email'
          }
        }
      ]
    }));
  });
```

``` js
import Ember from 'ember';

export default Ember.Route.extend({
  actions: {
    contactUsFormSubmit: function () {
      customerSupport.save().catch((error) => {
        console.log(error);
      });
    }
  }
});
```

```
TypeError: ember$data$lib$system$model$internal$model$$get(...).add is not a function
    at InternalModel.ember$data$lib$system$model$internal$model$$InternalModel.addErrorMessageToAttribute (http://localhost:4200/assets/vendor.js:100040:75)
    at InternalModel.ember$data$lib$system$model$internal$model$$InternalModel.adapterDidInvalidate (http://localhost:4200/assets/vendor.js:100064:18)
    at ember$data$lib$system$store$$Service.extend.recordWasInvalid (http://localhost:4200/assets/vendor.js:101615:23)
    at http://localhost:4200/assets/vendor.js:102349:17
    at tryCatch (http://localhost:4200/assets/vendor.js:67605:14)
    at invokeCallback (http://localhost:4200/assets/vendor.js:67620:15)
    at publish (http://localhost:4200/assets/vendor.js:67588:9)
    at publishRejection (http://localhost:4200/assets/vendor.js:67522:5)
    at http://localhost:4200/assets/vendor.js:43997:7
    at Queue.invoke (http://localhost:4200/assets/vendor.js:11505:16)
```

the exception is thrown in `internal-model.js` when doing `get(record, 'errors').add(attribute, message);` in which record is equal to `customerSupport` model, `attribute` is equal to `email` and message is equal to `'Error Sending Email, Please try again!!!'`

``` js
  addErrorMessageToAttribute: function (attribute, message) {
    var record = this.getRecord();
    get(record, 'errors').add(attribute, message);
  },
```

what are we doing wrong? thanks

**Comment by buritica** [comment]
hey @igorT would you happen to know how we can approach this?

**Comment by igorT** [comment]
cc @tchak @wecc

**Comment by drspaniel** [comment]
@sescobb27 This is a hunch, but did you put an 'errors' property on your model? By default it is an instance of [DS.Errors](http://emberjs.com/api/data/classes/DS.Errors.html) which has an add method. If you've accidentally replaced this with your own errors property, the `add` method it's looking for would be missing. Can you include your model code as well?

**Comment by tchak** [comment]
Yes this looks definitely as `errors` being redefined on the model.

**Comment by sescobb27** [comment]
@drspaniel, we are using `ember-validations` from dockyard, and in did they modify the `errors` attribute in the models.
```
export default DS.Model.extend(EmberValidations.Mixin, {
    ...
})
```

**Comment by drspaniel** [comment]
@tchak Is there a way we can raise a warning if a user defines an errors attribute on a model?

**Comment by drspaniel** [comment]
@sescobb27 EmberValidations isn't meant to be mixed in with the model. Mix it into your controller or your component instead

**Comment by sescobb27** [comment]
@drspaniel :disappointed: so, do I need to copy/paste those validations in every controller where I need them?

**Comment by drspaniel** [comment]
@sescobb27 You can create a mixin with just that validations hash, then mix that into your controllers.
```
export default Ember.Controller.extend(EmailValidationsMixin, {
...
});
```
 I work at dockyard btw, and we're talking right now about how we can make this clearer in the documentation

**Comment by tchak** [comment]
@drspaniel we can definitely add a warning if someone overrides `errors` object. @igorT @bmac are you ok with such warning?

**Comment by drspaniel** [comment]
I'd love a commit in ED, let me do the PR?
My intuition would be to warn on the entire list of properties. Any reason not to?
Maybe some should be warns, and others raise errors?
```
adapterError
attributes
dirtyType
errors
fields
hasDirtyAttributes
id
isDeleted
isEmpty
isError
isLoaded
isLoading
isNew
isReloading
isSaving
isValid
modelName
relatedTypes
relationshipNames
relationships
relationshipsByName
transformedAttributes
```

**Comment by tchak** [comment]
I am not sure about the general case...

And in your list there is a lot of static attributes/methods. I would not care much about them.

**Comment by oleg-andreyev** [comment]
@drspaniel you are saying that `EmberValidation` shouldn't be mixed with `Model`, but after reading [this article](https://dockyard.com/blog/2014/04/30/understanding-validation-graphs), I have mixed feelings about it... 

How then we can validation complex graphs?
Having ability to validated complex graph is a MUST HAVE feature.

**Comment by bcardarella** [comment]
@tchak @igorT please no warning when overriding `errors`

**Comment by drspaniel** [comment]
@oleg-andreyev that's true, the post does leave an open ended question. I'm not sure we ever resolved it. The ember-validations repo would probably be a better place for that discussion though.

**Comment by drspaniel** [comment]
@bcardarella why not? It causes ED to crash if you override it?

**Comment by bcardarella** [comment]
@drspaniel if overriding the `errors` object causes ED to crash that that be seen as an ED issue. We should be able to override `errors` with an API compliant object and not get warnings. Adding the warnings now is going to create problems later

**Comment by bcardarella** [comment]
@oleg-andreyev I'm not following your logic. We don't need to have validations in models to get the validation graph. The validations can be allowed on any property path that can go to any other validate-able object

**Comment by drspaniel** [comment]
@bcardarella in this case we're not overriding with an API compliant object though. We could check for API compliance and only warn if it doesn't match? My worry is that domain 'errors' properties are probably not uncommon, and we should guard against accidental overrides.
We could fix this so it doesn't crash, but it will still result in ED behaving differently than normal if you override the property.

**Comment by sescobb27** [comment]
@bcardarella @drspaniel what about overriding `errors` in `ember-validation` with a `DS.Error` instance object?

**Comment by bcardarella** [comment]
@drspaniel per semantic versioning if a feature is added (like this warning) it cannot be removed until the next major version. The issue in this case is with ember-data's compatibility with ED's errors object. When this issue is resolved users shouldn't be getting a warning.

**Comment by bcardarella** [comment]
@sescobb27 that is one possibility I have been exploring. @rwjblue has made the same case to me

**Comment by bcardarella** [comment]
However, I am still leaning towards an overwrite of the ED errors object entirely as I don't think it meets the complexity that is necessary for validation messaging, at least in the way that ember-validations intends

**Comment by drspaniel** [comment]
@bcardarella I think there's a case to be made for protecting the average developer from naively adding an `errors` property to their model without understanding the consequences

**Comment by sescobb27** [comment]
The thing is I didn't override the `errors` attribute but instead I have all my models mixed with ember-validations 'cause that's the most natural way of handling that, I will refactor my app in order to make those validations in our components, `Controllers` are going to be removed in coming releases, but maybe some other people are going to face this same issue as I did, that's why I think that complexity matter.

**Comment by bcardarella** [comment]
@drspaniel you could make that case for pretty much every piece of public API

**Comment by rwjblue** [comment]
> @rwjblue has made the same case to me

Super minor correction here: my suggestion was to extract a shared object (not in ember-data's repo) that can be used by both projects.  I am not 100% certain that the current `DS.Errors` will do all of the things that ember-validations needs/wants (though it may, I haven't dug into it a bunch lately).

**Comment by bcardarella** [comment]
@rwjblue I agree, I do think, however, that it can respond to the same API that ED expects but do its own thing under the hood

**Comment by rwjblue** [comment]
Ya, makes sense

**Comment by tchak** [comment]
Good news is, we are moving away from complex event mechanics in `DS.Errors` that could make harder to integrate with it (see #3853). By doing that we decorrelating `DS.Errors` from invalid state transitions.

**Comment by bcardarella** [comment]
@tchak that's great news :)

**Comment by OpakAlex** [comment]
own API it's Ember way guys! More own api, and soon you will 0 users.

**Comment by runspired** [comment]
closing as we have no intent on changing the API of `errors`, the path forward is full deprecation and removal of `@ember-data/model`. Folks who wish to have a nicer errors experience today may either directly access and subscribe to errors from the cache and/or fully replace Model by implementing the instantiateRecord hook (or use an addon like ember-m3 which does so)
