### ISSUE TITLE
given a DS.Model instance no clear way to obtain a model's modelName

### ISSUE THREAD

**Issue by justin-hackin** [emberjs/data#3894]
I'm aware that there is a way to get modelName from a modelFor call (as indicated here: https://github.com/emberjs/data/issues/3472) .  However, given an arbitrary model, there seems to be no simple way for me to find out what kind of model it is.  Before I was using model.get('constructor.modelName') but this doesn't seem to be working any more (maybe in the update to 2.0 it broke ).  Regardless, I think that it would be a good idea to implement a method on models that gives me this info.  I've had to resort to using model.get('_internalModel.modelName') which feels dirty and prone to breaking.  If you have any better suggestions, I welcome them.  Thanks for all your efforts :)

**Comment by corrspt** [comment]
I wanted to second this. I've resorted to adding a "metadata" object on each DS.Model to hold some other stuff

```js

export default DS.Model.extend({

metadata: {
   modelName: 'THE-MODEL-NAME'
   //other metadata
}

});
```

**Comment by wecc** [comment]
I just tried `model.constructor.modelName` with 2.0 and 2.1 and it works as expected.

Would you be able to reproduce a case where it doesn't work?

**Comment by corrspt** [comment]
@wecc : Sorry, in my case `model.constructor.modelName` does work (in version 2.0 and 2.1), but I couldn't find it on the public api. So I assumed it would be a private API and I don't want to rely on it. Hence my post here. Or is it public api?

The closest I could find is [this](http://emberjs.com/api/data/classes/DS.Model.html#property_modelName) but I can't seem to have access to it (I'm not using `modelFor` in that code, I just have access to an instance of `DS.Model`).

**Comment by justin-hackin** [comment]
Returning to this issue, I've confirmed that, oddly, I can now access constructor.modelName ... I suspect I was experiencing a bug with Chrome or the ember inspector.  Sorry to raise this unnecessarily, it's not so much a bug as a 'nice to have' for clarity sake, and thus I'd consider it a low priority.

**Comment by sandstrom** [comment]
@corrspt It's public API. Documented here: http://emberjs.com/api/data/classes/DS.Model.html#property_modelName

**Comment by HeroicEric** [comment]
@corrspt @justin-hackin can this be closed?

**Comment by corrspt** [comment]
@HeroicEric Yup, fine by me. Thanks everyone.

**Comment by sly7-7** [comment]
@HeroicEric @corrspt Thanks for the heads up. Closing
