### ISSUE TITLE
BuildURLMixin drops query params

### ISSUE THREAD

**Issue by swalkinshaw** [emberjs/data#3895]
I'm using `adapter.buildURL` for a non-standard URL and I was following through the [file](https://github.com/emberjs/data/blob/v1.13.14/packages/ember-data/lib/adapters/build-url-mixin.js) (in 1.13.14) to see if there was a nicer way to specify query params than manually for the ajax call.

`query` is listed as a [param](https://github.com/emberjs/data/blob/v1.13.14/packages/ember-data/lib/adapters/build-url-mixin.js#L49), but if you follow any function call which uses `query` none of the functions actually use it:

```js
urlForQuery: function(query, modelName) {
  return this._buildURL(modelName);
},
```

```js
urlForQueryRecord: function(query, modelName) {
  return this._buildURL(modelName);
},
```

This is no different in 2.1.0 either. I don't know if this is intentional but `query` shouldn't even exist if the option is never used.

**Comment by wecc** [comment]
The private `_buildURL` method doesn't use `query` and therefor it's not being passed. The URL is just based on the modelName. The query is then added [here](https://github.com/emberjs/data/blob/v1.13.14/packages/ember-data/lib/adapters/rest-adapter.js#L525) and [here](https://github.com/emberjs/data/blob/v1.13.14/packages/ember-data/lib/adapters/rest-adapter.js#L497) in the adapter.

If you override `urlForQuery` or `urlForQueryRecord` you're free to inspect `query` and create your URL based off of that.

**Comment by HeroicEric** [comment]
@swalkinshaw does that answer give you what you're looking for? Do you have any further questions?

**Comment by swalkinshaw** [comment]
Haven't had a chance to really look into this more. But going by @wecc's reply, I'll go ahead and close this.
