### ISSUE TITLE
Documentation Outdated

### ISSUE THREAD

**Issue by IsaiahJTurner** [emberjs/data#3896]
http://emberjs.com/api/data/ does not include the `async` option for DS.attr. I don't know if other options are also missing.

**Comment by wecc** [comment]
From what I know `attr` does not have an `async` option?

**Comment by IsaiahJTurner** [comment]
I'm going crazy, you're right @wecc.

**Comment by stefanpenner** [comment]
https://www.youtube.com/watch?v=pygwaX2VNzQ
