### ISSUE TITLE
Inconsistent initialization of relationships

### ISSUE THREAD

**Issue by elwayman02** [emberjs/data#3897]
Ember-Data creates an empty `DS.PromiseObject` on a `belongsTo` relationship when the parent record is initialized, but not a `DS.PromiseArray` on a `hasMany` relationship.

```
export default Model.extend({
  teams: hasMany('team'),
  industry: belongsTo('industry')
});
```

If I `createRecord`, `model.get('industry')` returns a `DS.PromiseObject` with null `content`, but `model.get('teams')` returns `null`. I would prefer they both return null, honestly, but I'm extra confused as to why it's not consistent between them.

**Comment by igorT** [comment]
I would expect get teams to return an empty array, this seems weird.

**Comment by elwayman02** [comment]
I'm seeing this on `2.2.0-beta.1`...haven't tested other versions.

**Comment by pangratz** [comment]
Hey @elwayman02, I cannot reproduce this using `ember-data` `v2.2.0-beta.1`: https://ember-twiddle.com/91e75878af843a3b84f7?openFiles=twiddle.json%2Capplication.route.js

Can you check what is different in your case? Do you use sync relationships?

**Comment by elwayman02** [comment]
@pangratz honestly I am not working on that code anymore, so I don't have a way to test.

**Comment by pangratz** [comment]
I am going to close this as it couldn't be reproduced. @elwayman02 feel free to reopen if you still experience this issue.
