### ISSUE TITLE
Only get 41 records through 'findAll' method?

### ISSUE THREAD

**Issue by chenxiwei** [emberjs/data#3908]
I want to use 'findAll' method to get the record,and I mocked 80 records,But I find the stores only have 
41 objects that parsed.
just like:
![image](https://cloud.githubusercontent.com/assets/3908001/10963167/099267fe-83d9-11e5-8185-f4d4094cae49.png)

![image](https://cloud.githubusercontent.com/assets/3908001/10963184/24b4e584-83d9-11e5-9cc1-d382fbe9fd5c.png)
How can I get all the objects that parsed?

**Comment by wecc** [comment]
Would you be able to provide a failing JSBin/Ember Twiddle?

**Comment by chenxiwei** [comment]
I have solved it,bacause I use 'Mock.Random.integer' to  generate id,but I set range from 60 to 100,so I only can get 41 ids,it means I only can push 41 records in store.=_= Silly me

**Comment by wecc** [comment]
:)
