### ISSUE TITLE
query loses meta for pagination

### ISSUE THREAD

**Issue by krisselden** [emberjs/data#3918]
Looks like only has many record arrays have meta for pagination.

**Comment by pangratz** [comment]
I cannot reproduce and I think this has been fixed. Can you confirm?

See [this ember-twiddle](https://ember-twiddle.com/69a88a1e83c7bcc1a99b?openFiles=application.template.hbs%2Capplication.route.js).

**Comment by bmac** [comment]
@krisselden do you mind taking a look at @pangratz's twiddle and letting us know if we are missing something?

**Comment by bmac** [comment]
@krisselden do you mind taking a look at @pangratz's twiddle and letting us know if we are missing something?

**Comment by pangratz** [comment]
@krisselden I am going to close this issue as it looks like it cannot be reproduced. Feel free to reopen if you think this is still an issue, ideally with an ember-twiddle demonstrating the issue.
