### ISSUE TITLE
Write changelog entry instructing users of the ember cli addon how to update

### ISSUE THREAD

**Issue by fivetanley** [emberjs/data#3921]

**Comment by bmac** [comment]
Notable changes:
- Remove Ember Data from bower
- Update `ember-cli-shims` in bower to `0.1.0`
- with Ember Data beta.4 you need to include `ember-inflector` in your package.json. (Should be fixed in next beta)

**Comment by bmac** [comment]
We should copy the content from the upgrading section in the release blogpost to the changelog. http://emberjs.com/blog/2016/01/12/ember-data-2-3-released.html#toc_changes-in-ember-data-2-3
