### ISSUE TITLE
Add support for singular resources

### ISSUE THREAD

**Issue by ncolgan** [emberjs/data#393]
The Rails Guides have a section on  [singular resources](http://guides.rubyonrails.org/routing.html#singular-resources):

> Sometimes, you have a resource that clients always look up without referencing an ID. For example, you would like /profile to always show the profile of the currently logged in user. In this case, you can use a singular resource to map /profile (rather than /profile/:id) to the show action.

It would be nice if the RESTAdapter supported this kind of resource.

**Comment by venkatd** [comment]
I'm in need of this functionality too. I'd like to be able to request the the current user, application settings, and a number of things for which there is only one instance.

Maybe the solution is to add support for virtual ids (for example an id of 'me' always translates to 456) and add a hook to the store. Not sure how much complexity this would add but I do think singular resources are a pretty common occurrence. Thoughts?

Also how are you guys currently handling this case?
