### ISSUE TITLE
[JSON API] what does/doesn't ED support?

### ISSUE THREAD

**Issue by jamesdixon** [emberjs/data#3932]
Hi,

I was curious if there is a definitive resource as to what ED does and does not support with regards to the current JSON API 1.0 specification? I keep finding myself running into issues where I'm thinking there is a bug with my code or ED only to find out that ED doesn't support a particular part of the specification.

If no such resource exists, I think it might be worth while to put something together. It would be both a great resource for developers using JSON API w/ Ember as well as hopefully preventing new issues from being opened where there is really no issue other than ED not supporting a specific part of the specification at this time.

I'm more than willing to help out, but would obviously need some guidance from the core contributors.

Thanks for all of your hard work.

Cheers.

**Comment by wecc** [comment]
I'm pretty sure no such resource exists but I think this is a great idea. There's #2905 but it's not an exhaustive list. I'd be happy to guide you if you would like to put something together.

**Comment by bmac** [comment]
I'm going to close this. As @wecc said #2905 is the best place to see what parts of JSON API that Ember Data supports.
