### ISSUE TITLE
Going crazy with promises.

### ISSUE THREAD

**Issue by mxrguspxrt** [emberjs/data#3934]
Imagine that I have: 

Post with many comments (async is true). Now when I give post.comments to a component, sometimes they are resolved (array of comments), sometimes they are promisearray, sometimes they are fulfilled promisearray. 

If given to a component, should not be they updated to resolved array of comments at some point?

**Comment by stefanpenner** [comment]
This does not appear to be a bug report, unfortunately we need to keep this issue tracker focused on issues. A much better venue, geared for this is http://stackoverflow.com/

Feel free to tag the SO post and cross post back here. I would recommend providing a concrete example, either via demo or an extremely concise but well defined example.
