### ISSUE TITLE
ajaxOptions is private on adapters, can it be made public?

### ISSUE THREAD

**Issue by adam-knights** [emberjs/data#3939]
AjaxOptions is the only place I can see to add a generic timeout for our web app, e.g.

```
ajaxOptions(url, type, options) {
    let hash = this._super(url, type, options);
    hash.timeout = 20000;
    return hash;
}
```

Is there a particular reason this is private? Can it be made public?

**Comment by wecc** [comment]
It's on the list in issue #3249 to be public.

**Comment by wecc** [comment]
Closing this
