### ISSUE TITLE
CoalesceFindRequests causes troubles

### ISSUE THREAD

**Issue by tschoartschi** [emberjs/data#3942]
EDIT: we are on ```ember data 1.13.12``` and also tried ```ember data 1.13.15```, problem exists in both versions. Without ```coalesceFindRequests: true``` everything is fine

I don't know how to tackle this problem therefore I open an issue here. I have the following problem:

In my template I display items which belongs to a catalog. The catalog relation is async and when Ember is trying to fetch the catalogs a wrong url is built. The url looks like this (if there are three different catalogs):

```
http://API_URL/catalogs/catalogId1,catalogId2,catalogId3?ids[]=catalogId1&ids[]=catalogId2&ids[]=catalogId3
```

or backend expects such requests like this

```
http://API_URL/catalogs?ids[]=catalogId1&ids[]=catalogId2&ids[]=catalogId3
```

how does the ```catalogId1,catalogId2,catalogId3``` part come into the url? How can I debug this issue better? 

item model looks as following:
```javascript
export default DS.Model.extend({
        //...
        catalog: DS.belongsTo('catalog', {async: true, inverse: null})
        //...
});
```

catalog model looks as following:
```javascript
export default DS.Model.extend({
        //...
        items: DS.hasMany('item', {async: true}),
        //...
});
```

template:
```hbs
{{#each items key="@index" as |item| }}
        <div class="basket-item__catalog">{{item.catalog.label}}</div>
{{/each}}
```
I'm not sure if it is a bug or a problem with our application code. Every help is appreciated

**Comment by fivetanley** [comment]
Which adapter are you using? I can't reproduce this with a quick jsbin: http://emberjs.jsbin.com/peqiho/1/edit?html,js,output

**Comment by tschoartschi** [comment]
@fivetanley thanks for your reply! We are still using ```DS.RESTAdapter```. I think the problem arises, if a rerender occurs during fetching the catalogs. But I'm not sure. I also don't know how to isolate this issue better. If you have any tips, just let me know and I'll try to give you better information.

**Comment by fivetanley** [comment]
Are you overriding any adapter methods?

**Comment by tschoartschi** [comment]
Yes the buildURL method:

```javascript
import Ember from 'ember';
import DS from 'ember-data';

export default DS.RESTAdapter.extend({
    coalesceFindRequests: true,
    host: AppWebclientENV.APP.API_ROOT,

    buildURL: function (type, id, snapshot, queryType, query) {
        // record is now a snapshot otherwise we get following errors:
        // DEPRECATION: Usage of `snapshot.constructor` is deprecated, use `snapshot.type` instead.
        // DETAILS: http://emberjs.com/blog/2015/02/14/ember-data-1-0-beta-15-released.html
        if (!query && (!snapshot || // NO Ember.isEmpty possible then --> DEPRECATION
            !snapshot.record)) { // JUST ACCESS RECORD WITHOUT GET SHOULD BE OK: http://emberjs.com/api/data/classes/DS.Snapshot.html#property_record
            return this._super(type, id, snapshot);
        }
        var queryParams = {};
        if (snapshot && snapshot.record && query) {
            AppWebclient.error('Snapshot.record and query defined... what to do?!?');
        }

        if (snapshot && snapshot.record) {
            var record = snapshot.record;
            queryParams = Ember.get(record, 'queryParams');
        }
        
        var queryParamsString = '';
        if (!Ember.isEmpty(queryParams)) {
            var isFirst = true;
            for (var key in queryParams) {
                if (queryParams.hasOwnProperty(key)) {
                    var sep = (isFirst) ? '' : '&';
                    isFirst = false;
                    if (//key !== 'id' &&
                        queryParams.hasOwnProperty(key)) {
                        queryParamsString += sep + key + '=' + queryParams[key];
                    }
                }
            }
        }
        var url = this._super(type, id, snapshot);
        var seperator = (url.indexOf('?') === -1) ? '?' : '&';
        url = (Ember.isEmpty(queryParamsString)) ? url : url + seperator + queryParamsString;
        if (queryType === 'queryRecord' && query.__id__) {
            url += '/' + query.__id__;
            query.__id__ = null;
            delete query.__id__;
        }
        return url;
    },
    shouldBackgroundReloadRecord: function (/*store, snapshot*/) {
        return false;
    },

    shouldReloadAll: function () {
        return true;
    }
});

```

The ``buildURL``` method I override because I need to pass a parameter to findOne, for more details see: https://github.com/emberjs/data/issues/1576#issuecomment-127617470

I hope this isn't causing troubles. Otherwise I have to refactor this code.

**Comment by tschoartschi** [comment]
@fivetanley do you think it has something to do with the ```buildURL``` method? If not let me know how i can provide better feedback

**Comment by tschoartschi** [comment]
@fivetanley ```buildURL``` thanks to the pointer to our custom ```buildURL```. It was really our fault. I forgot to pass ```queryType``` and ```query``` to the super function. So the solution was quite simple

```javascript
//...
this._super(type, id, snapshot, queryType, query);
//...
```

The buildURL code is quite old, this is why I didn't looked at it at the first glance. But with some update of ```ember data``` we introduced this bug.
