### ISSUE TITLE
Better error for when the `type` property is missing from a JSON API response.

### ISSUE THREAD

**Issue by martndemus** [emberjs/data#3945]
Currently it will just throw `Uncaught TypeError: Cannot read property 'replace' of undefined`, because somewhere along the parsing of the response replace is used on the value of `type`.

The error is triggered at: https://github.com/emberjs/data/blob/master/addon/serializers/json-api-serializer.js#L139

**Comment by allthesignals** [comment]
I am getting this error, but I am using the RESTAdapter...
