### ISSUE TITLE
Polymorphism on the model level, not at the association level

### ISSUE THREAD

**Issue by boris-petrov** [emberjs/data#3947]
I'm not sure I understand fully what's going on. Let's say I have a couple of models - `Base` and `Derived` where `Derived` inherits from `Base`.

If I do a `store.findRecord("base", "someId")`, and a record of `Derived` is returned (the JSON is something like `{ "derived": { "id": "someId", "type": "derived", ... } }`), "everything" works fine, i.e. the model can be used as a `Derived` one (I can use properties from `Derived`).

However, let's say I have a model which has a relation to `Base` like so:

``` coffeescript
SomeModel = DS.Model.extend
  base: DS.belongsTo("base", inverse: null, async: true, polymorphic: true)
```

Let's say I get an instance of SomeModel with the following JSON:

``` json
{ "some_model": { "base": "someId" } }
```

Then, if I access the `base` property, e.g. in an HTMLBars template, it acts like a `Base` instance, even when the JSON returned for `someId` is like the one above - i.e. a `Derived` instance (`{ "derived": { "id": "someId", "type": "derived", ... } }`).

My question is - why? I know I can "fix" it by returning:

``` json
{ "some_model": { "base": { "id": "someId", "type": "derived" } } }
```

However this doesn't work for me as I don't know the type of `someId` before I get it from the DB and I don't want to do unnecessary queries. Why is `base` acting as a `Base` model and not a `Derived` one even though the fetch from the server returned a `Derived` instance? Why does it work fine after a fetch via `store.findRecord` but it doesn't work when used via a polymorphic relation? And what can I do to make it work?

**Comment by bmac** [comment]
Hi @boris-petrov.

@igorT put together an RFC https://github.com/emberjs/rfcs/pull/67 a few months ago to address some of the issues's you've mentioned here. However, there we some concerns raised about this initial RFC and it is still in need of some work.

**Comment by kylenathan** [comment]
Hey @bmac - what were the concerns raised? Cant seem to see anything raised at the RFC itself?

**Comment by hschmidt99** [comment]
Comments concerning the rfc are under https://github.com/emberjs/rfcs/pull/67
I'd definitely vote this up since I could use this functionality right now, alas in conjunction with the RESTSerializer which I *hope* will in the future also profit from this somehow.

**Comment by stefanpenner** [comment]
closing in-favor of an RFC
