### ISSUE TITLE
Error: Attempted to handle event `notFound` after store.unload

### ISSUE THREAD

**Issue by dchersey** [emberjs/data#3948]
Hi, 

I am pushing data via a websocket into the store via store.push. That's working great, and I'm loving the real-time sync-up being handled by Ember!

However, I'm getting an error I can't seem to handle when I delete a record and push a notification of that delete to my clients.  I'm using ember-data 2.1.0.

My handler looks like: 

```javascript
            if (data.destroyed) {
                self.store.findRecord('note', data.destroyed).then(function(note) {
                  self.store.unloadRecord(note);
                });
            };
```

This successfully removes the data from the store, but apparently there's still an object left in there in the deleted.saved state. When the route refreshes its model (I can't seem to stop it from doing this), it gets a 404 from my REST backend and tries to perform that transition on the deleted object, yielding: 

```
Error: Attempted to handle event `notFound` on <ui@model:note::ember702:null> while in state root.deleted.saved. 
    at new Error (native)
    at Error.EmberError (http://localhost:3000/assets/ui/assets/vendor.js:24736:21)
    at ember$data$lib$system$model$internal$model$$InternalModel._unhandledEvent (http://localhost:3000/assets/ui/assets/vendor.js:73449:15)
    at ember$data$lib$system$model$internal$model$$InternalModel.send (http://localhost:3000/assets/ui/assets/vendor.js:73327:16)
    at ember$data$lib$system$model$internal$model$$InternalModel.notFound (http://localhost:3000/assets/ui/assets/vendor.js:73284:14)
    at http://localhost:3000/assets/ui/assets/vendor.js:70088:23
    at tryCatch (http://localhost:3000/assets/ui/assets/vendor.js:60720:14)
    at invokeCallback (http://localhost:3000/assets/ui/assets/vendor.js:60735:15)
    at publish (http://localhost:3000/assets/ui/assets/vendor.js:60703:9)
    at publishRejection (http://localhost:3000/assets/ui/assets/vendor.js:60638:5)
```

Any suggestions? I'm new to ember, so maybe I'm not seeing a way to keep the route from trying to refresh its model.  I tried adding a transition to the next higher route but that didn't help. 

```javascript
            if (data.destroyed) {
                self.store.findRecord('note', data.destroyed).then(function(note) {
                  self.store.unloadRecord(note);
                  this.transitionTo('notebooks');
                });
            };
```

I also tried surrounding all my model hooks with try/catch .. still no help. 
I tried catching it on my back end, and the route complained that my API returned empty data.

Thanks!

**Comment by dchersey** [comment]
I just figured out how to avoid this ... not sure if this might still be a bug anyway but the work-around is:

```javascript
            if (data.destroyed) {
                var note = self.store.peekRecord('note', data.destroyed);
                if (note) {
                  self.store.unloadRecord(note);
                }
            }
```

data.destroyed is the id of the destroyed note. Checking makes sure we don't go to the back end to find the non-existent note that was destroyed.

**Comment by fivetanley** [comment]
Hey @dchersey, I apologize for the long delay.

You do want to use peekRecord here. It's the recommended method for returning something from the store if it exists in the store. It doesn't make any network requests.

I don't think this is a bug. Would you mind if we closed the issue?

**Comment by dchersey** [comment]
That's fine, thanks for following up!
