### ISSUE TITLE
DS.Model.reopen can't override the function addErrorMessageToAttribute

### ISSUE THREAD

**Issue by Lit-Yin** [emberjs/data#3951]
I want to override the function addErrorMessageToAttribute in DS.Model to underscore my custom error field name from the server,just like 'ServerSideError' to 'server_side_error'.
Then I write some code like this:
```javascript
	DS.Model.reopenClass({
		addErrorMessageToAttribute: function (attribute, message) {
			alert(attribute);
			alert(message);
			attribute = Ember.String.underscore(attribute);
			this._super(attribute, message);
		}
	});
```
or
```javascript
	DS.Model.reopen({
		addErrorMessageToAttribute: function (attribute, message) {
			alert(attribute);
			alert(message);
			attribute = Ember.String.underscore(attribute);
			this._super(attribute, message);
		}
	});
```
But it doesn't work,and i go to watch the sourse code in ember-data,i find the function is the prototype of 'ember$data$lib$system$model$internal$model$$InternalModel',which is equal DS.InternalModel.

How can i fix this problem.

ember.debug.js:5553 DEBUG: -------------------------------
ember.debug.js:5553 DEBUG: Ember      : 1.13.11
ember.debug.js:5553 DEBUG: Ember Data : 1.13.15
ember.debug.js:5553 DEBUG: jQuery     : 1.11.3
ember.debug.js:5553 DEBUG: -------------------------------

**Comment by Lit-Yin** [comment]
nobody figure out?

**Comment by wecc** [comment]
Instinctively I'd say this is something your serializer should handle for you, but I'm not too familiar with the error parts of ED.

ping @tchak

**Comment by Lit-Yin** [comment]
@wecc thanks.I had read the serializer code in ember-data,but i can't fix this problem yet.

**Comment by tchak** [comment]
@Lit-Yin `addErrorMessageToAttribute` is a private method of private class `InternalModel`. Clearly this is a serializer concern.

**Comment by Lit-Yin** [comment]
@tchak thanks.I had read the code about serializer,it can serializer the property of the model,but it can't serializer the key which is not the property of the model.
How can i fix this problem through serializer concern?

**Comment by ubuntuvim** [comment]
Is it better to rewrite the serialization?
[http://guides.emberjs.com/v2.0.0/models/customizing-serializers/](http://guides.emberjs.com/v2.0.0/models/customizing-serializers/)

**Comment by Lit-Yin** [comment]
@tchak @wecc thanks.I find the way by https://github.com/pangratz/data/commit/a8791733ac54ba0cb6773ebeb46a3aa3319273fc.
It no need to reopen any function.Just add a 'attrs' property with DS.RESTSerializer int the file 'serializers/application'.It will auto serialize the 'ServerSideError' to 'server_side_error' in all model.
```javascript
export default DS.RESTSerializer.extend({
    ...
    attrs:{
        server_side_error:'ServerSideError'
    }
    ...
```
