### ISSUE TITLE
Create record with new hasMany relationship sends empty ids instead of attributes

### ISSUE THREAD

**Issue by andruby** [emberjs/data#3953]
With this Book model:

```js
export default DS.Model.extend({
  title: DS.attr('string'),
  authors: DS.hasMany('author')
});
```

When creating a record with new authors.

```js
var book = this.store.createRecord('book', {title: 'The Ember Way'});
book.get('authors').createRecord({name: 'Jack'});
book.save();
```

The author relationships are serialised as if they were already persisted. The relationship is serialised as a [Resource Identifier Object](http://jsonapi.org/format/#document-resource-identifier-objects).

```json
{
  "data":{
    "attributes":{
      "title":"The Ember Way"
    },
    "relationships":{
      "authors":{
        "data":[
          {"type":"author", "id":null}
        ]
      }
    },
    "type":"book"
  }
}
```

From my understanding of JSONAPI, the unpersisted relationship should be serialised as a [Resource Object](http://jsonapi.org/format/#document-resource-objects) with attributes.

```json
{
  "data":{
    "attributes":{
      "title":"The Ember Way"
    },
    "relationships":{
      "authors":{
        "data":[
          {
            "attributes":{
              "name":"Jack"
            },
            "type":"author"
          }
        ]
      }
    },
    "type":"book"
  }
}
```

**Comment by wecc** [comment]
> The author relationships are serialised as if they were already persisted

This looks like a bug to me. We wouldn't want to serialize new records before they have been saved. Not 100% sure what the correct path here would be.

> From my understanding of JSONAPI, the unpersisted relationship should be serialised as a Resource Object with attributes.

Hm, I don't think "embedded" records in relationships are a thing in JSON API at all? Unsure though. Can you point me to the part of the spec that made you think this is the recommended behavior?

**Comment by andruby** [comment]
@wecc I think you are right. The JSONAPI spec does not explicitly support what I'm trying to do. It seems natural though, and need it to atomically create a new record with relationships. I'll go on the jsonapi discuss to see if they are looking at extending the spec for these kinds of requests. Thanks!

**Comment by andruby** [comment]
@wecc Ember-Data already supports serializing relationships through the [EmbeddedRecordsMixin](http://emberjs.com/api/data/classes/DS.EmbeddedRecordsMixin.html). Thanks to @lolmaus at https://github.com/json-api/json-api/issues/795#issuecomment-159927027

Adding the EmbeddedRecordsMixin was as easy as creating a custom serializer for `Book` from my example:

```js
import DS from 'ember-data'
import ApplicationSerializer from 'face/application/serializer'

export default ApplicationSerializer.extend(DS.EmbeddedRecordsMixin, {
  attrs: {
    author: { embedded: 'always' }\
  }
})
```
