### ISSUE TITLE
Add DS.Store base delegate method to the adapter

### ISSUE THREAD

**Issue by teckays** [emberjs/data#3954]
I'm wondering if I need to extend the `DS.Store` class in order to add a query method like `this.store.search()` for example, would it be possible on the current version? 

This need comes from the fact that I have a `JSONAPIAdapter`-like backend API but with some minor changes.  For example I have a custom route to perform searches on the model `/{model}/search` and none of the existing methods, `findAll()`, `query()` and others help me achieve this functionality without overriding some of them which is not something I really like. 

The build-in `this.store.query()` method works great if I want to query on a specific model field, but for `search()` I'm using a `text` parameter which looks over multiple model fields to find a match.

The best approach in my opinion would be to extend the `DS.Store` class and add a `this.store.search()` method for example that would allow me to automatically search for records on any model.

**Comment by wecc** [comment]
There's currently no built-in way (other than extending) to provide additional methods to the store.

You can use `adapterOptions` to `query()`/`queryRecord()` if you want to communicate with your adapter. Like, if you provide a `search` key your adapter could behave differently.

**Comment by teckays** [comment]
As for now I managed to find this solution:

***/stores/application.js***
``` lang-js
import DS from 'ember-data';

export default DS.Store.extend({
    search: function(modelName, query){
        const adapter = this.adapterFor(modelName);
        const baseUrl = adapter._buildURL(modelName);
        return Ember.$.get(`${baseUrl}/search`, query);
    }
});
```
so any `this.store.search(model, query)` would make a request to `/{model}/search?{query}`. One thing I don't like here is using `Ember.$.get()` method, looks kind of dirty. Is there a way to make it prettier?

**Comment by bmac** [comment]
Hi @teckays. 

I'd recommend you place your extended store in `/services/store.js` because `/stores/application.js` is deprecated with Ember Data 1.13 and not supported by Ember Data 2.0.

As for `Ember.$.get()` there isn't a good way to replace that with Ember Data today. Instead I'd recommend you check out https://github.com/rwjblue/ember-cli-ic-ajax or https://github.com/ember-cli/ember-ajax. Both are Ember runloop friendly wrappers for `$.get` ajax.

**Comment by bmac** [comment]
I'm going to close this issue since it appears the original question has been resolved. Feel free to re-open if I'm missing something.
