### ISSUE TITLE
Ember normalize response

### ISSUE THREAD

**Issue by teckays** [emberjs/data#3957]
I'm extending the `JSONSerializer` in order to fit my server response which looks like this:

    {
      "result": {
        "items": [
          {
            "id": "...",
            "title": "...",
            ...
          },
          ...
        ],
          "total": number,
          "...": "..."
      }   
    }

therefore I have overridden `normalizeResponse()` method:

    normalizeResponse: function(store, primaryModelClass, payload, id, requestType) {
            payload = payload.result.items;

            return this._super(store, primaryModelClass, payload, id, requestType)
        },

after this my model data fields are all `undefined`. What I'm doing wrong?

**Comment by wecc** [comment]
Looks like this was solved, see http://discuss.emberjs.com/t/ember-normalize-response-undefined-fields/9204/2

Closing.
