### ISSUE TITLE
Different Model for plural

### ISSUE THREAD

**Issue by orgertot** [emberjs/data#3959]
Hi,
So we have a model called workouts. 
The rest server provides under GET /workouts basic information as id, name. 
If you want to have more informations about a workout you have to call GET /workout/:workout_id. The server will provide you a hole bunch of information/data.

How can I add a new model and a new request for the plural? I didnt find anything in the documentation. 

Thanks!

**Comment by bmac** [comment]
Hi @orgertot. I'd recommend you check out this addon https://github.com/BookingSync/ember-data-partial-model which supports the use case of basic information list GET + more detailed single model GET.

The other approach to handling this use case would be to define 1 `workout` Ember Data model. Then creating a workout specific adapter in `app/adapters/workout.js` or `app/workout/adapter.js` where you extend [urlForFindRecord](http://emberjs.com/api/data/classes/DS.RESTAdapter.html#method_urlForFindRecord) to make the request to `/workout/:workout_id` and [shouldReloadRecord](http://emberjs.com/api/data/classes/DS.RESTAdapter.html#method_shouldReloadRecord) to load return true when the workout record is in its partially loaded state (missing information from ` /workout/:workout_id`).

**Comment by orgertot** [comment]
Thanks very much for ember-data-patial-model addon!
