### ISSUE TITLE
Dynamically added records to hasMany relationship don't get serlialised (ED 2.2.1, Ember 2.1.0)

### ISSUE THREAD

**Issue by MiracleBlue** [emberjs/data#3962]
I have a model called `outcome` that looks something like this:

`
DS.Model.extend({
  decisionMaker: belongsTo('user'),
  pleaOrders: DS.hasMany('plea-order')
})
`

And a model called `plea-order` that looks like this:

`
DS.Model.extend({
  outcome: belongsTo('outcome')
})
`

And after I save the plea-order to the back-end and it returns me a new ID, I then push the plea-order record into the pleaOrders array on the outcome like so

`outcome.get('pleaOrders').pushObject(pleaOrder);`

Where `pleaOrder` is the instance of the record.  The problem I'm having is that when I call `outcome.save()`, the belongsTo relationship `decisionMaker` gets serialized just fine (as do all other belongsTo relationships) but my hasMany does not, even though it's accessible from the array when I call `outcome.get('pleaOrders')`

**Comment by MiracleBlue** [comment]
I forgot to mention, I'm using the JSON API Serializer as well.

**Comment by jcope2013** [comment]
you need to add the DS.EmbeddedRecordsMixin to your serializer  http://emberjs.com/api/data/classes/DS.EmbeddedRecordsMixin.html

```
serializers/outcome.js

import DS from 'ember-data';

export default DS.JSONAPISerializer.extend(DS.EmbeddedRecordsMixin, {
  attrs: {
    pleaOrders: { embedded: 'always' }
  }
}); 
```

**Comment by MiracleBlue** [comment]
The thing is that I'm not trying to embed it into the response, I'm simply trying to get the relationship (id + type) in the relationships object.

For example, the output I expect is this:

```
{
  data: {
    type: "outcome",
    attributes: { ... },
    relationships: {
      user: {
        data: { id: "user01", type: "user"}
      },
      pleaOrders: {
        data: [{id: "plea01", type: "plea-orders"}]
      }
    }
  }
}
```

But what I end up with is just

```
{
  data: {
    type: "outcome",
    attributes: { ... },
    relationships: {
      user: {
        data: { id: "user01", type: "user"}
      }
    }
  }
}
```

No plea-orders.

But if you're saying that I need to do the embedded record with my hasmany in order for it to add that relationship, then I do apologise and will try that.

**Comment by jcope2013** [comment]
you might want to do ``` { serialize: 'ids', deserialize: 'ids' } ``` instead of ``` { embedded: 'always' }  ``` which is really ``` { serialize: 'records', deserialize: 'records' } ```

**Comment by MiracleBlue** [comment]
Thanks @jcope2013 I will try that!

**Comment by MiracleBlue** [comment]
I've found the answer here: http://stackoverflow.com/questions/19093078/ember-data-saving-record-loses-has-many-relationships/24619032#24619032

Makes sense I suppose.  I'll just over-ride the serializer to allow manyToOne for my specific use case for now.

**Comment by wecc** [comment]
FWIW, you should be able to do `attrs: { pleaOrders: { serialize: true } }` (without the `EmbeddedRecordsMixin`) to serialize ManyToOne relationships.

**Comment by MiracleBlue** [comment]
Oh wonderful! That would be so much nicer than my current overridden
serializer method. Thanks for this, I'll give it a go in the morning.

**Comment by MiracleBlue** [comment]
That worked great @wecc, thanks a lot!
