### ISSUE TITLE
Too easy to introduce path traversal weaknesses.

### ISSUE THREAD

**Issue by nathanhammond** [emberjs/data#3971]
I'm presenting this as an issue to discuss possible solutions. In an Ember Data Adapter you can specify the URL at which that resource should be addressed. Inside of Ember Data itself there is the [Build URL Mixin](https://github.com/emberjs/data/blob/v2.2.1/packages/ember-data/lib/adapters/build-url-mixin.js) which handles this for you based upon the default patterns.

This gives lots of extension points and makes it simple to specify how to accomplish each of the datastore's methods. However, there is one catch: once you specify one of these methods, *you must ensure the URL you generate is safe from path traversal*.

What is path traversal? If you generate a URL like this:
```javascript
return `/this/is/${ID}/`;
```
You have accidentally inserted a path traversal vulnerability if `ID` is:
```javascript
"../../somewhere/else#"
```

Now a cleverly crafted input would be able to load any arbitrary URL via an Ajax request within the same domain. If paired with a JSONP endpoint or an uploaded file or a redirector this is a method to easily end up with an XSS vulnerability.

The solution to this problem is actually as simple as calling `encodeURIComponent` [as is done in the default implementation](https://github.com/emberjs/data/blob/v2.2.1/packages/ember-data/lib/adapters/build-url-mixin.js#L97), but it's really easy to forget, as evidenced by [being omitted from Ember Data](https://github.com/emberjs/data/commit/3681fcf463204bfc0acf307cbe8ff0aa4e95efb9) for the first few years of its existence and in applications I've reviewed.

In sticking with our premise of API design being a feature (or in this case, I'd call it a bug) I'm filing this issue. Any thoughts?

**Comment by stefanpenner** [comment]
I believe this maybe should have been raised via: http://emberjs.com/security/

**Comment by nathanhammond** [comment]
@stefanpenner I considered it, but didn't feel it warranted it as all issues with this are introduced by the user in their own application. We just make it too easy for users to troll themselves. Further, to address this, we would likely require a 3.X build to force a new API.

My apologies if we'd prefer to have gotten in front of this one. If we'd call this a security@ issue, I'd like to change a bit of copy on that page to make it more inviting. `/dev/null` this if you'd like.

**Comment by fivetanley** [comment]
We discussed this a few weeks ago in the core team meeting. We don't consider this to be a priority for a few reasons.

First, the confluence of events to create the perfect storm seems is quite interesting. You must be overriding URL generator methods *and* your server has to be configured to allow path traversals. Modern web and application servers (Rails, Express, Spring, Nginx, Apache, etc) do not seem to be configured this way by default.

Secondly, I think a better way forward is actually @amiel's work of integrating URL templates with ember data. We need to get back on the boat as @amiel has done all the hard work but we've unfortunately not given it the care and time to get it integrated back in.

Thank you for opening this issue. In the future, please use the security policy @stefanpenner linked to for any security related issues, no matter how small. Responsible disclosure is important for fixing security vulnerabilities.
