### ISSUE TITLE
How to tell if a container contains a factory?

### ISSUE THREAD

**Issue by mmelvin0** [emberjs/data#3982]
I have a service that can optionally be used if it is present.

If I do `this.container.has('service:optional-service')` it works but warns `DEPRECATION: has should be called on the registry instead of the container`.

If I do `this.container._registry.has('service:optional-service')` it works without the deprecation but the underscore leads me to believe this is private.

Is there a public API to query for the existence of a factory in a container or registry?

**Comment by workmanw** [comment]
The public way is through the "Owner API" which will land in Ember 2.3. The function you're looking for there is `hasRegistration`. More details can be found on the blog post: http://emberjs.com/blog/2015/11/16/ember-2-2-released.html

There is polyfill for the Owner API: https://github.com/rwjblue/ember-getowner-polyfill

Related API Docs: [RegistryProxyMixin](http://emberjs.com/api/classes/RegistryProxyMixin.html) and [ContainerProxyMixin](http://emberjs.com/api/classes/ContainerProxyMixin.html).

**Comment by mmelvin0** [comment]
Thank you so much for your timely and informative reply. I'm still on 1.13 so I'm really happy to hear about the polyfill.

This can be closed.

**Comment by workmanw** [comment]
You're welcome. The good news is that the polyfill seems to support all the way back to 1.13. That should make it much easier for you to future proof :). Happy Embering.

**Comment by rwjblue** [comment]
I don't think I've tested exactly where the polyfill stops working, but I believe it works from at least 1.10. I'd be interested in hearing exactly where it falls down (maybe report an issue over in the polyfill repo). I kinda hope it works back to 1.0.0 (but I have no clue).
