### ISSUE TITLE
enhancement request

### ISSUE THREAD

**Issue by ptmoy2** [emberjs/data#3991]
Add a method in 'store' to delete all records of a given type from both 'store' and server.

For example:
         this.store.deleteAllRecords ('post');   or  this.store.destroyRecords ('post');

**Comment by jcope2013** [comment]
this already exists (http://emberjs.com/api/data/classes/DS.Store.html#method_unloadAll)

``` store.unloadAll('post'); ```

**Comment by ptmoy2** [comment]
Yes, I knew about store.unload().  I'll update my original post to be a bit more specific.

**Comment by igorT** [comment]
Thanks for opening an issue.
I think currently you can achieve this by doing
```
store.peekAll('post').map( (record) => record.destroyRecord() );
```
Not sure we want to add this to the public API, as it's already pretty large.
Thanks!
