### ISSUE TITLE
JSON API errors without source / pointer

### ISSUE THREAD

**Issue by drewclauson** [emberjs/data#3994]
I don't see a way to get errors returned in a JSON API response that are not associated with a source/pointer.  Using JSON API adapter (of course :smile:)

For example, in the response below, I need to grab the detail of the first error and display it in a alert block at the top of my form, but model.errors doesn't have it and model.errors.messages doesn't have it.  The only thing I have figured out to do so far is use the catch callback on the `save()` promise and set messages on the controller if any of the errors don't have source / pointer attributes.  

Is there any way to get that error other than that?

```
{
  "errors": [
    {
      "code": "422",
      "title": "Invalid Model",
      "detail": "The data submitted is invalid."
    },
    {
      "status": "422",
      "title": "Invalid Attribute",
      "detail": "This value should not be blank.",
      "source": {
        "pointer": "/data/attributes/description"
      }
    },
    {
      "status": "422",
      "title": "Invalid Attribute",
      "detail": "This value should not be blank.",
      "source": {
        "pointer": "/data/attributes/title"
      }
    }
  ]
}
```

**Comment by fivetanley** [comment]
cc @tchak

**Comment by khomyakov42** [comment]
+1

**Comment by adam-knights** [comment]
@drewclauson in Ember 2.2 onward if the source looks like

    source: { pointer: "/data" }

i.e. not associated with a specific property of the model, then the error is added to errors.base

So one option, if you have control over the api, would be to include a source like the above for generic errors.

@tchak would have to answer whether we would want to get objects in the errors array with no source at all..

**Comment by drewclauson** [comment]
@adam-knights Thanks! I have control of the backend so I'll use that!
