### ISSUE TITLE
New public API does not compile in ember-cli 1.13.8

### ISSUE THREAD

**Issue by topaxi** [emberjs/data#3998]
`addon/relationships.js` doesn't get compiled in my output (using ember-cli 1.13.8) and therefore results in a syntax error.

`vendor.js`:
```javascript
// snip...
define('ember-data/relationships', function () {

    'use strict';

    export * from 'ember-data/-private/system/relationships';

});
// ...snip
```

**Comment by rwjblue** [comment]
Thanks for reporting. My guess is that the transpired used on older ember-cli doesn't support export *.

**Comment by rwjblue** [comment]
I'll test a bit more then submit a PR to change them to manual import and export statements.

**Comment by stefanpenner** [comment]
Addon/ is handled by the addon though(it's Babel should handle this), seems strange Esperanto had anything to do with this

**Comment by rwjblue** [comment]
@stefanpenner - ember-cli-babel by default blacklists es6.modules, and the ember-cli build itself handles modules

**Comment by rwjblue** [comment]
https://github.com/babel/ember-cli-babel/blob/master/index.js#L71

**Comment by bmac** [comment]
@rwjblue what needs to happen for us to close this issue. Should Ember Data be manually importing and exporting the modules instead of using `export *`?

**Comment by fivetanley** [comment]
I am kind of in favor of moving the files where these placeholder files are. These "re-export a module" files don't seem to add much value while making the compiled payload larger.

**Comment by rwjblue** [comment]
@fivetanley - I agree with you and will do that where possible, but in some cases that would also expose any named exports as "public" also (which I think is not what we want).  

@bmac - Yes:

```
export { default } from 'abc';
```

Becomes:

```
import Foo from 'abc';

export default Foo;
```

**Comment by stefanpenner** [comment]
> export { default } from 'abc';

this should just work

**Comment by stefanpenner** [comment]
@topaxi can you upgrade to ember-cli 1.13 please and try again.

**Comment by rwjblue** [comment]
@stefanpenner:

> this should just work

Agreed, that is why I wrote it that way initially, but does not work all the time (in older ember-cli versions in the 1.13 series).

I guess we could say that to use Ember Data 2.3.0 "you must use latest ember-cli", but that seems somewhat harsh especially when we have a known work around.

**Comment by stefanpenner** [comment]
> but that seems somewhat harsh

it should be a small amount of effort to upgrade

**Comment by rwjblue** [comment]
Should be, agreed.  But the fact that ember-data 2.2.0 works with ember-cli@1.13.8 and 2.3.0-beta.3 does not is not good.

**Comment by stefanpenner** [comment]
Lots of other add-ons use that syntax, i don't think switching back is healthy at all. People should just upgrade, their life will be better in many dimensions.
