### ISSUE TITLE
2.2.1 doesn't have a default export

### ISSUE THREAD

**Issue by runspired** [emberjs/data#4013]
`import DS from 'ember-data';` fails for this reason.

**Comment by pangratz** [comment]
I cannot reproduce this on ember-twiddle: https://ember-twiddle.com/9bdc514252c3515213c2. Also it looks like [there is a `export default DS`](https://github.com/emberjs/data/blob/v2.2.1/packages/ember-data/lib/main.js#L157).

Can you create a ember-twiddle / JSBin reproducing this issue?

**Comment by bmac** [comment]
@runspired What version of https://github.com/ember-cli/ember-cli-shims are you using?

**Comment by runspired** [comment]
@bmac, I diffed my package.json and bower.json with @benborowski last night and he realized I was using the newest version of ember-cli-shims, which doesn't expose ED and is meant to work with `2.3`.
