### ISSUE TITLE
Observers on post.comments.@each.id are not called on Comment#save

### ISSUE THREAD

**Issue by lcoq** [emberjs/data#4024]
Given `Post` and `Comment` as follows : 

```js
// models/post.js
export default DS.Model.extend({
  comments: DS.hasMany('comment'),
  name: DS.attr()
});
```

```js
// models/comment.js
export default DS.Model.extend({
  post: DS.belongsTo('post')
});
```

And given a newly created comment, attached to a post as follows : 

```js
let comment = this.store.createRecord('comment', { post: post });
```

When we save it, the observers for `post.comments.@each.id` are not called :

```js
postCommentIdsChanged: Ember.observer('post.comments.@each.id', function() {
  console.log('post.comments.@each.id observer called');
})
```

But the `post.get('comments').mapBy('id')` changes during save : 

```js
// post.get('comments').mapBy('id'); => ['']
comment.save().then(function() {
  // post.get('comments').mapBy('id') => ['1']
});
```

[See this EmberTwiddle (this link could not work with Safari) ](https://ember-twiddle.com/8f60fb47ad37195b6795)

**Comment by lcoq** [comment]
This is somewhat related to #4020 (but not the same bug) as we cannot either rely on `post.comments.@each.id` nor `post.comments.@each.isNew` to filter new/persisted records of a `hasMany` relation.

**Comment by jcope2013** [comment]
most likely related to https://github.com/emberjs/ember.js/issues/12475

**Comment by bmac** [comment]
I took a look at this issue this morning and I agree with @jcope2013. When I downgraded the Ember version in the jsfiddle the `post.comments.@each.id` observer fired as expected.

**Comment by bmac** [comment]
I'm going to close this since we are already tracking this issue here: https://github.com/emberjs/data/issues/3911
