### ISSUE TITLE
[Feature Request] finding records that don't have IDs

### ISSUE THREAD

**Issue by nickiaconis** [emberjs/data#4027]
There are a few resources in our API that only return single records, but are accessed per account (via auth token) rather than by a given ID. We used to be able to omit the ID from `findRecord`, but more recent versions of Data, to which we are now trying to upgrade, prevent this.

```javascript
this.store.findRecord('id-less-model-type'); // now throws assertion error
```

One way for us to get around this is to request "all" the records (an array of 1), then return the first object, but this feels heavy-handed for such a simple requirement.

```javascript
this.store.findAll('id-less-model-type').then((recordArray) => recordArray.get('firstObject'));
```

Another way we have investigated is passing an arbitrary ID, then disregarding it in the adapter. This is nice because it requires less processing, but it feels hacky because it requires changes on multiple layers.

```javascript
// app/some/route.js
this.store.findRecord('id-less-model-type', 0);

// app/adapters/id-less-model-type.js
export default ApplicationAdapter.extend({
  buildURL(modelType, id, ...rest) {
    return this._super(modelType, undefined, ...rest);
  }
});
```

I searched the issues briefly, but couldn't find anything similar by title.
Has anyone else found a need for something like this? What solution did you employ?
Is this a case that Ember Data will attempt to solve in the near future?

**Comment by fivetanley** [comment]
This is related to https://github.com/emberjs/data/issues/1763. I don't think ID-less records is something we're going to support. The reason for this has mostly to do with the identity map (the thing that guarantees you only have one instance per-id) and relationships (we can't tie together records without IDs). 

The workarounds you outlined in the issue description are what I would suggest (`findAll`, or generate an ID in the adapter/serializer).
