### ISSUE TITLE
destroyRecord rises exception after successfull delete operation

### ISSUE THREAD

**Issue by bevinhex** [emberjs/data#4028]
I have,

'deployd' as backend,
use 'RESTAdapter' as application adapter,
use 'JSONSerializer' as application serializer,

put custom component in a template, template sends model as property to component, component does operations like 'new' 'delete' 'update'; 

problem is 'new' 'update' works fine with creating, modifying records, not 'delete', when I call `model.destroyRecord` program sends 'OPTIONS' 'DELETE' request to deployd, and does the job correctly, but after server returns successfully, console prints lot's of info like `...vendor.js ... didSaveRecord ...updateId ...`

After investigating a little bit, found out that problem is in 

```
didSaveRecord: function (internalModel, dataArg) {
        var data;
        if (dataArg) {
          data = dataArg.data;
        }
        if (data) {
          // normalize relationship IDs into records
          this._backburner.schedule('normalizeRelationships', this, '_setupRelationships', internalModel, internalModel.type, data);
          this.updateId(internalModel, data);
        }

        //We first make sure the primary data has been updated
        //TODO try to move notification to the user to the end of the runloop
        internalModel.adapterDidCommit(data);
      },
```

function from ember-data.js file, after I delete a record, somehow did entered this function, 
guess dataArg.data is the data returned back from adapter, while `data.id` is `null`, so it's not possible to `updateId` with a null id, 

So my solution is change it into this:

```
didSaveRecord: function (internalModel, dataArg) {
        var data;
        if (dataArg) {
          data = dataArg.data;
        }
        if (data.id) {
          // normalize relationship IDs into records
          this._backburner.schedule('normalizeRelationships', this, '_setupRelationships', internalModel, internalModel.type, data);
          this.updateId(internalModel, data);
        }

        //We first make sure the primary data has been updated
        //TODO try to move notification to the user to the end of the runloop
        internalModel.adapterDidCommit(data);
      },
```

We won't updateId while data.id is null, hope someone rechecks my solution and put it into the repository.

**Comment by bmac** [comment]
@bevinhex what sort of response is your server returning from the delete http request? iirc If there is a response Ember Data assumes the payload is the serialized record that was just deleted. If there was no response Ember Data will use its existing knowledge of the record to delete it. 

If your server is responding with something other then the serialized record in the payload this may be confusing Ember Data. One workaround maybe to override [normalizeDeleteRecordResponse](http://emberjs.com/api/data/classes/DS.JSONSerializer.html#method_normalizeDeleteRecordResponse) in your serializer and have it always return null.

**Comment by bevinhex** [comment]
It did return ```200 OK``` , deletion is successful on server side, it returns successful, the page refreshes loosing the record deleted, everything seems find, just a bunch of error messages on console.
I wonder what caused ember-data to set id null for deleted record while keeping before updateId function.
here is console log:
```
GET 
XHR 
http://localhost:2403/weekly-goals [HTTP/1.1 200 OK 7ms]
OPTIONS 
XHR 
http://localhost:2403/roles/9f1e40138c2d3933 [HTTP/1.1 204 No Content 0ms]
DELETE 
XHR 
http://localhost:2403/roles/9f1e40138c2d3933 [HTTP/1.1 200 OK 6ms]
Object { id: "null", type: "roles", attributes: Object, relationships: Object } vendor.js:84152:9
EmberError@http://localhost:4200/assets/vendor.js:27348:15
_emberMetalCore.default.assert@http://localhost:4200/assets/vendor.js:16067:13
ember$data$lib$system$store$$Store<.updateId@http://localhost:4200/assets/vendor.js:84203:9
ember$data$lib$system$store$$Store<.didSaveRecord@http://localhost:4200/assets/vendor.js:84156:11
ember$data$lib$system$store$$_commit/</<@http://localhost:4200/assets/vendor.js:84901:11
Backburner.prototype.run@http://localhost:4200/assets/vendor.js:10843:18
ember$data$lib$system$store$$Store<._adapterRun@http://localhost:4200/assets/vendor.js:84742:16
ember$data$lib$system$store$$_commit/<@http://localhost:4200/assets/vendor.js:84892:9
tryCatch@http://localhost:4200/assets/vendor.js:67710:14
invokeCallback@http://localhost:4200/assets/vendor.js:67725:15
publish@http://localhost:4200/assets/vendor.js:67693:9
@http://localhost:4200/assets/vendor.js:44051:7
Queue.prototype.invoke@http://localhost:4200/assets/vendor.js:11571:9
Queue.prototype.flush@http://localhost:4200/assets/vendor.js:11635:11
DeferredActionQueues.prototype.flush@http://localhost:4200/assets/vendor.js:11436:11
Backburner.prototype.end@http://localhost:4200/assets/vendor.js:10725:9
Backburner.prototype.run@http://localhost:4200/assets/vendor.js:10847:13
run@http://localhost:4200/assets/vendor.js:31688:12
ember$data$lib$adapters$rest$adapter$$RestAdapter<.ajax/</hash.success@http://localhost:4200/assets/vendor.js:72892:15
jQuery.Callbacks/fire@http://localhost:4200/assets/vendor.js:3346:10
jQuery.Callbacks/self.fireWith@http://localhost:4200/assets/vendor.js:3458:7
done@http://localhost:4200/assets/vendor.js:9512:5
.send/callback@http://localhost:4200/assets/vendor.js:9916:8
 vendor.js:44090:9

```

**Comment by bevinhex** [comment]
Also the response for the DELETE operation was
```
{
count:1
}

**Comment by wecc** [comment]
@bevinhex Are you still having problems with this issue? Would you be able to reproduce it?

**Comment by stefanpenner** [comment]
This seems to have gone stale. Will gladly reopen if a reproduction is provided.
