### ISSUE TITLE
store.pushPayload swallows errors 

### ISSUE THREAD

**Issue by kagemusha** [emberjs/data#4034]
Seems `store.pushPayload` fails silently when it encounters errors, which leaves the developer little clue as to what is going on.

My particular example (though probably a more general problem) was pushing user data to the store after authenticating.  My Rails server was returning active-model style json and i had forgotten to override the adapter.  Fairly easy to debug when pausing on caught exception if you've done this before, but throwing the exception to the console would speed the process, especially for less experienced developers.

**Comment by bmac** [comment]
Hi @kagemusha. I made a quick jsbin to test the issue you described and pushPayload seemed to throw an error for me. http://emberjs.jsbin.com/cosixezepo/1/edit?html,js Do you mind taking a look at this jsbin and let me know what I'm missing?

**Comment by kagemusha** [comment]
@bmac Have looked at again and error may be getting swallowed at higher level - closing until find area definitively.   Thanks for looking at!
