### ISSUE TITLE
Strip assertions when using the Ember CLI Addon with a prod build

### ISSUE THREAD

**Issue by bmac** [emberjs/data#4047]
Stanley Stuart [10:55 AM] 
@bmac based off the existing code https://gist.github.com/fivetanley/1708106ba3372b41dc94

​[10:55] 
we would have to return something like this in `treeForAddon`

​[10:55] 
so basically do an ES6 to ES6 compilation so ember-cli can do the rest as it normally would

​[10:55] 
although this gist needs to be updated for the `-private`-ification

​[10:56] 
similar to https://github.com/emberjs/data/pull/4043

**Comment by pangratz** [comment]
This issue can be closed since #4048 has been merged.
