### ISSUE TITLE
Wrong version info in the 2.3 release

### ISSUE THREAD

**Issue by sly7-7** [emberjs/data#4062]
Installing ember-data 2.3 with npm is working, but there is a problem with the version shown in the console, or in the inspector:

```
DEBUG: Ember      : 2.4.0-canary+a364b39e
Ember Data : 0.0.1+
```

**Comment by poteto** [comment]
I have the same issue, this breaks any addon (in our case, `ember-infinity`) that relies on https://www.npmjs.com/package/ember-version-is.

**Comment by fivetanley** [comment]
This seems to happen only when pulling the bower version in for me.

**Comment by fivetanley** [comment]
Actually the bower version is broken :sweat: fixing

**Comment by rwjblue** [comment]
I'm working on the addon angle while @fivetanley is working on the globals bower build...

**Comment by rwjblue** [comment]
https://github.com/emberjs/data/pull/4064 should fix the version issue when used as an addon.

@poteto / @sly7-7 - Can you test that branch and confirm?

**Comment by poteto** [comment]
On that commit `VERSION` is now returning a value

![screenshot 2016-01-12 14 40 27](https://cloud.githubusercontent.com/assets/1390709/12274782/843051f6-b93a-11e5-8ffc-976934979eb0.png)

**Comment by bmac** [comment]
I just released Ember Data https://github.com/emberjs/data/releases/tag/v2.3.1 with a fix for this issue.

**Comment by sly7-7** [comment]
Thanks all of you :heart:

**Comment by poteto** [comment]
Confirm, thanks to everyone for solving this so quickly!

**Comment by alvincrespo** [comment]
This thread just save my life 🙏
