### ISSUE TITLE
EmbeddedRecordsMixin does not seem to respect `key` values in `attrs` hash

### ISSUE THREAD

**Issue by grapho** [emberjs/data#4068]
While using `DS.EmbeddedRecordsMixin`, I discovered this while trying to embed records and also map a key for said records:
```
attrs: {
  steps: { key: 'process_steps', embedded: 'always'}
}
```
I had assumed that i could still use the `attrs` hash to mapp the json key to model attribute.. however it seems to be ignored.

When the json payload is deserialized into a model, `steps` seems to be resolved correctly.. but when attempting, but when doing a POST/PUT.. serializing the model back to json.. they key remains `steps` and not the intended `process_steps`

I have attempted workarounds by overriding `serializeHasMany` and also `keyForRelationship .. which results in the correct payload key.. however at that point none of the actual embedded records get serialized at all?

Edit: Solution for now is to just not map "embedded record keys" and just use a `computed.alias`

I am wondering if anyone else has experienced or overcome this limitation?

**Comment by HeroicEric** [comment]
@grapho not sure where you saw the `key` option but I can't find any references to it in the code.

I think `keyForRelationship` is what you're looking for. Can you provide some more details about what wasn't working when you tried that? Here is a commit with a test that shows that passing (in a new branch) https://github.com/HeroicEric/data/commit/31e60350cff2aa4dd5c21c231da1bf6cc5c641dc

**Comment by grapho** [comment]
@HeroicEric  that is a very good point. there is not direct mention of `key` in the EmbeddedRecordsMixin`... however, `key` _is_ mentioned in the Serializer `attrs` hash api.  Since they seem to piggyback together, i assumed that the features would work together.

As to using `keyForRelationship`... I overwrote the method and made sure that `'serialize'` would return `process_steps` and `'deserialize'` would return `steps`... this resulted in the payload key itself being serialized properly.. but for some reason the array was empty

**Comment by grapho** [comment]
I am pretty sure now that this issue i am having might have been fixed in `ember-data 2.3+`.. i am upgrading and will close if resolved.

**Comment by bmac** [comment]
@grapho where you ever able to confirm if `ember-data 2.3` fixed this issue?

**Comment by grapho** [comment]
@bmac it did not seem to fix the issue.  I have tried a few combinations of things with no luck.  `keyForRelationship` does not seem to work as the recent bugfix suggested either...

I am going to try a few more times before i determine if it is just "user error" before persuing further as an actual issue.

**Comment by ef4** [comment]
`key` is definitely a supported option, and this looks like a bug to me. Several related scenarios already respect `key`: it works for deserializing an embedded record and for serializing a non-embedded record.

It's [documented here](http://emberjs.com/api/data/classes/DS.JSONSerializer.html#property_attrs).

**Comment by mdentremont** [comment]
The same issue is present when using `serialize: id` and `serialize: ids`, I've created and issue for it (vhttps://github.com/emberjs/data/issues/4472) and a fix (https://github.com/emberjs/data/pull/4473)
