### ISSUE TITLE
ember-data-source gem 2.3.1 doesn't have 'dist' directory

### ISSUE THREAD

**Issue by tricknotes** [emberjs/data#4069]
Couldn't require `ember-data.js` from Sprockets. (it is expected to exist in `dist/ember-data.js`.)

```
$ tree ember-data-source-2.3.1
ember-data-source-2.3.1
├── lib
│   └── ember
│       └── data
│           ├── source.rb
│           └── version.rb
└── package.json

3 directories, 3 files
```

**Comment by fivetanley** [comment]
Wow, I was just writing the code for this myself but didn't get the email til just now :P thanks!

**Comment by tricknotes** [comment]
Could someone release a new version of `ember-data-source`, such as `2.3.1.1` or something?
