### ISSUE TITLE
import Model from 'ember-data/model' doesn't work

### ISSUE THREAD

**Issue by bmac** [emberjs/data#4075]
Unless you also import `ember-data`.

rwjblue [2:20 PM] 
basically there are some side effects that happen upon importing `ember-data`

​[2:21] 
yep

​[2:21] 
https://github.com/emberjs/data/blob/a0408cc1f1ec4004368e6c553f219b8360ec6bb3/addon/-private/system/relationships/ext.js#L101 doesn't get ran if you `import Model from 'ember-data/model';`

GitHub
emberjs/data
A data persistence library for Ember.js.
(edited)

​[2:21] 
@bmac: thoughts on ^^?

​[2:21] 
@atimberlake: add `import "ember-data";` to `app/app.js` for now to fix your app code

atimberlake [2:22 PM] 
@rwjblue: Thanks, will do

rwjblue [2:22 PM] 
I wonder if there is a specific reason we `.reopen` there instead of provide a mixin that `Model` can include

atimberlake [2:23 PM] 
Thanks, all working again

bmac [3:23 PM] 
@rwjblue: sounds like model should be importing `relationships/ext`

rwjblue [3:24 PM] 
@bmac: it should import a mixin from there(edited)

​[3:24] 
but if model imports it for side effects, then you have a circular dep and `Model` will be undefined in relationships/ext

bmac [3:31 PM] 
makes sense

**Comment by bmac** [comment]
Closed by https://github.com/emberjs/data/pull/4091

**Comment by MattNguyen** [comment]
After upgrading to 2.3.3, we still need to add `import ember-data` in `app/app.js`. #4091 was supposed to resolve this, correct?

**Comment by bmac** [comment]
@MattNguyen That is correct what error are you seeing?
