### ISSUE TITLE
Deprecate unused initializers

### ISSUE THREAD

**Issue by bmac** [emberjs/data#4093]
Ember Data has 4 initializers that it supports for legacy reasons but otherwise do nothing. https://github.com/emberjs/data/blob/master/tests/ember-data-initializers.js#L18-L40

@rwjblue [suggested](https://github.com/emberjs/data/pull/4088#issuecomment-172663110) that it may be possible to deprecate them by "hook[ing] into the DAG map that is used for initializers and see if anyone depends on it"

**Comment by wecc** [comment]
Link is gone, should be these:

https://github.com/emberjs/data/blob/master/app/initializers/data-adapter.js
https://github.com/emberjs/data/blob/master/app/initializers/injectStore.js
https://github.com/emberjs/data/blob/master/app/initializers/store.js
https://github.com/emberjs/data/blob/master/app/initializers/transforms.js
