### ISSUE TITLE
Shim error breaks CLI generators at sub-directory

### ISSUE THREAD

**Issue by knownasilya** [emberjs/data#4096]
Works at the top level:

```shell
iradchenko my-project (master)$ ember g util path-to-bounds
version: 2.2.0-beta.4
installing util
  create app/utils/path-to-bounds.js
installing util-test
  create tests/unit/utils/path-to-bounds-test.js
```

Broken in any other directory:

```shell
iradchenko app (master)$ cd app
iradchenko app (master)$ ember g util path-to-bounds
Using a version of ember-cli-shims prior to 0.1.0 will cause errors while loading Ember Data 2.3.0-beta.3+. Please update ember-cli-shims from undefined to 0.1.0.
```

This is for all generators. I'm using v2.3.1 of ED (only in package) and the shim is updated.

**Comment by bmac** [comment]
@rwjblue are we using `ember-cli-version-checker` correctly here? https://github.com/emberjs/data/blob/master/index.js#L27-L28

**Comment by rwjblue** [comment]
Yes. It is being used correctly. It is possible that it needs to use something like findup.sync to find the bower.json instead of just looking in process.cwd().

**Comment by rwjblue** [comment]
https://github.com/rwjblue/ember-cli-version-checker/pull/14 should fix this (it is released as v1.1.6 which a `nom` should grab for our consumers).

**Comment by rwjblue** [comment]
Thanks @HeroicEric!

**Comment by bmac** [comment]
@knownasilya can you confirm that the issue has now been fixed?

**Comment by knownasilya** [comment]
Confirmed. Thanks guys!
