### ISSUE TITLE
Issue with the hover

### ISSUE THREAD

**Issue by jacko99** [emberjs/data#4098]
Hi all, 

I have an issue. When I move my mouse over the graph, I have 3 figures instead of one. I didn't change anything. Can someone help me? 

Example : http://preprod.conseilsparissportifs.fr/bilan-pronostics/

**Comment by fivetanley** [comment]
Neither Ember or Ember Data is being loaded on the page. Is there another link?

**Comment by jacko99** [comment]
No. Thanks for your help. I have other examples : http://preprod.conseilsparissportifs.fr/bilan-expert/?id=4

**Comment by fivetanley** [comment]
This page doesn't have Ember or Ember Data either. I think you are filing an issue on the wrong repository.
