### ISSUE TITLE
Errors importing `ember-data/serializers/json-api` without importing `ember-data`

### ISSUE THREAD

**Issue by bmac** [emberjs/data#4103]
It looks like the run in debug block doesn't get run before the user extends the serializer if they import the serializer directly instead of importing `ember-data` https://github.com/emberjs/data/blob/master/addon/serializers/json-api.js#L496-L505

This also impacts the `RESTSerializer`.

**Comment by rwjblue** [comment]
Seems odd. Does the block get ran at all?

**Comment by bmac** [comment]
I can no longer reproduce the issue on 2.3.2. https://github.com/bmac/test-ember-data-2-3/commit/88b4fa25f6b146a6043097f772eec1220c49aac6
