### ISSUE TITLE
build url mixin uses encodeURIComponent on URI segments

### ISSUE THREAD

**Issue by chrisseto** [emberjs/data#4106]
[Relevant line of code](https://github.com/emberjs/data/blob/master/addon/-private/adapters/build-url-mixin.js#L99)

`encodeURIComponent` is used for encoding query parameters.
```javascript
encodeURIComponent('=') // -> '%3D'
encodeURIComponent('?') // -> '%3F'
encodeURIComponent(':') // -> '%3A'
```

```javascript
encodeURI('=') // -> '='
encodeURI('?') // -> '?'
encodeURI(':') // -> ':'
```

My resource ids contain `:`s, when sending a request to my server I expect ember-data to leave these characters untouched but it escapes them.

This seems like incorrect default behavior.

```javascript
// GET /v1/resource/name%3Sspaced
this.store.find('resource', 'name:spaced');
```

I'd submit a PR but I'm not sure if this specific behavior is relied on anywhere or if the RESTadapter is the only class that inserts that field into a URL segment.

**Comment by wecc** [comment]
Hey @chrisseto! The current behavior of encoding using `encodeURIComponent()` is expected. I'm pretty sure most web servers would handle this and correctly decode `%3A` back to `:` when it reaches your backend.

Quoting @igorT  from somewhat related issue #2480:

> Supporting this is actually somewhat of a security concern, and it seems like if you want to do this you can just turn %2F back into '/' in your buildURL. I don't think we will be reverting this.

**Comment by chrisseto** [comment]
@wecc ah, thanks for pointing that out. It's not a bug if it's by design!
