### ISSUE TITLE
Test run pauses for a second every 5 seconds or so with ember-data 2.3.0 - 2.3.3

### ISSUE THREAD

**Issue by danielspaniel** [emberjs/data#4112]
This could be something to do with qunit, but qunit was same version. 
Only upgrading to ember-data 2.3+ causes this issue. 

It's pretty interesting. Not sure what is causing it, but for that second javascript is pausing, it's doing ( ParseHtml about 10 times, then a Minor GC call ) <- over and over again.
Have you found this issue when running ember-data tests? 

Interestingly even with phantomjs there is a slowdown. It's more consistent, in that phantomjs tests just run slower ( all of them ) .. whereas on chrome runner, it runs normally for a while then pauses after 5 seconds or so for one it's one second breaks. 

![screen shot 2016-01-23 at 2 12 33 pm](https://cloud.githubusercontent.com/assets/180456/12532201/cd070aa6-c1db-11e5-9382-ee18da82c331.png)

If you run the tests in the  ember-data-factory-guy repo you'll be able to see what I see here.

**Comment by bmac** [comment]
@rwjblue or @fivetanley any hunches as to why ember-data 2.3 might cause this behavior?

**Comment by fivetanley** [comment]
Do you think you could reproduce in a new repo with `ember new`? It'd be super helpful for us to have an isolated reproduction case. Otherwise I can try to take a look at it on the new app I'm on.

**Comment by danielspaniel** [comment]
I have another ember app ( using ember mocha ), and I am not seeing this behavior so there is something particular going on here ( which I obviously don't know what it is ).  Maybe it's the combination of ember-data and qunit? 

I would have to make a new app and then create a hundred or so tests to get a feel for the slowdown. But if ember-data tests don't show this ( and there are many hundreds ) , then has to be something in my repo code that is triggering it ( which I reckon is the case )

I threw this out there as a hail mary kind of throw, to see if anyone had the same issue, but if not one else see's same that is good info too.
