### ISSUE TITLE
Meta-data is not reflected on a saved model (ED 2.3, ED 2.4)

### ISSUE THREAD

**Issue by duizendnegen** [emberjs/data#4115]
Calling `save` on a model (this is a PUT operation in this case) doesn't capture the metadata that is returned from the server. Incidentally, this is also true for `queryRecord`. (Perhaps related: #3918)

```javascript
payment.save().then((result) => {
   console.log(this.get('payment.meta'));
});
```
prints `undefined`.

Using the private method `_metadataFor` gives the metadata as expected
```javascript
payment.save().then((result) => {
   console.log(this.get('store')._metadataFor('payment'));
});
```
prints
```javascript
{
   error: "Failed charging the card"
}
```

**Comment by bmac** [comment]
I believe it is a known issue that `meta` is not supported on records. See: https://github.com/emberjs/data/issues/2905

@wecc do you mind writing up what needs to happen to allow for meta support on records?

**Comment by duizendnegen** [comment]
Any update @wecc @bmac, especially considering the workaround doesn't work with 2.4.x anymore?

**Comment by wecc** [comment]
@duizendnegen There's an RFC from @pangratz at https://github.com/emberjs/rfcs/pull/160 that aims to lay the groundwork for supporting meta and links.

I'm closing this issue since we're tracking JSON API support (including meta for single records) in #2905, feel free to join the discussion there.
