### ISSUE TITLE
JSON payload with null values gets pushed into store as [object Object]

### ISSUE THREAD

**Issue by JakeDluhy** [emberjs/data#4121]
I have a model
```
// examplel.js
export default DS.Model.extend({
  name: DS.attr('string'),
  description: DS.attr('string')
});
```
That gets a payload that looks like
```
{  
  "type":"example",
  "id":"1",
  "attributes":{  
    "name":"my name",
    "description":null
  }
}
```
Notice that sometimes, the description field is `null`

The problem is that somewhere along the way of the model getting pushed into the store, the value of `null` becomes '[object Object]'. When I change the model to `description: DS.attr()` it just gives me an Ember Object. I did some investigating, and I wasn't able to find where it is happening... I don't think it's happening before or during the transforms (I put the below code into my serializer and played around at the debugger and it looked good)
```
normalize(modelClass, resourceHash) {
  if (resourceHash.attributes) {
    this.normalizeUsingDeclaredMapping(modelClass, resourceHash.attributes);
  }

  if (resourceHash.relationships) {
    this.normalizeUsingDeclaredMapping(modelClass, resourceHash.relationships);
  }

  let data = {
    id:            this.extractId(modelClass, resourceHash),
    type:          this._extractType(modelClass, resourceHash),
    attributes:    this.extractAttributes(modelClass, resourceHash),
    relationships: this.extractRelationships(modelClass, resourceHash)
  };

  this.applyTransforms(modelClass, data.attributes);
  debugger;
  return { data };
},
```
Please advise with any information, thanks!
I'm on Ember Data 2.3.3

EDIT: I did a little more investigating and it seems that something _is_ happening before the transforms...
If I write a custom transform
```
// transforms/custom-string.js
import DS from 'ember-data';

export default DS.Transform.extend({
  deserialize(serialized) {
    if(Object.keys(serialized).length === 0) {
      return undefined;
    }
    return serialized;
  },

  serialize(deserialized) {
    if(Object.keys(deserialized).length === 0) {
      return undefined;
    }
    return deserialized;
  }
});
```
And apply it to `description` then it returns undefined and the value in the store becomes undefined.
Obviously this is not ideal, and I'd prefer a better way...

EDIT 2: Upon further work I've discovered that I am not having this problem when I have a `DS.attr('number')` value

**Comment by pangratz** [comment]
Having a `DS.attr("string")` and a normalized value of `[object Object]` looks like the value which should be normalized is an object. Are you sure that the value for `description` is a string or `null`/`undefined`?

Can you reproduce with a failing response in an ember-twiddle? You can use [this](https://ember-twiddle.com/267b07fb439f18d4e483?openFiles=application.route.js%2Capplication.template.hbs) as a starting point.

**Comment by JakeDluhy** [comment]
It looks like we had done some work to camelize our json keys embedded in object (like with the response
```
{
  data: {
    type: 'person',
    id: 1,
    attributes: {
      name: 'Jake',
      occupation_information: {
        job: 'Software Dev',
        is_he_skilled: 'questionable'
      }
    }
  }
}
```
 in normalize, that was recognizing null as an object and transforming it into an empty object. Thanks so much for your help, it was me trying to add my serializer to the ember-twiddle that made me realize the mistake!

**Comment by pangratz** [comment]
Nice, glad you figured it out! :+1:
