### ISSUE TITLE
unloadRecord doesn't disconnect observers on the model

### ISSUE THREAD

**Issue by jerel** [emberjs/data#4126]
Here is a twiddle demonstrating the problem (on canary): https://ember-twiddle.com/1523fd2fae4a21c261d7?numColumns=1&openFiles=models.event.js%2C

I have a scenario where a list of models is shown and each model is responsible for removing itself after it becomes old. However when `unloadRecord` is called the model is removed but the observers stay connected.

**Comment by alexspeller** [comment]
it seems like `unloadRecord` doesn't actually destroy the record - no idea if this is intended or not, the workaround is just:

```
model.unloadRecord();
model.destroy();
```

**Comment by mitchlloyd** [comment]
Perhaps this could be resolved with some updates to the current API documentation which is pretty sparse.

http://emberjs.com/api/data/classes/DS.Store.html#method_unloadAll

**Comment by wecc** [comment]
This should be fixed by #4593
