### ISSUE TITLE
2.3 does not appear to work outside development environment

### ISSUE THREAD

**Issue by jpaas** [emberjs/data#4127]
When I upgraded to 2.3 everything appeared to be fine until I deployed to production. In production I get an error deserializing any JSONAPI response. The error occurs when when trying to check some assertions and the following functions are not defined:

warnMessageForUndefinedType
warnMessageNoModelForType

because they are removed from non-debug environments: https://github.com/emberjs/data/blob/2322aacc3f3e4fb4fe9b30c7d790c45126fa5c73/addon/serializers/json-api.js#L501

Rolling back to ember 2.2.1 fixes this for me.

**Comment by pangratz** [comment]
Hmm, the [corresponding `assert`](https://github.com/emberjs/data/blob/2322aacc3f3e4fb4fe9b30c7d790c45126fa5c73/addon/serializers/json-api.js#L156-L158) - which needs the `warnMessageForUndefinedType` method - should be removed as well. So it shouldn't matter that there is no `warnMessageForUndefinedType` method available.

All the asserts are stripped correctly in http://builds.emberjs.com/release/ember-data.prod.js

Can you post your `package.json` and `bower.json`?

**Comment by jpaas** [comment]
package.json:
```
{
  "name": "hcp-webapp",
  "version": "2.7.0",
  "description": "This is the iMD Health web app for Healthcare Providers.",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test"
  },
  "repository": {
    "type": "git",
    "url": "git+ssh://git@bitbucket.org:imdhealth/hcp-webapp.git"
  },
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "iMD Health",
  "license": "© Copyright 2015-2016 iMD Health Global Corp. Patent pending. All rights reserved.",
  "devDependencies": {
    "broccoli-asset-rev": "^2.2.0",
    "ember-ajax": "0.7.1",
    "ember-browserify": "^1.0.5",
    "ember-can": "0.7.3",
    "ember-cli": "2.2.0-beta.6",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-auto-complete": "^0.2.1",
    "ember-cli-babel": "^5.1.5",
    "ember-cli-bootstrap-sassy": "0.5.1",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-deploy": "0.5.1",
    "ember-cli-deploy-build": "0.1.0",
    "ember-cli-deploy-display-revisions": "0.1.0",
    "ember-cli-deploy-gzip": "0.1.1",
    "ember-cli-deploy-manifest": "0.1.0",
    "ember-cli-deploy-revision-data": "0.1.0",
    "ember-cli-deploy-s3": "0.2.0",
    "ember-cli-deploy-s3-index": "0.2.0",
    "ember-cli-deploy-slack": "0.0.4",
    "ember-cli-document-title": "0.3.0",
    "ember-cli-htmlbars": "^1.0.1",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-imd": "git+ssh://git@bitbucket.org:imdhealth/ember-cli-imd.git#2.6.0",
    "ember-cli-inject-live-reload": "^1.3.1",
    "ember-cli-qunit": "^1.1.0",
    "ember-cli-rails-addon": "0.7.0",
    "ember-cli-release": "0.2.8",
    "ember-cli-sass": "5.2.1",
    "ember-cli-sri": "^2.0.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "2.3.3",
    "ember-disable-proxy-controllers": "^1.0.1",
    "ember-export-application-global": "^1.0.4",
    "ember-intl": "2.0.0",
    "ember-resolver": "^2.0.3",
    "ember-select-2": "1.3.0",
    "ember-simple-auth": "1.0.1",
    "ember-validations": "dockyard/ember-validations"
  }
}

```

bower.json:
```
{
  "name": "hcp-webapp",
  "dependencies": {
    "ember": "2.3.0",
    "ember-cli-shims": "0.1.0",
    "ember-cli-test-loader": "0.2.2",
    "ember-load-initializers": "0.1.7",
    "ember-qunit-notifications": "0.1.0",
    "jquery": "1.11.3",
    "loader.js": "^3.5.0",
    "qunit": "~1.20.0",
    "bootstrap-sass": "~3.3.6",
    "bootswatch": "3.3.5",
    "select2": "3.5.2",
    "carouFredSel": "6.2.1"
  },
  "resolutions": {
    "ember": "2.3.0"
  }
}
```

**Comment by pangratz** [comment]
And I guess there is nothing weird on the output when doing a `ember build --prod`?

**Comment by jpaas** [comment]
I've been using ember-cli-deploy to deploy to s3, but I tried a manual build and didn't see any unusual output.

**Comment by bmac** [comment]
@jpaas what version of node and npm are you using?

**Comment by bmac** [comment]
@jpaas I tired to reproduce the issue in this repo https://github.com/bmac/ember-data-issue-4127 and I was unsuccessful.

Would you mind trying to delete your `node_modules` folder and re-running npm install?

**Comment by jpaas** [comment]
@bmac I just deleted node_modules and tried a clean npm install but got the same result.

```
$ ember version
version: 2.2.0-beta.6
node: 5.2.0
npm: 2.14.10
os: darwin x64
```

**Comment by jpaas** [comment]
@bmac I had a look at https://github.com/bmac/ember-data-issue-4127 but it doesn't appear to have any models. My ember app runs fine until it needs to deserialize a JSONAPI response into an ember data model.

**Comment by bmac** [comment]
Hi @jpaas to test I was building the project with `ember build --environment=production` then manually inspecting the `dist/assets/vendor-54571537ea930fe6dd7c9e4a35599bc0.js` file for `warnMessageForUndefinedType`. I will try to setup a more fleshed out example with models and a JSONAPI response.

**Comment by bmac** [comment]
@jpaas I spent some more time looking at this issue today and I was still unable to reproduce the issue. Do you mind trying the npm install again (with Ember Data 2.3.3 in the package.json) with a `npm cache clean`?

```bash
rm -rf node_modules bower_components dist tmp
npm cache clean
npm install
```

If this doesn't work would you be available to pair so I can look into the issue remotely?

**Comment by Soliah** [comment]
This is actually happening to too. I've tried doing cleaning node_modules and bower but prod builds still throw these errors. Will try and see if I can create reproducible repo.

**Comment by Soliah** [comment]
I think I've fixed this simply by creating an `app/serializers/application.js` that simply exports `DS.JSONAPISerializer`.

**Comment by jpaas** [comment]
@bmac I tried upgrading to ember-cli 2.3.0 today. It turns out it doesn't work with ember-data prior to 2.3. So I tried upgrading to ember-data 2.3.3. Everything worked fine until I deployed to staging. Same problem.

**Comment by jpaas** [comment]
All of my serializers extend my `/app/serializers/application.js` serializer which extends `DS.JSONAPISerializer`

**Comment by Soliah** [comment]
@jpass can you also paste your ember-cli-build.js

**Comment by jpaas** [comment]
Here's my ember-cli-build.js:

```javascript
/*jshint node:true*/
/* global require, module */

var EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  var env = EmberApp.env();
  var isProductionLikeBuild = ['production', 'staging'].indexOf(env) > -1;
  var fingerprintPrepend;
  if (env == 'staging') {
    fingerprintPrepend = 'https://adminstaging.imdpinga.com/';
  } else if (env == 'production') {
    fingerprintPrepend = 'https://admin.imdpinga.com/';
  }

  var app = new EmberApp(defaults, {
    babel: {
      includePolyfill: true
    },

    'ember-cli-bootstrap-sassy': {
      'glyphicons': false // We're using fontawesome
    },

    'ember-cli-selectize': {
      'theme': 'bootstrap3'
    },

    hinting: process.env.EMBER_CLI_TEST_COMMAND || !isProductionLikeBuild,

    fingerprint: {
      enabled: isProductionLikeBuild,
      prepend: fingerprintPrepend
    },

    minifyCSS: { enabled: isProductionLikeBuild },

    minifyJS: { enabled: isProductionLikeBuild },

    tests: process.env.EMBER_CLI_TEST_COMMAND || !isProductionLikeBuild,

    sassOptions: {
      includePaths: [
        'bower_components',
        'node_modules/ember-cli-imd/app/styles'
      ]
    },

    sourcemaps: {
      enabled: !isProductionLikeBuild
    },

    vendorFiles: {
      'ember.js': {
        production: 'bower_components/ember/ember.prod.js',
        staging: 'bower_components/ember/ember.prod.js'
      }
    }
  });

  // Use `app.import` to add additional libraries to the generated
  // output files.
  //
  // If you need to use different assets in different
  // environments, specify an object as the first parameter. That
  // object's keys should be the environment name and the values
  // should be the asset to use in that environment.
  //
  // If the library that you are including contains AMD or ES6
  // modules that you would like to import into your application
  // please specify an object with the list of modules as keys
  // along with the exports of each module as its value.
  app.import('bower_components/select2/select2-bootstrap.css');

  return app.toTree();
};
```

**Comment by Soliah** [comment]
So I've had to add:

```
      'ember-data': {
        staging: 'bower_components/ember-data/ember-data.prod.js'
      },
```

to `vendorFiles` for this to work. If I don't have that in there I get the same error. However this seems to break the data section in Ember Inspector.

**Comment by jpaas** [comment]
@Soliah I tried adding ember-data to my vendorFiles but it fails to build because ember-data is no longer installed as a bower component as of ember-cli 2.3.0.

**Comment by Soliah** [comment]
@jpaas I've been talking to @lukemelia about this and I think I've figured it out. So `vendorFiles` isn't necessary at all if you're using ember-cli-deploy apparently. Instead you'll need to not use `if (environment === 'staging')` and instead use `if (process.env.DEPLOY_TARGET === 'staging')` in `config/environment.js`

You also must leave `build.environment = 'production'` in `deploy.js` even for staging environments as ember-cli isn't aware of the staging env like this:

```
  if (deployTarget === 'staging') {
    ENV.build.environment = 'production';
  }

  if (deployTarget === 'production') {
    ENV.build.environment = 'production';
  }
```

This was also helpful: http://blog.firstiwaslike.com/staging-environments-with-ember-cli-deploy/

I haven't confirmed if this works yet. In the process of testing it now.

**Comment by Soliah** [comment]
Also the reason why ember-data isn't working is because it's somehow being included twice. You can confirm this by looking at the data section in Ember inspector and observe there are no models showing, or by running `require('ember-data/model').default === DS.Model;` in the console. This should return true but returns false when this happens.

Thanks to @teddyzeenny for debugging this for me.

**Comment by Soliah** [comment]
Ok so so summarize:

Do this in your `config/environment.js` and use `deployTarget` to switch on the environment instead the passed in `environment`.

```js
module.exports = function(environment) {
  var deployTarget = process.env.DEPLOY_TARGET || environment;
}
```

Remove any occurrence of `vendorFiles` in `ember-cli-build.js`. Then make sure both staging and production environments in `config/deploy.js` have `build.environment = 'production'`

```js
  if (deployTarget === 'staging') {
    ENV.build.environment = 'production';
  }

  if (deployTarget === 'production') {
    ENV.build.environment = 'production';
  }
```

**Comment by jpaas** [comment]
Thanks so much @Soliah ! I've been deploying this app for 6 months, and apparently the config was subtly wrong all along even though I dutifully followed the ember-deploy docs. It all appears to be good now. Clearly this wasn't an ember-data problem so much as a misunderstanding of how to use ember-deploy for staging.

**Comment by bmac** [comment]
Thanks for debugging this issue @Soliah. :tada:

**Comment by pangratz** [comment]
Thanks for tracking this down @Soliah!! This started to look like a very annoying bug, but you tracked it down to "just" a misconfiguration.
