### ISSUE TITLE
Observers on properties 'isLoading', 'isLoaded' and 'isSaving' are not working

### ISSUE THREAD

**Issue by fguillen** [emberjs/data#4133]
I started a question in StackOverflow but as don't get any answer I am starting to think it is a bug:

- http://stackoverflow.com/questions/35139936/emberjs-understanding-ds-model-life-cycle

**Comment by bmac** [comment]
Hi @fguillen. 

The 'isLoading', 'isLoaded' and 'isSaving' properties are all implemented as computed properties. In Ember, computed properties are lazy and do not compute their state until they are requested for the first time using `.get` or displayed in a template. So despite the fact that conceptually we as developers may know the value of `isLoading` is changing and will return a different value when `record.get('isLoading')` is called, as far as Ember is concerned the value of `isLoading` is undefined until some code explicitly asks Ember for that value and Ember takes the time to compute its state.

As a result, when you use `Ember.observer` to watch a computed property it will not be able to detect changes in the computed property until some other code has attempted to access the value of the computed property.

Observers also have a few other gotcha that you may want to be aware of. @stefanpenner has a good talk about their issues https://www.youtube.com/watch?v=vvZEddrClAQ and why they should be used sparingly.


I hope this explanation helps.

**Comment by stefanpenner** [comment]
@bmac you should submit that to SO, and get your 200pt bounty :)

**Comment by fguillen** [comment]
Hi @bmac thanks a lot for the explanation and for the video link, very clarifying.

After understanding this I see 2 mayor problems:

1. If computed properties are not observable this should be very clear in the documention. In the section of the _Observer_ and in the section of the _Properties_ indicating in the property documentation if it is a _computed property_ or not.

2. I don't see any way I can react in a Model state changes :/
