### ISSUE TITLE
How to get meta information on createRecord ?

### ISSUE THREAD

**Issue by vinothwindows47** [emberjs/data#4138]
Hi My Request is : 
 

`/file/newResource =>   createRecord({
                                                                   parenFolder : "testproj/src",
                                                                   fileName : "helloworld.java"
                                                           });` 

Response is  : 

` { "newFile": {},  meta: { result: "Success", message: "File Created Successfully ..."} }`

I did not get meta information in latest ember data version ....

**Comment by fivetanley** [comment]
Can you give us a fuller example? There are several methods in Ember Data called `createRecord` so I'm not sure what your question is about.

**Comment by pangratz** [comment]
@vinothwindows47 do you mean something like:

```js
store.createRecord('file', {
  parentFolder: "testproj/src"
}).save().then(function(newFile) {
  assert.deepEqual(newFile.get("meta"), { result: "Success" });
});
```

Because that is currently not possible but tracked on the todo list in #2905...

**Comment by vinothwindows47** [comment]
Yes .. @pangratz

**Comment by pangratz** [comment]
@vinothwindows47 I am closing this issue since it is already tracked in #2905...
