### ISSUE TITLE
Reproducible invalid transitions when saving a model twice

### ISSUE THREAD

**Issue by koreiklein** [emberjs/data#4144]
I've been tracking an issue where ember-data will throw an error saying

`Error: Attempted to handle event 'didCommit' on <phoenix@model:user::ember629:34> while in state root.loaded.updated.uncommitted.`

For the most part, the error was intermittent and I could only get it to happen 1 in every 20 tries or so.

After some playing around, I found a way to reproduce it consistently:

The code I'm using is

``` javascript
let user = this.get('userManager.user');

user.set('firstname', user.get('firstname') + ' modified');
user.save();
user.set('firstname', user.get('firstname') + ' modified');
user.save();
debugger;
user.set('firstname', user.get('firstname') + ' modified');
```

The debugger breakpoint is key.  Without it, the timing doesn't work out and I'll have to run the code many times before I get an actual error.  If instead, I pause for a second or two after hitting the breakpoint, I can repro consistently.

Also, the repro only works with a suitable backend hooked up (of course).

It appears that the 'didCommit' event is happening when the `save()` promises resolve.  Somehow, this case leads to a 'didCommit' transition when the state machine is not in the right state.

A few questions:
- Is this a known issue?
- Should I expect ember-data to deal with issues like this, or should I be handling them myself?
- Any idea how to fix the problem?

**Comment by workmanw** [comment]
I'm just a user of ember-data so I can't speak to what "is suppose to happen". 

In our app, it's high interactable. Lots of inline editing, drag and drop, realtime updates and we can't "lock the ui" while a record is saving. We use to get this error a lot. I believe what's happening is is your second `save` call is coming **before** the first `save` call completes. I'm not 100% positive that's what's happening based on your description about the `debugger`, but the error and symptoms kind of sounds right.

To fix this problem, we implemented a save throttle on the models. Here is a gist: https://gist.github.com/workmanw/aa02325ea92fdd4744cb . So in this case all of our model extend from our App's BaseModel. If the user saves a record while a save is already inflight, it's basically queued until after the first save completes. Maybe you can give that a shot and see if that helps?

** Disclaimer: When I had this problem I asked around and was told that multiple concurrent saves of a single record was not supported by ember-data. It was recommend that I lock my UI, which is not an option for us. So this solution might not be endorsed my ember-data folks. Use at your own discretion. :)

**Comment by koreiklein** [comment]
Thanks, I like the idea there. I gave it a shot and it fixed everything.

**Comment by koreiklein** [comment]
I have, however, noticed one important caveat:

When using the code in the above gist, if you make two calls to save one right after the next, then the second promise never resolves.

You can fix the problem most simply by removing the check for `hasDirtyAttributes`.

That fix can lead to a some unnecessary POSTs. I don't mind then personally, though I can imagine a more elaborate fix that would still make a small number of POSTs and ensure that every returned promise does eventually resolve.

**Comment by runspired** [comment]
Since we no longer utilize a state-machine firing multiple requests will not error.
