### ISSUE TITLE
Deprecation ember-application.injected-container triggered inside ember-data code

### ISSUE THREAD

**Issue by jnfingerle** [emberjs/data#4151]
I've got a customized set of store, adapter, and serializer classes. For testing I used a setup of those classes similar to https://github.com/emberjs/data/blob/v2.3.3/tests/helpers/store.js. When running tests in this setup (that worked fine before 2.3.*) I get

> DEPRECATION: Using the injected `container` is deprecated. Please use the `getOwner` helper instead to access the owner of this object. [deprecation id: ember-application.injected-container] See http://emberjs.com/deprecations/v2.x#toc_injected-container-access for more details.
>         at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:16695:7)
>         at raiseOnDeprecation (http://localhost:4200/assets/vendor.js:16605:12)
>         at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:16695:7)
>         at invoke (http://localhost:4200/assets/vendor.js:16711:7)
>         at deprecate (http://localhost:4200/assets/vendor.js:16664:32)
>         at Object.deprecate (http://localhost:4200/assets/vendor.js:26672:37)
>         at Object.defineProperty.get (http://localhost:4200/assets/vendor.js:12125:26)
>         at getOwner (http://localhost:4200/assets/vendor.js:79144:22)
>         at modelFactoryFor (http://localhost:4200/assets/vendor.js:78280:55) 

This basically complains about https://github.com/emberjs/data/blob/v2.3.3/addon/-private/utils.js#L71 using the container (in this case caused by https://github.com/emberjs/data/blob/v2.3.3/addon/-private/system/store.js#L1530, there are different causes, but all of the referring to getOwner in utils.js).

https://github.com/emberjs/data/blob/v2.3.3/addon/-private/utils.js#L60 promises that this polyfill won't trigger a deprecation, so I would consider that a bug. 

Having said that: Is this approach to test a set of custom store, adapter and serializer as intended (and: future proof), or could you recommend a better approach that might not trigger this behaviour by e.g. returning an owner in https://github.com/emberjs/data/blob/v2.3.3/addon/-private/utils.js#L67?

**Comment by pangratz** [comment]
Can you reproduce this is an sample app? Also it would be interesting how your `setupStore` differs from the one used in `ember-data`...

**Comment by jnfingerle** [comment]
Hi, my setupStore looks like this:

```
export function setupStore(module, models) {
  module.registry = new Ember.Registry();
  module.container = module.registry.container();

  module.registry.register('service:store', MyStore.extend({
    adapter: '-default'
  }));

  module.registry.optionsForType('serializer', {singleton: false});
  module.registry.optionsForType('adapter', {singleton: false});
  module.registry.register('serializer:-rest', MyRestSerializer);
  module.registry.register('adapter:-default', MyRestAdapter);

  module.registry.register('transform:boolean', DS.BooleanTransform);
  module.registry.register('transform:date', DS.DateTransform);
  module.registry.register('transform:number', DS.NumberTransform);
  module.registry.register('transform:string', DS.StringTransform);

  _.forOwn(models, (model, modelName) => {
    module[modelName] = model;
    module.registry.register('model:' + Ember.String.dasherize(modelName),
          model);
  });

  module.store = module.container.lookup('service:store');
  module.adapter = module.store.get('defaultAdapter');
}
```

I'll try and provide a test case. Unfortunately I cannot (read: am not allowed to) share the "real" code.

**Comment by jnfingerle** [comment]
OK, I've got a test case with setupStore copied verbatim from https://github.com/emberjs/data/blob/v2.3.3/tests/helpers/store.js:

Take a newly generated `ember addon` (ember-cli 2.3.0-beta.2) and add test/integration/some-test.js as follows:

```
/* globals test, module */
import Ember from 'ember';
import DS from 'ember-data';

/*
 setupStore copied from
 https://github.com/emberjs/data/blob/v2.3.3/tests/helpers/store.js
*/
function setupStore(options) {
  var container, registry;
  var env = {};
  options = options || {};

  if (Ember.Registry) {
    registry = env.registry = new Ember.Registry();
    container = env.container = registry.container();
  } else {
    container = env.container = new Ember.Container();
    registry = env.registry = container;
  }

  env.replaceContainerNormalize = function replaceContainerNormalize(fn) {
    if (env.registry) {
      env.registry.normalize = fn;
    } else {
      env.container.normalize = fn;
    }
  };

  var adapter = env.adapter = (options.adapter || '-default');
  delete options.adapter;

  if (typeof adapter !== 'string') {
    env.registry.register('adapter:-ember-data-test-custom', adapter);
    adapter = '-ember-data-test-custom';
  }

  for (var prop in options) {
    registry.register('model:' + Ember.String.dasherize(prop), options[prop]);
  }

  registry.register('service:store', DS.Store.extend({
    adapter: adapter
  }));

  registry.optionsForType('serializer', {singleton: false});
  registry.optionsForType('adapter', {singleton: false});
  registry.register('adapter:-default', DS.Adapter);

  registry.register('serializer:-default', DS.JSONSerializer);
  registry.register('serializer:-rest', DS.RESTSerializer);

  registry.register('adapter:-rest', DS.RESTAdapter);

  registry.register('adapter:-json-api', DS.JSONAPIAdapter);
  registry.register('serializer:-json-api', DS.JSONAPISerializer);

  env.restSerializer = container.lookup('serializer:-rest');
  env.store = container.lookup('service:store');
  env.serializer = env.store.serializerFor('-default');
  env.adapter = env.store.get('defaultAdapter');

  return env;
}

/*
 * Integration-Tests
 */
module('integration ', {
  beforeEach: function() {
    setupStore(this);
  }
});

test('some test', function(assert) {
  assert.ok(true);
});
```

This leads to two of those deprecation warnings. 

Of course, there is a minimal version of this with a newly generated `ember addon` (ember-cli 2.3.0-beta.2) and test/integration/some-test.js as follows:

```
/* globals test, module */
import Ember from 'ember';
import DS from 'ember-data';

module('integration ', {});

test('some test', function(assert) {
  const registry = new Ember.Registry();
  registry.register('service:store', DS.Store);
  registry.container().lookup('service:store');
  assert.ok(true);
});
```

**Comment by sly7-7** [comment]
I don't know if it's related, but executing the ember-data test suite in the browser also throw this deprecation warning...

The "funny" thing is that the function which throws this message, is the `getOwner` function itself: 

```
See http://emberjs.com/deprecations/v2.x#toc_injected-container-access for more details.
        at HANDLERS.(anonymous function) (http://localhost:7357/assets/vendor.js:16679:7)
        at raiseOnDeprecation (http://localhost:7357/assets/vendor.js:16589:12)
        at HANDLERS.(anonymous function) (http://localhost:7357/assets/vendor.js:16679:7)
        at invoke (http://localhost:7357/assets/vendor.js:16695:7)
        at deprecate (http://localhost:7357/assets/vendor.js:16648:32)
        at Object.deprecate (http://localhost:7357/assets/vendor.js:26656:37)
        at Object.defineProperty.get (http://localhost:7357/assets/vendor.js:12109:26)
      ***  at getOwner (http://localhost:7357/assets/vendor.js:78297:26) ***
        at init (http://localhost:7357/assets/vendor.js:76241:131)
```

**Comment by jnfingerle** [comment]
Yes, it's in the getOwner polyfill that's supposed to suppress the deprecation warning (at least this is what's said in the comments).

**Comment by rwjblue** [comment]
Can someone provide a run able demo showing this?

**Comment by pangratz** [comment]
I can confirm, as pointed out by @sly7-7, that the deprecations also show up in the browser console when running `ember serve` on latest `master`...

**Comment by rwjblue** [comment]
Thank you. I will dig into it this morning.

**Comment by jnfingerle** [comment]
My minimal test case can be found here: https://github.com/jnfingerle/ember-data-issue-4151

It's really just a newly generated ember addon (ember-cli 2.3.0-beta.2) and one added file (test/integration/some-test.js) as described above.

**Comment by rwjblue** [comment]
Also, just to be clear, the issue title is inferring that Ember Data is triggering deprecations in a running application which is not the case. The Ember Data testing infrastructure was causing deprecations, and that testing infrastructure is not public API...

**Comment by jnfingerle** [comment]
For my part, the deprecations are triggered when running the *test code* of **my own set of store, adapter and serializer** (see above). This isn't the running app, but it isn't just the internal ember data tests either, it's the tests in my own code. (And to make things worse, this blew my *.tap file for 300 tests up to 100MB wich made jenkins choke and fail the build; I know this is my own problem, but wanted to at least tell the story.)

If there is another (blessed) way how to test the integration of modified store/adapter/serializer that doesn't use this API (namely creating a new Ember.Registry object and using it), I'd gladly be pointed into the right direction.

**Comment by sly7-7** [comment]
@jnfingerle Maybe you could see how it's done in the related pr, fixing the code for ember-data tests.
You should give an owner to the container, see https://github.com/emberjs/data/pull/4155/files.

Hope that helps

**Comment by rwjblue** [comment]
@jnfingerle using moduleFor('asdf' { integration: true }) is public API from ember-test-helpers, and gives you the ability to use all of the normal test helpers.

**Comment by jnfingerle** [comment]
@sly7-7 Thanks, just did that and it works great.

@rwjblue Thanks, but so far I haven't figured out how to do an integrated test of store/adapter/serializer with the normal test helpers, only unit tests of each. Since there are many subtleties in the interaction of my implementation, I want to test automatically a store.find(...) etc. that uses my own versions of each in one integrated test. Anyway, this might be a problem at my end, if there is an example somewhere how to do this, I'd be very happy.
