### ISSUE TITLE
Paginated sideloaded relationships

### ISSUE THREAD

**Issue by Finhas** [emberjs/data#4157]
Say I have `author.hasMany('books', {async: true})` and in the author route, `adapterOptions` which has `fields: {'author': 'books'}` but does not `include: books`.

````
{
   data: {
      id: "293313",
      type: "authors",
      links: {
         self: "/authors/293313"
      },
      relationships: {
         books: {
            links: {
               self: "/authors/293313/relationships/books",
               related: "/authors/293313/books"
            }
         }
      }
   }
}
````

In the author template, when requesting `#each author.books as |book|`, ED makes the appropriate request to `author/author.id/books` or in this case `/authors/293313/books`.

The issue is that `/authors/293313/books` is paginated and I need to define/watch those `queryParams` within that request. Is there a way to define that router?

**Comment by Finhas** [comment]
So it looks like this was a point of discussion:
https://github.com/emberjs/data/pull/1517#issuecomment-59463879
and 
https://github.com/emberjs/data/issues/1937#issue-33472419

Both are `closed` but don't solve the issue: `query async hasMany relations through the get method.`

**Comment by mdehoog** [comment]
+1 for supporting for pagination/querying of linked has-many relationships.

@Finhas in the meantime, you could try this addon: https://github.com/mdehoog/ember-data-has-many-query, it provides a separate `query` method for querying hasMany relations.

**Comment by wecc** [comment]
I'm closing this as we're tracking relationship links and pagination for JSON API in #2905.
