### ISSUE TITLE
Can PromiseArray by public?

### ISSUE THREAD

**Issue by jrjohnson** [emberjs/data#4163]
After reading:
http://emberjs.com/blog/2016/01/12/ember-data-2-3-released.html#toc_importing-modules

I was surprised to poke around and discover that PromiseArray is private.  We use it a lot in models and components to do things like filter models based on criteria or to provide a loading indication when several promises need to come together to create a single array.  A lot like this comment by @stefanpenner 
https://github.com/emberjs/data/issues/2754#issuecomment-72910478

Or this implementation in our code:
https://github.com/ilios/frontend/blob/468048edc3446c91f97aea9ff42e987262129d76/app/components/detail-topic-manager.js#L21

Should I create my own implementation of an promise proxy + array?  It's not a lot of effort, but it is nice to have a convention for this common problem across code bases.

**Comment by bmac** [comment]
I think its unlikely that `PromiseArray` would be made public. While, it solves a very real problem today of allowing templates to iterate over async hasMany relationships in templates it often results in some awkward code when working with a `PromiseArray` in JavaScript land. The main issues that people run into with a `PromiseArray` array is it is not as transparent about proxing to the underlying array as many people assume. This leads to confusion where people often can not use a method that is available in the proxied array or attempting to use the `content` property of the `PromiseArray` for equality checks.

Currently, the Ember Data team is exploring other solutions to the problem of rendering promise's values in templates such as @fivetanley's [promise aware templates](https://github.com/emberjs/rfcs/pull/110) proposal.

**Comment by bmac** [comment]
We talked about this issue in today's Ember Data team meeting and it was agreed that PromiseArray will remain private for the reasons mentioned above.

**Comment by jrjohnson** [comment]
Thanks.  I'm going to give promise aware templates a try, that looks like a nice approach.
