### ISSUE TITLE
Embedded record shows up null if it is seen twice in same store.query call

### ISSUE THREAD

**Issue by danconnell** [emberjs/data#4165]
So, this is going to be vague, and I apologize for that, but I can't create a JSBin for it, since I don't know how to reproduce the problem. We use embedded relations all over our site, and don't have a problem, except in one spot.

In one spot, we have a problem where an embedded record (via DS.belongsTo with async: false) appears as null in the setupController hook, right after it's been loaded and nothing has been done to the data. This issue, however, only happens to all but the last record that were loaded in the query that have the same embedded model.

If the id on the embedded model is changed, everything works fine. If the order of the data being returned is changed, it's still only the last one that works (so this means it's regardless of content).

I'm at a loss because we do this a lot and this is only an issue in one spot, and I don't understand why. Hoping someone has an idea of something I can look for that I overlooked or can point me in the right direction in debugging Ember data code (what files might be relevant here?). I'm 99% sure it's not a problem with my own code at this point since I can see in my serializers that that the models are getting normalized but then the data isn't there later on in the loading path.

Again, sorry for the vagueness, but it's hard for me to be more specific since anything more specific and you'd just want to say "it should be working" and I know it should since the structure of my code and data being loaded is the same as other places where it's working fine.

I don't mind stepping through Ember data code, I'm just not sure where to start, so if someone could point me in the right direction for this type of problem, I'd appreciate it.

**Comment by bmac** [comment]
@danconnell I'd start by trying to set `{ inverse: null}` on your `belongsTo` relationship. There are cases in Ember Data where its inverse relationship heuristic guesses wrong and assumes a 1 to 1 relationship exists. This can result in scenarios where Ember Data erroneously tries to keep this 1 to 1 relationship in sync and valid by nulling previous relationships that refer to the same record. This often manifest in a "last relationship seen wins" pattern like the behavior you are describing.

If it seems like this is impacting your app the workaround is usually to explicitly set the inverse property for your problematic relationship.

**Comment by danconnell** [comment]
Thanks! That was it.

**Comment by pangratz** [comment]
Kind of related I guess #3804
