### ISSUE TITLE
Record id always gets coerced to string

### ISSUE THREAD

**Issue by ctusch** [emberjs/data#4166]
I'm using Ember Data with JSON API. No matter what the type of a record's id is Ember Data always coerces it to string. When updating such a record this leads to wrong data types on the server. I haven't seen any possibility in Ember Data's sources to circumvent this.

**Comment by bmac** [comment]
Hi @ctusch. It should be possible to achieve this behavior in Ember Data by overriding the `serialize` method in your application serializer.


```js
// app/serializers/application.js
export default DS.JSONAPISerializer.extend({
  serialize: function(snapshot, options) {
    var serialized = this._super.apply(this, arguments);
    serialized.data.id = parseInt(snapshot.id, 10);
  }
});
```

**Comment by ctusch** [comment]
The problem is how should I know whether the original id was a number or a
string etc.? I haven't found a good place in Ember Data to store this
information or the original id.

**Comment by bmac** [comment]
Does the id's type vary per model class or per record? You can define a serializer for a specific model class so it will always transform the id in the same way for every record of that model class.

**Comment by ctusch** [comment]
It varies per model. Defining a serializer for every model whose id isn't a
string would work I guess. But we are going to have a lot of models (big
product with over 400 tables) so this feels like a really tedious
workaround.

**Comment by fivetanley** [comment]
The reason Ember Data coerces to a string internally is because many backends use UUIDs, which are randomly generated strings. Also, JavaScript has a limit on large numbers so after a certain point, numbers on integers are chomped off. Many people work around this by storing the IDs as strings.

You could define an `ApplicationSerializer` with the following `serialize` function that switches on type:

```javascript
import DS from 'ember-data';

var MODELS_REQUIRING_INTEGER_PRIMARY_KEY = [
  'post'
];

export default DS.JSONAPISerializer.extend({
  serialize: function(snapshot, options) {
    var serialized = this._super.apply(this, arguments);
    // only serialize certain models, like post. the `modelName` property is dasherized, so a class like
   // BlogPost would be `blog-post`.
    if (MODELS_REQUIRING_INTEGER_PRIMARY_KEY.indexOf(snapshot.modelName) >= 0) {
      serialized.data.id = parseInt(serialized.data.id, 10);
    }
    return serialized;
  }
});
```
