### ISSUE TITLE
Misleading assert - passing classes to store methods has been removed

### ISSUE THREAD

**Issue by courajs** [emberjs/data#4170]
Specific message: "Passing classes to store.serializerFor has been removed. Please pass a dasherized string instead of undefined"
See [JSBin](http://emberjs.jsbin.com/bowugudede/edit?js,output)
I bumped into this when using the `EmbeddedRecordMixin`, and was failing to include `type` on one of the embedded records. This message was not very helpful

**Comment by courajs** [comment]
I'd envision a fix for this might be more checks like https://github.com/emberjs/data/blob/master/addon/-private/system/store.js#L960

**Comment by Znegl** [comment]
This is also a problem when the server returns data instead of IDs to a hasMany relation, since it's looking for id.type instead of singularizing the key.
