### ISSUE TITLE
Using ember-ajax with Ember Data

### ISSUE THREAD

**Issue by taras** [emberjs/data#4175]
The purpose of this issue is to flash out and later keep track of the progress of integrating [`ember-ajax`](http://github.com/ember-cli/ember-ajax) and Ember Data. 

@alexlafroscia and I spent some time thinking through how the adoption process might work. Here are some of our thoughts. We're open to suggestions, both strategic and tactical. 

The migration path will be gradual and will eventually result in ajax code being removed from Ember Data's RESTAdapter in Ember Data 3.0. 

To get there we propose the following path:
- [ ] Refactor RESTAdapter to allow users to opt-in to use Ember Ajax Service to make ajax requests
- [ ] Encourage users to use error detection helpers from Ember Ajax Service to ease transition
- [ ] Introduce deprecation warnings to inform users who have dead code in their application's adapters
- [ ] Write Ember Data blog post that introduces Ember Ajax and provides information about migration path
- [ ] Remove ajax code from Ember Data RESTAdapter before 3.0
## Opt-in to use Ember Ajax Service

To opt-in the user will inject Ember Ajax Service into the adapter on `ajaxService` property.

``` javascript
export default DS.JSONAPIAdapter.extend({
  ajaxService: Ember.inject.service('ajax')
});
```
## Error detection helpers

Ember Ajax comes with helpers that can be used to distinguish errors. Ember Ajax provides the following helpers: `isUnauthorizedError`, `isForbiddenError`, `isInvalidError`, `isBadRequestError`, `isNotFoundError` and `isServerError`. As part of the migration path, we'll make it possible for Ember Ajax's helpers to detect Ember Data ajax errors: `AdapterError`, `TimeoutError` and `AbortError`. 

Using Ember Ajax's helpers to detect errors will allow us to deprecate Ember Data's `AdapterError`, `TimeoutError` and `AbortError`. (this part might need to be flashed out a bit further)
## Deprecation warnings

When the user opts-in to using Ember Ajax Service, the default ajax request/response methods on RESTAdapter becomes dead code that's never called. Detecting this dead code is difficult because it's never called. We'll add deprecation warnings that'll inform the user at built time about dead code in their adapters.
## Remove ajax code

We'll be able to remove the following methods from the RESTAdapter
    - handleResponse
    - isSuccess
    - isInvalid
    - ajaxOptions
    - parseErrorResponse
    - normalizeErrorResponse
    - generatedDetailedMessage

WIP PR for this issue is #4176

**Comment by tomdale** [comment]
Hey @taras, we are excited about this and want to make it happen. I think we definitely need to be careful about deprecating the current AJAX related code but not breaking it. Despite being private, it's in common usage. But we should definitely plan to remove it in Ember Data 3.0 if possible.

**Comment by taras** [comment]
Agreed. 

If the ED team doesn't have any objections to what I described above then we'll start working on making this happen. I'm also going to promote this issue to the Ember community to tease out complicated use cases that we might not have considered.

**Comment by bmac** [comment]
No objections to the overall direction. Lets do this @taras :+1:.

**Comment by sandstrom** [comment]
Friendly ping 😃  What's the state of this?

**Comment by alexlafroscia** [comment]
@sandstrom Right now, there's a mixin that `ember-ajax` provides that swaps out the Ember Data networking code to use Ember AJAX instead.  We haven't gotten to actually replacing the ED networking code for real yet.

**Comment by sandstrom** [comment]
@alexlafroscia ah, thanks for the update!

**Comment by alexlafroscia** [comment]
Sure thing. If there's a major interest in this happening, I would be willing to work on it more, but I don't really know how many people are currently using the Mixin-based support that we provide now and am not sure how much of a benefit people would really get from the effort to see this through.

**Comment by bmac** [comment]
@alexbrinkman if you have the time to work on a pr for this I'd love to see it happen.

**Comment by alexbrinkman** [comment]
@bmac - I think you got the wrong Alex.  Though I would love to contribute to Ember Data, I don't think you want my PR :) Perhaps you meant @alexlafroscia?

**Comment by alexlafroscia** [comment]
I think that was the case ;)

**Comment by bmac** [comment]
You are correct. Sorry about that. 😉

**Comment by riklaunim** [comment]
I don't know how much it's related but I tried to use ember-ajax for my JSONAPIAdapter in ember 2.9 and it screwed up backend validation with ember-cp-validation. Frontend validations work, but backend error responses aren't noticed - the code thinks that the fields are valid. ( https://github.com/offirgolan/ember-cp-validations/issues/373 )

What also changed is model.isValid was true on error response while model.isError was true on error response while the docs say that isError ca be true "for any reason other than a server-side validation error." Both properties behave opposite to what documentation says about them.

**Comment by stefanpenner** [comment]
This seems to have gone stale, https://github.com/emberjs/data/issues/4929 seems to be the most recent discussion
