### ISSUE TITLE
Related records are reloaded even when they already exist in the store

### ISSUE THREAD

**Issue by wvteijlingen** [emberjs/data#4179]
This was discussed with @wecc in the Ember Slack.

Given a `brand` model that has many `products`, each `product` belongs to a `brand`. When doing `brand.get('products')` it also requests `http://example.com/api/products/{id}/brand` for each loaded product. This shouldn't happen when the brand is already in the store.

This bug happesn when a product payload contains a `links` hash in its relationship data, even when a `data` hash containing the brand id is already present.

The following product payload contains a `links` hash _only_ for the first product. The result is that Ember Data requests `http://localhost:5000/api/v1/brands/1/products` and then `http://localhost:5000/api/v1/products/1/brand`. The brand for the second product is resolved from the local store data.

**Brand payload**
```json
{
  "data": {
    "id": "1",
    "type": "brands",
    "links": {
      "self": "http://localhost:5000/api/v1/brands/1"
    },
    "attributes": {
      "title": "My Brand",
    },
    "relationships": {
      "products": {
        "links": {
          "self": "http://localhost:5000/api/v1/brands/1/relationships/products",
          "related": "http://localhost:5000/api/v1/brands/1/products"
        }
      }
    }
  }
}
```

**Products payload**
```json
{
  "data": [
    {
      "id": "1",
      "type": "products",
      "links": {
        "self": "http://localhost:5000/api/v1/products/1"
      },
      "attributes": {
        "created-at": "2016-02-16T15:49:06.643Z",
        "updated-at": "2016-02-16T15:49:06.643Z",
        "title": "First product",
      },
      "relationships": {
        "brand": {
          "links": {
            "self": "http://localhost:5000/api/v1/products/1/relationships/brand",
            "related": "http://localhost:5000/api/v1/products/1/brand"
          },
          "data": {
            "type": "brands",
            "id": "1"
          }
        }
      }
    },
    {
      "id": "2",
      "type": "products",
      "links": {
        "self": "http://localhost:5000/api/v1/products/2"
      },
      "attributes": {
        "created-at": "2016-02-16T15:49:06.647Z",
        "updated-at": "2016-02-16T15:49:06.647Z",
        "title": "Second Product",
      },
      "relationships": {
        "brand": {
          "data": {
            "type": "brands",
            "id": "1"
          }
        }
      }
    }
  ]
}
```

**Comment by pangratz** [comment]
Seems like #4099 is related...

**Comment by wvteijlingen** [comment]
I seems this is not an issue with Ember Data after all. I'm using EmberValidations on my models and it seems that validations on relationships trigger a fetch. In this case I have a `presence: true` rule for the `brand` relationship. This causes a fetch for the brand because it checks whether the brand field is set.
