### ISSUE TITLE
Problem with `flushCanonicalLater` after  upgrading to Ember 2.x

### ISSUE THREAD

**Issue by Serabe** [emberjs/data#4185]
We have an application where we might add a record on initialization to a relationship. We delay pushing it to the `actions` queue. After upgrading to Ember and Ember Data 2.x (it happens in both 2.2 and 2.3 at least), the `flushCanonical` runs after pushing the record and that [causes a reorder of it](https://github.com/emberjs/data/blob/883cf9c0ebe18277b1c8fab2381fe46eacfb13d9/addon/-private/system/relationships/state/relationship.js#L163-L178).

Our current _solution_ (though in Spanish we might call this _ñapa_), is getting the backburner from the store and adding that record after the relationships have been synced.

Is there any recommended way of fixing this or any way I can help with the diffing?

**Comment by fivetanley** [comment]
An example project via `ember new` or JSBin/Ember Twiddle as outlined in the Contributing.md document in the project repository would be a great first step. Even some example code of what you are doing would be great.

**Comment by pangratz** [comment]
This issue has been open for a while. I am triaging issues and going to close this. @Serabe feel free to reopen if you think this issue is still present in your app. Ideally with a code sample or ember-twiddle/JSBin demonstrating the issue. Thanks!
