### ISSUE TITLE
ember-cli-shim check errors if no shim is provided

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/data#4192]
this prevents us from bundling shims with the future ember module.

I suspect something like `this.project.findAddonByName('ember-source')` will be a sufficient check

**Comment by rwjblue** [comment]
Removing the existing checks would cause extra pain to users upgrading and having the wrong versions, but we can definitely make it work properly when `ember-cli-shims` is not present in `bower.json`. 

Also, we can't use `findAddonByName` because it isn't an addon.

**Comment by stefanpenner** [comment]
@rwjblue i think you misread, if  that addon is present no shims for ember are required. Otherwise it should do the existing flow.

**Comment by rwjblue** [comment]
ember-cli-shims@0.0.6 provided shims for both Ember Data and Ember.  If ember-cli-shims@0.0.6 is present with ember-data@^2.3.0 we need to provide an accurate message telling them to change what they are including.

**Comment by rwjblue** [comment]
I agree that the presence of `ember-source` changes things a bit (because once that happens ember-cli-shims is not needed anymore), but the real issue is that when `ember-cli-shims` is not present in `bower.json` at all we throw an error.

**Comment by rwjblue** [comment]
I submitted https://github.com/emberjs/data/pull/4200 to address, can you review?

**Comment by rwjblue** [comment]
Also, FWIW, you are correct.  I misread initially and thought you were suggesting to use `project.findAddonByName('ember-cli-shims')`.  Sorry about that...

**Comment by stefanpenner** [comment]
I likely left the description too ambiguous
