### ISSUE TITLE
Ember Data 2.4.0 reports its version with a git hash

### ISSUE THREAD

**Issue by SaladFork** [emberjs/data#4199]
In the console output after updating to `ember-data@2.4.0` I see:
```
DEBUG: -------------------------------
DEBUG: Ember             : 2.4.1
DEBUG: Ember Data        : 2.4.0+9f8c40927a
DEBUG: jQuery            : 2.2.1
DEBUG: -------------------------------
```

**Comment by rwjblue** [comment]
Hmm.  I thought we addressed this?

**Comment by rwjblue** [comment]
In https://github.com/emberjs/data/pull/4066

**Comment by pangratz** [comment]
This needs to be fixed upstream in [npm-git-info](https://github.com/tricknotes/npm-git-info). I attempted to fix this in tricknotes/npm-git-info#1, but that wasn't sufficient. I am working on another fix.

@SaladFork what `npm` version are you using?

**Comment by pangratz** [comment]
`npm-git-info#1.0.2` has been released, which should fix this issue after clearing `node_modules` and doing a `npm install`.

@SaladFork I am closing this issue, please reopen if you still experience a wrongly reported version.

**Comment by agrobbin** [comment]
@pangratz I could definitely be doing something wrong, but I am getting this same output in a development console for Ember 2.4.2:

> DEBUG: Ember Data : 2.4.2+73b13354fd

I have npm-git-info 1.2.0 installed:

```bash
npm list | grep npm-git-info
│ ├── npm-git-info@1.0.2
```

**Comment by pangratz** [comment]
@agrobbin looks like this issue still exists :disappointed: reopening and will take a look...

**Comment by pangratz** [comment]
@agrobbin what version of `npm` and `node` are you using? Also, what does your `package.json` look like?

**Comment by agrobbin** [comment]
```bash
$ node -v
v5.9.0
$ npm -v
3.7.3
```

My `package.json` looks like:

```json
{
  "name": "insight",
  "version": "1.1.1",
  "description": "Client facing analytics dashboards",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "active-model-adapter": "2.1.1",
    "broccoli-asset-rev": "^2.2.0",
    "dotenv": "2.0.0",
    "ember-ajax": "0.7.1",
    "ember-cli": "2.4.2",
    "ember-cli-accounting": "1.0.0",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-autoprefixer": "0.6.0",
    "ember-cli-babel": "^5.1.5",
    "ember-cli-content-security-policy": "0.5.0",
    "ember-cli-cors": "0.0.2",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-deploy": "0.6.0",
    "ember-cli-deploy-lightning-pack": "0.5.0",
    "ember-cli-htmlbars": "^1.0.1",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.3.1",
    "ember-cli-mirage": "0.1.11",
    "ember-cli-moment-shim": "1.1.0",
    "ember-cli-qunit": "^1.2.1",
    "ember-cli-release": "0.2.8",
    "ember-cli-sass": "5.3.0",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.4.2",
    "ember-deploy-s3": "0.0.3",
    "ember-disable-proxy-controllers": "^1.0.1",
    "ember-export-application-global": "^1.0.4",
    "ember-highcharts": "0.4.2",
    "ember-load-initializers": "^0.5.0",
    "ember-moment": "6.1.0",
    "ember-resolver": "^2.0.3",
    "ember-simple-auth": "1.1.0-beta.3",
    "highcharts": "4.2.3",
    "loader.js": "^4.0.0",
    "semantic-ui-ember": "0.9.3",
    "silent-error": "^1.0.0"
  }
}
```

**Comment by pangratz** [comment]
@agrobbin can you also post the contents of `node_modules/ember-data/package.json` in a gist?

**Comment by agrobbin** [comment]
@pangratz I'm really sorry for the false alarm. It looks like because of my dependency being `^2.4.2` and not `^2.4.3`, it was only pulling in version 2.4.2, which wasn't reported correctly. Clearing `node_modules` and forcing 2.4.3+ fixed it for m!

**Comment by sly7-7** [comment]
@pangratz if that could help:
node: `v5.2.0`
npm: `3.8.5`

[ember-data's package.json](https://gist.github.com/sly7-7/5221a7e0550caa4f782cf9219d2b016b)

Ember 2.3.2
Ember Data 2.4.3+a3e2521f85

**Comment by sly7-7** [comment]
Seems weird, since from cli:

```
var npmGitInfo = require('npm-git-info');
var info = npmGitInfo(require('ember-data/package.json'));

info
{ 
 name: 'ember-data',
  version: '2.4.3',
  sha: 'a3e2521f85c91f18dd455f316572068566ff1a3b',
  abbreviatedSha: 'a3e2521f85',
  ref: undefined
}
```

**Comment by sly7-7** [comment]
Maybe https://github.com/tricknotes/npm-git-info/pull/4 could fix this (I don't know I could try this locally)

**Comment by tricknotes** [comment]
Great thanks for your investigate and nice fix, @sly7-7 
Now I released a new version including [your fix](https://github.com/tricknotes/npm-git-info/pull/4) as [npm-git-info@1.0.3](https://github.com/tricknotes/npm-git-info/tree/v1.0.3).
It works fine for me.

Could you someone try it?

**Comment by sly7-7** [comment]
Let's wait a new release of npm-git-info :)

**Comment by sly7-7** [comment]
I just tested with a new ember-cli app, it's working. Having an ember-data dep to `^2.4.2` (wich is the current default blueprint for a new ember-cli app) gives `DEBUG: Ember Data : 2.4.3`.

Closing this issue (hopefully once and for all now ;))

**Comment by pangratz** [comment]
:heart_eyes: merci so much for taking over this and fix this @sly7-7!! Also, thanks to @tricknotes for the fast response, as always :heart:

**Comment by sly7-7** [comment]
You're welcome :) Small bugs like this are fun to fix, and much more easier than `ds-references` feature :wink:
