### ISSUE TITLE
JSON API missing records spec

### ISSUE THREAD

**Issue by nicolas-dular** [emberjs/data#4201]
JSON API defines the response for missing records with `{"data": null}` [[0](http://jsonapi.org/format/#fetching-resources-responses.)]

Here is a [jsfiddle](http://emberjs.jsbin.com/yisuyizoli/edit?html,js,output ) with the same response as in the JSON API spec. However, we get an error at  https://github.com/emberjs/data/blob/master/addon/-private/system/store/finders.js#L43. 

I couldn't find another issue for this, but I'd like to make a pull request if you can tell me what's the best way to handle this?

**Comment by wecc** [comment]
This is a bit tricky imho. The JSON API [specification](http://jsonapi.org/format/#fetching-resources-responses) states:

> `null` is only an appropriate response when the requested URL is one that might correspond to a single resource, but doesn't currently.

And:

> Note: Consider, for example, a request to fetch a to-one related resource link. This request would respond with null when the relationship is empty (such that the link is corresponding to no resources) but with the single related resource's resource object otherwise.

The way I interpret this is that `/articles/1` should respond with a 404 if there is no article with ID 1. However, if you request `/articles/1/author` and the articles exist but does not yet have an author, a 200 response with `data: null` seems appropriate.

So in Ember Data terms a `store.findRecord('article', 1)` would not accept 200 `data: null` but `article.get('author')` would.

**Comment by nicolas-dular** [comment]
@wecc That's true, my example is probably misleading.
In my own case, I have a single resource like `/subscription` -  in that case there should be `data: null`.
I know ember-data doesn't support single resources yet, I guess this is the problem then for me.

**Comment by wecc** [comment]
@nicolas-dular do you have some kind of "parent" entity like `user` or `account`? if so, you can make `subscription` a belongsTo relationship of that entity.

**Comment by wecc** [comment]
`{ data: null }` should be supported by belongsTo relationships.

**Comment by nicolas-dular** [comment]
@wecc no, it's not a parent from something. But I guess, it is appropriate to say  `/subscription` returns `404` if there is no record.
I'll close the issue, thanks for the quick response.
