### ISSUE TITLE
[master] Module import path error on Windows in production build

### ISSUE THREAD

**Issue by floqqi** [emberjs/data#4218]
For history see #4205 (starting at https://github.com/emberjs/data/pull/4205#issuecomment-193237120).

**Comment by pangratz** [comment]
This should work with latest `master` now since #4215 has been merged. Can you give this another try and report back if it has been resolved? Thanks!

**Comment by floqqi** [comment]
@pangratz 

```json
"ember-data": "emberjs/data#master"
```

works for me!

**Comment by pangratz** [comment]
Nice, thanks for checking! :+1:
