### ISSUE TITLE
queryRecord Regression in Ember Data 2.4

### ISSUE THREAD

**Issue by jherdman** [emberjs/data#4219]
Issue #3790 allowed for `queryRecord` to work with empty responses, e.g. `{ my_model: [] }`. This worked with Ember Data 2.3, but not with Ember Data 2.4. I have a reproduction app available:

* Ember Data 2.4 failing https://github.com/jherdman/issue-3790-reproduction/commit/137d9a830b1c7883f39739beca8f06562e8717c7
* Ember Data 2.3.3 working https://github.com/jherdman/issue-3790-reproduction/commit/1f265eae7ab2c4282399ebbd18f534e189da401a

The repo lives here: https://github.com/jherdman/issue-3790-reproduction. Run the app, hit the index page in your browser. Note the Ember Data 2.4 complains about the empty response, whereas 2.3.3 does not.

**Comment by floqqi** [comment]
Having exactly the same issue as mentioned in https://github.com/emberjs/data/pull/4205#issuecomment-193186882.

This only happens using the development build of `ember-cli` in my app. In the production build (with `ember-data` at version `2.4.0`) the API of `queryRecord` behaves like in `2.3.3` -> no complaining.

I'm not exactly sure what causes this issue. Tested with exactly the same server response in both build modes. Maybe the proxy-server of `ember-cli`?

**Comment by pangratz** [comment]
Looks like regression has been added in [#3864](https://github.com/emberjs/data/pull/3864).

**Comment by floqqi** [comment]
API-Docs:
> Ember build tools will remove any calls to `Ember.assert()` when doing a production build.

That would explain why it only fails in development.

**Comment by bmac** [comment]
This fix has been released as Ember Data `v2.4.3`
