### ISSUE TITLE
Ember Data bower canary build is broken

### ISSUE THREAD

**Issue by bmac** [emberjs/data#4232]
Reported by @danmcclain in https://github.com/tomdale/ember-cli-addon-tests/issues/4

Looks like the file published to the bower repo is missing some content.
https://github.com/components/ember-data/blob/canary/ember-data.js#L14890

**Comment by fivetanley** [comment]
I'm confused, what is missing here?

**Comment by bmac** [comment]
When I looked several days ago it appeared the last 1/4th of the file was missing. I can no longer reproduce the issue now.
