### ISSUE TITLE
Uncaught Error: Could not find module `-private/system/references/record`

### ISSUE THREAD

**Issue by oskarrough** [emberjs/data#4251]
Hi, I'm getting this error in production builds only with ember-data 2.4.2, ember 2.4.3 and ember-cli 2.4.2.

`Uncaught Error: Could not find module `-private/system/references/record` imported from `ember-data/-private/system/references``

Related: https://github.com/emberjs/data/pull/4248#issuecomment-198816278

**Comment by fivetanley** [comment]
Can you post your `bower.json` and `package.json`? Usually these kind of errors are loader.js related, but I wouldn't be surprised if something in ember-data isn't working correctly around feature stripping.

**Comment by oskarrough** [comment]
Sure, I left all the dependencies in as well.

- package.json: http://pastie.org/private/aitrqoisgh1hitcvwzv6eq
- bower.json: http://pastie.org/private/ijynykzs5gg29rc9ifadq

**Comment by floqqi** [comment]
```json
"ember-cli": "2.4.2",
"ember-data": "2.4.2"
```

works for me. Did you clear your cache using `npm cache clean && bower cache clean`?

**Comment by oskarrough** [comment]
Clearing the npm cache did the trick. Sorry and thank you!
