### ISSUE TITLE
belongsTo is empty using JSONAPISerializer

### ISSUE THREAD

**Issue by zion03** [emberjs/data#4252]
I can't understand what wrong with JSONAPIAdapter, but my `relationships` does not set into model.

Versions:
` Ember             : 2.4.1`
`Ember Data        : 2.4.0`

I have two model with belongsTo:

      /models/user.js
      export default DS.Model.extend({
      });

and 

      /models/chat.js
       export default DS.Model.extend({
         userOne: DS.belongsTo('user'),
         userTwo: DS.belongsTo('user'),
      });`

Chat and users loaded but relations is empty:

for example:

      {{#each model as |i|}}
      {{ i.id }}  // output - 1
      {{ i.userOne.id }}  // output - empty 
      {{ i.userTwo.id }}  // output - empty
      {{/each}}

Using this jsonapi format:

```json
{
   "jsonapi":{
      "version":"1.0"
   },
   "included":[
      {
         "type":"user",
         "links":{
            "self":"/users/35"
         },
         "id":"35",
         "attributes":{
            "id":35
         }
      },
      {
         "type":"user",
         "links":{
            "self":"/users/37"
         },
         "id":"37",
         "attributes":{
            "id":37
         }
      }
   ],
   "data":[
      {
         "type":"chat",
         "relationships":{
            "userTwo":{
               "data":{
                  "type":"user",
                  "id":"35"
               }
            },
            "userOne":{
               "data":{
                  "type":"user",
                  "id":"37"
               }
            }
         },
         "links":{
            "self":"/chat/1"
         },
         "id":"1",
         "attributes":{
            "id":1
         }
      }
   ]
}
```

**Comment by fivetanley** [comment]
I think the JSONAPISerializer expects `dasherized` names by default. You can override `keyForRelationship` like so:

```javascript
// app/adapters/application.js
import DS from 'ember-data';
export default DS.JSONAPISerializer.extend({
  keyForRelationship: function() {
    return Ember.String.camelize(key);
  }
})
```

Here's the API documentation: http://emberjs.com/api/data/classes/DS.JSONAPISerializer.html#method_keyForRelationship

Please let us know if that fixes your issue.

**Comment by zion03** [comment]
yep, my fault, it's works. Thanks!
