### ISSUE TITLE
queryRecord returns array, expect single record

### ISSUE THREAD

**Issue by MarkMT** [emberjs/data#4255]
According to the description of `queryRecord` in the [guides](https://guides.emberjs.com/v2.4.0/models/finding-records/)  (emphasis added) -

> If you know your query will return only one result Ember Data provides a convenience method that will return a promise that resolves with **a single record**. Calling `store.queryRecord()` will make a `GET` request with the passed object serialized as query params.

However what I'm seeing in practice is that the return value actually resolves to an _array_ with as many elements as fit the query (and it appears to be a regular javascript array not an Ember.Array). So if I want to use the method in a model I have to do something like this -
```
export default Ember.Route.extend({
  model() {
    return this.store.queryRecord('person', {filter: {name: 'foo'}}).then(function(result) {
      return result[0].get('data');
    });
  }
});
```
It works, but it doesn't seem consistent with what's advertised. The only difference I'm seeing from `query` is that the latter returns an Ember.ArrayProxy rather than a javascript array.

**Comment by MarkMT** [comment]
Seems similar to #4227 but I don't think the discussion there resolves my concern.

**Comment by MarkMT** [comment]
Hmm, looks like I'm on ember 2.3. Maybe that's what the difference is.

**Comment by MarkMT** [comment]
Nope. Just upgraded, same behavior.

**Comment by pangratz** [comment]
What does your response look like?

**Comment by MarkMT** [comment]
If I add this to my model hook:
```
    this.store.queryRecord('person', {filter: {name: 'foo'}}).then(function(result) {
      console.log(result);
      console.log(result[0].get('data'));
    });
```
I get this in the console:

```
[Class]
0: Class
length: 1
__proto__: Array[0]
etc...

EmptyObject {name: "foo"}
```

**Comment by pangratz** [comment]
I mean what does your server return when `this.store.queryRecord('person', { ... })` is invoked?

`store.queryRecord` expects the server to return a single resource. I looks like the response in your case is an array. If your server returns an array, you should use `store.query` instead:

``` jas
this.store.queryRecord('person', {filter: {name: 'foo'}}).then(function(result) {
  return result[0];
});
```

**Comment by MarkMT** [comment]
Sorry... the server returns an array even if there is only one element (which it is). It's a vanilla rails 5 api server.

**Comment by MarkMT** [comment]
If an array is the intended result when the server returns a one element array (a) the method doesn't seem quite as useful as I'd hoped and (b) the guides are a little misleading and I'll file an issue there.

**Comment by MarkMT** [comment]
Incidentally, the server request that is fired by `queryRecord` is to plural route `/persons?filter%5Bname%5D=foo`, which seems to imply that a set of records is expected.

**Comment by urbany** [comment]
I think JSONAPI urls always use the plural form of the resource name. The [filter spec](http://jsonapi.org/format/#fetching-filtering) does not indicate a way to query just one result so it seems normal for Rails to respond with an array.

Maybe it the best thing here would be for Ember to do the following for queryRecord:
* If data is a resource: return the resource
* If data is an array && length == 1: return the first element of the array
* If data is an array && length > 1: return the first element and maybe throw a warning in the console

**Comment by MarkMT** [comment]
@urbany I agree. That's consistent with what I imagined it would do and I think it would make the method more useful than it is at present.

**Comment by pangratz** [comment]
@MarkMT @urbany the behavior for `store.queryRecord` has been clarified in #4300 and `queryRecord` should only be used when your API returns a single object. In all other cases you should use `query` in combination with returning the first object of the array:

```js
this.store.query('person', {filter: {name: 'foo'}}).then(function(result) {
  return result[0];
});
```

I am going to close this issue as the documentation has been adapted accordingly in #4300.
