### ISSUE TITLE
"serializer" blueprint should support different base classes

### ISSUE THREAD

**Issue by Turbo87** [emberjs/data#4266]
The "adapter" blueprint supports the `--base-class` option and automatically detects if an "application" adapter exists. IMHO the same logic should be reused for the "serializer" blueprint too.

**Comment by pangratz** [comment]
This is tackled in #4023. Can you chime in there? Currently the failing test for the serializer prevents that PR from being merged. I think the test is failing because the blueprint from `ember-cli` is used instead of the one provided in `ember-data`...

**Comment by Turbo87** [comment]
@pangratz thanks, didn't see that one

**Comment by pangratz** [comment]
Yeah, the title of that PR is not that descriptive :pensive:
