### ISSUE TITLE
Cannot read property 'container' of null (findRecord)

### ISSUE THREAD

**Issue by robguilfoyle** [emberjs/data#4269]
I have the store injected into a component and I am doing a very basic `this.get('store').findRecord('site', 1);` command which throws an error. I have recently upgraded from 2.2 to 2.4 so this is a new regression I'm assuming. The error goes into this method telling me the store is undefined:

```
  // if `Ember.setOwner` is defined, accessing `this.container` is
  // deprecated (but functional). In "standard" Ember usage, this
  // deprecation is actually created via an `.extend` of the factory
  // inside the container itself, but that only happens on models
  // with MODEL_FACTORY_INJECTIONS enabled :(
  if (_ember.default.setOwner) {
    Object.defineProperty(Model.prototype, 'container', {
      configurable: true,
      enumerable: false,
      get: function () {
        (0, _emberDataPrivateDebug.deprecate)('Using the injected `container` is deprecated. Please use the `getOwner` helper instead to access the owner of this object.', false, { id: 'ember-application.injected-container', until: '3.0.0' });

        return this.store.container; // ERROR claims store doesn't have a container
      }
    });
  }
```

I wish I could be of more help with a JS bin and what not but I just don't have time at the moment. I really appreciate all your work on ember-data and hope someone has seen this before as I have scoured SO.

**Comment by bmac** [comment]
@robguilfoyle what version of Ember Data are you using?

**Comment by robguilfoyle** [comment]
2.4.3 for Data and Ember

**Comment by sly7-7** [comment]
I've tried to reproduce, with no success. @robguilfoyle Here is a twiddle https://ember-twiddle.com/575952c5d55838cd854f, maybe you could try to take it as a starting point to reproduce your case.

**Comment by bmac** [comment]
@robguilfoyle shared this stack trace with me over slack.
```
ember-data.js:3892 Uncaught TypeError: Cannot read property 'container' of nullObject.defineProperty.get @ ember-data.js:3892giveDescriptorSuper @ ember.debug.js:19184addNormalizedProperty @ ember.debug.js:19297mergeMixins @ ember.debug.js:19346mergeMixins @ ember.debug.js:19354applyMixin @ ember.debug.js:19483MixinPrototype.applyPartial @ ember.debug.js:19700Class.proto @ ember.debug.js:36898validatePropertyInjections @ ember.debug.js:32419injectedPropertyAssertion @ ember.debug.js:37309factoryFor @ ember.debug.js:1419Container.lookupFactory @ ember.debug.js:1271(anonymous function) @ ember.debug.js:33431exports.Store.Service.extend.modelFactoryFor @ ember-data.js:9315exports.Store.Service.extend.modelFor @ ember-data.js:9296exports.Store.Service.extend._internalModelForId @ ember-data.js:8672exports.Store.Service.extend.findRecord @ ember-data.js:8357(anonymous function) @ component.js:22applyStr @ ember.debug.js:23428sendEvent @ ember.debug.js:16879notifyObservers @ ember.debug.js:20781propertyDidChange @ …
```

I was also unable to reproduce but the issue looks like the error is happening as when Ember is trying to copy the `container` property from one class prototype to another.

**Comment by robguilfoyle** [comment]
Here is a closer example. I am on a bit of a time crunch so I have ot finished the method, i ended up having to roll back to ED-2.2
https://ember-twiddle.com/575952c5d55838cd854f?openFiles=components.my-component.js%2C

**Comment by robguilfoyle** [comment]
This issue was caused by an attribute I had named container...
