### ISSUE TITLE
nested JSONAPI error objects are not deserialized

### ISSUE THREAD

**Issue by Asherlc** [emberjs/data#4273]
Twiddle: https://ember-twiddle.com/f2738639cbb16f33ed16?openFiles=routes.application.js%2C

Ideally, the nested error would be applied to the referenced model, in this case the author. Currently, this omission makes it difficult to do embedded record saving.

**Comment by kernel-io** [comment]
have just run into this issue myself. possibly I could fix this in a model specific serializer?

**Comment by bmac** [comment]
@kernel-io if you get around to implementing hasMany I would be interested in a pr that adds this functionality to Ember Data.

**Comment by kernel-io** [comment]
turns out I don't have any clue on how the JSONAPI error spec would work for a nested hasMany payload. Any clues? Can't find any documentation regarding it, #jsonapi irc is dead :8ball:

**Comment by kernel-io** [comment]
so here is it with hasMany support, code will probably need some cleaning up, and DRY'ing to make it look like part of ember data.

this expects a response from the server like this:
<img width="1003" alt="screen shot 2016-04-06 at 1 21 27 pm" src="https://cloud.githubusercontent.com/assets/1523960/14304922/8bae2932-fbfa-11e5-8a88-7d91af3684fd.png">


````javascript
  extractErrors(store, typeClass, payload, id) {
    payload = this._super(...arguments)

    let record = store.peekRecord(typeClass.modelName, id)
    let errorKeys = _.keys(payload)

    typeClass.eachRelationship( (name, descriptor) => {
      let key = this.keyForAttribute(name, 'deserialize')
      if (descriptor.kind === 'belongsTo') {
        let relatedModel = record.get(name)
        let errorRegex = new RegExp(`^${key}/attributes/(.*)`)

        errorKeys.forEach( (errorKey) => {
          let match = errorKey.match(errorRegex)

          if (match) {
            relatedModel.get('errors').add(camelize(match[1]), payload[match[0]])
            relatedModel.set('isError', true)
            delete payload[match[0]]
          }
        })

      } else if (descriptor.kind === 'hasMany') {
        let errorRegex = new RegExp(`^${key}/(.*)/attributes/(.*)`)

        errorKeys.forEach( (errorKey) => {
          let match = errorKey.match(errorRegex)
          if (match) {
            let relatedModel = store.peekRecord(descriptor.type, match[1])            

            if (relatedModel) {
              relatedModel.get('errors').add(camelize(match[2]), payload[match[0]])
              relatedModel.set('isError', true)
              delete payload[match[0]]
            }
          }
        })
      }

    })

    return payload
  }
````

**Comment by youroff** [comment]
Does it peek record by id? But in case of saving related hasMany records there's no ids, however order is preserved as far as I can tell. Also add on errors is deprecated, not sure if there's another way of adding errors.

**Comment by kernel-io** [comment]
yeah I have no clue on the proper way to add errors these days, documentation is hidden somewhere....
I have client generated id's, so yeah.... Any way you can think of to handle it if you don't have client generated id's?

**Comment by youroff** [comment]
Yeah, assuming that it's responsibility of API to preserve order, something like this works for me: https://github.com/emberjs/data/issues/4298#issuecomment-206107864
To make it less hacky, InvalidError needs some apis for nested errors and then we need changes either to `InternalModel` https://github.com/emberjs/data/blob/master/addon/-private/system/model/internal-model.js#L721-L733 or(and) `Store`. Though I don't know the architecture of `ember-data` in details yet.

**Comment by youroff** [comment]
Btw, documentation is generated form code, so it's right there:
https://github.com/emberjs/data/blob/master/addon/-private/system/model/errors.js#L209-L225
http://emberjs.com/api/data/classes/DS.Errors.html#method_add

**Comment by Asherlc** [comment]
@kernel-io does your snippet work recursively? i.e. for multiple layers of nested models.

**Comment by kernel-io** [comment]
@Asherlc try and let us know!

**Comment by runspired** [comment]
Errors are now handled opaquely, this should just work. Let's revisit if removing extractErrors does not result in the errors appearing on Error.errors / is not retrievable from the cache via https://api.emberjs.com/ember-data/5.2/classes/%3CInterface%3E%20Cache/methods/getErrors?anchor=getErrors
