### ISSUE TITLE
Serializer blueprint doesn't extend ApplicationSerializer if it exists

### ISSUE THREAD

**Issue by blimmer** [emberjs/data#4282]
We should do this similar to how the Adapter blueprint works, where it extends ApplicationSerializer if it exists, or use `DS.JsonApiSerializer`.

https://github.com/emberjs/data/blob/master/blueprints/adapter/index.js#L33

**Comment by bmac** [comment]
Should be resolved when https://github.com/emberjs/data/pull/4023 get merged.

**Comment by pangratz** [comment]
#4023 has been merged
