### ISSUE TITLE
Strange behaviour of `deleteRecord` after validation error

### ISSUE THREAD

**Issue by pablobm** [emberjs/data#4289]
I'm seeing a strange behaviour that might be a bug. `Model#deleteRecord` removes the record from the store, unless there has been an **unsuccessful** attempt to save it.

To reproduce in an app, first create a record on the store. From there, the behaviour of `deleteRecord` varies depending on whether `save` is called on the record or not, and what the result of this was. Presently:

  * No attempt to save: removes the record form the store
  * After a successful save: removes the record from the store
  * After a failed save: apparently nothing

Here's a twiddle that reproduces the behaviour: https://ember-twiddle.com/e820604c62b94a5828d6890d2e37efe2?fileTreeShown=false&numColumns=2&openFiles=templates.application.hbs%2Ccontrollers.application.js

From the Twiddle, this is the important part (the model name is `line`):

```js
import Ember from 'ember';

export default Ember.Controller.extend({
  init() {
    this.store.createRecord('line', {name: "yksi"});
    this.store.createRecord('line', {name: "kaksi"});
    this.store.createRecord('line', {name: "kolme"});
  },
  
  lines: Ember.computed(function() {
    return this.store.findAll('line');
  }),
  
  actions: {
    invalidate(line) {
      // Recklessly using private APIs in order
      // to reproduce the problem with minimum code
      this.store.recordWasInvalid(
        line._internalModel, {
          name: "is not up to scratch",
        }
      );
    },
    
    delete(line) {
      line.deleteRecord();
    },
  },
});
```

The action `delete` removes the record from the store. However, this doesn't work if we previously call `invalidate`. I would try to mimic the case of the successful save too, but can't work out the private APIs for that.

**Comment by pangratz** [comment]
Looks somewhat related #3688.

**Comment by pablobm** [comment]
I have observed #3688 in my app too. That issue can be split into two concerns: on one hand the one I describe above, and other other hand the bogus `DELETE /resource` request.

**Comment by pablobm** [comment]
I can reproduce with Ember Data 2.0.1. Doesn't happen with 1.13.15.

I wonder if the "Breaking change" introduced in Ember Data v2.0.0-beta.1 has something to do with any of this: https://github.com/emberjs/data/releases/tag/v2.0.0-beta.1 However, I don't see how that would affect records marked as invalid, but not valid ones.

**Comment by bmac** [comment]
Hi @pablobm this was an unintentional bug introduced by the change that resulted in unsaved deleted records are no longer removed from the store. Working on a fix now.
