### ISSUE TITLE
RestAdapter Ajax Global error handling

### ISSUE THREAD

**Issue by GramozKrasniqi** [emberjs/data#4291]
Created a global error handler for a ember app on the RestAdapter so i overwrote the ajax function:
`ajax: function ajax(url, type, dataObject)
...
var options = adapter.ajaxOptions(url, type, dataObject);
options.success = function (resultJson, statusText, jqXhr) ...
options.error = function (jqXhr, statusText, errorThrown)`

inside the options.error i call
 `ajaxError: function ajaxError(jqXhr) {
this._super(jqXhr);
return jqXhr;}`

but when i want to catch the errors in other parts of the application it dosent get handled e.g on Route
`return this.store.findRecord('xxx', params.xxx).then(function (xxx) {
                return xxx;
            }, function (errorResponse) {
                _this.toast.error('Error');
}`

only the error handler in the RestAdapter is being fired no where else.
I want to use it on both of them.
Thanks in advance.

**Comment by bmac** [comment]
Hello @GramozKrasniqi. I don't quite follow the issue would you mind creating a [jsbin](http://emberjs.jsbin.com/nunico/1/edit?html,js,output) or https://ember-twiddle.com/ that demonstrates the issue?

**Comment by GramozKrasniqi** [comment]
Sorry @bmac it seems that it wasnt an issue but just a mistake.
But thank you for your support.

**Comment by pangratz** [comment]
Thanks for the heads up @GramozKrasniqi.
