### ISSUE TITLE
Checking if hasMany (by link) was loaded without requesting

### ISSUE THREAD

**Issue by zion03** [emberjs/data#4296]
Probably it's a duplicate question but I can't find answer. What it's proper way to checking if hasMany (by link) was loaded without requesting?

Currently i try to use :
```
export default DS.Model.extend({
 unreadCountComputed: function(){
     if (this._internalModel._relationships.initializedRelationships.replies.hasData)...
 }.property('replies.@each')
});
```
So solution looks like not good.
**Question**: is this code a normal solution and do you planning integration this login to API

Thanks!

**Comment by sly7-7** [comment]
For now it should be possible use the `ds-references` feature flag. See  https://github.com/emberjs/rfcs/blob/ce19612e447e0ec393f842bfb31add96edaba9a1/text/0057-ember-data-reference-unification.md for more details. You should be able to do `record.hasMany('replies').value === null` to see if it's loaded or not.

**Comment by pangratz** [comment]
Yes, as @sly7-7 said, references is the way to go here.

**Comment by zion03** [comment]
How to deal with this in model directly I trying execute this in model (Ember Data        : 2.4.0)
```
export default DS.Model.extend({
 replies: DS.hasMany('c-reply'),
 unreadCountComputed: function(){
     if (this.hasMany('replies').value)...
 }.property('replies.@each')
});

```

Receive this error: `Uncaught Error: Assertion Failed: The `hasMany` method is not available on DS.Model, a DS.Snapshot was probably expected. Are you passing a DS.Model instead of a DS.Snapshot to your serializer?`

**Comment by sly7-7** [comment]
You have to enable the `de-references` feature flag in your config/environnement.js file (assuming you're using ember-cli. see https://guides.emberjs.com/v2.4.0/configuring-ember/feature-flags/#toc_enabling-at-runtime
