### ISSUE TITLE
Validation errors for hasMany records

### ISSUE THREAD

**Issue by youroff** [emberjs/data#4298]
I tried to ask it on so and ember discuss, but no answers.

What would be the way to process errors from the back-end related to hasMany relationships? I'm trying to create a record with associated records in one request. In case if some of nested records have validation errors, I'd like to access appropriate errors on that record. I'm using json-api adaptor, so what should be the format of errors from the backend? I'm trying something like this, with no luck though:

```
{"errors":[
  {
    "detail": "can't be blank",
    "source": {
      "pointer":"data/relationships/steps/0/data/attributes/est_threshold"
    }
  }
]}
```

According to the source, `extractErrors` still returns `DS.InvalidError` for one record. Is there natural way to assign these errors to nested objects?

**Comment by kernel-io** [comment]
I have written support for belongsTo errors, but I am stuck on the same issue you have (what is the expected format on the JSON pointer), once I get that figured out, I will write hasMany support.

https://github.com/emberjs/data/issues/4273#issuecomment-205066538

is this:
   "pointer":"data/relationships/steps/:id/data/attributes/est_threshold"
the correct format per jsonapi spec?

**Comment by youroff** [comment]
I'm not sure if json-api spec even covers that. But it says that pointer points at json path in payload, so in case of embedded records mixin it would look like the above. After some experiments I ended up with mixin like this:
```
`import Ember from 'ember'`

RelatedErrors = Ember.Mixin.create

  save: ->
    @_super().catch (resp) =>
      resp.errors.forEach (err) =>
        pattern = /^data\/relationships\/(\w+)\/(\d+)\/data\/attributes\/(\w+)$/
        if [_, rel, idx, attr] = err.source.pointer.match pattern
          @get(rel).objectAt(idx).get('errors').add(attr, err.detail)
    
`export default RelatedErrors`
```

It seems to work, except in doesn't drop invalid status on nested models if they were invalidated.

**Comment by runspired** [comment]
Errors are now handled opaquely, this should just work. Let's revisit if removing extractErrors does not result in the errors appearing on Error.errors / is not retrievable from the cache via https://api.emberjs.com/ember-data/5.2/classes/%3CInterface%3E%20Cache/methods/getErrors?anchor=getErrors
