### ISSUE TITLE
StringTransform converts boolean false to string 'false'

### ISSUE THREAD

**Issue by josefguenther** [emberjs/data#4305]
The String Transform deserializer (and serializer for that matter) allows `false` to pass through; instead of converting it to a blank '' like it does with `null`, it converts it to 'false' (string).

Consider this: server returns a phone number as a string. If the phone is empty, it returns `false`.
```
export default DS.Model.extend({
  phone: DS.attr('string'),
});
```

This will preserve the boolean `false` and convert it to a string 'false' instead of converting to an empty string.

The more I think about it, there could be an argument either way. Some people might desire this behavior, even though it is contrary to standard type casting. At least there should be an option to disable this 'feature'.

**Comment by pangratz** [comment]
I am inclined to think that this is a special case in your API of handling a `string` attribute. I am also not sure if this should be possible to be configured as an option, as this could lead to more options in the future - things like `{ treatFalseAsEmpty: true }` or `{ treatFalseAsNull: true }` - which would be needed to support all possible cases an API might have.

If there is a special case your API offers, you would need to write your own transform; see [the section in the guides](https://guides.emberjs.com/v2.4.0/models/customizing-serializers/#toc_creating-custom-transformations) on how to do that. You can extend from `DS.StringTransform` to re-use the existing logic:

```js
// app/transforms/my-string.js
import DS from "ember-data";

export default DS.StringTransform.extend({
  deserialize(value) {
    if (value === false) {
      return "";
    }

    return this._super(value);
  },

  serialize(value) {
    if (value === "") {
      return false;
    }

    return this._super(value);
  }
});
```

This transform is now available via `DS.attr("my-string")`.

If this should be the case for all `string` attributes in your app, you can place the custom string transform at `/app/transforms/string.js`, which would overwrite the default `string` transform of `ember-data` in your app, and you wouldn't need to change the attribute definitions and could continue to use `DS.attr("string")` in your model definitions.

---

I am going to close this issue as I really think that this is a special case of string handling which should be handled by a custom transformation. Feel free to re-open if you disagree so this can be discussed further.
