### ISSUE TITLE
babel-plugin-feature-flags name collision in 2.5.1 with fastboot

### ISSUE THREAD

**Issue by davidpett** [emberjs/data#4322]
When updating to version 2.5.1 and running `ember s` I received the following error:
```
File: modules/ember-data/adapter.js
The Broccoli Plugin: [Babel] failed with:
ReferenceError: The plugin "babel-plugin-feature-flags" collides with another of the same name
```
After some digging, @pangratz found that because I am using `ember-cli-fastboot` there is a collision in the plugins. You can reproduce the issue with these steps:
```
ember new abcd
cd abcd
ember build # works as expected

ember install ember-cli-fastboot
ember build # throws ReferenceError: The plugin "babel-plugin-feature-flags" collides with another of the same name
```

**Comment by fivetanley** [comment]
This should be fixed once we change the approach in ember-cli-fastboot https://github.com/ember-fastboot/ember-cli-fastboot/pull/145

**Comment by rwjblue** [comment]
https://github.com/emberjs/data/pull/4328 seems like a nice work around for now...

**Comment by davidpett** [comment]
To be able to use this fix, do i need to run on master? or will release include it?

**Comment by rwjblue** [comment]
Release will include it, but I don't think it's been cherry picked yet.
