### ISSUE TITLE
modelNameFromPayloadKey doesn't work with sideloaded models

### ISSUE THREAD

**Issue by amk221** [emberjs/data#4325]
Please see this [simple example](http://jsfiddle.net/amk221/vjtj757r/)

There are 2 basic models. `Things`, and `Tags`

A payload of `Things` returns the associated `Tags` (and this works fine)

I'm trying to make this work with an alternative payload:

```diff
{
- things: [{
+ somethings: [{
    id: 100,
    name: 'Thing A',
    tags: [1000]
  }],
  tags: [{
    id: 1000,
    name: 'Tag A'
  }]
}
```

By returning the new value "somethings" using `modelNameFromPayloadKey` the sideloaded (secondary) data somehow makes its way into the _primary_ models.

**Comment by pangratz** [comment]
`modelNameFromPayloadKey` is invoked with the `payloadKey` and is called for _every_ key in the payload to resolve the model name. You would need something like this:

```js
modelNameFromPayloadKey: function(payloadKey) {
  if (payloadKey === "somethings") {
    return "thing";
  }

  return this._super(payloadKey);
}
```

**Comment by amk221** [comment]
Doh, sorry! Thanks for the quick response.

**Comment by pangratz** [comment]
No problem! I just checked and this should be documented in the API doc. Do you agree that the documentation is enough, or would it helped if there would be more information about that? http://emberjs.com/api/data/classes/DS.RESTSerializer.html#method_modelNameFromPayloadKey

**Comment by amk221** [comment]
The docs are thorough enough :)
