### ISSUE TITLE
JSONAPI Sparse Fieldset Support

### ISSUE THREAD

**Issue by toobulkeh** [emberjs/data#4332]
We have a few use cases where sparse fieldsets would be the ideal situation. Mainly where separating the data into a separate object is too difficult / too much overhead, and where loading all of the attributes in the index collection would be too cumbersome on the server.

To support that, we've used [this addon](https://github.com/BookingSync/ember-data-partial-model).

I would like to propose that it be adopted into ember-data core. I also don't know enough about either's innerworkings to realistically investigate it -- as it probably doesn't actually use the JSONAPI sparse fieldset parameters, but just solves our problem / the difference between the collection/singular resource endpoints.

Here's a [previous discussion](https://github.com/emberjs/data/issues/51#issuecomment-9572757) from a few years back that lead me to this request.

For posterity, [here's a SO discussion](http://stackoverflow.com/questions/36613843/sparse-fieldsets-or-reload-from-component-for-ember-data-2-0) with details to our solution.

**Comment by bmac** [comment]
Hey @toobulkeh. The https://github.com/BookingSync/ember-data-partial-model addon is great. 

Unfortunately, I don't think Ember Data will be able to support JSONAPI Sparse Fieldsets any time soon. One of the fundamental assumptions of Ember Data is that every attribute is loaded on the record when the record is in the store. This allows Ember Data to be able to confidently give you a record form the cache when you request a type / id combination Ember Data has seen before. Sparse fieldsets break this assumption so for now I'd recommend you stick with the ember-data-partial-model addon.

**Comment by pangratz** [comment]
FYI, there has been an RFC for partial record loading at emberjs/rfcs#31, but it has been closed. Not sure if there were any follow ups...

**Comment by bmac** [comment]
I'm going to close this. Ember Data has no plans to support partial records at the momennt. For now the best option is to use this addon: https://github.com/BookingSync/ember-data-partial-model
