### ISSUE TITLE
No way to retrieve a single record by id and pass queryParams

### ISSUE THREAD

**Issue by olivierlesnicki** [emberjs/data#4335]
My API expect the following request
```
/appointments/:id?include=appointment-slot
```

The `include` query parameter allows the client to specify models to side-load as part of the response.

However this is currently not possible, `findRecord()` doesn't offer query parameters and `queryRecord()` doesn't offer a way to specify id.

**Comment by pangratz** [comment]
This has been implemented by the `ds-finder-include` feature, which has been enabled by default in `2.5`. See [this ember-twiddle](https://ember-twiddle.com/5977b76ab51d27ef76da8f306790a9a3?fileTreeShown=false&numColumns=2&openFiles=routes.application.js%2Ctemplates.application.hbs) as an example.

Can you clarify that this solves the use case you're having?

**Comment by olivierlesnicki** [comment]
Okay, that's exactly what I was searching for - to bad we're still on 2.4.3 :(

**Comment by pangratz** [comment]
You can overwrite `adapter#urlForFindRecord`, if you are stuck on `2.4`. See [this ember-twiddle](https://ember-twiddle.com/e45dbbca12cc91532a5f21e280f321eb?fileTreeShown=false&numColumns=2&openFiles=routes.application.js%2Cadapters.application.js) as a possible solution:

```js
// app/adapters/appointment.js
import Ember from "ember";
import Adapter from "ember-data/adapters/json-api";

export default Adapter.extend({
  urlForFindRecord(id, type, snapshot) {
    let url = this._super(...arguments);
    
    if (snapshot.adapterOptions.include) {
      let queryParams = Ember.$.param(snapshot.adapterOptions);
      return `${url}?${queryParams}`;
    }
    
    return url;
  }
});
```

```js
// GET /appointsments/1?include=appointment-list
this.store.findRecord('appointments', 1, {
  adapterOptions: {
    include: "appointment-list"
  }
});
```
