### ISSUE TITLE
Firing { reload: true } when a model is passed into the route

### ISSUE THREAD

**Issue by davidlormor** [emberjs/data#4336]
I'm not exactly sure if this is an ember core or data issue, but I ended up here by way of #3704. I ran into an issue where I thought that my { reload: true } option wasn't firing from the model hook upon entering a route.  In actuality I was passing the model into the link-to helper, causing the hook not to fire. I realize that this is the desired behavior of the link-to helper (skip the model hook), but it seems like it can lead to a bit of confusion. Just curious about thoughts around possible ways to clarify the API/functionality to help others avoid the rabbit hole I ended up in.

**Comment by pangratz** [comment]
Hey @davidlormor, I can definitely see how this is a surprising behavior and this should be better documented, as the [current documentation for the `{{link-to` helper](http://emberjs.com/api/classes/Ember.Templates.helpers.html#toc_supplying-a-model) doesn't make it very clear that the `model` hook is not invoked, when a model is specified. There is a [section in the gudies](https://guides.emberjs.com/v2.5.0/routing/specifying-a-routes-model/#toc_dynamic-models) but I can see how this can be easily overlooked.

As this is actually an issue which is not `ember-data` specific, I am going to close this one. Can you instead open an issue on the [`ember.js`](https://github.com/emberjs/ember.js) and/or [`guides`](https://github.com/emberjs/guides) repository, so this gets addressed so people don't stumble over this again? Thanks!

**Comment by davidlormor** [comment]
Thanks for your help, @pangratz!
