### ISSUE TITLE
isUpdating is broken since 2.4.3

### ISSUE THREAD

**Issue by kbbpartners** [emberjs/data#4339]
Prior to version 2.5.0, we used `isUpdating` to determine the loading state of an ArrayProxy resulting from `findAll`. The reason for using `isUpdating` is that other states, such as `isFulfilled`, were not triggered during background loads.

To be clear, since version 2.5.0, `isUpdating` returns false when it used to return true. It used to return true when: (1) the `findAll` promise was resolving, where `reload: true` was set, and (2) the records were being (re)loaded in the background for ordinary `findAll` operations.

Did we miss an API change, or perhaps is there a better way of tracking the loading state of an ArrayProxy resulting from a find operation?

**Comment by pangratz** [comment]
Looks like this regression has been introduced [in #4316](https://github.com/emberjs/data/pull/4316/files#diff-fd4c34d9a34dfde73cd3413128a3c973L1009). I am working on a fix.

**Comment by pangratz** [comment]
@kbbpartners this regression should be fixed once #4386 is merged and a new version `2.5.3` is released. Many thanks for reporting this and sorry for the inconvenience.

**Comment by pangratz** [comment]
@kbbpartners FYI, `ember-data` `v2.5.3` has been released...

**Comment by kbbpartners** [comment]
Looks good. Our loading indicators are back! Thank you.
