### ISSUE TITLE
Document DS.Store#findAll options

### ISSUE THREAD

**Issue by awochna** [emberjs/data#4341]
The documentation for the `findAll` method includes an optional `options` parameter, but doesn't specify what options can be passed for what effect.

I kept trying to figure out why my model wasn't reloading when transitioning to the view route from the index and it took a fair amount of searching to find that there is a `{ reload: true }` option that can be passed.

After digging through the source where that method is declared, I still had a hard time trying to find out what *other* options can be used there. I still don't know. StackOverflow didn't have any questions that I could find about this, so I figured filing a documentation issue was the best way to help newer people (and myself).

**Comment by pangratz** [comment]
Hey @awochna, sorry you stumbled over this. I hope this is better once #4338 is merged...

**Comment by awochna** [comment]
@pangratz Thanks! I was just looking at that one. Do you know if there are any other options that the method can receive? If not, your pull request solves this problem perfectly.

**Comment by pangratz** [comment]
@awochna there is another option, namely `adapterOptions`, which will be passed, you guessed it, to the adapter. Unfortunately they are also not yet documented, but there is #4303 which tracks that. Also see #4329 for a little explanation on what it is for.

Are you running into a specific issue? What option would you expect to be passable to `store.findAll`?

**Comment by awochna** [comment]
The only specific issue I was running into was reloading the model when changing routes. It was hard enough to find that I thought it would be a good idea to know what else can be passed and I couldn't find anything. No specific issue otherwise.

**Comment by pangratz** [comment]
I am going to close this as #4338 has been merged which should improve the documentation and list all the possible options for `store.findAll`. Please feel free to reopen if you think this is still not yet documented sufficiently. Thanks!
