### ISSUE TITLE
_changedKey function : possibility to deep compare object / array

### ISSUE THREAD

**Issue by olivierchatry** [emberjs/data#4351]
Hello,

I'm not sure if it is relevant or not, but pushing object values will always being notified as "changed" by _changedKeys because the function only compare the reference value. It would be nice to have a hook ( maybe in the "transforms" object ?  that would allow to provide a isEqual function. 

What do you think ?

**Comment by olivierchatry** [comment]
Sorry, just traced the code and found out that you can provide a "isEqual" function to the object you compare and it will use it. I would still prefer to have that in "transforms" object as it would make more sense, but I'm sure I can work that around.

**Comment by olivierchatry** [comment]
Actually, scrap that, there is a problem after ember get the changed key, the values are anyway always assigned: 
system/model/internal-model.js

```.js
    setupData: function setupData(data) {
      var changedKeys = this._changedKeys(data.attributes);
      assign(this._data, data.attributes);
      this.pushedData();
      if (this.record) {
        this.record._notifyProperties(changedKeys);
      }
      this.didInitalizeData();
    },
```

I think ember should just assign the values that have changed.

**Comment by wecc** [comment]
Would you be able to reproduce the issue or summarize what the actual vs. expected result is?

**Comment by stefanpenner** [comment]
This seems to have gone stale, if @wecc question is answered we can likely reopen.

Note, there are also plans to make the difffing/change-tracking pluggable in the future
