### ISSUE TITLE
ds-reference hasMany().value() intended behavior of null when I can use .ids()?

### ISSUE THREAD

**Issue by adam-knights** [emberjs/data#4355]
Following up from a question on slack I want to query the current behavior as its not what was intended - or the use case in the 2.4 beta blog post could be better.

I have a product that has many priceListItems.

If a product has no price list items then calling

```
let productModel = this.get('store').peekRecord('product', product.get('id'));
console.log(productModel.hasMany('priceListItems').value())
```
Returns a non null result for .value(), and then ```productModel.hasMany('priceListItems').ids()``` returns []

That all looks ok.

If a product does have price list items - and the server sent down their ids only then in that case .value() returns null and .ids() returns an array of the ids.

Is it intended that value() returns null here? The 2.4 blog post had:

```
// check if there are comments, without triggering a request
if (post.hasMany('comments').value() !== null) {
  var ids = post.hasMany('comments').ids();

  var meta = post.hasMany('comments').meta();
  console.log(`${ids.length} comments out of ${meta.total}`);
} else {
  post.hasMany('comments').load();
}
```

This to me suggests value() should not be null here - because I can get to the ids successfully without triggering a request?

If null is correct here then I would redo the example because the use case is to get to .ids() without having to do the load.

**Comment by adam-knights** [comment]
cc @pangratz @bmac @locks incase answer here helps guides etc

**Comment by adam-knights** [comment]
Pangratz has confirmed null is correct - I'll leave open so you can use to make the example in blog post/guides better?

**Comment by pangratz** [comment]
Closing in favor of the updated blog posts in emberjs/website#2565. Thank you very much @adam-knights for reporting this!

**Comment by adam-knights** [comment]
And thank you for the functionality - its working a charm and will be live next week.
