### ISSUE TITLE
Add preconfigured ember twiddle to 'reporting a bug' section

### ISSUE THREAD

**Issue by adam-knights** [emberjs/data#4362]
The reporting a bug section has js bins etc but Ember Twiddle can be alot easier to use. @pangratz had a basic one https://ember-twiddle.com/0e1a24aabb8fa7c1fdd8/copy?fileTreeShown=false&numColumns=2&openFiles=routes.application.js%2Ctemplates.application.hbs
that I found easy to play with and add to.

So something similarly maintained would be good, and then added to this section.

I also noticed Ember CLI now have a template that appears when you try to create an issue - linking to the preconfigured bins in one of those may also save alot of time/waiting for a repo

**Comment by wecc** [comment]
This ember-twiddle link looks good to me! Would you like to open a PR adding it to `CONTRIBUTING.md`?

**Comment by wecc** [comment]
I'm closing this, adding Ember Twiddle is already tracked in #4238. I copied the link from this issue to that issue.
