### ISSUE TITLE
findAll is not a function

### ISSUE THREAD

**Issue by VincentMolinie** [emberjs/data#4364]
I've just pass to ember 2.5.0 and ember-data doesn't work anymore.
The store injected in my route only contains the function find and I need to do a this.get('store') to have it, if I don't I get this:
![2016-05-03](https://cloud.githubusercontent.com/assets/3263749/14989612/97a75eaa-1150-11e6-82f6-c8993aaf47ae.png)

**Comment by pangratz** [comment]
Are you manually injecting the store into your route via `Ember.inject.service()`? This shouldn't be necessary.

Can you modify [this ember-twiddle](https://ember-twiddle.com/1ac3c4a29b99d9eed268800d4290c5c3?fileTreeShown=false&numColumns=3&openFiles=routes.application.js%2Ctemplates.application.hbs%2Ctwiddle.json) and make changes so it demonstrates the issue you're having?

**Comment by VincentMolinie** [comment]
Found my issue I was missing this line in the app.js:

**Comment by pangratz** [comment]
Alright, glad you figured it out.
