### ISSUE TITLE
Configure Ember data to build in production mode on a custom environment

### ISSUE THREAD

**Issue by deepan83** [emberjs/data#4369]
We are currently using Ember data 2.5.x and use a custom 'staging' environment in our ember CLI configuration to build production like apps for functional testing (as we have different API keys for production). However, we are currently  encountering an issue where these staging mode apps fail with the below exception,

TypeError: this.warnMessageForUndefinedType is not a function 

This is due to the fact that the Ember data addon only strips asserts, warns etc when the environment is 'production' and hence in staging mode, these methods don't exist (due to Ember noops in production builds) but get called. Any suggestions on this?

**Comment by pangratz** [comment]
Are you using `ember-cli-deploy`? If so, http://blog.firstiwaslike.com/staging-environments-with-ember-cli-deploy/ should help you get started with different deploy targets.

Otherwise I think you need to configure your API keys based on a different ENV variable using `process.env.MY_CUSTOM_ENV` within `config/environment.js` and use the `production` environment for ember-cli.

**Comment by deepan83** [comment]
We don't use ember-cli-deploy. Previously, when it was a bower dependency, you could use the below in vendorFiles,

 'ember-data': {
    staging: 'bower_components/ember-data/ember-data.prod.js'
   }

This isn't possible anymore as it now an addon.

**Comment by pangratz** [comment]
So you want the `production` environment for `ember-data`, since you want the assertions/warnings stripped.

For custom configuration of the API keys I would do something like this:

``` js
// config/environment.js
module.exports = function(environment) {
  var config = {
    API_KEY: "123"
  };

  if (process.env.DEPLOY_ENV === 'staging1') {
    config['API_KEY'] = "staging-1-key";
  }

  if (process.env.DEPLOY_ENV === 'staging2') {
    config['API_KEY'] = "staging-2-key";
  }

  return config;
};
```

and then invoke your build task via `DEPLOY_ENV=staging2 ember build --environment=production`.

Does this help?

**Comment by deepan83** [comment]
Yeah thanks mate. Closing this issue

**Comment by pangratz** [comment]
Nice, glad I could help.
