### ISSUE TITLE
Document polymorphic relationships

### ISSUE THREAD

**Issue by pangratz** [emberjs/data#4375]
😨  looks like this is currently not covered by the API docs for `belongsTo` and `hasMany`. Also, there is currently no entry in the guides for that 😢

**Comment by wecc** [comment]
@pangratz is this something you intend to tackle or should we unassign?

**Comment by pangratz** [comment]
😔

**Comment by rhysdavies1994** [comment]
This is confusing, I've been trying to learn about polymorphic relationships in ember-data, and just finding random tutorials using them on the internet. Went to ember docs to actually understand what I can do with them, but there is nothing. Can people with knowledge on the subject please help to create official documentation.

**Comment by runspired** [comment]
these are now covered by the schema docs, though this behavior should be given its own "how to" guides section
