### ISSUE TITLE
Ember findRecord always does api call without send {reload: true} param.

### ISSUE THREAD

**Issue by carlesnunez** [emberjs/data#4381]
Hi everyone.

According to ember DS.Store docs findRecord will do the follow:
````
If you would like to force the record to reload, instead of loading it from the cache when present
you can set reload: true in the options object for findRecord.
````

Using that method on my code I can see that findRecord **ALWAYS** does an API call. Looking at the ember-data code I saw [that strange line](https://github.com/emberjs/data/blob/75bec5ec1b1b842ee87eb4cb2fb0b6dbe1b93d85/packages/ember-data/lib/system/store.js#L624):

````javascript
findRecord: function(modelName, id, options) {
    Ember.assert('Passing classes to store methods has been removed. Please pass a dasherized string instead of '+ Ember.inspect(modelName), typeof modelName === 'string');
    var internalModel = this._internalModelForId(modelName, id);
    options = options || {};

    if (!this.hasRecordForId(modelName, id)) {//<------- HERE
      return this._findByInternalModel(internalModel, options);
    }

    var fetchedInternalModel = this._findRecord(internalModel, options);

    return promiseRecord(fetchedInternalModel, "DS: Store#findRecord " + internalModel.typeKey + " with id: " + get(internalModel, 'id'));
  },
````

I was wondering about if we need to reload by default our model doing an API call... why I am retrieving from InternalModel doing a return of the data only if **I don't have the data**?

I don't know if I have a concept problem around that function or is really a bug, can you help me?

**Comment by pangratz** [comment]
So `store.findRecord` will always make an API call if the record is not yet available locally in the cache. The line you marked in the code is responsible for that, where `this._findByInternalModel` will make the API call, which might not be obvious from the name of the function.

If the record is already in the store, then `store.findRecord` might also do an API call if a background reload should be made. This is indicated either by passing `{ backgroundReload: true }` to `store.findRecord()` or if the adapters' `shouldBackgroundReloadReload()` returns true (which is the default).

Does this help?

**Comment by carlesnunez** [comment]
Not really @pangratz.

I add the flag backgroundReload but nothing different happens.

I can saw a strange behavior on the api call.
I have the following code
```javascript
this.store.findRecord('room', params.id, {backgroundReload: false).then(()=>{
     console.log('Is loaded?->', this.store.recordIsLoaded('room', params.id));
   });
````

First case:
I acces directly to the URL typing on my bar and I got the following on console:
````terminal
jquery.js:9203 XHR finished loading: GET "http://myapicallurl.dev/api/rooms/4d298701-6d17-4b5b-b2d3-b0f0ecf461a7".
Is loaded?-> true
````

Second case:

I acces to my URL throught transitions that already have done an api call to get rooms. It means that I already have a room stored in my store. But... I get the follow on my console:
````terminal
Is loaded?-> true
jquery.js:9203 XHR finished loading: GET "http://myapicallurl.dev/api/rooms/4d298701-6d17-4b5b-b2d3-b0f0ecf461a7".
````

A you can see something is calling API after resolve the promise... that's so strange and I don't know what im doing wrong...

**Comment by pangratz** [comment]
The `backgroundReload` isn't considered yet; the flag is added in #4356. If you update your adapters' `shouldBackgroundReloadRecord()` and return false, no API call should be made in the second request...

**Comment by carlesnunez** [comment]
Hi @pangratz 

Thanks for the fast response.

As you told me, overriding ````shouldBackgroundReloadRecord()```` ember doesn't make an api call if already have the record loaded In the store.

But I have a last question:

**According to that:**
````
If you would like to force the record to reload, instead of loading it from the cache when present
you can set reload: true in the options object for findRecord.
````

Ember should NOT do an api call by default, instead I should use the 'reload' flag to force API call but by default ember is doing completely the oposite.

If it is a bug... the fix for future users is to override the ````shouldReloadRecord()```` on your adapter and return a false on the function. With that workaround you will get the cached data for each ````findRecord()```` that you use from your adapter.

With that, on 
````javascript
findRecord('model', <id>, {reload: true})
````

you will force ember-data to do an API call ALWAYS.


Am I in the right way?

**Comment by pangratz** [comment]
The docs for `findRecord` have been updated in #4338 so I hope this confusion has been addressed in the meantime.

Essentially `store.findRecord()` _always_ triggers an API call. The reload / background reload behavior specified via the passed options and the hooks on the adapter allow you to configure _when_ the promise returned by `findRecord` should be resolved: if you are reloading a record, then the promise resolves once the response from the API comes back. If a background reload should be done, then the promise resolves immediately with the cached record from the store, and updates the data for the record in the background.

If you want to get the cached version from the store without triggering an API call, use `store.peekRecord()`.

Does that clear things up?

**Comment by carlesnunez** [comment]
Totally clear now! Thank you!

**Comment by pangratz** [comment]
Great to hear!
