### ISSUE TITLE
Associated record deletion

### ISSUE THREAD

**Issue by Asherlc** [emberjs/data#4382]
In Rails, and I presume other frameworks, it's not uncommon for records to automatically destroy some or all of their associated records when they themselves are destroyed. So, a deletion of one nominal record may delete many other records as well.

Currently, it appears Ember Data has no way to receive this information in response to a DELETE, so orphaned records may be left on the client side that have been destroyed on the server side.

**Comment by pangratz** [comment]
Related to #1945

**Comment by wecc** [comment]
Closing as a dupe of #1945
