### ISSUE TITLE
rolledBack event not firing on model

### ISSUE THREAD

**Issue by rk1** [emberjs/data#4395]
This twiddle illustrates the issue (testable via the "test rollback" button):
https://ember-twiddle.com/6995f426ba012f6d37724de7ecd526fb?openFiles=models.animal.js%2C

The `rolledBack` event is not fired (even if it's an unsaved model). In the console there's a log for the `ready` event.

**Comment by fivetanley** [comment]
Hi @rk1, thanks for opening an issue. I'm wondering where this particular event has been documented, as it's new to me. Do you have a link to perhaps the API documentation?

**Comment by rk1** [comment]
Hey, sure, here it is - http://emberjs.com/api/data/classes/DS.Model.html#event_rolledBack

**Comment by stefanpenner** [comment]
there is def code for this event to be dispatched:

https://github.com/emberjs/data/blob/7bfadcdb48291b6d4c8af75c412757ee44d453f3/addon/-private/system/model/internal-model.js#L733-L762

**Comment by stefanpenner** [comment]
Will gladly reopen, if it is demonstrated on latest ember-data that this does not work.

**Comment by stefanpenner** [comment]
Actually. We emit the state machine transition, but we do not trigger the event on the model itself.

**Comment by leondmello** [comment]
@stefanpenner Is #5010  a similar occurrence?

**Comment by bmac** [comment]
Fixed as part of https://github.com/emberjs/data/pull/4468.
