### ISSUE TITLE
cp not updating when using hasMany(..).value() instead of get(..)

### ISSUE THREAD

**Issue by dylanmensaert** [emberjs/data#4402]
I created a twiddle: https://ember-twiddle.com/52edd8462fa6e3cf1a147a2a047c9207?openFiles=models.post.js%2C

_Issue:_ cp `characters` on `post` does not get updated when property `content` changes on `comment`.
_'Fix':_ the change does happen when using `this.get('comments')` instead of `this.hasMany('comments').value()`.

`get` notifies observers that it should look for changes on the property because it is being used, while `hasMany` does not seem to have this functionality..

Is this on purpose or a bug?

**Comment by fivetanley** [comment]
I think this is on purpose. `hasMany` returns what's called a `reference`. It is intentionally a low-level public API for dealing with records. As such, we are designing hooks for updates, but references should definitely not be the first tool we want end users to reach for.

I think `post.get('comments')` should serve your use case better here, but I'm wondering if there was a use case not in the gist you were trying to use `hasMany` for.

**Comment by dylanmensaert** [comment]
My understanding is that `post.get('comments')` performs a server call while I do not want that to happen. 
I only want to get cached `comment` records for the given `post` parent.

`peek` functionality does not support this, so I though that `hasMany` was the way to go.

What is the difference between `reference` and `full objects` in this context?

**Comment by dylanmensaert** [comment]
I believe this bug is a more general one.
For example, I wrote another twiddle: https://ember-twiddle.com/a0e965cc94f4d2846add09e57dfa17d9?openFiles=templates.application.hbs%2C

Here I am using a global array instead of `this.hasMany`. If a property is never `set` or `get` via according methods, no related observable is being notified.

**If** I am correct then the question is if this is a correct implementation since a use case might for referenced properties.

**Comment by dylanmensaert** [comment]
I fixed this issue by modifying the private api.

The solution is available via following `ember-addon`: https://github.com/dylanmensaert/ember-data-peek-relationship
