### ISSUE TITLE
Expose more access to jqXHR object in handling adapter responses.

### ISSUE THREAD

**Issue by eshtadc** [emberjs/data#4404]
I would like to add some custom functionality when an AJAX request returns and need access to the jqXHR object.  The use case is to validate a server signature from an authentication proxy server that requires knowing the responseText from the jqXHR request.  I can't get to this from handleResponse.  I tried looking at using ajaxOptions to push a success callback but I see that the rest adapter would overwrite this with it's own success callback.
https://github.com/emberjs/data/blob/fec260a38c3f7227ffe17a3af09973ce2718acca/addon/adapters/rest.js#L998

jQuery 1.5 and up allow an array of success callbacks which would give me one way of accomplishing this.

Another way would just be to allow handleResponse to get access to the underlying jqXHR rather than just the little bit of requestData.  It seems that ember-data is trying to insulate a bit from the type of AJAX call used, so I can see how this might be a bit distasteful.... 

I'm happy to work on a PR - but feel like there are a few directions this could go and want to work through the approaches before coding it up.

Of course - if there is some super obvious way of getting back the raw response info from the request that I'm missing - that would be awesome too :)

**Comment by fivetanley** [comment]
I am disappointed that end users have lost access to this. I think it's definitely something we should restore. Maybe we should stick it on `requestData.jqXHR` ?

**Comment by lkhaas** [comment]
Yeah - ideally it would be something I could access within handleResponse like that - so that I could validate and then return an error when the server signature is invalid.  Feels the most "ember-y".  I can take a stab at the code here and have something up shortly.

**Comment by lkhaas** [comment]
OK - so this is my first ever ember-data PR.  I welcome any feedback on what I did right/wrong, etc.  Thanks!

**Comment by stefanpenner** [comment]
closing in-favor of and RFC
