### ISSUE TITLE
How would you be able to use models with same attribute names and the router

### ISSUE THREAD

**Issue by devotox** [emberjs/data#4410]
```
this.route('languages',  { path: 'languages' }, function(){
	this.route('topics',   { path: ':slug/topics' }, function() {
	  this.route('topic',  { path: ':slug/topic'}, function() {
		this.route('phrase', { path: ':phrase_id/phrase'});
		this.route('item', { path: ':item_id/item'});
	  });
	});
  });
```

the :slug dynamic parameter always uses the first slug rather than the one from the next model

**Comment by bmac** [comment]
@devotox one work around you can try is make an computed property on you model that is an alias to the original attribute. Then you can reference the computed property in the router map.

```js
export default DS.Model.extend({
  slug: DS.attr(),
  topicSlug: Ember.computed.alias('slug')
});
```
```js
this.route('languages',  { path: 'languages' }, function(){
    this.route('topics',   { path: ':slug/topics' }, function() {
      this.route('topic',  { path: ':topicSlug/topic'}, function() {
        this.route('phrase', { path: ':phrase_id/phrase'});
        this.route('item', { path: ':item_id/item'});
      });
    });
  });
```

**Comment by devotox** [comment]
oooooo thank you this looks to be a bit easier actually. what i did was use a serializer

```
import DS from 'ember-data';

export default DS.JSONAPISerializer.extend({
	attrs: {
		"topic_slug": "slug"
	}
});
```

Which way would you say is more "correct" or better yet more the "emberesque" way

**Comment by pangratz** [comment]
I would say the approach suggested by @bmac is more elegant, as it doesn't involve the serializer, which IMHO shouldn't care about stuff needed within the router.
