### ISSUE TITLE
`ds-finder-include` parameter doesn't respect serializer `keyForRelationship`

### ISSUE THREAD

**Issue by chnn** [emberjs/data#4412]
Let the application serializer have a `keyForRelationship` method which serializes keys using [snake_case](https://en.wikipedia.org/wiki/Snake_case). I would expect
```
store.findRecord('article', 1, { include: 'commentProfiles' })
```
to issue the request
```
GET /articles/1?include=comment_profiles
```
but instead it issues
```
GET /articles/1/?include=commentProfiles
```
Is this the desired behavior?

While the `ds-finder-include` parameter isn't JSON API specific, the spec still may provide some guidance. [It says](http://jsonapi.org/format/#fetching-includes):

> The value of the include parameter MUST be a comma-separated (U+002C COMMA, “,”) list of relationship paths. A relationship path is a dot-separated (U+002E FULL-STOP, “.”) list of relationship names.

It seems like a “relationship name” should use the server formatting convention (e.g. snake_case in my example).

**Comment by bmac** [comment]
Hi @chnn. 

Currently Ember Data doesn't do anything special to transform the include keys. While, I think the consistency of transforming relationship names in the `include` key would be nice, I think it is unlikely that behavior will be added to Ember Data. The adapter, which is responsible for building the url doesn't know anything about the serializer so it doesn't know about `keyForRelationship`. I'm not sure the cost of increasing the complexity in the adapter to know about the serializer and handle the other edge cases around transforming dot-separated relationship names would be worth the benefits. 

The value of `include` is opaque to Ember Data so you will need to provide a value that your server already understands.

**Comment by chnn** [comment]
Understood, thanks for the insight!
