### ISSUE TITLE
hasMany doesnt accept DS.ManyArray

### ISSUE THREAD

**Issue by dmagunov** [emberjs/data#4415]
Why hasMany field doesn't accept DS.ManyArray? 

This code doesn't work on latest Ember Data release:
```
modelOne.get('child_ids').then((childrens)=>{
    modelTwo.set('child_ids',childrens);
});
```

**Comment by bmac** [comment]
@dmagunov does it work if you do:

```js
modelOne.get('child_ids').then((childrens)=>{
    modelTwo.set('child_ids', childrens.toArray());
});
```
?

**Comment by dmagunov** [comment]
The issue is that it is not consistent way. The right way for my opinion is
to accept data retrieved by the store

**Comment by pangratz** [comment]
I am closing this issue as this seems to work. See [this ember-twiddle](https://ember-twiddle.com/0d5b341b1a543d191d245a158ee2d8bc?fileTreeShown=false&numColumns=2&openFiles=routes.application.js%2Ctemplates.application.hbs) for a working example.

Feel free to reopen if you think this is still a bug, preferable with an ember-twiddle demonstrating the issue.

Thanks!
