### ISSUE TITLE
Running tests shows Warnings and Deprecation's

### ISSUE THREAD

**Issue by frunjik** [emberjs/data#4416]
When i run the tests i get warnings and deprecation's.

Before i try to see if i can get rid of them i want to understand if this is expected behavior, or am i doing something wrong ?
- WARNING: FEATURE["ds-serialize-ids-and-types"] is set as enabled, but FEATURE flags are only available in canary builds.
- DEPRECATION: Using the global version of DS is deprecated. Please either import the specific modules needed or `import DS from 'ember-data';`. [deprecation id: ember-data.global-ds]
      at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:16464:7)
      at raiseOnDeprecation (http://localhost:4200/assets/vendor.js:16372:12)
      at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:16464:7)
      at invoke (http://localhost:4200/assets/vendor.js:16480:7)
      at deprecate (http://localhost:4200/assets/vendor.js:16433:32)
      at Object.deprecate (http://localhost:4200/assets/vendor.js:26472:37)
      at deprecate (http://localhost:4200/assets/vendor.js:69315:40)
      at get (http://localhost:4200/assets/vendor.js:82215:44)
      at http://localhost:4200/assets/tests.js:21:21
- DEPRECATION: The adapter returned an array for the primary data of a `queryRecord` response. This is deprecated as `queryRecord` should return a single record. [deprecation id: ds.serializer.rest.queryRecord-array-response]
      at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:16464:7)
      at raiseOnDeprecation (http://localhost:4200/assets/vendor.js:16372:12)
      at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:16464:7)
      at invoke (http://localhost:4200/assets/vendor.js:16480:7)
      at deprecate (http://localhost:4200/assets/vendor.js:16433:32)
      at Object.deprecate (http://localhost:4200/assets/vendor.js:26472:37)
      at deprecate (http://localhost:4200/assets/vendor.js:69315:40)
      at http://localhost:4200/assets/vendor.js:85334:48
      at runInDebug (http://localhost:4200/assets/vendor.js:16645:5)
- WARNING: Interacting with a record errors object will no longer change the record state.
- WARNING: There is no attribute or relationship with the name `notInMapping` on `post`. Check your serializers attrs hash.
- DEPRECATION: `RESTSerializer.normalizeHash` has been deprecated. Please use `serializer.normalize` to modify the payload of single resources. [deprecation id: ds.serializer.normalize-hash-deprecated]
      at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:16464:7)
      at raiseOnDeprecation (http://localhost:4200/assets/vendor.js:16372:12)
      at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:16464:7)
      at invoke (http://localhost:4200/assets/vendor.js:16480:7)
      at deprecate (http://localhost:4200/assets/vendor.js:16433:32)
      at Object.deprecate (http://localhost:4200/assets/vendor.js:26472:37)
      at deprecate (http://localhost:4200/assets/vendor.js:69315:40)
      at normalize (http://localhost:4200/assets/vendor.js:85181:46)
      at superWrapper [as normalize](http://localhost:4200/assets/vendor.js:33225:22)
- WARNING: Ember Data expected to find records with the following ids in the adapter response but they were missing: [igor]

**Comment by bmac** [comment]
Hi @frunjik. These warnings are expected. Most of them are from recent deprecations and warnings added to the code base. Since they don't fail the build these cleaning up the old tests often get missed. If you have some time to get rid of some of these that would be great.

**Comment by frunjik** [comment]
My knowledge lacks to be able to solve the issues myself.
I have identified the offending tests (by trial and error).
I include a list of offending tests per message.
Maybe you can help me by hinting at what the right approach would be to get rid of the messages ?

==
DEPRECATION: Using the global version of DS is deprecated. Please either import the specific modules needed or import DS from 'ember-data';. [deprecation id: ember-data.global-ds]
- Solvable by explicitly importing Ember.DS in tests/ember-data-initializers.js 

==
WARNING: FEATURE["ds-serialize-ids-and-types"] is set as enabled, but FEATURE flags are only available in canary builds.
- This is not tied to a particular test (it shows always even when running 0 tests)

==
DEPRECATION: The adapter returned an array for the primary data of a queryRecord response. This is deprecated as queryRecord should return a single record. [deprecation id: ds.serializer.rest.queryRecord-array-response]
**tests/integration/adapter/rest-adapter-test.js**
- test("queryRecord - returning an array picks the first one but saves all records to the store", ...

==
DEPRECATION: RESTSerializer.normalizeHash has been deprecated. Please use serializer.normalize to modify the payload of single resources. [deprecation id: ds.serializer.normalize-hash-deprecated] 
**tests/integration/serializer/rest.js**
- test('normalizeHash normalizes specific parts of the payload', ...
- test('normalizeHash works with transforms', ...

==
WARNING: There is no attribute or relationship with the name notInMapping on post. Check your serializers attrs hash.
**tests/json-serializer-test.js**
- test('normalizeResponse ignores unmapped attributes', ...

==
WARNING: Ember Data expected to find records with the following ids in the adapter response but they were missing: [igor]
**tests/unit/store/adapter-interop-test.js**
- test("store.fetchRecord reject records that were not found, even when those requests were coalesced with records that were found", ...

==
WARNING: Interacting with a record errors object will no longer change the record state.
**tests/integration/records/error.js**
- test('adding errors during root.loaded.created.invalid works', ...
- test('adding errors root.loaded.created.invalid works', ...
- test('adding errors root.loaded.created.invalid works add + remove + add', ...
- test('adding errors root.loaded.created.invalid works add + (remove, add)', ...

**tests/unit/model/errors.js**  (all tests in this module give the warning)
- test("add error", ...
- test("get error", ...
- test("remove error", ...
- test("remove same errors from different attributes", ...
- test("clear errors", ...

**Comment by frunjik** [comment]
Tracking progress
- [x] ~~DEPRECATION: Using the global version of DS is deprecated. Please either import the specific modules needed or import DS from 'ember-data';. [deprecation id: ember-data.global-ds]~~      
     **solved by #4418**
- [ ] WARNING: FEATURE["ds-serialize-ids-and-types"] is set as enabled, but FEATURE flags are only available in canary builds. **[no specific files/tests / is global]**
- [ ] DEPRECATION: The adapter returned an array for the primary data of a queryRecord response. This is deprecated as queryRecord should return a single record. [deprecation id: ds.serializer.rest.queryRecord-array-response] **[1 file / 1 test]**
- [ ] DEPRECATION: RESTSerializer.normalizeHash has been deprecated. Please use serializer.normalize to modify the payload of single resources. [deprecation id: ds.serializer.normalize-hash-deprecated] **[1 file / 2 tests]**
- [ ] WARNING: There is no attribute or relationship with the name notInMapping on post. Check your serializers attrs hash.**[1 file / 1 test]**
- [ ] WARNING: Ember Data expected to find records with the following ids in the adapter response but they were missing: [igor] **[1 file / 1 test]**
- [ ] WARNING: Interacting with a record errors object will no longer change the record state. **[2 files / 9 tests]**

**Comment by lkhaas** [comment]
With regards to the queryRecord warning, there are two tests (next to each other) in rest-adapter-test.  One "queryRecord - returning an array picks the first one but saves all records to the store" seems to run counter to "queryRecord - returning an array is deprecated".  I'm not sure which of these tests is the valid one.  It appears that the code is following the latter (deprecation warning).

**Comment by bmac** [comment]
There are some tests in the Ember Data repo that test for deprecated behavior. I don't believe we want to remove those tests yet because the deprecated behavior is still valid until Ember Data 3.0 and we don't want to accidentally break it before then.


Recently I discovered that the [ember-dev library injects](https://github.com/emberjs/ember-dev/blob/bcfb9c3487ec2fd58b932394a15ce16fd9cf7eed/addon/test-helper/deprecation.js#L67) an `ignoreDeprecation` method into the test environment. We can use that to silence known deprecations for valid tests like "queryRecord - returning an array picks the first one but saves all records to the store" by wrapping the call that triggers deprecated code in 

```js
ignoreDeprecation(function() {
  //... some code that is deprecated
})
```

We may also need to add `ignoreDeprecation` to the [list of acceptable globals](https://github.com/emberjs/ember-dev/blob/bcfb9c3487ec2fd58b932394a15ce16fd9cf7eed/tests/.jshintrc#L2) in our tests.

**Comment by lkhaas** [comment]
That sounds great - unfortunately it seems to only apply to synchronous code.  I opened a corresponding issue https://github.com/emberjs/ember-dev/issues/165
Will try to continue on this (or work on that as well).

**Comment by bmac** [comment]
One technique that is used in some places in the Ember Data tests is to mock out the API response and wrap some async code in an `Ember.run(function() { ... })` which will make the code run as if it was synchronous from outside the `Ember.run` call. While, this may not be possible everywhere I suspect some of the deprecations could be silenced by wrapping the `Ember.run` in `ignoreDeprecation`.

**Comment by frunjik** [comment]
Thx for helping me understand :)

A general test question:

To test locally i run:

ember serve -lrp 49155 - localhost:4200/tests
and
ember test production=environment

both succeed...

But when i push the commit the build it (sometimes) fails ...

What command(s) do i need to invoke to simulate the test run's the CI's do ?

**Comment by wecc** [comment]
@frunjik Thank you so much for tackling this and please forgive the late response. Are you still willing to work on this? Is there anything I can do to help? Feel free to reach out in the Ember Community Slack.
