### ISSUE TITLE
JSON API 1.0 Full Support

### ISSUE THREAD

**Issue by jvanantwerp** [emberjs/data#4420]
The current implementation of JSONAPISerializer/Adapter is not a full implementation of the JSON API 1.0 Specification.  Some things that are missing are access to resource-level relationship links, document level metadata, and and document level links.

Are there any plans underway to add full specification support?

**Comment by aars** [comment]
@jvanantwerp If you're in need of things like resource-level relationship control, have a look at [pixelhandler's ember-jsonapi-resources library](https://github.com/pixelhandler/ember-jsonapi-resources)

**Comment by pangratz** [comment]
> Are there any plans underway to add full specification support?

Hey @jvanantwerp, we're not quite there yet but [RFC#160](https://github.com/emberjs/rfcs/pull/160) aims to address this.

**Comment by jvanantwerp** [comment]
@pangratz that will be very helpful!  Any idea on a timeframe?

**Comment by pangratz** [comment]
@jvanantwerp unfortunately not 😔 But as soon as the RFC is flushed out, I guess somebody will start working on an implementation.

I am aware that it is quite frustrating that this is not supported yet, but we definitely need to flush out all the use cases and the API before we can start working on it.

**Comment by wecc** [comment]
We're tracking JSON API support in #2905 so I'm closing this, feel free to take part of the discussions in there.
