### ISSUE TITLE
Relationships return null

### ISSUE THREAD

**Issue by scryba** [emberjs/data#4429]
I can't seem to get ember to display related data.

These are my models

//models/account.js
import Model from 'ember-data/model';
import attr from 'ember-data/attr';
import { belongsTo } from 'ember-data/relationships';

export default Model.extend({
  title: attr('string'),
  firstname: attr('string'),
  lastname: attr('string'),
  othernames: attr('string'),
  email: attr('string'),
  phone: attr('number'),
  senderId:  attr('string'),
  numSenderId:  attr('string'),
  accountBalance:  attr('number'),
  refCode:  attr('string'),
  phoneValidated:  attr('boolean'),
  emailValidated:  attr('boolean'),
  createdAt:  attr('date'),
  updatedAt:  attr('date'),
  country: belongsTo('country'),
});

//models/country.js
import Model from 'ember-data/model';
import attr from 'ember-data/attr';
import { hasMany } from 'ember-data/relationships';

export default Model.extend({
  longName: attr('string'),
  shortName: attr('string'),
  duoCode: attr('string'),
  trioCode: attr('string'),
  numericCode: attr('number'),
  createdAt: attr('date'),
  updatedAt: attr('date'),
  accounts: hasMany('account'),
});

//This is the index.js
import Ember from 'ember';

export default Ember.Route.extend({
  
  model() {
    var Id = '11e61481e3b68640b31b63eae8eae225';
    return this.store.findRecord('account', Id);
  }

});

//index.hbs
{{outlet}}

<br> belongsTo Relations <br>
<p>
  {{model.firstname}} from <em>{{model.country.longName}}</em>
</p>

/// JSON API response for /accounts/11e61481e3b68640b31b63eae8eae225

{
  "data": {
    "type": "accounts",
    "id": "11e61481e3b68640b31b63eae8eae225",
    "attributes": {
      "title": "Dr.",
      "firstname": "Aletha",
      "lastname": "Schoen",
      "othernames": "DVM",
      "email": "chanel90@omail.co",
      "phone": "+9300641934018",
      "sender-id": "sydney.mert",
      "num-sender-id": "9300641934018",
      "account-balance": "180.0000",
      "ref-code": "82362854",
      "phone-validated": 1,
      "email-validated": 1,
      "created-at": "2016-05-07 18:31:18",
      "updated-at": "2016-05-07 18:31:18",
    },
    "links": {
      "self": {
        "href": "/accounts/11e61481e3b68640b31b63eae8eae225"
      }
    },
    "relationships": {
      "country": [
        {
          "data": {
            "type": "country",
            "id": "418977"
          }
        }
      ]
    }
  },
  "included": [
    {
      "type": "country",
      "id": "418977",
      "attributes": {
        "long-name": "Sri Lanka",
        "short-name": "Dominica",
        "twol-code": "wi",
        "threel-code": "xFJ",
        "numeric-code": 90,
        "created-at": "2016-05-07 18:31:17",
        "updated-at": "2016-05-07 18:31:17"
      },
      "links": {
        "self": {
          "href": "/countries/418977"
        }
      }
    }
  ],
  "jsonapi": {
    "version": "1.0"
  }
}

Using 
Ember : 2.5.1
Ember Data : 2.5.2

**Comment by pangratz** [comment]
It looks like the `country` relationship returned for `/accounts/11e61481e3b68640b31b63eae8eae225` is an array, although it is defined as a `belongsTo`. If the relationship is updated in the reponse to be a single object, this should work:

```js
{
  "data": {
    "type": "accounts",
    "id": "11e61481e3b68640b31b63eae8eae225",
    "relationships": {
      "country": {
        "data": {
          "id": "418977",
          "type": "country"
        }
      }
    }
  }
}
```

**Comment by pangratz** [comment]
I am going to close this as I really think the returned array for the belongs-to relationship is the issue here. Feel free to reopen if you think this is still a bug.

Also feel free to ask in the `#-ember-data` channel in the `embercommunity` slack.

**Comment by scryba** [comment]
Hello @pangratz you are very right, just tried it and it worked fine.

**Comment by pangratz** [comment]
Awesome! Glad this has been figured out!
