### ISSUE TITLE
Default test generated for application serializer depends on 'model:application'

### ISSUE THREAD

**Issue by jcano** [emberjs/data#4436]
After generating a serializer for the application using ember-cli

```
ember g serializer application
```

The tests generated by ember-cli fail with:

```
Attempting to register an unknown factory: `model:application`
```

**Comment by bmac** [comment]
This is defiantly a bug. 

I think the fix is to introduce some new test helpers for serializers so they do not need to rely on `moduleForModel` for testing.

**Comment by wecc** [comment]
Should be re-open this issue in https://github.com/emberjs/ember-qunit + https://github.com/switchfly/ember-test-helpers ?

**Comment by pangratz** [comment]
@wecc I think this issue should be tracked here, since we are providing the blueprint ourselves.

**Comment by runspired** [comment]
should be resolved with the latest and greatest :)
