### ISSUE TITLE
QueryRecord causing relationships to incorrectly link

### ISSUE THREAD

**Issue by Kilowhisky** [emberjs/data#4452]
I'm not entirely sure how to describe this bug. I have a feeling ember is hooking up relationships incorrectly but explicitly forcing the relationships doesn't appear to be doing anything useful. 

Here is a working model. 
https://ember-twiddle.com/8058c9349db3e850115b6186ee1ae61e?openFiles=routes.set-edit.js%2C

I have two models:
```
// /models/myset.js
export default Model.extend({
  name: attr('string'),
  revisionLatest: belongsTo('myset-revision')
});
```
```
// /models/myset-revision.js
export default Model.extend({
  myset: belongsTo('myset'),
  createdDate: attr('date'),
  settings: attr()
});
```

I query for the records like so. 
```
 model(params){
  	return Ember.RSVP.hash({
      set: this.store.findRecord('myset', params.set_id),
      revision: this.store.queryRecord('myset-revision', {
         revision: params.revision_id,
         includeSettings: true
      }),
      revisions: this.store.query('myset-revision', { setId: params.set_id })
    });
  }
```

 For some reason ember data is doing two things when i query like this. 

1. It is switching the relationship depending on what records are loaded. My model specifies that the revisionLatest is id 2. Yet when you click on revision 2 and then click on revision 1 you can see that the "SetLatestRevision" flashes to 1. Now in the demo app it ends up switching back to two. But in my real ember app it just stays on 1. 
2. It is refusing to even populate the relationship under certain circumstances. This can be viewed by clicking on revision 2 and then at the bottom attempting to click "View Revision: 1". The link-to helper will squawk about not having enough information to link to the other route even though it never makes a GET request and should already have everything it needs downloaded.

**Comment by bmac** [comment]
It looks like Ember Data's heuristics for syncing both sides of a relationship are mistakenly assuming that `revisionLatest` and `myset` are a 1 to 1 relationship. So when Ember Data sees the response from the `myset-revision` with id 1's `myset` property is pointing to the `myset` with an id of 1 record it tries to update the `myset` record's `revisionLatest` to point back to the `myset-revision` with id 1 to keep the `revisionLatest` and `myset` relationships in sync.

The easiest fix would be to tell Ember Data that there is no inverse relationship for the `revisionLatest` relationship.

```js
// /models/myset.js
export default Model.extend({
  name: attr('string'),
  revisionLatest: belongsTo('myset-revision', { inverse: null })
});
```

**Comment by Kilowhisky** [comment]
That doesn't seem to affect the result. It still linked them up incorrectly.

The only thing that did seem to work was declaring two relationships and then explicitly define which one i was talking about.  Once i did that everything worked as expected.

```
// /models/myset.js
revisions: hasMany('myset-revision'),
revisionLatest: belongsTo('myset-revision')
```

```
// /models/myset-revision.js
myset: belongsTo('myset', { inverse: 'revisions' })
```

Should this be closed as a quirk then? Seems odd to me that the `inverse: null` didn't fix the problem though.

**Comment by bmac** [comment]
It is odd that `inverse: null` didn't fix the problem. When I was testing your twiddle adding the `inverse: null`. Appeared to fix the "flashes to 1" issue.

**Comment by Kilowhisky** [comment]
Your right. It does fix it in the test app!  But it doesn't seem to work in my live one. I'll investigate further and see if i can replicate it again. I'll just close this for now.
