### ISSUE TITLE
Currently no way to get relationship info from JSON-API relationship "self" links

### ISSUE THREAD

**Issue by robbiespeed** [emberjs/data#4453]
When relationship data is absent ember-data instead relies on the "related" link, and makes a request that grabs all the related resources data.

This causes potentially a lot of duplicate data to be pulled down from the api.

Say I have a `file`:
```
data: {
  "id": "1",
  "type": "files",
  "attributes": {
    "name": "File1",
  },
  "relationships": {
    "folders": {
      "links": {
        "self": "api/files/1/relationships/folders",
        "related": "api/files/1/folders"
      }
    }
  }
}
```
and my `folders` look like this:
```
data: {
  "id": "1",
  "type": "folders",
  "attributes": {
    "name": "Folder1",
  },
  "relationships": {
    "files": {
      "links": {
        "self": "api/folders/1/relationships/files",
        "related": "api/folders/1/files"
      }
    }
  }
}
```

Whenever I go to load a `file` it could be pulling back `folders` that have already been loaded.

It would be much better to instead grab ids from the `api/files/1/relationships/folders` endpoint. Then only make requests for the folders not loaded already.

**Comment by wecc** [comment]
> Whenever I go to load a file it could be pulling back folders that have already been loaded.

ED wouldn't (shouldn't) automatically re-fetch the already loaded folders - yes, the links would be duplicate data but not the folders themselves... if I'm not missing something?

**Comment by wecc** [comment]
If not a bug but feature request for relationship `self` link support I would like to close this and keep tracking relationship `self` link support in #2905

**Comment by robbiespeed** [comment]
> ED wouldn't (shouldn't) automatically re-fetch the already loaded folders - yes, the links would be duplicate data but not the folders themselves... if I'm not missing something?

It does refetch already loaded folders. If I have `file_1` and `file_2` both of which relate to `folder_a`, when I get the folder relationship on both files it'll receive the data for `folder_a` twice. Unavoidable in instances where relationships are only represented in links until self links support is added.

But yes this is a feature request for `self` links, so I think it would be fine to track and discuss there, and in [RFC #160](https://github.com/emberjs/rfcs/pull/160).
