### ISSUE TITLE
Rename the store's `query` to `queryAll`

### ISSUE THREAD

**Issue by Panman8201** [emberjs/data#4458]
Seems odd that we have `findRecord` <=> `queryRecord`, but `findAll` <=> `query`. Seems logical for `query` to be `queryAll` so that it lines up with `findAll`.

Just a suggestion. More of a bikeshed case, so I don't really care one way or the other (I just like consistancy :smile:).

**Comment by bmac** [comment]
We discussed naming `query` `queryAll` when when `find` was split into, `findRecord`, `findAll` and `query` but ultimately decided to name it `query` instead of `queryAll` because the record set returned by `query` is unlikely to be "all" of the records.

**Comment by Panman8201** [comment]
Very well, makes sense. Maybe `queryMultiple` or `queryMany` would work, but probably not worth the hassle of changing it now... Just thought I'd bring the topic up. Thanks
