### ISSUE TITLE
store#query returns internalModels

### ISSUE THREAD

**Issue by FredUK** [emberjs/data#4462]
I've recently upgraded to Ember Data 2.6 (from 1.13) and I just noticed when using the store.query method it is returning an object with my models being InternalModels inside the content property.
For what I could read in different parts the models are not being materialized. Is that the correct term?
![image](https://cloud.githubusercontent.com/assets/11888256/16582454/ef4bde38-42a6-11e6-9ac9-066dca30d4d4.png)

![image](https://cloud.githubusercontent.com/assets/11888256/16582534/5e39341c-42a7-11e6-805a-4405e0326690.png)

To iterate over the results I need to iterate over `results.conten`t and then call `getRecord()` on each one if I want to be able to use .get().
Is this how it is supposed to work or should I just get a RecordArray ?

The docs ( https://guides.emberjs.com/v2.6.0/models/finding-records/ ) say:

```
// GET to /persons?filter[name]=Peter
this.get('store').query('person', { filter: { name: 'Peter' } }).then(function(peters) {
  // Do something with `peters`
});
```

But I can't do something with `peters`.. Am I doing anything wrong? All seemed to work fine with 1.13

**Comment by FredUK** [comment]
#3530

**Comment by bmac** [comment]
Hi @FredUK the `content` property on the RecordArray is private and its not recommended that you access it. If you would like to do something with the records in the resulting query array you can use normal array methods on the RecordArray like `map`, `filter`, `forEach`, ect. You can also convert the RecordArray into a normal array by calling `toArray()`.

**Comment by pangratz** [comment]
I am closing this since accessing `content` directly is not encouraged. As @bmac pointed out, you should use the methods on the `RecordArray` or `toArray()` instead.

**Comment by pangratz** [comment]
Hmm, actually I think it's better to reopen this and close once #3604 is addressed...

**Comment by wecc** [comment]
@pangratz are you OK with closing this (again) and keep tracking the issue in #3604 instead of having two issues related to the same thing open?

**Comment by pangratz** [comment]
Seems good.
