### ISSUE TITLE
[ds-improved-ajax] feature is stringifying my data params and messing up url

### ISSUE THREAD

**Issue by danielspaniel** [emberjs/data#4465]
Is there something I am missing in this feature. 

When it is on: 
```js
 store.query('model', {name: 'foo'}) 
```
results in url:

/foo{%22name%22:%22foo%22}

I see that in the code you are 

```js
    _requestToJQueryAjaxHash(request) {
     ...
         hash.data = JSON.stringify(request.data);
```

stringifying that data

which is therefore messing up the url 

should I update something besides ember-data?

**Comment by pangratz** [comment]
Thanks for reporting and reminding me to merge #4465, which will fix this bug...
