### ISSUE TITLE
Uncaught TypeError: this._initProperties is not a function when using PromiseObject

### ISSUE THREAD

**Issue by olivierlesnicki** [emberjs/data#4467]
```js
import Ember from 'ember';
import DS from 'ember-data';
import layout from '../templates/components/ember-cli-static-loader';

export default Ember.Component.extend({
  layout,
  content: Ember.computed(function () {
    return new DS.PromiseObject.create({
      promise: Ember.$.get('/pages/' + this.get('path')).then(html => {
        return Ember.Object.create({ html });
      })
    });
  })
});
```

Result in an error: 
```
Uncaught TypeError: this._initProperties is not a function when using PromiseObject
```

**Comment by bmac** [comment]
I haven't seen this error before and I don't think `_initProperties` is something that Ember Data defines.
@olivierlesnicki do you mind creating a [jsbin](http://emberjs.jsbin.com/sarobu/1/edit?html,js,output) that reproduces the issue? 

From a quick glance at the code the only thing that looks out of place is the `new` keyword isn't needed with using the `create` method of an ember object. `return new DS.PromiseObject.create({`

**Comment by pangratz** [comment]
I can confirm that the error goes away if you are not creating the `DS.PromiseObject` via `new DS.PromiseObject.create` but via `DS.PromiseObject.create` without new. See [this ember-twiddle](https://ember-twiddle.com/80cec6028fb1360f8f7a3ba1b2e887ce?fileTreeShown=false&numColumns=2&openFiles=components.person-name.js%2Ctemplates.components.person-name.hbs).
