### ISSUE TITLE
Multiple calls made to fetch association

### ISSUE THREAD

**Issue by aandis** [emberjs/data#4476]
Order model

```js
export default Model.extend({
    name: attr('string'),
    products: hasMany('product', { async: true })
});
```

Product model

```js
export default Model.extend({
    title: attr('string'),
    order: belongsTo('order',  { async: true })
});
```
Using `JSONAPIAdapter`, `store.findAll('orders')` works fine like below - 

```json
{
    "data": [
        {
            "id": "1",
            "type": "orders",
            "attributes": {
                "name": "abcd"
            },
            "relationships": {
                "products": {
                    "data": [
                        {
                            "id": "1",
                            "type": "product"
                        },
                        {
                            "id": "2",
                            "type": "product"
                        }
                    ]
                }
            }
        }
    ]
}
```

But when I do, `order.products` for the first order, the adapter makes multiple api calls - 

    /products/1

    /products/2

I expected - 

    /products?ids=[1,2]

Is this intended behavior? How can I change it to fetch associations in a single call?

**Comment by aandis** [comment]
```json
 "ember-data": "^2.6.0",
 "ember-cli": "2.6.2"

```

**Comment by davidpett** [comment]
@aandis set `coalesceFindRequests: true` in your adapter

**Comment by aandis** [comment]
@davidpett thanks! that did it. Sorry I am just really new to ember. Is it also possible to configure the resource route? For example I want `order.products` to call `/order/:order_id/products?ids[]=1&ids[]=2`

**Comment by aandis** [comment]
Found it! http://stackoverflow.com/questions/24515729/how-to-use-ember-data-with-nested-resources
Thanks. :)

**Comment by davidpett** [comment]
Great. Best place to ask these questions is in slack. Does not require opening an issue
