### ISSUE TITLE
Make id datatype configurable

### ISSUE THREAD

**Issue by hezus** [emberjs/data#4477]
RELATED: https://github.com/emberjs/data/issues/4166

Assuming a ID is always a string feels very opinionated towards API's which use a UUID. 

Wouldn't it be better to set a type for the id? I use ember for many project but most times you work against a REST API which expect the ID to be a integer corresponding to a certain database ID. 

It would be nice if the ID datatype is configurable, so it is always a string or integer depending on the settings.

A dynamic typed language like Ruby or Javascript doesn't really care, but whenever I work with a strong typed API this is always a hassle, especially if you work with embedded objects.

**Comment by fivetanley** [comment]
Hi @hezus,

The reason we don't make it configurable is that `id` is heavily used internally. Having a consistent type means we have less type errors and keeps the internals a bit more clean. Numbers also get converted to strings when put inside an object in JavaScript (e.g. `{}`).

If your server only accepts a strict Number type, you could override [serialize](http://emberjs.com/api/data/classes/DS.RESTSerializer.html#method_serialize):

```javascript
export default DS.JSONAPISerialize.extend({
  serialize: function(snapshot, options) {
    var json = this._super(snapshot, options);
    json.id = parseInt(json, 10);
    return json
  }
});
```

**Comment by fivetanley** [comment]
Actually for symmetry we should probably have a `serializeId` hook as we have an [extractId hook](http://emberjs.com/api/data/classes/DS.RESTSerializer.html#method_extractId).

**Comment by pangratz** [comment]
I am closing this issue since #4620 has been merged: having the `ds-serialize-id` feature enabled, you can now overwrite `serializeId` and customize how the id should be serialized into the hash.
