### ISSUE TITLE
PUT request generated instead of PATCH

### ISSUE THREAD

**Issue by deepan83** [emberjs/data#4478]
I have a survey model with a hasMany relationship to a question model. When I add questions to this relationship and save the survey, I get a PUT request instead of a PATCH. My understanding is that the JSON API spec uses PATCH for resource updates as opposed to PUT. Is this behaviour a bug?

**Comment by bmac** [comment]
You are correct `PATCH` is the expected verb. What version of Ember Data are you using?

**Comment by deepan83** [comment]
2.5.2

**Comment by bmac** [comment]
Do you have an application adapter or a model specific adapter defined in your project? Usually located in `app/application/adapter.js` or `app/adapters/application.js`?

**Comment by deepan83** [comment]
Just realised that I had a REST adapter as opposed to the JSONAPI one!
