### ISSUE TITLE
Loading hasMany through record acquired from findRecord bug

### ISSUE THREAD

**Issue by DanielOchoa** [emberjs/data#4480]
This looks like a bug but I'm not entirely sure -- I am making a request for a single record through `findRecord` and the response follows the JSON API spec. It returns the `relationships`  object and the `included` object as well so in essence it's side loading a `hasMany` called `employeeLineItems`. Snippets are blow:

Ember model:
`pods/invoice/model.js`
```javascript
  export default Model.extend({
    invoiceType: attr('string'),
    employeeLineItems: hasMany('employee-line-item'),
    …
```

Here's the payload when doing a request through `findRecord`:
url: `/api/v1/admin/invoices`
```json
{
  "data":{
    "id":"1",
    "type":"invoice",
    "attributes":{
       ...
    },
    "relationships":{
      "employee-line-items":{
        "data":[
          {
            "id":"1",
            "type":"employee-line-item"
          },
          {
            "id":"2",
            "type":"employee-line-item"
          },
          {
            "id":"3",
            "type":"employee-line-item"
          }
        ]
      }
    }
  },
  "included":[
    {
      "id":"1",
      "type":"employee-line-item",
      "attributes":{
         ...
      }
    },
    {
      "id":"2",
      "type":"employee-line-item",
      "attributes":{
        ...
      }
    },
    {
      "id":"3",
      "type":"employee-line-item",
      "attributes":{
          ...
      }
    }
  ]
}
```

And this is how I'm calling `findRecord`:

```javascript
this.get('store').findRecord('invoice', 1).then(invoice => {
  // invoice.get('employeeLineItems') is empty, so maybe we need to resolve it as a promise...
  return invoice.get('employeeLineItems');
}).then(lineItems => {
  // this is where lineItems is [] and I believe it shouldn't.
});
```

The `lineItems` array var does get populated eventually, but the promise for them gets resolved and it is not populated until a microsecond later, which it seems like the promise shouldn’t be resolved until the array for the relationship has the line items. Calling `invoice.hasMany('employeeLineItems').ids()` is also empty. Ember data version is 2.6.

**Comment by pangratz** [comment]
I cannot reproduce this; the payload you provided seems fine and it works, see [this ember-twiddle](https://ember-twiddle.com/5dd26cd41636f49c81ef212d91439e79?fileTreeShown=false&openFiles=routes.application.js%2C). Do you spot any differences to the code you have in your app?

**Comment by DanielOchoa** [comment]
Thanks for looking into it. it's not different from the payload perspective. I'll keep digging around. Thanks again.
