### ISSUE TITLE
DELETE request going as 'text/plain' for RESTAdapter

### ISSUE THREAD

**Issue by escobera** [emberjs/data#4487]
Hello there,

I was having trouble connecting to a java api today using the ```RESTAdapter``` and and after debugging found out that my DELETE requests were being sent with ```'Content-Type: text/plain;charset=UTF-8```.

I was getting a mime type error from the server, which was denying everything that wasn't ```application/json```. 

Since a ```DELETE``` request is almost always (and this is my case) dataless, why send a Content-Type header at all? And if so, why not the default one for the adapter?

PS: I was able to make it work with the following horrid workaround:
```javascript
export default DS.RESTAdapter.extend({
  //...
  ajaxOptions(url, type, options) {
    let newOptions = this._super(...arguments);
    if (type === 'DELETE') {
      newOptions.contentType = 'application/json; charset=utf-8';
    }
    return newOptions;
  }
});
```

**Comment by bmac** [comment]
I'm not sure where the `text/plain` is coming from. Looks like Ember Data only sets a content type when there is a payload https://github.com/emberjs/data/blob/master/addon/adapters/rest.js#L1081. As you pointed out the DELETE request is dataless so this field should be empty.

**Comment by escobera** [comment]
Maybe jquery is setting it? I don't know jquery's internals and couldn't find anything on a glance.

**Comment by pangratz** [comment]
So it looks like jQuery is setting it to `text/plain` when no data is send with the request (see [this ember-twiddle](https://ember-twiddle.com/d9ba245761c2f077323d1dbcf0c36d7a?fileTreeShown=false&numColumns=2&openFiles=routes.application.js%2Cadapters.application.js) for a demonstration).

@escobera if your API expects to always have a specific `Content-Type` header set, you can specify the `headers` on your adapter via:

```js
// app/adapters/application.js
export default RESTAdapter.extend({
  headers: {
    "Content-Type": "application/json; charset=utf-8"
  }
});
```

With this you don't need to overwrite `ajaxOptions`.

---

Not sure if this should be changed in ember-data so the `Content-Type` is set to `application/json` for every request, regardless if data is present or not. A similar issue to this is #4226, where the `Content-Type` for `json-api` is also only set when data is present...

**Comment by escobera** [comment]
@pangratz 
I was about to open an issue on jquery's repo but when trying to reproduce this with jquery alone I couldn't.

Check this [jsbin](https://jsbin.com/hefewe/edit)

I don't know if I'm doing something wrong but it seems to not be setting the content-type at all (which is the correct behavior).

**Comment by pangratz** [comment]
Ok, so after a little debugging it looks like the `text/plain` content type in the twiddle is set [within `FakeXMLHttpRequest`](https://github.com/pretenderjs/FakeXMLHttpRequest/blob/fafac9799ac9989fa4798f2fe23b071c2209e04e/src/fake-xml-http-request.js#L270) 😔  ... Setting a breakpoint and doing a `delete this.requestHeaders["Content-Type"]` after that line looks like it results in a request intercepted by Pretender with no `Content-Type` header being set anymore - like your JSBin shows as well @escobera.

The only relevant issues I could find in the jQuery repo are https://github.com/jquery/jquery/issues/1801 and https://github.com/jquery/jquery/issues/1804...

**Comment by escobera** [comment]
I tested both 2.x and 3.x versions of jquery, this bug doesn't seem to be on their side. I'll try and debug a little more.

**Comment by wecc** [comment]
@escobera did you find anything? I'm unable to reproduce this issue in a brand new app with `RESTAdapter`, using:

```
DEBUG: Ember      : 2.8.2
DEBUG: Ember Data : 2.9.0
DEBUG: jQuery     : 3.1.1
```

**Comment by escobera** [comment]
@wecc sorry, forgot to add to this. I found the culprit. ember-data is not to blame.
As @pangratz said the problem lies in withing FakeXMLHttpRequest. I've opened an issue there (https://github.com/pretenderjs/FakeXMLHttpRequest/issues/27), but so far, no answer.

Thanks a lot guys, I think we can close this.
