### ISSUE TITLE
Brittle Promise Usage

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/data#4488]
The following snippets make an invalid assumption, that is all code they execute cannot possibly throw. Although it may seems reasonable to assume this, it unfortunately isn't, especially for framework provided code, that calls into other extension points.

- [ ] https://github.com/emberjs/data/blob/master/addon/adapters/rest.js#L1024-L1049
- [ ] https://github.com/emberjs/data/blob/master/addon/adapters/rest.js#L1008-L1020
- [ ] https://github.com/emberjs/data/blob/master/addon/adapters/rest.js#L1406-L1417
- [ ]  https://github.com/emberjs/data/blob/master/addon/adapters/rest.js#L1421-L1446

For example: `adapter.handleResponse` is a public API extension point, which has a pretty high likelihood of failing. https://github.com/emberjs/data/blob/master/addon/adapters/rest.js#L1041

Anyways, when wrapping contents of callbacks invoked by foreign async we must be careful, or unexpected errors will result breaking the completion guarantee of the given function, and can result in unrecoverable blank screens for our users. One such use-case is described here: https://github.com/emberjs/ember.js/issues/13919

The solution is to wrap the entire foreign invoked callback in a try/catch + reject https://github.com/emberjs/data/blob/master/addon/adapters/rest.js#L1024-L1049

```js
options.error = function() {
  try {
    // other code.
  } catch(e) {
    reject(e);
  }
}
```

For those that will argue that this is overly defensive and we cannot possibly guard against all possible failures, I would agree in the general case, but the above falls is merely our reasonable due diligence.

**Comment by pangratz** [comment]
I believe this is fixed by #4489. Feel free to reopen if I am mistaken.
