### ISSUE TITLE
Thinking about separating namespaces of domain and meta level in DS.Model

### ISSUE THREAD

**Issue by frunjik** [emberjs/data#4495]
The domain data and the meta data of an DS.Model live in the same namespace:
model.get('username')
model.get('isDestroyed')

Can we start thinking about ways to migrate to separating this ?

Maybe via:

model.get('meta.isDestroyed') 
model.meta.get('isDestroyed')

or something ...

**Comment by wecc** [comment]
I'm closing this as a duplicate of #3906
