### ISSUE TITLE
Deprecations for `Enumerable#contains` usage.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/data#4504]
In Ember 2.8.0-beta.1+ the `ember-runtime-enumerable-includes` feature is enabled (read more about it in [the RFC](https://github.com/emberjs/rfcs/blob/master/text/0136-contains-to-includes.md)). Many deprecations are triggered by Ember Data. 

It would be great to get this fixed before ember-data@2.8.0 stable is released, though I haven't dug into how much work it would be to fix.

**Comment by rwjblue** [comment]
I created https://github.com/rwjblue/ember-runtime-enumerable-includes-polyfill to make this a bit easier for Ember Data (and other addons) to avoid deprecations, use the newer syntax, and not trigger deprecations.

**Comment by pangratz** [comment]
I guess this is fixed by #4519 and can be closed, right?

**Comment by bmac** [comment]
Yes.
