### ISSUE TITLE
hasMany relationship getting out of sync

### ISSUE THREAD

**Issue by aaronbhansen** [emberjs/data#4507]
We have a hasMany relationship that appears to be getting into a race condition. We are saving multiple of the child relationships at the same time and then the parent has the incorrect number of associated records with it. Here is an example of the parent calling the child association of **selections**.

![example](https://cl.ly/1V2B0x3u101e/Screen%20Shot%202016-08-23%20at%209.37.37%20AM.png)

Without changing anything other than calling flushCanonical again, the record length and currentState changes to reflect the correct number of associations. It starts at 1, but the correct number of selections should be 3, which is reflected after flushCanonical is called.

Since it seems to be happening randomly (most the time it works, then occasionally it doesn't), I'm thinking it's a race condition between the various model states. Trying to get an example so it's repeatable, but not having luck having it consistently replicated. 

Is this a known issue, or any ideas on how to fix it? It is happening for sure between Ember data 2.5-2.7.

**Update**

I added some logging to get a better idea of what is happening. 

The logging code is 

```
DS.ManyArray.reopen({
    flushCanonical() {
      let canonicalStateLengthBefore = this.canonicalState.length;
      let toSetBefore = this.canonicalState.filter((internalModel) => !internalModel.isDeleted());
      let notDeletedLengthBefore = toSetBefore.length;
      let currentStateLengthBefore = this.currentState.length;
      let newRecordsLengthBefore = this.currentState.filter((internalModel) => internalModel.isNew() && toSetBefore.indexOf(internalModel) === -1).length;
      this._super(...arguments);
      let canonicalStateLengthAfter = this.canonicalState.length;
      let toSetAfter = this.canonicalState.filter((internalModel) => !internalModel.isDeleted());
      let notDeletedLengthAfter = toSetAfter.length;
      let currentStateLengthAfter = this.currentState.length;
      let newRecordsLengthAfter = this.currentState.filter((internalModel) => internalModel.isNew() && toSetAfter.indexOf(internalModel) === -1).length;
      Ember.Logger.info(`${this.type.modelName}: canonicalState ${canonicalStateLengthBefore} / ${canonicalStateLengthAfter} - currentState ${currentStateLengthBefore} / ${currentStateLengthAfter} - Not Deleted ${notDeletedLengthBefore} / ${notDeletedLengthAfter} - New ${newRecordsLengthBefore} / ${newRecordsLengthAfter}`);
    }
  });
```

When it gets the error and the counts are off the first time the information is:

`order/selection: canonicalState 4 / 4 - currentState 4 / 3 - Not Deleted 3 / 3 - New 0 / 0`

Then after manually running flushCanonical again, the logging is:

`order/selection: canonicalState 4 / 4 - currentState 3 / 4 - Not Deleted 3 / 3 - New 1 / 1`

It appears that the new records aren't getting synced in the first time. 

Starting to think the issue is coming down to saving multiple new child records at the same time. If they are all saving and then calling flushCanonical at the same time as others, the internal collections are getting called and set multiple times. Which could cause errors in the collection. Maybe flushCanonical needs to be scheduled like in the situation of belongsTo

**Comment by aaronbhansen** [comment]
To distill the problem down the issue is related to multiple records of a hasMany collection saving at the same time and then calling flushCanonical. Either they are calling the same method  at the same time and overwriting the collections internally, or there are some model states that fully haven't resolved in the run queue that resolve later. 

To fix this internally for now, after all the child models have saved in the collection, we then call flushCanonical on the hasMany relationship and the record counts update correctly. This isn't a long term solution, just a hack for now. 

Any thoughts on a long term fix?

**Comment by jembezmamy** [comment]
It seems that I'm experiencing the same problem:

<img width="490" alt="zrzut ekranu 2016-10-13 o 10 08 25" src="https://cloud.githubusercontent.com/assets/720354/19341302/32eafe74-912d-11e6-84ca-dc0a06f6a8cf.png">

- I would expect that after `item.deleteRecord()` the `item` should disappear from `collage.get("items")`,
- After `item.save()` item 3 unnecessarily disappeared from the collection.

**Comment by aaronbhansen** [comment]
The deleted records are expected to remain until they are saved. That was a change in 2.0 so you could reference them still. 

But we've definitely keep hitting situations where we have flush the canonicalState after all child saves have been completed or we have missing records from the collections.

**Comment by runspired** [comment]
This layer has gone through substantial cleanup and refactoring since the time this was reported. If this is still an issue against latest master, please reopen and even better submit a failing test :D
