### ISSUE TITLE
store.findAll('foo', {reload: true}) returns PromiseArray with old data

### ISSUE THREAD

**Issue by jnfingerle** [emberjs/data#4508]
`store.findAll('foo', {reload: true})` returns with a PromiseArray containing the data before the call to the backend and will only later be populated with the new data.

In my case, I expected `store.findAll('foo', {reload: true}).then((data) => {this.set('bar', data.getEach('id')})` to work on the new data and set bar to the new ids, but I still have got the
old ones (which are none, in my case, because it's the first call). I thought this was standard behaviour that should be overridden by `{reload: true}`.

If it's only me not understanding  `{reload: true}` correctly, a hint in the right direction would be appreciated.

**Comment by fivetanley** [comment]
Hi @jnfingerle,

Can you tell us more about the requests? What is your server returning for both requests?

**Comment by jnfingerle** [comment]
Oh, sorry, I've shot myself in the foot. And then I redacted it out of the sample code for the issue. :-(

My code is like
```
promiseMeSomething()
.then(() => store.findAll('foo', {reload: true}))
.then((data) => {
  this.set('bar', data.getEach('id'));
})
```

This doesn't work, since the second line returns a promise for a promise, so data in line three is still the unsettled PromiseArray.

The following works:
```
promiseMeSomething()
.then(() => store.findAll('foo', {reload: true}))
.then((data) => {
  data.then((data) => {
    this.set('bar', data.getEach('id'));
  }
})
```
So, I'm sorry for mis-reporting this. It works as documented, but I'm back in "nested callback land" which seems a bit awkward and led to my confusion in the first place. Is there a better way to do this?

**Comment by jnfingerle** [comment]
Ah, well, adding to that, promiseMeSomething() is essentially Ember.$.ajax, so I've got a jQuery promise instead of an RSVP promise. With RSVP the first version works.
