### ISSUE TITLE
Immutability of RecordArray from this.store.findAll() should be characterized with a better error message

### ISSUE THREAD

**Issue by ckl1989** [emberjs/data#4513]
Currently, mutations to a RecordArray returned by a call to the store's findAll() is throwing the following error:

TypeError: internalModel.getRecord coming from record-array.js

This message is really ambiguous to the root cause and took me days of searching to sort it out. I feel a message about the RecordArray's immutability should be shown instead of a TypeError. 

This is also the case with AdapterPopulatedRecordArrays coming from query() calls, mutations should not be possible on the live array. I believe this was fixed for the query case, but not for the findAll() case.
This issue was raised in  #4045

The issue can be seen in the following ember fiddle with a reverseObjects() call:

https://ember-twiddle.com/d64b21293b6d7a2a2886f3b8368b1081?openFiles=controllers.application.js%2C

this is related to #3530 when trying to push objects. 

I hope my understanding of this issue is correct. Please correct me if I am wrong! I really haven't found too much information available online relating to this.

**Comment by ckl1989** [comment]
@bmac Sorry to call directly call out to you. I know you've probably got lots of other things to deal with but when you get a chance, can you provide some feedback on this PR? Thank you!

**Comment by wecc** [comment]
Closing this as #4520 has been merged!
