### ISSUE TITLE
Ember understands only dasherized property in relationships

### ISSUE THREAD

**Issue by ikondrat** [emberjs/data#4525]
If we have defined model with relationship like 

` myRelatedItems: DS.hasMany('my-related-item'),`

it works only for dasherized property in json
E.g. works
```
relationships : {
  "my-related-items":  ..

```

But doesn't work for camelized:
```
relationships : {
  "myRelatedItems":  ..

```

It is somehow reproduced only for relationships, for attribute properties Ember can understand  camelized property also

Looks like we need consistensy and it will be perfect to have option to understand camelized property in JSON for relationships also

**Comment by petrKoukal** [comment]
just in case smbd else finds this issue - in our Ember app we use JSON API, which expects dasherized names. We've overwritten this convention for attributes in application serializer with
```
keyForAttribute(attr) {
   return attr;
}
```

and of course forgot about it. With similar code, one can also adjust that for relationships: 
```
keyForRelationship(rel) {
   return rel;
}
```
