### ISSUE TITLE
isUpdating remains true if backgroundReloadAll is false

### ISSUE THREAD

**Issue by wongpeiyi** [emberjs/data#4527]
See http://emberjs.jsbin.com/xicosasazo/1/edit?html,js,output – click "Click here", then "Go back" –> `isUpdating` is true even though `backgroundReloadAll` returns false and no fetch was triggered

Should https://github.com/emberjs/data/blob/03d098d5cdb2fba2249f6c750268240c6400518d/addon/-private/system/store.js#L1378 reset `isUpdating` to `false` before returning?

**Comment by bmac** [comment]
Closed by https://github.com/emberjs/data/pull/4529
