### ISSUE TITLE
RESTAdapter silently swallows exceptions

### ISSUE THREAD

**Issue by yads** [emberjs/data#4533]
Let's say we using `findAll` to retrieve a set of models in our route

```
export default Ember.Route.extend({
   model() {
     return this.store.findAll('my-model');
   }
});
```

We then have a template like:

```
{{#each model as |instance|}}
  {{#each instance.prop key="id" as |p|}}
     <span>{{p.text}}</span>
   {{/each}}
{{/each}}
```

If we get a model instance like:

```
{
  prop: [{id: undefined, text: 'text'}]
}
```

The each helper will throw the error 'You must provide a string key when calling `yieldItem`; you provided undefined'. However, because of 

https://github.com/emberjs/data/blob/v2.8.0/addon/adapters/rest.js#L1014
and then subsequently 
https://github.com/tildeio/rsvp.js/blob/v3.3.1/lib/rsvp/-internal.js#L243

We have the error fail silently. The rest adapter catches the error, tries to reject it, but because the promise is already resolved, it swallows the exception. The rendering might completely fail, but the console will not show any errors, making it quite difficult to trace the error down.

**Comment by bmac** [comment]
Thanks for digging into this issue @yads. I think the solution would be to move the try/catch so it only wraps the `adapter.handleResponse` method and no longer includes the `Ember.run.join(null, resolve, response);` line.

**Comment by yads** [comment]
Thanks for opening the PR!
