### ISSUE TITLE
Error loading many to many JSONAPI relationship

### ISSUE THREAD

**Issue by sgargan** [emberjs/data#4549]
I'm seeing an issue loading a many to many relationship into ember from a jsonapi end. I've two models, a user and a project both of which reference one another. 

``` javascript
// app/models/project.js
import DS from 'ember-data';
export default DS.Model.extend({
  name: DS.attr('string'),
  users: DS.hasMany('user, {async: true}')
});

// app/models/user.js
import DS from 'ember-data';
export default DS.Model.extend({
  name: DS.attr('string'),
  email: DS.attr('string'),
  projects: DS.hasMany('project', {async: true})
});
```

If i hit the endpoint that loads the user it loads ok 

``` javascript
{
  "jsonapi": {
    "version": "1.0"
  },
  "data": {
    "type": "user",
    "relationships": {
      "projects": {
        "links": {
          "related": "/api/projects/1"
        }
      }
    },
    "id": "1",
    "attributes": {
      "name": "Steve",
      "email": "steve@me.io"
    }
  }
}
```

and when I access the projects I see the call to the projects api return with the following

``` javascript
{
  "jsonapi": {
    "version": "1.0"
  },
  "data": {
    "type": "project",
    "relationships": {
      "users": {
        "links": {
          "related": "/api/users/1"
        }
      }
    },
    "id": "1",
    "attributes": {
      "name": "Simple Example"
    }
  }
}
```

But this fails [here](https://github.com/emberjs/data/blob/581781c3385c9384c0f3589281ebf1efced770ea/addon/-private/system/store/finders.js#L103). Seems it's expecting an array of records to be returned when the payload is pushed but as it only has a single item in the the data attribute of the payload this fails. If I remove the has many from the project model it loads fine. Shouldn't the finder cater for both single item and array cases?

**Comment by rmcsharry** [comment]
I stumbled into this problem, but never knew the cause, and now I do, so thanks for posting this!
I worked around it by changing M-M to M-1-M, a bit more effort but at least it works.

**Comment by fivetanley** [comment]
I'm not sure what the jsonapi.org recommendation is but your api might want to return an array with one record in it as a workaround. That also lets ember data handle the case where there is more than one.

**Comment by fivetanley** [comment]
It doesn't look like jsonapi has a [recommendation](http://jsonapi.org/format/#fetching-relationships), pinging @igor or @dgeb as to whether we should:

* Warn if a response with one record is sent, and log a message indicating an array should be sent back or `normalizeHasManyResponse` should overridden
* Throw if a response with one record is sent, and log a message indicating an array should be sent back or `normalizeHasManyResponse` should overridden
* Just handle this case by default

If we don't pick the last choice, we should have some pretty robust error messaging.

**Comment by wecc** [comment]
It seems your `related` links point to a single resource but you're telling Ember Data it's a `hasMany` relationship?

Instead of `"related": "/api/projects/1"` I would kind of expect to see something like `"related": "/api/users/1/projects"`?

**Comment by xamoom-pali** [comment]
Btw, a typo?

`users: DS.hasMany('user, {async: true}')`

**Comment by sgargan** [comment]
@wecc you are correct, refactoring to your suggested layout made a lot of sense so I've changed my service to expect that instead. Thanks for your help.
