### ISSUE TITLE
Saving with EmbeddedRecordsMixin does not update related models dirty attributes

### ISSUE THREAD

**Issue by ewoody** [emberjs/data#4552]
#2487 is still reproducible on "ember-data": "^2.4.0", "ember-cli": "2.7.0",

and it is big issue for performance while saving ember data.

Copied issue discription from #2487 

No matter what way the serializer is configured in Ember dirty attributes of the relationships records are not updated with those from the response, non dirty attributes are updated though.

The only workaround I have found is to manually go through and mark them individually as willCommit and then didCommit by overriding save on the model - I tried doing this in the serializer for better encapsulation but couldn't get it to work.

If I've specified serialize: 'records' for my serializer when using EmbeddedRecordsMixin I would expect those records to be automatically set as saving/saved etc. along with the parent according to the normal save flow.

**Comment by fivetanley** [comment]
Do you have an example model, payload, and serializer? It would be very helpful for us to try to track this down.

**Comment by wecc** [comment]
ping @ewoody ^

**Comment by hjdivad** [comment]
@igorT seems related to https://github.com/emberjs/rfcs/pull/173

**Comment by ewoody** [comment]
I will provide an example by Monday.

**Comment by runspired** [comment]
@ewoody did you ever make an example? This does not seem to be an issue anymore after https://github.com/emberjs/data/pull/3868

**Comment by runspired** [comment]
Anything not covered by #3868 is likely covered by #6272, will close with that.
