### ISSUE TITLE
Raise error on failed async load

### ISSUE THREAD

**Issue by anddah** [emberjs/data#4554]
If you use links to load data async and for some reason the server responds with a 500 error the array will be empty an no error is raised. That is if the async loading gets triggered by the template.

I did a small workaround in a model and 

```
model(params) {
        let _this = this;
        return new Ember.RSVP.Promise(function (resolve, reject) {
                _this.store.findRecord('model1', params.Id).then(
                    function(model1) {
                        breedinggroup.get('model2FromHasManyLink').then(
                            function() {
                                resolve(model1);
                            }, function(reason) {
                                reject(reason);
                            }
                        );
                    }, function(reason) {
                        reject(reason);
                    }
                );
            });
    }
```

This actually raises the error to my error action but it seams a bit much to get some error handling.

**Comment by wecc** [comment]
@anddah would you be able to create an https://ember-twiddle.com/ reproducing this issue?

**Comment by runspired** [comment]
closing as no reproduction was ever given. We have tests that cover these scenarios so we shouldn't be swallowing an error here but if we are very happy to fix!
