### ISSUE TITLE
Model tests aren't very grep-able

### ISSUE THREAD

**Issue by brandonjmckay** [emberjs/data#4555]
A generated model test gets `Unit | Model | ModelName` (at least for mocha), and when grepping for it you can't single out that one test.

The URL for the grep becomes `?grep=Unit | Model | ModelName` which I think ends up just filtering out anything that starts with `Unit` on that description line.

It would be great to change to use something like `Unit/Model/ModelName` as the default blueprint.

**Comment by bmac** [comment]
Sounds like a good change. @brandonjmckay would you have time to open a pr? I think the relevant line is https://github.com/emberjs/data/blob/fec260a38c3f7227ffe17a3af09973ce2718acca/blueprints/model-test/index.js#L13.

**Comment by brandonjmckay** [comment]
I'd like to, but I think the relevant line is [here](https://github.com/ember-cli/ember-cli-test-info/blob/master/index.js#L13) in ember-cli-test-info.

Not sure what the best way to go would be. I imagine we could find a way to make the separator configurable by a consuming app?

**Comment by runspired** [comment]
We've updated our test blueprints to use the lovely new-style tests. See https://github.com/emberjs/data/blob/master/blueprints/model-test/qunit-files/tests/unit/__path__/__test__.js#L4

We generate the friendly test description using an ember-wide helper: https://github.com/emberjs/data/blob/master/blueprints/model-test/index.js#L13

So whatever `ember-cli-test-info` is configured to, we will use :)
