### ISSUE TITLE
Please add refresh method to collection

### ISSUE THREAD

**Issue by OpakAlex** [emberjs/data#4556]
Example:
```
let collection = this.store.query('user', {use_ember: true});
collection.refresh(); // make request to api with same params
```
Will be very nice, like 21 century, not like now 1900 year!

**Comment by locks** [comment]
I advise that next time you make a feature request you refrain from insulting the project maintainers. You may find them more amenable to your suggestion.

**Comment by pangratz** [comment]
This is already possible using `#update()` on the result, see [this ember-twiddle](https://ember-twiddle.com/1d12368f31c5128f946624ce546755c1?fileTreeShown=false&numColumns=2&openFiles=routes.application.js%2Ctemplates.application.hbs) for an example.

@OpakAlex can you point out where you have looked respectively where you would look at in the documentation to find such information? This would be very helpful so this is documented when future developers stumble over this issue. Thank you very much.
