### ISSUE TITLE
RestAdapter is not detecting XHR interrupted  by refresh as an abort

### ISSUE THREAD

**Issue by bryanhickerson** [emberjs/data#4561]
For several months, we have been hitting `Ember Data 0 Payload Empty Content-Type` errors on our production server (Related: http://stackoverflow.com/questions/38983556/ember-data-0-payload-empty-content-type). I can reproduce the error by using Chrome Dev Tools Network throttling and hitting refresh in the middle of an Ember Data related XHR. 

Since this is an abort, I was curious why we were getting this error instead of the abort error seen here: https://github.com/emberjs/data/blob/16cf35db2aa0ddbe28c043570ef6d725139b0c47/addon/adapters/rest.js#L1433. So I logged the `textStatus` while triggering the error and found out that the textStatus was `error` instead of `abort`. 

```
if (responseData.textStatus === 'abort' || jqXHR.status === 0) {
   error = new AbortError();
}
```

Seemingly, if the adapter did the above, this would flag the error correctly. I'm open to writing the PR if this seems like the right approach.

**Comment by bmac** [comment]
I believe this is fixed by your pr in https://github.com/emberjs/data/pull/4567. I've just published the v2.9.0-beta.4 release which includes that fix. Feel free to reopen if its still an issue.
