### ISSUE TITLE
TypeError: Cannot read property 'type' of null 

### ISSUE THREAD

**Issue by bauerjon** [emberjs/data#4568]
If our server json api response includes a model that our ember application does not know about we got a `TypeError: Cannot read property 'type' of null` error.

Would a more desired behavior be to ignore unknown models? Let me know your thoughts, would be happy to help with a fix.
#### Stack trace

```
TypeError: Cannot read property 'type' of null
    at r._pushInternalModel (https://example.com/assets/vendor-ff470fb65f1009ec8ea7bcea14d830f0.js:26:2600)
    at r.push (https://example.com/assets/vendor-ff470fb65f1009ec8ea7bcea14d830f0.js:26:2332)
    at https://example.com/assets/vendor-ff470fb65f1009ec8ea7bcea14d830f0.js:25:23950
    at Object.run (https://example.com/assets/vendor-ff470fb65f1009ec8ea7bcea14d830f0.js:5:11070)
    at r._adapterRun (https://example.com/assets/vendor-ff470fb65f1009ec8ea7bcea14d830f0.js:26:3526)
    at https://example.com/assets/vendor-ff470fb65f1009ec8ea7bcea14d830f0.js:25:23853
    at y (https://example.com/assets/vendor-ff470fb65f1009ec8ea7bcea14d830f0.js:18:26952)
    at b (https://example.com/assets/vendor-ff470fb65f1009ec8ea7bcea14d830f0.js:18:27047)
    at v (https://example.com/assets/vendor-ff470fb65f1009ec8ea7bcea14d830f0.js:18:26855)
    at https://example.com/assets/vendor-ff470fb65f1009ec8ea7bcea14d830f0.js:13:13635
```
#### Versions Reproduced

ember-data: 2.8.1
ember-data: ^2.4.0

**Comment by bmac** [comment]
Hi @bauerjon. Great question. I think the correct behavior for Ember Data would be to log a warning that the model was not found, then ignore the data instead of trying to process it. If you would like to submit a pr to fix this issue that would be great. Let me know if there is any help you need.

**Comment by bauerjon** [comment]
@bmac looking into adding this. I had a couple of questions after looking through the code.

What method would I use to log a warning that would not be stripped out in production build? Are there other use cases in ember data where we log something in production? Or would the desire be that this does not log in production and only in debug? I notice there is a `info` method [here](https://github.com/emberjs/data/blob/master/addon/-private/debug.js#L15-L17), but I can't find the actual implementation of `Ember.info` in Ember. I made the assumption it would be in the [shims](https://github.com/emberjs/ember.js/blob/master/vendor/ember/shims.js). 

Something to note - I see when not in production we are [raising an exception](https://github.com/emberjs/data/blob/master/addon/-private/system/store.js#L2284) explicitly  if we do not recognize the type. Even though this is here for debug, I think that, in production, logging would be better for cases where the server response includes extra associations that the client does not yet need to know about.

**Comment by crhayes** [comment]
I just experienced this error.

I think it makes sense for Ember Data to log an error rather than blowing up, considering the API can change independently of any of its clients.

For instance, an API team deciding to add a new included resource by default should not break the Ember web client application.

**Comment by stefanpenner** [comment]
> I think it makes sense for Ember Data to log an error rather than blowing up

:+1:
