### ISSUE TITLE
Setting `coalesceFindRequests` to true may break testing

### ISSUE THREAD

**Issue by GRardB** [emberjs/data#4569]
Hey!

I ran into a bug recently, which @mixonic helped me with. Essentially, enabling `coalesceFindRequests` caused one of my acceptance tests to hang.

The test:

```
test('', function(assert) {
  // ember-cli-mirage
  server.createList('invitation', 5, {
    accepted: true,
    group: server.create('group'),
    member: this.user,
  });

  visit('/');

  andThen(() => {
    // the test (irrelevant)
  });
});
```

The offending code:

```
afterModel: function(model) {
  if (model) {
    return model.user.get('invitations').then((invitations) => (
      Ember.RSVP.all(
        invitations.map((invitation) => (
          invitation.get('group').then(group => {
            return group.reload(); // makes the test hang
          })
        ))
      )
    ));
  }
},
```

I have a [Twiddle](https://ember-twiddle.com/7e4ee6acc64df223fe4e17f0ebe3b000?openFiles=routes.index.js) which shows the rest of the relevant code (minus the adapter and the test), but I suspect it's not really necessary.

From our email exchange, I'll quote:

> Apparently, when you coalesceFindRequests, the AJAX request isn’t immediately started, thus when the waiter checks it doesn’t see any requests in flight and presumes that things are “settled”. The test is permitted, incorrectly, to continue.

Disabling `coalesceFindRequests` allows the test to run!

At this point, it's probably best for Matthew to chime in with his knowledge and suggestions for how to fix the issue :grin:

**Comment by mixonic** [comment]
@fivetanley we talked about adding a waiter for ember-data separately from this, but it seems `coalesceFindRequests` is another spot where ember-data should be expressing waiting itself instead of relying on the jQuery ajax system.

**Comment by broerse** [comment]
Perhaps it is related to a bug with _findMany See: https://github.com/emberjs/data/issues/4463

**Comment by jalcine** [comment]
Any update on this? Looks like progress stalled on #4463.

**Comment by runspired** [comment]
We've add ed a test-waiter #5422
