### ISSUE TITLE
destroyRecord calls DELETE endpoint on collection 2.4.3

### ISSUE THREAD

**Issue by typeoneerror** [emberjs/data#4570]
Unsure if related to #3688 #4289, but in 2.4.3, I'm seeing the following:

1. Call save() on a record. 
2. Server responds with 422 error. 
3. Then call `destroyRecord` on the record on the unsaved, validated record.
4. a DELETE call is made to api/collections, not api/collections/:id.

**Comment by bmac** [comment]
I suspect this is related to the 2 issues you linked. It looks like the fix for this wasn't bug introduced until 2.5.0. 

@typeoneerror would it be possible for you to update to 2.5.0 or higher and see if that fixes the issue or is there something preventing you from updating beyond 2.4.3?

**Comment by typeoneerror** [comment]
@bmac working on CLI 2.4.3 -> 2.8.0 update and then I will upgrade to latest ember/ed. I think you're right looking at the issues and fixes more thoroughly. You can consider this closed. I'll reopen if I still encounter after upgrade. I just did `this.store.unloadRecord` as a workaround for now.
