### ISSUE TITLE
Could we keep the beta out of latest on npm?

### ISSUE THREAD

**Issue by kitsunde** [emberjs/data#4573]
Hello!

ember-data seems to publish beta relates to npm under latest:

```bash
$ npm view ember-data dist-tags
{ latest: '2.9.0-beta.2', beta: '2.9.0-beta.4' }
``` 

For contrast ember-cli keeps the stable in latest.

```bash
$ npm view ember-cli dist-tags
{ latest: '2.8.0', beta: '2.9.0-beta.2' }
```

Could we avoid doing that since it makes it hard for dependency checkers to figure out what's the latest stable: 

https://github.com/tjunnone/npm-check-updates/issues/285#issuecomment-253027858

**Comment by bmac** [comment]
I've updated the latest tag for Ember Data to be `2.8.1`. Sorry about that @kitsunde. Thanks for reporting the issue.
