### ISSUE TITLE
querying existing record triggers a change in its belongsTo relationships (twiddle included)

### ISSUE THREAD

**Issue by miguelcobain** [emberjs/data#4579]
On ember-data 2.7.0 and above, setting an observer on a `belongsTo` triggers without the relationship actually changing.

Here is the twiddle: https://ember-twiddle.com/e5fb5b69d401ca2187840a771b5d7785?fileTreeShown=false&numColumns=2&openFiles=controllers.application.js%2Ctemplates.application.hbs

When you click "reload", you can see a log on the console which shouldn't happen. The belongs to relationship never changed.
The log only happens if ember-data is set to a version above 2.7.

**Comment by BryanCrotaz** [comment]
Same bug with `hasMany` - there's a todo related to this:
```
// ember-data/.../many-array.js
   flushCanonical: function flushCanonical() {
      //TODO make this smarter, currently its plenty stupid
     ...
     var oldLength = this.length;
      this.arrayContentWillChange(0, this.length, toSet.length);
      // It’s possible the parent side of the relationship may have been unloaded by this point
      if ((0, _emberDataPrivateSystemStoreCommon._objectIsAlive)(this)) {
        this.set('length', toSet.length);
      }
      this.currentState = toSet;
      this.arrayContentDidChange(0, oldLength, this.length);
      //TODO Figure out to notify only on additions and maybe only if unloaded
      this.relationship.notifyHasManyChanged();
      this.record.updateRecordArrays();
```

**Comment by BryanCrotaz** [comment]
See PR #4583 for a fix for this in a `hasMany` - you may be able to use a similar fix for a `belongsTo`

**Comment by wecc** [comment]
PR for `belongsTo` at #4605
