### ISSUE TITLE
[DOC] store.unloadAll() is wrongly documented.

### ISSUE THREAD

**Issue by xaqq** [emberjs/data#4595]
The documentation for `store.unloadAll()` is as follow:

````
This method unloads all records in the store.

Optionally you can pass a type which unload all records for a given type.
````

However, it seems this is wrong. I've ran into the very simple issue with the following code:

````
store.unloadAll('myModel');
store.peekAll('myModel'); // WTF, this returns a non-empty array.
````

Someone on Ember's slack pointed out that `unloadAll()` simply schedule the unload, and that the caller needs to wait until the next run loop for the store to be unloaded. Indeed after testing, this seems to be case.

**Comment by wecc** [comment]
Thanks for reporting @xaqq! Would you like to open a PR adding this information to the docs?
