### ISSUE TITLE
Guard for destroyed objects in promises handlers

### ISSUE THREAD

**Issue by tchak** [emberjs/data#4611]
As @stefanpenner mentioned in this comment https://github.com/emberjs/data/pull/4600#pullrequestreview-4978084 we have a few places where we use `this` inside promises handlers without guarding for `isDestroyed`.

**Comment by pete-the-pete** [comment]
@runspired or @hjdivad, is this still valid?

**Comment by runspired** [comment]
@pete-the-pete no I've completed this. Thanks for the ping :)
