### ISSUE TITLE
Get hasMany#isLoaded loads the relationship

### ISSUE THREAD

**Issue by lcoq** [emberjs/data#4627]
```js
App.Author = DS.Model.extend({
  books: DS.hasMany('book')
});
App.Book = DS.Model.extend({
  title: DS.attr('string')
});
```

Given an `author` loaded from this server response : 

```js
{
  data: {
    id: 1, type: 'authors', 
    attributes: { name: "Mark Twain" }, 
    relationships: { 
      books: { 
        links: { related: "http://foo.bar" }
      }
    }
  }
}
```

Access the `isLoaded` property of the `books` relationships sends the request to `http://foo.bar` : 

```js
this.store.findRecord('author', 1).then(function(author) {
  // the following line triggers the request to "http://foo.bar"
  author.get('books.isLoaded');
});
```

[Here is the JS Bin that demonstrate the issue](http://emberjs.jsbin.com/hulozovapo/1/edit?js,output)

**Comment by sly7-7** [comment]
I think this is expected, but since references are implemented, you can now test `author.hasMany('books').value() === null` to see if the relation is loaded. More info here: http://emberjs.com/api/data/classes/DS.Model.html#method_hasMany

**Comment by pangratz** [comment]
Yep, usin references here is the way to go.

**Comment by lcoq** [comment]
@sly7-7 @pangratz Sorry I did not see this method in the doc, thank you!
