### ISSUE TITLE
has_many relationship with foreign key only in children

### ISSUE THREAD

**Issue by eraleis** [emberjs/data#4628]
I have some trouble with has_many relationship in ember, lets say i want to retrieve the comments attached to a post, i can easily do it if my postgres schema look like this:

**posts:**
    
    {
      id: 1,
      comments: [1, 2, 3]
    }
**comments:**

    {
      id: 3,
      post_id: 1
    }

But what I want is to get rid of the "comments" in posts table, like:

**posts:**

    {
      id: 1
    }
**comments**

    {
      id: 3,
      post_id: 1
    }

So far I haven't found anything that can help me even if it doesn't seem hard, and i don't understand why i need an array of id in the parent table

**Comment by wecc** [comment]
Hi @eraleis, this seem unrelated to Ember Data?

**Comment by eraleis** [comment]
Hi @wecc, Yes you are right, sorry i didn't wanted to post the issue here :/

**Comment by pangratz** [comment]
It's definitely possible to define the relationship on the child only, see [this ember-twiddle](https://ember-twiddle.com/100f34d3930df0570217d85defde9feb?fileTreeShown=false&numColumns=2&openFiles=routes.application.js%2Ctemplates.application.hbs) for an example on how to do that.

If you have further questions, feel free to chime into the `-ember-data` channel in [embercommunity.slack.com](https://embercommunity.slack.com/messages/-ember-data/).
