### ISSUE TITLE
Control over relationship fetch needed

### ISSUE THREAD

**Issue by technomage** [emberjs/data#4634]
We have several cases where traversing a relationship would bring in 10s of k records from a single source record.  We would like to be able to page through a relationship rather than pull in all target objects in one request, and ideally only bring in the first page and later pages if the user actually looks at them.  (Think detail records for a summary, or exploding list of comments for a post, etc).

**Comment by wecc** [comment]
There's currently nothing built-in for paginating collections (and hasMany relationships) in Ember Data. We are working on improving references and links support (see https://github.com/emberjs/rfcs/pull/160) and we're tracking many of these JSON API related features in meta issue #2905.

I'm going to close this in favor of the issues mentioned above to keep duplication to a minimum. Feel free to re-open if I misunderstood the use-case.
