### ISSUE TITLE
hasMany relationship and canonicalState not being flushed?

### ISSUE THREAD

**Issue by jaredgalanis** [emberjs/data#4681]
I’m running Ember 2.8.1 and Ember Data 2.8.0.

I have two models which are related via a hasMany relationship. Sections hasMany Items.

When I create a new section record and set an existing item's relationship to the new section (where the item was related to a previously existing section), that relationship is set correctly and reflected in the ember inspector.

However, when I run ```save();``` on the section that was previously related to that item, the relationship with that item is re-established. I have noticed that before the save the canonicalState of the old section still shows a relationship to the child while the currentState is empty.

I don't know enough about what's happening here to fix this, but I wonder if the canonicalState of the old section needs to be flushed.

Flagging as potentially related to #4507.

**Comment by jaredgalanis** [comment]
So in this image you can see that there are two sections to begin with. The relevant item looks up to section with an id of 109. Then a new section is created (where the id is null as it has no been persisted yet). Also, on creation that new section was set as the section that the item looks up to (again the section's id is null). Then when a save is run on section 109, the originally related section, its relationship to the item is re-established when it should not be. 

![screen shot 2016-11-28 at 7 05 10 am](https://cloud.githubusercontent.com/assets/6305935/20667762/1b2592b0-b539-11e6-90c5-a5d57d47400c.png)

**Comment by sly7-7** [comment]
Could you share the payload send by the server when you save the section 109 ? I ask this to be sure the new relationships are correctly defined.

**Comment by jaredgalanis** [comment]
@sly7-7, sure no prob. Here's the payload, let me know if you need something else.

```{"data":{"id":"109","type":"sections","attributes":{"title":"derpy","requisition_id":43},"relationships":{"items":{"data":[{"id":"44","type":"items"}]}}}}```

**Comment by sly7-7** [comment]
Well, if the related item is the item 44, I think this is legit that the relationship is reverted. Maybe I just don't understand, in that case could you reproduce thé bug in a twiddle ?

**Comment by jaredgalanis** [comment]
Thanks @sly7-7. Sorry, I probably am not being clear. The related item is item 44, but the issue here is that when I set the item's relationship to the newly created section I would expect that the relationship with section 109 would be severed and not reinstated when section 109 is saved. The intention is that the newly created section be the section that item 44 looks up to until I explicitly set another relationship. 

I have been trying to get an ember twiddle going, but I'm having some issues with including ember-cli mirage (which I was assuming I would need since this issue can only be born out while using a backend because the save() is necessary). I'll try again on that today.

**Comment by sly7-7** [comment]
Well, I think that when you save the sections, the server must respond with the expected state for each section. If I'm right this behavior is called the 'single source of truth', which is the server.
To be concrete, in your example, when you save the sections, the server must respond with:
 - The newly created section must have the item 44 in the relationships part of the payload.
 - The section 109 must have no item in the relationships part of the payload.

**Comment by jaredgalanis** [comment]
That makes total sense. After looking at the server return payloads and the server requests I see that it's only on the item save that the item-section relationship is being established server side. When a section is saved the relationship with item is not being sent to the server and thus is not in the payload on the return from the server. Given that I can see that an item is related to the section from the section side, I don't understand why saving that section wouldn't also send the item relationship in the request to the server. Does JSONAPI adapter only send relationship data from the child side of a relationship?

**Comment by sly7-7** [comment]
By default the JSONAPISerializer does not serialize the many side of a one-to-many relationship, but you can override the attrs hash if you want to.
In your example, assuming your ApplicationSerializer is a JSONAPISerializer, you could try something like this

```app/serializers/section.js
import ApplicationSerializer from '<path/to/your/application-serializer>' ;

export default ApplicationSerializer({
  attrs: {
     items: {serialize: true}
  }
})
```

This way, when serializing, [this check](https://github.com/emberjs/data/blob/c9d8212c857ca78218ad98d11621819b38dba98f/addon/serializers/json.js#L890) will be true and your relation will be serialized.

Hope this helps

**Comment by jaredgalanis** [comment]
Thanks for all of your help and patience @sly7-7! It does help indeed, closing this out now.
