### ISSUE TITLE
Ember Data caching BelongsTo records from dropped/reset connections

### ISSUE THREAD

**Issue by Kilowhisky** [emberjs/data#4690]
It appears that when ember data tries to load a belongsTo reference and the connection gets dropped or reset it never re-attempts to load the data upon subsequent requests.  It will always just return a fulfilled promise that has a `null` content.  Also any request to `mymodel.belongsTo('reference').reload()` wont generate a GET request either. 

This appears to be because the `BelongsToRelationship` for the parent model marks the record as 
```
hasData: true,
hasLoaded: true,
inverseRecord: null
```

So when `getRecord()` is called here: https://github.com/emberjs/data/blob/7b452907bc02e6b3d4d4213ca6d6ea32dbb4d20a/addon/-private/system/relationships/belongs-to.js#L118  it immediately resolves with a null promise. When in fact it has failed to load properly to begin with. 

unfortunately because this depends on a dropped internet connection i can't create a twiddle for it.  
To replicate this behavior just create a model with a belogsTo reference (do not make a reflexive relationship) and then make a UI with a button to load it on command and attempt to recover a specific property. Then using a proxy app like fiddler or charles create an automatic responder that responds with a dropped connection or a reset connection. 

![capture3](https://cloud.githubusercontent.com/assets/7075666/20816394/d5d2339e-b7d6-11e6-972a-ca9eef6bd1ba.PNG)

I think there are few possible correct behaviors. 
1. Reject the promise that caused it to load and reject the promise on subsequent calls instead of just fulfilling with `null`.
2. Reject the promise that caused it to load and then reset the reference so it can try again next time. 
2. Reject the promise that caused it to load and and then call the caching adapter methods mentioned in the 1.13 release upon subsequent calls. http://emberjs.com/blog/2015/06/18/ember-data-1-13-released.html
3. Reject the promise that caused it to load and provide a way to ask it to `{reload: true}` just like findRecord.

EDIT:

I should state the following:
* Ember: 2.9.1
* Ember Data: 2.9.0
* Adapter: DS.RestAdapter

**Comment by Kilowhisky** [comment]
Looking into if further it appears that when an error in ajax occurs it calls `unloadRecord` which transitions the record to the state 'root.deleted.saved'. 

https://github.com/emberjs/data/blob/758ebe7991fb6e9d51fa119b08141d48e19f0252/addon/-private/system/store/finders.js#L52
```
 function(error) {
    internalModel.notFound();
    if (internalModel.isEmpty()) {
      internalModel.unloadRecord();
    }
```

**Comment by Subaku** [comment]
I would like to mention that I've run into this issue as well. I'm using Ember-Data 2.11.3 and for me when I try to access a belongsTo relationship that our user does not have permissions to see our server responds with a 404 and a simple error message of "Not found". This puts my record's belongsTo relationship into the same state initially described above with no apparent way to gracefully handle the error or even attempt to reload the relationship. 

Is there anything we can attempt to do for this situation?

**Comment by runspired** [comment]
with the removal of the state machine, the only logic that exists is part of the legacy network handler (which unloads the record if the request fails and various criteria is met). I believe in this case it would unload only if the relationship is `sync`, as for `async` relationships we would retain the identifier as non-releasable. In near-future EmberData relationships and data-fetch simply don't work the same way and we have no need to call unload so the identifier will stick around making this issue moot. For current users, if the relationship is `sync` and errors in this way, the best refactor is to use `links` instead of `id` for knowing what to attempt to fetch.
