### ISSUE TITLE
Accessing a model via a submodel relationship yields an ObjectProxy, not a Model

### ISSUE THREAD

**Issue by lorcan** [emberjs/data#4692]
If we create a parent-child relationship between two models and attempt to access the parent via the child we get what looks like an ObjectProxy, not a Model. This can lead to problems when we need to operate on a parent instance not knowing whether we've received the instance as a Model or an ObjectProxy. Proxying allows us to interact with properties fine but methods or attributes that are defined on Model aren't proxied and can lead us to problems,  e.g., calling `serialize()` on what we think is a Model.

I have [an ember twiddle that demonstrates with an example](https://ember-twiddle.com/0746590ada06e9bbbad42780eb8e5ee3?fileTreeShown=false&openFiles=components.demo-belongsto.js%2Ctemplates.components.demo-belongsto.hbs).

My current workaround is to do something like:
```
if (model.serialize) { 
  model.serialize();
} else {
  model.content.serialize();
}
``` 
which isn't ideal.

Is there a single way to call these functions without having to know whether we have a model or a submodel?

I could avoid the problem if I was accessing a child from a parent by embedding child in parent, but  can't embed child in parent and parent in child.

**Comment by runspired** [comment]
It's on my near term plans to make these objects be as close to if not exactly what you expect them to be instead of proxies.

**Comment by lorcan** [comment]
Sounds great! We'd be happy to help out if there's anything we can do to assist :-)

**Comment by runspired** [comment]
For `async` relationships, use the snapshots or references API for serialization needs.
