### ISSUE TITLE
DS.Errors#add/remove/clear should not be marked as deprecated?

### ISSUE THREAD

**Issue by HeroicEric** [emberjs/data#4694]
As a result of https://github.com/emberjs/data/pull/3853, `DS.Errors#add`, `DS.Errors#remove`, and `DS.Errors#clear` were marked as deprecated but no deprecation was added to the functions. Instead, a warning was added to the functions to make sure the behavior was clear.

I think we need to either

- add deprecations to these functions
- remove the `@deprecated` tags

**Comment by runspired** [comment]
We discussed this recently and I believe we do want to move to deprecate, possibly even go all the way to assertion.

**Comment by runspired** [comment]
Closing as we decided to not pursue a deprecation at this time. The `RecordData Errors` RFC will provide an alternative path to a future without this class.
