### ISSUE TITLE
We should deprecate the (private) modelFactoryFor

### ISSUE THREAD

**Issue by runspired** [emberjs/data#4711]
We largely have it so that in a few places we can warn instead of error when an unknown `type` is encountered by a serializer when normalizing a payload, however I'm fairly certain this will still hard error shortly thereafter in the actual push.

**Comment by pete-the-pete** [comment]
can we create a failing test to prove this?

**Comment by runspired** [comment]
@pete-the-pete probably? I mostly opened this as a reminder to not forget ;)

**Comment by locks** [comment]
RFC~
