### ISSUE TITLE
hasMany resolution will not use related links if any data:[] is present

### ISSUE THREAD

**Issue by rstudner** [emberjs/data#4712]
If I have this json-api response:
```
{
  "data": [
    {
      "type": "expel-alerts",
      "id": "64839987-80d5-4de7-9a74-62d472ba0562",
      "attributes": {
        "detail": "collaborate with collaborators",
        "title": "3 endpoints in Finance domain beaconing to known C2 122.33.52.122",
        "severity": "3",
        "activity-start": "2016-11-23T04:55:45.000Z",
        "activity-end": "2016-11-25T23:55:45.000Z",
        "type": "network"
      },
      "relationships": {
        "vendor-alerts": {
          "data": [
            {
              "type": "vendor-alerts",
              "id": "a91db472-99f7-4a8d-8878-7365e689a346"
            }
          ],
          "links": {
            "self": "/expel-alerts/64839987-80d5-4de7-9a74-62d472ba0562/relationships/vendor-alerts",
            "related": "/expel-alerts/64839987-80d5-4de7-9a74-62d472ba0562/vendor-alerts"
          }
        }
      }
    }
  ],
  "meta": {
    "count": 1
  }
}
```
In the ember inspector if $E is set to the expelAlert model object, , if I do $E.get('vendorAlerts') , ember-data will attempt to do /api/vendor-alerts/a91db472-99f7-4a8d-8878-7365e689a346 to retrieve the vendorAlert model (ignoring the related links entry)

If, the JSONAPI response (for just the relationships area) is:
```
      "relationships": {
        "vendor-alerts": {
          "links": {
            "self": "/expel-alerts/64839987-80d5-4de7-9a74-62d472ba0562/relationships/vendor-alerts",
            "related": "/expel-alerts/64839987-80d5-4de7-9a74-62d472ba0562/vendor-alerts"
          }
        }
      }
```
then $E.get('vendorAlerts') will hit /api/expel-alerts/64839987-80d5-4de7-9a74-62d472ba0562/vendor-alerts  (respecting the related links entry)

I would think(?) it would always prioritize the links entry.  (especially if there were say, 5000 vendor-alerts.. you wouldn't want 5000 individual ajax requests, nor would the coalesce true ?filter[etc]=1,2,...,5000 be right either)

**Comment by runspired** [comment]
Related: https://github.com/emberjs/data/issues/4292#issuecomment-255453415

**Comment by runspired** [comment]
Tangential: https://github.com/emberjs/data/issues/2162
