### ISSUE TITLE
Warnings issued while using feature flags w/o Ember Canary

### ISSUE THREAD

**Issue by HeroicEric** [emberjs/data#4713]
![screen shot 2016-12-13 at 12 24 34 pm](https://cloud.githubusercontent.com/assets/602204/21155946/4965baf2-c131-11e6-92c8-9b687ffa4410.png)

I believe this has something to do with `knownFeatures` at https://github.com/emberjs/ember.js/blob/master/packages/ember-debug/lib/index.js#L182 containing any feature flags that are set in your `EmberENV.FEATURES`:

![screen shot 2016-12-13 at 12 45 44 pm](https://cloud.githubusercontent.com/assets/602204/21156190/1b5ddd0a-c132-11e6-88d4-31e0d97ac9e7.png)

**Comment by runspired** [comment]
@HeroicEric looking at the above, it seems like it is working as intended? E.G. in canary, if feature flag is on, it warns you that you are using it.

**Comment by runspired** [comment]
No longer an issue now that we have our own infra
