### ISSUE TITLE
JSONAPIAdapter sends all properties for PATCH

### ISSUE THREAD

**Issue by wayne-o** [emberjs/data#4721]
I've began using the Json Api Adapter in my app and have a compliant backend running and it's all smooth.

Only issue I have found is that when I update a property on a model and then .save it - i see that all of the properties on that model are sent to the server as a PATCH request. In my understanding this should be limited to the properties that have changed and require an update?

**Comment by wecc** [comment]
Thank for the issue!

Basically ED doesn't yet support dirty relationships - only dirty attributes. That's the reason why we haven't updated the serializer to pass only modified attributes and relationships.

This is being worked on and tracked in #3467 (there are workarounds in that thread)

**Comment by runspired** [comment]
The solution to this now is to use the serialization utils or the cache APIs for changed relationships directly:

e.g. if using JSON:API

```ts
import { serializePatch } from '@ember-data/json-api/request';

const patch = serializePatch(cache, identifier);
```

Or more directly if you want to specifically work with the diffs:

```ts
const  changed = cache.changedRelationships(identifier);
```
