### ISSUE TITLE
Better Docs for Add-On Builders and more API Surface

### ISSUE THREAD

**Issue by RobIsHere** [emberjs/data#4724]
I think Ember Data is one of the best things, i have seen in data/orm/odm/whatever... and now the "but": i have often use cases that are not covered by ED.

It's a pity, that it is hard to develop Add Ons for ED. While I think the greatest thing about Ember.JS itself are the Add Ons. They provide many different solutions for many Use Cases. 

Currently it is very hard to do because:
- many "magic" internals without documentation. High level docs would be enough like call diagrams and data flow maybe.
- the Public API surface is very very limited! I know you have a reason for this, but building something around ED gets harder the fewer "entry points" you have. Maybe a "AddOn"-Semi Public API could help?
- in depth documentation about things like Snapshot, InternalModel, Store internals, Relationship internals (Even if you don't expose API - to build an Add-On, you must know how it works)

My current use case is, that i would like to bypass the store on write and push only responses into it. So the store should always represent what is on the server. And just that. So to build this, i will have a very hard time to figure things out. 

If i made an add-on, it could serve me well in future projects. And even others, if i put it on github. But i can't get an overview of the amount of work that has to be done, to use ED the way i need it.

There are many long standing issues like the rollback story or dirtying, that most likely will not be solved out of the box. So there should be a lot of Add-Ons. But there are only some. And most are pretty simple, more like hacks!

**Comment by runspired** [comment]
Hi @RobIsHere thanks for opening this issue :) 

We'd love to see more contributions, especially from folks willing to dive into the internals and write addons! (Really, there really really should be more addons).

> many "magic" internals without documentation. High level docs would be enough like call diagrams and data flow maybe.

I agree! This would be great :) However, not to discourage, but the reason this doesn't exist is it's literally too complex at the moment to diagram correctly for anything but a very abstract idea of how it works.  That said, I've been [working rapidly through refactoring and cleaning up the internals](https://github.com/emberjs/data/pulls?utf8=%E2%9C%93&q=is%3Apr%20author%3Arunspired) and we are very very close to a data flow story that is more intuitive and definitely easier to explain.  I think you will soon notice that timeline profiles tell a cohesive story about the flow of a query.

For instance, my latest backburner PR leads you to being able to see the following flow:

<img width="1204" alt="screen shot 2016-12-21 at 9 59 09 am" src="https://cloud.githubusercontent.com/assets/650309/21408947/899b85b4-c78c-11e6-9d90-da7d693d33fa.png">

I would be happy to work with you to build a comprehensive flow diagram of how the internals work, especially as they will soon be fairly easy to understand :)

> the Public API surface is very very limited! I know you have a reason for this, but building something around ED gets harder the fewer "entry points" you have. Maybe a "AddOn"-Semi Public API could help?

I agree! However there isn't so much a reason so much as there is a lack of a reason. There's been a lack of solid proposals for what is needed and what to implement.  I've sketched many many ideas for better ED ergonomics out, hoping to land some of them as RFCs, but the refactoring of the internals and performance work has been more important.  I'd be happy to detail some of these out and find a champion for them!

> in depth documentation about things like Snapshot, InternalModel, Store internals, Relationship internals (Even if you don't expose API - to build an Add-On, you must know how it works)

Most things internally are shifting rapidly at the moment, so for anything you find yourself needing or abusing private API for, please open an issue detailing the use case, and hopefully we can iterate towards an RFC and landing a public API to accomplish the things needed by addons.

> My current use case is, that i would like to bypass the store on write and push only responses into it. So the store should always represent what is on the server. And just that. So to build this, i will have a very hard time to figure things out.

Believe it or not, this is trivial to do without using any private API! But that's a conversation best left to DM.

> There are many long standing issues like the rollback story or dirtying, that most likely will not be solved out of the box.

There are (actually) clear paths forward for fixing all these things, but we don't speak publicly enough about why they have not been done and when/how they might be done.

💃

**Comment by RobIsHere** [comment]
I thought on how to start this at christmas days and came to the conclusion that this should be gradually done and extended.

The refactoring is a huge step in the right direction! So i wait for you to finish and start afterwards? That would be good timing, because now I'm working on a project that doesn't use ember.

So i would maybe start a blog or something like this. And when there is enough written up to make a manual from the content of the posts: review it and commit it back / pr to docs as tutorials.

I have to think of this. And also get a better understanding of the ember-data internals. I already now a lot, but didn't dedicate much time on the internals until now.

**Comment by RobIsHere** [comment]
I'm closing this, because I'm stopping to use ember data. The 3 ember data using projects I have are stuck on 2.12 since a long time. I've continued to use ember, but with ember-redux and a redux stack. This has given control back in my hands and additionally I could use very easy and small tools like redux-saga with its testing 'experience'. The productivity has been even better and the headaches for working around ember-data are gone (e.g. undo/rollback implemented in minutes). The migration of my old projects are happening gradually as this is economically efficient, but from 2.12. I won't try to upgrade beyond that version anymore because I've had some very evil surprises in production (e.g. ember-data crashed totally, not even normal buttons worked after getting a 404 from the server).

**Comment by runspired** [comment]
@RobIsHere I would suggest going all the way to 3.1 or 3.3 canary tbqh. There were a lot of issues in between, but we've invested a lot in solving them.

I reopened this because ultimately the model-data RFC is intended to resolve this issue.

**Comment by runspired** [comment]
Closing as we now have much of this documentation and desired features/fixes
