### ISSUE TITLE
Accidental addon overrides

### ISSUE THREAD

**Issue by runspired** [emberjs/data#4725]
There's a known issue with ember-cli where any addon can clobber other addon or app's version of an addon by specifying the addon as a dependency being the "last in". I recently hit this with an addon locking to 2.10 while the app was on 2.12 canary, but it was difficult to spot because the version number printed in the console was still (incorrectly) the canary version (pulled from package.json).  Had I not known the internals code, I would not have spotted this as my issue.

We should ensure we print the correct version number.

@rwjblue also suggested I add a build check to ensure an addon cant clobber the parent app's version of Ember-Data.

**Comment by igorT** [comment]
Do you know how hard it would be to add the anti clobbering assertion? cc @rwjblue

**Comment by runspired** [comment]
@igorT this is actually the infra we just added to emebr-cli-version-checker for highlander checks, I'll be PRing using it to EmberData and helping back port it to 3.12, 3.16 and stable pretty soon :)

**Comment by runspired** [comment]
With proper peer-dependencies now specified (and locked) this is no longer required.
