### ISSUE TITLE
v2.10. `createRecord` errors when payload from server does not have an id

### ISSUE THREAD

**Issue by dustinspecker** [emberjs/data#4735]
It looks like v2.10.0 was supposed to revert this change according to the [release notes](https://github.com/emberjs/data/releases/tag/v2.10.0), but we're receiving this error after updating to 2.10. It looks like https://github.com/emberjs/data/commit/7d7017c44161f30c537bdd50b96c628fcf83298c was merged back in.

If we can provide any more information please let me know.

We're using Ember 2.10.2, Ember CLI 2.10.0, and Ember Data 2.10.0.

**Comment by fivetanley** [comment]
Hi @dustinspecker,

are you using the `primaryKey` field on your serializer? We're running into that on 2.11 as well in that scenario.

**Comment by dustinspecker** [comment]
Hey @fivetanley,

Sorry for the late response. We're not using the `primaryKey` field on our serializer. Have you all found a workaround?

**Comment by runspired** [comment]
We had some trouble with that assertion but eventually got it right. Sorry for the confusion :D
