### ISSUE TITLE
Compat with factoryFor (Ember 2.12ish)

### ISSUE THREAD

**Issue by mixonic** [emberjs/data#4737]
In Ember 2.12 it is likely (pending a go/no-go this week) that `factoryFor` will be new public API. This method on application instances replaces the private `_lookupFactory` API.

* See [the RFC](https://github.com/emberjs/rfcs/blob/master/text/0150-factory-for.md) 
* See [implementation PR in Ember](https://github.com/emberjs/ember.js/pull/14360)

To avoid a deprecation warning, Ember-Data must not call `_lookupFactory` when `factoryFor` is present. For example in these two known locations:

* https://github.com/emberjs/data/blob/a1bac10f3a79c8658cb588f04544e91b1af71456/addon/-private/system/store.js#L2038
* https://github.com/emberjs/data/blob/a1bac10f3a79c8658cb588f04544e91b1af71456/addon/-private/system/store.js#L2111

Additionally, although the class returned by `_lookupFactory` has dependencies injected onto it via `extend`, the `factory.class` value returned by `factoryFor` is the base class without any injections. Where `LookedUpClass.create()` was called before, instead `factory.create()` must be called if injections are desired.

/cc @runspired @chadhietala @rwjblue @stefanpenner

**Comment by bwbuchanan** [comment]
This appears to be resolved by #4743 , so I think this can be closed.
