### ISSUE TITLE
Add a glossary

### ISSUE THREAD

**Issue by hjdivad** [emberjs/data#4751]
There is some inconsistent naming the codebase.  A first step to improving this is writing a clear glossary of objects, states and actions.  It doesn't really need to be complete, it just needs to be some place that has whatever definitive terms exist, and a place where new definitive terms can be added.

cc @igorT

**Comment by runspired** [comment]
Probably still a good idea for this, will help contributors, though it's cleaned up lots over the years.

**Comment by runspired** [comment]
Not super sure we need this anymore as we largely build over public concepts throughout now that InternalModel is gone. We probably could do with some better docs on a few things, which is already in progress, but doesn't need tracked by this.
