### ISSUE TITLE
Check use of `internalModel.record`

### ISSUE THREAD

**Issue by hjdivad** [emberjs/data#4756]
`IntenalModel` has a `get record` as well as a `getRecord` which is a bit confusing.

Likely we can remove the getter and replace it with `InternalModel.hasRecord` but this remains to be verified.

**Comment by esbanarango** [comment]
Hello @hjdivad, I'm trying to tackle this issue but I don't really understand why you suggest to replace it with `InternalModel.hasRecord`? `get record` will return `this._record` but `hasRecord` will return a boolean.
