### ISSUE TITLE
Improve internalmodel gc bfs to be one pass instead of two

### ISSUE THREAD

**Issue by hjdivad** [emberjs/data#4757]
InternalModel calls `this._allRelatedInternalModels()` and then passes that to `areAllModelsUnloaded`.  These two iterations of the relationship graph can be consolidated into one.

**Comment by fivetanley** [comment]
I'm removing the "good for new contributors" label, there's not enough detail here.

**Comment by runspired** [comment]
we still do somewhat a double pass here but we've mostly killed off the need for the GC sweep and will soon run a single sweep only for the graph killing off the remnants of this entirely. I think we can close this as the implementation is significantly different at this point.
