### ISSUE TITLE
Observer of hasMany on model not firing after upgrade to 2.11.0

### ISSUE THREAD

**Issue by eddiesholl** [emberjs/data#4759]
We have recently done an upgrade of ember cli and ember data. We have noticed a problem that can reliably be toggled by switching between 2.10.0 and 2.11.0 of ember-data.

We have a model with a hasMany child (lets call it 'comments'), and an observer property on 'comments.length'. We use this observer to regenerate some metadata stored on the parent model, when child models are first instantiated, then as they come and go.

In 2.11.0, the observer is not fired, either at startup or on changing the array.  It can be worked around by adding an .on('init') to the observer property. I am aware that there has always been a rule of thumb in ember that computed properties aren't 'live' if they aren't referenced in a template for example, but I don't see how that logic would make sense for observers.

Half of the commits in 2.11.0 are performance fixes that sound like just the sort of thing that might have 'broken' this scenario. Is there anything obviously wrong with an observer on the length of a hasMany child?

**Comment by stefanpenner** [comment]
> I am aware that there has always been a rule of thumb in ember that computed properties aren't 'live' if they aren't referenced in a template for example, but I don't see how that logic would make sense for observers.

This is in-fact true, and the rule was specifically added to prevent observing a property from having a side-affect.

It would be really unfortunately, if observing an async relationship invoked an ajax request for example.

--

As described this doesn't sound like regression rather a bugfix.

**Comment by eddiesholl** [comment]
Hmm OK that sounds like what I was expecting. When you say the rule was added, is that cracking down on side effects in ember in general, or restricted to models and ember-data?

This is unfortunately one of those occasions where replacing observers and side effects with a strict computed approach is just really difficult to achieve. We're doing some funky dynamic property stuff at runtime using names of child models, to 'flatten out' objects and display them in a grid.

I'm also trying to work out if the workaround of invoking the observer on init gets us back to our previous position. I know this triggers an initial calculation at least, I probably need to build a test to check for follow up runs. For now, we're sitting on 2.10.0.

**Comment by runspired** [comment]
> When you say the rule was added, is that cracking down on side effects in ember in general, or restricted to models and ember-data?

@eddiesholl neither, before `hasMany` was accidentally "overly noisy". Generally a key on an object is only considered dirty when the value it references changes; however, we were notifying the key that it was dirty despite it being a stable array whenever we changed any content in the internal array (this dirties `.[]` or `.length` but should not dirty the key itself as the array is still the same reference).

**Comment by runspired** [comment]
@wecc this should be closed as a `wontfix`

**Comment by Kerrick** [comment]
Isn't the whole point of an observer to have side-effects? This broke our production application in a real way when we tried updating Ember Data.
