### ISSUE TITLE
Docs missing for preload option for findRecord

### ISSUE THREAD

**Issue by GCheung55** [emberjs/data#4761]
Docs for the `preload` is missing for [`findRecord`](https://github.com/emberjs/data/blob/6d96eda226f15738b23032bc25c009e081070359/addon/-private/system/store.js#L672).

Docs for `preload` was added for `find` and `findById` with https://github.com/emberjs/data/pull/2198. I understand that `find` and `findById` are deprecated.

Is it just missing or was it intentionally left out?

**Comment by bmac** [comment]
Looks like this is an oversite @GCheung55. Would you have time to open a pr adding the missing documentation to the findRecord doc block?

**Comment by GCheung55** [comment]
@bmac Sure!
