### ISSUE TITLE
How to extend DS.Store.extend in ember-cli 2.10.0 and ember-data 2.11.0 ?

### ISSUE THREAD

**Issue by vinothwindows47** [emberjs/data#4768]
@bmac @cdoornink @fivetanley

**Comment by bmac** [comment]
You should be able to extend the store by defining a file in `app/services/store.js` that looks like this:
```js
// app/services/store.js
import DS from 'ember-data';

export default DS.Store.extend({
  // ...
});
```

**Comment by vinothwindows47** [comment]
@bmac But this is not working for me . If I create `app/services/store.js` like this ,


      // app/services/store.js

     import DS from 'ember-data';
     export default DS.Store.extend({
          _metadataFor: function() {
                console.log('calling metadataFor .....');
           }
      });


When I am going to call this store function in controller like this,

     export default Em.Controller.extend({

           actions: {
              callStore: function() {
                      this.store._metadataFor();
             }
         }
      });

Always throws exception like this

`this.store._metadataFor method is not defined .` . What can I do for this ? Please give suggestion or give demo project code using extending DS.store .

**Comment by pangratz** [comment]
@vinothwindows47 this should work, see this [this ember-twiddle](https://ember-twiddle.com/cd3a4ef3d307f3086fd8f85908cae808?fileTreeShown=false&numColumns=2&openFiles=controllers.application.js%2Ctemplates.application.hbs). What versions are you using?

Can you take a look and spot any differences to they way you're doing it in your app? A repo reproducing the issue you're having would greatly help in tracking down the problem.

**Comment by pangratz** [comment]
I've created https://github.com/pangratz/extend-store-test and cannot reproduce using ember-cli 2.10 and ember-data 2.11.

I am gonna close this as it seems that it's working as expected. Feel free to reopen if you still run into the issue. Also, checkout the #-ember-data channel on http://embercommunity.slack.com for further assistance. Thanks!

**Comment by MalayaliRobz** [comment]
@vinothwindows47 try DS.Store.Service.extend
