### ISSUE TITLE
Unloaded records reappearing in hasMany relationships after query.

### ISSUE THREAD

**Issue by sgargan** [emberjs/data#4773]
Since the 2.11 release we've been seeing duplication of entries in hasMany relationships when records are unloaded via the store and reloaded via a query. We use this unload/requery pattern in a number of places in our app to avoid displaying data that may have been deleted by another concurrent session.  

Since 2.11 when records are returned in query results after being unloaded, their ids are duplicated in any in hasMany relationship that contained them.

I've put together a [twiddle](https://ember-twiddle.com/0e329424ec7880edbf3923cc4c5c38bd?openFiles=routes.application.js%2C) that illustrates this. 

This may be related to how we return the relationship information as we only return the inverse of the relationship i.e. in the example each folder contains it's parents id. When the child ids are specified explicitly the duplication does not occur.

This may well be related to https://github.com/emberjs/data/issues/4770.

**Comment by sgargan** [comment]
Dug into this a little further and from what I can tell the canonical state of the relationship is not being properly cleared when the records are unloaded.

**Comment by runspired** [comment]
A bug fix for this is forthcoming.

**Comment by JoshSmith** [comment]
Is this at all related to #4786 @runspired?

**Comment by runspired** [comment]
Fixed by #4791 and #4792 with a failing test committed by #4790

**Comment by bmac** [comment]
This is fixed by https://github.com/emberjs/data/pull/4791 and the fix was published in the Ember Data 2.11.1 release. I'm going to close this issue now but please let me know if you are still experiencing a problem.

**Comment by JoshSmith** [comment]
🙌

**Comment by arian-kh** [comment]
Hi there, we're experiencing the same issue on 2.13. Is it possible it was reintroduced at some point?

**Comment by xn** [comment]
Confirmed. Rolling back to `2.12.2` fixes it for me.

**Comment by xn** [comment]
@bmac should we open a new issue?
