### ISSUE TITLE
Error when has many relationship data is null from pushPayload

### ISSUE THREAD

**Issue by rlivsey** [emberjs/data#4787]
I'm pushing a payload which contains null as the value of one of the relationships in the sideloaded models:

```json
    {
      "id": "cbd0b810-e6d5-11e6-a487-efa75a311b77",
      "type": "meeting/poll/slot",
      "attributes": {
        "startAt": "2017-01-30T10:20:37.288Z",
        "duration": 60
      },
      "relationships": {
        "poll": {
          "data": {
            "type": "meeting/poll",
            "id": "cbc53bde-e6d5-11e6-a487-7bf9b149a688"
          }
        },
        "responses": {
          "data": null
        }
      }
    },
```

That's producing the following error:

```
TypeError: Cannot read property 'length' of undefined
    at ManyRelationship.computeChanges (has-many.js:208)
    at ManyRelationship.updateRecordsFromAdapter (relationship.js:289)
    at ManyRelationship.updateData (has-many.js:295)
    at ManyRelationship.push (relationship.js:347)
    at store.js:2462
    at model.js:1408
    at cb (ember.debug.js:19269)
    at OrderedSet.forEach (ember.debug.js:19070)
    at Map.forEach (ember.debug.js:19273)
    at Function.eachRelationship (model.js:1407)
```

<img width="696" alt="screen shot 2017-02-01 at 07 17 45" src="https://cloud.githubusercontent.com/assets/3740/22498201/c5168264-e84e-11e6-9359-37449512d2a2.png">

There appears to be a check for `undefined` but in this case it's `null` so it gets through:

<img width="741" alt="screen shot 2017-02-01 at 07 18 04" src="https://cloud.githubusercontent.com/assets/3740/22498206/cca11634-e84e-11e6-9cbb-4d0ef4a61899.png">

**Comment by rlivsey** [comment]
Ah, it looks like this might be invalid JSON, the spec says it should be `[]` for empty hasMany resources:

http://jsonapi.org/format/#document-resource-object-linkage

I'll dig into the [JSONAPI library we're using](https://github.com/vt-elixir/ja_serializer) and see if there's a bug there.

Wonder if it's possible to throw a nicer error here, but feel free to close!

**Comment by rlivsey** [comment]
Closing this as it's not a bug :)

**Comment by alexmiddeleer** [comment]
Just to help future googlers, this caused some of our tests to fail when we upgraded ember data to 2.13. There was some broken code creating mirage records with `null` for relationships, as described above (switching `null` to `[]` fixed it).
