### ISSUE TITLE
No Error event triggered when server is completely offline

### ISSUE THREAD

**Issue by masterX244** [emberjs/data#4788]
When for some reason the server is unreachable (for example shut down or crashed completely) any request done via RESTAdapter doesnt cause a error event of any type to happen

**Comment by bmac** [comment]
Hi @masterX244. I was unable to reproduce this issue. Normally you can see errors from the rest adapter by using the `catch((error) => {...})` method on the promise returned from the store's `findRecord`, `findAll`, or `query` API or the `save()` method on a record.

Here is the ember twiddle I used to try to reproduce this issue.
https://ember-twiddle.com/f9a73141522b687c99192e4f56fe9648?openFiles=templates.application-error.hbs%2C

**Comment by runspired** [comment]
Also could not reproduce this.
