### ISSUE TITLE
Automatic discovery of inverse relationships introduces unnoticed data loss

### ISSUE THREAD

**Issue by RobIsHere** [emberjs/data#4793]
I just ended a 4 hour debugging session for a change that should have taken 10 minutes.

The automatic discovery of relationship inverses made a totally wrong assumption of an inverse relationship. So loading the other end of the relationship in the model hook caused a change to the belongsTo on the other model.

So everytime i have selected a value in the checkbox, then closed the dialog and reopened it I wondered about why the hell this relationship changed!

I already had this similar case two times and I'm really worried about my data integrity! If some unnoticed wrong inverse changes a model on load of the other relationship end, my data would be seriously broken!

Is there a way to completely disable this? Like { inverse: null } on every relationship as default? I want to specify inverses explicitly with { inverse: ... }. Then I know what I have in my model layer is right.

**Comment by bmac** [comment]
I'll make sure to bring this up in the next Ember Data team meeting. FWIW I've also spent way too much time debugging counter intuitive behavior that happens when Ember Data assumes a 1 to 1 relationship that doesn't exist in the real data model.

**Comment by iirving** [comment]
as per issue #4797

**Comment by runspired** [comment]
I've tightened the error checking: https://github.com/emberjs/data/pull/5261

**Comment by runspired** [comment]
I believe we now assert every situation in which there was a potential conflict, ambiguity, or a missing inverse for a relationship, so I am closing this.
