### ISSUE TITLE
trouble accessing 'some' async data

### ISSUE THREAD

**Issue by iirving** [emberjs/data#4797]
this is with "ember-data": "~2.11.1"

I've got a channel model which includes 'outputs' 
```javascript
  outputs: DS.hasMany('output', {
    async: true
  }),
```
and the output model includes 'identity'
```javascript
  channel: DS.belongsTo('channel'),
  identity: DS.belongsTo('identity', {
    async: true
  }),
```

in the route of the output (which is below the channel), i doing this in the model 
```javascript
  model() {
    let channel = this.modelFor('channel').channel
    let outputs = channel.get('output')
    return Ember.RSVP.hash({
      channel: channel,
      outputs: outputs
    })
}
```
and that is letting me see all the outputs the belong to the channel, as expected.

where I am having a problem is the identities belonging to an output.  
 
now the identities can be shared by the outputs, so for example an identity might be 'youtube' and there might be 3 outputs with the same  'youtube' identity

what I'm seeing is that the one of those outputs has the 'youtube' identity details but the other 2 outputs are seeing .get('identity') to be null.

Have i set model or model hook incorrectly? Or is it doing something to stop me from retrieving the identities again (some kind of caching?)

Help!

**Comment by iirving** [comment]
I'm thinking that I've found an edge case on the belongsTo and async the resulting  in only applying the  "included" data is only be applied once to the records it belongs to (maybe doing a find rather than a find all?) (i've been unable find in the ember-data code)

Here's is some more data (with 2 identities, one twitch and one facebook)

this api call
GET /api/v1/channels/812bcff3-1c7f-4f3c-ae79-9641f2dddf5c/outputs?include=identity 

results

{
  "data": [
    {
      "id": "fb1a95cb-12d1-48d6-93e0-8a210b90b308",
      "type": "outputs",
      "links": {
        "self": "http://192.168.2.21/api/v1/outputs/fb1a95cb-12d1-48d6-93e0-8a210b90b308"
      },
      "attributes": {
        "name": "test",
        "description": "",
        "service": "rtmp",
        "custom-public-url": null,
        "custom-stream-url": "test",
        "custom-stream-key": "test",
        "current-ingester-id": null,
        "feed-type": null,
        "feed-item": null,
        "created-at": "2017-02-07T18:02:16Z",
        "updated-at": "2017-02-07T18:02:16Z"
      },
      "relationships": {
        "channel": {
          "links": {
            "self": "http://192.168.2.21/api/v1/outputs/fb1a95cb-12d1-48d6-93e0-8a210b90b308/relationships/channel",
            "related": "http://192.168.2.21/api/v1/outputs/fb1a95cb-12d1-48d6-93e0-8a210b90b308/channel"
          }
        },
        "identity": {
          "links": {
            "self": "http://192.168.2.21/api/v1/outputs/fb1a95cb-12d1-48d6-93e0-8a210b90b308/relationships/identity",
            "related": "http://192.168.2.21/api/v1/outputs/fb1a95cb-12d1-48d6-93e0-8a210b90b308/identity"
          },
          "data": null
        }
      },
      "meta": {
        "last-updated-at": "2017-02-07T18:02:16Z"
      }
    },
    {
      "id": "740632e5-50fe-4b27-8921-5a29d534770b",
      "type": "outputs",
      "links": {
        "self": "http://192.168.2.21/api/v1/outputs/740632e5-50fe-4b27-8921-5a29d534770b"
      },
      "attributes": {
        "name": null,
        "description": null,
        "service": "facebook",
        "custom-public-url": null,
        "custom-stream-url": null,
        "custom-stream-key": null,
        "current-ingester-id": null,
        "feed-type": "groups",
        "feed-item": "107224486397911",
        "created-at": "2017-02-07T23:43:29Z",
        "updated-at": "2017-02-07T23:43:29Z"
      },
      "relationships": {
        "channel": {
          "links": {
            "self": "http://192.168.2.21/api/v1/outputs/740632e5-50fe-4b27-8921-5a29d534770b/relationships/channel",
            "related": "http://192.168.2.21/api/v1/outputs/740632e5-50fe-4b27-8921-5a29d534770b/channel"
          }
        },
        "identity": {
          "links": {
            "self": "http://192.168.2.21/api/v1/outputs/740632e5-50fe-4b27-8921-5a29d534770b/relationships/identity",
            "related": "http://192.168.2.21/api/v1/outputs/740632e5-50fe-4b27-8921-5a29d534770b/identity"
          },
          "data": {
            "type": "identities",
            "id": "c2782eeb-977c-4ff4-bbef-e62228e52e9f"
          }
        }
      },
      "meta": {
        "last-updated-at": "2017-02-07T23:43:29Z"
      }
    },
    {
      "id": "770459e7-bcbe-4b90-a598-a9b56dcffdda",
      "type": "outputs",
      "links": {
        "self": "http://192.168.2.21/api/v1/outputs/770459e7-bcbe-4b90-a598-a9b56dcffdda"
      },
      "attributes": {
        "name": null,
        "description": null,
        "service": "facebook",
        "custom-public-url": null,
        "custom-stream-url": null,
        "custom-stream-key": null,
        "current-ingester-id": null,
        "feed-type": "pages",
        "feed-item": "113438555355493",
        "created-at": "2017-02-07T23:46:30Z",
        "updated-at": "2017-02-07T23:46:30Z"
      },
      "relationships": {
        "channel": {
          "links": {
            "self": "http://192.168.2.21/api/v1/outputs/770459e7-bcbe-4b90-a598-a9b56dcffdda/relationships/channel",
            "related": "http://192.168.2.21/api/v1/outputs/770459e7-bcbe-4b90-a598-a9b56dcffdda/channel"
          }
        },
        "identity": {
          "links": {
            "self": "http://192.168.2.21/api/v1/outputs/770459e7-bcbe-4b90-a598-a9b56dcffdda/relationships/identity",
            "related": "http://192.168.2.21/api/v1/outputs/770459e7-bcbe-4b90-a598-a9b56dcffdda/identity"
          },
          "data": {
            "type": "identities",
            "id": "c2782eeb-977c-4ff4-bbef-e62228e52e9f"
          }
        }
      },
      "meta": {
        "last-updated-at": "2017-02-07T23:46:30Z"
      }
    },
    {
      "id": "63856e57-cd6f-4aeb-837c-881843ad069e",
      "type": "outputs",
      "links": {
        "self": "http://192.168.2.21/api/v1/outputs/63856e57-cd6f-4aeb-837c-881843ad069e"
      },
      "attributes": {
        "name": null,
        "description": null,
        "service": "facebook",
        "custom-public-url": null,
        "custom-stream-url": null,
        "custom-stream-key": null,
        "current-ingester-id": null,
        "feed-type": "groups",
        "feed-item": "306461036370067",
        "created-at": "2017-02-03T21:26:22Z",
        "updated-at": "2017-02-03T21:26:22Z"
      },
      "relationships": {
        "channel": {
          "links": {
            "self": "http://192.168.2.21/api/v1/outputs/63856e57-cd6f-4aeb-837c-881843ad069e/relationships/channel",
            "related": "http://192.168.2.21/api/v1/outputs/63856e57-cd6f-4aeb-837c-881843ad069e/channel"
          }
        },
        "identity": {
          "links": {
            "self": "http://192.168.2.21/api/v1/outputs/63856e57-cd6f-4aeb-837c-881843ad069e/relationships/identity",
            "related": "http://192.168.2.21/api/v1/outputs/63856e57-cd6f-4aeb-837c-881843ad069e/identity"
          },
          "data": {
            "type": "identities",
            "id": "c2782eeb-977c-4ff4-bbef-e62228e52e9f"
          }
        }
      },
      "meta": {
        "last-updated-at": "2017-02-03T21:26:22Z"
      }
    },
    {
      "id": "0e03cb70-392d-42a0-ba5b-e3aab281e719",
      "type": "outputs",
      "links": {
        "self": "http://192.168.2.21/api/v1/outputs/0e03cb70-392d-42a0-ba5b-e3aab281e719"
      },
      "attributes": {
        "name": null,
        "description": null,
        "service": "twitch",
        "custom-public-url": null,
        "custom-stream-url": null,
        "custom-stream-key": null,
        "current-ingester-id": null,
        "feed-type": null,
        "feed-item": null,
        "created-at": "2017-02-03T22:07:52Z",
        "updated-at": "2017-02-03T22:07:52Z"
      },
      "relationships": {
        "channel": {
          "links": {
            "self": "http://192.168.2.21/api/v1/outputs/0e03cb70-392d-42a0-ba5b-e3aab281e719/relationships/channel",
            "related": "http://192.168.2.21/api/v1/outputs/0e03cb70-392d-42a0-ba5b-e3aab281e719/channel"
          }
        },
        "identity": {
          "links": {
            "self": "http://192.168.2.21/api/v1/outputs/0e03cb70-392d-42a0-ba5b-e3aab281e719/relationships/identity",
            "related": "http://192.168.2.21/api/v1/outputs/0e03cb70-392d-42a0-ba5b-e3aab281e719/identity"
          },
          "data": {
            "type": "identities",
            "id": "935cbb63-6fcc-44fd-9663-10c5797d57ea"
          }
        }
      },
      "meta": {
        "last-updated-at": "2017-02-03T22:07:52Z"
      }
    }
  ],
  "included": [
    {
      "id": "c2782eeb-977c-4ff4-bbef-e62228e52e9f",
      "type": "identities",
      "links": {
        "self": "http://192.168.2.21/api/v1/identities/c2782eeb-977c-4ff4-bbef-e62228e52e9f"
      },
      "attributes": {
        "provider": "facebook",
        "name": "Ian Irving",
        "service-name": "Facebook",
        "service-options": [
          {
            "id": "user",
            "name": "My Feed"
          },
          {
            "id": "events",
            "name": "Events",
            "items": []
          },
          {
            "id": "groups",
            "name": "Groups",
            "items": [
              {
                "id": "107224486397911",
                "name": "Connected Thinking Demos"
              },
              {
                "id": "306461036370067",
                "name": "Testing Groups I can see (secert)"
              }
            ]
          },
          {
            "id": "pages",
            "name": "Pages",
            "items": [
              {
                "id": "113438555355493",
                "name": "Connected Thinking"
              }
            ]
          }
        ]
      },
      "relationships": {
        "user": {
          "links": {
            "self": "http://192.168.2.21/api/v1/identities/c2782eeb-977c-4ff4-bbef-e62228e52e9f/relationships/user",
            "related": "http://192.168.2.21/api/v1/identities/c2782eeb-977c-4ff4-bbef-e62228e52e9f/user"
          }
        }
      },
      "meta": {
        "last-updated-at": "2016-12-01T18:25:15Z"
      }
    },
    {
      "id": "935cbb63-6fcc-44fd-9663-10c5797d57ea",
      "type": "identities",
      "links": {
        "self": "http://192.168.2.21/api/v1/identities/935cbb63-6fcc-44fd-9663-10c5797d57ea"
      },
      "attributes": {
        "provider": "twitch",
        "name": "falsepositivesto",
        "service-name": "Twitch",
        "service-options": []
      },
      "relationships": {
        "user": {
          "links": {
            "self": "http://192.168.2.21/api/v1/identities/935cbb63-6fcc-44fd-9663-10c5797d57ea/relationships/user",
            "related": "http://192.168.2.21/api/v1/identities/935cbb63-6fcc-44fd-9663-10c5797d57ea/user"
          }
        }
      },
      "meta": {
        "last-updated-at": "2017-01-16T22:51:04Z"
      }
    }
  ]
}

**Comment by bmac** [comment]
@iirving It sounds like you've run into a case here where Ember Data is incorrectly inferring an inverse relationship. Usually when this happens Ember Data assumes there is a 1 to 1 relationship somewhere that doesn't actually exist. When Ember Data tries to keep this inverse relationship in sync it will often set other conflicting relationships to null. 

To fix this you can explicitly tell Ember Data there is no inverse relationship by using `inverse: null`.

I suspect adding this to your output model will fix your issue. 
```js
  channel: DS.belongsTo('channel'),
  identity: DS.belongsTo('identity', {
    async: true,
    inverse: null,
  }),
```

**Comment by iirving** [comment]
that looks like that has resolved the issue.  I'm slowly undoing some of the hideous workarounds, but it is looking good.

I guess it would be  nice if some future Ember Data did not need to be explicitly told there is no 1 to 1 relationship.

I'll close this issue for now.

**Comment by runspired** [comment]
We've improved our assertions to catch these situations now :)
