### ISSUE TITLE
Batch populateLiveRecordArray records

### ISSUE THREAD

**Issue by jlami** [emberjs/data#4803]
Hi,

I was wondering why the `populateLiveRecordArray` functions passes new items to `_addInternalModelToRecordArray` (and thus also to the event listeners of the array) one by one, instead of batching them first, and then sending them in one or at least in bigger batches.
This could probably speed up some event listeners if they would not have to be called as often.

**Comment by runspired** [comment]
We do batch at a different level, however I think you are specifically referring to using array observers? Can you confirm that?

**Comment by jlami** [comment]
I think we can close this one. I'm afraid it is the product of trying to profile some code that I had not such a good grasp of at the time. Looking at a snapshot of `populateLiveRecordArray` at the time of creating this issue makes me believe I might have made some incorrect conclusions at the time.

But thanks for taking the time to look into this old issue non the less!

**Comment by runspired** [comment]
Thanks for the follow up!
