### ISSUE TITLE
pushPayload does not change hasMany relationship when going to empty state

### ISSUE THREAD

**Issue by danielspaniel** [emberjs/data#4804]
I have a model which hasMany things, then I pushPayload with data that says .. I have no things anymore.  Ember data ignores that and keeps the hasMany things. 

The key activities are that:
 -  I have a model with no things
 -  then I set some things  model.set('things',  things)
 -  then I pushPayload to remove them. 

Here is a twiddle to show the problem:

https://ember-twiddle.com/26204b7fa7fc185dde464418cd33df95?openFiles=routes.application.js%2C

**Comment by hjdivad** [comment]
@danielspaniel https://ember-twiddle.com/53d305379774c4756d576107c98ae6d4?openFiles=routes.application.js%2C

In the above gist you can comment / uncomment line 48 (ie the `this.store.pushPayload` line) to see things either cleared or not cleared.

There are two changes as compared to your original twiddle.

1. the initial relationships data is populated, the relationships are not merely sieloaded in the included payload
2. the manyarray itself is used and not overwritten by the live array from `peekAll` (ie the `person.set('things', things)` line is commented).


Please let me know if I have misunderstood the issue your twiddle aimed to highlight, but I believe the core error in the above was in the payload and not an ember data bug.

**Comment by runspired** [comment]
The issue with the first twiddle is that the relationship is being added as "dirty state", it won't be cleared because no save attempt has been made (so obviously a server update would not know about it).

**Comment by danielspaniel** [comment]
The reason I flag this as a bug is because even in a dirty state if you pushPayload with values for the hasMany then the relationship will update itself to add those new rows. 
By your logic in a dirty state pushing data to a model would always have no affect.

**Comment by Exelord** [comment]
Any news here?

**Comment by Dirk-27** [comment]
I ran into the same issue with ember-data Version 3.8: empty relationship arrays in the payload didn't clear the relationship. What is the state of this issue?

**Comment by wuarmin** [comment]
I have the same issue

**Comment by runspired** [comment]
@Dirk-27 the state of this issue is there is nothing more we can do for `push` api's. It is equally incorrect to discard local mutations as it is to not discard them: it just boils down to what your app wants.

While not explicitly enabled by the new cache design in emberjs/rfcs#854 once `@ember-data/graph` is made public rollback will be a public API. Custom cache implementations can also choose today to do one behavior vs the other.

**Comment by runspired** [comment]
Also closing this as at this point this request is more about relationship-rollback than it is about updating the state. The store forking behavior introduced in emberjs/rfcs#854 allows applications to better choose whether to display remote or mutated state as desired, so rollback and this issue are dead artifacts of a previous era of APIs.
