### ISSUE TITLE
Deprecate partial support for sparse to-many arrays?

### ISSUE THREAD

**Issue by hjdivad** [emberjs/data#4819]
It is possible to populate relationships on one side and have the data available immediately on the other side.  In cases where the inverse fully specifies the data, this seems reasonable, as when the many side is populated and we ask for the one side ([see test](https://github.com/emberjs/data/blob/master/tests/integration/relationships/one-to-many-test.js#L92-L123)).

What seems very strange is we do this even when the relationship is *not* fully specified. ([see test](https://github.com/emberjs/data/blob/master/tests/integration/relationships/one-to-many-test.js#L125-L160))

if a user has many messages and we do the following

```js
// message:2 belongs to user:1
store.push({
  data: {
    id: '2',
    type: 'message',
    attributes: {
      title: 'EmberFest was great'
    },
    relationships: {
      user: {
        data: {
          id: '1',
          type: 'user'
        }
      }
    }
  }
});

// this payload is silent about user:1's relationships
let user = store.push({
  data: {
    id: '1',
    type: 'user',
    attributes: {
      name: 'Stanley'
    }
  }
})

// we cannot possibly know this
user.get('messages.length') === 1;
```
([see twiddle](https://ember-twiddle.com/741fef38937ec8f8bfe0fbb6c8011aec?openFiles=templates.application.hbs%2C))

If we have populated the inverse of a to-many side, we cannot say things like "how many items are in this relationship".  We *could* say "how many items have we loaded locally" but those aren't the semantics of `record.get('hasManyRelationship.length')`.

I do think having support for sparse to-many relationships would be excellent, but until we have that support this behaviour of Ember-Data feels like a footgun.  If people haven't been shot too much by it, I suspect it's mainly because they tend to specify `relationships` on both sides of their relationship.

**Comment by hjdivad** [comment]
Thoughts about changing this behaviour?  Deprecating it, or dropping it & considering the change a bugfix?  Are there good reasons for preferring the current behaviour?

**Comment by hjdivad** [comment]
cc @stefanpenner @igorT @runspired

**Comment by runspired** [comment]
The recent refactor for `links` support added flags that help just this case, and added a codepath for loading to ensure we are in the right state. We won't consider ourselves loaded in this scenario and would attempt to fetch.

That said, I'm not super convinced that `length` referring to anything more than `local data available` is correct. If folks want access to a `total`, especially for unloaded data, I'm of the mind that they should pass `meta` for the relationship and access `total` from it.

**Comment by igorT** [comment]
This seems fine for the sync relationships. For the async, we should not leak length before the initial fetch. Let's write a test to make sure we don't.

**Comment by runspired** [comment]
We will now always fetch if there is a link and no own-membership-data (e.g.  not partial) or any unfetched membership data.
