### ISSUE TITLE
async hasMany leaks ManyPromiseProxy arrayObservers

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/data#4826]
https://github.com/emberjs/data/blob/master/addon/-private/system/relationships/state/has-many.js#L209-L213 ultimately attaches an array observer to the underlying manyArray but is never cleanedup. This means, when a async hasMany relationship is dirtied, the next `get` will create a new `PromiseManyArray` without dissociated the previous ones arrayObservers.

Either we cleanup the old PromiseManyArray, or we have to produce a fresh ManyArray. Otherwise the stable ManyArray will have an ever growing number of listeners from the new PromiseMany arrays being created.

**Comment by BryanCrotaz** [comment]
Demonstration at
[https://github.com/BryanCrotaz/ember-memory-leak](https://github.com/BryanCrotaz/ember-memory-leak)

Route uses peekAll to get all posts from the store. Controller impersonates some sort of server polling by repeatedly pushing jsonapi data into the store.

The key is that we're overwriting the comments hasMany by doing this.

Put a console log in ember.debug.js at the end of the `matchingListeners` method and 
```
if (result.length > 3) {
  console.log(result.length);
}
```
What you'll see is an extra 6 elements in the array every time the posts are pushed to the store.

@stefanpenner this is what we spoke about on Slack, but a much simpler reproduction

**Comment by BryanCrotaz** [comment]
The below code in has-many.js fixes the leak

```
export default function hasMany(type, options) {
  if (typeof type === 'object') {
    options = type;
    type = undefined;
  }

  assert("The first argument to DS.hasMany must be a string representing a model type key, not an instance of " + Ember.inspect(type) + ". E.g., to define a relation to the Comment model, use DS.hasMany('comment')", typeof type === 'string' || typeof type === 'undefined');

  options = options || {};

  if (typeof type === 'string') {
    type = normalizeModelName(type);
  }

  // Metadata about relationships is stored on the meta of
  // the relationship. This is used for introspection and
  // serialization. Note that `key` is populated lazily
  // the first time the CP is called.
  var meta = {
    type: type,
    isRelationship: true,
    options: options,
    kind: 'hasMany',
    name: 'Has Many',
    key: null
  };

  let lastRelationshipRecords = null;
  const setLastRelationshipRecords = function(newArray) {
    if (lastRelationshipRecords) {
        lastRelationshipRecords.destroy();
      }
    lastRelationshipRecords = newArray;
  };

  return Ember.computed({
    get(key) {
      var relationship = this._internalModel._relationships.get(key);
      const result = relationship.getRecords();
      setLastRelationshipRecords(result);
      return result;
    },
    set(key, records) {
      assert("You must pass an array of records to set a hasMany relationship", isArrayLike(records));
      assert(`All elements of a hasMany relationship must be instances of DS.Model, you passed ${Ember.inspect(records)}`, (function() {
        return Ember.A(records).every((record) => record.hasOwnProperty('_internalModel') === true);
      })());

      var relationship = this._internalModel._relationships.get(key);
      relationship.clear();
      relationship.addRecords(Ember.A(records).mapBy('_internalModel'));
      const result = relationship.getRecords();
      setLastRelationshipRecords(result);
      return result;
    }
  }).meta(meta);
}
```

**Comment by BryanCrotaz** [comment]
Should I submit a PR?

**Comment by stefanpenner** [comment]
fix is happening here: https://github.com/emberjs/data/pull/4827

**Comment by BryanCrotaz** [comment]
Whoops, just saw you'd submitted a fix. Your changes fix the leak in my reproduction repo above.

**Comment by stefanpenner** [comment]
https://github.com/emberjs/data/pull/4827#issuecomment-283448820
