### ISSUE TITLE
unloadRecord destroys manyArray

### ISSUE THREAD

**Issue by hjdivad** [emberjs/data#4835]
see https://github.com/emberjs/data/blob/master/addon/-private/system/relationships/state/has-many.js#L59-L65

presumably the right behaviour is to issue a change event for that index and then call it a day.

cc @stefanpenner @igorT

**Comment by BryanCrotaz** [comment]
surely the many array is the bit that's using RAM so we do want to destroy it on unload?

**Comment by stefanpenner** [comment]
@BryanCrotaz I believe in this case when a single belongsTo is unloaded, it destroys any `hasMany` pointing to it, forcing it to be invalidated and totally rebuilt when accessed.

**Comment by BryanCrotaz** [comment]
Ah that's a Bad Thing.

**Comment by BryanCrotaz** [comment]
although when the *last* belongsTo is unloaded, this should happen

**Comment by stefanpenner** [comment]
@bryancrotaz well it should become empty, but the hasMany should stick around until it's record is unloaded/destroyed

**Comment by runspired** [comment]
This was resolved by #5273 and other more recent fixes to the relationship layer.
