### ISSUE TITLE
reload: true on findAll is not documented in the guides

### ISSUE THREAD

**Issue by checkerap** [emberjs/data#4839]
I know now there is a blog post and it is documented in the api docs (there are several issues that mention it here already), but I found no mention of this in the guides and wasted several hours until I noticed the behavior and looked at the api docs.

I think at least a link in the guides would be helpful.

**Comment by bmac** [comment]
@locks Do you think it would be helpful to mention `{reload: true}` in the guides?

**Comment by bbansalWolfPack** [comment]
@bmac  Not sure if this is right place to ask doubt, but reload: true is not working for me. I have a page which makes a network call in route using findAll with reload: true and when I visit that page again using tabs then I dont see a new network call in the network tab.

**Comment by bmac** [comment]
@bbansalWolfPack sounds like you are using `reload: true` correctly. What adapter and version of Ember Data are you using?

**Comment by bbansalWolfPack** [comment]
@bmac  I am using   "ember-data": "2.11.0"

**Comment by bmac** [comment]
What adapter are you using?

**Comment by bbansalWolfPack** [comment]
@bmac  I am extending RESTAdapter

**Comment by bbansalWolfPack** [comment]
@bmac please correct me if I am wrong, does ember data store has a timeout after which even if records are in store and we dont use reload: true flag, it will still issue a new API request if triggered?

**Comment by runspired** [comment]
@bbansalWolfPack no. But there is a concept of backgoundReloading if you try to `findRecord` a record again.

Closing this issue as the guides now just link directly to the docs and skim past findAll otherwise.
