### ISSUE TITLE
Assertion Failed: You modified model.isNew twice on ...

### ISSUE THREAD

**Issue by jakubikan** [emberjs/data#4844]
according to this thread there is a new assertion

https://github.com/emberjs/ember.js/issues/13948

this happens for (e.g. isNew and dirtyType) when trying to use them in an `if` block in the template

thank you for you help

**Comment by runspired** [comment]
@jakubikan which version of ember-data was this? There were some issues with this but I was under the  impression we'd caught them all (at least as of 2.11)

**Comment by jakubikan** [comment]
i'm not quite sure (but i think it was 2.11.2)  - well i stopped the update at this point since there were just strange things happening ^^ 

But I can try the upgrade again and let you know

**Comment by bmac** [comment]
I was also under the impression that we've caught all of the cases where this happened. If you get a chance @jakubikan, a version number and an reproduction would be a big help.

**Comment by jakubikan** [comment]
Thanks for the help i did the update and it seems to be fixed :+1:
