### ISSUE TITLE
HasManyReference property _isLoaded return false when it had been loaded once (with empty result)

### ISSUE THREAD

**Issue by twawszczak** [emberjs/data#4845]
I have an issue with HasManyReference property "_isLoaded". It should return true when relationship had been loaded at least one time, right? But it returns false, when last relationship request returned empty array. (works correct when last request returned more then 0 elements)

https://github.com/emberjs/data/blob/v2.11.0/addon/-private/system/references/has-many.js#L111

**Comment by bmac** [comment]
Seems like a bug. What do you think @runspired / @igorT? Should `_isLoaded` return true when `hasData` is true and the members array has 0 elements?

**Comment by runspired** [comment]
seems like a bug

**Comment by bmac** [comment]
Actually @twawszczak now that I'm digging into this I'm having trouble reproducing the issue. I created a test for the issue in pr https://github.com/emberjs/data/pull/4891 but its currently passing on the master branch. Would you mind taking a look at my test and let me know if I'm missing something.

Thanks

**Comment by twawszczak** [comment]
@bmac i suppose you should assert _isLoaded property value, am i right? This is a problem in this issue.

**Comment by bmac** [comment]
I've updated the test to use `_isLoaded`, however, I'm still seeing it return true. I think I might have something wrong with how I'm getting into the state with an empty array. @twawszczak do you mind taking a look again?

**Comment by twawszczak** [comment]
@bmac I have loading data from server via JSONAPiAdapter, I don't know how reproduce it in test suite. :(

**Comment by bmac** [comment]
Would you be able to reproduce it using [this Ember Twiddle](https://ember-twiddle.com/c0beed7d3c0bed65ac8ed018dcc57894/copy)?
