### ISSUE TITLE
Update to babel@6 infrastructure.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/data#4859]
Now that ember-cli-babel@6 is released (still beta, but pretty solid in addons so far), we should work on ember-data's build system to start migrating to babel@6.

The addon build part is fairly easy, but we do need to confirm that the heimdall stripping babel plugin works properly with babel@6 (@runspired do you recall?).

The custom bower build stuff is slightly harder/more annoying, but still doable.

Creating an issue here for visibility...

TODO: 

- [ ] Update `babel-plugin-filter-imports`
- [ ] Update `babel-plugin-feature-flags`
- [ ] Update `babel5-plugin-strip-heimdall`
- [ ] Update `babel5-plugin-strip-class-callcheck`
- [ ] Update `ember-cli-babel`
- [ ] Update `broccoli-babel-transpiler` (for bower build pipeline)
- [ ] Update bower build pipeline

**Comment by bmac** [comment]
@rwjblue I believe you've taken care of everything described by this issue in pr https://github.com/emberjs/data/pull/4862. I'm going to close this issue but feel free to reopen if I'm missing something.
