### ISSUE TITLE
Built version of ember-data published to cdnjs.com does not compile.

### ISSUE THREAD

**Issue by Gaurav0** [emberjs/data#4873]
This version: https://cdnjs.cloudflare.com/ajax/libs/ember-data.js/2.12.0/ember-data.js of Ember Data does not compile.

See https://ember-twiddle.com/f3c647c9c4ef70c46d2dbe3aeabc5c72?openFiles=twiddle.json%2C

This is the version currently used by Ember Twiddle when a specific version is specified.

**Comment by Gaurav0** [comment]
Please note also that the "release" version at builds.emberjs.com is still 2.11.3

**Comment by runspired** [comment]
https://github.com/emberjs/data/blob/master/lib/javascripts.js#L55

^ this line closing out the iife that wraps the globals build needs to pass in `this` or `window` as the context.

**Comment by bmac** [comment]
Ember Data 2.12.1 has been published with a fix for this issue. Please let me know if you are still experiencing issues.

**Comment by bmac** [comment]
@runspired reports that 2.12.1 has fixed the issue with Ember Twiddle. I'm going to close this issue. Feel free to reopen if there is still a problem.
