### ISSUE TITLE
RESTAdapter assumes serializer must be a JSONSerializer

### ISSUE THREAD

**Issue by ming-codes** [emberjs/data#4887]
We have a custom adapter/serializer setup that delegates CRUD methods to appropriate adapter. In this case, it's a RESTAdapter. This works pretty well on read operation, but when doing updates, the adapter automatically assumes the serializer is a JSONSerializer and calls `serializeIntoHash`.

https://github.com/emberjs/data/blob/master/addon/adapters/rest.js#L776

This cam as quite a surprise as my understanding is that you can pair any adapter with any serializer so long that they both conform to the interface defined by `DS.Adapter` and `DS.Serializer`

**Comment by runspired** [comment]
@ming-codes it might be time to update things, but TL;DR `JSONAPISerializer` extends `RESTSerializer` which extends `JSONSerializer`.  For almost everything it is possible to assume that if it exists on `JSONSerializer` it is available.  We may want to reconsider which class is considered the "minimum interface".

**Comment by bmac** [comment]
I've always thought of the interface defined by `DS.Adapter` and `DS.Serializer` has been the interface between the the Ember Data store and and the adapter/serializers. 

While in theory the adapter is responsible for the protocol for communicating with a backend and the serializer is responsible for the serialization format of the records in practice they often end up with some level of coupling. `serializeIntoHash` being one of those cases.

**Comment by runspired** [comment]
the `RestAdapter` uses the per-model serializer strategy as expected at this point. E.G. if serializing `foo` it will lookup the serializer for `foo` to ensure it uses the correct one.
