### ISSUE TITLE
Attempted to handle event `deleteRecord` while in state root.deleted.saved

### ISSUE THREAD

**Issue by gregattra** [emberjs/data#4890]
After deleting one record successfully, i cannot delete another record of the same type or else this error is thrown:

`Attempted to handle event 'deleteRecord' while in state root.deleted.saved`

**Comment by erichonkanen** [comment]
any answer for this? getting same thing

**Comment by bbansalWolfPack** [comment]
I am getting this error, which is similar to this one:

Attempted to handle event 'deleteRecord' while in state root.deleted.inFlight
