### ISSUE TITLE
findAll throwing error

### ISSUE THREAD

**Issue by devtoro** [emberjs/data#4906]
Hello, 

I am using a simple findAll query in my ember application ( ember-version: 2.12.0, ember-data-version: 2.12.1 ) and I get the following error:

Assertion Failed: You can no longer pass a modelClass as the first argument to store.buildInternalModel. Pass modelName instead.

I am using the RESTAdapter and RESTSerializer.

Here is my team model: 

  `

      export default DS.Model.extend({
        name: DS.attr('string'),

        projects: DS.hasMany('project'),
        users: DS.hasMany('user'),
        members: Ember.computed('users', function() {
          return this.get('users.content.length');
        }),
        leader: DS.belongsTo('user', {
          inverse: 'team'
        })
      });
`

and my team serializer:
`
  export default ApplicationSerializer.extend(DS.EmbeddedRecordsMixin,{
    attrs: {
      users: { embedded: "always" },
      projects: { async: true }
    }
  });
`

Despite the error the team objects I requested are in the store. I had no luck in solving this...

**Comment by bmac** [comment]
Hi @devtoro. I suspect this might be an issue with the `DS.EMbeddedRecordsMixin` but I'm having trouble reproducing the issue on my end. I started created a jsfiddle based on the info you provided. Would you mind taking a look at it and letting me know what I'm missing https://ember-twiddle.com/?openFiles=routes.application.js%2C

**Comment by devtoro** [comment]
Even without the EmbeddedRecordsMixin, I still get the same error. 
I haven't use ember-twiddle before so it will take me some time, sorry :(

Here is the payload from the server:

{"teams":[{"id":1,"name":"Test Team 1","users":[{"id":2,"first_name":"Ethelyn","last_name":"Yost","lead":true,"email":"macie@kunze.co","role":"analyst","username":"Pidgeot","team_name":"Test Team 1"},{"id":6,"first_name":"Leila","last_name":"Haley","lead":false,"email":"marlon_weber@zulaufmckenzie.co","role":"analyst","username":"Raichu","team_name":"Test Team 1"},{"id":10,"first_name":"Claudia","last_name":"Flatley","lead":false,"email":"loyce@hettingerokon.info","role":"analyst","username":"Raticate","team_name":"Test Team 1"},{"id":14,"first_name":"Janie","last_name":"Weber","lead":false,"email":"carmel.baumbach@oberbrunnerschumm.name","role":"analyst","username":"Vulpix","team_name":"Test Team 1"},{"id":18,"first_name":"Lawrence","last_name":"Armstrong","lead":false,"email":"phyllis.olson@larson.com","role":"analyst","username":"Venonat","team_name":"Test Team 1"},{"id":22,"first_name":"Bonita","last_name":"Gorczany","lead":false,"email":"candice_bosco@nicolasgreen.biz","role":"analyst","username":"Charmeleon","team_name":"Test Team 1"}],"leader":{"id":2,"first_name":"Ethelyn","last_name":"Yost","lead":true,"email":"macie@kunze.co","role":"analyst","username":"Pidgeot","team_name":"Test Team 1"}},{"id":2,"name":"Test Team 2","users":[{"id":3,"first_name":"Lilian","last_name":"Dickinson","lead":true,"email":"emelia.dooley@ritchie.name","role":"analyst","username":"Seaking","team_name":"Test Team 2"},{"id":7,"first_name":"Yasmeen","last_name":"Steuber","lead":false,"email":"davion.hudson@metzlindgren.net","role":"analyst","username":"Mew","team_name":"Test Team 2"},{"id":11,"first_name":"Bette","last_name":"Abbott","lead":false,"email":"onie.renner@dietrich.com","role":"analyst","username":"Charizard","team_name":"Test Team 2"},{"id":15,"first_name":"Ernest","last_name":"Halvorson","lead":false,"email":"name@prosacco.io","role":"analyst","username":"Exeggutor","team_name":"Test Team 2"},{"id":19,"first_name":"Ryann","last_name":"Ward","lead":false,"email":"dan@huels.io","role":"analyst","username":"Scyther","team_name":"Test Team 2"},{"id":23,"first_name":"Kyler","last_name":"Windler","lead":false,"email":"bailee_weimann@dachklocko.org","role":"analyst","username":"Koffing","team_name":"Test Team 2"}],"leader":{"id":3,"first_name":"Lilian","last_name":"Dickinson","lead":true,"email":"emelia.dooley@ritchie.name","role":"analyst","username":"Seaking","team_name":"Test Team 2"}},{"id":3,"name":"Super Team 1","users":[{"id":4,"first_name":"Maynard","last_name":"Blanda","lead":true,"email":"colton@ebert.name","role":"analyst","username":"Oddish","team_name":"Super Team 1"},{"id":8,"first_name":"Randall","last_name":"Davis","lead":false,"email":"ethelyn.wuckert@schuppe.co","role":"analyst","username":"Abra","team_name":"Super Team 1"},{"id":12,"first_name":"Chester","last_name":"Littel","lead":false,"email":"deven@wilkinson.net","role":"analyst","username":"Kakuna","team_name":"Super Team 1"},{"id":16,"first_name":"Kali","last_name":"Cruickshank","lead":false,"email":"burnice.rogahn@bogisich.info","role":"analyst","username":"Hitmonlee","team_name":"Super Team 1"},{"id":20,"first_name":"Lauren","last_name":"Batz","lead":false,"email":"cale@ortiz.com","role":"analyst","username":"Dodrio","team_name":"Super Team 1"},{"id":24,"first_name":"Edmund","last_name":"Hudson","lead":false,"email":"verna_von@douglas.name","role":"analyst","username":"Pidgeotto","team_name":"Super Team 1"}],"leader":{"id":4,"first_name":"Maynard","last_name":"Blanda","lead":true,"email":"colton@ebert.name","role":"analyst","username":"Oddish","team_name":"Super Team 1"}},{"id":4,"name":"Super dupper team 1","users":[],"leader":null},{"id":5,"name":"Graphql Team 1","users":[],"leader":{"id":2,"first_name":"Ethelyn","last_name":"Yost","lead":true,"email":"macie@kunze.co","role":"analyst","username":"Pidgeot","team_name":"Test Team 1"}},{"id":6,"name":"Graphql Team 2","users":[],"leader":{"id":3,"first_name":"Lilian","last_name":"Dickinson","lead":true,"email":"emelia.dooley@ritchie.name","role":"analyst","username":"Seaking","team_name":"Test Team 2"}}]}

**Comment by bmac** [comment]
Sorry @devtoro. I used the wrong link. Check out this one https://ember-twiddle.com/dea9a158428ebbc748a0ad5ad179fd21?openFiles=routes.application.js%2C

**Comment by devtoro** [comment]
Ok, so the problem was in my team model. The "leader" attribute:

    leader: DS.belongsTo('user', {
          inverse: 'team'
        })

I still don't quite get it. As I saw in the code, the error is thrown if typeof(modelName)==='string'.
Should I pass the model class to the relationship? If so, should I do it in the options passed to the relationship?

**Comment by devtoro** [comment]
I set this as closed. I did not add "leader" in the team serializer. Thank you for your time and sorry. Guess I need a coffee break :)

**Comment by bmac** [comment]
I'm going to reopen this issue. I think Ember Data could provide a much better error message to make it clear why Ember Data is having trouble parsing this response.
