### ISSUE TITLE
snapshot returns undefined in adaptor

### ISSUE THREAD

**Issue by shivani2692** [emberjs/data#4907]
I am trying fetch data from store. I was previously using store.query but that always makes call to store. I want ember to first check in cache and if its a miss then only make a call to the store. Hence I am trying to use store.findAll as shown below.

I have a task in my route file 

```js
fetchTracksTask: task(function * (params) {
     return yield this.store.findAll('org-track', { adapterOptions: params });
}),
```

And i have an adapter org-track.js
```js
import DS from 'ember-data';

export default DS.JSONAPIAdapter.extend({
  urlForFindAll(modelName, snapshot) {
    const options = snapshot.adapterOptions;
    let query = '?';
    if (options) {
      Object.keys(options).forEach(function (key) {
        query += `&${key}=${options[key]}`;
      });
    }
    return `${this._buildURL()}${query}`;
  }
});
```

If I log 'snapshot.adapterOptions' it returns undefined.

Please help

**Comment by bmac** [comment]
The code you have looks correct. Is it possible that the `params` argument passed into your `fetchTracksTask` is undefined?

**Comment by shivani2692** [comment]
I tried logging the params inside fetchTracksTask and it is getting successfully passed into fetchTracksTask

**Comment by shivani2692** [comment]
Please help me in understanding if there is any alternate way of using urlForFindAll

**Comment by bmac** [comment]
Hi @shivani2692. I tried out your code in an Ember Twiddle here: https://ember-twiddle.com/3a2db002c1d423d7801708d9aa5000f6?openFiles=routes.application.js%2C

I was unable to reproduce the issue with `adapterOptions` being undefined but I did have to pass the `modelName` into `this._buildURL(modelName)`.

**Comment by shivani2692** [comment]
Worked after I updated ember-data version. Thanks :)
