### ISSUE TITLE
Make store.findByIds public, or remove it ?

### ISSUE THREAD

**Issue by sly7-7** [emberjs/data#4915]
see: https://github.com/emberjs/data/search?utf8=%E2%9C%93&q=findByIds&type=
It seems like it's not used internally anymore.

I'm currently moving an old app from ember-data pre.1.0, to ember-data 2.12, and I need something to get the records in the store passing an array of ids. I used findByIds, but it's private, is the an other way to do this ? (better than a loop over the ids and calling peekRecord)

**Comment by sly7-7** [comment]
@bmac Any thought about that ?

**Comment by bmac** [comment]
Making it public seems ok to me.

**Comment by sly7-7** [comment]
Do we need go from others ? If not, I can make this simple PR (I guess only removing the @private 'flag' ?)

**Comment by runspired** [comment]
It's similar to `findMany` (also `@private`) except I think `findMany` is specific to finding unloaded records only.  We want to significantly improve our `finders` layer soon, so I think bringing either of these public would be a bad idea.

If you are concerned about using this private-api, I would recommend either using `coalesceFindRequests` or writing a simple find method of your own that calls the adapter directly, normalizes, and then pushes to the store.
