### ISSUE TITLE
JSONAPISerializer does not support serializePolymorphicType

### ISSUE THREAD

**Issue by tacocat** [emberjs/data#4921]
`JSONSerializer` supports the `polymorphic` option, but `JSONAPISerializer` does not.

Given the [documentation](https://emberjs.com/api/data/classes/DS.JSONAPISerializer.html#method_serializePolymorphicType), it seems like both should support the `serializePolymorphicType` hook.

Example model with polymorhpic belongsTo:
```js
let ExampleModel = DS.Model.extend({
    favoriteMessage: belongsTo('message', { polymorphic: true })
})
```

**Comment by runspired** [comment]
given we are shifting off of supporting serializers I'm going to close this; however, if anyone interested in maintaining these serializers wants to add this I'll reopen it.
