### ISSUE TITLE
Throwing in `serialize`

### ISSUE THREAD

**Issue by amk221** [emberjs/data#4945]
If I throw an error whilst serializing, I was expecting to be able to catch this with `save().catch(...)`

Does this seem reasonable?

https://ember-twiddle.com/e63e22ec26ced2171e2c53cc088af37c?openFiles=controllers.application.js%2C

**Comment by bmac** [comment]
@amk221 this does seem very reasonable. I have opened a pr to fix the issue here: https://github.com/emberjs/data/pull/4977.

**Comment by amk221** [comment]
Brilliant, thanks!
