### ISSUE TITLE
AdapterError generatedDetailedMessage should handle JSON payloads

### ISSUE THREAD

**Issue by urbany** [emberjs/data#4953]
Hi,

When I get a JSONAPI error from the API I see this message:
```
Ember Data Request PATCH /api/professionals/1044 returned a 403
Payload (Empty Content-Type)
[object Object]
```

The `[object Object]` is the payload. Maybe there is a better way of showing this since `[object Object]` is not very helpful.

This message is generated here: https://github.com/emberjs/data/blob/24f41209b7ab9978bcdf029e50e3e62564d0b50f/addon/adapters/rest.js#L1192

In my case I'm using JSONAPI, since the [error format is known](http://jsonapi.org/examples/#error-objects-multiple-errors), maybe we can parse the error?

Or just `JSON.stringify(payload)` ?

This would be very useful for people that use services like sentry.io. I'm going to override these locally for now, but would like to know what you think of this.

Thanks in advance for your inputs!

**Comment by bmac** [comment]
Sounds like a good change to me. @urbany would you like to open a pr for this change?

**Comment by urbany** [comment]
Sure, I just don't know how to create a test for it, which I imagine would be needed for the PR.
Anyway do you think the best option is to stringify the payload and truncate it (in case it's a big payload) Or look at any of the attributes returned in the JSONAPI errors object?
