### ISSUE TITLE
rejectMissingRecords - unable to paginate with findByIds/coalesced ids

### ISSUE THREAD

**Issue by bttf** [emberjs/data#4955]
We are doing a GET request to our API w/ `coalesceFindRequests` enabled, giving us a request URI like this:

`/person?filter[id]=1,2,3,4,...,99`

Our API only returns at most 25 records, with pagination info included. But since there are missing records (requested ids vs. received ids), ember-data will throw the response away and consider the request failed.

We need a way to get the response, and be able to use the pagination info to re-request w/ pagination params included.

**Comment by stefanpenner** [comment]
I believe you can control this via the adapter: https://github.com/emberjs/data/blob/d4772a1d5978b6f548f5552cf3fb39b0b5fb0275/addon/adapter.js#L465-L482

**Comment by bttf** [comment]
That will allow us to 'chunk' the requests, and will work for us for the time being. This may not be a tenable solution though, because it needs some cooperation w/ API (deciding on 'chunk size'; different 'chunk sizes' for different resources).

Allowing `findMany` to accept partial records (if only by turning on some flag to ignore rejectMissing) would allow us to leverage pagination info which is readily available from the API

**Comment by runspired** [comment]
`findMany` is mostly about grouping for a precise request, what you are describing is a fairly odd setup for grouping (client says give me exactly these records and API says nah is ... odd).  You might have more success implementing this as a `query`.

Closing as there is no general pattern which we could build that would allow pagination of `findMany` at this time, given individual records are returned to their respective request sites, not an array of records.
