### ISSUE TITLE
peekRecord() not working as expected

### ISSUE THREAD

**Issue by denchen** [emberjs/data#4985]
I'm having an issue with `peekRecord()`, and I'm hoping I'm just not understanding how it works.

Basically, I have a record that I want to destroy, but after I destroy it and then use `peekRecord()` on it, I still see the record. Is this expected? In essence, I'm doing this:

    try {
      let record = this.store.peekRecord('my-model', 123);
      if (record) {
        yield record.destroyRecord();
        // I expect this next command to return null or Record Not Found
        let record2 = this.store.peekRecord('my-model', 123);
        console.debug('Record is still here:', record2.get('id'));
      }
    } catch(e) {
      console.error('Error:', e);
    }

I'm using ember-cli 2.12.3.

**Comment by hjdivad** [comment]
@denchen the deletion has not been persisted yet.

```js
record.destroyRecord.then(() => {
  store.hasRecordForId('model-name', id);
})
```

**Comment by stefanpenner** [comment]
@hjdivad wouldn't the `yield` handle that? (Assuming the generator supports promises)

**Comment by pangratz** [comment]
The record is in the `root.deleted.saved` state, see [this twiddle](https://ember-twiddle.com/d3e5bd62a320c3b0795150859f498928?fileTreeShown=false&numColumns=2&openFiles=routes.application.js%2Ctemplates.application.hbs).

**Comment by runspired** [comment]
I believe this has been cleaned up, but we should confirm.

**Comment by sly7-7** [comment]
@rwjblue @bmac I can't test the previous twiddle against ember-data canary, because of this  error:
```
ember-data.js:258 Uncaught Error: Could not find module `@ember/ordered-set` imported from `ember-data/-private/system/ordered-set`
```
Something wrong with the external import ? must we add `something somewhere`?

**Comment by runspired** [comment]
Closing in favor of #5006 which is a duplicate: TL;DR destroyed records are not unloaded automatically.
