### ISSUE TITLE
Using assert outside of promise context causes async function to become sync

### ISSUE THREAD

**Issue by steffansluis** [emberjs/data#4988]
So, I ran into this while working with `ember-simple-auth`. Seeing as this is very strange behavior to me I opened an [issue about it](https://github.com/simplabs/ember-simple-auth/issues/1335). This issue was closed with the justification that it's ok to do this because `ember-data` is doing it too.

I don't agree with this. Functions that return a promise should always return a promise. This subject is also (being) discussed [here](https://github.com/emberjs/data/issues/4428), but it seems to be more specifically targeted and a bit outdated. I'm curious to hear what you think about this.

**Comment by runspired** [comment]
I'm not sure what you mean. It doesn't cause async behavior to become synchronous, it causes an asynchronous function to never run at all because it errors out early...

**Comment by steffansluis** [comment]
Functions that return promises should return a rejecting promise if they fail instead of error-ing out. Synchronous function return non-Promises and error out. Asynchronous function return resolving or rejecting Promise-like objects. This is also specified [here](https://www.promisejs.org/patterns/).

**Comment by runspired** [comment]
@steffansluis you are misunderstanding. These asserts are basically inline-unit tests. If you hit them, your app should break to a full stop, versus going quietly into the night.  This isn't a potential promise rejection scenario, this is "we can't even fire off this promise because your app is in a broken state, here is what you need to fix".

**Comment by steffansluis** [comment]
I understand the reasoning behind using asserts as inline unit tests, but I'm still not sure if this is a good idea. To me the distinction between sync/async seems so ingrained JS that it should be upheld regardless of the state any app might be in.

Consider the `async` keyword from ES7. It changes the behavior of your function from sync to async, and in doing so it will turn your broken states into rejecting promises. To me that says: 'Async functions are supposed to return promises. Period.' In fact, TypeScript wouldn't even allow you to return a non-Promise-like object from a proper `async` function. Why should asserts statements be excluded from this principle?

Even though you are not using ES7 async function in this case, I think this principle holds regardless for any function that wishes to return a Promise-like object, and as such it should hold for your assert statements as well. Even if they are only triggered in development mode and/or serve as inline unit tests.

**Comment by runspired** [comment]
This isn't a return. If you hit this, there is no way the application can recover or continue.

**Comment by mdebbar** [comment]
> In fact, TypeScript wouldn't even allow you to return a non-Promise-like object from a proper async function.
Does TypeScript prevent you from throwing inside an async function?

Let's talk about contracts 🙃
Assertions are used by libraries to define contracts. If a library method throws an assertion exception, it means that the developer has violated the contract. In that case, the developer has violated the contract first, so why is library not allowed to break the contract at that point? 😄

**Comment by steffansluis** [comment]
@runspired 
I'm still not sure if that justifies violating the principle. I understand the practical reasoning behind it, but it can cause weird behavior, just to have the application break when you want it to break. I think there are ways to accomplish this without violating this principle.

To be fair, I'm really doubting my own arguments as I'm writing this. I am sympathetic to the idea of being defensive about your API in development mode by using asserts, if only to protect people from themselves. However, in my experience, being inconsistent about synchronicity generally causes everybody to have a bad time. Personally, I would rather not be protected against myself at the cost of that.

@mdebbar Fair argument. What about the way Javascript goes about dealing with sync vs async? I would argue that is a more important contract than the one defined by the assert statements.

**Comment by steffansluis** [comment]
@mdebbar Also, ES7 allows you to throw in an async function. This results in a rejecting Promise. That means there is actually no way to have a proper async function work the way the assert statements are now. TypeScript just (correctly) enforces that async functions should always return a Promise-like object.

**Comment by runspired** [comment]
A parting note, much of what we assert on would be a type error in typescript. Types are just another method of contract enforcement.

**Comment by steffansluis** [comment]
Fortunately, that contract doesn't violate the basic principle of async programming that you are violating. Furthermore, this is mostly about the `async` keyword and its interaction with a function. You cannot break the way you are right now in a function that has the `async` keyword. The contract you have with ES7 won't allow it.
