### ISSUE TITLE
Everything works fine until I have a more complex data object

### ISSUE THREAD

**Issue by terrycafe520** [emberjs/data#4989]
when I use the data like this ,I can get the data object.
`data: [{ type: 'rentals', id: 'grand-old-mansion', attributes: { title: 'Grand Old Mansion' } }]`
but when I change the data like below ( just add the code and msg ) . I cannot get the data . In the models I defined the model attr. Where is the problem's key point ?
`code': 200, 'msg': 'something else' 'data': [{ type: 'rentals', id: 'grand-old-mansion', attributes: { title: 'Grand Old Mansion' } }]`

**Comment by pangratz** [comment]
I have trouble reproducing. Using the response you posted, getting the attributes seems to work fin, so I am closing.

Can you update [this ember-twiddle](https://ember-twiddle.com/16b46c706735da23659704cd18ad9854?fileTreeShown=false&numColumns=2&openFiles=routes.application.js%2Ctemplates.application.hbs) so it demonstrates the issue you're having? Feel free to reopen if you still run into an issue, ideally with an ember twiddle showing what's not working. Thanks!
