### ISSUE TITLE
Using different key instead of "type" for polymorphic

### ISSUE THREAD

**Issue by minhnq013** [emberjs/data#4990]
I understand that it is part of JSON API spec and there are issue asking this question already, however they were not addressed nor commented, so sorry for duplicating it here. 

Would it be possible to change the key "type" into another one for polymorphic? The API in our app current use "type" as one of the property key.
It also seems very odd that we can change the polymorphic key for "serializing" but not "deserializing".

**Comment by pangratz** [comment]
Can you update [this ember-twiddle](https://ember-twiddle.com/0e1a24aabb8fa7c1fdd8/copy?fileTreeShown=false&numColumns=2&openFiles=routes.application.js%2Ctemplates.application.hbs) so it demonstrates the issue you're having?

**Comment by runspired** [comment]
Closing as we've standardized on `json-api` as our internal format. Other uses of reserved member names (such as `type`) should be transformed into another attribute (such as `dataType` for instance),
