### ISSUE TITLE
Polymorphic Relationships Broken

### ISSUE THREAD

**Issue by btecu** [emberjs/data#5004]
Up until `2.12.2` polymorphic relationships work.
Starting with `2.13.0-beta.1` I get `Cannot read property 'length' of undefined` which is not very useful.
I've also tested with `2.13.2` and it's not working.

It appears polymorphic relationships work under `2.14.0-beta.2`.

**Comment by sbatson5** [comment]
Ran into this issue too. Updating to `2.14.1` fixed it

**Comment by pangratz** [comment]
Closing as it seems this has been fixed in newer versions.
