### ISSUE TITLE
Question: Relationships, WebSockets, and Custom Adapter

### ISSUE THREAD

**Issue by josiahbryan** [emberjs/data#5005]
I'm using a [custom adapter](https://www.npmjs.com/package/ember-data-feathers) to interact with [FeathersJS](www.feathersjs.com) over WebSockets that I'm trying to get to support relationships. 

The docs say nothing about how an Adapter can support loading relationships. And, my adapter uses WebSockets as the transport, no Ajax or REST. So links are not relevant. 

What do I need to implement in my adapter to get it to support automatic loading of hasMany / belongsTo relationships?

**Comment by pangratz** [comment]
I am sorry to be that guy but we're using GitHub issues to track bugs. Your question seems more suited for the [`-ember-data` channel](https://embercommunity.slack.com/messages/-ember-data/) in the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/).

Basically if you want to push in a specific relationship, you could push the according data via ` store.push`, so something like this:

```js
let book = store.peekRecord('book', 1);

book.get('author.id') === undefined;

store.push({
  data: {
    type: 'author',
    id: '2',
    relationships: {
      book: {
        data: {
          id: '1',
          type: 'book'
        }
      }
    }
  }
});

book.get('author.id') === '2';
```
