### ISSUE TITLE
Ember 2.13.0 Reloading relationships that have already been loaded

### ISSUE THREAD

**Issue by adamlawson** [emberjs/data#5007]
Hi, I've just updated to Ember 2.13.2 from 2.11.0, and having issues with ember data.

In my app I load lookup data in the route before loading in a model that relates to the lookup data...
For example: I preload all productCategories, then load the product
However, when referring to product.productCategory.name in a computed function, it always attempts to reload the relationship instead of using whats already in the store.
Every relationship seems to be reloaded on first use. I only noticed it because on my api i don't have an endpoint for singular items. This wasn't happening in 2.11.0.

Is this a bug or is there something I should be doing differently? I could make sure that each relationship has the singular endpoints available but that would negatively impact performance

**Comment by runspired** [comment]
@adamlawson is this still an issue?

**Comment by runspired** [comment]
I've added enough test coverage lately that I'm fairly certain this is an user-land app issue.
