### ISSUE TITLE
ready event not fired for every load of a model instance from the server

### ISSUE THREAD

**Issue by leondmello** [emberjs/data#5010]
As per the [documentation](https://emberjs.com/api/data/classes/DS.Model.html#event_ready) for `DS.Model` `ready` event, the event is triggered for every load of a model instance from the server.

If that's the case, it doesn't fire on every fetch from the server but just the initial fetch for the lifetime of the app. Is this expected behavior? (If yes the docs need to be updated and I hope there is an alternate solution).

I created a simple [repository](https://github.com/leondmello/ed_ready_issue) which reproduces the issue.

**Steps to reproduce the issue**
1. Load the example ember application with the browser console open
2. Visit the `new` route (http://localhost:4200/new) - This should print that the ready hook fired
3. Save with a name
4. This takes you to the `view` route which loads the record from `mirage` - This does not trigger the `ready` hook for some reason
5. Go to `All` and click the same record again - This does not trigger the `ready` event either

**Comment by runspired** [comment]
`ready` should only fire once. The documentation does not suggest more than the initial load. `didUpdate` is more likely the event you want; however, I would heavily recommend not using events on models at all.
