### ISSUE TITLE
Could not find module `ember-data/-private

### ISSUE THREAD

**Issue by moogus** [emberjs/data#5021]
I'm having a similar to Could not find module `ember-data/-private` imported from `ember-data/setup-container` #5019 

CLI builds stating:

```bash
'instrument' is imported from external module 'ember-data/-debug' but never used
[BABEL] Note: The code generator has deoptimised the styling of "-private.js" as it exceeds the max of "100KB".
```

When I run my tests I get: 

```
Error: Could not find module `ember-data/-private` imported from `ember-data/setup-container`
    at missingModule (https://localhost:4200/assets/vendor.js:228:11)
    at findModule (https://localhost:4200/assets/vendor.js:239:17)
    at Module.findDeps (https://localhost:4200/assets/vendor.js:179:24)
    at findModule (https://localhost:4200/assets/vendor.js:242:11)
    at Module.findDeps (https://localhost:4200/assets/vendor.js:179:24)
    at findModule (https://localhost:4200/assets/vendor.js:242:11)
    at requireModule (https://localhost:4200/assets/vendor.js:29:15)
    at https://localhost:4200/assets/vendor.js:240732:20
    at Array.forEach (native)
    at exports.default (https://localhost:4200/assets/vendor.js:240729:8)
```

Tried latest ember-data, and my current 2.10 both with and without ^.  Just seems super broken.

Any ideas?

**Comment by royk** [comment]
Same here. Going back to 2.13.2 fixes it. (2.14.0 is already broken)

**Comment by os6sense** [comment]
Same issue

**Comment by runspired** [comment]
This appears to be an issue with ember-cli-babel < 6

**Comment by alcance** [comment]
Same issue. 
```
"ember-cli": "2.9.1",
"ember-data": "^2.7.0",
"ember-cli-babel": "^5.1.6"
```

**Comment by marclundgren** [comment]
Can confirm.

```
"ember-cli": "2.6.3",
"ember-data": "^2.6.0",
"ember-cli-babel": "^5.1.6",
```

**Comment by alcance** [comment]
Targeting ember-data's version to `~2.13.0` fixed it for me

**Comment by bmac** [comment]
Ember Data [v2.14.2](https://github.com/emberjs/data/releases/tag/v2.14.2) is published with a fix for this issue.

**Comment by BrianSipple** [comment]
I just updated to `v2.14.2` and I'm still getting something very similar. 

This is what gets logged when I run `ember serve`:

```
'instrument' is imported from external module 'ember-data/-debug' but never used
'instrument' is imported from external module 'ember-data/-debug' but never used
```

And this is error thrown in the browser console when I visit the app running on my localhost:

```
loader.js:244 Uncaught Error: Could not find module `ember-data/-private/system/normalize-model-name` imported from `ember-resource-metadata/private-api`
    at missingModule (loader.js:244)
    at findModule (loader.js:255)
    at Module.findDeps (loader.js:165)
    at findModule (loader.js:259)
    at Module.findDeps (loader.js:165)
    at findModule (loader.js:259)
    at Module.findDeps (loader.js:165)
    at findModule (loader.js:259)
    at Module.findDeps (loader.js:165)
    at findModule (loader.js:259)
```

**Comment by rwjblue** [comment]
@BrianSipple - That seems like a thing that ember-resource-metadata needs to deal with (not the issue being reported here).  Specifically, that addon is importing a module that will not exist in ember-data@2.14.0.

**Comment by stefanpenner** [comment]
If I'm understanding correctly, an addon is importing private api, which has now been moved. Although I can totally empathize, that add-on will need to update itself.

**Comment by abbasovalex** [comment]
Same problem:
$ ember -v
ember-cli: 2.15.0-beta.1
node: 8.0.0
os: darwin x64

Anybody could fix it? All my projects were broken :( I tried install several version of ember-cli, but could not fixed it.

**Comment by balinterdi** [comment]
That's fixed in 0.0.8 of ember-resource-metadata ([see PR here](https://github.com/ef4/ember-resource-metadata/pull/4)).

**Comment by royk** [comment]
This is now back in Ember data 2.15.0

**Comment by tomasbecklin** [comment]
Ended up locking ember data to 2.14.10

**Comment by dave-ramirez** [comment]
Increasing Ember-data dependency solved my problem.

`npm install --save ember-data@2.14.2` and `npm cache clean`

by: [Pavol](https://stackoverflow.com/questions/46073580/error-could-not-find-module-ember-data-private-imported-from-ember-data-set?answertab=votes#tab-top)
