### ISSUE TITLE
queryRecord does not apply raw transform

### ISSUE THREAD

**Issue by vmalloc** [emberjs/data#5036]
I have a model with a raw (nested JSON) attribute:

```
import DS from "ember-data";

export default DS.Model.extend({
  ...
  related: DS.attr('raw'),
  ...
});
```

I implemented the raw transform as `app/transforms/raw.js`:
```
import DS from 'ember-data';

export default DS.Transform.extend({
  deserialize: function(serialized) {
    console('transforming', serialized);
    return serialized;
  },
  serialize: function(deserialized) {
    return deserialized;
  }
});
```

The code that loads my model looks like this (you can find it [here](https://github.com/getslash/backslash/blob/bugfix/query_record/webapp/app/session/route.js#L19) ):

```
model({ id }) {
      let self = this;
      return self.store.queryRecord("session", {id: id}).then(function(session) {
        return Ember.RSVP.hash({
          session_model: session,
          ...
        });
      });
    },
```

When I do this, and try to access `related` in my controller or template, I get `undefined`, and the transform's deserialize isn't even called.

Weirdly enough, when I change the `queryRecord` to `findRecord, the serializer gets called and the expected value is returned to the controller...

Is there anything I'm doing wrong?

My entire code is [here](https://github.com/getslash/backslash/tree/bugfix/query_record/webapp) and if there's anything else you'd like me to provide or explain I will gladly do so. Thanks in advance!

P.S Using ember-cli 2.13.2 with ember-data 2.13.1

**Comment by kumkanillam** [comment]
When you know `id` is known beforehand then it's good to use `findRecord`. otherwise you can also use `store.query` and get the firstObject from the result is the preferred way. 
You can refer here for more details. https://emberjs.com/api/data/classes/DS.Store.html#method_queryRecord
I am not really saying fix for your issue. This is just a note.

**Comment by vmalloc** [comment]
@kumkanillam I can't use `findRecord` because my API accepts two possible formats for the record's ID, which means I have to use a query to fetch the object...

**Comment by pangratz** [comment]
I have trouble reproducing. Can you update [this ember-twiddle](https://ember-twiddle.com/095000f5b819174a542c5736f67b34ac?fileTreeShown=false&numColumns=2&openFiles=routes.application.js%2Ctemplates.application.hbs) so it demonstrates the issue you're having?
