### ISSUE TITLE
store.push can leave belongsTo content as null

### ISSUE THREAD

**Issue by BryanCrotaz** [emberjs/data#5037]
push a jsonapi blob with:

```
... relationships: {
  parent:
    data: {
      id: something,
      type: my-type
    }
}
```

obj.get('parent') === null

**Comment by pangratz** [comment]
Can you update [this ember-twiddle](https://ember-twiddle.com/6f415e227c83ed83cd02102814065b86?fileTreeShown=false&numColumns=2&openFiles=routes.application.js%2Cmodels.person.js) so it demonstrates the issue you're having?

**Comment by sly7-7** [comment]
@BryanCrotaz I've encountered something like this, see https://github.com/emberjs/data/pull/5208, perhaps the same use case ?
