### ISSUE TITLE
Upgrading to 2.14.x from 2.13.x causes lots of double render errors

### ISSUE THREAD

**Issue by rstudner** [emberjs/data#5056]
Not sure exactly what i'm doing wrong here.. 
I have a component, I reference like this:
```
{{my-component investigation=investigation}}
```

Here is its template.
```
{{#if investigation.leadAlert}}
  {{investigation.leadAlert.alertTypeText}}
{{else}}
  <span class="overflow">{{investigation.leadDescription}}</span>
{{/if}}
```

The investigation model has a async relationship, to leadAlert.  It is a one to one relationship.

The initial route for this investigation had an &includes=leadAlert sort of thing on it.

Basically, the above now causes a double render/this has been deprecated error.

If I made my component.js have:
```
leadAlert: computed.alias('investigation.leadAlert'),
leadAlertAlertTypeText: computed.alias('leadAlert.alertTypeText)
```
and change my .hbs to have:
```
{{#if leadAlert}}
  {{leadAlertAlertTypeText}}
{{else}}
  <span class="overflow">{{investigation.leadDescription}}</span>
{{/if}}
```

Then the double render errors go away.

But like -- why do I have to do this?  I have had the top syntax for.. I mean.. years? without issue.

**Comment by tsteuwer** [comment]
If you look at the other issues this one has been reported. You'll need to stick to 2.13.2 or prior version.
