### ISSUE TITLE
ember-data 2.14.3 : Warning: ignoring input sourcemap for vendor/ember/ember.debug.js

### ISSUE THREAD

**Issue by olivierchatry** [emberjs/data#5057]
Complete message : 
```
Warning: ignoring input sourcemap for vendor/ember/ember.debug.js because ENOENT: no such file or directory
```

Not sure if it a ember-data bug, but it only appears if I use 2.14.x ( I'm at 2.14.3 now ).

**Comment by rwjblue** [comment]
This seems like an issue with ember itself (not ember-data).

**Comment by olivierchatry** [comment]
Woops yes, don't know why I read ember data :(
