### ISSUE TITLE
Avoid use new Date(<string>) to deserialize

### ISSUE THREAD

**Issue by woprandi** [emberjs/data#5064]
Hi,

`new Date()` being implementation-dependent, the behavior is different according to the browsers (versions) : 

Chrome 59 : 
`new Date("2017-07-13T07:00:00")`
` Thu Jul 13 2017 07:00:00 GMT+0200 (CEST)`

Chrome 54 : 
`new Date("2017-07-13T07:00:00")`
`Thu Jul 13 2017 09:00:00 GMT+0200 (CEST)`

PhantomJS:
`new Date("2017-07-13T07:00:00")`
`Thu Jul 13 2017 09:00:00 GMT+0200 (CEST)`

The use of moment.js should fix this problem

**Comment by runspired** [comment]
There is a discussion of why we do what we do here: https://github.com/emberjs/data/pull/4936 with links to other issues on the topic.
