### ISSUE TITLE
With 2.14.4 a little bit slower my entire page animation.

### ISSUE THREAD

**Issue by johnunclesam** [emberjs/data#5065]
With `2.14.4` I have noticed little delays in graphics animations on the page compared to the previous one I came from, `2.13.2`.

**Why?**

Something small, no problem, but my eye is good enough to notice that.

**Comment by stefanpenner** [comment]
It may be related to unloading records. We do more cleanup in that area then before. Does your slowdown related to unloading records?

**Comment by johnunclesam** [comment]
I don't think so. It's about loading models the first time...

**Comment by stefanpenner** [comment]
Ya that was just a guess. Do you have a reproduction handy? I would love to compare

**Comment by stefanpenner** [comment]
Will gladly reopen if my above comment is responded to.
