### ISSUE TITLE
recordArray param no longer available in query

### ISSUE THREAD

**Issue by rmmmp** [emberjs/data#5076]
I believe it's related to #4947 but I'm not sure if it's intentional.

My use case is that I have an adapter that currently sets a Firebase listener to mutate that `recordArray` on record changes at the start of the `query`.

Before I go off to find another solution, I just wanted to make sure that the removal of `recordArray` is intentional? Seeing that it's a public API, I would've thought that there should've been some deprecation.

EDIT:

This is for 2.15+ btw.

**Comment by rmmmp** [comment]
Any update here?

**Comment by pangratz** [comment]
Just to add more context, I recall another discussion about the `recordArray` param for `query` in #4610...

**Comment by pangratz** [comment]
ping @stefanpenner

**Comment by runspired** [comment]
The issue here was recently fixed by #5345
