### ISSUE TITLE
Loading base class results into an empty array

### ISSUE THREAD

**Issue by mnifakram** [emberjs/data#5085]
I can't load all models that inherits from a base class. Let's say I have an **Admin** and **SuperAdmin**, both inherits from **User** class. Using `store.findAll('user')` will make the request but the result data will be an Empty Array.

By checking the Ember Data Inspector Data Tab, I can see that data has been loaded but it lives under **super-admin** and **admin** section.

Here is a twiddle that reproduce that https://ember-twiddle.com/0e1a24aabb8fa7c1fdd8.

**Comment by kumkanillam** [comment]
@mnifakram Update your twiddle

**Comment by mnifakram** [comment]
@kumkanillam sorry it was the original twiddle here's mine https://ember-twiddle.com/b90ae067f4e6c3867984f9f4d9bba0a9

**Comment by alexspeller** [comment]
I have now looked at this and realised that this is expected behaviour - the users array will contain only a list of users, not other classes too.

**Comment by mnifakram** [comment]
Should this be a feature where you could load all the child classes aggregated? At the end an **Admin** is also a **User**!!

**Comment by pangratz** [comment]
So unfortunately this is a limitation of polymorphic relationships at the moment. I am going to close this issue in favor of the [corresponding RFC 67](https://github.com/emberjs/rfcs/pull/67).
