### ISSUE TITLE
Delete right after reload triggers exception

### ISSUE THREAD

**Issue by jlami** [emberjs/data#5096]
Hi,

I know this is not really good practice, but our adapter has to handle this case. The problem is that it receives signals from the remote database that indicate that a record should be reloaded. But if the user then deletes that record before the reload is finished, the data is pushed on a deleted record. This results in exceptions.

In our addon this is actually `Assertion Failed: Cannot call writableTag after the object is destroyed`, but in the repro this is ``Attempted to handle event `pushedData` on <person:1> while in state root.deleted.saved``

This might be due to slightly different timings in the repro vs our addon.

Repro in this twiddle, which just reloads and then immediately deletes the record:
https://ember-twiddle.com/31f5ac5be269523394e124cfb728c955?numColumns=2&openFiles=routes.application.js%2Ctemplates.application.hbs

The discussion for the bug in our addon is here: https://github.com/pouchdb-community/ember-pouch/issues/188

I hope you can help

**Comment by stefanpenner** [comment]
@jlami what is the expected outcome?

* should the user delete win ?
* should the server restore win ?


My intuition here, is to say that the delete should cancel the reload , or at-least ignore the response to the reload (letting the user win).

**Comment by jlami** [comment]
I agree.

**Comment by stefanpenner** [comment]
In that case what should the `reload()` promise fulfill with, or a rejection?

**Comment by jlami** [comment]
Our addon actually does not care which option is taken. But I know that is good to think about it here.

I think there are two options.

1. Fulfill with a record that has `.isDeleted` set to `true`
2. Reject

In case 1 I don't know if the data should be updated to reflect the reloaded attributes.

At first thought I would be inclined to go with option 1. It feels more correct. Though that might give people unexpected behaviour as the deleted record might react differently to the code in the resolve callback. Although before this was never possible due to the exception. So handling this as a rejection might give it the extra attention that this case might need?

--
As a related question: is it possible to set a model to the `deleted.saved` state from inside an adapter? I guess you would have to handle the current state? If this is too far offtopic I can ask somewhere else. I ask here since this scenario of a reload followed by a delete can also happen in our addon from events. So if the `reload()` happens locally, but remotely the item is deleted. For the delete we get a message, which can get handled before the reload is done. In this case we can't handle it with a `destroyRecord()`. 

Currently we handle remote deletions with `unloadRecord`. But I guess this will result in even more problems, since then you won't be able to track the state to see that the `reload` should be handled like the case in this issue. Marking the model as `deleted.saved` could solve this? But I haven't used the InternalModel like this before. Any advice? (Are deleted.saved records actually unloaded at some point to save 'space'?)

**Comment by runspired** [comment]
- This is somewhat related to #5387 which has a repo.
- The underlying issue (push of data onto a deleted record) was fixed here: #5408
