### ISSUE TITLE
Refreshing partially loaded records

### ISSUE THREAD

**Issue by rvega** [emberjs/data#51]
Here's the scenario:

You load a list of records with findQuery but the server only returns a few fields for each record. Afterwards, when the user navigates to a "detail" screen, you need to fetch the rest of the fields for the record from the server so you call App.store.find(type, id) and the store returns the already fetched record, there's no way to tell the store to fetch ask the adapter for the record again.

Also, any suggestions for a work around are appreciated.

**Comment by ZenCocoon** [comment]
There's now a Ember CLI addon to solve this at https://github.com/BookingSync/ember-data-partial-model

**Comment by toobulkeh** [comment]
Are there downsides to including that addon into ember-data core?

**Comment by tchak** [comment]
@toobulkeh including properly this kind of functionality in core require to make all attributes accessors async (aka return a promise). This is something that is discussed but have a lot of implications. It could be not too much of a problem once async/await are more wildly used.
