### ISSUE TITLE
Calling serialize on model with embedded relationship causes a warning

### ISSUE THREAD

**Issue by josemarluedke** [emberjs/data#5100]
I have a model which I create a record (`createRecord`) passing only a few fields and not passing the relationship. When I call `serialize()` (or `save()`) it will issue the following warning: 

`WARNING: The embedded relationship 'tags' is undefined for 'post' with id 'null'. Please include it in your original payload.`

The warning feels weird because it is complaining about the original payload, which in this case there is no original payload.

I have a reproduction here: https://github.com/josemarluedke/ember-data-embedded-relationship-warning

This is happening in the latest Ember Data (2.14.x), but was not back in the 2.12.x version.

**Comment by sly7-7** [comment]
I think that's is happening since https://github.com/emberjs/data/pull/5048. The workaround I think about for now is explicitely passing an empty array to the relationship.
Though I wonder if we can reintroduce the old behavior.

cc/ @stefanpenner

**Comment by amk221** [comment]
This is affecting me also.

**Comment by amk221** [comment]
Any news, although they're only warnings, it's putting me off upgrading.

**Comment by atomkirk** [comment]
yeah this seems like a bug since its on create and there is no original payload

**Comment by amk221** [comment]
:(

**Comment by runspired** [comment]
Closing in favor of #5173 which gets at the underlying issue a bit more clearly.

**Comment by amk221** [comment]
Sorry to being up an old issue...

Given a model like:

```
export default Model.extend({
  name: attr('string'),
  bar: belongsTo('bar'),
  bazs: hasMany('baz')
});
```

...and a test endpoint like:

```
this.server.get('/api/foo/1', () => {
  return [
    200,
    {},
    {
      foo: {
        id: 1,
        name: 'Test foo'
      }
    }
  ];
});
```

I often leave out the embedded relationships simply because they are not relevant to the test case and/or there are too many 'blank' relationships to make.

So I ended up with A LOT of:

```
WARNING: The embedded relationship 'bar' is undefined for 'foo' with id '1'. Please include it in your original payload.
```

...do I _really_ have to include it _all the time_ ? 

I expect the answer is yes, but thought I'd ask anyway.
