### ISSUE TITLE
Embedded records do not change status when model is saved

### ISSUE THREAD

**Issue by Lillvik** [emberjs/data#5104]
```
let model = DS.Model.extend({
    related: DS.belongsTo('relatedModel', {async: false})
});

DS.RESTSerializer.extend(DS.EmbeddedRecordsMixin, {
  attrs: {
    related: {embedded: 'always'}
  }
});

model.

model.save();
```
When saving the model, the status of the related model is not changed to isSaving = true and when the model is saved it is not changed to hasDirtyAttributes = false

**Comment by pangratz** [comment]
Yeah, that's a known limitation at the moment. See https://github.com/emberjs/rfcs/pull/173 for a related RFC.

**Comment by pangratz** [comment]
I am closing in favor of the RFC, as we try to keep GitHub issues to tracking bugs. Thanks!
