### ISSUE TITLE
When model has no key and you unloadRecode, deleteRecord, rollbackAttributes it should show some sensible error and does not freez the whole browser.

### ISSUE THREAD

**Issue by GitSahib** [emberjs/data#5116]

**Comment by grodriguez85** [comment]
I am having the same problem. Why does the whole browser freezes? How can I unload a record which had failed to save?

**Comment by bantic** [comment]
Do you have devtools open at this time? I think something about the ember-data store being in an inconsistent state and having the ember inspector present (not even directly open, but if the devtools are open and you have ember-inspector installed) causes Chrome to hang. I've noticed it too, when debugging #5167.

**Comment by janwerkhoven** [comment]
As @bantic mentioned: The Chrome browser tab freezes consistently when I'd have the Chrome dev tools open, on the Ember Inspector "Data" tab, on the moment the app does a `store.unloadAll()`.

Ember Inspector 2.1.1
"ember-cli": "~2.14.1",
"ember-data": "2.14.10",

**Comment by Saldonas** [comment]
I just ran in to this problem myself. Was occurring in both Firefox and Chrome for me. I had Ember Inspector enabled for both. I just disabled it on Firefox and the issue appears to have gone away.

**Comment by pangratz** [comment]
It seems that this is an issue with Ember Inspector and not ember-data, so I am closing.

**Comment by GitSahib** [comment]
How it seems
