### ISSUE TITLE
Can't load initializers in globals build

### ISSUE THREAD

**Issue by mmun** [emberjs/data#5118]
When I try to use canary ember-data in ember-twiddle I get an error.

```
Uncaught Error: Assertion Failed: An instance initializer cannot be registered without an initialize function
  assert @ ember.debug.js:5989
  assert @ ember.debug.js:17740
  (anonymous) @ ember.debug.js:5115
  registerInstanceInitializers @ ember-data.js:18728
  exports.default @ ember-data.js:18705
  (anonymous) @ ember-data.js:18741
  (anonymous) @ ember-data.js:18751
```

The problems seems to be rooted at this line, which I believe only runs in the globals build:

https://github.com/emberjs/data/blob/8e600fe3c4d295be3d80b75ea0dca793c8ed889d/lib/javascripts.js#L57

**Comment by runspired** [comment]
@mmun thanks! yes the initializers changed a bit recently, annoying how the build tooling for globals means we dont quite test the true globals build in our tests
