### ISSUE TITLE
2.14.x. links relationships id is reloaded. 2.13.2 is OK.

### ISSUE THREAD

**Issue by johnunclesam** [emberjs/data#5143]
## **_With 2.13.2 everything ok._**

**From 2.14.x** I have a strange phenomenon:

I'm in the category 1 page, in that page I have a simply

```
{{#each model.posts key="id" as |post index|}}
    {{#link-to 'post' model.id post.id}}Post{{/link-to}}`
{{/each}}
```

when I go in the post page I have this:

`{{#link-to "category" model.category}}Back to category{{/link-to}}`

sometimes that link is **_`/#`_**.

In my router.js I have this:

```
...
this.route('post', { path: ':category_id/:post_id' });
...

```
So after investigating a bit I realized that the blame is of the new "ember-data 2.14.x (and 2.15.x of course, I tried)" and of its bad relationship with the related JSONAPI links (many bugs with JSONAPI related links just fixed in ember-data 2.14.10).

The first time I enter that post page the link "Back to category" is **_`/#`_** until it loads (**again** I can say, because in the category page it already knows about `post` and its `category.id`, isn't it?).

I can't reproduce on ember-twiddle because I'm not enough good to. But I realized a twiddle with mirage without links related relationships. Maybe some of you can insert the missing links part in mirage? Here is the link: https://ember-twiddle.com/94b21b033f50339cfa5de0040787f12f

I hope we can fix soon and most important we can understand and test more from this mistake. :)

Maybe related to: https://github.com/emberjs/data/pull/5124, https://github.com/emberjs/data/issues/5062, https://github.com/emberjs/data/issues/4982.

And maybe @mmun (author of bugfix https://github.com/emberjs/data/pull/5119 in 2.14.10) knows something more and better?

**Comment by stefanpenner** [comment]
Ya it seems quite likely related to https://github.com/emberjs/data/pull/5124, thanks for reporting!

**Comment by johnunclesam** [comment]
@stefanpenner, can you modify that twiddle to use that ember-cli-mirage already there with JSONAPI links method? I don't know how... :(

**Comment by stefanpenner** [comment]
@johnunclesam I'm not sure I have time this week (currently traveling), if you could give it another try that would be quite helpful.

**Comment by stefanpenner** [comment]
[I have a fix](#5147)  for #5124, which _may_ cover this issue. I hope to get that released within a day or so. If you could double check that would be great.

**Comment by johnunclesam** [comment]
Dear @stefanpenner, I tried install the master branch in my repo. Maybe the problem in #5124 s fixed, but mine is still there unfortunately.

I think we should add links example to that twiddle (I wish I could).

I enter the children and if in my hbs put `{{model.category.id}}` I see nothing immediately because it is fetching again the id... and then (after the delay I put on the server side) the id shows up! Really a big bug! :( :( :(

**Comment by stefanpenner** [comment]
> Dear @stefanpenner, I tried install the master branch in my repo.

Thanks for testing that out, to bad it wasn't addressed by the above.

> and then (after the delay I put on the server side) the id shows up! Really a big bug! :( :( :(

Ya, sounds like we will need to investigate.

**Comment by BryanCrotaz** [comment]
Try PR #5257 and see if that fixes your links problems
