### ISSUE TITLE
Could not find module `ember-data/-private`

### ISSUE THREAD

**Issue by royk** [emberjs/data#5163]
This issue was reported and fixed in #5021 
With the latest release of Ember Data it (2.15.0) it happens again. Reverting to 2.14.10 fixes it.
This is my console output when running ember test:
```
---
        actual: >
            null
        expected: >
            null
        stack: >
            http://localhost:7357/assets/test-support.js:5296
        message: >
            Error: 
            Error: Could not find module `ember-data/-private` imported from `ember-data/setup-container`
            TypeError: undefined is not an object (evaluating 'initializer.name')
            TypeError: undefined is not an object (evaluating 'initializer.name')
        Log: |
    ...
```

**Comment by urbany** [comment]
Isn't this a duplicate of https://github.com/emberjs/data/issues/5019 ?

**Comment by Turbo87** [comment]
@urbany https://github.com/emberjs/data/issues/5021 and https://github.com/emberjs/data/issues/5019 were about v2.14.x, and according to https://github.com/emberjs/data/issues/5021 the issue was fixed in v2.14.10. This issue here is about v2.15.x which apparently reintroduced the same problem again...

**Comment by urbany** [comment]
Ah got it, thanks! Maybe #5019 can be closed then.

**Comment by krisselden** [comment]
https://github.com/emberjs/data/pull/5022 fixed the original issue reported (#5019), but it targeted 2.14's release branch and was not ported forward to `beta` or `master` branch.

@rwjblue - Would you mind submitting PR's updating the other branches?

**Comment by rwjblue** [comment]
Further sluething shows it was ported to master in https://github.com/emberjs/data/pull/5031 a few months ago (and is therefore in the current `beta` branch).  It was not ported to the `beta` branch at the time (which was then promoted to `release` for 2.15) and hence has resurfaced...

**Comment by bmac** [comment]
Hi @krisselden thanks for calling this out. It looks like @stefanpenner 
 ported this to `master` in pr https://github.com/emberjs/data/pull/5031 so its on the current `master` and `beta` branches. However its missing form the current `release` branch. I just opened a pr to add to to `release` https://github.com/emberjs/data/pull/5195. I can merge and release it later today.

**Comment by rwjblue** [comment]
@bmac ❤️

**Comment by bmac** [comment]
Release as Ember Data `2.15.3`.
