### ISSUE TITLE
Error deserializing record from server

### ISSUE THREAD

**Issue by CrushedPixel** [emberjs/data#5174]
I'm getting an error similar to #4906 when receiving the following payload from my backend:

```javascript
{ project: 
   { tracks: 
      [ { name: 'Test',
          description: 'test',
          category: 'test',
          file: '9d7ad001-c4c9-4632-a83f-16364d9a28c2',
          extension: '.MP3',
          project: 2,
          createdAt: '2017-09-14T15:37:08.744Z',
          updatedAt: '2017-09-14T15:37:08.744Z',
          id: 28 } ],
     offers: [],
     // [...]
     id: 2 } }
```

I'm using the default `DS.RESTSerializer`. This is the error I get:

```
Assertion Failed: You can no longer pass a modelClass as the first argument to store._buildInternalModel. Pass modelName instead.
    at new EmberError (error.js:38)
    at Object.assert (index.js:142)
    at Object.assert (index.js:17)
    at Class._buildInternalModel (-private.js:12272)
    at Class._internalModelForId (-private.js:10980)
    at Class._pushResourceIdentifier (-private.js:12449)
    at Class._pushResourceIdentifiers (-private.js:12460)
    at ManyRelationship.updateData (-private.js:4672)
    at ManyRelationship.push (-private.js:3990)
    at Relationships.get (-private.js:5027)
defaultDispatch @ ember-metal.js:3988
```

My `project.js` model looks like this:
```javascript
  tracks: DS.hasMany('track', { async: true }),
  offers: DS.hasMany('offer', { async: true }),
  // [...]
```

Interestingly enough, when the payload received from the server contains an empty array for the `tracks` field, no error occurs. This is also the case when removing the `tracks` attribute from the project model.

Removing all attributes from the ember track model results in the same error, so it's probably not the track model's fault.

The weirdest part about this behaviour is that no error is thrown when the `offers` array is non-empty - this behaviour is specific to the `tracks` field.

Any suggestions?

**Comment by pangratz** [comment]
The error message could definitely be improved, but I am taking a wild guess that the `tracks` relationship is not declared as embedded in your serializer, using [`DS.EmbeddedRecordsMixin`](https://emberjs.com/api/ember-data/2.16/classes/DS.EmbeddedRecordsMixin). So you need to specifiy something along the lines:

```js
export default DS.RESTSerializer.extend(DS.EmbeddedRecordsMixin, {
  attrs: {
    tracks: { embedded: 'always' }
  }
});
```
