### ISSUE TITLE
Offline data persistence, maybe pouchdb is not useful? Maybe I need something else?

### ISSUE THREAD

**Issue by johnunclesam** [emberjs/data#5180]
I'm wondering about offline data persistence here:

https://github.com/pouchdb-community/ember-pouch/issues/199

Some hint from you?

**Comment by pangratz** [comment]
Hey @johnunclesam, I think the #ember-data channel on https://embercommunity.slack.com/ is better suited for this kind of question, as we're using GitHub issues to track bugs.

If you want to look into offline storage, take a look at https://github.com/funkensturm/ember-local-storage, maybe that's what your looking for...
