### ISSUE TITLE
Ember Data is failing when findRecord

### ISSUE THREAD

**Issue by Blackening999** [emberjs/data#5182]
It's the findRecord method which is failing.

I have 2 models
- notification-subscription
&
- notification-subscriptions-preset

The error comes from the last item.
It should build an URL to fetch /notification-subscriptions-preset but it trying to fetch by notification-subscription instead.
I think there's an error with parser somewhere

So it comes from
_flushPendingFetchForType method > 
```if (shouldCoalesce) { ...```

then it goes up to

```
 } else if (ids.length === 1) {
          var pair = seeking[groupedInternalModels[0].id];
          _fetchRecord(pair);
        } else {
```

and here it fails. The pair has an incorrect type:
pair.internalModel.type.modelName is "notification-subscription" when it should be "notification-subscriptions-preset"

I'm using ActiveModel Adapter (I know, I know), and I checked the
```
var groups = adapter.groupRecordsForFindMany(this, snapshots);
```

Then I realised that it starts in building model type. I was exhausted debugging so deep, so I'd appreciate any help.

This issue prevents me from upgrading my project to the 2.15 version

Thanks in advance

**Comment by pangratz** [comment]
Can you update [this ember-twiddle](https://ember-twiddle.com/80f1fe8c1b3fac0ce15f85c31a3ff466?fileTreeShown=false&numColumns=2&openFiles=routes.application.js%2Ctemplates.application.hbs) so it demonstrates the issue you're having?

**Comment by Blackening999** [comment]
After a long while, I have fixed the issue.
The problem was with the fact one of our developers extended the model of similar model and it seems like namespace doesn't play the role when it comes to get the internal record name

**Comment by pangratz** [comment]
Thanks for getting back @Blackening999 ❤️ ! Glad you solved it!
