### ISSUE TITLE
FastBoot tests breaking on ember-data canary

### ISSUE THREAD

**Issue by kratiahuja** [emberjs/data#5186]
Seems like this [PR](https://github.com/emberjs/data/pull/5114) introduces usage of `let` which is only allowed in strict mode: https://travis-ci.org/ember-fastboot/ember-cli-fastboot/jobs/279033050 . This is breaking fastboot. 

cc: @runspired

**Comment by kellyselden** [comment]
Duplicate of #5177.

**Comment by bmac** [comment]
@kratiahuja now that https://github.com/emberjs/data/pull/5176 is merged are the fastboot tests working again or do they still break due to Ember Data?

**Comment by kratiahuja** [comment]
Yes fastboot tests are working again. Thank you. This can be closed.
