### ISSUE TITLE
ShouldReload not consistent

### ISSUE THREAD

**Issue by williamhector** [emberjs/data#5194]
The RESTAdapter's shouldReloadAll seems to be inconsistent with shouldReloadRecord.
When shouldReloadAll returns false the first time all model of a particular type are requested, the store returns the cached collection, which is empty because its the first request. (shouldBackgroundReloadAll also false)
However when shouldReloadRecord is false (and shouldBackgroundReloadRecord also false), then the first time a model is requested, it makes an AJAX request to the server.

Twiddle: https://ember-twiddle.com/59ec12e6006eb8b646a5eb355263a4b8?openFiles=adapters.application.js%2C
(uses adapters to mock the AJAX promises)

The behaviour of findAll when shouldReloadAll is false (and shouldBackgroundReloadAll also false) seems to be currently identical to peekAll; only using the cache.

The expected behaviour is that the first findAll for any model should always send an AJAX request to the server, regardless of shouldReload* values.

I am currently working around this by tracking which model types have been requested with findAll, and only returning true the first time:
```
shouldReloadAll: function(store, snapshotRecordArray) {
	return this.modelHasPreviouslyDoneAFindAll(Ember.get(snapshotRecordArray, 'type'));
},
previousFindAlls: null,
modelHasPreviouslyDoneAFindAll: function(modelType){
	if(!this.previousFindAlls){
		this.previousFindAlls = {};
	}
	var modelName = Ember.get(modelType, 'modelName');
	if(!this.previousFindAlls[modelName]){
		this.previousFindAlls[modelName] = true;
		return true;
	}
	return false;
}
```

**Comment by bmac** [comment]
Hi @williamhector. I can understand how the `shouldReloadAll` behavior is confusing and inconsistent and I think you changes would benefit many common use cases out of the box. Unfortunately, it would be difficult to change now without breaking semver.

**Comment by williamhector** [comment]
I only have a basic understanding of semver.

On reflection, this issue seems to be more of a semantic bug than a confusing feature.
The shouldReload* methods should not even be called on the first load, because the first load is not a "reload". On first load, the store should just load.
If this is indeed a bug, should in not be addressed in the next patch or minor release?

What are the problems Ember projects might face if this issue was patched?
From my limited understanding of adapters, the worst thing that would happen is that some project's adapters would make some unnecessary, but not breaking, AJAX requests.

**Comment by runspired** [comment]
The issue here is that it's rather impossible with our current architecture to know if we've made the request before.  We're investigating significant improvements to the `finders` API to resolve these sorts of footguns; however, it is unlikely we change the behavior of `findAll` itself.

I would recommend combining `query` and `peekAll` to have more granular control over the process.
