### ISSUE TITLE
RecordReference & BelongsToReference value() is inconsistent

### ISSUE THREAD

**Issue by xomaczar** [emberjs/data#5207]
If the record does not exist in the store, we get the following:
```
let recordReference = this.store.getReference('book', '1');
recordReference.value() === undefined
```
while belongsToReference
```
let author = this.store.peekRecord('author', 1);
author.belongsTo('book').value() === null
```
The docs treat these too cases the same

**Comment by pangratz** [comment]
Good catch! This seems like a bug since the documentation mentions it should return `null`:

https://github.com/emberjs/data/blob/5fceead8acb53723bdf38daabad00aff093f390a/addon/-private/system/store.js#L981-L984

Wanna submit a bugfix PR?

**Comment by xomaczar** [comment]
Sure - so null everywhere?

**Comment by pangratz** [comment]
Yes. Have you found other `undefined` values for `value()`?
