### ISSUE TITLE
Custom validate method

### ISSUE THREAD

**Issue by wuarmin** [emberjs/data#5215]
Hello!
First..I love ed :)
I want to validate models, which works fine with following solution and the corresponding method at my adapter:
```javascript
export default DS.Model.extend({

  validate(/*options*/) {
    let record = this;
    let store = this.store;
    let modelName = record.constructor.modelName;
    let adapter = store.adapterFor(modelName);
    let serializer = store.serializerFor(modelName);

    return adapter.validate(record.get('id'), modelName, record.serialize()).catch((reason) => {
      let errors = serializer.extractErrors(store, record.constructor, reason, null);
      store.recordWasInvalid(record._internalModel, errors);
      return Ember.RSVP.Promise.reject();
    });
  }

});
```
It works quite well, but I have one issue : If a model-attribute at backend is invalid and the model is opened at frontend to edit, the rootState of the field is "root.loaded.saved". If user clicks "save" and server responds with a model error, the errors are added with: 
```javascript
store.recordWasInvalid(record._internalModel, errors);
```
the problem is that just the errors are added, but transition to rootState "root.loaded.updated.invalid" fails, so rootState stays "root.loaded.saved". The consequent behaviour is, that the errors are not cleared if the user solves the error, because model is in the wrong state. so input field i.e. stays red and user is confused. 
I ended up for now with following solution: 
```javascript
import Ember from 'ember';
import DS from 'ember-data';

export default DS.Model.extend({

  validate(/*options*/) {
    let record = this;
    let store = this.store;
    let modelName = record.constructor.modelName;
    let adapter = store.adapterFor(modelName);
    let serializer = store.serializerFor(modelName);

    record.send('becomeDirty'); //change state manually, to fix my issue 

    return adapter.validate(record.get('id'), modelName, record.serialize()).catch((reason) => {
      let errors = serializer.extractErrors(store, record.constructor, reason, null);
      store.recordWasInvalid(record._internalModel, errors);
      return Ember.RSVP.Promise.reject();
    });
  }

});
```
Now I want to know, what are you thinking about the solution and if there's a better solution for my use-case.
Thank You

**Comment by pangratz** [comment]
Servus!

You're dealing with private API (`record._internalModel`, `store.recordWasInvalid`) so be aware that stuff might be breaking in the future.

The concept of only validating without actual saving the model is not supported in ember-data, so I would take a different approach and not use actual state changes on the model for that, but instead set own properties like `isValidating` and `validationErrors` on the model. By this you're not interacting with any private API, but still get the benefits of the adapter and serializer, as you do already in your code sample.

So basically something like this (not tested):

```js
import Ember from 'ember';
import DS from 'ember-data';

export default DS.Model.extend({

  validate(/*options*/) {
    let record = this;
    let store = this.store;
    let modelName = record.constructor.modelName;
    let adapter = store.adapterFor(modelName);
    let serializer = store.serializerFor(modelName);

    record.set('isValidating', true);

    return adapter
      .validate(record.get('id'), modelName, record.serialize())
      .catch((reason) => {
        let errors = serializer.extractErrors(store, record.constructor, reason, null);
        record.set('validationErrors', errors);
        return Ember.RSVP.Promise.reject();
      })
      .then(() => record.set('isValidating', false));
  }

});
```

---

We're trying to keep GitHub issues for bug tracking, so I am closing this one. If you have further questions, feel free to chime in at the [`-ember-data` channel](https://embercommunity.slack.com/messages/-ember-data/) in the [Ember Community Slack](https://ember-community-slackin.herokuapp.com/).

**Comment by wuarmin** [comment]
Servas!
Thank you! I hoped for such an clear answer. Solving this without dealing with ed-internals is cool!
