### ISSUE TITLE
inverse link payload is overriden when new data payload is pushed

### ISSUE THREAD

**Issue by sly7-7** [emberjs/data#5219]
I find myself in a use case where a link hasMany relationship was not loaded (ie the link was not called. I've finally found the root cause, and wondered if it is expected.
In this line, the payload is totally overriden instead of merged if it existed before (which can be the case if it was a link).
https://github.com/emberjs/data/blob/1fe7e462546a13d9b9ce4b8f4dff388870d631aa/addon/-private/system/relationships/relationship-payloads.js#L296

cc/ @hjdivad

**Comment by urbany** [comment]
Can you provide an example? I didn't understand the scenario.

**Comment by ppcano** [comment]
@sly7-7 Based on your description, #5235 may be the same case.

**Comment by sly7-7** [comment]
@ppcano Thank you, your test is indeed the same use case. I'm closing this one.

**Comment by BryanCrotaz** [comment]
Fixed in #5257
