### ISSUE TITLE
`async: false` and reference api's `load()`

### ISSUE THREAD

**Issue by miguelcobain** [emberjs/data#5226]
I was hoping to completely opt out of async relationships and always use `async: false`.
The reason is that I think this abstraction leaks everywhere. Data access is mixed with data loading, and often gets in the way when trying to manipulate relationships, e.g writing a more complex filter on an async hasMany relationship.

I'd rather keep separate the logic that loads data (i'd put it in the route or even in a component's init) from the logic that actually drives the UI, like computed properties, etc. This would allow me to think async once and always think sync afterwards.

When I looked at the reference API, it seemed like it was the perfect fit for this. However, I found that `model.hasMany('comments').load()` doesn't work with `async: false` relationships. I get the error:
```
You looked up the 'comments' relationship on a 'post' with id 5 but some of the associated records were not loaded. Either make sure they are all loaded together with the parent record, or specify that the relationship is async ('DS.hasMany({ async: true })')
```

My question is: is there a way to use sync relationships with `load()`?
If there isn't, is there an alternative way we can use this pattern?

/cc @samselikoff

**Comment by urbany** [comment]
I think the idea is: if the relationship is async then there is no way to get it separately from the model. If you load a model with a relationship that is async and the payload provides a link for that relationship you see a warning in the console saying something like: "you marked this relationship as async but the payload provides a link to load it, this is probably a mistake".

Anyway I seem to agree with you. Marking it as async shouldn't mean I can't load it separately later. But I might be missing something

**Comment by miguelcobain** [comment]
Update: ember-data-storefront addresses exactly this use case https://github.com/EmberMap/ember-data-storefront

**Comment by runspired** [comment]
I'm walking back my previous statement that we should make this work, because after doing a lot of work in this area of the codebase I've realized that both semantically and practically there is no possible way this could ever work.

That said, it is very easy (and will be supported, although #5548 surfaces a needed bugfix) to use `ref.reload()`.
