### ISSUE TITLE
json-api "links" for pagination are being set to null

### ISSUE THREAD

**Issue by erichonkanen** [emberjs/data#5236]
EDIT: See bottom.

Today I upgraded from ember-data 2.12.1 to the latest 2.17.1beta (along with source), I am now noticing that my pagination has broken.

In the following code, `res.links` is null, despite the server having returned links. The only serializer file I have is the generated ApplicationSerializer that sets it to JSONAPISerializer.

```
    return this.get('store')
      .query(model, this.get(`pageData.${model}.opts`))
      .then((res) => {
        this._cacheQueryOpts(model, type, {}, res.links); // res.links = null
        return RSVP.resolve(res);
      })
```
![image](https://user-images.githubusercontent.com/230757/31802602-fb5ca5ce-b503-11e7-9ff6-88fbac0fc234.png)

I tried overriding the `ApplicationSerializer.normalize()` method to add a debugger and see if the links came through there and they do come through there. I'm almost certain nothing else has changed in my app but unless anyone has an idea of how it could be getting set to null then I'm assuming something in the latest version is doing it...

Thanks

EDIT1: I have gone back and confirmed that this problem began at `ember-data@2.15.1`. Previous versions did indeed automatically include the `links` data for a json-api response.

EDIT2: I have pinned down the general area where it goes wrong [here](https://github.com/emberjs/data/blob/4b419d91b3773a4b78412bd963ebbe16cb2423ff/addon/-private/system/record-array-manager.js#L371). `links` is always null there despite `payload.links` having a value (`{next: 'v1/foo', prev: null}`)

**Comment by erichonkanen** [comment]
I think I've identified the source of the problem here:

https://github.com/emberjs/data/blob/master/addon/-private/system/record-arrays/adapter-populated-record-array.js#L52

@stefanpenner do you know why you are always setting `links = null`? It is overriding pagination links in the server response and causing this bug...

I went back and verified that by commenting out the above line, the `links` attribute it set properly and it fixes the bug...

**Comment by sly7-7** [comment]
closed by https://github.com/emberjs/data/pull/5263

**Comment by rwwagner90** [comment]
Is this released in any version yet? I'm still experiencing this issue.

**Comment by beerlington** [comment]
@rwwagner90 I tried upgrading to 2.18 but am still seeing this issue even though the supposed fix was merged before this version was released. Is that what you're experiencing too?

**Comment by erichonkanen** [comment]
@beerlington it looks like it made it into the 3.0 beta release https://github.com/emberjs/data/blob/v3.0.0-beta.1/addon/-private/system/record-arrays/adapter-populated-record-array.js

**Comment by rwwagner90** [comment]
Yes, I can confirm it is in 3.0 beta. Thanks @erichonkanen!
