### ISSUE TITLE
provide better documentation for serializing nested relationships with JSONAPISerializer

### ISSUE THREAD

**Issue by efx** [emberjs/data#5244]
The last line of [the 2.16 API docs for serialize](https://emberjs.com/api/ember-data/2.16/classes/DS.JSONAPISerializer/methods/serialize?anchor=serialize) reads: 

> By default, belongs-to relationships are converted into IDs when inserted into the JSON hash.

If you need to override this behavior, it is unclear where to start or if it is even possible using public methods. A use case I had was to serialize a parent -> child -> grandchild relationship in one payload. See @frank06's [excellent post](https://emberigniter.com/saving-models-relationships-json-api/) demystifying how to achieve this with a mixin. I think the documentation should  provide a caveat or a best-practice from the core team.

(As an aside, I searched for similar issues using this: https://github.com/emberjs/data/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20serialize%20nested)

**Comment by runspired** [comment]
Ultimately, only one method is called for serialize. Serialize. :P Any other hook that happens to get called is just sugar, and doesn't need to be.  Think of it this way, if you want `serialize` to be a "pure function", it can be. We give it some inputs, we get a serialized record back, as far as we care that is the end of it.

If you need to do this sort of custom serialization, do so!  (I agree the post is excellent btw).

**Comment by frank06** [comment]
@runspired Thanks, it's been a long time since I wrote that. Is there a clean way to "link" the serialized nested resources to the response from the JSON API server?  Order in the response is not reliable (or is it?) and the workaround I found was passing along the `internalModel` id

**Comment by runspired** [comment]
@frank06 your solution is the ideal one, although there is also now a spec for it which we will converge on in ED proper: https://github.com/json-api/json-api/pull/1254

Look at the `lid` for solving this issue, it is the same concept as your `__id__`
