### ISSUE TITLE
push()ing json-api data with links causes infinite recursion

### ISSUE THREAD

**Issue by BryanCrotaz** [emberjs/data#5251]
creating the record causes fetchLinks which causes a snapshot to be created, which recreates the same record... ad infinitum

ED 2.13.2

**Comment by BryanCrotaz** [comment]
not sure yet how to repro this - fails in a very complex app

**Comment by runspired** [comment]
@BryanCrotaz did you ever manage to figure out a replication?

**Comment by runspired** [comment]
Closing this as there have been no other reports and attempts at simple replications do not reproduce it.
