### ISSUE TITLE
Ember Data FEATURES aren't merged with Ember FEATURES

### ISSUE THREAD

**Issue by alexander-alvarez** [emberjs/data#5253]
There a feature in `ds-check-should-serialize-relationships` which has been `true` since `ember-data 2.12` https://github.com/emberjs/data/blob/v2.12.0/config/features.json#L7

My interpretation of https://guides.emberjs.com/v2.16.0/configuring-ember/feature-flags/#toc_flagging-details leads me to believe that I should be able to use said feature in a non-beta (and non-canary) release of Ember. 

I haven't gotten this to work

https://github.com/alexander-alvarez/ds-features-not-enabled/commit/d89e7f3b9dd3884db3284b652cb071e4bbf59928 **reproduces** it on `ember: 2.15.x` and `ember-data: 2.15.x`

**My diagnosis**

This check https://github.com/emberjs/data/blob/master/addon/serializers/json-api.js#L582 fails

When I dump `Ember.FEATURES` I get
```json
{
  "ember-libraries-isregistered":false,
  "ember-improved-instrumentation":false,
  "ember-metal-weakmap":false,
  "ember-glimmer-allow-backtracking-rerender":false,
  "ember-routing-router-service":true,
  "ember-engines-mount-params":true,
  "ember-module-unification":false,
  "glimmer-custom-component-manager":false,
  "mandatory-setter":true,
  "ember-glimmer-detect-backtracking-rerender":true
}
```
which are the features enabled in https://github.com/emberjs/ember.js/blob/v2.15.1/features.json

Should it not also contain the features in ember-data's `features.json`?

**Comment by runspired** [comment]
@rwjblue we removed all of our feature flags, but we should still get this fixed before we add any new ones.

**Comment by runspired** [comment]
Feature flag infra was later improved to not require merging with Ember's.
