### ISSUE TITLE
Replace Ember.Map/OrderedSet with native Map/Set classes

### ISSUE THREAD

**Issue by Turbo87** [emberjs/data#5254]
`ember-data` is currently using `Ember.Map` and `Ember.OrderedSet`, which are close approximations of the native `Map` and `Set` classes introduced in ES2015. It seems that `ember-data` is the only major user of these classes and Ember is not even using them itself anymore and would like to get rid of them.

Since 3.0 is around the corner it might make sense to reevaluate the usefulness of these polyfills as IE11 already has somewhat usable native `Map` and `Set` support (see http://kangax.github.io/compat-table/es6/#test-Map).

As some public methods of `ember-data` return instances of `Map` and `MapWithDefault` this would probably have to be considered a breaking change 🤔

**Comment by rwjblue** [comment]
I submitted #5255 to migrate away from `Ember.Map` and `Ember.MapWithDefault` (to native `Map`), however after discussing with @hjdivad I believe that we will still have a need for `@ember/ordered-set` ([the addon](https://github.com/emberjs/ember-ordered-set/issues/11)) as a custom data store for the ember-data relationship data (e.g. an array like with fast membership lookup for large relationships).

**Comment by Turbo87** [comment]
@rwjblue as mentioned in https://github.com/emberjs/ember-ordered-set/issues/14 it seems that the differences between `OrderedSet` and `Set` are quite small, what is the specific difference that makes it necessary to keep `OrderedSet` around?

**Comment by hjdivad** [comment]
@Turbo87 https://github.com/emberjs/data/blob/master/addon/-private/system/ordered-set.js#L19

The order is not always insertion order.  When inserting into a `hasMany` it is possible to insert at an arbitrary index.  The relationships code currently assumes its set `members` has the same order as the many array.

**Comment by Turbo87** [comment]
@hjdivad okay, so we are actually talking about `EmberData.OrderedSet` 😉

**Comment by Turbo87** [comment]
this is somewhat important though because in that case the code for `OrderedSet` could just live inside of Ember Data instead of having a dedicated addon just for that class

**Comment by rwjblue** [comment]
@Turbo87 - Confirm, but I was just going to use the addon simply because it was already done and tested (thanks!)...
