### ISSUE TITLE
DEPRECATION: `ember-cli/ext/promise` is deprecated, use `rsvp` instead. Required here:    Object.<anonymous> (/home/travis/build/emberjs/data/node_modules/ember-cli-blueprint-test-helpers/lib/helpers/setup.js:3:24)

### ISSUE THREAD

**Issue by BryanCrotaz** [emberjs/data#5259]
Happens in production build on travis

**Comment by rwjblue** [comment]
We need to update ember-cli-blueprint-test-helpers to the latest version to fix the deprecation...

**Comment by bmac** [comment]
I've opened https://github.com/emberjs/data/pull/5264 to fix this issue.
