### ISSUE TITLE
Could not find module `ember-data/-debug` imported from `ember-data/-private`

### ISSUE THREAD

**Issue by mitchiru** [emberjs/data#5262]
I upgraded to

Ember             : 2.16.2
Data        : 2.16.3
jQuery            : 3.2.1
Ember Simple Auth : 1.4.0

when serving my app, I have no problem. However, when I make a build the build has an JS error as stated in the subject.

I tried npm clear and all that stuff. I moved ember source from bower to npm as suggested.

I've seen several commits to this kind of issue but here I am still. I tried also canary and other versions.

What else can I do / try?

**Comment by mitchiru** [comment]
Only going back to 2.13.0 solved my issue:

npm install --save ember-data@2.13.0

**Comment by mitchiru** [comment]
I found a hint using ember data 2.14.10: If the environment is production, the error does not occur.

I have multiple environments which I am building and apparently on production it kind of never appears.

**Comment by bmac** [comment]
@mitchiru What version of ember-cli are you using? I started to try to put together a reproduction of the issue here https://github.com/bmac/issue-5262 using ember-cli 2.16.2 but I wasn't able to reproduce.

**Comment by mitchiru** [comment]
I always tried with ember-cli 2.16.2 first and could reproduce the error with several ember-data versions like 2.14.10 and 2.16.3

I think, the major issue is here, if I use e.g. environment=customenvironment, with environment=production it didnt occur.

**Comment by mitchiru** [comment]
I think I nailed it down.

my environment is called productionhh I get the error in the build, when I use somethingelse as env, it works.

**Comment by rwjblue** [comment]
Checkout https://github.com/emberjs/data/issues/5233, and specifically https://github.com/emberjs/data/issues/5233#issuecomment-337444450:

> To be clear, ember-cli only supports three specific build environments: `test`, `development`, and `production`. Deployment environments are a very different thing (the ember-cli-deploy folks actually have a [nice section on their site](http://ember-cli-deploy.com/docs/v1.0.x/configuration/#additional-environments) about this exact thing).

**Comment by mitchiru** [comment]
Awesome feedback. THX a lot!
