### ISSUE TITLE
Big memory leak using iframes

### ISSUE THREAD

**Issue by BryanCrotaz** [emberjs/data#5266]
create and destroy components that include an iframe and we get an enormous memory leak each time.

Twiddle:
https://ember-twiddle.com/b1ce25d3c3fd4a1db41750ca37b316c3?openFiles=components.iframe-display.js%2Ctemplates.components.iframe-display.hbs

**Comment by stefanpenner** [comment]
I'm not sure this is ember-data specific. Did you mean to open on ember?

**Comment by stefanpenner** [comment]
Also, I would request that when opened some minimal reproduction (that isn't nested within other frames like embertwiddle) be provided. It will likely help diagnose quickly.

I did take a quick look at the twiddle, but couldn't immediately see ember stuff leaking.

**Comment by stefanpenner** [comment]
I'm locking this, only because I believe it to be on the wrong location and want to prevent further discussion here.
