### ISSUE TITLE
Uncaught TypeError: Cannot read property 'data' of undefined at isInverseRelationshipInitialized

### ISSUE THREAD

**Issue by lolmaus** [emberjs/data#5270]
Tried upgrading an addon from `2.6` to `2.16`+ and it crashes with:

```
Uncaught TypeError: Cannot read property 'data' of undefined
    at isInverseRelationshipInitialized (-private.js:12687)
    at -private.js:12729
    at Array.forEach (<anonymous>)
    at setupRelationships (-private.js:12727)
    at Class._setupRelationships (-private.js:12313)
    at invoke (backburner.js:257)
    at Queue.flush (backburner.js:151)
    at DeferredActionQueues.flush (backburner.js:328)
    at Backburner.end (backburner.js:461)
    at Backburner.run (backburner.js:533)
````

The offending line is: https://github.com/emberjs/data/blob/v2.18.0-beta.1/addon/-private/system/store.js#L2838

My `data.relationships` object looks like this:

```js
{
  classes: undefined,
  file: {
    data: {
      id: "addon/trigger.js",
      type: "yuidoc-file"
    }
  },
  namespaces: undefined,
  submodules: undefined,
  version: {
    data: {
      id: "lolmaus/ember-element-query/gen-1",
      type: "yuidoc-version"
    }
  },
}
```

I. e. some properties do appear on the object, but their values are `undefined`.

The last stable `ember-data` minor version that the issue does not happen for me is `2.15`.

You can review my model definitions here: https://github.com/lolmaus/yuidork/tree/gen-1/addon/models

**Comment by lolmaus** [comment]
This is yet another Ember Data regression. :astonished: :gun:

**Comment by lolmaus** [comment]
On `2.15.3` Ember Data crashes with `relationshipData` being `undefined` at:

https://github.com/emberjs/data/blob/v2.15.3/addon/-private/system/relationships/relationship-payloads.js#L227

The last working minor version is `2.13`.

**Comment by runspired** [comment]
@lolmaus that is an invalid payload. That it happened to work in the past is interesting, likely the method of iteration changed. json-api spec for relationships states they must either be null or an object with links or data. I would recommend converting `undefined` to `null` in your serializer or deleting the keys set to undefined.
