### ISSUE TITLE
RecordArrayManager._syncLiveRecordArray trigger unexpect didChange cause EMBER_GLIMMER_BACKTRACKING_RERENDER 

### ISSUE THREAD

**Issue by ispiders** [emberjs/data#5271]
### Twiddle first:
[https://ember-twiddle.com/eddfe31a08d04ea9301b7a7ec77d2413](https://ember-twiddle.com/eddfe31a08d04ea9301b7a7ec77d2413)

Please run this twiddle and check console for error detail.

### Based on my research, this issue apears to be related to `RecordArrayManager.prototype._syncLiveRecordArray` method

```javascript
RecordArrayManager.prototype._syncLiveRecordArray = function _syncLiveRecordArray(array, modelName) {
    (true && !(typeof modelName === 'string') && Ember.assert("recordArrayManger.syncLiveRecordArray expects modelName not modelClass as the second param", typeof modelName === 'string'));

   
    var hasNoPotentialDeletions = Object.keys(this._pending).length === 0;
    var map = this.store._internalModelsFor(modelName);
    var hasNoInsertionsOrRemovals = get$10(map, 'length') === get$10(array, 'length');

    /*
      Ideally the recordArrayManager has knowledge of the changes to be applied to
      liveRecordArrays, and is capable of strategically flushing those changes and applying
      small diffs if desired.  However, until we've refactored recordArrayManager, this dirty
      check prevents us from unnecessarily wiping out live record arrays returned by peekAll.
      */
    if (hasNoPotentialDeletions && hasNoInsertionsOrRemovals) {
      return;
    }
    
     // MY COMMENT: hasNoPotentialDeletions is false because some async relationships are trying to fetch data
    var internalModels = this._visibleInternalModelsByType(modelName);
    var modelsToAdd = [];
    for (var i = 0; i < internalModels.length; i++) {
      var internalModel = internalModels[i];
      var recordArrays = internalModel._recordArrays;
      if (recordArrays.has(array) === false) {
        recordArrays.add(array);
        modelsToAdd.push(internalModel);
      }
    }

    // MY COMMENT: even if modelsToAdd is an empty Array, it triggers didChange event
    array._pushInternalModels(modelsToAdd);
  };

**Comment by ispiders** [comment]
UPDATE:
I dug more today. And the issue apears to be related to using `store.peekAll(sameModelName)` multiple times in a single render process. Which will cause `liveRecordArrayFor` to trigger `_syncLiveRecordArray`.
This means some multi `get` method could triggers `set` process, which means changes happening in render process. 

So, in my twiddle demo, the workaround is to use a single global peekAll('user'), the error will be gone.

**Comment by tylerturdenpants** [comment]
try pull #5378

**Comment by runspired** [comment]
@ispiders #5378 should resolve this

**Comment by ispiders** [comment]
ok, thanks

**Comment by miketervela** [comment]
Is there any solution for this going back to a 2.18 LTS?  We're at Ember Data 2.18.3 and not ready for 3.x yet, but getting nailed by this issue.  Right now trying to refactor all of our peekAlls into a service but every time I fix one source another pops up.

**Comment by tylerturdenpants** [comment]
@miketervela have you at least tried ED 3.2 in your app?

**Comment by miketervela** [comment]
I had tried upgrading, and had encountered some problems that I wasn't able to track down at the time.  I tried again and think I resolved the problem.  Going to spend some more time verifying 3.2 will work for me, but so far so good.
