### ISSUE TITLE
How to set id of model to integer?

### ISSUE THREAD

**Issue by devdemi** [emberjs/data#5279]
In my serializer I orverwrote `extractId` method:
```
    extractId(modelClass, resourceHash)  {
        let id = this._super(...arguments);
        return parseInt(id, 10);
    },
```

> Ember | 2.17.0
> Ember Data | 2.17.0

And when I try to get id of model `this.get('model.id')` I get string value. I always want to get an integer type of model's id.
Please help me to find solution of my problem.

**Comment by kjhangiani** [comment]
Our solution for this was to do the following in app.js:

```
DS.Model.reopen({
	intId: Ember.computed(
		'id',
		function() {
			if (!this.get('id')) { return null; }
			return parseInt(this.get('id'), 10);
		}
	),
});
```

which adds a computed property to every model, then use `model.intId` where we needed an integer.

**Comment by bmac** [comment]
One of Ember Data's constraints is every record has and id property and it is always a string. 

If you need the id to be an integer in your Ember app you can use @kjhangiani's suggestion of creating a computed property to transform the id into an integer. 

If you need the id to be an integer when sending the data to your backend you can define a custom serializer, to transform the id to an integer before sending it to the backend.

Those 2 techniques should solve 90% of the use-cases where you need to us an `id` as an integer. I don't think Ember Data will support non string `id` properties on records.
