### ISSUE TITLE
Possible race condition in relationships

### ISSUE THREAD

**Issue by NLincoln** [emberjs/data#5295]
We discovered this all the way back in ember-data@2.14(?), in prod. Since that time we've been locked at ember-data@2.12. Twiddle is running canary and I've also repro'd in 2.17

# Repro URL

https://ember-twiddle.com/8e76a1c6df824b8c13945bd7f4bd7f86?openFiles=templates.application.hbs%2C

# Background
Users are grouped into "groups". Groups have a head user who might not be a part of the group (this is weird but it makes sense in our app). Relationships are set up accordingly. When a user loads up our app one of the earliest routes will load both their user, and the group they belong to. Sometime later we load the groups head user and display that on our app for the users. 

# The bug
If the users group is loaded before the user model, then the groups head user will be set to the session user instead of the head user.

# Some things I've found
- The store is definitely populated wrong. I checked in the ember inspector in our own app and all the relationships are messed up. 
- When this bug is hit, the head user won't be fetched from the api at all. (so there will only be 2 fetches instead of the expected 3. I think this is a symptom though)
- In the twiddle above, commenting out the group belongsTo in the user model will cause the bug to not happen

**Comment by NLincoln** [comment]
I've spent a few hours trying to track down where this happens, and I think I've tracked it down to the following line:
https://github.com/emberjs/data/blob/d829b4b8ecd0009c5385a8a1c416ec4853b14ce3/addon/-private/system/relationships/relationship-payloads-manager.js#L121

However that only seems to be adding things to an array(????).

I'd appreciate some help in tracking this down, we can't upgrade above 2.12 because of this bug. I'm also worried that even if I find out what is causing this bug, I won't be able to fix it without breaking something else.

**Comment by NLincoln** [comment]
Marking the either one of the `belongsTo` as `{ inverse: null }` is a workaround for the bug

**Comment by NLincoln** [comment]
Are there any more details I can add?

**Comment by NLincoln** [comment]
I'd like to reiterate: I have spent several hours trying to track down this issue, with no success. If there's anyone more familiar with this codebase that would be willing to point me in the general direction here, I would be more than happy to PR a fix.

**Comment by fabriciotav** [comment]
I've run into the same issue with ember-data 2.14. To work around (for now) I've set `{ inverse: null }` in all relationships.

**Comment by NLincoln** [comment]
I've been considering doing that, but after debugging the issue for awhile I'm worried that it's a fragile solution that will only break things further and in even more unexpected ways.

**Comment by sly7-7** [comment]
@NLincoln Unfortunately, I have a problem using the twiddle, 'cannot import ember-data' 😞

**Comment by NLincoln** [comment]
@sly7-7 Yeah... it looks like ember-twiddle is broken. If you go to the base RESTAdapter twiddle found [here](https://github.com/emberjs/data/blob/master/CONTRIBUTING.md#reporting-a-bug), you'l l get the same error.

**Comment by NLincoln** [comment]
Should be fixed by https://github.com/emberjs/data/pull/5230
