### ISSUE TITLE
Support nested JSON objects

### ISSUE THREAD

**Issue by devinus** [emberjs/data#53]
E.g.:

``` json
{
  name: {
    first: 'Devin',
    last: 'Torres'
  }
}
```

Thoughts:
1. `name: DS.attr('object')`
2. `firstName: DS.attr('string', { key: 'name.first' })`

Justification:

Nested JSON objects are too prevalent to require transforming them every time they're used. Models should model the data, not some transformed representation you morph in adapter, and hopefully not through hundreds of transformers.

**Comment by lolmaus** [comment]
So what is the recommended way for having an arbitrary JSON-like object as an attribute?

**Comment by simonoff** [comment]
@lolmaus use backbone.js :)

**Comment by bmac** [comment]
@lolmaus Currently the best way to have an arbitrary JSON-like object as an attribute is use `DS.attr()` as suggested by @jasonkriss.
> If you just want to have nested objects/arrays, you should be able to just declare the attribute as DS.attr(). This will pass the raw data through untouched. The catch is that dirty tracking will not work for that attribute.

**Comment by lolmaus** [comment]
@bmac, say, from that JSON-like attribute i render a complex editing form with various types of controls: checkboxes, text fields, select lists...

After a user has changed a value of a control, Ember will update the object corresponding to the control's value. But the attribute containing that object will not be dirtied and the user's edit will not propagate.

So all i need is to dirty the attribute whenever the user modifies a control, and everything will be okay, right?

If yes, then the question is how do i dirty the attribute and how do i do it *after* Ember saves the value of the child object of the attribute.

**Comment by alvincrespo** [comment]
@lolmaus Might be good to have a jsbin w/ an example use case?

**Comment by bmac** [comment]
@lolmaus Unfortunately I do not know of a good way to mark the parent object as dirty.

**Comment by elwayman02** [comment]
https://github.com/lytics/ember-data.model-fragments was the way to go for us, @lolmaus

**Comment by lolmaus** [comment]
@elliterate, model-fragments claims to be incompatible with the current version of Ember Data. I also find it risky to depend on a third party extension that hacks Ember internals: even after becoming compatible, it might break with next update of Ember Data.

I managed to come up with a solution using native Ember features: http://emberjs.jsbin.com/vapama/1/edit?html,js,output

Highlights:

* The model has a JSON-like attribute `thedata`.
* The template renders checkboxes for every item contained by the attribute. Each checkbox has `checked` set to the corresponding item.
* Checkboxes are customized `Ember.Checkbox` that send a `stain` action to the controller on change.
* When the action is triggered, the controller marks the record as dirty.
* For the controller to know which record to stain, i have to pass the record from the template to the checkbox, and the checkbox has to pass the record to the triggered action.

The latter will require a lot of utility code, so don't hesitate to suggest a more concise approach if you have something in mind.

**Comment by lolmaus** [comment]
Here's a slightly more compact version: http://emberjs.jsbin.com/vapama/3/edit?html,js,output

Instead of having the checkbox ask the controller to stain the record, the checkbox stains the record itself.

**Comment by lolmaus** [comment]
An even shorter version, now reusing the input helper rather than subclassing it: http://emberjs.jsbin.com/vapama/4/edit?html,js,output

Can you guys please review this and tell your opinion on whether it's an appropriate solution?

**Comment by lolmaus** [comment]
Okay, this works in a JSBin, but in real-life scenario this approach requires so much utility code that it becomes simpler, more error-proof and definitly more Ember-way to use nested models.

**Comment by lolmaus** [comment]
Yay, Model Fragments have been updated to support Ember Data beta 14! :D

**Comment by JKGisMe** [comment]
I'm also trying to do a `DS.attr('json')` type thing to send back to the Rails backend. My situation is very similar to that of @alvincrespo where the user needs to be able to specify the key and the value. In my case we need the user to be able to specify multiple key/value pairs if needed. I'm hesitant to try ModelFragments because I'm wary of adding more dependencies.

**Comment by slindberg** [comment]
@JKGisMe I have the same need in my app for which model fragments works well. I understand your reluctance to add more dependencies, but model fragments was born out of your exact need. Ember Data may one day support nested id-less records like this, but that day is far in the future.

If you are interested, this is the rough pattern I'm using:

`app/models/thing.js`

```javascript
export default DS.Model.extend({
  config: DS.hasManyFragments('config_field')
});
```

`app/models/config-field.js`

```javascript
export default DS.ModelFragment.extend({
  name: DS.attr('string'),
  value: DS.attr('string')
});
```

`app/templates/thing.hbs`

```handlebars
{{each config as |config|}}
  <div class="form-control">
    <label>{{config.name}}</label>
    {{input value=config.value}}
  </div>
{{/each}}
```

This will serialize `thing` records with a `config` property that is an array of objects with `name` and `value` properties. If your API expects an object, you can override the `thing` serializer:

`app/serializers/thing.js`

```javascript
export default DS.RESTSerializer.extend({
  serializeAttribute: function(snapshot, json, key) {
    if (key === 'config') {
      json.config = snapshot.attr('config').reduce(function(config, fieldSnapshot) {
        config[fieldSnapshot.attr('name')] = fieldSnapshot.attr('value');
        return config;
      }, {});
    } else {
      this._super.apply(this, arguments);
    }
  }
});
```

**Comment by igorT** [comment]
:+1: for model fragments

**Comment by lodr** [comment]
Hi people. I'm following this approach. In my case I want to store a _info_ object for a _channel_ entity I'm working on:

```js
var Channel = DS.Model.extend({
  name: DS.attr('string'),
  info: DS.attr({ defaultValue: () => Info.create() })
});

var Info = Ember.Object.extend({
  version: DS.attr('string'),
  description: DS.attr('string')
});
```

What is bad about this approach?

Thank you.

**Comment by igorT** [comment]
Well, I have no idea what happens when you put a DS.attr inside something that is not a `DS.Model` it definitely isn't a supported use case. You could have Info be a normal object, but you don't get dirtyness/rollback and some of the normalization/serialization niceties, but it definitely works for simpler use cases

**Comment by JKGisMe** [comment]
Thank you @slindberg I didn't see this earlier!. That looks very clean and probably would have worked great. The specs for our project changed a little and I ended up just making a whole new model & accompanying component in Rails & Ember which I then convert to customized JSON in the end from Rails.

**Comment by billpull** [comment]
Is ember-data-model-fragments now incompatible with ember-data `1.13.2`

**Comment by igorT** [comment]
It will be compatible soon

**Comment by boehlke** [comment]
Hello guys, I followed this discussion because I have the same use case (nested documents).
After some thinking, I decided the solve the problem by creating a server-side component which flattens the data so that it can be used with ember-data.
My input to this discussion: Probably you do not want embedded records in the first place. Think about the complexity you introduce the your ember app. It is probably better handled on the server.

Having said that, I vote against having model-fragments in ember-data.
:-1:

**Comment by lolmaus** [comment]
@boehlke You assume that any data can be flattened, but that's absolutely not the case.

**Comment by boehlke** [comment]
@lolmaus Sorry, I cannot think of an example JSON object which cannot be flattened. Can you provide one? Probably that's easier than for me to prove that every JSON can be flattened. Thanks!

**Comment by wildchild** [comment]
This thread is turning into masturbation. Embedded objects are parts of JSON documents. If ember won't support it, fuck it. This framework is too "idiomatic" to be usable.

**Comment by lolmaus** [comment]
@boehlke Imagine a hash that has arrays which contain hashes which contain arrays of hashes.

You can of course undestructively flatten it by producing really elaborate key names. But working with such a flat structure from Ember will be a nightmare. You won't be able iterate over specific sub-arrays, etc. That's just not a working solution.

**Comment by stefanpenner** [comment]
The reality is, depending on the scenario people want both flattened and nested structures.

> If ember won't support it, fuck it.

Ember works fine with deeply nested data-structures out of the box.

Ember-data also works with deeply nested data-structures, i believe the pain people are noticing. Is they want there nested blobs to behave like ember-data models, in both a read and right fashion. Ember-data today, is largely the following units (on top of ember), and models have nice patterns, such as:

1. an identity map (to ensure you are always dealing with a single canonical entity)
2. a set of adapters (to normalize foreign endpoints/api)
3. a set of serializers (meant to contain all logic related to transformation of data to/from the server)
4. a mechanism of relationship syncing
5. a mechanism to detect changes, and the ability for a developer to commit said changes back a foreign data-store

Expanding these patterns to the nested id'less entities, is something we are interested in exploring. the model-fragments project is showing promise, and is a very intriguing interpretation of the problem. Unfortunately, it relies on private API and monkey patching to accomplish its goal. One of our goals moving forward is, to ensure a stable public API for model-fragments. This will prevent the upgrade turmoil currently introduced.

Now as for model-fragments becoming part of ember-data itself, it's too soon to know for sure. It is great to push this logic into user-space, as it will come with some caveats (and the problem space needs some more fleshing out) The important part today is for both model-fragments and ember-data to work better in tandem. This will allow the flexibility for authors to experiment, but also the stability to ship real projects with it.

**Comment by fivetanley** [comment]
@wildchild I would advise you to read the community guidelines. I do not mean to belittle your frustration but this kind of behavior is not acceptable in the ember community. http://emberjs.com/guidelines/

**Comment by devinus** [comment]
@stefanpenner 

> Ember works fine with deeply nested data-structures out of the box.

I just ran into this last night:

`{{upload-field inputId="desktop-hero" accept="image/*" signURL=signURL uploadedURL=model.templateSettings.context.hero.src}}`

Because `model.templateSettings = {}` and `model.templateSettings.context.hero` doesn't exist yet, the value is never updated.

I am forced to do this as a workaround in `afterModel`:

```js
    if (isNone(get(model, 'templateSettings.context.hero'))) {
      set(model, 'templateSettings.context.hero', {});
    }
```

**Comment by stefanpenner** [comment]
@devinus a better place would be to add that to your serialization code.

**Comment by devinus** [comment]
@stefanpenner What question?

**Comment by daminufe** [comment]
:+1:

**Comment by aivanov93** [comment]
@lolmaus I'm having trouble figuring out how to nicely flatten a JSON.
I have a similar problem to this SO question http://stackoverflow.com/questions/25220442/json-api-and-translations-with-ember-data and I really like the first answer with nesting everything under the translations field. 
Sure, I could flatten everything to `title_en`, `title_fr`, but this way on a change of locale, I would have to manually change all the fields.
Any nice solution to this case?

**Comment by lolmaus** [comment]
@aivanov93 [ember-data-model-fragments](https://github.com/lytics/ember-data-model-fragments) seem to fit nicely into your use case.

But I would attempt a completely different solution. I would split the model into two parts, e. g. `post` and `post-translation`. A single post would look like this then:

```js
{
  id: '1'
  type: 'post',
  relationships: {
    translations: [
      {id: '1', type: 'post-translation'},
      {id: '2', type: 'post-translation'}
    ]
  }
}

{
  id: '1'
  type: 'post-translation',
  relationships: {
    post: {id: '1', type: 'post'}
  },
  attributes: {
    lang: 'en',
    title: 'Hello world!',
    body: "Wonderful weather we have today, don't we?"
  }
}

{
  id: '2'
  type: 'post-translation',
  relationships: {
    post: {id: '1', type: 'post'}
  },
  attributes: {
    lang: 'ru',
    title: 'Здравствуй, мир!',
    body: 'Чудесная погодка сегодня, не так ли?'
  }
}
```
