### ISSUE TITLE
hasMany relationship singularizes realtionshipMeta.type

### ISSUE THREAD

**Issue by Frozenfire92** [emberjs/data#5314]
From what I can tell this is an undocumented thing [1](https://emberjs.com/api/ember-data/2.16/classes/DS/methods/hasMany?anchor=hasMany) [2](https://guides.emberjs.com/v2.18.0/models/relationships/) and really threw me for a loop.

### Example
```sh
ember g route application
ember g model a
ember g model b/a
ember g model b/ta
ember g model b/c
ember g model c
ember g model ta
ember g model ata
```

```js
// app/models/a.js
import Model from "ember-data/model";
import { hasMany } from "ember-data/relationships";
import { computed, get } from '@ember/object';

export default Model.extend({
  ba: hasMany('b/a'),
  bc: hasMany('b/c'),
  c: hasMany('c'),
  bta: hasMany('b/ta'),
  ta: hasMany('ta'),
  ata: hasMany('ata'),

  collection: computed(
    'ba.[]',
    'bc.[]',
    'c.[]',
    'bta.[]',
    'ta.[]',
    'ata.[]',
    function () {
      // Works
      console.log('ba', get(this, 'ba'));
      console.log('bc', get(this, 'bc'));
      console.log('c', get(this, 'c'));
      // Breaks
      // console.log('bta', get(this, 'bta'));
      // console.log('ta', get(this, 'ta'));
      console.log('ata', get(this, 'ata'));
    }
  )
});
```

```js
// app/routes/application.js
import Route from '@ember/routing/route';

export default Route.extend({
  model() {
    return this.store.createRecord('a');
  },
  actions: {
    test() {
      this.controller.get('model.collection');
    }
  }
});
```

```hbs
{{!-- app/templates/application.hbs --}}
<button {{action 'test'}}>Click me</button>
```

which throws the following Ember error

`No model was found for 'atum'`

### The offending code

https://github.com/emberjs/data/blob/0999f8a0a756a3118f1e6a4e110709be72e1ad3e/addon/-private/system/relationship-meta.js#L5-L13

### Potential fixes

1. Document this behavior
2. Add support to skip this behavior

```js
// addon/-private/system/relationship-meta.js
if (meta.kind === 'hasMany' && !meta.options.skipSingularization) {
  modelName = singularize(normalizeModelName(modelName));
}
```
```js
// app/models/a.js
ata: hasMany('ata', { skipSingularization: true }),
```

I'm happy to do a PR for 2. if this is a good approach

**Comment by runspired** [comment]
@Frozenfire92 ember-data requires types to be singular-dasherized internally and converts all model-names to such when they enter the store. You can add an inflector rule to specify `ata` as `uncountable` or customize that transformation. See `ember-inflector` for more.

**Comment by runspired** [comment]
Closing. This is documented here but additional documentation is always welcome; https://guides.emberjs.com/v3.0.0/models/customizing-serializers/#toc_ember-data-s-normalized-json-format
