### ISSUE TITLE
RESTAdapter and RESTSerializer have issue with translating name

### ISSUE THREAD

**Issue by mxrguspxrt** [emberjs/data#5316]
Hello!

Why this happens?

> WARNING: Encountered "market_data" in payload, but no model was found for model name "market-datum" (resolved model name using (unknown mixin).modelNameFromPayloadKey("market_data"))

> TypeError: Cannot read property 'id' of null
>     at -private.js:8637
>     at tryCatcher (rsvp.js:215)
>     at invokeCallback (rsvp.js:393)
>     at publish (rsvp.js:379)
>     at rsvp.js:14
>     at invoke (backburner.js:274)
>     at Queue.flush (backburner.js:153)
>     at DeferredActionQueues.flush (backburner.js:345)
>     at Backburner.end (backburner.js:455)
>     at Backburner.run (backburner.js:539)

 I was able to solve issue like this:

```
import DS from 'ember-data'

export default DS.RESTSerializer.extend({
  modelNameFromPayloadKey(key) {
    return key
  }
})

```

**Comment by kjhangiani** [comment]
This is due to singularization / pluralization by ember.  The singular of `data` is `datum`, and it's attempting to singularize it.  As far as I know, your solution looks correct.

**Comment by mxrguspxrt** [comment]
Oh, I thought "datum" is not a word, but now it makes a bit sense. Thank you for the response! :)
