### ISSUE TITLE
Crash on _debug.assertPolymorphicType

### ISSUE THREAD

**Issue by gerry3** [emberjs/data#5334]
When loading Ember Data (2.18.0) from cdnjs, calls to `store.createRecord` crash with:

`Uncaught TypeError: (0 , _debug.assertPolymorphicType) is not a function`

in `BelongsToRelationship.addInternalModel`

This is in what I think would be considered the dev / debug build: https://cdnjs.cloudflare.com/ajax/libs/ember-data.js/2.18.0/ember-data.js

I do not see the issue using the production or min builds:
https://cdnjs.cloudflare.com/ajax/libs/ember-data.js/2.18.0/ember-data.prod.js
https://cdnjs.cloudflare.com/ajax/libs/ember-data.js/2.18.0/ember-data.min.js

**Comment by mcfiredrill** [comment]
I'm having the same issue but not unable to create a small reproducible app yet.
Not seeing the issue in production/test, assuming its because its being removed from those builds:

**Comment by mcfiredrill** [comment]
I'm seeing this issue with the `ember-data-source` gem (ember-rails).

Seems that the DEBUG flag is set to false in the build for this gem.
https://github.com/emberjs/data/blob/e6cb564bdb33da4b3c15c3c668dc4b1fdafdf190/addon/-debug/index.js#L30

Its the first time I've looked at the ember data source code, but it seems like the other callsites for `assertPolymorphicType` should have a `if (DEBUG)` guard.
I tried this and it fixed the issue for me.
https://github.com/mcfiredrill/data/commit/37f0955ee33bd37b2569109d5d9d676762dec87f

Should I open a PR? 🔨

**Comment by runspired** [comment]
`assertPolymorphicType` should be stripped from prod builds, seems odd if these CDNs are getting only-partially-prod builds.

**Comment by runspired** [comment]
> Seems that the DEBUG flag is set to false in the build for this gem.

aaah. This is the sad consequence of not using ember-cli. We're ending our support for non ember-cli things with 3.0, I'm sure we'd accept a fix for the build for 2.18 but we've already removed the globals build for 3.x

**Comment by Bartheleway** [comment]
It's actually causing problem in twiddle ... Not really good when we try to setup test cases.

**Comment by runspired** [comment]
Twiddle needs to use ED as a real addon
