### ISSUE TITLE
Relationship getting sent with payload on attribute PATCH request

### ISSUE THREAD

**Issue by npendery** [emberjs/data#5335]
I am not sure if this is expected behavior, but when I update an attribute and save the model as so:
```
customer.set('complete', true)
customer.save()
```
the PATCH request payload that results is:
```
{
  "data": {
    "id":"fake-id",
    "attributes": {
        "complete":true
     },
     "relationships": {
         "office-profile": { "data": { "type": "office-profiles", "id": "fake-id"} }
      },
      "type":"customer-profiles"
   }
}
```

and this does not work with the backend I am using because customers should not be able to update their office. Curious why the relationships are sent along because JSONAPI thinks that I am trying to update the office that this customer belongs to ([spec source for updating relationships](http://jsonapi.org/format/#crud-updating-resource-relationships)), but it is not changing at all. Is there a flag I can set to make sure this doesn't happen? I did a workaround with the `serialize()` function in the customer adapter, but wouldn't think something that isn't dirty is sent through with a PATCH request.

**Comment by runspired** [comment]
Our default currently is to serialize the entire state of the record, not just the changes. As you noted, it is fairly easy (and the correct course to take) to implement a `serialize` function that works as your API expects.
