### ISSUE TITLE
Invalid JSON responses and ajaxOptions depreciation

### ISSUE THREAD

**Issue by jcheron** [emberjs/data#5338]
A Rest API does not always return a valid json response. 
if the answer is empty, jQuery displays the following error:  see #4207 

>   SyntaxError: Unexpected end of JSON input
>     at parse (<anonymous>)
>     at ajaxConvert (jquery.js:8787)
>     at done (jquery.js:9255)
>     at XMLHttpRequest.<anonymous> (jquery.js:9548)

Before [ds-improved-ajax](https://www.emberjs.com/blog/2016/06/09/ember-data-2-6-released.html#toc_code-ds-improved-ajax-code-a-href-https-github-com-emberjs-data-pull-3099-3099-a) it was possible to correct this error by modifying the dataType used by jQuery in the ajaxOptions method:

``` javascript
export default DS.RESTAdapter.extend({
  ajaxOptions: function(url, type, options) {
    var hash = this._super(url, type, options);
    // override if it's a POST request (empty response)
    if (type == 'POST') {
      hash.dataType = 'text';
    }
    return hash;
  }
}
```

What is the recommended solution for this since **ajaxOptions** is deprecated?

I did not see anything in the methods mentioned to modify the response:
- `methodForRequest `to get the HTTP verb
- `urlForRequest `to get the URL
- `headersForRequest `to get the headers
- `dataForRequest `to get the data (query params or request body)

**Comment by runspired** [comment]
We will not be moving `ds-improved-ajax` forward, and will be removing it. It's likely you should continue to use `ajaxOptions`

**Comment by runspired** [comment]
Closing this because of #5384
