### ISSUE TITLE
Adding support to options 'fields' in store.findRecord

### ISSUE THREAD

**Issue by alejandrodevs** [emberjs/data#5349]
Store#findRecord method supports 'include' in the options in order to support JSONAPI spec but 'fields' is not supported.

Something like this:
```javascript
this.store.findRecord('user', 1, {
  include: ['role'],
  fields: { roles: ['name'] }
});
```

I think 'fields' should be supported according to JSONAPI specification [http://jsonapi.org/format/#fetching-sparse-fieldsets](url)

**Comment by runspired** [comment]
@alejandrodevs any reason why this could not be achieved easily via including it on `adapterOptions` today?

**Comment by alejandrodevs** [comment]
Passing `fields` directly to `adapterOptions` does not work. In order to get this working we need to override findRecord in application adapter, like this:

```javascript
  findRecord(store, type, id, snapshot) {
    if (snapshot.adapterOptions) {
      let url = this.buildURL(type.modelName, id, snapshot, 'findRecord');
      return this.ajax(url, 'GET', { data: {
        include: get(snapshot.adapterOptions, 'include'),
        fields: get(snapshot.adapterOptions, 'fields')
      }});
    } else {
      return this._super(...arguments);
    }
  }
```

And if `fields` is part of the JSONAPI spec would be great to have the possibility to pass `fields` directly to the `findRecord` options. `include` could be passed and it's working well but 'fields' is ignored.

Am I missing something?

**Comment by runspired** [comment]
I think you should RFC adding fields, I think we'd be open to anything json-api spec related being brought in and supported. In lieu of that, what you've done above (overriding the adapter) is correct, although using `urlForFindRecord` might be the easiest way.
