### ISSUE TITLE
`store._push`  ignores meta data for single record responses

### ISSUE THREAD

**Issue by mattmarcum** [emberjs/data#5363]
The [json-api spec](http://jsonapi.org/format/#document-resource-objects) says that `meta` can be present on a resource object, so I took advantage of that to return some additional data there in my api.

It took me awhile to figure out why my `meta` hash for a single record response wasn't available anywhere.  The JSONAPISerializer hooks all showed that the `meta` key was present.  It wasn't until I stepped into the code and got into `store.push` and `store._push` that I realized this was were the `meta` hash was getting ignored.

[store._push](https://github.com/emberjs/data/blob/v3.0.0/addon/-private/system/store.js#L2330) takes one argument `jsonApiDoc` and the only member that's ever accessed off of it is `data`.  Looks like this code passes `jsonApiDoc.data` off to `store._pushInternalModel` so I don't think the fix would be trivial.

I sort of got around this by creating a ` meta` attr on my model and then moving the `meta` hash to `data.attributes.meta` during the `normalizeSingleRecord` hook in the model's serializer.

I'm guessing this is all going to be affected by the model-data [rfc](https://github.com/emberjs/rfcs/pull/293), so I guess I'm just wondering if anyone else has run into this problem and has a better fix.

**Comment by mattmarcum** [comment]
Just fyi, I tried putting `meta` as both a top-level member `{ data: {...}, meta: {...}}` and as a member of `data`: `{ data: {..., meta: {...}}`

**Comment by runspired** [comment]
We sadly don't have a good story around `meta` `links` and `errors` today at the resource, relationship or document level. This is something we will be addressing this year.

**Comment by runspired** [comment]
Closing in favor of the quest ticket for this: #2905

**Comment by runspired** [comment]
@mattmarcum I thought you'd like to know that the RFC is up :) 

https://github.com/emberjs/rfcs/pull/332
