### ISSUE TITLE
headersForRequest doesn't provide enough context

### ISSUE THREAD

**Issue by amk221** [emberjs/data#5388]
I'm trying to migrate to `ds-improved-ajax`

Currently, my adapter looks like this:

```javascript
ajax() {
   return this.get('apiService').request(...arguments);
}
```

...it just hands off all the work to the API service. Meaning that the URL, and the Headers will be handled automatically, in a consistent way. This allows me to make manual requests against the API too, without ED. I really like this approach. It also means I can use `fetch` instead, easily.

The new way is trickier...

In order for me to build the `headers` I need to know the `url` of the request and the `data`, so that I can handle ETags and Content-Type and some other things too.

But the new `headersForRequest` method does not receive enough information to let me do this.

The new style looks like this:

```javascript
headersForRequest(params) {
  // Method is called `headersForRequest`, yet it does not tell me what is being requested.
  return this.get('apiService').headersForRequest(???);
}
```

**Comment by bmac** [comment]
Thanks for the feedback @amk221. 

For now I'd recommend you stick with ajax. There is a proposal to remove the `ds-improved-ajax` flag https://github.com/emberjs/data/pull/5384 with the plan to evolve ember data in a different direction in 2018. (There will likely be an addon that supports the current `ds-improved-ajax` API to help those who have already migrated to `ds-improved-ajax`.)

**Comment by amk221** [comment]
Ok thanks

**Comment by runspired** [comment]
Closing due to #5384
