### ISSUE TITLE
One side of relationship is not updated after pushPayload

### ISSUE THREAD

**Issue by cbou** [emberjs/data#5391]
I try to remove a model from a relationship and later import the model again by using pushPayload with the relationship. I would expect the relationship to be reactivate on both side (side of the model and the inverse one).

It work great for that model (attributes and relationship) but does not work for the inverse side of the relationships.

``` javascript
this.get('store').pushPayload({
  folder: {
    id: 1,
    name: 'My folder'
  }
});

this.get('store').pushPayload({
  item: {
    id: 2,
    name: 'My item',
    parentFolder: 1
  }
});

var folder = this.get('store').peekRecord('folder', 1);
var item = this.get('store').peekRecord('item', 2);

console.log('Parent folder id: ', item.get('parentFolder.id'), 'Items length', folder.get('items.length'));
item.get('parentFolder').get('items').removeObject(item);
console.log('Parent folder id: ', item.get('parentFolder.id'), 'Items length', folder.get('items.length'));

this.get('store').pushPayload({
  item: {
    id: 2,
    name: 'My item',
    parentFolder: 1
  }
});
console.log('Parent folder id: ', item.get('parentFolder.id'), 'Items length', folder.get('items.length'));
```

I would expect to get the following output:

> Parent folder id:  1 Items length 1
> Parent folder id:  undefined Items length 0
> Parent folder id:  1 Items length 1

But I get this one:

> Parent folder id:  1 Items length 1
> Parent folder id:  undefined Items length 0
> Parent folder id:  1 Items length 0

The issue is on the last Items length which is 0 instead of 1.

https://ember-twiddle.com/d58d95d5be0cc8750282b9cc48db6489

**Comment by cbou** [comment]
[One solution](https://stackoverflow.com/questions/49470775) seems to be calling `unloadRecord`. This is a bit weird because the record actually still exists.

**Comment by runspired** [comment]
The issue here is that `removeObject` is an update to `currentState` (or `dirty|local` state) while `pushPayload` is updating `canonicalState` (or `remote|server` state).  Unless something tells us to discard the local change, it will continue to be there.
