### ISSUE TITLE
error message uses base model name if polymorphic

### ISSUE THREAD

**Issue by BryanCrotaz** [emberjs/data#5397]
> The person:pets relationship declares 'inverse: null', but it was resolved as the inverse for animal:owner.

In this case the owner hasMany was on the descendant dog model, so the error message is confusing.

// dog.js
export default Animal.extend({
  owner: belongsTo('person')
})

**Comment by runspired** [comment]
It's quite possible that animal defines owner and dog merely inherits the relationship, so there are scenarios in which baseModelName is more-correct. There's probably a happy way to achieve both, I'll need to poke around.

**Comment by BryanCrotaz** [comment]
SOmehow we need to find which class defined the relationship

**Comment by runspired** [comment]
@BryanCrotaz this may have been fixed by #5518 but I haven't checked.
