### ISSUE TITLE
Typo in the method documentation

### ISSUE THREAD

**Issue by belgoros** [emberjs/data#5417]
https://github.com/emberjs/data/blob/252ffd7606a44a5c257bfb042cd7c7f51ae192d0/addon/-private/adapters/build-url-mixin.js#L350

I think there should not be `record.save()` here as we delete a record by this method.

**Comment by sly7-7** [comment]
Maybe this is a misphrasing, but this is correct.
When you delete a record locally (by calling `deleteRecord`, you have to call record.save() to send the deletion to the server.
