### ISSUE TITLE
Fetch is failing to refresh relationships

### ISSUE THREAD

**Issue by Bartheleway** [emberjs/data#5420]
Hi everyone,

This is another issue about relationships.

My use case is pretty simple, I have two models (A and B) which are related. One has a belongsTo to the second model. Let's say A can have a relation giving B.
When I'm editing my record of type A, I can assign it a B record and then rollback A.

I read for something like 3 hours that doing a rollback of this relation is not something obvious.
Fair enough, I then decided to :
    - Reload the A record (using `reload`) => KO (I think this was working in 2.X)
    - Fetch the A record (using `queryRecord`) which should then "rollback" the change as it is not present on the server => KO

In my test, I'm coming from a non-initialized relation. Was `null`, changed to `something`, trying to revert to `null`.

Am I doing something wrong or is it a real bug ?

I'm using Ember-data v3.1.1 / Ember v3.0.0.

I did try to setup a twiddle but I didn't find a way to reproduce as I don't have a server for the data.

P.S: It would be really awesome to see this [RFC](https://github.com/emberjs/rfcs/pull/21) coming to life 👍

**Comment by runspired** [comment]
I happened to type this up as a walk through for someone else last night looking to update relationship in a rollback situation. It's not an answer, more a tutorial of the pieces in play: https://ember-twiddle.com/c65c33ce0b1810258b75b5679b75d0e4?openFiles=controllers.application.js%2C

I'm going to close this as a support request as it's not clear that you've hit any sort of bug. If you build a twiddle showing the problem I will be happy to investigate it :)

**Comment by Bartheleway** [comment]
Hi, I finally found how to create a correct twiddle ... Not really easy to understand thaught.

You will see in the twiddle that if your original record comes with an initialized relation, you can rollback it easilly. But the other way around isn't working => when it's null and you then initialize it.

Twiddle here : https://ember-twiddle.com/8e049802cbdf7e201f7f0e9931d76b67

**Comment by runspired** [comment]
@Bartheleway this is because you've given us no new information about the relationship. A slight modification to the payload makes both scenarios work the same: https://ember-twiddle.com/7005d3764c473bbab19531d2f3ea1f4c?openFiles=routes.application.js%2C
