### ISSUE TITLE
ensure that unloadAll(type) does not leave stranded internalModels in relationships

### ISSUE THREAD

**Issue by runspired** [emberjs/data#5425]
I'm not sure if this bug really exists, but I suspect it does and we should write tests to confirm.

1. unloadAll(type) clears the internalModel map for that type
2. clearing removes all internal models from the map, and calls `unloadRecord` on each model
3. unloadRecord marks relationships as dirty, but does not itself remove an item from a potentially retaining relationship.
4. (bug) This likely means that if the relationship is resurrected, a user will encounter a record not in the internal model map.

**Comment by efx** [comment]
I'm adding a test for this today; will ask in ember-data slack if I get stuck.

**Comment by runspired** [comment]
We investigated a test here #5429 and discovered that we clean up appropriately.

However, investigating #5424 it shows there is an issue with getting duplicates into relationships. Will likely repurpose our test work for fixing any issues found there but closing this.
