### ISSUE TITLE
json-api : serializeBelongsTo check for belongTo record is new not complete

### ISSUE THREAD

**Issue by olivierchatry** [emberjs/data#5430]
In my case, I'm generating an id on the client side, so the check for belongTo is new is not valid :
```js
        var belongsToIsNotNew = belongsTo && belongsTo.record && !belongsTo.record.get('isNew');
```

I think the test should just see if bleongTo have an id assigned or not.

**Comment by runspired** [comment]
@olivierchatry are you saying that you called `createRecord` but since you provided an ID you don't expect the record to be in the `isNew` state?

**Comment by olivierchatry** [comment]
No, I'm saying that the belong to relationship is set to null because
following current logic the record is 'new' and so has no id set. My record
is 'new' but have an id.

**Comment by runspired** [comment]
@olivierchatry does the record exist on the server? or are you creating it with a client-generated id?

**Comment by olivierchatry** [comment]
With a client generated id, a la firebase.

**Comment by runspired** [comment]
The answer here is you should implement your own `serializeBelongsTo` method.  In the general case, serializing an ID where the server has no knowledge of the ID or the record that it pertains to would be incorrect.

**Comment by olivierchatry** [comment]
Already done, thanks for taking time to reply.
