### ISSUE TITLE
Investigate potentially unnecessary relationship refetch

### ISSUE THREAD

**Issue by runspired** [emberjs/data#5441]
Reported by @fivetanley [here](https://github.com/emberjs/data/pull/5433#issuecomment-380877957). I will need an example "fail case" payload to produce a test and debug.

**scenario**
```js
const IdentityProvider = DS.Model.extend({
  owner: belongsTo('identity-provider-owner', {
    polymorphic: true,
    inverse: 'identityProvider'
  })
})
const Account = DS.Model.extend({
  identityProvider: belongsTo({ inverse: 'owner' })
});

const provider = store.createRecord('identity-provider', { owner: owner });

try {
  await provider.save();
} catch (e) {
  provider.unloadRecord(); // causes refetch of account.get('identityProvider'), even if the canonical state is `null`.
}
```

**Comment by HeroicEric** [comment]
I think I may be running into the same thing.

https://ember-twiddle.com/840a1b37e2409723bfb8373690f58359

**Comment by runspired** [comment]
#5525 is potentially a duplicate of this.

Primarily we need to add a failing test that captures the cases described above, in the linked ticket, and for one described offline (the same as above but no call to save the new record is made). From there we can determine the right fix.

**Comment by runspired** [comment]
closing since the related ticket was resolved that we thought was a duplicate and we don't have an example payload that was triggering the fail-scenario
