### ISSUE TITLE
Change documentation for building ember-data

### ISSUE THREAD

**Issue by izelnakri** [emberjs/data#5458]
Hi, I want to manually build ember-data into a dist folder that I can re-use outside of ember-cli. 

Current documentation on `README.md` is outdated and the npm scripts under `package.json` misses ember-cli-build.js file to build. How can we do this currently? I think we should always have this option for advanced use cases.

**Comment by runspired** [comment]
We no longer produce a stand-alone globals build, and only support ember-cli so this will likely be mostly on you to support. You will likely want to build a broccoli script that emulates the addon-build / babel / rollup stages and produces the desired module format output.

**Comment by izelnakri** [comment]
This is a ridiculous architectural decision. Excuse my directness, I will build this anyways. This is just a hint of disservice being done by `ember-cli`, I hope better decisions will be taken in future.

**Comment by runspired** [comment]
@ianstarz using ember without ember-cli is no longer supported either. It's easy to integrate ember-cli into other build flows. It's an unnecessary burden to support edge cases when using the provided tool allows you to accomplish what you need.

**Comment by runspired** [comment]
We publish ES Modules... Use them.

The `dist` artifacts for `ember-source` like ours are a pre `3.0` artifact. That they still exist is incidental, I wouldn't rely on them.

**Comment by izelnakri** [comment]
ok I think I understood the situation, thanks for the explanation. I'll try to run my own addon-build + babel/rollup stages, hopefully everything will work correctly.
