### ISSUE TITLE
Custom Query Records

### ISSUE THREAD

**Issue by dmtask** [emberjs/data#5464]
Hi there,

i actually need something like a custom query for a project. Specifically I would like to check before a `createRecord` whether it already exists in the database. In SQL this would be quite easy with `EXISTS`, but in ember there is no such thing (yet).

Is such a thing planned or will there be the possibility in the future to create completely own querys, something like `createRecordIfExists`.

**Comment by runspired** [comment]
@dmtask you can use `peekRecord`.
