### ISSUE TITLE
Invalid link for code location on api docs

### ISSUE THREAD

**Issue by bekicot** [emberjs/data#5483]
![image](https://user-images.githubusercontent.com/1826884/40885986-6473c69c-675a-11e8-9adc-7c3656908323.png)

Url: https://www.emberjs.com/api/ember-data/release/classes/DS.JSONSerializer/properties

It is only an example, The `DEFINED IN` link is invalid in all the page I encountered.

**Comment by runspired** [comment]
I think this was an issue with the yui-docs version that was used. I think @bmac was going to re-release with an older yui-docs version to resolve this.

**Comment by bmac** [comment]
There was a travis hiccup that caused the api docs not to be published with the release build. I re-triggered the failing build and the yui docs were published successfully on the second attempt.
