### ISSUE TITLE
Memory leak in _pendingPayloads

### ISSUE THREAD

**Issue by BryanCrotaz** [emberjs/data#5484]
Repeatedly save a model instance with ED 2.18 which has a `hasMany` relationship embedded. The server will return the `hasMany` as part of its json-api blob response.

This causes the payload to be added to `_pendingPayloads`. This is only flushed when the `hasMany` is read.

If the `hasMany` is never read, this will grow infinitely.

In my case this is a write-only model (diagnostics sent back every 20 seconds to the server) and never read in the webapp.

Proposal: Instead of adding to the array infinitely, when `_pendingPayloads` for a particular `{modelName,id,relationship}` tuple gets to a certain length (5?), it is merged down to a single entry.

Thoughts? @runspired

**Comment by runspired** [comment]
We’ve removed lazy relationships in the RecordData feature branch. There are varying reasons as to why to not restore them; however, the single-source-of-truth concept is likely to make a comeback at some point, so documenting this seems very good.

The right course of action for now I’m unsure. At least a warning “this seems unused” and some auto-flattening or some such. Could likely even just always flatten now tbqh, we do better in that layer than we used to with all the work to fix Meta links and polymorphism

**Comment by runspired** [comment]
@stefanpenner this issue would likely go away if this were the only source of truth; however, this is also one of the interesting foot-guns we've discovered along the way I was mentioning in our convo the other day.

**Comment by runspired** [comment]
Closing as lazy relationships were removed beginning in 3.5

**Comment by BryanCrotaz** [comment]
What’s the replacement for lazy relationships? We use them a LOT

**Comment by runspired** [comment]
@bryancrotaz we returned to non-lazy but the perf characteristics of the newer internals resulted in similar performance
