### ISSUE TITLE
DNS Resolution Error is handled as a generic error not TimeoutError

### ISSUE THREAD

**Issue by BryanCrotaz** [emberjs/data#5486]
`findRecord` always returns the same error regardless of why.

Possible reasons:
* DNS did not resolve
* Timeout
* Server 5xx error
* Server 4xx error
* Malformed response

The application may want to react to these in different ways. We should give visibility in the exception response of why the failure happened.

**Comment by BryanCrotaz** [comment]
Whoops - I was using typeof and not instanceof.

But I did find a case that's missed, when DNS fails to resolve on Chrome on Windows. PR supplied.

**Comment by runspired** [comment]
Now that we've moved to RequestManager I think we can close this
