### ISSUE TITLE
defaultValue doesn't work in latest beta

### ISSUE THREAD

**Issue by Sinled** [emberjs/data#5493]
After i've updated  ember data to `3.2.0-beta.4`, some of my tests, that were depending on `defaultValue` failed.

I have made a new repo with reproduction
[model](https://github.com/Sinled/ember-store-push-bug/blob/master/addon/models/test-model.js)
[test](https://github.com/Sinled/ember-store-push-bug/blob/master/tests/unit/serializers/test-model-test.js)
[ember-try settings](https://github.com/Sinled/ember-store-push-bug/blob/master/config/ember-try.js)

these tests work fine with ember data 3.1.1

Am i doing something wrong?

**Comment by nickschot** [comment]
I think this was fixed in #5428 which seems to not have been included in this beta :( .

**Comment by urbany** [comment]
Yeah unfortunately the latest beta is missing that, and the latest release has other bugs, so right now I'm using this in production: "ember-data": "github:emberjs/data#c438a8a5e053724eb5b5257a451259a761a06d98"

This commit has the defaultValue fix and I didn't notice any bugs. Have been running it in production for a few weeks now.

I know the devs do this on their free time and really appreciate their hard work, but it would be pretty cool if someone could release a new beta with that fix. Thanks in advance :)

**Comment by rwjblue** [comment]
I'm trying to set up the final release of 3.2 today, and am under a bit of a crunch from other obligations, but if you have the time you can cherry-pick the change and send a PR targeting the beta branch. I'll sit down with @runspired (and possibly @hjdivad) to review to make sure it is low enough risk to land into the beta branch...

**Comment by lhoBas** [comment]
@rwjblue I've gone ahead and created the [cherry-pick PR](https://github.com/emberjs/data/pull/5497). Hope this will make the cut, it's a 'make-it-or-break-it' for us with 3.2 😅

**Comment by rwjblue** [comment]
Thank you!

**Comment by BnitoBzh** [comment]
There is no 3.2.0-beta-5 version scheduled with the https://github.com/emberjs/data/pull/5497 ?
The only solution is to use ember-cli@3.2.0-beta-2 + ember-data@beta ?
