### ISSUE TITLE
Waiting for Model.hasMany('relationship').value() to not be null

### ISSUE THREAD

**Issue by cptran777** [emberjs/data#5506]
Hey Ember Data folks,

Currently on Ember 2.17 and I'm running into an issue where I've made a call using Ember Data to fetch a model with an include for relationships. For example, if I had a model `Employee` with a relationship hasMany to other employees in a property called `directReports` and using the `data` method to cache relationships
```
// In a route model() hook:
const employee = await store.findRecord('employee', id, { include: 'directReports });
```

Then when I try to access the direct reports relationship through reference

```
const directReports = employee.hasMany('directReports').value();
```

It's null, which I think is weird because the relationship should have already been included in the response for the query above. I'm suspecting because the relation models are loaded asynchronously even if they have been side loaded with an `include`. However, if I do something like create a delayed function and set it for something like 200ms later, then `employee.hasMany('directReports').value()` will return the `directReports`. However, at that point my route's model hook would have already resolved. 

Another option I tried was to use
```
employee.hasMany('directReports').load().then( ... )
```

But this seems to make an additional api call. 

My question has two parts:
1. Should the reference really need to be loading if it was already included in the api response that returned the query for the employee
2. Is there a way to wait for the reference to stop loading and get the value in some kind of promise without using `.load()` since that seems to make an additional api request?

**Comment by cptran777** [comment]
Hey @runspired , thanks for the response! I've tried both `employee.get('directReports')` or `employee.hasMany('directReports').load()` but both make an additional API call. It's not necessarily the end of the world but it's annoying that it's making this extra API request to get the direct reports when I know for a fact that the data is already available.

**Comment by runspired** [comment]
@cptran777 if the data is side-loaded the `get('directReports')` approach will not fire an extra request. Either there is a background reload occurring or you are hitting an odd timing bug that we should investigate.

- Which version of EmberData
- Can you give me a brief TL;DR of how you try to access `directReports` in relation to having found the employee record in the model hook?
- Is this relationship sync or async?
- Do both sides declare an inverse or is this an `inverse: null` relationship?
- Do you load a link with the relationship?

**Comment by cptran777** [comment]
@runspired So I may have simplified everything too much in order to create a very generalized question. It seems like side-loaded data at the first level gets included just fine, however it's when I want to access nested relationships that there is an issue. 

- Ember Data is on version 2.18.0
- Relationship is async
- Both sides have inverse

For example, if we do something like: 
```
// models/employee.js
export default DS.Model.extend({
  directReports: DS.hasMany('employee', { inverse: 'reportsTo' }),
  reportsTo: DS.belongsTo('employee', { inverse: 'directs' })
  ...
});
```

```
// routes/index.js
model() {
  const employee = await store.findRecord('employee', id, { include: 'directReports,directReports.directReports' });
  
  // This will be fine
  const reports = employee.hasMany('directReports').value();
  
  // This will return all nulls
  const reportsOfReports = reports.map(report => report.hasMany('directReports').value())
  
  // Interestingly, if we have a promise that creates some kind of delay for say 500ms
  await delay(500);
  //This now works and returns an array of array of reports of our reports
  const tryAgain = reports.map(report => report.hasMany('directReports').value())
}
```

**Comment by runspired** [comment]
Ah. The issue here is likely async await. You must use the polyfill not native and you’ll need to be on most recent versions of ember data.

**Comment by runspired** [comment]
@cptran777 native async-await uses native promises while the polyfill will use RSVP Promises, this subtle difference includes a subtle difference in timing of when work is complete.

**Comment by runspired** [comment]
@cptran777 did you ever resolve this? if not would you mind PRing a test with this setup to see if we can isolate what's wrong?

**Comment by runspired** [comment]
For anyone wishing to contribute, a good test for this will:

- setup a model with an async has-many relationship to another model that also has an async has-many relationship (one model can be used if modeled cleverly)
- fetch that record and include all related records in the api-response
- after the fetch completes, access the has-many relationship via `record.hasMany()`
- iterate the related records and access the async has-many relationship on that model via `relatedRecord.hasMany()`
- expect that all records were available via this process
