### ISSUE TITLE
Belongs to relation cleared on server response

### ISSUE THREAD

**Issue by lcoq** [emberjs/data#5510]
**Version**

2.9.0

**Setup**

```js
// app/models/comment.js
export default DS.Model.extend({
  post: DS.belongsTo('post', { inverse: null })
});
```

```js
// app/models/post.js
export default DS.Model.extend();
```

**Scenario**

```js
const comment = store.createRecord('comment');
comment.save();

// somewhere else, before the `save()` server response
comment.set('post', aPost);

// => Once the server has responded (obviously its payload has no `post`)
comment.get('post').then(function(post) {
  console.log(post); // post is `null`
});
```

**Why could it be a bug ?**

- This behavior is inconsistent as it only appears with relation (at least `belongsTo`), not with "classic" model attributes.
- This makes it hard to let a form opened while saving it

**Comment by runspired** [comment]
@lcoq your model definition is incorrect (and should be throwing an error). You have no inverse on `post` for `comment`. If you intend for there to be no inverse you should explicitly set `inverse: null`.

**Comment by lcoq** [comment]
@runspired right, sorry. I've updated the code above.
Anyway, this behavior remains unchanged with `inverse: null`..

**Comment by runspired** [comment]
This is a duplicate of the many issues open to preserve local changes to relationship during flushCanonical. We will eventually fix this issue (present since the beginning of ember-data); however, doing so is non-trivial and our last few attempts have surfaced major regressions causing the attempt to be reverted. Closing in favor of the existing tickets.

**Comment by lcoq** [comment]
@runspired could you please, for me and future readers, give the link of the main issue that keeps track of this bug ? thank you very much
