### ISSUE TITLE
[3.2.0+] Problem setting belongsto relationship (only works the 2nd time)

### ISSUE THREAD

**Issue by urbany** [emberjs/data#5511]
Hi, weird bug I found while upgrading from v3.2.0-beta.4 to v3.2.0 (also happens on v3.3.0-beta.1)

I have a model `appointment` which belongsTo a model `service`.
When I create the appointment and then set the relationship `service` it does not work, it stays null.
It only happens with the relationship to the model named `service`, the other models work correctly, I tried to create a twiddle but I couldn't  make it use latest ED, so here is a repro: https://github.com/urbany/ember-data-service-belongsto-bug

Try the buttons. The relationships to the model Service only get set when you set them twice

**Comment by urbany** [comment]
actually according to this it is not exclusive to models named service:
https://embercommunity.slack.com/archives/C045BQ4P7/p1530380754000078

**Comment by barelyknown** [comment]
We started to notice this issue 1-2 weeks ago on canary, but haven't tracked down the commit in which it was introduced.

**Comment by runspired** [comment]
@barelyknown @urbany @nickschot what version of ember is paired with ember-data here?

**Comment by nickschot** [comment]
3.2.2 in the Twiddle, 3.1.3 in my app.

**Comment by runspired** [comment]
I was able to track it down to the proxy not being refreshed on set, will fix. Thanks!

**Comment by barelyknown** [comment]
@runspired That's great. I noticed that it does not seem to be a problem on `3.3.0-canary`. Has it already been fixed there?

**Comment by runspired** [comment]
@barelyknown the bug exists on canary.

**Comment by john-griffin** [comment]
Any updates on this one? This has blocked our apps from upgrading data to 3.2 and is now blocking us from upgrading to ember 3.3 (as it also requires this fix https://github.com/emberjs/data/pull/5466 which is only available in newer ember-data). Happy to help out if you can point in the right direction.

**Comment by runspired** [comment]
Closing in favor of coalescing on #5517
