### ISSUE TITLE
Mandatory setter issue on model second load

### ISSUE THREAD

**Issue by LeviDooley** [emberjs/data#5513]
I'm getting a strange error when transitioning from one route to another which both load the same model. It seem very similar to #3077, but I'm not sure if it's the same problem, and I don't think their solution applies to my case.

By the way, this project is a few years old, I only started getting these problems after upgrading to these newer versions.

Versions: (Current)
```javascript
{
    "ember-data": "~3.2.0",
    "ember-source": "~3.2.2",
    "ember-cli": "~3.2.0"
}
```

Model:
```javascript
import Model from 'ember-data/model';
import { belongsTo, hasMany } from 'ember-data/relationships';
import attr from 'ember-data/attr';

export default Model.extend({
    name: attr('string'),
    text: attr('string'),
    version: attr('string'),
    type: attr('string'),
    desc: attr('string'),
    abbrev: attr('string'),
    parent: attr('string'),
    parentSite: belongsTo('site'),
    units: hasMany('unit'),
    points: hasMany('point')
});
```

![2018-07-03_10-57-54](https://user-images.githubusercontent.com/18010173/42231344-ebf38392-7eb0-11e8-9cee-4e7ad38a4055.png)
![chrome_2018-07-03_10-58-54](https://user-images.githubusercontent.com/18010173/42231349-ee045aee-7eb0-11e8-8770-ac1a98daf9e8.png)
![chrome_2018-07-03_10-59-54](https://user-images.githubusercontent.com/18010173/42231351-f005ccb0-7eb0-11e8-9950-c317535a9fa7.png)
![chrome_2018-07-03_11-29-07](https://user-images.githubusercontent.com/18010173/42232571-6b52b89e-7eb4-11e8-8788-6e3eb71a1de7.png)
![chrome_2018-07-03_11-01-36](https://user-images.githubusercontent.com/18010173/42231357-f4273fcc-7eb0-11e8-9f4b-8e22f539f50c.png)

```
Uncaught TypeError: Cannot convert object to primitive value
    at Object.SETTER_FUNCTION [as desc] (ember-metal.js:1604)
    at assign (<anonymous>)
    at InternalModel.setupData (-private.js:7054)
    at Class._load (-private.js:11614)
    at Class._pushInternalModel (-private.js:11977)
    at internalModelOrModels._backburner.join (-private.js:11917)
    at Backburner._run (backburner.js:815)
    at Backburner._join (backburner.js:793)
    at Backburner.join (backburner.js:568)
    at Class._push (-private.js:11901)
```

So, first of all, this is breaking because `this` (an object) is being concatenated to a string which gives the "Cannot convert object to primitive value" error.

But honestly, I can't figure out what is causing the mandatory setter function to fail at all. If `Ember.assign` is the problem, why is it only a problem when transitioning from one route to another? I'm assuming that it is because the model gets reloaded, and the error only happens on reload.

Any idea of what might be going on here? Or any ideas for a workaround?

**Comment by runspired** [comment]
@LeviDooley looking at your last screenshot you can see that the `desc` property on `internalModel.__data`  has a getter/setter installed. This means somewhere in your app code you are consuming this property directly either via an observer, a computed property, or a template instead of via the record. Could be doing something like `record._data.desc` or some such.

**Comment by LeviDooley** [comment]
Thank you. 😄 The problem was indeed that someone was accessing the `desc` property using `record._data.desc` inside of a template. I found that spot and fixed it, and it's working now.

I agree that this issue can be closed, but it would be nice if there was some deprecation warning when someone tries to access a property in that way. Especially if it creates problems down the line which are this difficult to track down.
