### ISSUE TITLE
Problem with `setId` when creating a belongsTo association

### ISSUE THREAD

**Issue by sdhull** [emberjs/data#5514]
Hello Emberistas! Thank you for your tireless work on ember-data, it's awesome.

After upgrading recently from Ember 2.17 to 3.1.3 (ED 3.1.1), we found a strange issue when creating a record.

I've kind of reproduced the issue with [this Ember Twiddle](https://canary.ember-twiddle.com/9fa7c8bc250032994b6e01c470ed30b3?openFiles=controllers.index.js%2C), you have to open console to see the errors.

The difference between that Twiddle & our code is that there is no error but if we do `order.get('items.lastObject.id')` it's `null` after (successfully) saving the `item`. Stranger yet is that `order.get('items.lastObject._internalModel.id')` it is the correct id.

But it seems like there is something going on here related to updating the id on a cached hasMany association after saving the associated record... Any guidance would be appreciated. Thanks!

**Comment by sdhull** [comment]
After further investigation, there's a decent workaround (for our codebase, this doesn't fix the twiddle) by doing the equivalent of:
```js
let item = this.order.get('items').createRecord();
```
This makes it so that `order.get('items').mapBy('id')` after saving the item actually returns the proper id for the last item in the array proxy.

Still seems like this should work.

**Comment by runspired** [comment]
What Ember version are you paired with?

**Comment by runspired** [comment]
There were two issues here, one has been fixed and one remains.

1) [FIXED] `setId` was not updating the store cache.
2) [BUG] `setId` does not push the ID to the backing `RecordData`.

**Comment by runspired** [comment]
This should be fixed in more recent versions, please open a new issue if you feel this issue still exists.
