### ISSUE TITLE
.node_modules.ember-try included in 2.18.2 release

### ISSUE THREAD

**Issue by PieterJanVdb** [emberjs/data#5519]
The .node_modules.ember-try folder is included in the 2.18.2 release: [unpkg](https://unpkg.com/ember-data@2.18.2/.node_modules.ember-try/)

This caused my build time to increase by quite a large margin. As this is the ember-data LTS, it might be worth removing this folder in eg. 2.18.3?

**Comment by bmac** [comment]
Seems reasonable. I'll cut a 2.18.3.

**Comment by bmac** [comment]
Just published 2.18.3 without a `.node_modules.ember-try` folder [unpkg](https://unpkg.com/ember-data@2.18.3/).
