### ISSUE TITLE
Optional source.pointer field for InvalidError

### ISSUE THREAD

**Issue by lougreenwood** [emberjs/data#5521]
When working with a non-JSON API compatible API (in my case, an JSON RPC API) an error may be received where there is no reference to which field caused an invalid error (even if it is technically an invalid error).

In these circumstances it should still be possible to make use of an InvalidError (different handling by ED than other error types  - model set to invalid, etc - something not obviously possible even with custom error classes) without having to fake a pointer value.

In my code, currently the only way to work around the required `pointer` field is to add some fake pointer to  an actual model field (not possible to use `null` or `'null'` empty values etc) - which means a developer must write purposefully misleading code to satisfy the (seemingly?) overly-strict requirements of `InvalidError`.

**Comment by runspired** [comment]
Errors are now handled opaquely, so this should just work. Let's revisit if removing extractErrors does not result in the errors appearing on Error.errors / is not retrievable from the cache via https://api.emberjs.com/ember-data/5.2/classes/%3CInterface%3E%20Cache/methods/getErrors?anchor=getErrors
