### ISSUE TITLE
[FEAT] empty records in the process of being requested should be in the empty state

### ISSUE THREAD

**Issue by wagenet** [emberjs/data#5522]
Record that have never been fulfilled (e.g. empty) but which transition to a loading state should also remain empty until the loading state is resolved. To accomplish this, a deprecation will need to be created for when `isEmpty` returns false but `isLoading` is true.

**Original issue that surfaced this:**

----

Commit 3b7b5e73cff46a48d513cf8a46af3ee459bba772 causes the regression.

See also #5517.

**Comment by wagenet** [comment]
@runspired ping

**Comment by runspired** [comment]
The bug that this resulted in was fixed in #5562 however, we still do not consider `isLoading` records to also be `isEmpty` when we likely should. Since that has been the case since forever, it will require a deprecation lifecycle to change. Converting this ticket to track that.

**Comment by wagenet** [comment]
@runspired thanks!

**Comment by wagenet** [comment]
@runspired I just verified that #5562 fixes the exact issue that I ran into.

**Comment by runspired** [comment]
Closing in favor of RFC (which needs to be written, but details are here): https://github.com/emberjs/rfcs/issues/359
