### ISSUE TITLE
BelongsTo not cleared on destroyRecord 3.2.0+

### ISSUE THREAD

**Issue by jlami** [emberjs/data#5523]
https://ember-twiddle.com/8699e6c887c9eb2cb4344fb1d2551dbe?openFiles=routes.application.js%2C

Might be related to #5511 

Expected behaviour is that pressing the delete button will remove the post object and clear the belongsTo. This works in 3.1.1
In 3.2.0 the post object remains in the belongsTo in state 'root.deleted.saved' while it is removed from the store (store.peekAll('post').length returns 0, written to console with second button)

I can't get beta to work in ember-twiddle, but copying the twiddle to a local project shows that beta and master both don't work.

**Comment by broerse** [comment]
Release v6.0.0 test for to [ember-pouch](https://github.com/pouchdb-community/ember-pouch) adapter fail on this bug. See: https://travis-ci.org/pouchdb-community/ember-pouch/builds/403065559 I hope it can be solved soon.

**Comment by runspired** [comment]
I have confirmed that this is the same issue as #5511 and #5517 with one slight variation in which the relationship flag state should now be `relationshipIsEmpty: true` yet it is still `false`. I will add a test for this case to ensure the flags transition properly in the PR for these issues #5533.

**Comment by broerse** [comment]
@runspired Thanks for fixing this. All test pass again :pouch: 🏆🎉🎉🎉🎉
