### ISSUE TITLE
BUG: regex hostWhitelist doesnt work since new fastboot changes

### ISSUE THREAD

**Issue by izelnakri** [emberjs/data#5527]
I had an app running on ember-data 3.1.1 with fastboot and it was working fine. 

Today I upgraded it to 3.3.0 and started to see this error in my test suite:
```
There was an error running your app in fastboot. More info about the error: 
 Error: The host header did not match a hostWhitelist entry. Host header: localhost:1234
```

This is strange because I had this in my environment.js and it was working before 3.3.0 upgrade:
```js
    fastboot: {
      hostWhitelist: [/^localhost:\d+$/]
    },
```
so I added localhost:1234 there:
```js
    fastboot: {
      hostWhitelist: ['localhost:1234', /^localhost:\d+$/]
    },
```
Then it started working again. It seems that new ember-data ignores regex hostWhitelists. I checked the changelog, there are some code additions to ember-data on fastboot environment. This could be the cause but Im not sure: 
https://github.com/emberjs/data/pull/5385/files

**Comment by runspired** [comment]
cc @tchak

**Comment by Gaurav0** [comment]
Looks to me like the error comes from here: https://github.com/ember-fastboot/fastboot/blob/1d0e4c86f4f3bdecc9acc95116c720db17c77a46/src/fastboot-request.js#L36

**Comment by runspired** [comment]
Closing as I don't believe this was related to EmberData
