### ISSUE TITLE
ember-inflector Ember.EXTEND_PROTOTYPES is deprecated

### ISSUE THREAD

**Issue by sumeetattree** [emberjs/data#5529]
`ember-inflector: ^2.0.0` is triggering the following deprecation message. The deprecation has been fixed in `ember-inflector: 3.0.0`

```js
define('ember-inflector/lib/ext/string', ['ember-inflector/lib/system/string'], function (_string) {
  'use strict';

  if (Ember.EXTEND_PROTOTYPES === true || Ember.EXTEND_PROTOTYPES.String) {
  ...
```

**Comment by runspired** [comment]
@sumeetattree got a moment to send in a PR with the bump and any necessary changes to `import` statements?

**Comment by sumeetattree** [comment]
@runspired Little busy this week. I can send it over by Monday.
