### ISSUE TITLE
[BUG] new FastBoot support code breaks ajax mocking

### ISSUE THREAD

**Issue by izelnakri** [emberjs/data#5532]
https://github.com/emberjs/data/blame/6a13afee5ff0cfdebd58ed8476a572dfe3c9055e/addon/adapters/rest.js#L1026 This method currently breaks the development flow of any library that leverages ajax mocking when fastboot is toggled. 

There aren't many libraries out there that does this, since mirage doesnt support fastboot I think my memserver library is the only library that is affected by this. I was also hacking it with my fastboot fork(via overridingSanbox with jsdom) to leverage this functionality in non-production & memserver enabled environments. Currently I have a work around, but I would like to have this functionality injected through my addon. My current workaround:

```js
// in /src/data/models/application/adapter.js

import DS from 'ember-data';
import ENV from '../../../../config/environment';

export default DS.RESTAdapter.extend({
  _ajax(options) {
    if (ENV.memserver && ENV.memserver.enabled) {
      this._ajaxRequest(options);
    } else if (this.get('fastboot.isFastBoot')) {
      this._najaxRequest(options);
    } else {
      this._ajaxRequest(options);
    }
  },
});

```

ajax/xhr mocking allows me to have a big/advanced and very fast frontend test suite, in addition I can run the server as my prototype server on browser and on the development fastboot server. I'm not happy with this change, previous fastboot injection was hacky but at least it was an initializer that I could overwrite.

I also tried this without the workaround but it didnt work, either because it was extending the class or referencing directly to the import, I dont know:

```js
        // appending this to vendor.js on memserver environments:
        window.DS = window.require('ember-data').default;
        window.DS.RESTAdapter.reopenClass({
          _ajax(options) {
            this._ajaxRequest(options);
          }
        });
```

**Comment by izelnakri** [comment]
I suggest doing a more fine-grained if check there to see if xhr object is available(I guess simple-dom disables it), if it does always make this._ajaxRequest(options).

**Comment by izelnakri** [comment]
Something like `(window.$ && window.$.ajax) ? this._ajaxRequest(options) : this._najaxRequest(options)`

**Comment by runspired** [comment]
I'm not convinced this is a bug vs mocking ajax in fastboot being a bad pattern. I'm curious what @stefanpenner / @kratiahuja / @tomdale think about this.

**Comment by xg-wang** [comment]
Instead of checking `xhr`, I think maybe providing an overriding point for fastboot environment could enable a better pattern.

If we separate this fastboot related part in [`ajaxOptions`](https://github.com/emberjs/data/pull/5385/files#diff-72c4292e6eedd1425a5c51ef498585b7R1073) into [`_najaxRequest`](https://github.com/emberjs/data/pull/5385/files#diff-72c4292e6eedd1425a5c51ef498585b7R1009), then we can just provide an override in fastboot.

For @izelnakri 's case something like

```
// in /src/data/models/application/adapter.js

import DS from 'ember-data';
import ENV from '../../../../config/environment';

export default DS.RESTAdapter.extend({
  _najaxRequest(options) {
    if (ENV.memserver && ENV.memserver.enabled) {
      this._ajaxRequest(options);
    } else {
      this._super(...arguments);
    }
  },
});
```

**Comment by izelnakri** [comment]
perf wise that if check will then only occur on fastboot, so it might be better. However when I see a method called _najaxRequest, I also expect it to just make an najaxRequest. Maybe we can add a new method.

**Comment by runspired** [comment]
Prefer to leave things as they are.
