### ISSUE TITLE
Invalid relationship inverse configuration not asserted (implicit null inverse)

### ISSUE THREAD

**Issue by runspired** [emberjs/data#5538]
The following inverse configuration should error because there is no inverse relationship definition, but does not:

```
class User extends Model {
  @attr name;
  @belongsTo('pet')
  pet;
}

class Pet extends Model {
  @attr name;
}
```

Similar issue that is equally good for new contributors https://github.com/emberjs/data/issues/5435

**Comment by runspired** [comment]
cc @pete-the-pete these might be good for you to tackle.

**Comment by pete-the-pete** [comment]
Sounds good @runspired , i'll take a look by EOW!

**Comment by pete-the-pete** [comment]
Haven't forgotten about this....@runspired the test should assert that an exception is thrown?

**Comment by runspired** [comment]
@pete-the-pete 

> the test should assert that an exception is thrown?

After discussing with @fivetanley we determined that asserting here is actually a breaking change. Instead we would like to add tests that assert that the relationship is resolved as if defined as `inverse: null` (e.g. an implicit relationship) and then deprecate this behavior. We suspect that today we do not resolve to a `null` inverse but just "happen to not error" for "mysterious reasons". If this is the case, we should make it resolve to a `null` inverse as well.

**Comment by michielboekhoff** [comment]
@runspired - hope no one minds that I insert myself into this conversation. Especially @pete-the-pete, hope you don't mind I took a look at this.

I've written a small test that asserts that the `inverseFor` is correctly returning `null` when there is no inverse configured on the model and the relationship does not specify an explicit inverse. It's something like:

```
test('No inverse configuration - should default to a null inverse', function (assert) {  
  User = DS.Model.extend();
  
  Comment = DS.Model.extend({
    user: belongsTo('user')
  });

  const env = setupStore({
    user: User,
    comment: Comment
  });

  const comment = env.store.createRecord('comment');

  assert.equal(comment.inverseFor('user'), null, 'Defaults to a null inverse');
});
```

This test passes without any changes. After inspecting the code that deals with associations, this _seems_ to make sense, though I'd like to run that past you.

**Comment by pete-the-pete** [comment]
No problem! i have been swamped with work for too long, glad you picked it
up.

**Comment by runspired** [comment]
@michielboekhoff Thanks! could you PR the test, ideally using the newer style test syntax? (Happy to pair / walk you through that, feel free to reach out on discord)
