### ISSUE TITLE
[3.2.1] Error when doing HasManyReference.reload() for a non-async relationship

### ISSUE THREAD

**Issue by YoranBrondsema** [emberjs/data#5548]
In 3.2.1, I'm seeing an error

`Error: Assertion Failed: You looked up the 'comments' relationship on a 'post' with id 1 but some of the associated records were not loaded. Either make sure they are all loaded together with the parent record, or specify that the relationship is async (`DS.hasMany({ async: true })`)`

I wasn't seeing this in 3.1. I here have a [twiddle failing in 3.2.1](https://ember-twiddle.com/7661280bc7ca1713e17801f0ac9a8975?openFiles=routes.application.js%2C) and the same code [working in 3.1.1](https://ember-twiddle.com/379973ac804a73a27a988249266ec389?openFiles=routes.application.js%2C). It looks like it's caused by the changes in [this commit](https://github.com/emberjs/data/commit/d725553f4f70d00b8bb96ca3112811664b338709#diff-96eb5e2389293df72cc41de71500176f).

All the relationships in my app are async and I use the `value()`/`load()`/`reload()` functions in the `ds-references` API to manually load data when necessary.

**Comment by urbany** [comment]
HI @YoranBrondsema I'm not sure if this is a bug. @runspired is better suited to answer this but here are my thoughts:

Your model is saying `post.comments` is sync. When you retrieve the post it says it has a comment with the id 1, but that comment is not in Ember-Data yet, but if it is sync it has to be there when you reference it. Some possible solutions to apply to your code:
1. it should either be async
2. you should have the comments already in ED or get them at the same time you get the post.
3. your posts API should not give you the IDs of the comments relationship, send only the link. You can do something like this in your serializer `delete data.relationships.comment.data`.

**Comment by YoranBrondsema** [comment]
Hi @urbany, thanks for your reply. Assuming that what you say is correct and that this is intended behavior and not a bug, here are some arguments to support my case of maintaining the behavior of 3.1 and earlier versions.

## Supported by the JSON API
The JSON API specification allows relationship IDs to coexist with links (see http://jsonapi.org/format/#document-resource-object-linkage). Therefore, the JSON that I provide in the twiddles is valid according to the JSON API spec. Now is the question how the two possible values of `async` interpret the JSON.

## `async` is very ill-defined
I was trying to find documentation for the semantics of the `async` option and I couldn't find any. I looked at the [official guide on relationships](https://guides.emberjs.com/release/models/relationships/), the API documentation for [DS.Model.belongsTo](https://www.emberjs.com/api/ember-data/3.3/classes/DS.Model/methods/belongsTo?anchor=belongsTo) and [DS.Model.hasMany](https://www.emberjs.com/api/ember-data/3.3/classes/DS.Model/methods/hasMany?anchor=hasMany) but neither of these resources explains what `async` actually does. It seems that there's a global "understanding" in the Ember.js community of what it roughly means (maybe it was documented somewhere in an earlier version?) but I still think that its semantics need to be specified at least somewhere in the documentation. There's even an [addon](https://github.com/embermap/ember-data-storefront) that based itself on the behavior of `async: false`! I'm not pointing any fingers as I'm equally responsible as anyone else in the community for this documentation not being available. But I think that this should be addressed.

## Blog post for `ds-references` seems to support my use case
The [blog post](https://www.emberjs.com/blog/2016/05/03/ember-data-2-5-released.html) that introduced the `ds-references` API seems to support my use case. In the example snippet of code, they do:

```javascript
var commentIds = post.hasMany('comments').ids();

post.hasMany('comments').load();
```

According to the new behavior, the last line will always throw an error if `commentIds` is not empty and the `comments` relationships is not async.

## It is actually a very useful pattern
I found that having the IDs of relationships available without having to explicitly load the entire associated models is a very useful pattern that prevents _many unnecessary requests_, therefore resulting in a faster application and a better user experience.

Imagine you want to check whether the current user is the author of a post. Using the `ds-references` API, we can do

```javascript
currentUserIsAuthor: computed(
  function() {
    return this.get('session.currentUser.id') === this.get('post').belongsTo('author').id();
  }
)
```

To compute this, I just need the ID of the author relationship. I don't need the entire model. However, with the "new" semantics of `async`, I would have to load the entire `author` relationship just to compute this property. Things get worse in the case of hasMany associations, as entire arrays of records will have to be loaded from the backend just to make a comparison based on their IDs.

# Conclusion
Of course, all the above arguments should only be considered if what I raised as a bug is really intended behavior from 3.2 and onward. I'm curious to hear @runspired's opinion on this. If it is indeed a bug (which I hope), then I'll gladly offer my help to get it fixed.

**Comment by YoranBrondsema** [comment]
Hi @urbany, thanks for your reply. Assuming that what you say is correct and that this is intended behavior and not a bug, here are some arguments to support my case of maintaining the behavior of 3.1 and earlier versions.

## Supported by the JSON API
The JSON API specification allows relationship IDs to coexist with links (see http://jsonapi.org/format/#document-resource-object-linkage). Therefore, the JSON that I provide in the twiddles is valid according to the JSON API spec. Now is the question how the two possible values of `async` interpret the JSON.

## `async` is very ill-defined
I was trying to find documentation for the semantics of the `async` option and I couldn't find any. I looked at the [official guide on relationships](https://guides.emberjs.com/release/models/relationships/), the API documentation for [DS.Model.belongsTo](https://www.emberjs.com/api/ember-data/3.3/classes/DS.Model/methods/belongsTo?anchor=belongsTo) and [DS.Model.hasMany](https://www.emberjs.com/api/ember-data/3.3/classes/DS.Model/methods/hasMany?anchor=hasMany) but neither of these resources explains what `async` actually does. It seems that there's a global "understanding" in the Ember.js community of what it roughly means (maybe it was documented somewhere in an earlier version?) but I still think that its semantics need to be specified at least somewhere in the documentation. There's even an [addon](https://github.com/embermap/ember-data-storefront) that based itself on the behavior of `async: false`! I'm not pointing any fingers as I'm equally responsible as anyone else in the community for this documentation not being available. But I think that this should be addressed.

## Blog post for `ds-references` seems to support my use case
The [blog post](https://www.emberjs.com/blog/2016/05/03/ember-data-2-5-released.html) that introduced the `ds-references` API seems to support my use case. In the example snippet of code, they do:

```javascript
var commentIds = post.hasMany('comments').ids();

post.hasMany('comments').load();
```

According to the new behavior, the last line will always throw an error if `commentIds` is not empty and the `comments` relationships is not async.

## It is actually a very useful pattern
I found that having the IDs of relationships available without having to explicitly load the entire associated models is a very useful pattern that prevents _many unnecessary requests_, therefore resulting in a faster application and a better user experience.

Imagine you want to check whether the current user is the author of a post. Using the `ds-references` API, we can do

```javascript
currentUserIsAuthor: computed(
  function() {
    return this.get('session.currentUser.id') === this.get('post').belongsTo('author').id();
  }
)
```

To compute this, I just need the ID of the author relationship. I don't need the entire model. However, with the "new" semantics of `async`, I would have to load the entire `author` relationship just to compute this property. Things get worse in the case of hasMany associations, as entire arrays of records will have to be loaded from the backend just to make a comparison based on their IDs.

# Conclusion
Of course, all the above arguments should only be considered if what I raised as a bug is really intended behavior from 3.2 and onward. I'm curious to hear @runspired's opinion on this. If it is indeed a bug (which I hope), then I'll gladly offer my help to get it fixed.

**Comment by kobsy** [comment]
Running into a similar issue on a project I'm working on. Tracing the breaking Ember Twiddle above, it looks like `post.hasMany('comments').reload()` is indeed fetching the data from Pretender correctly. The hang up seems to me to be [this line](https://github.com/emberjs/data/blob/d725553f4f70d00b8bb96ca3112811664b338709/addon/-legacy-private/system/relationships/state/has-many.js#L47), where -- based on the method and variable names alone -- it seems like `!i.isEmpty()` should actually be `i.isEmpty()`. I wonder if this is an error that crept in from [the equivalent computed property in the RecordData version](https://github.com/emberjs/data/blob/d725553f4f70d00b8bb96ca3112811664b338709/addon/-record-data-private/system/relationships/state/has-many.js#L251)?

Though I admit I'm pretty green when it comes to ED internals, so I may be way off. 😅

**Comment by runspired** [comment]
@kobsy @YoranBrondsema not an error. If you want to use the store-front pattern of treating async relationships as sync ones and manually triggering a fetch, you need to use `reload()`. This has been true for various reasons in the past, but it is consistently true now.

Past usage of `load()` in this area was not a guaranteed behavior. While we'd left it a warning instead of an assertion, depending on whether you used links and whether you properly use the `data` member to communicate emptiness would result in load sometimes loading, sometimes loading unnecessarily, and sometimes not loading at all.

cc @samselikoff @ryanto for ensuring anywhere this is documented that use of `ref.reload()` and not `ref.load()` is clear.

**Comment by runspired** [comment]
@YoranBrondsema 

> async is very ill-defined

- `async: true` is the default and is (strictly speaking) more in-line with `json-api`'s semantics; however, most folks do not like dealing with the proxy that becomes necessary for async relationships, nor do they like the `autofetch` behavior that accessing an `async` relationship brings currently. For this reason they reach for the pattern you have used and which storefront suggests.

- `async: false` is actually the poorly defined variant, mostly because unlike `async: true` it comes with expectations that go beyond the semantics of `json-api`. Specifically, the following things are expected of synchronous relationships:

  - the related resource data is loaded prior to or along-side the primary resource
  - `links` are for reloads only
  - `undefined` or missing data members indicate `empty` relationships (e.g. the same as `data: []` for has-many or `data: null` for belongs-to)

**Comment by samselikoff** [comment]
Thanks for the ping @runspired. Storefront uses `ref.reload()` when fetching a relationship, which has worked well for us so far. (We never were able to rely on `ref.load()` as its behavior seemed too unpredictable. Additionally, we were already managing our own cache, so we knew when we needed fresh data and could just `.reload()` the relationship.)

In the past, to avoid the assertion mentioned in the OP, we did what @urbany mentioned in his comment and removed the data linkage IDs from the payload, if the corresponding resources were not present in the current compound document. After chatting with dgeb, it seemed this best fit the semantics of JSONAPI: data linkage is intended to be used to cross-reference resources within a single compound document. To fetch related resources later, then, we would rely on `links` or queries like `GET /posts?filter[author_id]=1`.

As far as your last comment @runspired, I might need a little clarification... to this day we have used `async: false` relationships and have actually been working on the opposite assumptions of the 3 bullet point expectations that you list. (To wit, we lazily load sync relationships all the time.) Are these behaviors that are changing?

**Comment by samselikoff** [comment]
Roger that – thanks!

**Comment by YoranBrondsema** [comment]
@runspired Thanks for your reply and detailed explanation. One more question though.

> @kobsy @YoranBrondsema not an error. If you want to use the store-front pattern of treating async relationships as sync ones and manually triggering a fetch, you need to use reload(). This has been true for various reasons in the past, but it is consistently true now.

The [non-working Twiddle I linked to](https://ember-twiddle.com/7661280bc7ca1713e17801f0ac9a8975?openFiles=routes.application.js%2C) uses `reload()` on the `post.hasMany('comments')`, yet that throws an error. So am I correct in assuming that starting from 3.2, the IDs of associated records should never appear in the payload, unless they are sideloaded?

**Comment by runspired** [comment]
@YoranBrondsema no, you should be able to include links and data members. What you spotted in the above twiddle is a bug, thanks for bringing that up :) There should be no reason to intentionally strip `data` members from async or sync relationships to "make ember-data work".

**Comment by YoranBrondsema** [comment]
OK! Somehow glad to hear that it's a bug haha :-). I should have been clearer in my initial post that the bug was occurring with `reload()`. I guess the issue can be reopened then?
