### ISSUE TITLE
Object.assign is not supported in IE11

### ISSUE THREAD

**Issue by hmajoros** [emberjs/data#5550]
Exact Line of Code: https://github.com/emberjs/data/blob/d41601529a09636e636524a6d80b4d877952c344/addon/-record-data-private/system/model/internal-model.js#L288

This problem typically can be solved by using the Ember built in polyfill for Object.assign: Ember.assign:
```
import { assign } from '@ember/polyfills';
...

assign(createOptions, additionalCreateOptions);

```

Reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

**Comment by rwjblue** [comment]
IMHO, we should fix this via babel.

Specifically:

* Add `babel-plugin-transform-object-assign`
* Add something like [this](https://github.com/emberjs/ember.js/blob/master/broccoli/transforms/inject-babel-helpers.js) to ensure that `Ember.assign` is used as the provided helper.

**Comment by rwjblue** [comment]
Looks like this was fixed in https://github.com/emberjs/data/pull/5549
