### ISSUE TITLE
Assertion Failed: expected container not to be destroyed

### ISSUE THREAD

**Issue by herzzanu** [emberjs/data#5570]
After upgrading to 3.3 from 3.2 I get the following error in most of the tests

![image](https://user-images.githubusercontent.com/2959519/44233792-20658500-a1a5-11e8-8989-18ec96bee3e1.png)

Probably related to #5465

**Comment by runspired** [comment]
@herzzanu by `3.3` from `3.2` I assume you mean `ember-source` (aka `ember.js`). What version of `ember-data` are you paired with? (`3.3` and `3.2` for ember-data are identical).

**Comment by runspired** [comment]
Closing in favor of #5578. While ultimately this is an issue with `ember.js` upstream, the commit we can backport would make this less painful and we should backport it.

**Comment by herzzanu** [comment]
@runspired `ember-data` is `3.2` as well, understanding it's the same as `3.3`
