### ISSUE TITLE
OrderedSet Constructor Invoked Without 'new'

### ISSUE THREAD

**Issue by chadhietala** [emberjs/data#5573]
Ember has moved its implementation of `OrderedSet` to an ES6 class as of 3.2.0. If you are not transpiling ES6 class you will receive an error like below.

```
Class constructor OrderedSet cannot be invoked without 'new'
```

I believe this was fixed on master with https://github.com/emberjs/data/pull/5557 but likely needs to be back ported.

**Comment by runspired** [comment]
Closing in favor of #5576 which has details of where we will backport this (didn't realize @chadhietala had done me the favor of opening this :D )
