### ISSUE TITLE
Backport #5467 (work during destroy) to 3.1/2.18

### ISSUE THREAD

**Issue by runspired** [emberjs/data#5578]
The fix in #5467 helps to prevent issues with `ember.js` version `3.3`, it is likely we should backport it at least that far.

**Comment by jherdman** [comment]
I'm going to take this on.

**Comment by runspired** [comment]
Turns out this was backported to 3.2/3.3 already. We should backport to 3.1/2.18 to catch more folks that haven't upgraded and are still re-reporting the issue.
