### ISSUE TITLE
[CANARY RecordData] orphan cleanup should not be required on custom implementations

### ISSUE THREAD

**Issue by runspired** [emberjs/data#5581]
During unloadRecord orphan cleanup (private API) expected to be present on all RecordData implementations

**Comment by hjdivad** [comment]
@runspired does this still need team discussion?  we have a path forward for this no?

**Comment by runspired** [comment]
@hjdivad path forward but I think we should discuss the idea of moving the orphan cleanup code into somewhere other than `modelData` in the future.

**Comment by runspired** [comment]
The fix for this has landed
