### ISSUE TITLE
Loaded resource linkage could be used to reduce number of requests

### ISSUE THREAD

**Issue by makepanic** [emberjs/data#5588]
Hi,
I think https://github.com/emberjs/data/pull/5410 changed the behavior of data for resources which use resource linkage without providing included resources.

Before that, data would look at the resource linkage and not load already loaded resources.
After the fix, this was changed so a belongsTo/hasMany relationship will always load the relationship link.

This behavior could possibly be changed to optimize relationship resource loading. 

For a belongsTo relationship it could peek into the local store and then [findBelongsTo](https://github.com/emberjs/data/blob/master/addon/-legacy-private/system/relationships/state/belongs-to.js#L217) if nothing was found.
For a hasMany relationship, where resource linkage is provided, it could try to see if any local records exists and only load the missing (or [findHasMany](https://github.com/emberjs/data/blob/master/addon/-legacy-private/system/relationships/state/has-many.js#L333) if none are already loaded).

In general, it's possible that [resource linkage is used outside compound documents](https://discuss.jsonapi.org/t/clarification-non-compound-documents-and-resource-linkages/1309). Sadly this isn't really clear from the jsonapi spec.

Example for a belongsTo resource:

* if people id=12 is already in the data store, the following wouldn't fetch the relationship link if accessed

```
{
  "links": {
    "self": "/articles/1/relationships/author",
    "related": "/articles/1/author"
  },
  "data": {
    "type": "people",
    "id": "12"
  }
}
```

Is this something that could be added by data? We're seeing a large amount of additional requests when using 3.2+

**Comment by runspired** [comment]
@makepanic it is likely that you have misdiagnosed why you are seeing a large amount of additional requests when using 3.2+. #5410 was also included in 3.1, and several other issues have led to 3.2 and 3.3 firing requests unintentionally. Most of these issues have been resolved in `3.4 beta`.

In general, ember-data does exactly as you describe your ideal scenario to be: if we have complete knowledge locally, we don't hit network, but if we don't have complete knowledge and we do have a link, then we will use the link.

**Comment by makepanic** [comment]
Thanks, I've checked 3.4 and can confirm that it works as expected for belongs-to relationships.

I think has-many can be optimized though.

As an example a relationship with resource linkage will always follow the relationship link even if only one of the records isn't in store yet.

One could maybe load the missing records instead of loading all again.

When reaching [`getData`](https://github.com/emberjs/data/blob/master/addon/-legacy-private/system/relationships/state/has-many.js#L347) with following state, it'll always call [`this._fetchLink`](https://github.com/emberjs/data/blob/master/addon/-legacy-private/system/relationships/state/has-many.js#L333)

![20180828-080828](https://user-images.githubusercontent.com/1205444/44705226-4e4ca280-aa9e-11e8-8dac-bc96109933ce.png)

I guess this could also be premature optimization, so I'm also ok with closing this issue

**Comment by runspired** [comment]
@makepanic got time to write an RFC that would allow you to make that determination?

https://github.com/emberjs/rfcs/issues/356
