### ISSUE TITLE
The use of transforms in the README

### ISSUE THREAD

**Issue by kennethlarsen** [emberjs/data#5591]
In the README (https://github.com/emberjs/data#defining-your-models) it shows the model definition using transforms but without mentioning this fact. I think this should be changed so the model definition doesn't use transforms since this tends to confuse a lot of new developers. (Many seems to think that transforms are types).

Also, we probably should consider not having a Using Ember Data (https://github.com/emberjs/data#using-ember-data) section in the README but link to the guides on emberjs.com instead to avoid maintaining two docs.

Let me know what you think.

**Comment by runspired** [comment]
@kennethlarsen I agree with both of these things. It would also be a nice first step towards deprecating all mention of transforms in the suggested usage practice at all. Some prior discussion of this in in a closed RFC, I would read these two comments of mine there:

- https://github.com/emberjs/rfcs/pull/343#issuecomment-400376395
- https://github.com/emberjs/rfcs/pull/343#issuecomment-400864166

**Comment by kennethlarsen** [comment]
Looks like this has been fixed ✨

**Comment by runspired** [comment]
@kennethlarsen yep! did an overhaul of our main docs :)
