### ISSUE TITLE
Timeouts thrown as AdapterError instead of TimeoutError

### ISSUE THREAD

**Issue by nulle** [emberjs/data#5603]
I'm noticing that Ember Data timeouts (in my case: from `findAll`) are thrown as generic `AdapterError`, not `TimeoutError`. 

Reproducing twiddle here: https://ember-twiddle.com/4e7f769a8789ae1e6dfab36f2a738f2e?openFiles=controllers.application.js%2C

So I went deeper and it seems `ajaxResponseData` ([link](https://github.com/emberjs/data/blob/v3.3.1/addon/adapters/rest.js#L1256))  is trying to read `textStatus` property from jqXHR, however the correct jqXHR property is `statusText` (as visible from [jQuery.ajax](http://api.jquery.com/jquery.ajax/)). Now I am not sure if `textStatus` is injected on jqXHR somewhere else, but in this particular case the error thrown is not correct.

**Comment by runspired** [comment]
related: #5486

**Comment by runspired** [comment]
@nulle thanks for the detailed report and easy solution!
