### ISSUE TITLE
Backport Ember.copy removal to 2.18 -> 3.3

### ISSUE THREAD

**Issue by runspired** [emberjs/data#5606]
#5436 removed our usage of `Ember.copy`. While this was done prior to the RFC for deprecating `Ember.copy`, the RFC has unfortunately still hindered our ability to keep older release branches passing (as they test against release/beta/canary versions of Ember).

**Comment by dcyriller** [comment]
@runspired https://github.com/emberjs/data/pull/5630 ports the commit to `release-3-1`branch

**Comment by dcyriller** [comment]
Do you need backport on some other release branch @runspired?

**Comment by runspired** [comment]
@dcyriller I believe that's the last branch that needed it
