### ISSUE TITLE
Better strategy for prior-release tests on Travis CI

### ISSUE THREAD

**Issue by runspired** [emberjs/data#5607]
Ember Data often backports bugfixes to older versions; however, our test suite tests those versions against the latest versions of Ember (latest release, beta, canary) as well as against the latest versions of our "`External Partners`".

We should configure travis to ignore these jobs (or move them to allowed failures) for named release branches, as it has usually been impossible to keep them green: whether because of implementation changes, breaking changes in those libraries, or new deprecations added to them.

As part of this, we should also adopt a policy of adding the Ember version matching the Ember Data release version to the must-pass scenarios for the release branch.

**Comment by runspired** [comment]
cc @backspace if you have some time and <3 to give

**Comment by backspace** [comment]
Would checking whether the branch being merged into is `master` vs something else be enough for this, do you think?

As an aside, a daily cron now tests `travis-web` against Ember beta and Ember Data beta, [here](https://travis-ci.org/travis-ci/travis-web/builds/422168826)’s an example. I’ll be refining it some time next month.

**Comment by runspired** [comment]
Discussed with @rwjblue and @hjdivad in today's meeting and we came to the following consensus:

- ember-data releases should have their travis configs set to test against the ember version they are released with
- ember-data releases should not test prior ember releases
- ember-data releases should not test against "channels" (release/beta/canary)
- ember-data releases should not test against external-partners
- ember-data should be configured such that we do not fail tests when deprecations are present in release branches
- ember-data should not fail tests for linted style errors in release (because code style drifts)

To accomplish this, we intend to

- move channel tests into their own build stage
- ensure that the version of `ember-source` in `devDependencies` is the same minor version (using `~`) but allow patches. This will ensure that the default test run is testing the version we release with.
- add conditions for the channel and external partner stages to only build when NOT the branch is not `release` or `release-` 
- configure such that we do not fail tests when deprecations are present in release branches
- run the lint job conditional to the same
- backport this travis config to `2.18`, `3.1` and `3.4`. Note that `3.1` here is not considered LTS, but due to instability we are temporarily adding it as a backport target for specifically requested bugfixes. `3.4` will become LTS.

An additional thing we discussed is the danger that arises from `Ember` backporting changes to older versions, which could retroactively cause prior ember-data releases to become bad. While `Ember` has opened such PRs (https://github.com/emberjs/ember.js/pull/16770) they are apparently for testing purposes only, and will not be released except as an opt-in addon.  This is important because otherwise `ember-data` is fighting a shifting target for stability.

**Comment by runspired** [comment]
#5614 for `2.18` is being a bit stubborn :( hopefully we will have it worked out shortly.

**Comment by runspired** [comment]
We have cleaned up all the prior release branches we care about. :)
