### ISSUE TITLE
`extractPolymorphicRelationship` method is not called when extracting a polymorphic hasMany relationship

### ISSUE THREAD

**Issue by ehaberev** [emberjs/data#5623]
Why `polymorphic` option [is checking only for belongsTo relationships](https://github.com/emberjs/data/blob/v3.3.1/addon/serializers/json.js#L664) when extracting relationships in DS.JSONSerializer (and in DS.RESTSeriazlizer correspondingly)?

I need set proper value for `type` property in relationship hashes for plymorphic hasMany embedded records (in my case I have `@odata.type` property in hash and I need to convert it to `type` property with appropriate value), otherwise error will be thrown in [`_normalizeEmbeddedRelationship` method of DS.EmbeddedRecordsMixin](https://github.com/emberjs/data/blob/v3.3.1/addon/serializers/embedded-records-mixin.js#L609) when extracting these relationship hashes.

My serializers are inherited from DS.RESTSerializer, but I can't use neither `keyForPolymorphicType` hook nor `extractPolymorphicRelationship` method to specify a custom type key for polymorphic hasMany relationship, because it is called only for belongsTo polymorphic records.

So is there a right way to do this? Or what is a right way to customize extracting polymorphic hasMany relationships (some analogue of `extractPolymorphicRelationship` method)?

It seems there is no documentation for this case.

**Comment by runspired** [comment]
Seems like an oversight, feel free to PR a fix.

**Comment by Parrryy** [comment]
I wouldn't mind picking this up for Hacktoberfest. I'm assuming it's a case of adding the `extractPolymorphicRelationship` with check to `hasMany` for each data item?

**Comment by runspired** [comment]
@Parrryy thanks! and yes:

https://github.com/emberjs/data/blob/v3.3.1/addon/serializers/json.js#L678 here we would make the same conditional branch as the belongs-to based on whether we are polymorphic. I would recommend caching the check for whether we are polymorphic somewhere outside of the loop.
