### ISSUE TITLE
Best way to test release, beta, and canary versions of data?

### ISSUE THREAD

**Issue by ryanto** [emberjs/data#5628]
I'm working on an addon that tests itself against different versions of data. I'm wondering if there's a way to setup ember try to test against release, beta, and canary versions of Ember Data?

This is what I've come up with so far, but I'm not sure if it's the right way to do this...

```js
// conig/ember-try.js

urls = await Promise.all([
  getChannelURL('release'),
  getChannelURL('beta'),
  getChannelURL('canary'),
]);

// ...

{
  name: 'ember-release',
  npm: {
    devDependencies: {
      'ember-source': urls[0],
      'ember-data': 'emberjs/data#release'
    }
  }
},
{
  name: 'ember-beta',
  npm: {
    devDependencies: {
      'ember-source': urls[1],
      'ember-data': 'beta'
    }
  }
},
{
  name: 'ember-canary',
  npm: {
    devDependencies: {
      'ember-source': urls[2],
      'ember-data': 'emberjs/data'
    }
  }
}
```

**Comment by runspired** [comment]
We have all three channels available as github branches:

Beta: `emberjs/data#beta`
Master: `emberjs/data#master`
Release: `emberjs/data#release`

That said, we are considering removing `beta` from our process and moving to a setup where `beta` releases are always cut from `master`. Until such time the above will work well.

**Comment by ryanto** [comment]
Thanks, I'll start referencing the GH branches!
