### ISSUE TITLE
Pushing records into the store right after unloading them causes them to get stuck in isDestroying=true

### ISSUE THREAD

**Issue by bendemboski** [emberjs/data#5638]
Ember Data: 3.4.1

[this](https://github.com/bendemboski/ember-data-unload-push) repo has tests demonstrating the issue. Here is the failing test:

```javascript
  test('pushing right after unloading gets models stick with isDestroying=true', async function(assert) {
    // put some data into the store
    let store = this.owner.lookup('service:store');
    store.pushPayload({
      data: [{
        id: 1,
        type: 'thing',
        attributes: {},
        relationships: {}
      }, {
        id: 2,
        type: 'thing',
        attributes: {},
        relationships: {}
      }]
    });
    // sanity check
    assert.deepEqual(store.peekAll('thing').mapBy('isDestroying'), [ false, false ]);

    // unload and re-push
    store.peekAll('thing').invoke('unloadRecord');
    store.pushPayload({
      data: [{
        id: 1,
        type: 'thing',
        attributes: {},
        relationships: {}
      }, {
        id: 2,
        type: 'thing',
        attributes: {},
        relationships: {}
      }]
    });

    // wait 100ms to be sure
    later(() => assert.deepEqual(store.peekAll('thing').mapBy('isDestroying'), [ false, false ]), 100);
    await settled();
  });
```

a workaround is to call `peekAll()` in between unloading the records and re-pushing the data, maybe because it forces a sync of the live record array?

This test may be a bit silly, but my use case is a web socket that pushes an updated list of models to the client when a change happens. The client then unloads all existing models and pushes the new data into the store, after which any models that were unloaded and re-pushed have `isDestroying=true`.

**Comment by runspired** [comment]
I dug into this (because we actually have a test to ensure that this does not happen). In normal usage, the issue you have observed will not manifest. It seems likely that you are either using an observer or manually accessing (and thus recalculating) a computed in between the call to `unloadRecord` and the call to `push`, or (more likely) that you are retaining a cached version of the previous contents of `peekAll` somewhere. `unloadRecord` will *always* fully destroy the `record` instance and if new data is received and either the `internalModel` is reused or a new one created you will get a new `record` instance.

**Comment by brandontksmith** [comment]
@runspired I am experiencing this same issue I believe. We load data specific to a user's organization, but admins have access to all. If an admin logs out of an organization we unload all the data. Upon re-entering the organization, the unloaded data does not load properly going further and the relationships are mismatched. I used Ember Inspector and see the data loaded, but it is showing null for the contents on the relationships.

**Comment by bendemboski** [comment]
Sorry, just getting back to this -- @runspired I'm confused by your response. The [unit test](https://github.com/bendemboski/ember-data-unload-push/blob/master/tests/unit/models/thing-test.js) reproducing the issue doesn't have any observers, and doesn't hold onto to any of the peeked content...

**Comment by runspired** [comment]
@bendemboski I'd have to revisit but I believe the unit test passes :P

**Comment by bendemboski** [comment]
It's still [failing](https://travis-ci.org/bendemboski/ember-data-unload-push/builds/467219513) on Ember Data 3.6

**Comment by bendemboski** [comment]
@runspired could we re-open this? It's still failing. Not urgent since I have workarounds for where it crops up, but I'm worried that if it stays closed it will just get lost, and it is an easily reproduce-able issue on the latest Ember.

**Comment by brandontksmith** [comment]
This issue is not resolved.
