### ISSUE TITLE
Array as dirty attribute

### ISSUE THREAD

**Issue by veelenga** [emberjs/data#5648]
I have the following example:

```js
export default Model.extend({
  earnings: attr(); // array of numbers
});

model.get('earnings') // => []
model.set('earnings', [])
model.get('hasDirtyAttributes') // => true
model.changedAttributes() // => { earnings: [[], []]}
```

This happens because Ember Data [uses `===` to compare updated attributes](https://github.com/emberjs/data/blob/v2.17.0/addon/-private/system/model/internal-model.js#L679-L681). Is there a good way to avoid such a behaviour and let `hasDirtyAttributes` to return false in this case?

**Comment by runspired** [comment]
@veelenga there is not currently. See #5026 or #1540 for more context on previous discussions. With the landing of #5616, you will soon be able to provide your own `RecordData` implementation that diffs in a way that works best for you.
