### ISSUE TITLE
[TEST] spec-tests for RecordData RFC

### ISSUE THREAD

**Issue by runspired** [emberjs/data#5653]
The `RecordData` implementation relied on passing existing tests; however, there are no "spec tests" for the feature itself. This has led to unfortunate discoveries in real-world implementations. For instance, `_bfs` being an incorrectly required property of `RecordData`.

We should write tests that ensure that basic implementations can/do work as expected when conforming to spec.

**Comment by Gaurav0** [comment]
Can you scope this out? The default implementation seems to have public methods that are not in the spec. Please specify what is required and what isn't.

**Comment by runspired** [comment]
we have enough test coverage here at this point to satisfy the base, though more are always appreciated
