### ISSUE TITLE
docs should not reference rails backend (or any backend)

### ISSUE THREAD

**Issue by ctcpip** [emberjs/data#5672]
The docs for `store` methods references Rails backend, with example, in a couple places.  We should remove references to specific backend implementations.

`addon/-private/system/store.js`

> The call to the server, using a Rails backend, will look something like this:

and 

> The call made to the server, using a Rails backend, will look something like this:

**Comment by runspired** [comment]
@ctcpip want to send in a quick PR?

**Comment by ctcpip** [comment]
will do
