### ISSUE TITLE
Single findRecord(category) instead of many findRecord(subcategory)?

### ISSUE THREAD

**Issue by stephanebruckert** [emberjs/data#5674]
This problem has probably been discussed before, but I can't find the wording to find it again.

First I am loading all my `categories` with `findAll`. In return I get categories and their relationship IDs: `subcategories`. For performance reason, I don't want to `include` subcategories when initially finding all my categories.

Then if I click on a category, it does NOT use `findRecord(category)` (even though in my code) but it does `findRecord(subcategory)` for EACH of the subcategories. The reason for this I suppose is because ember-data already has subcategories IDs.

Do you confirm that the current expected behaviour for ember-data is to do 100 queries if my category has 100 subcategories? Is there any way to avoid this?

This is causing severe performance issues in some cases. Thanks for your help.

**Comment by sly7-7** [comment]
I'm not sure, but perhaps when https://github.com/emberjs/data/pull/5671 will be merged, this 'issue' will be resolved.

**Comment by runspired** [comment]
The short answer is that we will trigger a request for each individual resource you ask for that isn't loaded. However, there are many ways including `coalesceFindRequests` implementing `findMany` and the use of `links` that would allow you to fire off a single request instead.

Please join discord and ask for assistance there for questions regarding usage. server/invite link => [https://discord.gg/emberjs](https://discord.gg/emberjs)

**Comment by stephanebruckert** [comment]
Using `coalesceFindRequests` makes sense, as we are not loading any data twice. Thanks, that's my solution!
