### ISSUE TITLE
Ember Data 2.18.0< is not updating store record when a findRecord is called with reload true.

### ISSUE THREAD

**Issue by thilinadinith** [emberjs/data#5725]
trying to do 

      this.controllerFor('people/profile').store.findRecord( 'profile', id, {reload:true}).then( response => {

        this.controllerFor( 'people/profile' ).set( 'user',response);
        this.controllerFor( 'people/edit' ).set( 'person',response );
      
});

expected : flush the dirty record in the model- profile and update with new backend data.
but it doesn't update dirty record in model.

Ember Data 2.18.0

**Comment by runspired** [comment]
Discord is a better place to ask for help on these sorts of questions; however, I suspect your issue may be that you expect a reload to eliminate "dirty" state (e.g. local changes) or automatically `null` fields not included in the new API response. Local changes will be preserved during a reload and fields not included in a response are left "as is".

**Comment by thilinadinith** [comment]
thanks for the information. yes the issue was local changes are there with dirty state where i had to roll back those changes and call the findrecord which get data from api and it worked
