### ISSUE TITLE
Breaking change in Ember Data 3.2: Can no longer create a relation and persist it

### ISSUE THREAD

**Issue by psbanka** [emberjs/data#5728]
### Description

Prior to Ember Data 3.2, it used to be possible, given the following models:

```js
// TlsSubscription
export default DS.Model.extend({
  tlsDomains: hasMany('tlsDomain'),
})

// TlsDomain
export default DS.Model.extend({
})

```

to do the following:

```js
const newTlsDomain = this.store.createRecord('tls_domain', {
  id: domainName,
})
const customer = this.get('store').peekRecord('customer', customerId)
this.get('tlsSubscriptions').createRecord({
  certificateAuthority: 'lets-encrypt',
  tlsDomains: [newTlsDomain]
}).save()
```

That would produce the following (valid) JSON-API payload to the server:

```json
{
  "data": {
    "attributes": {
      "certificate_authority": "lets-encrypt",
    },
    "relationships": {
      "tls_domains": {
        "data": [
          {
            "type": "tls_domain",
            "id": "test.com"
          }
        ]
      }
    },
    "type": "tls_subscription"
  }
}
```

*However*, due to this pull-request: https://github.com/emberjs/data/pull/5317 from @ryanto 

Ember Data now refuses to serialize the object that has not yet been persisted to the server, and now we get the following payload:

```json
{
  "data": {
    "attributes": {
      "certificate_authority": "lets-encrypt",
    },
    "relationships": {},
    "type": "tls_subscription"
  }
}
```

It seems to me that this is a breaking API change and should have been delayed until the 4.x release (although this is a PR from about a year ago, so that ship has probably already sailed). It also seems to be a useful feature in Ember Data to be able to construct an API request in this fashion without necessarily saving other records off to the database.

**Comment by jamesarosen** [comment]
Some hacks that _might_ work, or might cause more problems:
```js
// model:tls-domain
isDeleted: computed(() => false),
isLoaded: computed(() => true),
isLoading: computed(() => false),
isNew: computed(() => false),
isReloading: computed(() => false),
isSaving: computed(() => false),
```

or

```js
const newTlsDomain = this.store.createRecord('tls_domain', {
  id: domainName,
  isNew: false,
})
```

**Comment by jamesarosen** [comment]
Last option: `serializeBelongsTo` is part of the [public API](https://emberjs.com/api/ember-data/3.5/classes/DS.JSONSerializer/methods/serializeBelongsTo?anchor=serializeBelongsTo). The answer could just be "override it." Unfortunately, it's a lot of logic to duplicate in a custom serializer.

**Comment by psbanka** [comment]
well, `isNew: false` on the model did the trick (did not need to be a CP), so as for hacks that seems to be the least horrible for now. Thanks, @jamesarosen

**Comment by ryanto** [comment]
Yikes, sorry about that @psbanka !

If you're building a record that's not new, in other words it has an ID that the backend would know what to do with, then I would recommend using `store.push` instead of `createRecord`. That will let you add models to the store that the backend knows about.

You can also override `serializeBelongsTo` if you need this functionality, it's the best place for this sort of escape hatch.

**Comment by psbanka** [comment]
@ryanto – `store.push()` works like a charm. Thank you! 👍
