### ISSUE TITLE
"content" field doesn't work through async relationships

### ISSUE THREAD

**Issue by ef4** [emberjs/data#5732]
(This is based off a [forum question](https://discuss.emberjs.com/t/ember-handlebar-view-for-foreignkey-values/15755).)

Given these fields:

```js
// app/models/answer.js
question: belongsTo('question'),

// app/models/question.js
content: attr('string'),
```

If you try to render the `content` field through the async `question` relationship, it doesn't work.

```hbs
{{someAnswer.question.content}}
```

The expected output is the value of the `content` field. The actual output is `<frontend@model:question::ember276:5>`.

The PromiseProxy's own `content` property takes precedence.

I don't think we can easily fix this without breaking other things, but we should consider at least linting for the `content` field name in models.

**Comment by igorT** [comment]
Until we remove proxies, we could move `.content` to a more private place, and expose `.content` as deprecated and prioritize the user supplied one.

**Comment by runspired** [comment]
.content is intimate API at this point, I thin adding “content” to the list of reserved property names is better for now until we have a stronger proposal for eliminating proxies.

**Comment by runspired** [comment]
@igorT @ef4 I have a proposal, best seen as a PR

**Comment by runspired** [comment]
I'll try to see if someone can pick up the work in https://github.com/emberjs/data/pull/5755 this week.

**Comment by runspired** [comment]
The scope of this issue is now only `PromiseBelongsTo`, since we assert for content properties there's nothing more for us to do here. When we replace `@ember-data/model` we will not use these older proxies.
