### ISSUE TITLE
Emberdata upgrade to 3.5 from 1.13 and it is not resolving belongsTo relationships

### ISSUE THREAD

**Issue by thilinadinith** [emberjs/data#5745]
i used to have emberjs 1.13 which i upgraded to 3.5 i got an issue with belongsTo relationships where i cannot access those data in it. my code as below

model
```

export default DS.Model.extend( {

  title: DS.attr( 'string' ),
  description: DS.attr( 'string' ),
  published: DS.attr( 'boolean' ),
  publishedAt: DS.attr( 'date' ),

  course: DS.belongsTo( 'course' ),
  author: DS.belongsTo( 'profile', { async: true } ),

  viewed: false,
  isNew: true,

}
```
in controller

```
this.get('model.published') working 
this.get('model.author.name') not working 
```
but the same code was working on 1.13 of emberjs

ember data 3.5
<img width="1425" alt="screenshot 2018-11-08 at 11 20 11 am" src="https://user-images.githubusercontent.com/11405429/48175895-d970d100-e348-11e8-91f2-a3fc1bce40c1.png">

ember 1.13
<img width="1436" alt="screenshot 2018-11-08 at 11 20 45 am" src="https://user-images.githubusercontent.com/11405429/48175918-ec83a100-e348-11e8-92e2-239bea2f7bb3.png">

**Comment by runspired** [comment]
`author` is an `async` relationship, you would need to resolve the promise first:

```
this.get('model.author').then(author => author.get('name')
```
