### ISSUE TITLE
queryRecord does not pass options hash to adapter

### ISSUE THREAD

**Issue by ivegner** [emberjs/data#5751]
The adapter's queryRecord method does not receive or parse the options hash passed to it. [Here](https://github.com/emberjs/data/blob/v3.5.0/addon/-private/system/store/finders.js#L490), it is evident that the `options` parameter is passed to `adapter.queryRecord()`, but in the adapter's corresponding method, the `options` hash is not listed in the [function declaration](https://github.com/emberjs/data/blob/v3.5.0/addon/adapters/rest.js#L562). This issue prevents passing `adapterOptions` to the adapter. This problem seems to also affect the other methods in the adapter, such as `query`. 

This problem was also noticed in #4497, and a PR was merged, but it did not fix the adapter-side code.

**Comment by runspired** [comment]
@ivegner adapterOptions is available in both `query` and `queryRecord`.

https://github.com/emberjs/data/blob/master/tests/integration/adapter/store-adapter-test.js#L1445-L1471
