### ISSUE TITLE
Class constructor EmberError cannot be invoked without 'new'

### ISSUE THREAD

**Issue by ssutar** [emberjs/data#5752]
When used with `ember-native-class-polyfill` for ES6 classes, following error is thrown: 
```
Uncaught TypeError: Class constructor EmberError cannot be invoked without 'new'
    at new AdapterError (vendor.js:132445)
    at Class.handleResponse (vendor.js:144384)
    at Class.handleResponse (vendor.js:122856)
    at Class.superWrapper (vendor-static.js:51234)
    at Class.handleResponse (vendor.js:89895)
    at Class.superWrapper [as handleResponse] (vendor-static.js:51234)
    at Class.handleResponse (vendor.js:119158)
    at Class.superWrapper [as handleResponse] (vendor-static.js:51234)
    at ajaxError (vendor.js:144655)
    at ajaxErrorHandler (vendor.js:144682)
```
It is originated from https://github.com/emberjs/data/blob/master/addon/-private/adapters/errors.js#L79
```
export function AdapterError(errors, message = 'Adapter operation failed') {
  this.isAdapterError = true;
  EmberError.call(this, message);

  this.errors = errors || [
    {
      title: 'Adapter Error',
      detail: message,
    },
  ];
}
```
As `EmberError` is a class with `ember-native-class-polyfill`, it cannot be called without `new`.

**Comment by ssutar** [comment]
I have a fix at https://github.com/ssutar/data/blob/v_3_5_beta/addon/-private/adapters/errors.js#L79 but its not same as the current code. 

Its something like this:

```
export function AdapterError(errors, message = 'Adapter operation failed') {
  this.isAdapterError = true;
  this.message = message;

  this.errors = errors || [
    {
      title: 'Adapter Error',
      detail: message,
    },
  ];
}
```

Its creating a new property `message` on the AdapterError instead of using one from `EmberError`. It works correctly due to prototype property lookup, but not sure if it is the correct fix.

cc: @rwjblue @krisselden

**Comment by pzuraq** [comment]
This depends on usage, but I think this is meant to be a class, and if so the accurate update would be:

```js
export class AdapterError extends EmberError {
  constructor(errors, message = 'Adapter operation failed') {
    super(message);
    this.isAdapterError = true;

    this.errors = errors || [
      {
        title: 'Adapter Error',
        detail: message,
      },
    ];
  }
}

**Comment by ssutar** [comment]
Yeap, but would that need `ember-native-class-polyfill` to be included? 🤔That is the reason why I was not changing it to class. But let me try doing it, if tests pass I think we should be okay!

**Comment by pzuraq** [comment]
Because this is a class which does not extend from `EmberObject` it should be fine. Native classes have worked by themselves for some time, just not when mixing with the Ember Object model.

**Comment by runspired** [comment]
@pzuraq I read through the conversation about making `Ember.Error` extend from `Error`. Personally I would prefer to just eliminate use of `Ember.Error` here entirely and also extend from `Error` ourselves if possible.

**Comment by rwjblue** [comment]
Agree with @pzuraq, error subclasses are hard :(

**Comment by runspired** [comment]
@rwjblue @pzuraq am I interpreting this correctly to mean `the subclassing in https://github.com/emberjs/data/pull/5753/files is not cross-browser`

**Comment by runspired** [comment]
We resolved this by reverting the change from function to class based definition of `EmberError` upstream.
