### ISSUE TITLE
[QUEST] Fix Gaps in Documentation

### ISSUE THREAD

**Issue by anlumo** [emberjs/data#5756]
As requested by @runspired, here are the things I found to be undocumented, but required to be known for using ember-data:

* [x] snapshot, as passed into many DS.Adapter functions.
* [ ] type, as passed into many DS.Adapter functions.
* [ ] The meta object given to the function passed to the functions `DS.Model.eachRelationship` and `DS.Model.eachAttribute`.
* [ ] How to notify the store about a record deletion from the server side.
* [ ] `DS.belongsTo` and `DS.hasMany` being async by default.
* [ ] When to use `unloadRecord`.
* [ ] How to unset attributes in a way that they revert back to the `defaultValue` instead of `null`.
* [x] A full step-by-step guide on how to implement the whole ember-data layer with a custom adapter that does not inherit from DS.JSONAdapter (including serializers).
* [ ] The undocumented fact that you have to push all changes that happened locally back to the store once they're on the server

Related: #4375

**Comment by runspired** [comment]
@anlumo working on getting lots of doc fixes resource, just wanted to say thanks for opening this ♥️

**Comment by runspired** [comment]
Going to roll this into #8394
