### ISSUE TITLE
Fastboot tests breaking with ember-data canary

### ISSUE THREAD

**Issue by kratiahuja** [emberjs/data#5760]
This is reproducible on a clean master where it is failing to build due to a ts file: https://travis-ci.org/kratiahuja/ember-cli-fastboot/jobs/460523308

Is there a way to fix this soon? I understand `ember-cli-addon-tests` does some tree magic which ember data also does.

I am happy to send a PR to fix this if someone can guide me into the changes.

cc: @igorT @runspired

**Comment by rwjblue** [comment]
This is fixed with recent changes by @igort, however we need to evaluate if we *must* support users directly using branches from git like is being done by ember-cli-addon-tests. IMHO, we should not in the long run (though perhaps we have to for some reason already?)...
