### ISSUE TITLE
generateIdForRecord api doc

### ISSUE THREAD

**Issue by yaxinr** [emberjs/data#5803]
https://github.com/emberjs/data/blob/8fabf969229a5d83cab2fe35e882eb9a9bccc33e/addon/adapter.js#L226

wrong:  generateIdForRecord(store, inputProperties)
must be: generateIdForRecord(store, type, inputProperties)

**Comment by runspired** [comment]
Thanks for pointing out the mistake in the docs!

**Comment by rajasegar** [comment]
@runspired Raised a PR #5892 , kindly verify
