### ISSUE TITLE
Relationship on sibling records lost after saving new record with the same relationship

### ISSUE THREAD

**Issue by MichalBryxi** [emberjs/data#5807]
### Reproduction

- A [Twiddle](https://ember-twiddle.com/44c82be3d29679ed0b173ce1a0524a96?openFiles=templates.application.hbs%2C) - all the details are described in the application template.

### Description

1. Relationships: visit hasMany sells. Sell belongsTo item.
1. App loads "visit" with included data: "sells" and "sells.item".
1. User clicks on the button that will create new sell. Sell has information about an item and respective visit. This sell will use item that is already linked to another sell.
Server saves the data and sends back JSON-API response describing the saved data. Exactly at that moment, all the already existing sells will lose their relationship link to their item - this is unexpected behaviour. It works with any number of sells. All the already loaded sells will lose the relationship link.

- I'm using gem 'jsonapi-resources', '0.9.2' to generate my data.
- The expected behaviour is that no sell will lose the relationship to the item after creating new sell.

### Versions

First known problematic version:
```cli
  "ember": "3.4.3",
  "ember-data": "3.5.0",
```

#### Tested versions of ember-data:

* 3.4.2 - no bug
* 3.4.4 - no bug
* 3.5.0 - bug present
* 3.6.0 - bug present

**Comment by MichalBryxi** [comment]
Thanks @BryanCrotaz. Tried to convert the twiddle to ember-cli app, but looks like your branch won't help with this problem. The export is here if you want to have a look that I'm not doing something silly: https://drive.google.com/file/d/17a1PbH1dbY4_Wr_ClvRA2I6nFgxuGnfU/view?usp=sharing

**Comment by runspired** [comment]
This is fixed in 3.10+ in the twiddle above.
