### ISSUE TITLE
docs sample error: recordRef push param must be with type

### ISSUE THREAD

**Issue by yaxinr** [emberjs/data#5808]
https://github.com/emberjs/data/blob/8fabf969229a5d83cab2fe35e882eb9a9bccc33e/addon/-private/system/references/record.js#L59

userRef.push({ data: { id: 1, **MUST PRESENT->type: 'user',** username: "@user" }}).then(function(user) {
   userRef.value() === user;
 });

**Comment by runspired** [comment]
I believe what we want here in the docs is

```javascript
userRef.push({
  data: {
    id: "1",
    type: "user",
    attributes: { username: "@user" }
 }
});
```

**Comment by rajasegar** [comment]
@runspired Raised a PR #5889 for the same, can you please verify the fix
