### ISSUE TITLE
Rest Serializer `isPrimaryType` should not use `store.modelFor`

### ISSUE THREAD

**Issue by igorT** [emberjs/data#5809]
Currently Rest Serializer implicitly does type normalization in `store.isPrimaryType` by calling `store.modelFor`. It shouldn't do that, it should normalize the type name itself

**Comment by runspired** [comment]
TL;DR

`isPrimaryType` is used in one location to check if the result of `store.modelFor(modelName)` is equal to the `ModelClass` provided to the serializer as the primary `ModelClass`.

It would be better to check if `normalizeModelName(modelName) === PrimaryModelClass.modelName`
