### ISSUE TITLE
Setting belongsTo relationship to new value results to null value

### ISSUE THREAD

**Issue by dmarkin** [emberjs/data#5810]
From https://github.com/emberjs/data/issues/5517
Maybe also related to https://github.com/emberjs/data/issues/5807
The bug is here.
I have the Model Offer, including
`type: belongsTo('offerType', {async: true})`
and Model Offer-type with some properties.
With updating from 2.12 to 3.5 Ember breaks down the app cause if I do
`offer.set('type', someNewTypeFromStore)`
I'll get finally
`offer.get('type') === null`

_Originally posted by @dmarkin in https://github.com/emberjs/data/issues/5517#issuecomment-450146155_

**Comment by BryanCrotaz** [comment]
Could this be related to #5822

**Comment by runspired** [comment]
@dmarkin did you ever come up with a reproduction? I still have doubts this is a real bug. So far any case I've been shown was an issue with the app not loading data in the right format.

**Comment by runspired** [comment]
Closing as we have no reproduction for this and this behavior is covered by multiple tests.
