### ISSUE TITLE
Infinite belongsTo fetch after 404

### ISSUE THREAD

**Issue by cbroeren** [emberjs/data#5814]
### Summary

Models keep fetching belongsTo relation object even when it returns a 404 (when they have an inverse relation). 

### Description 

Since we've upgraded ember-data from 3.5.2 to 3.6.0, we have some problems with getting belongsTo relation objects when they don't exist. For example, we have an object:
```js
{
  id:   ...,
  type: ...,
  relationships: {
    activity: 
      { data: { id: 58340, type: 'activity' }
  }
}
```
The back-end can't find the activity with id 58340 (or the user is not allowed to see it) and returns a 404. No problem with previous versions, but now it keeps trying to get it again and again, even when it already has received a 404. It only occurs when the relationship has an inverse. When I add `{ inverse: null }` to the belongsTo, it will just try twice (no answer to that not being once), and then it is resolved. 

#### Current behaviour
It tries to get the belongsTo object from the api, but on retrieving a 404 it keeps trying (infinitely) when an inverse is defined. 
#### Expected behaviour
try it once, and on retrieving a 404 it should stop (I expect it wouldn't exist after trying it 500 times either).

Note: I know our backend shouldn't return a relation with an id that doesn't exist anymore or the user may not retrieve, but I guess this infinite loop isn't expected behaviour either. 

### Reproduction
Remove the `{ inverse: null }` on the parent belongsTo relation in [this Twiddle](https://ember-twiddle.com/99cdb735d0451f093418157935955b8c?openFiles=models.person.js%2C).

### Versions
Latest working version: 3.5.2

Caused by this change:
https://github.com/emberjs/data/pull/5671/files#diff-fd4c34d9a34dfde73cd3413128a3c973R1563
(I changed that line back in a local linked ember-data project)

```cli
yarn list v1.12.3
├─ ember-cli@3.6.0
├─ ember-data-filter@1.13.0
├─ ember-data@3.6.0
├─ ember-source-channel-url@1.1.0
└─ ember-source@3.5.1
✨  Done in 1.06s.
```

**Comment by david-duncan** [comment]
Confirmed on 3.7, but not on 3.4. 

Found this when upgrading from 3.4 to fix an issue with 403 reflexive relationships. Inverse property doesnt matter in our case.

Probably same issue as https://github.com/emberjs/data/issues/5836

**Comment by Kilowhisky** [comment]
I also have this issue in 3.7 but only when built in release mode.
