### ISSUE TITLE
[Docs] error in DS.JSONSerializer normalize example (?)

### ISSUE THREAD

**Issue by dd-wrt-nxt** [emberjs/data#5819]
It looks like there's an error in the normalize example in the [DS.JSONSerializer API documentation](https://www.emberjs.com/api/ember-data/3.7/classes/DS.JSONSerializer/methods/normalize?anchor=normalize) 

`export default DS.JSONSerializer.extend({
  normalize(typeClass, hash) {
    var fields = get(typeClass, 'fields');

    fields.forEach(function(field) {
      var payloadField = underscore(field);
      if (field === payloadField) { return; }

      hash[field] = hash[payloadField];
      delete hash[payloadField];
    });

    return this._super.apply(this, arguments);
  }
});`

in line 9:

`fields.forEach(function(field) {`

should actually be

`fields.forEach(function(type, field) {`

since otherwise `field` does not contain the field name but the type (i.e. `attrib`,`belongsTo` etc.). Hope I didn't get this wrong.

**Comment by runspired** [comment]
correct, `field` would be the `value` and not the `key`

**Comment by rajasegar** [comment]
@runspired Raised a PR #5890 for the same, kindly verify and let me know
