### ISSUE TITLE
index 'currentState' is a reserved property name on instances of classes extending Model

### ISSUE THREAD

**Issue by erkie** [emberjs/data#5835]
Adding an `observer` to `currentState` on a model makes it throw an error when using that model.

### Reproduction

https://github.com/erkie/ember-data-bug-5835

#### Offending code:

```js
import Model from 'ember-data/model';
import { observer } from '@ember/object';

export default Model.extend({
  doSomethingWhenCurrentStateChanges: observer("currentState", function() {
    console.log("currentState changed!");
  })
});
```

#### Stack trace

```
router.js:1070 Error while processing route: index 'currentState' is a reserved property name on instances of classes extending Model. Please choose a different property name for model:my-model Error: 'currentState' is a reserved property name on instances of classes extending Model. Please choose a different property name for model:my-model
    at Class.init (http://localhost:4200/assets/vendor.js:68698:17)
    at Class.superWrapper [as init] (http://localhost:4200/assets/vendor.js:35506:28)
    at initialize (http://localhost:4200/assets/vendor.js:34130:9)
    at Function.create (http://localhost:4200/assets/vendor.js:34595:9)
    at FactoryManager.create (http://localhost:4200/assets/vendor.js:11437:39)
    at InternalModel.getRecord (http://localhost:4200/assets/vendor.js:66652:63)
    at _backburner.join (http://localhost:4200/assets/vendor.js:73602:32)
    at Backburner._run (http://localhost:4200/assets/vendor.js:53781:35)
    at Backburner._join (http://localhost:4200/assets/vendor.js:53760:29)
    at Backburner.join (http://localhost:4200/assets/vendor.js:53583:25)
```

### Description

Adding an `observer` to `currentState` on a model makes it throw an error when using that model.

I found this when upgrading from ember data 3.4 so not sure when it started.

### Versions

Run the following command and paste the output below: `npm ls ember-source && npm ls ember-cli && npm ls ember-data`.

```cli
emberdatabug@0.0.0 /Users/erik/tmp/emberdatabug
└── ember-source@3.7.2

emberdatabug@0.0.0 /Users/erik/tmp/emberdatabug
└── ember-cli@3.7.1

emberdatabug@0.0.0 /Users/erik/tmp/emberdatabug
└── ember-data@3.7.0
```

**Comment by runspired** [comment]
We added more guards to make sure that folks could not override certain properties (`currentState` is one of them).

As weird as this may sound, adding an observer to a property overrides it, and unfortunately we don't have a way of distinguishing between this sort of "enhanced setter" wrapper situation and a clobber.

I would also caution against using observers in general, especially an observer on `currentState`, as it is likely to trigger with poor timing resulting in unexpected outcomes. It's likely that a computed property watching one of the exposed state flags (vs currentState itself) would work better for you.

**Comment by igorT** [comment]
We are also hoping to move away from this pattern. Closing the issue, given the better warnings @runspired said we added
