### ISSUE TITLE
"Cannot create a new tag" when trying to access a deleted belongsTo relationship's ID

### ISSUE THREAD

**Issue by swastik** [emberjs/data#5840]
### Reproduction

Here's a repo with a reproduction: https://github.com/swastik/ember-data-cannot-create-tag

[Here's the route with the code that throws an error.
](https://github.com/swastik/ember-data-cannot-create-tag/blob/master/app/routes/index.js)

This happens in `ember-data` 3.5.0 and above. It worked fine on 3.3.2.

### Description

We have a `belongsTo` relationship that our API returns a 404 response for. If we try to access that model's `id` (or any other property) a couple of times with delays, it eventually leads to an error:

```
Assertion Failed: Cannot create a new tag for … after it has been destroyed.
```

<details>
  <summary>Stacktrace</summary>
  <p>

assert | @ | index.js:125
  | writableTag | @ | meta.js:228
  | tagFor | @ | metal.js:318
  | contentFor | @ | -proxy.js:21
  | unknownProperty | @ | -proxy.js:71
  | get | @ | metal.js:1218
  | _getPath | @ | metal.js:1230
  | get | @ | metal.js:1215
  | get | @ | observable.js:37
  | setTimeout | @ | index.js:22
  | setTimeout (async) |   |  
  | setTimeout | @ | index.js:21
  | setTimeout (async) |   |  
  | setTimeout | @ | index.js:19
  | setTimeout (async) |   |  
  | setupController | @ | index.js:17
  | superWrapper | @ | utils.js:284
  | setup | @ | route.js:725
  | _routeEnteredOrUpdated | @ | router_js.js:1446
  | routeEnteredOrUpdated | @ | router_js.js:1458
  | setupContexts | @ | router_js.js:1400
  | finalizeTransition | @ | router_js.js:1308
  | newTransition.promise.newTransition.promise.then.result | @ | router_js.js:1259
  | tryCatcher | @ | rsvp.js:313
  | invokeCallback | @ | rsvp.js:483
  | publish | @ | rsvp.js:469
  | _runloop.backburner.schedule | @ | rsvp.js:13
  | invoke | @ | backburner.js:247
  | flush | @ | backburner.js:168
  | flush | @ | backburner.js:320
  | _end | @ | backburner.js:750
  | end | @ | backburner.js:553
  | _run | @ | backburner.js:793
  | _join | @ | backburner.js:770
  | join | @ | backburner.js:593
  | join | @ | index.js:164
  | hash.success | @ | rest.js:888
  | fire | @ | jquery.js:3268
  | fireWith | @ | jquery.js:3398
  | done | @ | jquery.js:9305
  | (anonymous) | @ | jquery.js:9548
  | (anonymous) | @ | fake_xml_http_request.js:137
  | dispatchEvent | @ | fake_xml_http_request.js:181
  | _readyStateChange | @ | fake_xml_http_request.js:389
  | _setResponseBody | @ | fake_xml_http_request.js:453
  | respond | @ | fake_xml_http_request.js:474
  | (anonymous) | @ | pretender.js:395
  | resolve | @ | pretender.js:446
  | (anonymous) | @ | pretender.js:437
  | setTimeout (async) |   |  
  | handleResponse | @ | pretender.js:436
  | _handleRequest | @ | pretender.js:394
  | (anonymous) | @ | pretender.js:405
  | tryCatcher | @ | rsvp.js:313
  | invokeCallback | @ | rsvp.js:483
  | publish | @ | rsvp.js:469
  | _runloop.backburner.schedule | @ | rsvp.js:13
  | invoke | @ | backburner.js:247
  | flush | @ | backburner.js:168
  | flush | @ | backburner.js:320
  | _end | @ | backburner.js:750
  | end | @ | backburner.js:553
  | _run | @ | backburner.js:793
  | _join | @ | backburner.js:770
  | join | @ | backburner.js:593
  | join | @ | index.js:164
  | args | @ | index.js:256
  | mightThrow | @ | jquery.js:3534
  | process | @ | jquery.js:3602
  | setTimeout (async) |   |  
  | (anonymous) | @ | jquery.js:3640
  | fire | @ | jquery.js:3268
  | fireWith | @ | jquery.js:3398
  | fire | @ | jquery.js:3406
  | fire | @ | jquery.js:3268
  | fireWith | @ | jquery.js:3398
  | ready | @ | jquery.js:3878
  | completed | @ | jquery.js:3888
  </p>
</details>

### Versions

```cli
ember-data-test@0.0.0 /Users/swastik/Sites/ember-data-test
└── ember-source@3.7.3 

ember-data-test@0.0.0 /Users/swastik/Sites/ember-data-test
└── ember-cli@3.7.1 

ember-data-test@0.0.0 /Users/swastik/Sites/ember-data-test
└── ember-data@3.7.0 
```

**Comment by runspired** [comment]
It seems you are signaling that a record exists, then signaling that it no longer exists (which would lead it to be destroyed). Attempting to access properties and use a destroyed object ought to error. This particular error is likely occurring because the `404` is returning a malformed response.

**Comment by swastik** [comment]
Thanks @runspired. I'll try to dig into this some more.

**Comment by runspired** [comment]
I was able to determine that this is part of the issue with #5814 and that a solution there would resolve this as well
