### ISSUE TITLE
Broken in IE 11

### ISSUE THREAD

**Issue by btecu** [emberjs/data#5849]
See https://github.com/emberjs/data/blob/release/addon/-private/system/many-array.js#L139

`.find` on an array is not supported in IE.

![image](https://user-images.githubusercontent.com/7517745/52573718-bd1d7e00-2de8-11e9-9242-60e3f685b32e.png)

**Comment by runspired** [comment]
@btecu unless you are testing an addon in IE11 with prototype extensions turned off, arrays always have prototype extensions in which case `.find` will be present: https://github.com/emberjs/ember.js/blob/v2.14.1/packages/ember-runtime/lib/mixins/enumerable.js#L474

**Comment by btecu** [comment]
@runspired Actually the application has prototype extensions turned off because of some conflicts with a third party library. Ember is also moving away from prototype extensions, since they are not good practice anyway.

**Comment by btecu** [comment]
cc @rwjblue

**Comment by runspired** [comment]
> Actually the application has prototype extensions turned off because of some conflicts with a third party library. Ember is also moving away from prototype extensions, since they are not good practice anyway.

You absolutely need prototype extensions to use Ember with arrays. There may come a time when Ember no longer requires this, but that day is not here and until it is then the "best practice" is to use them as it is also the only practice.

You may not notice the sometimes-subtle bugs that occur in all browsers (array mutations won't trigger re-renders) or the major performance regressions in older browsers (like IE11) that come with arrays when you turn off prototype extensions, but they are there.

If you wish to go down the dangerous road of turning off prototype extensions for an application, then I think it comes with the territory that you should also bring your own polyfill for `Array.find` for IE11.

**Comment by btecu** [comment]
@runspired Actually `ember-data` runs without the prototype extensions fine. See here:
https://github.com/emberjs/data/blob/master/package.json#L103

You absolutely *do not* need prototype extensions to use Ember with arrays.

You can use the KVN compliant methods (`pushObject`, `pushObjects`...) and they work fine without having to enable prototype extensions.

Before upgrading `ember-data` from `3.4.3` to `3.7.0` it worked fine. My guess is that the issue was introduced with `RecordData`.

**Comment by rwjblue** [comment]
I tend to agree with @btecu here. `this.canonicalState` should be declared as `A()` here:

https://github.com/emberjs/data/blob/c43f9f9c85806d4e9748af318fcab3720736030d/addon/-private/system/many-array.js#L133

And when we flushCanonical here:

https://github.com/emberjs/data/blob/c43f9f9c85806d4e9748af318fcab3720736030d/addon/-private/system/many-array.js#L184

---

In the abstract, using Ember without prototype extensions is **very common**. For example, all addons test without prototype extensions by default ([see blueprint here](https://github.com/ember-cli/ember-cli/blob/69218c5f5e7479f14fe34e6b157548c92e53b4a0/blueprints/addon/index.js#L69-L70) and [ember-addon-output](https://github.com/ember-cli/ember-addon-output/blob/1290373d0d0a0e450bc6b01290157e64d1e31605/package.json#L38)), and indeed ember-data itself tests without prototype extensions turned on (as mentioned by @btecu).

This is absolutely a case of browser support matrix failure, not user error.
