### ISSUE TITLE
Getting the length of a relationship forces a loadMany even when this is unnecessary

### ISSUE THREAD

**Issue by markprzepiora** [emberjs/data#586]
I have a Folder model with many Items. Our JSON API returns the items as an array of IDs only (since any particular folder may potentially have thousands of items, each with several attributes, so we want to delay loading the details until needed.)

Therefore, after loading an `aFolder` model, calling `aFolder.get('items.length')` should simply return the number of IDs. And it does. But in addition, it triggers a `findMany` call which loads all the items! (Which in our case can be several megabytes of data and might even exceed the allowed length of a GET request.)

Is this intended behaviour? It seems very unnecessary.

jsFiddle here: http://jsfiddle.net/KrwLq/14/

``` javascript
App = Ember.Application.create();

App.store = DS.Store.create({
  revision: 11,
  adapter: DS.RESTAdapter.extend({
    findMany: function() {
      alert('why am I called!?') 
    }
  })
});

App.Item = DS.Model.extend();

App.Folder = DS.Model.extend({
  items: DS.hasMany(App.Item),
});

App.store.load(App.Folder,
  {
      id: 1,
      items: [1, 2]
  }
);

console.log('number of items:', App.Folder.find(1).get('items.length'));
```

**Comment by raafael911** [comment]
I'm encountering this behavior as well. It causes a big performance issue in our project. 
@wycats: If this topic is still open for discussion I would like to participate and hopefully come to a proposal with your help.

**Comment by sly7-7** [comment]
@raafael911 This is implemented by the references feature, for example using https://emberjs.com/api/data/classes/DS.HasManyReference.html#method_value

**Comment by raafael911** [comment]
@sly7-7 Thank you for the hint. Strangely the `value()` method returns `null` for my particular hasMany relationship (not for the others if the same record). But there also is a `ids()` method which simply returns the array of ids. Then I can access the length attribute of this array.
