### ISSUE TITLE
isLoaded/isUpdating does not work on ManyArray

### ISSUE THREAD

**Issue by leepfrog** [emberjs/data#587]
When using the isLoaded/isUpdating property, it will return erroneous values.  The screenshot below shows me querying the isLoaded/isUpdating parameters with a paused Rails backend.  The XHR response completing happened after unpausing the Rails backend.

![Screen Shot 2013-01-06 at 8 10 43 PM](https://f.cloud.github.com/assets/119997/46701/bf5d394e-5888-11e2-99de-4a8b7ddf9038.png)

**Comment by jkutzfla** [comment]
Hi, I think this issue is still an open issue.  I am manually loading a belongsTo relationship in my model hook, but the `isLoading` and `isFulfiled` checks are always true, even though ajax request is still going.

I resorted to setting a new attribute and watching that.

I am using Ember & EmberData 2.2.0

If anyone has a pointer to why this doesn't work, I could start looking at the code.

-Josh

**Comment by bmac** [comment]
@jkutzfla Do you mind putting together a [jsbin](http://emberjs.jsbin.com/sarobu/1/edit?html,js,output) reproducing the issue?

**Comment by jkutzfla** [comment]
Ok, my jsbin is here:
http://emberjs.jsbin.com/netogagevo/1
Thank you for the template.

If you click on the '2nd route' link you should see what I mean. It is a belongsTo relationship and I set a 2 second delay in the mockjax.  When the view first renders, the model.address.isLoading is blank.  When the ajax completes, the isLoading updates to false.  But the isLoading was never set to true, so it cannot be used as a conditional in the template.

Maybe my approach of set'ing the relationship by hand in the model() is not recommended?
My goal is to have the model relationships available, but they will not always be included as defined relationships in the JSON API.

-Josh

**Comment by IBue** [comment]
@jkutzfla What you see in your jsbin is quite correct (except you should call `peekRecord('author',1)` ).

1.  _author#1_ doesn't know anything about your _address#123_ until you assign it (after 2 secs); →look at the internal ID of _model.address'_ DS.PromiseObject
2. _author#1_ is a fully resolved DS.Model on entering _MytestRoute_ and by no means a promise, so: `isLoaded=true`, `isFulfilled=undefined`
3. _author#1.address_ is initially not set on entering _MytestRoute,_ but there is a DS.PromiseObject for it with content `null,` so: `isLoading=undefined` (no DS.Model there), `isFulfilled=true` (no promise in action)
4. after 2 secs you assign a resolved DS.Model of _address#123_ to _author#1.address,_ resulting in a new DS.PromiseObject with content _address#123_, so: `isLoading=false,` `isFulfilled=true`

I have derived a new jsbin that demonstrates real asynchronous loading of _author#123_:
[http://emberjs.jsbin.com/najubuzewe/1](url)
