### ISSUE TITLE
pushedData not handled in deleted.inFlight

### ISSUE THREAD

**Issue by jlami** [emberjs/data#5908]
### Reproduction
https://github.com/jacobq/ember-pouch-test-problem
https://github.com/pouchdb-community/ember-pouch/issues/237

### Description
When doing the equivalent of `store.findAll('person').then(p => p.invoke('save'))` after an entry is marked as deleted, the sequence of events is the following:
- findAll returns the currently loaded persons (`shouldBackgroundReloadAll` is `true` in ember-pouch)
- the save executes the `adapter.deleteRecord` and the models go into state root.deleted.inFlight
- the findAll results come in from the adapter and trigger a pushedData

This results in the exception: "Attempted to handle event `pushedData` on <person:...> while in state root.deleted.inFlight. "

#### Expected behavior
The save should go through and the pushedData should be 'ignored', just like it is in the root.deleted.uncommitted state.

### Versions
ember-source@3.5.1
ember-cli@3.5.1
ember-data@3.5.2

I'm not sure if adding pushedData as an expected event in the root.deleted.inFlight state will cause any problems. Does that fill in new data and update relationships that might have already been torn down?

**Comment by runspired** [comment]
@jlami curious, why `save` after `find` (especially via `findAll` which would seem particularly deadly)

**Comment by jlami** [comment]
I know it is a bit weird. And in the related issue I already explained that `peekAll` should be better.

But it still remains a fact that in asynchronous code a lot of transitions might happen. Especially the way `findAll` works with `shouldBackgroundReloadAll`, this sequence of events can always occur. Even when split up into a routes `.model()` and some action handler.

**Comment by runspired** [comment]
since the state machine no longer exists this is likely just ignored at this point, please open an issue if there still is one
