### ISSUE TITLE
locally available BelongsTo relationships return proxy with unresolved promise

### ISSUE THREAD

**Issue by Alonski** [emberjs/data#5913]
### Reproduction

With the help of https://github.com/sukima I have a Twiddle which shows this error. Instructions inside.

https://ember-twiddle.com/b0b4e0662d4562bda383b983c03c7be1?openFiles=templates.application.hbs%2C

Something that *is* different in this Twiddle is that these relationships aren't `async: false` and that is because they are loaded by Mirage as two different resources. I hope that this will still show the error in such a way that it is easy to understand what is going on.

### Description

Originally posted here: https://discuss.emberjs.com/t/ember-data-proxy-belongsto/16327

I have 2 models. 
The parent has a `hasMany` relationship with the children. 

Each child has a `belongsTo` relationship with its parent. 

Before upgrading from Ember Data v2.18 -> 3.7 I was able to get the parent from the child by doing ` child.parent` or `child.get("parent")` and it just worked.

Now I am getting a Proxy object. I tried setting `async: false` on the parent belongsTo like this: `parent: belongsTo("parent-model", { async: false })`

This didn't work either. 

The children are embedded of the parent, so they are all loaded in the same request. 
```
export default Model.extend({
    children: hasMany("child-model", { async: false }),
});
```
```
export default Model.extend({
    parent: belongsTo("parent-model")
});
```

### Versions

```cli
λ npm ls ember-source && npm ls ember-cli && npm ls ember-data
camilyo@14.9.0 
`-- ember-source@3.7.3

camilyo@14.9.0 
`-- ember-cli@3.7.1

camilyo@14.9.0 
`-- ember-data@3.7.0
```

**Comment by Alonski** [comment]
From Discord:
> yeah, the specifics of the issue (and if you can attempt a twiddle, please do) are:

a sync hasMany pointing at a sync belongsTo (unclear if the left side being a hasMany matters) in which the left side loads the relationship and the right side is missing the relationship from it's payload (unclear if it missing matters) results in the BelongsToProxy being in a resolved content state but with a pending promise.
I suspect that this broken state is transient, and that after the next runloop tick the relationship is in the loaded state

**Comment by runspired** [comment]
To add an extra note of clarification (I'll update the title to reflect this) the potential issues is not that we return a proxy here (that is expected) but that the proxy has an unresolved promise when it should have a resolved promise

**Comment by runspired** [comment]
After investigating, I don't believe there is an issue with promise resolution, [see improved twiddle for replicating](https://ember-twiddle.com/13004a0eae8fddb543e7705d372eb1b0?openFiles=models.child.js%2C).

As you may note, whether the relationship is a proxy or is a record depends on whether the belongsTo is set to `async: true` (proxy)  vs `async: false` (no proxy).

**Comment by Alonski** [comment]
@runspired I wasn't sure how to create a Twiddle that exactly replicates my issue. My issue is when the relationships are `async: false` and I still get a Proxy and not the record.

**Comment by runspired** [comment]
@Alonski in the examples you've shown me thus far, your relationship was set to `async: true`. You can see in the twiddle I provided that if you set it to `false` you don't get a proxy.
