### ISSUE TITLE
fetch implementation returning empty payloads in Octane blueprint

### ISSUE THREAD

**Issue by mwpastore** [emberjs/data#5927]
### Reproduction

https://github.com/mwpastore/ember-data-fetch-demo-app/commit/8d01a579b91a2532df2a344d56c296f26ab7a78b

### Description

After the original fetch-findAll bug (#5918) was fixed (#5925), I went to try it again and got a new error: 

```
You made a 'findAll' request for 'article' records, but the adapter's response did not have any data
```

The responseText property of the Mirage response looks fine. If I do my own request and use pushPayload, it works fine. Installing jQuery fixes it without any code changes:

```
ember install @ember/jquery
ember feature:enable jquery-integration
```

### Versions

Octane

**Comment by CodingItWrong** [comment]
Here's an even more minimal reproduction that doesn't involve using Mirage, just creating a model and trying to `findAll` for it:

https://github.com/CodingItWrong/octane-sandbox/commit/37942e8892e4d7cc5e62a60696c5f81f2f3bcf67
