### ISSUE TITLE
Adapter's `ajax` and `ajaxOptions` should be deprecated

### ISSUE THREAD

**Issue by dcyriller** [emberjs/data#5932]
`ajax` and `ajaxOptions` are used to build the network request. Since the recent fetch integration 🎉, they've been using either `fetch` or `jQuery.ajax` internally.

Then, they should be renamed to something else. Maybe `request`and `requestOptions`?

Does this change need an RFC or following the deprecation process would be enough?

```javascript
ajax(args) {
  ... deprecation methods
  return this.request(args)
}
```

```javascript
ajaxOptions(args) {
  ... deprecation methods
  return this.requestOptions(args)
}
```

```javascript
request(args) {
  if(useFetch) {
    return fetch(url, options).then(fetchSuccessHandler).catch(fetchErrorHandler)
  } else {
    return ajax(url, options).then(ajaxSuccessHandler).catch(ajaxErrorHandler)
  }
}
```

```javascript
requestOptions(args) {
  if(useFetch) {
      return _fetchOptions(args);
  } else {
      return _ajaxOptions(args);
  }
}
```

**Comment by runspired** [comment]
This would require an RFC and we've looked at RFCing this a few times before, including one that was nearly completed and then abandoned.

Our general consensus at this time is that the existing RESTAdapter/JSONAPIAdapter hooks (and similarly existing Serializer hooks) simply do not have a clear path forward without several heavy rounds churn and deprecation lifecycles.

Our preferred approach is to introduce an alternative paradigm for managing requests that has richer context about the data being requested and how to manage the response. We expect to begin RFC level work for this over the coming months, and are always interested in help :)

**Comment by runspired** [comment]
Closing in favor of RFC

**Comment by dcyriller** [comment]
👍 thank you for the clarification
