### ISSUE TITLE
Calling findRecord without an id results in confusing error state in production builds

### ISSUE THREAD

**Issue by paddyobrien** [emberjs/data#5958]
Calling `store.findRecord('foo', undefined)` fails in a dev build with a very helpful error message:

```
Error: Assertion Failed: `id` passed to `findRecord()` has to be non-empty string or number
```

However doing the same thing in a production build does not fail and instead issues a request as if you had called `store.findAll('foo')`. It then resolves the promise with a model in a weird state where all fields are undefined:

![Screenshot 2019-04-01 at 17 22 14](https://user-images.githubusercontent.com/846372/55343299-b6cf8800-54a2-11e9-960c-212b449fa78e.png)

This probably happens because the argument validation is implemented using `Ember.assert` [here](https://github.com/emberjs/data/blob/master/addon/-private/system/store.js#L752-L755) and these assertions are stripped from production builds.

This behaviour can result in an extremely confusing and hard to understand situation where a model hook resolves but the model is in a completely broken state. It would be preferable in these cases for the model hook to just fail with the same or similar exception as we see in dev.

**Comment by snewcomer** [comment]
I find the debug scenario helpful but in client code overall, if I am unsure of the type of identifier will be passed, I assumed this would be left up to the client to guard.  What are your thoughts?

**Comment by travisghansen** [comment]
All things considered, the divergent behavior here is extremely bad form IMO.

**Comment by paddyobrien** [comment]
Looks like this got fixed in https://github.com/emberjs/data/pull/6561
