### ISSUE TITLE
`relationship-meta` example incorrectly shows `link-meta` instead of `relationship-meta`

### ISSUE THREAD

**Issue by oliverlangan** [emberjs/data#5969]
https://github.com/emberjs/data/blob/24e69e2d14ece1e363da9b65e174b19f59f782ba/addon/-private/system/references/reference.ts#L153

The example for DS.Reference#meta shows a metadata block as a descendant of  the `links` object, which does not actually work.
```
relationships: {
  user: {
    links: {
      related: {
        href: '/articles/1/author',
        meta: {
          lastUpdated: 1458014400000
        }
      }
    }
  }
}
```

According to the [JSON:API](https://jsonapi.org/format/#document-resource-object-relationships) spec, `meta` is allowed as a sibling/alternative to `links`. *This actually works in Ember Data* using `model.hasMany(relationship).meta()`, so the example should be updated:
```
relationships: {
  user: {
    links: {
      related: '/articles/1/author',
    },
    meta: {
      lastUpdated: 1458014400000
    }
  }
}
```

**Comment by oliverlangan** [comment]
A coworker pointed out that the metadata shown in the docs is indeed [valid JSON:API syntax](https://jsonapi.org/format/#document-links). However, this is still a valid issue because the `meta` method does not return that information.

**Comment by runspired** [comment]
@oliverlangan right, `meta` method is for the relationship-meta, not the link-meta

**Comment by snewcomer** [comment]
This can be closed!
