### ISSUE TITLE
Migrate to env variables from command flags

### ISSUE THREAD

**Issue by runspired** [emberjs/data#6009]
Currently our build utilizes command flags for determining when to keep in-progress-features and instrumentation in the build output. We should migrate these to environment variables to avoid the warning (and potential future assertion) that ember-cli throws for these flags.

See the comment here some additional context: https://github.com/emberjs/data/pull/5997#discussion_r274039678

**Comment by rwjblue** [comment]
Thanks for opening the issue for tracking @runspired.
