### ISSUE TITLE
`release` branch is not ignoring tests it should ignore

### ISSUE THREAD

**Issue by runspired** [emberjs/data#6049]
external partner tests, `release|beta|canary` tests of ember should not run for CI runs for release branch.

**Comment by mbinet** [comment]
Hello @runspired!

I've had a look at this issue and I'm not sure to understand.

Indeed, see the last build on the release branch: https://travis-ci.org/emberjs/data/builds/523223535
`external partner tests`, `Ember Release`, `Ember Beta` and `Ember Canary` do not run.

Could you give me additional informations please?

**Comment by runspired** [comment]
@mbinet I noticed this issue here https://travis-ci.org/emberjs/data/builds/522353527

It may be specific to the tag vs the branch.

**Comment by mbinet** [comment]
Oh ok I see!

Yes it does seem to be related to the tags.

So to clarify, we do **not** want to run these tests on tags, right?

**Comment by runspired** [comment]
@mbinet confirm

**Comment by runspired** [comment]
@mbinet in fact I see no reason to run tests for pushes of tags at all, since they always reflect a branch at the time they are created (beta or release)
