### ISSUE TITLE
Prevent packages from publishing typings

### ISSUE THREAD

**Issue by runspired** [emberjs/data#6052]
Prior to the monorepo conversion @mike-north had concocted  a strategy for preventing us from shipping typings.

This is beneficial in a few ways:

- most of our typings concern private APIs
- our types may eventually become public API but they are too unstable currently to be considered public API
- Typescript doesn't play the best with semver historically and this is a safeguard to help us ensure we remain semver

I forget the details of the strategy we had agreed on, but effectively each package will need to be configured to prevent shipping the types and this is something we must fix prior to shipping the multi-package architecture in a stable release.

**Comment by mike-north** [comment]
You need to add an explicit reference in each (published package's) package.json
```json
"types": "path/to/thing.d.ts"
```
and make sure you publish that `.d.ts` file. The file's contents will end up looking like

```ts
// one module declaration per public API module
declare module 'ember-data';
declare module 'ember-data/relationships';
declare module 'ember-data/model';
```

This strategy provides the following outcome:

* ember-data is shipping types
   * but only an indication of _which modules are part of the public API_
   * with no information about what those modules might contain
* if someone chooses to install `@types/ember-data`, they'll merge with the above type declarations neatly, and real-type checking will be possible

**Comment by runspired** [comment]
@mike-north thanks for all the context!
