### ISSUE TITLE
Ember-Data 3.9.1 adapter "headers" seems to be not getting sent.

### ISSUE THREAD

**Issue by nikhilsane** [emberjs/data#6058]
# Ember-Data 3.9.1 JSONAPIAdapter does not seem to send headers.

Hi Ember-Data team,

I have following Adapter in my application:
```
export default DS.JSONAPIAdapter.extend({
    namespace: '/foo/resources/v2.0',
    init() {
        this._super(...arguments);

        this.set('headers', {
            'Accept': 'application/json',
            'ApplicationQuery': '1'
        })
    }
});
```
When using **v3.9.1**, the "findAll" query sends the following header in the request:

> Request headers:
> Host: localhost:9000
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
> **_Accept: application/vnd.api+json_**
> Accept-Language: en-US,en;q=0.5
> Accept-Encoding: gzip, deflate
> Content-Type: application/vnd.api+json
> ApplicationQuery: 1
> X-Requested-With: XMLHttpRequest
> Connection: keep-alive
> Cookie: JSESSIONID=02E588F5129EFD7540B86F6F526D2371
> 

When using **v3.5.1**, the "findAll" query that is sent to the back-end API looks like the following:

> Request headers:
> Host: localhost:9000
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
> _**Accept: application/json**_
> Accept-Language: en-US,en;q=0.5
> Accept-Encoding: gzip, deflate
> X-Requested-With: XMLHttpRequest
> Connection: keep-alive
> Cookie: JSESSIONID=487615003A26F1141D0F22B9354F409B
> 
> 

So, as can be seen from the above outputs, the same code does not seem to work in v 3.9.1. Is this expected behavior? Am I missing something here?

### Versions

Following are the versions of the packages: ember-source, ember-cli, ember-data

```
`-- ember-source@3.7.0
`-- ember-cli@3.1.4
`-- ember-data@3.9.1
```

--------------------------------------------------------------
Thanks,

Nikhil.

**Comment by runspired** [comment]
Hi Nikhil,

This does appear to be a regression.[ This line here](https://github.com/emberjs/data/blob/master/packages/adapter/addon/json-api.js#L156) needs to be changed to the following

```js
options.contentType = options.contentType || 'application/vnd.api+json';
```

If you could submit a PR with this fix and a test that would be greatly appreciated :)

**Comment by nikhilsane** [comment]
Hi Chris,

Thanks for pointing me to the code line causing this issue. I have made the change, and now trying to push my local branch to the repository, but I am getting following error:

> remote: Permission to emberjs/data.git denied to nikhilsane.
> fatal: unable to access 'https://github.com/emberjs/data.git/': The requested URL returned error: 403

Seems like I do not have permissions to submit to this repo.

thanks,
nikhil.

**Comment by runspired** [comment]
@nikhilsane generally you would fork the repo, push to your own fork, and PR from your fork to this repository. Happy to help you learn how to do so if you are not familiar with that process :)

**Comment by nikhilsane** [comment]
@runspired : Thanks for the information. I have created a pull request from a fork. Please let me know if there is something missing. 

Thanks,

**Comment by rwjblue** [comment]
@runspired https://github.com/emberjs/data/blob/2db279aa154a5ce83875352dafe98296b606eb26/packages/adapter/addon/json-api.js#L159 is also an issue, we cannot assume to force `Accept` like this

Consider:

```js
  headers: computed(function() {
    return {
      'Content-Type': 'application/vnd.api+json; version=1',
      'Accept': 'application/vnd.api+json; version=1'
    }
  }),
```

**Comment by runspired** [comment]
@rwjblue that was already noted in the PR discussion, but thanks :)

**Comment by eluciano11** [comment]
Hi ember-data team, 

First of all, thank you for your work!

I'm writing because I found an issue on the `ajaxOptions` methods as well.

## Issue
The issue that I'm seeing is the following:
`Error while processing route: two-factor-auth Cannot read property 'contentType' of null TypeError: Cannot read property 'contentType' of null`

It seems like the `ajaxOptions` is receiving `null` as an argument and the object that's being used as the function default param is not being applied.

Example:
![Screen Shot 2019-08-13 at 11 11 20 AM](https://user-images.githubusercontent.com/6109151/62957091-1b401380-bdc2-11e9-8ff6-f65d0b36736b.png)

I've confirmed that this is happening on ember-data version greater than 3.9.0.

## Versions
```
"ember-source": "~3.11.1",
"ember-data": "3.11.4",
```
