### ISSUE TITLE
tests: a fetch query seems not to be catched by Pretender

### ISSUE THREAD

**Issue by dcyriller** [emberjs/data#6083]
https://github.com/emberjs/data/pull/5975 does the CI setup for testing with both opting in and out of jQuery. As a consequence, the adapter test suite is run with both `fetch` and `ajax`.

When using ajax, [this test](https://github.com/emberjs/data/pull/5975/files#diff-ce1f08de89610ad4a9e80807e91536cdR2862) is running fine. With fetch, the network call is not catched by Pretender.

For now, the test is scoped to jQuery. But it could enabled when jQuery is opted out.

See this conversation for details: https://github.com/emberjs/data/pull/5975/files#r280937905

**Comment by Gaurav0** [comment]
We are using Pretender 2.1.1, which supports intercepting both native and polyfilled fetch.

How to run the linked test using fetch instead of ajax?

**Comment by dcyriller** [comment]
I would expect it to run with the command `yarn test:with-ember-fetch`, provided the if statement is removed. Not sure, it was your question?
