### ISSUE TITLE
[FEAT tests] lint assertions to ensure labels/descriptions

### ISSUE THREAD

**Issue by runspired** [emberjs/data#6090]
This might be all we need https://github.com/platinumazure/eslint-plugin-qunit

TL;DR add for qunit asserts to enforce that the asserts have labels.

eg. not assert.ok(bool) but assert.ok(bool, 'some-label') and not assert.equal('a', 'b') but assert.equal('a', 'b', 'some-description')

**Comment by pete-the-pete** [comment]
Looking into it.

**Comment by runspired** [comment]
Completed by #6096
