### ISSUE TITLE
Migrate jQuery detection to using static build time macro

### ISSUE THREAD

**Issue by rwjblue** [emberjs/data#6093]
Once https://github.com/embroider-build/embroider/issues/162 has been implemented, update `packages/adapter/addon/rest.js` to leverage the new functionality in the `useFetch` detection.

**Comment by runspired** [comment]
With the landing of #6737 we could use that to add/remove both our jquery and fetch codepaths.

**Comment by rwjblue** [comment]
Ya, sounds good to me...

**Comment by runspired** [comment]
closing in favor of deprecation stripping which will be made available when implementing emberjs/rfcs#790
