### ISSUE TITLE
[BUG ci] Azure builds exhibit flakey behaviors for external-partners

### ISSUE THREAD

**Issue by runspired** [emberjs/data#6104]
Periodically external-partner tests on Azure will fail because the link command for the locally packaged version of `ember-data` will fail. Sadly it does not give us much more information in the log than that. We should:

- [x] improve the log to contain the error trace for the failure (if one exists that is being swallowed)
- [ ] investigate whether Azure has a way to restart individual checks (currently seems like we have to restart entire builds)
- [x] determine a fix for ensuring we can consistently `npm link` our local tarball

Example Failure: https://dev.azure.com/ember-data/emberjs/_build/results?buildId=172&view=logs&jobId=0f730510-e886-53d0-e9ee-3135be6cf1a2

**Comment by runspired** [comment]
using `DEBUG=test-external` to run the tests with extra logging it became clear that this wasn't an issue with flakiness but rather that when PR's introduce issues that prevent a package from being correctly published this will result.

In the particular failure linked, a rebase had re-introduced a `bin` command in the `package.json` of the `-build-infra` package that pointed at a file that no longer existed, causing install of the package to fail.

**Comment by igorT** [comment]
Oh that is actually an awesome catch. Makes me pretty happy
