### ISSUE TITLE
[CHORE] eliminate nodetest-runner in favor of default mocha test runner

### ISSUE THREAD

**Issue by runspired** [emberjs/data#6111]
Currently we provide our own test runner for our mocha tests that test our node and blueprint code. If we no replace mocha-only-detector with an eslint rule and address windows support we should be able to eliminate our custom test runner.

**Comment by makepanic** [comment]
Do you remember why the nodetest-runner was disabled for windows?

I'll try to work on this issue.

**Comment by efx** [comment]
@runspired anything else needed to close this one?

**Comment by makepanic** [comment]
https://github.com/emberjs/data/pull/6131 is still open but I'm not sure if there's anything to do to that prevents merging
