### ISSUE TITLE
Ember octane: tracked issue

### ISSUE THREAD

**Issue by antonbavykin1991** [emberjs/data#6143]
There is issue with modelName, when I try to create polymorphic relationship
```
export class SeoRecordableModelSchema extends Model {
  @hasMany('base', { async: false, polymorphic: true })
  contents;
}
```
in console I have this message:
```
You attempted to update model:base.modelName to "text", but it is being tracked by a tracking context, such as a template, computed property, or observer. In order to make sure the context updates properly, you must invalidate the property when updating it. You can mark the property as `@tracked`, or use `@ember/object#set` to do this.
```
resolved  when add `@tracked` prop to the Base model
```
export default class Base extends Model {
  @tracked
  static modelName
}
```

**Comment by rwjblue** [comment]
@antonbavykin1991 - Can you whip up a demo reproducing the underlying issue? Will make it easier to track down (pun intended)...

**Comment by runspired** [comment]
I suspect this is a manifestation of #6143 which is a scenario we intended to deprecate in #4886 which never was completed. @dmzza and @antonbavykin1991 can you verify that when this occurs the polymorphic base class is being re-exported for use as multiple "types" without being extended?

**Comment by dmzza** [comment]
@runspired I don’t think my issue is the same as the one described in #4886. 

This is my use case:

```ts

import Model from 'ember-data/model';
import { tracked } from '@glimmer/tracking';

export default class Variation<U> extends Model {
  @tracked static modelName: string
  // ...
}

```

```ts
// single-line-variation.ts
import Variation from "./variation";
import { SingleLine } from "./preset";

export default class SingleLineVariation extends Variation<SingleLine> {}

```

So I do extend the base class.

**Comment by runspired** [comment]
Interesting. @dmzza could you try to track down why the modelName is being set then, and what it changes from:to? Once it has been set once it shouldn't be changed.

**Comment by sakthikanth** [comment]
Worked for me " @tracked " by import { tracked } from '@glimmer/tracking';
Thank you..
