### ISSUE TITLE
Changing a parent then unload a child record clears the hasMany relationship current state of the parent

### ISSUE THREAD

**Issue by lsg-braymon** [emberjs/data#6146]
### Reproduction
* Pull Request Link: https://github.com/emberjs/data/pull/6147

### Description
1. Model setup:
    ```js
    class Person extends Model {
      @hasMany('pet', { inverse: 'owner', async: false })
      pets;
      @attr()
      name;
    }

    class Pet extends Model {
      @belongsTo('person', { inverse: 'pets', async: false })
      owner;
      @attr()
      name;
    }
    ```
1. Data:
    ```
    personA:
      pets: petA
  
    personB:
      pets: petB
    ```
1. Update the owner of `petB` so that it is now owned by `personA`:
    ```js
    petB.set("owner", personA)

    // It will result in the following relatioships:
    personA.pets // [petA, petB]
    personB.pets // []
    ```
1. Unload the original pet of `personA` which is `petA`: `petA.unloadRecord()`.
1. Inspect the relationships:
    ```js
    petB.owner // personA
    personA.pets // BUG: this is now empty. The expected result is [petB]
    ```

### Versions

Run the following command and paste the output below: `npm ls ember-source && npm ls ember-cli && npm ls ember-data`.

```cli
ember-source@3.10.0
ember-source@3.10.0
ember-data@3.11.0-beta.1
```
We were also using ember-data@3.10.0 before and the issue is also present in that version.

**Comment by runspired** [comment]
This was fixed at some point with all of the relationship layer cleanup :)
