### ISSUE TITLE
JSONAPI adapter content-type is being blanked over by application/vnd.api+json on POST

### ISSUE THREAD

**Issue by Benjy1979** [emberjs/data#6167]
### Reproduction

Please provide one of the following:

- a PR linking to this issue with a failing test showing the issue
A what?
- a [Twiddle](https://ember-twiddle.com/) with a simplified reproduction and instructions for how to
  observe the unexpected result.
Not familiar with it. It doesn't let me add an adapter and does not have the right version in the dropdown. 
- a github repository with a simplified reproduction and instructions for how to observe the unexpected result
 [Here is a repository](https://github.com/Benjy1979/ember-adapter-bug)

Check POST in the model adapters of CreateRecord call.

### Description

[See this for description ](https://github.com/emberjs/ember.js/issues/18112#issuecomment-503137074)

### Versions

Run the following command and paste the output below: `npm ls ember-source && npm ls ember-cli && npm ls ember-data`.

```cli
ember-roomviewer-bighomeshop@0.0.0 C:\inetpub\wwwroot\ember-roomviewer-bighomeshop
`-- ember-source@3.10.1

ember-roomviewer-bighomeshop@0.0.0 C:\inetpub\wwwroot\ember-roomviewer-bighomeshop
`-- ember-cli@3.10.1

ember-roomviewer-bighomeshop@0.0.0 C:\inetpub\wwwroot\ember-roomviewer-bighomeshop
`-- ember-data@3.10.0

```

*P.S. If any of the packages show more than one installed version, that may be the root cause of the issue!*

--------------------------------------------------------------

Thanks again!

The `ember-data` Team <3

**Comment by Benjy1979** [comment]
I've put a project showing simple program to reproduce the issue:
 [Here is a repository](https://github.com/Benjy1979/ember-adapter-bug)

**Comment by runspired** [comment]
@Benjy1979 if you properly case to `Content-Type` is it set?

**Comment by Benjy1979** [comment]
No it stays the same.
`Accept: application/vnd.api+json
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 66
Content-Type: application/vnd.api+json
Cookie: _ga=GA1.1.1842830690.1557486605; lc_sso10275727=1558697657640
Host: localhost:4200
Origin: http://localhost:4200
Pragma: no-cache
Referer: http://localhost:4200/
User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Mobile Safari/537.36
x-access-token: TOKENHERE
X-Requested-With: XMLHttpRequest`

**Comment by Benjy1979** [comment]
No it stays the same

**Comment by runspired** [comment]
I think this will resolve it: https://github.com/emberjs/data/pull/6169

**Comment by Benjy1979** [comment]
How do I get hold of the changes, I'm not too familiar with what I can do with that link. 1 of the tests are failing.

I normally just get the release as a zipped download.

**Comment by runspired** [comment]
@snewcomer was this fixed by #6341 ?

**Comment by snewcomer** [comment]
Yes it was!  At least for the `fetch` case - https://github.com/emberjs/data/pull/6341/files#diff-ad84fbc878beedc97078e5053b8e41d7R1102

For `ajax`, it is relying on `contentType` and shouldn't be blanking over it anymore!

**Comment by Benjy1979** [comment]
I'm sure it works great when you only have one Application adapter.
The problems occur when customizing an adapter (the JSONAPI Adapter in my case) (ie inheriting the application one for a particular model).

 If you customize a model you can't set the headers on it. It just reverts some other default one - not even the one from the application adapter.

**Comment by Benjy1979** [comment]
Ah yes it is working now, my extended adapter for a particular model is reading the header callback. Thanks very much.
