### ISSUE TITLE
Document usage of DS.InvalidError together with DS.JSONAPIAdapter

### ISSUE THREAD

**Issue by lolmaus** [emberjs/data#6173]
**UPD**: this started as a bug report but turned out to be a misuse caused by lack of documentation. See the following comment.

## Description

The [documentation for DS.InvalidError](https://api.emberjs.com/ember-data/3.10/classes/DS.InvalidError) provides an example of returning a rejected promise from the adapter's `updateRecord` method:

```js
  export default DS.RESTAdapter.extend({
    updateRecord() {
      return RSVP.reject(new DS.InvalidError([
        {
          detail: 'Must be unique',
          source: { pointer: '/data/attributes/title' }
        },
      ]));
    }
  });
```

The highlighted part of the following statement from the documentation is not fulfilled: 

> When a promise from an adapter is rejected with a DS.InvalidError the record will transition to the invalid state and **the errors will be set to the errors property on the record**

#### Steps to reproduce

1. Have the `RESTAdapter`'s or `JSONAPIAdapter`'s `updateRecord` method return a rejected promise containing a `DS.InvalidError` instantiated with an array of POJOs, like in the code-sample-from-documentation above.

2. Initiate a `.save()` on a record that would trigger the described behavior.

#### Expected behavior

1. The record enters invalid state: `isValid: false`.
2. The `errors` object on the record is populated with POJOs passed into the `DS.InvalidError`.

#### Actual behavior

1. The record enters invalid state: `isValid: false`.
2. The `errors` object on the record remains empty.

## Demo

https://ember-twiddle.com/f81baf350179cb0faf62877a3c93aeca?openFiles=templates.application.hbs%2C

### Versions

Here's what our app is using:

```cli
`-- ember-source@3.10.0
`-- ember-cli@3.10.1
`-- ember-data@3.10.0
```

The Twiddle demo is using Ember 3.4.3 and Ember Data 3.11.0-beta.1.

**Comment by lolmaus** [comment]
@lifeart has helped me to resolve this issue:

The `JSONAPIAdapter` expects the error payload to be in this format:

```js
      return RSVP.reject(new DS.InvalidError([
        {
          detail: 'This name is reserved',
          source: {pointer: '/data/attributes/name'},
        },
      ]));
```

I. e. it's a matter of which keys to use. Internally, `source.pointer` is mapped back to `attribute` and `detail` to `message`.

Demo: https://ember-twiddle.com/c9cc1b4226f7c58171ee0cdbf5796bd9?openFiles=templates.application.hbs%2C

I'll keep this open issue, since better documentation is obviously needed.

**Comment by lolmaus** [comment]
OK, this is documented in `JSONAPIAdapter::extractErrors`: https://api.emberjs.com/ember-data/3.10/classes/DS.JSONAPISerializer/methods/extractErrors?anchor=extractErrors

Thx again to @lifeart for pointing this out.

Quite an obscure place to find it, since I wasn't trying to hack the error format and was merely trying to use `DS.InvalidError` with `DS.JSONAPIAdapter`. 

We could probably add more info to `DS.InvalidError` documentation. Especially so since `JSONAPIAdapter` is the default, yet `DS.InvalidError` only documents `RESTAdapter`.

**Comment by runspired** [comment]
The documentation for `DS.InvalidError` you linked and the example you copied from it explicitly shows the `JSON:API` format with `source` and `pointer` and explicitly calls this out. This isn't undocumented, even for the `RESTAdapter` case.

**Comment by lolmaus** [comment]
Yeah, that's why I had closed the issue.

Looks like I've been looking at wrong documentation.

**Comment by runspired** [comment]
@lolmaus the point I am making is that you were looking at the correct documentation but failing to notice what it was telling you. The documentation wasn't lacking.

>  this started as a bug report but turned out to be a misuse caused by lack of documentation.
...
> Have the RESTAdapter's or JSONAPIAdapter's updateRecord method return a rejected promise containing a DS.InvalidError instantiated with an array of POJOs, like in the code-sample-from-documentation above.

From the docs for `InvalidError`

> For Ember Data to correctly map errors to their corresponding properties on the model, Ember Data expects each error to be a valid JSON-API error object with a source/pointer that matches the property name. For example, if you had a Post model that looked like this.

And the example (which you also linked) from those docs: notice it uses `detail`, `source` and `pointer`

```js
new DS.InvalidError([
        {
          detail: 'Must be unique',
          source: { pointer: '/data/attributes/title' }
        },
      ])
```

**Comment by lolmaus** [comment]
@runspired I've been looking at some other documentation fragment that was suggesting `attribute` and `message`. I did not take those keys out of my head, and, in fact, that's what is still used in templates.

**Comment by runspired** [comment]
This is true, the UI format is different from the over-the-wire data format so I could see how that could be confusing if you assumed it was 1:1

https://api.emberjs.com/ember-data/release/classes/DS.Errors.

**Comment by lolmaus** [comment]
@runspired What confused me is that:

* The JSONAPI spec stated that all keys on error objects are optional ("MAY include any of the following keys").
* I didn't realize that ONLY properly formatted errors make it into `errors`. I didn't expect other errors to be dropped without notice.

How am I supposed to inspect errors that aren't specific to a certain attribute?!

**Comment by runspired** [comment]
Errors not related to the resource's attributes/relationships will still be returned on the error object thrown from the rejection.

**Comment by lolmaus** [comment]
Yeah but you have to handle them imperatively in the controller and reassign back to the model. 😑

**Comment by runspired** [comment]
Well you could do it that way, yes, but those errors aren't resource-level errors but request-level or document-level errors. Assigning them onto the record wouldn't make sense.
