### ISSUE TITLE
Problem with native getters recomputing after changes to attribute

### ISSUE THREAD

**Issue by barelyknown** [emberjs/data#6224]
I created an attribute on an Ember Data model, and a getter that referenced it.

```js
import DS from 'ember-data';
const { Model, attr } = DS;

export default class User extends Model {
  @attr('string') bar;

  get isBarBaz() {
    return this.bar === "baz";
  }
}
```

However, when `isBarBaz` is referenced, it only changes the first time that the attribute is changed.

In this example, "is it baz?" changes from `false` to `true`, but then stays `true`.

```hbs
<button {{on "click" (fn (mut this.foo.bar) (concat this.foo.bar "baz"))}}>
  Add "baz"
</button>

<div>
  "is it baz?" should show "false" at first, then "true", then "false" for all future presses.  
</div>

<div>
  is it baz? {{this.foo.isBarBaz}}
</div>
```

While figuring this out, I noticed two things that might help with debugging:

1. If `this.foo.bar` is referenced in the template in another place, it never changes from `false` to `true`.
2. If you decorate `isBarBaz` with `@computed('bar')` it behaves as expected.

______

[This repo](https://github.com/barelyknown/ember-data-issue-6224) is a minimal reproduction of the bug.

**Comment by runspired** [comment]
This sounds like a bug with tracked properties (`attr` is a computed property and should be tracked). cc @pzuraq

**Comment by runspired** [comment]
we believe this has been fixed, please open a new issue in emberjs/ember.js if you're still experiencing the issue
