### ISSUE TITLE
Query arity check fails, leading to recordArray/options being dropped

### ISSUE THREAD

**Issue by loganrosen** [emberjs/data#6232]
### Reproduction

@runspired is aware of the specific issue here and said that reproduction steps are unnecessary for this issue.

### Description

In the underlying `_query()` function used when calling `store.query()`, [it makes an arity check](https://github.com/emberjs/data/blob/master/packages/store/addon/-private/system/store/finders.js#L401) for the number of arguments of `query()` in the adapter to see if it should pass along `recordArray` and `options` as fourth and fifth parameters. However, this length check does not work unless native classes are used. In a local test case, even when the adapter has `query(store, type, query, recordArray, options)`, this check sees it as a `superWrapper` with a length of 0. This causes it to only pass along the `store`, `type`, and `query` arguments, and it doesn't create/pass a record array, nor does it pass options.

According to @runspired, this appears to have been broken since 3.2.

### Versions

```cli
@linkedin/ember-pem@0.0.0 /Users/lrosen/ember-pem_trunk
└── ember-source@3.10.1 

@linkedin/ember-pem@0.0.0 /Users/lrosen/ember-pem_trunk
└── ember-cli@3.10.1 

@linkedin/ember-pem@0.0.0 /Users/lrosen/ember-pem_trunk
└── ember-data@3.10.0 
```

**Comment by runspired** [comment]
The resolution here is to drop the arity check entirely as there is no longer a way to do this when things extend from `EmberObject`.

**Comment by runspired** [comment]
@malatin3 This is the answer for your question in #6248, if you have a cycle to spare to implement the fix proposed here please do :)

**Comment by loganrosen** [comment]
@runspired @malatin3 I took a stab at this in #6248.
