### ISSUE TITLE
Fix CI issues on Windows

### ISSUE THREAD

**Issue by rwjblue** [emberjs/data#6235]
Currently, our Azure Pipelines config runs `yarn workspace ember-data test:optional-features` which internally does `EMBER_DATA_FEATURE_OVERRIDE=ENABLE_ALL_OPTIONAL ember test`. Specifying environment variables on the command line prior to a command like that does not work properly on Windows, and therefore CI is failing when ran against Windows.

From the CI logs:

```
$ yarn workspace ember-data test:optional-features
$ EMBER_DATA_FEATURE_OVERRIDE=ENABLE_ALL_OPTIONAL ember test
'EMBER_DATA_FEATURE_OVERRIDE' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
```

Some build links for review:

* https://dev.azure.com/ember-data/emberjs/_build/results?buildId=629&view=logs
* https://dev.azure.com/ember-data/emberjs/_build/results?buildId=624&view=logs&jobId=657c9d73-2672-59f2-b256-fdad23962c37

**Comment by efx** [comment]
Trying a few things here: https://github.com/emberjs/data/pull/6236.
I think we'd need a node shim to mutate the environment variable for whatever environment or a combination of configuring the pipeline alongside tweaks to the package.json test command.

**Comment by lifeart** [comment]
May https://github.com/kentcdodds/cross-env help?

**Comment by rwjblue** [comment]
Ya, seems like a good spot for that

**Comment by rwjblue** [comment]
Fixed by https://github.com/emberjs/data/pull/6236 (though we can still iterate and use cross-env)
