### ISSUE TITLE
adapterOptions not available for 'query'

### ISSUE THREAD

**Issue by malatin3** [emberjs/data#6248]
I was experiencing a behavior where passing adapterOptions to 'query' did not make adapterOptions available in the adapter.

I tested queryRecord and it seemed to be working fine so after some digging I tracked the problem down to this line. Is there some reason the options aren't being passed through here?

https://github.com/emberjs/data/blob/8088cf43eb1cc1f0c96890f5dbadd90f672bf7d8/addon/-private/system/store/finders.js#L421

**Comment by runspired** [comment]
This is a duplicate of #6232
