### ISSUE TITLE
CI Failing for Canary Ember

### ISSUE THREAD

**Issue by rwjblue** [emberjs/data#6253]
CI is currently failing against Canary versions of ember-source (indicating “test is not isolated”).

I haven’t done much digging but I suspect the change that is causing the issue is Ember’s new auto-tracking (the feature was enabled just a couple days ago). 

Making this as a placeholder for working through the issues (though it may need fixes in Ember and/or ember-qunit).

**Comment by rwjblue** [comment]
I believe that https://github.com/emberjs/ember-qunit/pull/478 is related (and that @pzuraq worked on it because of these failures in ED’s test suite while he was working on the feature).

**Comment by runspired** [comment]
There seem to be new canary features unrelated to why this was originally opened: roughly the issue is that some properties for observers are now computeds that we can't access during the destroy lifecycle

**Comment by runspired** [comment]
cc @pzuraq

**Comment by rwjblue** [comment]
We need to update to https://github.com/emberjs/ember-qunit/releases/tag/v4.5.1 to get the fixes for waiting.

**Comment by HeroicEric** [comment]
Here is the related issue mentioned above related to observers https://github.com/emberjs/ember.js/issues/18225
