### ISSUE TITLE
Move unnecessary dependencies to devDependencies

### ISSUE THREAD

**Issue by andreyfel** [emberjs/data#6255]
I've updated to Ember Data 3.11 and noticed a bunch of new dependencies in the lock file.
Some of them look like they shouldn't be there.
For example `@ember-data/-build-infra` has `mocha` and `chai` (through `ember-cli-blueprint-test-helpers`).
Can they be moved to devDependencies?

**Comment by runspired** [comment]
I don't believe so in the current state as `-build-infra` is providing them as dependencies for the other packages. We could potentially separate `-build-infra` into two packages: one for dev-time things and the other for shared infra that each package needs to ship with.

**Comment by rwjblue** [comment]
Ya, you are correct. Would you mind sending a PR to fix?

**Comment by snewcomer** [comment]
Anyway I can help here?  What shared infra is needed to ship with each package?

**Comment by runspired** [comment]
Resolved by #6291 

@snewcomer if you're interested in helping here's a good quick hitter: https://github.com/emberjs/data/issues/6267

**Comment by andreyfel** [comment]
Thanks guys for that fix! Do you plan to make another patch release of 3.11 with this change in place?
