### ISSUE TITLE
Release Improvements

### ISSUE THREAD

**Issue by runspired** [emberjs/data#6267]
Two quick things to improve the release process:

- remove prod builds for all but the `-ember-data` package
- ignore empty folders in `packages/` directory (switching git branches often leaves behind empty folders for new packages that may not be involved in the release)

**Comment by snewcomer** [comment]
> remove prod builds for all but the -ember-data package

Does this mean finding any `ember build --environment=production` npm scripts?  If so, I think `-ember-data` is the only one in `packages` with this!

**Comment by runspired** [comment]
@snewcomer almost all the packages have this as a prePublishOnly step, only `-ember-data` should.
