### ISSUE TITLE
Attempting to register an unknown factory: 'transform:boolean'

### ISSUE THREAD

**Issue by kellyselden** [emberjs/data#6297]
I think there may be an issue with the latest beta. I got this last night https://travis-ci.org/kellyselden/ember-test-setup/jobs/566246164#L513.

`Attempting to register an unknown factory: 'transform:boolean'`

**Comment by runspired** [comment]
Thanks for pointing this out!

The published beta appears to differ from the tagged beta. I'm doing a new beta release this evening and if the problem persists I'll dig in deeper to figure out what's up.

**Comment by acras** [comment]
We are getting the very same error here, we are not in Beta, but in 3.11.
