### ISSUE TITLE
Fix external partner tests in CI

### ISSUE THREAD

**Issue by HeroicEric** [emberjs/data#6307]
External partner tests that are part of the CI build are currently broken. Let's fix them :)

### Remove `--disable-gpu` flag from testem config

Some of the failures can be fixed by removing the `--disable-gpu` flag from their testem configuration. See https://github.com/ember-cli/ember-cli/pull/8774 for more details.

PRs opened with the external partners:

- [x] https://github.com/travis-ci/travis-web/pull/2106
- [x] https://github.com/emberobserver/client/pull/167
- [x] https://github.com/embermap/ember-data-storefront/pull/148
- [x] https://github.com/ef4/ember-resource-metadata/pull/16
- [x] https://github.com/ef4/ember-data-relationship-tracker/pull/11
- [x] https://github.com/lytics/ember-data-model-fragments/pull/335
- [x] https://github.com/danielspaniel/ember-data-change-tracker/pull/63
- [x] https://github.com/hjdivad/ember-m3/pull/339

### Master requires Ember => 3.10

https://github.com/emberjs/data/pull/6249 refactored `Store` to a class. As part of this refactoring, `Store#defaultAdapter` was implemented using the `@computed` decorator. Using the `@computed` decorator requires Ember 3.10+.

Since many of the external parters are on an older version of Ember, their test suite is currently timing out. This would also require any users of ember-data to use Ember 3.10+ or install [`ember-decorators-polyfill`](https://github.com/pzuraq/ember-decorators-polyfill).

The commit that refactored `Store` to a class was reverted for the latest release but that seems pretty entangled with the ongoing for Identifiers. I'm not sure if that was just a temporary solution or if the goal is to make the same changes in master.

What is the desired path forward here?

- Add `ember-decorators-polyfill` dependency to `@ember-data/store`?
- Add instructions to install `ember-decorators-polyfill` if you're using < Ember 3.10?
- Refactor `Store` away from using the `@computed` decorator?

**Comment by igorT** [comment]
Many ❤️

**Comment by HeroicEric** [comment]
@igorT I added another section with a question regarding Ember version support

**Comment by rwjblue** [comment]
> install ember-decorators-polyfill

We should either do this, or manually add the computed to the prototype.

**Comment by HeroicEric** [comment]
@rwjblue I just opened a PR for that :) https://github.com/emberjs/data/pull/6321

**Comment by HeroicEric** [comment]
second issue WRT decorators was fixed by https://github.com/emberjs/data/pull/6331
