### ISSUE TITLE
204 No Content on POST Request

### ISSUE THREAD

**Issue by romeoonisim** [emberjs/data#6314]
Based on the JSONAPI documentation: https://jsonapi.org/format/#crud-creating-responses-204

Ember does not handle correctly the 204 No Content response when making a POST Request. It throws the following error:

`Error: Assertion Failed: Your recommendation record was saved to the server, but the response does not have an id and no id has been set client side. Records must have ids. Please update the server response to provide an id in the response or generate the id on the client side either before saving the record or while normalizing the response.`

It expects to receive an ID for that newly created record. 
To fix this I've manually added a unique ID to that record.

**Comment by runspired** [comment]
> If a POST request did include a Client-Generated ID and the requested resource has been created successfully, the server MUST return either a 201 Created status code and response document (as described above) or a 204 No Content status code with no response document.

The spec specifically states that to use `204` you must also use a `Client-Generated ID`. The alternative is for your 204 to include an assigned ID as a header and to normalize that into JSON:API form.

**Comment by pirvudoru** [comment]
@runspired What I make of the spec is that

> If a POST request **did** include a Client-Generated ID then ...
(notice the "did")

In this case we don't include any Client-Generated ID and we expect that we can handle a 204.

Is the spec interpretation above incorrect?
