### ISSUE TITLE
JSONAPI adapter has Content-Type header by default

### ISSUE THREAD

**Issue by snewcomer** [emberjs/data#6324]
`GET` requests will include `Content-Type` by [default](https://github.com/emberjs/data/blob/67e849e2b8d4d12cdb4f4bcb8011360b3e5dcb13/packages/adapter/addon/json-api.js#L155).  Is this expected and should this only be added to `POST/PUT/PATCH` and/or `DELETE` with a req body.

Further clarification:
https://github.com/emberjs/data/issues/4226#issuecomment-216942585

Ref PR - https://github.com/emberjs/data/pull/6169

**Comment by runspired** [comment]
I believe this was handled by #6341
