### ISSUE TITLE
Remove use of setupStore/createStore from tests

### ISSUE THREAD

**Issue by runspired** [emberjs/data#6357]
This is just a tracking issue for

- [x] removing `createStore` usage
- [x] removing `setupStore` usage
- [x] eliminating any `initializer` logic that remains purely for supporting `createStore` and `setupStore`

cc @HeroicEric

**Comment by HeroicEric** [comment]
👋

**Comment by rwjblue** [comment]
The helper itself is now removed, I think the last thing remaining is determining what of the initializer logic can be killed off now.
