### ISSUE TITLE
Add Documentation for RecordData

### ISSUE THREAD

**Issue by runspired** [emberjs/data#6359]
We currently do not have documentation for this public feature.

**Comment by ChaiWithJai** [comment]
I think I can tackle this. We're looking to add information to this [page](https://api.emberjs.com/ember-data/release/classes/RecordDataDefault)?

**Comment by runspired** [comment]
We want to add an overview of the feature and how to use it here: https://api.emberjs.com/ember-data/release/modules/@ember-data%2Frecord-data

We would then add the `RecordData` interface (clearly marking it as v1, there is an unimplemented v2 that will arrive soon-ish) as well as document the DefaultRecordData.

**Comment by ChaiWithJai** [comment]
@runspired is my idea is to follow [this](https://api.emberjs.com/ember-data/release/modules/@ember-data%2Fmodel) API guide as a template.

And for my research, I'll read the [Record Data RFC](https://github.com/emberjs/rfcs/blob/master/text/0293-record-data.md) and grok the [code](https://github.com/emberjs/data/tree/master/packages/record-data).

**Comment by runspired** [comment]
I wrote docs for the store APIs associated with custom records and record-data implementations in #8114. RecordData itself still needs documented, I'm planning on adding documentation for it as I implement V2.

**Comment by runspired** [comment]
I added documentation when I implemented V2, improved documentation will be added when we ship the new Cache https://github.com/emberjs/rfcs/pull/854
