### ISSUE TITLE
Model ID property needs to be accessed with get() to be tracked in computed properties

### ISSUE THREAD

**Issue by CodingItWrong** [emberjs/data#6393]
### Reproduction

I've created a minimal repro demonstrating the issue: https://github.com/CodingItWrong/numeric-id-test

To observe the problem, run the app, then click "Create" repeatedly to create new records. They are intended to sort with the newest record first. But note that the newest record is always at the bottom of the list. Even when its ID is populated, it does not sort to the top of the list.

### Description

I have a computed property based on the Ember Data model's `id`.

**Expected behavior:** when I create a new model, the computed property is automatically updated when the model's `id` is populated by the `save()` operation.

**Actual behavior:** the computed property is not automatically updated if I am accessing the ID as `this.id`. It *is* automatically updated if I am accessing the ID as `this.get('id')`.

I have an Ember Data model, `Widget`. I want to sort it in descending order based on the ID. But since JSON:API IDs are strings, I make a computed `numericId` property:

```
import DS from 'ember-data';
const { Model, attr } = DS;
import { dependentKeyCompat } from '@ember/object/compat';

export default class WidgetModel extends Model {
  @attr() name;

  @dependentKeyCompat
  get numericId() {
    return Number(this.id);
  }
}
```

(At @rwjblue's instruction I added `@dependentKeyCompat` as this should be necessary.)

Then in the list component I create a `sortedWidgets` property using the `numericId`:

```
import Component from '@glimmer/component';

export default class WidgetListComponent extends Component {
  get sortedWidgets() {
    let { widgets } = this.args;

    return widgets.slice().sort((a, b) => b.numericId - a.numericId);
  }
}
```

Then simply output them:

```
{{#each this.sortedWidgets as |widget|}}
  <li>
    <div>ID: {{widget.id}}</div>
    <div>Numeric ID: {{widget.numericId}}</div>
    <div>Name: {{widget.name}}</div>
    <br/>
  </li>
{{/each}}
```

I insert new widgets using a simple form and `store.createRecord()` + `widget.save()`.

When Ember Data populates the widget's ID field, I expect its `numericId` to update right away, and therefore its sort order to update. Each new widget should be sorted to the top of the list.

Here's what I see instead: when the widget starts out with an empty ID, it sorts to the end of the list. Then, when Ember Data fills in its ID, its position in the list is _not_ updated—it stays at the end. But when the _next_ widget is added, _then_ it pops up to the top of the list correctly. In this way, the list is always correctly sorted except for the most-recently-inserted widget, which is incorrectly at the bottom.

Example of a sequence adding widgets:

<img width="227" alt="Screen Shot 2019-08-29 at 5 59 14 AM" src="https://user-images.githubusercontent.com/15832198/63930917-3b0e4300-ca22-11e9-852d-3641261279a7.png">

***

<img width="247" alt="Screen Shot 2019-08-29 at 5 59 20 AM" src="https://user-images.githubusercontent.com/15832198/63930920-3d709d00-ca22-11e9-8b9b-3f1f1f824c92.png">

***

<img width="242" alt="Screen Shot 2019-08-29 at 5 59 24 AM" src="https://user-images.githubusercontent.com/15832198/63930924-3fd2f700-ca22-11e9-9207-7034a812343b.png">

***

<img width="241" alt="Screen Shot 2019-08-29 at 5 59 29 AM" src="https://user-images.githubusercontent.com/15832198/63930927-42355100-ca22-11e9-9db4-ed9d051f2e06.png">

**However,** if I change `numericId` to access the `id` using `get()`:

```
  @dependentKeyCompat
  get numericId() {
    return Number(this.get('id'));
  }
```

Then the list sorts properly:

<img width="243" alt="Screen Shot 2019-08-29 at 6 10 13 AM" src="https://user-images.githubusercontent.com/15832198/63931658-b290a200-ca23-11e9-835b-a742229de326.png">

Is it correct that the `id` should be accessed with `get()` in this case? I had thought that Ember Data attributes are "automatically tracked" in some sense. If that is the case, does the `id` function differently?

### Versions

Run the following command and paste the output below: `npm ls ember-source && npm ls ember-cli && npm ls ember-data`.

```cli
$ npm ls ember-source
numeric-id-test@0.0.0 /Users/josh/apps/temp/numeric-id-test
└── ember-source@3.14.0-canary  invalid

~/apps/temp/numeric-id-test [master] $ npm ls ember-cli
numeric-id-test@0.0.0 /Users/josh/apps/temp/numeric-id-test
└── ember-cli@3.13.0-beta.1  invalid

~/apps/temp/numeric-id-test [master] $ npm ls ember-data
numeric-id-test@0.0.0 /Users/josh/apps/temp/numeric-id-test
└── ember-data@3.12.0
```

**Comment by runspired** [comment]
Resolved by #6829
