### ISSUE TITLE
Turn on all recommended ESLint Rules

### ISSUE THREAD

**Issue by Gaurav0** [emberjs/data#6405]
In PR #6373, turned off following newly recommended eslint rules:

- 'no-prototype-builtins': 'off',
- 'require-atomic-updates': 'off'

These should be fixed and turned back on.

**Comment by HERBOD7** [comment]
@Gaurav0 and @runspired I can do it.

**Comment by runspired** [comment]
@igorT I haven't tried turning it on but I like the rule a lot. If it's noisy this makes me worried we have quite a lot of race condition bugs :/

**Comment by igorT** [comment]
@runspired I think that would be true if the rule worked well ;) Check out
https://github.com/emberjs/data/pull/6605

**Comment by Gaurav0** [comment]
Recommend closing as per https://github.com/eslint/eslint/issues/11899#issuecomment-541714523
