### ISSUE TITLE
No application initializer named 'store' - Upgrading ember-cli from 2.x.x to 3.1.2

### ISSUE THREAD

**Issue by tfazekas** [emberjs/data#6427]
I've upgraded ember-cli from 2.x.x to 3.1.2, and after I upgraded all deprecated packages I found [this issue](https://github.com/Vestorly/torii/issues/261).
I'm definitely sure that my app is using the ember-data@3.1.2.
Is there something i miss during the upgrade?
Can you help me how I can get more meaningful error message?
How can i debug, what is the actual problem?

**Comment by runspired** [comment]
@tfazekas it means you have an initializer declaring that it needs to run either before or after "store", which does not exist anymore

**Comment by tfazekas** [comment]
@runspired Thanks for the quick response.

I don't have initializers which states that it should run before or after store. 
Do I have to generate an application initializer or application instance initializer for store?

As far as i checked ember-data/app/instance-initalizers/ember-data.js gets called.
So i guess the store is initialized.
I have a component initalizers which injects store globally to all components.
How should I replace this initializer if store no longer exists?
