### ISSUE TITLE
[FEAT CI] Fastboot and IE11 Integration Tests

### ISSUE THREAD

**Issue by runspired** [emberjs/data#6431]
We should test the following

*IE11*

- [x] run all tests with jQuery
- [x] run all tests without jQuery

*Fastboot*

- [x] run all tests with jQuery
- [x] run all tests without jQuery

**Comment by runspired** [comment]
https://github.com/emberjs/data/pull/6459 introduces an approach for having private packages that are fully functioning apps we can use to test with.

We should use this approach to build the above fastboot scenarios, we can use ember-try to switch between jquery and non-jquery test runs without a single test app.

For the IE11 tests we should just run our existing test suite in an IE11 box both with and without jQuery using ember-try

**Comment by Gaurav0** [comment]
Turning on jQuery during Fastboot doesn't make sense, jQuery doesn't run in node.

**Comment by runspired** [comment]
@Gaurav0 if you have it on we use najax, if you don't we use fetch
