### ISSUE TITLE
[SIDE QUEST] MinimumSerializerInterface Tests

### ISSUE THREAD

**Issue by runspired** [emberjs/data#6460]
# A Side-Quest for Project Trim!

Side Quests?!?! How fun!

## Mission

#6459 introduced test infrastructure for testing ember-data without the `@ember-data/serializer` package being present at all while #6451 introduced the MinimumSerializerInterface. In this repository we want to add integration tests covering three areas.

- requests
- mutation
- serialization

The following things should be tested:

**Requests**

- [x] `store.<findAll|findRecord|query|queryRecord>` call `serializer.normalizeResponse` with the store methodName as the `requestType` once the adapter resolves
- [x] accessing an async hasMany relationship without links results in `serializer.normalizeResponse` being called with the requestType `findMany`
- [x] accessing an async hasMany relationship with links results in `serializer.normalizeResponse` being called with the requestType `findHasMany`
- [x] accessing an async belongsTo relationship with links results in `serializer.normalizeResponse` being called with the requestType `findBelongsTo`
- [x] errors in JSON:API format "just work" with no `extractErrors` hook on the serializer

**Mutation**

- [x] normalizeResponse deleteRecord
- [x] serialize updateRecord
- [x] serializeIntoHash if present updateRecord
- [x] normalizeResponse updateRecord
- [x] serializeIntoHash if present createRecord
- [x] serialize createRecord
- [x] normalizeResponse createRecord

**Serialization/Normalization**

- [x] record.serialize
- [x] store.serialize
- [x] snapshot.serialize
- [x] store.normalize
- [x] store.pushPayload calls serializer.pushPayload

**Comment by runspired** [comment]
@Gaurav0 is going to work to complete this side-quest :)

**Comment by Gaurav0** [comment]
I've interpreted record.serialize as Model.serialize, but there doesn't seem to be a store.serialize?

**Comment by Gaurav0** [comment]
Side quest completed solo.

**Comment by runspired** [comment]
And much appreciation for it! Great work :D I'm very happy to have all the additional test coverage this introduced :)

P.S. I'll be speccing out the tests for Adapters this week
