### ISSUE TITLE
File size regression in v3.13.0

### ISSUE THREAD

**Issue by Turbo87** [emberjs/data#6495]
### Description

Expected: No significant asset size increase after updating ember-data to v3.13.x
Actual:
```
  - vendor.js: 2.83MB -> 2.85MB (+16.89KB / 0.6%)
```

> If a previous version of `ember-data` worked as `expected`, which was the most recent version that worked?

v3.12.3

### Versions

Run the following command and paste the output below: `npm ls ember-source && npm ls ember-cli && npm ls ember-data`.

```cli
└── ember-source@3.12.0
└── ember-cli@3.12.0
└── ember-data@3.13.0
```

/cc @runspired

**Comment by dcyriller** [comment]
I believe this size change relates to the addition of two canary features: Identifiers and RequestStateService.

**Comment by Turbo87** [comment]
you mean they were promoted from canary to the stable release? unfortunately the v3.13 release is not mentioned at all in https://github.com/emberjs/data/blob/master/CHANGELOG.md :-/

**Comment by dcyriller** [comment]
I mean they have been added as canary features. They are not activated yet but can be with a feature flag.

That said, I’m not right person to answer!

**Comment by runspired** [comment]
@turbo87 that looks like non prod / non compressed size? If so seems expected.

**Comment by runspired** [comment]
I'm going to close this as there is nothing actionable for us. There are a few reasons file size would have increased in 3.13 by ~16kb before compression/prod-build/minification including:

- Identifiers (infra from the feature is always in use even when the APIs are off via the feature flag)
- RecordData Errors, RecordData State, Custom Model Class infra (mostly stripped but would cause some small increases)
- Added Asserts and Deprecations (calls to assert/deprecate aren't always stripped iirc, just silenced, this is something I'll be looking into to ensure we do strip them in the future if not)
- Added Docs (If not a prod-build the comments would affect file size)
- Octane decorator support

**Comment by Turbo87** [comment]
> that looks like non prod / non compressed size? If so seems expected.

the numbers are pre-gzip post-minification from the prod build
