### ISSUE TITLE
Can't use 'trigger' as a table field name

### ISSUE THREAD

**Issue by maxwondercorn** [emberjs/data#6504]
Added a new table field named `trigger` to our database and it generates a type error when added to the model. The record is loaded but the error breaks rendering

```shell
Uncaught TypeError: trigger.apply is not a function
```
Digging into the source the error is generated in the private `internal-model.js` module, specifically:

```js
  _triggerDeferredTriggers() {
    if (!this.hasRecord) {
      return;
    }
    let triggers = this._deferredTriggers;
    let record = this._record;
    let trigger = record.trigger;
    for (let i = 0, l = triggers.length; i < l; i++) {
      trigger.apply(record, triggers[i]);
    }

    triggers.length = 0;
  }
```
`let trigger =` gets the field value and tries to execute it.  I noticed a guard was recently added for the loop in pr #6313. The guard works if the data field is empty but not otherwise.

The fix would also check if the trigger is a function

```js
  if (trigger && typeof trigger === 'function')
      for (let i = 0, l = triggers.length; i < l; i++) {
        trigger.apply(record, triggers[i]);
      }
```
If this looks like a reasonable fix I can open a PR.

**Comment by runspired** [comment]
please PR :)

**Comment by runspired** [comment]
(trigger is part of evented which we've now deprecated so this check seems very fine to add)
