### ISSUE TITLE
Support for sparse fieldsets in store.findAll()

### ISSUE THREAD

**Issue by esbanarango** [emberjs/data#6529]
Right now the only way to use [sparse fieldsets](https://jsonapi.org/format/#fetching-sparse-fieldsets) is by using `store.query(...)`. But the returned object of that promise is an `AdapterPopulatedRecordArray` which doesn't update with any addition or deletion.

In the other hand `store.findAll(...)` promise returns a "live" array that does update. But `store.findAll(...)` only supports `{ include }`. The current work around is to overwrite `urlForFindAll`.

Are there any plans to support more options (in this case `{fields}`) in `store.findAll(...)`?

Thank you.

**Comment by runspired** [comment]
you can pass any options you want in via `adapterOptions`, alternatively you can pair `query` with `peekAll`
