### ISSUE TITLE
optimising findAll with 100,000 models

### ISSUE THREAD

**Issue by BryanCrotaz** [emberjs/data#6576]
I'm using virtualised components to display a very very long (100,000+) list of models. To speed up first load I want to send the minimum data to the UI.

It seems to me that there should be a way for `findAll` to just be sent
```
data: [
  {id:1, type: "person"},
  etc
]
```

This would mark the records as `unloaded` in the store so that they are loaded on first access. This would be similar to the existing behaviour when a serialized relationship only contains ids.

Is this already possible but not clear from docs?

If not, would you accept a PR that would mark the records as not loaded if the attributes hash is missing?

**Comment by runspired** [comment]
why load all with less data vs loading fewer with all data?

**Comment by BryanCrotaz** [comment]
Because I want the UI to know how many records there are. 

It seems inconsistent that this methodology works for hasMany relationships but not for findAll

**Comment by runspired** [comment]
@BryanCrotaz you could use `meta` to return that info alongside pagination info from your API without needing to load the placeholders.

**Comment by BryanCrotaz** [comment]
i could do, but wouldn’t it be great if ember-data could be consistent with the way it already works for hasMany?

**Comment by runspired** [comment]
TBH, the way it works for `hasMany` is a bit insane. That said, what you describe is also **not** how `hasMany` works.

With `hasMany`, all records are requested immediately once the `hasMany` is accessed. They don't wait to fetch until their index in the array is accessed.

**Comment by BryanCrotaz** [comment]
Darn.

**Comment by runspired** [comment]
There are long term designs for making working with paginated collections very nice, which is what you seem to need.  Until then, I'd recommend using `query` to return the `ResourceIdentifierObjects` then wrapping the result in an ArrayProxy that forces reload on access if the record is empty. Example: https://ember-twiddle.com/1ad34bbd30b2e54667496b3a6c296267?openFiles=adapters.application.js%2C

**Comment by runspired** [comment]
@BryanCrotaz PS I pinged you on discord, been wanting to chat about work we have in-flight and how well it aligns to your usage of ember-data :) hit me back!

**Comment by runspired** [comment]
Going to close this as there isn't anything actionable for us. In this area we do intend to introduce paginated collections as a first-class primitive, but we have no intention on the proposed on-demand load mechanism mentioned here.

That said, it wouldn't be hard to build this. If you implemented a Proxy wrapping an Array, you could use the `identifierCache` to populate the array and on access of each index trigger a `findRecord` for that identifier. If using coalescing this would coalesce, or you could do custom coalescing in your adapter.
