### ISSUE TITLE
adapter.headers is given precedence over options.headers

### ISSUE THREAD

**Issue by runspired** [emberjs/data#6588]
https://github.com/emberjs/data/blob/master/packages/adapter/addon/rest.js#L1089

See this discourse thread for more info: https://discuss.emberjs.com/t/how-to-override-the-adapter-headers-that-get-sent-in-the-ajax-request/17106

**Comment by runspired** [comment]
After discussing, we've decided to resolve this by:

- [ ] Submitting a fix to LTS 3.12 to warn if headers conflict and are overridden
- [ ] Submitting a fix to 3.13+ that reverses this behavior to ensure the headers from options are given precedence.

**Comment by Gaurav0** [comment]
What should the warning say?
