### ISSUE TITLE
Can't install with npm 3.5.2

### ISSUE THREAD

**Issue by drewcovi** [emberjs/data#6589]
### Reproduction

1. Create folder
1. `npm install ember-data`
1. See output below

### Description

Running on `Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-65-generic x86_64)`

```cli

➜  testing npm install --save-dev ember-data
npm ERR! addLocal Could not install /home/drew/testing/@ember-data/-build-infra@3.13.1
npm ERR! Linux 4.15.0-65-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--save-dev" "ember-data"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! path /home/drew/testing/@ember-data/-build-infra@3.13.1
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/drew/testing/@ember-data/-build-infra@3.13.1'
npm ERR! enoent ENOENT: no such file or directory, open '/home/drew/testing/@ember-data/-build-infra@3.13.1'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/drew/testing/npm-debug.log

```
### Debug log
https://gist.github.com/drewcovi/e1aa549e8dafaee6e104e17c10f4e8e3

**Comment by drewcovi** [comment]
Resolving here should resolve issues in `ember-init` https://github.com/emberjs/ember.js/issues/18473#issuecomment-541423726

**Comment by rwjblue** [comment]
Thank you for helping dig into this @drewcovi!

**Comment by rwjblue** [comment]
Hmm, why does your system have `npm@3.5.2`? `node@8.10.0` comes with `npm@5.6.0` bundled by default :thinking:

**Comment by drewcovi** [comment]
Can't say, just fired up `apt install nodejs npm`

**Comment by runspired** [comment]
@rwjblue @drewcovi closing as a duplicate/wont-fix. The issue here is with folks using Verdaccio. https://github.com/verdaccio/verdaccio/issues/1429

**Comment by runspired** [comment]
(as an aside, if there is an issue with older `npm` we aren't aware of we also can't fix older npm)

**Comment by rwjblue** [comment]
Hmm, @runspired what points to the verdaccio issue in this report?

**Comment by runspired** [comment]
also related: https://github.com/emberjs/data/issues/6273

**Comment by rwjblue** [comment]
@drewcovi - Can double check if you are using [verdaccio](https://verdaccio.org/) in your environment?

**Comment by runspired** [comment]
Looking further at the log it does seem this is an issue with outdated `npm` similar to the issues `verdaccio` encountered but distinct:

```
360 silly resolveWithNewModule @ember-data/model@3.13.1 checking installable status
361 silly cache add args [ '@ember-data/model@3.13.1', null ]
362 verbose cache add spec @ember-data/model@3.13.1
363 silly cache add parsed spec Result {
363 silly cache add   raw: '@ember-data/model@3.13.1',
363 silly cache add   scope: '@ember-data',
363 silly cache add   name: '@ember-data/model',
363 silly cache add   rawSpec: '3.13.1',
363 silly cache add   spec: '3.13.1',
363 silly cache add   type: 'version' }
364 silly addNamed @ember-data/model@3.13.1
```

note the parsing above on `@ember-data/model`, then see how `@ember-data/-build-infra` is not parsed for `name` and `scope` correctly

```
113 silly fetchOtherPackageData @ember-data/-build-infra@3.13.1
114 silly cache add args [ '@ember-data/-build-infra@3.13.1', null ]
115 verbose cache add spec @ember-data/-build-infra@3.13.1
116 silly cache add parsed spec Result {
116 silly cache add   raw: '@ember-data/-build-infra@3.13.1',
116 silly cache add   scope: null,
116 silly cache add   name: null,
116 silly cache add   rawSpec: '@ember-data/-build-infra@3.13.1',
116 silly cache add   spec: '/home/drew/testing/@ember-data/-build-infra@3.13.1',
116 silly cache add   type: 'local' }
117 error addLocal Could not install /home/drew/testing/@ember-data/-build-infra@3.13.1
118 silly fetchPackageMetaData Error: ENOENT: no such file or directory, open '/home/drew/testing/@ember-data/-build-infra@3.13.1'
118 silly fetchPackageMetaData  error for @ember-data/-build-infra@3.13.1 { Error: ENOENT: no such file or directory, open '/home/drew/testing/@ember-data/-build-infra@3.13.1'
118 silly fetchPackageMetaData   errno: -2,
118 silly fetchPackageMetaData   code: 'ENOENT',
118 silly fetchPackageMetaData   syscall: 'open',
118 silly fetchPackageMetaData   path: '/home/drew/testing/@ember-data/-build-infra@3.13.1' }
```

**Comment by runspired** [comment]
Incidentally the folks at verdaccio had designed their system around npm's perceived limitation around dashes: https://github.com/verdaccio/verdaccio/issues/1400

https://github.com/verdaccio/verdaccio/pull/1409

**Comment by drewcovi** [comment]
@runspired @rwjblue definitely not using verdaccio at all... this was on a clean system. Considering that the package for Ubuntu LTS is still 3.5.2 is this still closed as a `wont fix`?

**Comment by drewcovi** [comment]
Or if I understand the issue, it has more to do with the actual name of the repository which would be the only fix here since `npm` holds the keys to this fix

**Comment by drewcovi** [comment]
If so, should there be a clear requirement for NPM version in the Ember docs?

**Comment by runspired** [comment]
> Or if I understand the issue, it has more to do with the actual name of the repository which would be the only fix here since npm holds the keys to this fix

Correct. The version of `npm` you have does not appear to support scoped packages with dashes starting the name following the scope

> If so, should there be a clear requirement for npm version in the Ember docs?

There is via node version requirement. It is unfortunate that some platforms provide a different version of npm than that bundled.
