### ISSUE TITLE
GET Request status 423

### ISSUE THREAD

**Issue by AndriesDemeulenaere** [emberjs/data#6590]
Hi, I have a rather odd problem with an uncommon server status response in combination with ED. I’ll try to be as specific as possible. (Currently on v3.7) 

At some point in the application I’m building, the GET request (JSON API) of a certain resource can resolve in a 423 response (Locked state). As specified in the documentation, I’ve added a check in application-adapter to handle te specific status. Basically, it should route to the error page with a specific message. The weird part is that it doesn’t route to the error page (never enters the error action in the application router), but if I change the response status check for example to `status === 200`, the first 200 response does work and the app is routed to the error page. So I was thinking there is something wrong with server response or how the error is handled, but can’t seem to figure out what/why. (I've read in some other issue topics that it could be due to the server response not have  `source: { pointer: "/data" }`, but no luck there after updating response)

Application Adapter
```javascript
import { LockedError } from './errors';
 … 
  handleResponse(status) {
    if (status === 423) {
      return new LockedError();
    }

    return this._super(...arguments);
  }
… 
```

errors.js file
```javascript
import { AdapterError } from 'ember-data/adapters/errors';

 export const LockedError = AdapterError.extend({ message: 'Request is locked.' }); 
```

routes/application.js file: 
```javascript
import { LockedError } from ‘myapp/adapters/errors';
 … 
actions: {
    error(error) {
      if (error instanceof LockedError) {
        this.intermediateTransitionTo('error', LockedErrorModel.create());
 …
```

Server Response: (which is with a 423 status code)
```javascript
{"errors":["Some error message."]} 
```

Versions
```cli
ember-source@3.7.3 
ember-cli@3.7.1 
ember-data@3.7.0 
```

**Comment by runspired** [comment]
@AndriesDemeulenaere I believe what's needed here is to throw the error.

```js
handleResponse(status) {
    if (status === 423) {
      throw new LockedError();
    }

    return this._super(...arguments);
  }
```

**Comment by AndriesDemeulenaere** [comment]
@runspired Thanks for your response. I gave that a try but with no luck, it's still not routing the error page.

**Comment by snewcomer** [comment]
@AndriesDemeulenaere A few thoughts.

1.  I had some troubles b/w 3.6-3.7.  I've heard others have had issues as well.  I'm curious if 3.8 LTS yields different results.  I'm not sure when the router service became public, but there may have been churn around that time.
2.  Is there a silent error?  What happens when you turn on the stop sign?
<img width="247" alt="Screen Shot 2019-10-27 at 1 07 27 PM" src="https://user-images.githubusercontent.com/7374640/67640914-bf623280-f8ba-11e9-89d2-857ad705abd5.png">
3.  What happens when you just pass one arg `this.intermediateTransitionTo('error');`?

**Comment by AndriesDemeulenaere** [comment]
@snewcomer Thanks for your response. To answer your questions:

When I turn on the stop sign, there is an error, it stops and throws the error in `rsvp.js`:
![image](https://user-images.githubusercontent.com/8791607/67676122-277b4c00-f981-11e9-9b0d-5bbb80e85ff1.png)

When I just pass one arg to the intermediateTransition, nothing happens, it'll just go on as before.

Another remark, the error is actually shown in the console log.

![image](https://user-images.githubusercontent.com/8791607/67676630-3a425080-f982-11e9-9a7d-de57b92ba9a0.png)

**Comment by runspired** [comment]
@AndriesDemeulenaere I think you need to throw the LockedError, not return it, but my off-hand knowledge of exactly how some of that code works isn't great. Mind creating a reproduction?

**Comment by runspired** [comment]
closing as likely user error (not throwing the error)
