### ISSUE TITLE
JSONAdapter: Collision with internal properties should throw warning

### ISSUE THREAD

**Issue by Redsandro** [emberjs/data#6611]
Ember data `JSONAdapter` lacks the ability to `PATCH` only dirty attributes. One way to work around this is to use the automatically inserted state attributes (i.e. `isNew`) in your serializer:

```javascript
export default ApplicationSerializer.extend({
  serializeAttribute(snapshot, json, key, attributes) {
    if (snapshot.record.get('isNew') || snapshot.changedAttributes()[key]) {
      this._super(...arguments)
    }
  }
})
```

However, when (accidentally) using such a key in your model, no warning is given that an internally set key is overwritten, causing problems with state-related functionality.

```javascript
import DS from 'ember-data'
import { computed } from '@ember/object'

export default DS.Model.extend({
  // ... abridged
  labels: DS.attr(),

  isNew: computed('labels.[]', function() {
    return this.get('labels').includes('new')
  })
})
```

It took me some time to figure out that [my own code was to blame](https://github.com/ember-infinity/ember-infinity/issues/393#issuecomment-544566093), indicating of course that, contrary to what my mother used to say, I'm not the smartest person in the world. I had completely forgotten this computed property and the model was not in my frame of reference when hunting for the problem.

Humans are prone to this kind of mistakes. I suggest that either the internally set parameters are prepended with an underscore to signify their status, or **show a warning when internally set parameters are overwritten in the model**.

### Versions

```cli
─ ember-source@3.12.0 

ember-infinity@1.4.9 /tmp/ember-infinity
└── ember-cli@3.12.0 

ember-infinity@1.4.9 /tmp/ember-infinity
└── ember-data@3.12.4 
```

**Comment by Redsandro** [comment]
By any chance, would there be a different path from which I can `get()` the state params that are not directly on the model?

**Comment by snewcomer** [comment]
https://github.com/emberjs/data/blob/9a67f6a422ec965ed80ba7a349f966e460d10f6f/packages/record-data/addon/-private/record-data.ts#L298

@Redsandro 👋 Glad you found the issue. Which one "won" - the ember-data property or your property? 

Also, luckily, this is tracked privately with `_isNew` already!  I believe the public property `isNew` is meant to be overridden if you so desire.

https://github.com/emberjs/data/blob/681d922fe6736df0acab33f3eecfceba91cb8e65/packages/store/addon/-private/ts-interfaces/record-data.ts#L58

**Comment by Redsandro** [comment]
> this is tracked privately with `_isNew` already!

https://github.com/emberjs/data/blob/9a67f6a422ec965ed80ba7a349f966e460d10f6f/packages/record-data/addon/-private/record-data.ts#L298-L300

I can't believe I haven't found that! I should have used that. Seems like a 1 char serializer fix. I never really check out the underscored parameters when inspecting (anymore) because those change sometimes without notice. But in this case it would have been a quick fix.

> Which one "won" - the ember-data property or your property?

The Ember Data property won :sweat_smile: I changed all refs in my app.

**Comment by Redsandro** [comment]
Not sure if I should close this because I understand what happened, or keep this open because everyone can step into the same trap, especially since `record.get('isNew')` is documented here and there on the Ember forum and Ember Igniter guides.

**Comment by sly7-7** [comment]
In the past there has been more or less the same complaint about other properties, so some tests were added: https://github.com/emberjs/data/blob/master/packages/-ember-data/tests/unit/model-test.js#L703. Here it seems like a different case here, but I don't know if properties like isNew (which are defined as readOnly (https://github.com/emberjs/data/blob/9a67f6a422ec965ed80ba7a349f966e460d10f6f/packages/model/addon/-private/model.js#L89) are meant to be overwritten. 
Also maybe when RecordData features are on, this problem will disappear by itself.
cc @runspired

**Comment by Redsandro** [comment]
### References

- [0000-record-data.md](https://github.com/igorT/rfcs/blob/6e284f9dc5dc26d0aed4bc639bf3f41ac6cad879/text/0000-record-data.md)
- https://github.com/emberjs/data/issues/5618

**Comment by sly7-7** [comment]
Maybe we also could add some checks, like https://github.com/emberjs/data/blob/master/packages/model/addon/-private/model.js#L1399

**Comment by runspired** [comment]
A few things:

1) This property is decently safe to override as the snapshot should expose this without you needing to access it from the record.

2) Serializing non-attrs and only changed attrs and using PATCH are all relatively easy to accomplish. I'd suggested reading the adapter docs more (or reading the adapter package + MinimumAdapterInterface docs when those land in 3.16)

For non-attrs, snapshot does give you access to the record it is a snapshot for, so you can serialize any non-attributes that way via direct access.

For changed attrs snapshot gives you `changedAttributes()` which returns a dictionary of attributes that have changed along with their old and new values.

`snapshot.isNew()` returns whether the snapshot is in the new state.
