### ISSUE TITLE
[Feature Request] Common Adapter for Models in a Folder

### ISSUE THREAD

**Issue by jeffsawatzky** [emberjs/data#6614]
I have an app that works with a bunch of different backend api's, and each one slightly different which means different adapters for each. I have structured my ember-data models in folders like "api-1/resource-a", "api-1/resource-b", "api-2/resource-a", "api-2/resource-b" etc.

I was hoping that I could create an adapter for "api-1" and one for "api-2" and have all the models in the subfolders use the correct one. But it seems like ember data only looks for an adapter for the specific model name, or uses the global application adapter.

Am I missing something, or do I really need to create individual adapters for each resource (even if each one just inherits from a common one for that api)?

**Comment by runspired** [comment]
You can use your application adapter and application serializers as delegators and use a heuristic (model name prefix) or an explicit map to switch based on the primary resource type involved.

A quick example:

```ts
function adapterForType(type) {
  if (type.startsWith('api-v1')) {
    return 'api-v1';
  }
}

class ApplicationDelegatorAdapter extends EmberObject {
   findRecord(store, { modelName }) {
     return store.adapterFor(adapterForType(modelName)).findRecord(...arguments);
   }
}
```
