### ISSUE TITLE
Errors in store.createRecord are Uncaught

### ISSUE THREAD

**Issue by NateDawg90** [emberjs/data#6622]
My application has the following code for creating Users in the Ember store:
```    
      let newUser = this.store.createRecord('user', user)
      // never reaches here
      return newUser.save()
        .then(res => {
          this.set('modalName', null);
          this.transitionToRoute('users.index');
          this.get('notify').success(`User ${res.name} created.`);
        })
        .catch((resp) => {
          console.log(resp)
        });
```
store.createRecord is not catching errors apparently. When I get an error from createRecord (BEFORE the request is made to the server), Ember breaks and gives and Uncaught Error Exception. An example of one of these errors is when I try to create a record with an id that is already existing in the users model.

How can I catch these errors and stop my app from breaking when createRecord returns an error?

Run the following command and paste the output below: `npm ls ember-source && npm ls ember-cli && npm ls ember-data`.

```cli
flexdirect@0.0.0 /Users/nate/Projects/BFCore/frontend
└── ember-source@3.4.0 

flexdirect@0.0.0 /Users/nate/Projects/BFCore/frontend
└── ember-cli@3.4.4 



   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │       New minor version of npm available! 6.9.0 → 6.12.0       │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.12.0   │
   │               Run npm install -g npm to update!                │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯

flexdirect@0.0.0 /Users/nate/Projects/BFCore/frontend
└── ember-data@3.4.4 
```

**Comment by runspired** [comment]
Hi @NateDawg90, for support requests we recommend StackOverflow or Discord. Likely whatever you are passing in as `user` is invalid.
