### ISSUE TITLE
Make sure serializer missing extractErrors method code path is tested

### ISSUE THREAD

**Issue by igorT** [emberjs/data#6689]
Seems like at least in the release version, the else branch of this code block wasn't tested
```
      if (error instanceof InvalidError) {
        let parsedErrors;

        if (typeof serializer.extractErrors === 'function') {
          parsedErrors = serializer.extractErrors(store, modelClass, error, snapshot.id);
        } else {
          parsedErrors = errorsArrayToHash(error.errors);
        }
```

**Comment by runspired** [comment]
This test lives here: https://github.com/emberjs/data/blob/master/packages/unpublished-serializer-encapsulation-test-app/tests/integration/errors-test.js I suspect it is newer than current release.
