### ISSUE TITLE
ED Fastboot mode requires node crypto package but doesn't really tell users

### ISSUE THREAD

**Issue by igorT** [emberjs/data#6690]
We need to have a good error message and maybe is there a blueprint where we can add the fastboot dependency? cc @rwjblue

**Comment by runspired** [comment]
The error message portion is above. There is not currently a blueprint used when installing fastboot but if there ever is one we should have it detect the presence of `ember-data` and add `crypto` to fastbootDependencies if present. `crypto` is a native module so it does not need installed, only specified.

**Comment by runspired** [comment]
Closing as there is now tracking for a blueprint in the fastboot repo.

**Comment by IgnaceMaes** [comment]
I just ran into this issue again. For anyone looking to copy paste the solution, add the following in your `package.json`:

```js
{
  // dependencies, devDependencies, ...
  "fastbootDependencies": [
    "crypto"
  ],
}
```

**Comment by runspired** [comment]
fastboot should also give you a much clearer error message now since the latest release contained the change to improve the error message around this

**Comment by satyam73** [comment]
> I just ran into this issue again. For anyone looking to copy paste the solution, add the following in your `package.json`:
> 
> ```js
> {
>   // dependencies, devDependencies, ...
>   "fastbootDependencies": [
>     "crypto"
>   ],
> }
> ```

Thanks @IgnaceMaes , it worked!
