### ISSUE TITLE
Imported CUSTOM_MODEL_CLASS from @ember-data/canary-features which is not a supported flag.

### ISSUE THREAD

**Issue by kellyselden** [emberjs/data#6697]
I just tried updating to 3.14.

https://github.com/ember-vr/ember-vr-shopping/pull/196

https://app.netlify.com/sites/ember-vr-shopping/deploys/5dc3e8d62f689d000cffc6ec

```
9:51:46 AM: Build Error (broccoli-persistent-filter:Babel > [Babel: @ember-data/store]) in -private/system/ds-model-store.ts
9:51:46 AM: /opt/build/repo/-private/system/ds-model-store.ts: Imported CUSTOM_MODEL_CLASS from @ember-data/canary-features which is not a supported flag.
```

It's interesting that Travis passed which is running `ember t`, but netlify failed which is running `ember b -prod`

**Comment by runspired** [comment]
cc @rwjblue. We don't throw this error so unsure what's up.

**Comment by runspired** [comment]
FWIW I am not able to replicate this by:

- `ember new data-bug`
- `cd data-bug`
- `yarn`
- `yarn add ember-data@latest`
- `ember b -e production`

**Comment by kellyselden** [comment]
It's possible that npm installed it incorrectly, because using yarn instead made it work.

**Comment by ballPointPenguin** [comment]
I just saw the same after installing ember-data to an exisiting octane app usuing `ember install ember-data`.

**Comment by ballPointPenguin** [comment]
I think it's a TypeScript caching issue that goes away if you rebuild node_modules.
Likely related: https://github.com/emberjs/data/issues/6567#issuecomment-552080045

**Comment by runspired** [comment]
Left this on the other issue as well but wanted to reiterate here:

**We don't know why it is occurring, but if someone saves off the `node_modules` and lock files from when it does we could figure it out.**

It is more than likely a bug with `npm` specifically as using yarn never seems to encounter it.

From what I've been able to gather so far it seems like npm is updating the lock file but not installing the new package.

**Comment by jathanasiou** [comment]
I've been able to replicate this consistently this week every single time I upgrade from to `3.13.1`. This is on an Ember Octane project. Below is my `package.json` and my [package-lock is here](https://gist.github.com/jathanasiou/dbe90ac09c7e2bcd2e70f32d06596eef).

```json
{
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "lint:hbs": "ember-template-lint .",
    "lint:js": "eslint .",
    "start": "cross-env-shell NODE_ENV=development ember serve --environment=$NODE_ENV",
    "test": "ember test",
    "publish": "cross-env-shell NODE_ENV=production ember build --environment=$NODE_ENV",
    "postpublish": "yarn bestzip dist.zip .ebextensions dist/"
  },
  "devDependencies": {
    "@ember/edition-utils": "^1.1.1",
    "@ember/optional-features": "^1.1.0",
    "@fortawesome/ember-fontawesome": "^0.2.1",
    "@fortawesome/free-solid-svg-icons": "^5.11.2",
    "@glimmer/component": "^0.14.0-alpha.12",
    "babel-eslint": "^10.0.3",
    "bestzip": "^2.1.5",
    "bootstrap": "^4.3.1",
    "broccoli-asset-rev": "^3.0.0",
    "cross-env": "^6.0.3",
    "ember-auto-import": "^1.5.3",
    "ember-bootstrap": "^3.1.0",
    "ember-bootstrap-changeset-validations": "^2.0.0",
    "ember-changeset": "^2.2.4",
    "ember-changeset-validations": "^2.2.1",
    "ember-cli": "3.14.0-beta.2",
    "ember-cli-app-version": "^3.2.0",
    "ember-cli-babel": "^7.12.0",
    "ember-cli-dependency-checker": "^3.2.0",
    "ember-cli-htmlbars": "^4.0.8",
    "ember-cli-inject-live-reload": "^2.0.2",
    "ember-cli-sass": "^10.0.1",
    "ember-cli-sri": "^2.1.1",
    "ember-cli-template-lint": "^1.0.0-beta.3",
    "ember-cli-uglify": "^3.0.0",
    "ember-data": "~3.14.0",
    "ember-export-application-global": "^2.0.1",
    "ember-fetch": "^6.7.2",
    "ember-load-initializers": "^2.1.1",
    "ember-maybe-import-regenerator": "^0.1.6",
    "ember-qunit": "^4.6.0",
    "ember-resolver": "^5.3.0",
    "ember-source": "https://s3.amazonaws.com/builds.emberjs.com/beta/shas/145ab13849706ed2d2d4225e5dbed37e5bc178bd.tgz",
    "ember-template-lint": "^1.8.1",
    "ember-truth-helpers": "^2.1.0",
    "eslint": "^6.6.0",
    "eslint-plugin-ember": "^7.5.0",
    "eslint-plugin-node": "^10.0.0",
    "loader.js": "^4.7.0",
    "lodash": "^4.17.15",
    "qunit-dom": "^0.9.2",
    "sass": "^1.23.3"
  },
  "engines": {
    "node": "8.* || >= 10.*"
  },
  "dependencies": {
    "query-string": "^6.9.0"
  }
}
```

@runspired my node_modules seems to have the correct version:
![Untitled](https://user-images.githubusercontent.com/8679925/68951364-c8596c00-07b5-11ea-86d7-e4b155655b37.png)

**Comment by jherdman** [comment]
I ran into this issue using yarn. With the help of ruspired on the Ember Discord we found:

```
$ yarn list --pattern ember-data
├─ @ember-data/-build-infra@3.12.0
├─ @ember-data/adapter@3.12.0
├─ @ember-data/canary-features@3.12.0
├─ @ember-data/model@3.12.0
├─ @ember-data/rfc395-data@0.0.4
├─ @ember-data/serializer@3.12.0
├─ @ember-data/store@3.12.0
├─ ember-data-array-transform@2.0.3
│  ├─ @ember-data/-build-infra@3.13.1
│  ├─ @ember-data/adapter@3.13.1
│  ├─ @ember-data/canary-features@3.13.1
│  ├─ @ember-data/model@3.13.1
│  ├─ @ember-data/serializer@3.13.1
│  ├─ @ember-data/store@3.13.1
│  └─ ember-data@3.13.1
├─ ember-data-json-transform@2.0.3
│  ├─ @ember-data/-build-infra@3.13.1
│  ├─ @ember-data/adapter@3.13.1
│  ├─ @ember-data/canary-features@3.13.1
│  ├─ @ember-data/model@3.13.1
│  ├─ @ember-data/serializer@3.13.1
│  ├─ @ember-data/store@3.13.1
│  └─ ember-data@3.13.1
├─ ember-data-numerical-date-transform@2.0.3
│  ├─ @ember-data/-build-infra@3.13.1
│  ├─ @ember-data/adapter@3.13.1
│  ├─ @ember-data/canary-features@3.13.1
│  ├─ @ember-data/model@3.13.1
│  ├─ @ember-data/serializer@3.13.1
│  ├─ @ember-data/store@3.13.1
│  └─ ember-data@3.13.1
└─ ember-data@3.12.0
```

These addons expose Ember Data as a `dependency` instead of `devDependency`.

**Comment by runspired** [comment]
@jathanasiou your lock file does look ok, but I'm not sure the grep is quite what we want as it doesn't print out any of the `@ember-data/*` packages or search for any other version, it just searches for the primary ember-data version. We want to detect any other versions that might be present and also ensure that the individual package dependencies are correctly locked to the primary ember-data version.

I think the closest thing to `yarn list --pattern ember-data` is going to be:

```
npm list | grep ember-data 
```

**Comment by jathanasiou** [comment]
@runspired  sadly I've already deleted that folder now and it's gonna be pretty hard to replicate. I will keep in mind in case it occurs on the next release though and post here.

**Comment by ballPointPenguin** [comment]
I use `npm ls ember-data` fyi

**Comment by runspired** [comment]
@ballPointPenguin that doesn’t work for all the packages.

**Comment by Kilowhisky** [comment]
I encountered this as well. I performed a delete on node_modules & dist and then reinstalled and its all good now.  I'm using `npm` btw.

**Comment by ijlee2** [comment]
@runspired I ran into the error when upgrading a tutorial app from 3.13.1 to 3.14.0. I've isolated the repo and added steps for reproducing the error in the readme. Hope this helps you with testing.

https://github.com/ijlee2/bug-upgrade-313-to-314

**Comment by runspired** [comment]
The issue here was compounded by a esm cache we've now removed.
