### ISSUE TITLE
Tom Clancy's Jack Ryan - S2 Ep 4 uses has-many.js

### ISSUE THREAD

**Issue by jonluca** [emberjs/data#6706]
This isn't really an issue but I thought it might be an interesting tidbit for the Ember maintainers. 

There's a scene with code in Tom Clancy's Jack Ryan - S2 Ep 4, around 9:52. For some reason they chose `packages/store/addon/-private/system/references/has-many.js` as an example of "code"

![image](https://i.imgur.com/5XuCfx6.png)

**Comment by runspired** [comment]
We're aware :)
