### ISSUE TITLE
Way to Force HTML5 Fetch?

### ISSUE THREAD

**Issue by jrjohnson** [emberjs/data#6759]
### Description

With Octane allowing jQuery (and our app being quite a distance from being able to switch it off) I'd still like to unify all of our data calls in fetch and be that one step closer. Could this be added as a feature flag to override the jQuery detection in [useFetch](https://github.com/emberjs/data/blob/master/packages/adapter/addon/rest.js#L311)?

Probably related to #6093, but not tied to the jQuery optional feature as that can be left on while still allowing fetch to be used.

**Comment by runspired** [comment]
You should be able to set `useFetch: true` when extending the adapter

**Comment by Gaurav0** [comment]
I think we automatically use ember-fetch if it is installed?

**Comment by runspired** [comment]
@Gaurav0 we don't but maybe we should? @rwjblue and @igorT what would you think of updating our `useFetch` computed to return `true` if `ember-fetch` is installed?

**Comment by jrjohnson** [comment]
As the `useFetch: true` option worked for me I'm inclined to close this unless further discussion is warranted.

**Comment by rwjblue** [comment]
Ya, we can't change to fetch by default (when both ember-fetch and jQuery are present). It would be a breaking change due to things like jQuery emitting ajaxStart/ajaxComplete, jQuery.prefilter, etc).
