### ISSUE TITLE
Turn allowJS on in tsconfig

### ISSUE THREAD

**Issue by runspired** [emberjs/data#6813]
This option being off saved us some hassle early on, but now prevents type info from flowing between packages easily and is covering up mistakes that tsc would otherwise catch.

Having it off also prevents intellisense for Javascript in vscode.

**Comment by igorT** [comment]
Doesn't it make pick up jsdoc comments as typese which is why we turned it off. Why does allowJS have an influence in type picking between packages, we had configured them before to look types between each other?

**Comment by runspired** [comment]
Having it off means that even between typescript files type definitions often do not correctly flow, losing a lot of the ergonomics we would otherwise have. That said now that Model is typed we are over the hump and should instead push to finish typing the project, closing in favor of moar types!
