### ISSUE TITLE
v3.11.5 missing from changelog

### ISSUE THREAD

**Issue by danwenzel** [emberjs/data#6866]
Could you please add v3.11.5 to the changelog?  Thanks!

https://github.com/emberjs/data/compare/v3.11.4...emberjs:v3.11.5

**Comment by runspired** [comment]
cc @igorT

**Comment by igorT** [comment]
Sure thing, will do this after the release

**Comment by brunoocasali** [comment]
Hey people, could you provide CHANGELOG for the 3.16 release too? thx!

**Comment by runspired** [comment]
3.11.5 is missing because it was a re-publish of 3.11.4, there were no changes so the script picked nothing up. 3.16 is in the changelog. Closing.
