### ISSUE TITLE
Setting async belongsTo not working after previous fetch rejected

### ISSUE THREAD

**Issue by danwenzel** [emberjs/data#6867]
### Description

Starting with ember-data version 3.12.0, setting a `belongsTo` relationship property on a model is not working after that relationship previously rejected.  As an example, if an async fetch of a post's `user` returns a 404, I'm then catching the error, creating a new user, and setting it to the post:

```js
async fetchOrCreateUser() {
  try {
    await this.post.get('user');
  } catch (error) {
    // 404 returned.  Create a new user and set it as the post's user
    const newUser = this.store.createRecord('user', {
      name: 'Larry',
    });
    this.post.set('user', newUser);
  }
},
```

#### Expected

`this.post.user` is now the new user

#### Actual

`this.post.user` continues to be the rejected promise from the first `get`

I'm pretty sure this has to do with this change: https://github.com/emberjs/data/pull/6112

This issue does not occur in version 3.11.5 and below.

### Reproduction - Failing Case (v3.12.0)

- Pull this branch: https://github.com/danwenzel/ember-data-relationship-issue/tree/3.12.0
- run `yarn && yarn start`
- visit "http://localhost:4200/
- click "Fetch or Create User"

Notice that the user name never populates, and `isRejected` is always true

### Reproduction - Non-failing Case (v3.11.5)

- Pull this branch: https://github.com/danwenzel/ember-data-relationship-issue/tree/3.11.5
- run `yarn && yarn start`
- visit "http://localhost:4200/
- click "Fetch or Create User"

Notice that the user name does populate successfully

### Versions - Failing Case

```cli
yarn list v1.19.1
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ ember-source@3.13.4
✨  Done in 0.62s.
yarn list v1.19.1
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ ember-cli@3.13.2
✨  Done in 0.63s.
yarn list v1.19.1
├─ @ember-data/-build-infra@3.12.0
├─ @ember-data/adapter@3.12.0
├─ @ember-data/canary-features@3.12.0
├─ @ember-data/model@3.12.0
├─ @ember-data/rfc395-data@0.0.4
├─ @ember-data/serializer@3.12.0
├─ @ember-data/store@3.12.0
└─ ember-data@3.12.0
```

### Versions - Non-failing Case

```cli
yarn list v1.19.1
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ ember-source@3.13.4
✨  Done in 0.67s.
yarn list v1.19.1
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ ember-cli@3.13.2
✨  Done in 0.61s.
yarn list v1.19.1
├─ @ember-data/-build-infra@3.11.5
├─ @ember-data/adapter@3.11.5
├─ @ember-data/model@3.11.5
├─ @ember-data/rfc395-data@0.0.4
├─ @ember-data/serializer@3.11.5
├─ @ember-data/store@3.11.5
└─ ember-data@3.11.5
```

**Comment by runspired** [comment]
Thanks! If you have time to turn your reproduction into a test scenario that would be awesome, but regardless thanks for the report.

cc @code0100fun let's roll this into the unload work since it's a similar issue to what you started out working on.

**Comment by danwenzel** [comment]
Hi, @runspired, thanks for your response!  Yeah, I'll try to get a test scenario written early this week

**Comment by danwenzel** [comment]
@runspired - Here you go: https://github.com/emberjs/data/pull/6874

**Comment by veelenga** [comment]
Also faced with this issue during the upgrade. I assume this is related:

```js
> record.set('myRelation', null)
null
> record.myRelation
Proxy {isFulfilled: false, isRejected: false, content: null, _belongsToState: {…}, _super: ƒ}
```

**Comment by runspired** [comment]
@veelenga your example above seems like correct behavior, content is null

**Comment by danwenzel** [comment]
Hey there @runspired and @code0100fun . Just checking to see if there is an ETA on this one yet

**Comment by kiwiupover** [comment]
@runspired G'day mate is there any movement here. Or is there a better way for us to move forward?

I loved the sit ups and your dog video.
