### ISSUE TITLE
Resolving relationship can trigger assertTagNotConsumed

### ISSUE THREAD

**Issue by makepanic** [emberjs/data#6943]
### Reproduction

Please provide one of the following:

- a github repository with a simplified reproduction and instructions for how to observe the unexpected result

https://github.com/makepanic/data-belongs-to-assertTagNotConsumed

### Description

A computed property that resolves nested relationships can trigger a `assertTagNotConsumed` deprecation.

See in the reproduction repo https://github.com/makepanic/data-belongs-to-assertTagNotConsumed/blob/master/app/components/x-foo.js which simply returns a deeply nested model attribute.

The chain looks like this:

`base (loaded)` -> `foo (unloaded)` -> `bar (unloaded)` -> `name`

The assertion wasn't previously thrown, most likely because older ember versions didn't throw tracking assertions.

![20200103-130107](https://user-images.githubusercontent.com/1205444/71724160-8ea8f700-2e2f-11ea-87df-2b7967af405a.png)

### Versions

Run the following command and paste the output below: `yarn list ember-source && yarn list ember-cli && yarn list --pattern ember-data`.

```cli
ember-source@3.15.0
ember-data@3.15.0
```

(the repro uses npm and output above is from `npm ls <pkg>`)

**Comment by makepanic** [comment]
Updated the repo so it only goes one relationship deep:

`base (loaded)` -> `foo (unloaded)` -> `name`

which causes the assertion warning to be thrown instead:

![20200103-140136](https://user-images.githubusercontent.com/1205444/71726556-bf8d2a00-2e37-11ea-81d0-34579389794b.png)

See https://github.com/makepanic/data-belongs-to-assertTagNotConsumed/commit/c8b36979c6d784f1f6f2d60597caab1c83e453c7 for diff

**Comment by makepanic** [comment]
Just noticed that this can also happens for any nested computed alias, e.g.

```
@alias('foo.name') string!;
```

**Comment by igorT** [comment]
Hi @makepanic, thanks for reporting this. @pzuraq mentioned that this Ember PR should fix this: https://github.com/emberjs/ember.js/pull/18668, do you mind testing it please?

**Comment by makepanic** [comment]
I've manually adjusted ember.debug to use the change in https://github.com/emberjs/ember.js/pull/18668 and I don't see the assertion anymore.

That means the issue is probably fixed. Thanks :+1:

**Comment by makepanic** [comment]
I'll close this because the bug was fixed in ember. Thanks everyone :wave:
