### ISSUE TITLE
API Documentation link in README is dead

### ISSUE THREAD

**Issue by SYU15** [emberjs/data#6945]
https://emberjs.com/api/ember-data/release/modules/ember-data goes to a `404` page. Feel free to close this if you think this should be an issue on the `ember-api-docs` side of things.

**Comment by efx** [comment]
@SYU15 great catch! 

Navigating manually I had to go to https://api.emberjs.com/ember-data/release. I think that is the canonical URL so we should definitely update the README to reflect that. Would you mind opening a PR? Thanks!
From my beginner understanding, `ember-api-docs` and friends handle the YUI documentation inline with ember-data's source code.

**Comment by SYU15** [comment]
Yeah no problem @efx, will definitely make a PR for it :)

**Comment by SYU15** [comment]
Here is the PR as promised @efx: https://github.com/emberjs/data/pull/6950

**Comment by bmac** [comment]
Closed via #6950.
