### ISSUE TITLE
Octane 3.15 issue

### ISSUE THREAD

**Issue by paxer** [emberjs/data#6947]
I've just upgraded to Ember Octane via ember-cli-update and I've noticed a number of acceptance test errors in my project probably somehow related to Ember Data update. My previous ember-data version was 3.12 but ember-cli-update has updated it to 3.15 and the errors in acceptance tests I see `Assertion Failed: You can only unload a record which is not inFlight.` pretty much in all tests where I `createRecord` and `.save()` it. I use Mirage and it was working just fine before to handle `.save()`. So I've reverted only ember-data library version to 3.12 and all tests passed again... I am not sure is this somehow related to ember-data 3.15 or maybe Mirage or something else 🤔

**Comment by runspired** [comment]
what's the stack trace?

**Comment by paxer** [comment]
What's the proper way to get a better stack trace? 
from QUnit in the browser I only see this...

`
Source: | Error: Assertion Failed: You can only unload a record which is not inFlight. `<shop:null>`     at Object.assert (http://lvh.me:4200/assets/vendor.js:48887:15)     at Object.assertAgainstUnloadRecord [as unloadRecord] (http://lvh.me:4200/assets/vendor.js:94625:13)     at InternalModel.send (http://lvh.me:4200/assets/vendor.js:98402:32)     at InternalModel.unloadRecord (http://lvh.me:4200/assets/vendor.js:97938:12)     at InternalModelMap.clear (http://lvh.me:4200/assets/vendor.js:99067:23)     at IdentityMap.clear (http://lvh.me:4200/assets/vendor.js:99121:18)     at InternalModelFactory.clear (http://lvh.me:4200/assets/vendor.js:99436:27)     at DefaultStore.unloadAll (http://lvh.me:4200/assets/vendor.js:102470:17)     at DefaultStore.willDestroy (http://lvh.me:4200/assets/vendor.js:103399:12)     at invoke (http://lvh.me:4200/assets/vendor.js:66090:16)
`

**Comment by runspired** [comment]
Do you have any deprecations in the console? Seems like you should from that trace.

**Comment by paxer** [comment]
yeah I have `You attempted to listen to the "willTransition" event which is deprecated. Please inject the router service and listen to the "routeWillChange" event.` from one of the addons and `computed property was just overriden. This removes the computed property and replaces it with a plain value, and has been deprecated.` but I am not sure are they directly related 🤔

**Comment by paxer** [comment]
actually these deprecations I have on Ember CLI 3.12, not Octane, I might need to try to upgrade to Octane again and check what deprecations I will see there

**Comment by rwwagner90** [comment]
Seeing this error on 3.14 as well.

**Comment by runspired** [comment]
@paxer @rwwagner90 more than likely folks encountering this issue hit something in which upgrading various dependencies caused a test to begin teardown before the save promise completed. Closing but for future wayfairers this is a fairly classic example of an error you might see if your test is "leaky". https://github.com/emberjs/ember-qunit/blob/f6b38abd7195e73723f9a9231ed70339010b7be1/addon-test-support/index.js#L214-L219 can help with that.

**Comment by rwwagner90** [comment]
@runspired hitting this again when trying to update to ember-data 4.x. Any ideas?

**Comment by runspired** [comment]
@rwwagner90 almost certainly means a test waiter isn't waiting for the save promise to complete.
