### ISSUE TITLE
Make sure we test node 10 & node 12 and 13

### ISSUE THREAD

**Issue by runspired** [emberjs/data#6988]

**Comment by efx** [comment]
This means adding those versions to the Travis CI build configuration:
https://github.com/emberjs/data/blob/7f99d0e6e4d22e11ae42446c852f71d702a47b62/.travis.yml#L5-L6

We might be able to simply add other entries in the yaml.
```

**Comment by efx** [comment]
Actually should be done in azure / actions per @runspired
