### ISSUE TITLE
clarify support and behavior around embedded records mixin

### ISSUE THREAD

**Issue by efx** [emberjs/data#6991]
Initial documentation was landed in #6958, but we should make it clearer for folks by default. After discussing in the ember-data core meeting on 2020-02-19, we (@hjdivad, @rwjblue, and @efx) propose:

Updating the embedded records mixin to assert when used with `JSONAPISerializer` unless a specific flag to opt out of the assertion is used.

Something like:

```js
assert(
  'The embedded records mixin does not work with all JSON:API\'s, please confirm this works for your specific API and add `this.isEmbeddedRecordsMixinCompatible = true` to your serializer', 
  this.isJSONAPISerializer !== true || this.isEmbeddedRecordsMixinCompatible === true
);
```

**Comment by adriancerejo** [comment]
I am fairly new to open source contributions and was wondering if I could take this issue.

**Comment by allthesignals** [comment]
Hmm I think it might go here: https://github.com/emberjs/data/blob/v3.17.0/packages/serializer/addon/json-api.js

I'm not sure where makes the most sense, maybe the constructor?

**Comment by hjdivad** [comment]
@allthesignals @adriancerejo changing the existing warning you identified to an assertion with an opt-out flag would be great.

**Comment by allthesignals** [comment]
@hjdivad I've got a branch but I'm not sure which to PR into, gonna check docs in a sec :)
