### ISSUE TITLE
Add optional json-patch behavior on save() 

### ISSUE THREAD

**Issue by slimee** [emberjs/data#7033]
Would be awesome to have the optional possibility to automatically produce Patch saves using Json merge patch or Json patch.
As explained here: https://stackoverflow.com/questions/60097932/designing-endpoint-for-performing-partial-updates-with-patch

Thanks you.

**Comment by runspired** [comment]
@slimee adapters are fully customizable and thus configuring `updateRecord` to generate a patch request is doable. The snapshot has a `changedAttributes` API for precisely for helping generate just such a patch.

If you want your patches to also include patches for relationships you may need a solution like ember-data-change-tracker to keep track of changed relationship pointers. This isn't something we have a public API for but it is something we are intending on adding a public API for in the future.

Closing as generating the patch isn't a feature we will add for "out of the box".
