### ISSUE TITLE
`BelongsToReference.meta()` sometimes not populated properly

### ISSUE THREAD

**Issue by Herriau** [emberjs/data#7039]
### Description

When an optional `belongsTo` relationship is loaded independently from the model it's defined on, e.g. when invoking `await someRecord.belongsTo('someRel').load()`, then the meta hash is only accessible on `BelongsToReference` object when `Adapter.findBelongsTo()` resolves to a hash that contains a non-null value on its `data` key.

Say I have a record loaded through `store.findRecord('some-model', <some-id>)`, intially hydrated from the following JSONAPI document:

```
GET /some-model/<some-id>

{
  data: {
    "type": "some-model",
    "id": <some-id>,
    "attributes": { ... },
    "relationships": {
      "some-rel": {
        "links": {
          "related": "/some-model/<some-id>/some-rel"
        }
      }
    }
  }
}
```

Then let's say I load that one relationship with `await someRecord.belongsTo('someRel').load()`, If the request / response that resulted from that call look like:

```
GET /some-model/<some-id>/some-rel

{
  "data": {
    "type": "some-other-model",
    "id": <some-other-id>,
    "attributes": { ... },
    ...
  },
  "meta": {
    "foo": "bar",
  }
}
```

then `someRecord.belongsTo('someRel').meta()` will return `{ foo: "bar" }`, which is correct. However if the request / response that resulted from that call look like:

```
GET /some-model/<some-id>/some-rel

{
  "data": null,
  "meta": {
    "foo": "bar",
  }
}
```

then `someRecord.belongsTo('someRel').meta()` will return `null`, when I would have expected it to return `{ foo: "bar" }` as well.

### Reproduction

**models/car.ts**
```typescript
export default class Car extends Model {
  @belongsTo('navigation-system')
  navigationSystem: NavigationSystem | null;
}
```

**models/navigation-system.ts**
```typescript
export default class NavigationSystem extends Model {}
```

**adapters/car.ts**
```typescript
export default class CarAdapter extends ApplicationAdapter {
  async findAll(store: any, type: any): Promise<any> {
    return {
      data: [
        {
          type: 'cars',
          id: 1,
          attributes: {},
          relationships: {
            navigationSystem: {
              links: {
                related: '/car/1/navigation-system',
              }
            }
          }
        },
        {
          type: 'cars',
          id: 2,
          attributes: {},
          relationships: {
            navigationSystem: {
              links: {
                related: '/car/2/navigation-system',
              }
            }
          }
        }
      ]
    };
  }

  async findBelongsTo(store: any, snapshot: any): Promise<any> {
    switch (snapshot.id) {
      case 1:
        return {
          data: { type: 'navigation-systems', id: 10, attributes: {} },
          meta: { foo: 'bar' },
        };

      case 2:
        return {
          data: null,
          meta: { foo: 'bar' },
        };
    }
  }
}
```

**test.ts**
```typescript
const [car1, car2] = (await store.findAll('car')).toArray();

car1.belongsTo('navigationSystem').meta(); // { foo: 'bar' }
car2.belongsTo('navigationSystem').meta(); // null, expected { foo: 'bar' }
```

### Versions

```cli
└─ ember-source@3.12.2
└─ ember-cli@3.14.0
├─ @ember-data/adapter@3.16.0
├─ @ember-data/canary-features@3.16.0
├─ @ember-data/debug@3.16.0
├─ @ember-data/model@3.16.0
├─ @ember-data/private-build-infra@3.16.0
├─ @ember-data/record-data@3.16.0
├─ @ember-data/rfc395-data@0.0.4
├─ @ember-data/serializer@3.16.0
├─ @ember-data/store@3.16.0
├─ @types/ember-data@3.1.9
├─ ember-data-copyable@1.1.2
└─ ember-data@3.16.0
```

**Comment by Herriau** [comment]
This originally came up when investigating a public way of dealing with this other issue: #5629

**Comment by runspired** [comment]
A PR with a test for this would be awesome, I suspect the issue is either that our code which ensures that the response of `findBelongsTo/findHasMany` is a complete payload is insufficient or that due to the missing data/included property it never gets threaded through to the relationship. In either case the fix shouldn't be terribly hard and I'd be happy to pair on a fix.
