### ISSUE TITLE
Document `instantiateRecord` and RFC#487 custom model class APIs

### ISSUE THREAD

**Issue by hjdivad** [emberjs/data#7055]
Action Items:
- [x] Document how to implement custom model classes (See RFC: https://github.com/emberjs/rfcs/blob/master/text/0487-custom-model-classes.md)

We've had discussions the last couple meetings about how to refer to model classes in the face of
 - The `DS` namespace going away in favour of packages and
 - Model being ambiguous between `@ember-data/model` and the user-specified return from [instantiateRecord](https://github.com/emberjs/data/blob/75d07d9409694143547c6c5271ab40800fcbb941/packages/store/addon/-private/system/core-store.ts#L482-L487)

The upshot is to refer to `@ember-data/model` specifically and to separately add documentation for implementing custom model classes, part of which requires coming up with clear names to describe generic records.

Custom model classes is an advanced feature that shouldn't be part of the onboarding guides.  A reasonable place to put this sort of thing might be under `Additional Resources -> Advanced -> Custom Model Classes` on https://guides.emberjs.com/release/

cc @rwjblue @igort @runspired @efx

**Comment by runspired** [comment]
Documented in #8114
