### ISSUE TITLE
Running tests via `yarn start` fails

### ISSUE THREAD

**Issue by pzuraq** [emberjs/data#7072]
### Reproduction

```
yarn start
```

Then visit the tests page

### Description

Several modules fail to load with messages like the following:

```
Error: Could not find module `@ember-data/unpublished-test-infra/version` imported from `@ember-data/unpublished-test-infra/test-support/deprecated-test`
```

### Versions

On master, doesn't affect published code/versions

**Comment by snewcomer** [comment]
I wonder if we need to really wrap this in the test command env variable?  I'm guessing we could get away with it!

https://github.com/emberjs/data/blob/648f2f5bcedc9d2c6fd7fdcb88463cdfeac21c5f/packages/unpublished-test-infra/index.js#L12

**Comment by rwjblue** [comment]
@snewcomer - Yes, you are correct. I think we can basically just remove that...
