### ISSUE TITLE
 findRecord does not update included hasMany relationships

### ISSUE THREAD

**Issue by LucasSys** [emberjs/data#7087]
I have the following models.

### Orcamento
```
import Model, { attr, belongsTo, hasMany } from '@ember-data/model';
import moment from 'moment';

export default Model.extend( {

  inicio: attr('string'),
  fim: attr('string'),

  condominio: belongsTo('condominio'),
  orcamento_contas: hasMany('orcamento-conta'),

});
```
### orcamento-conta
```
import Model, { attr, belongsTo, hasMany } from '@ember-data/model';
import Validator from 'ember-model-validator/mixins/model-validator';

export default Model.extend(Validator, {

  conta: belongsTo('conta'),
  orcamento: belongsTo('orcamento'),
  orcamento_previsoes: hasMany('orcamento-previsao'),

});
```
### orcamento-previsao
```
import Model, { attr, belongsTo } from '@ember-data/model';

export default Model.extend( {

  referencia: attr('number'),
  valor: attr('number'),

  orcamento_conta: belongsTo('orcamento-conta'),

});
```
and the following routes.

### previsao-orcamentaria/visualizar
```
import Route from '@ember/routing/route';

export default Route.extend({

  model({ orcamento_id }) {
    return this.store.queryRecord('orcamento', {
      orcamento_id,
      include: 'orcamento_contas,orcamento_contas.conta,orcamento_contas.orcamento_previsoes'
    });
  },

});
```
### previsao-orcamentaria/editar
```
import Route from '@ember/routing/route';
import { get } from '@ember/object';
import { hash } from 'rsvp';
import ModelTimeMachine from 'teste-app/utils/model-time-machine';

export default Route.extend({

  model({ orcamento_id }) {
    const condominio = this.modelFor('condominio');
    const orcamento_tipo = get(condominio,'orcamentoTipo');
    const condominio_id = get(condominio, 'id');
    const content = this.store.findRecord('orcamento', orcamento_id, {
      include: 'condominio,orcamento_contas,orcamento_contas.orcamento_previsoes'
    });
    const orcamento = ModelTimeMachine(content);
    return hash({ orcamento, orcamento_tipo });
  },

  actions: {

    willTransition() {
      const model = this.currentModel;
      const orcamento = get(model, 'orcamento');
      orcamento.undoAll();
    }

  }

});

```

### teste-app/utils/model-time-machine'
```
import TimeMachine from 'ember-time-machine';
import { Promise } from 'rsvp';
import { assign } from "@ember/polyfills";

export default function(model, options) {
  return new Promise((resolve) => {
    resolve(model);
  }).then((content) => {
    const params = assign({ content }, options);
    return TimeMachine.Object.create(params);
  });
}
```

### Reproduction

I enter the visualizar route, then I navigate to the editar route.

![visualizar](https://user-images.githubusercontent.com/55147215/76093643-1b8f3e80-5fa0-11ea-9ea9-fc1969687c74.png)

![image](https://user-images.githubusercontent.com/55147215/76093779-56917200-5fa0-11ea-90fc-3509a642575c.png)

I change the value of valor to 2 and saved it in the database.

then I enter the visualizar screen again and check the value.

![image](https://user-images.githubusercontent.com/55147215/76094375-4b8b1180-5fa1-11ea-82cd-d95c05a22223.png)

it keeps the previous one, even in the request coming with the updated value.

![image](https://user-images.githubusercontent.com/55147215/76094424-61003b80-5fa1-11ea-8469-9d4020b58ad1.png)

### Description

I think it may be the time machine but I'm not sure, if you can help me I would be very grateful.

### Versions

I use pods and engines.
ember-cli: ~3.14.0
ember-data: ~3.14.0
ember-time-machine: master

**Comment by runspired** [comment]
For help we recommend asking in the #ember-data or #help channels in the Ember Community Discord: https://discord.gg/emberjs 

I'm going to close this as it is for support and not for a bug; however, I am happy to assist you on discord. That said issues with EmberTimeMachine would likely be better assisted by folks familiar with that project as I am not.
