### ISSUE TITLE
Allow adapter to override VERB in request

### ISSUE THREAD

**Issue by Benjy1979** [emberjs/data#7088]
Hi,

Would be nice if the adapter could allow override of the VERB to be used.
For example if you want findAll to be a POST instead of GET.  I would expect it to run the serializer on it and change the format of it.

At the moment it seems you are forced to override the whole findAll function.

**Comment by runspired** [comment]
Hi @Benjy1979, serializers don't have anything to do with creating the parameters for a request.

For an Adapter, the correct hook to implement would indeed be the method for the request you are looking for.

**Comment by Benjy1979** [comment]
At the moment, the serializer is not call for the model if the verb happens to be a GET, for example.

   That is what I'm saying. But if you were to allow an override for the verb, then it should be called if the application changes the verb for a call to findRecord to a POST, for instance.

Yes I know it violates REST but the client isn't always able to dictate what the server does. The point is flexibility.

**Comment by runspired** [comment]
@Benjy1979 I recommend reading the API docs overview for serializers and adapters to clarify your understanding.

Adapter Docs: https://api.emberjs.com/ember-data/release/modules/@ember-data%2Fadapter

Serializer Docs: https://api.emberjs.com/ember-data/release/modules/@ember-data%2Fserializer

They include detailed information in their respective "minimum interface" docs on when each hook is invoked and how to use them.

**Comment by Benjy1979** [comment]
> `_This is often described as a per-model or per-type strategy for defining serializers. However, because APIs rarely format payloads per-type but rather per-API-version, this may not be a desired strategy.
`
I see. That is exactly the issue.
