### ISSUE TITLE
[3.16] intimate api getModelTypes() fails

### ISSUE THREAD

**Issue by Gaurav0** [emberjs/data#7112]
Running the intimate api:

`applicationInstance.lookup('data-adapter:main').getModelTypes()`

in Ember Data 3.16 and above fails with this error message:

`No model was found for '@ember-data/model/-private'`

See https://github.com/cardstack/ember-data-fastboot/issues/20

**Comment by codebruder** [comment]
I got the same issue. Any update on this?

**Comment by runspired** [comment]
ember-data-fastboot will need to take a new approach, the best approach currently would be to hook the recordData creation hook to keep track of seen types.

**Comment by runspired** [comment]
closing as using the inspector API to access this info was always a bit off and there are other ways to gather this information if needed for use cases like those in the linked cardstack issue (though cardstack.ember-data-fastboot is still using the inspector for this which is brittle and not a great idea. scanning the model list or wrapping one of the public APIs for that populates things for a type would be better).
