### ISSUE TITLE
Calling rollback() on a "new" record sets "deleted.saved" state

### ISSUE THREAD

**Issue by davelindquist-egistix** [emberjs/data#7122]
### Reproduction

See the Ember twiddle here, which reproduces the problem:

https://ember-twiddle.com/6b3e9e20c1c96d1b8d8bf09569fb2d34?openFiles=components.ember-data-test-rollback-new%5C.js%2Ctemplates.components.ember-data-test-rollback-new%5C.hbs

### Description

If you do the following operations:
1. Create a new record
2. Set an attribute
3. Call rollbackAttributes()
then Ember Data incorrectly marks the record as "saved and deleted" (no idea why that was chosen).

Specifically, this code:
```js
let record = this.store.createRecord('sometypeofmodel');
record.name = 'Bob';
record.rollbackAttributes();
// at this point, record.isNew is FALSE, and record.isDeleted is TRUE
```
Drilling into the Ember Data code, we can see this specifically -- rollbackAttributes calls:

```js
  createdState.uncommitted.rolledBack = function (internalModel) {
    internalModel.transitionTo('deleted.saved');
    internalModel.triggerLater('rolledBack');
  };
```
This causes a severe break for us attempting to upgrade from 2.18 to 3.12.

Thanks!

### Versions

```cli
"ember-cli": "~3.12.0",
"ember-source": "~3.12.0",
"ember-data": "~3.12.0",
```

(The provided 'yarn' commands don't work when yarn is not present...  The above are the relevant items from the package.json.)

**Comment by runspired** [comment]
The transition to `deleted.saved` is intentional, and was the behavior since the early days of this being the data library in SproutCore (I checked through the commit history and that code originates over 10 years ago). The idea is that rolling back something in the new state can only be a deletion, since no prior state exists.

What is the observable change you see?

**Comment by runspired** [comment]
I migrated the twiddle to 2.18 and even in 2.18 `isNew` is false and `isDeleted` is true: https://ember-twiddle.com/f4de9c30a661669fc94e3ecd0b712e91?openFiles=components.ember-data-test-rollback-new%5C.js%2Ctemplates.components.ember-data-test-rollback-new%5C.hbs

**Comment by davelindquist-egistix** [comment]
Hmm, OK, I'll take your word for it.  That's not the behaviour I saw in the application, but perhaps there was some other mitigating factor?

This seems like a bizzare choice of behaviour -- it's not at all consistent with the behaviour for a loaded record.  Here is what the flow looks like for each case (side-by-side):

|| Existing Record | New Record ||
|--|--|--|--|
||||??|
|**⭧**|store.findRecord | store.createRecord |**🠕**|
|**🠕**|record.name = 'Bob' | record.name = 'Bob' |**🠕**|
|**⭦**|record.rollbackAttributes() | record.rollbackAttributes() |**⭧**|

As you can see in the diagram above:
* For a LOADED record, the 'rollbackAttributes' reverts back to the state as of the findRecord call
* For a NEW record, the 'rollbackAttributes' does not - it reverts to some bizarre "prior to the record existing" state
    * I believe it SHOULD revert back to the state as of the createRecord call.

Is this something that cannot then be changed, since it is pre-existing behaviour?

Is there any way to get a sane rollbackAttributes equivalent, that just takes us back to the "newly created record" state?  I'm not seeing any obvious way of doing this in the API?
