### ISSUE TITLE
store injection initializer should be in store package, not meta package

### ISSUE THREAD

**Issue by hjdivad** [emberjs/data#7158]
this currently exists in `packages/-ember-data/addon/setup-container.js` but is a concern of the `store` package.

As of now, manually recreating these injections is required to use project trim.

cc @stefanpenner @runspired

**Comment by runspired** [comment]
@hjdivad this difference is intentional and is part of Project Trim. Apps bringing the individual packages can either do the registration themselves or use explicit injection.

**Comment by hjdivad** [comment]
@runspired ok, it's something that we'll need to include when we document how to use Project trim.
