### ISSUE TITLE
Fields in model not refreshing

### ISSUE THREAD

**Issue by csylaios** [emberjs/data#7165]
### Reproduction

I don't know how you can reproduce this since i haven't been able to track exactly when its happening 

### Description

i am using store.query to get a list of records. these records contain some attributes that are `serialised: false` in the serialiser. the backend returns an attribute with a value, however when i try to get this value from the model it's `undefined`. this does not happen always. the record has a field `data` and if i check there the data does actually exists, however i get undefined when using the getter to retrieve the value.

if i call `this.store.unloadAll('task');` and then query for the records everything works fine.

I am using the REST adapter, serialiser, etc.

### Versions

i noticed this in 3.17 and upgraded to 3.18 and still getting the same issue

thanks for your help

**Comment by runspired** [comment]
Closing as this seems likely to be very specific to your application, happy to assist in debugging though. Feel free to reach out on discord!
