### ISSUE TITLE
Should we make detectMerge and/or __configureMerge public

### ISSUE THREAD

**Issue by igorT** [emberjs/data#7188]

**Comment by igorT** [comment]
As https://github.com/emberjs/data/pull/7182 showed, there might be a need to configure merging strategies, but it's unclear whether we should expose the current configure merge mechanism, as you might need to configure detecting merge as well. 
@runspired mentioned calling it handlePotentialConflict or something like that

**Comment by runspired** [comment]
We ended up finding use-case for the cache knowing when this has occurred and added an operation to the cache RFC (in lieu of a hook) https://github.com/emberjs/rfcs/pull/854. We do not believe we need the hook to be public.
