### ISSUE TITLE
[improve] Provide meaningful debug information for identifier update error

### ISSUE THREAD

**Issue by lifeart** [emberjs/data#7193]
I see `Failed to update the 'id' for the RecordIdentifier '[object Object]' to '27830', because that id is already in use by '[object Object]'`. 

`[object Object]` - is not meaningful debug message, and it's tricky to track down issue (modelType? payload?)

![image](https://user-images.githubusercontent.com/1360552/81988908-e9a3f380-9644-11ea-9470-491164141640.png)

**Comment by snewcomer** [comment]
Perhaps we can replace `[object Object]` with `identifier.type || identifier` instead.  Or stringify the identifier object but that not print out pretty.

Here is another solution for that error.

```
const identifierOutput = typeof identifier === 'object' ? `id: ${identifier.id}, type: ${identifier.type}` : identifier;

throw new Error(`Failed to update the 'id' for the RecordIdentifier '${identifierOutput} to '${resourceData.id}', because that id is already in use by '${matchedIdentifierOutput'`)
```

**Comment by runspired** [comment]
I'm guessing this is a production build? In dev we implement `toString` for nice ergonomics.
