### ISSUE TITLE
Many-to-many per-relationship metadata not accessible

### ISSUE THREAD

**Issue by lfrost** [emberjs/data#7194]
The JSON:API specification provides for many-to-many relationship metadata at the level of individual relationships (https://jsonapi.org/format/#document-resource-identifier-objects).  There seems to be no way to access this information in the Ember Data API (v3.18.0).  Metadata can be accessed at the level of the type of relationship (which is also specified by JSON:API), but not at the level of individual relationships.

Below is an example.  This would be extremely useful because many-to-many tables often include additional columns.

```json
{   
    "data": {
        "id": "1",
        "type": "table1"
        "attributes": {
            ...
        },
        "relationships": {
            "table2s": {
                "data": [
                    {   
                        "id": "11",
                        "type": "table2",
                        "meta": {
                            "order": 1
                        }
                    },
                    {   
                        "id": "12",
                        "type": "table2",
                        "meta": {
                            "order": 2
                        }
                    }
                ]
            }
        }
    }
}
```

**Comment by runspired** [comment]
We have no plans of implementing support for this form of meta.

ResourceIdentifierObjects are (fuzzily) considered global and storing meta contextual to a specific relationship on them would be a source of conflict. Spec aside, within EmberData these objects are 100% treated as system-wide/global identifiers. A custom cache solution (not yet fully feasibly but with RecordData *mostly* feasible) could extract and handle this info separately but I think it is unlikely we would do this as a default as this form of meta is uncommon.

Some alternatives include:

- You could model this with an explicit join model
- You could extract this meta in your serializer and make it accessible via a map using the parent record and relationship name as keys.
- You could hoist this info into the overall relationship meta

**Comment by runspired** [comment]
I'm going to close this as its not on our roadmap to consider. A change like this would require an RFC although for the reasons listed above its likely this should be left to user-land implementation vs something in the core.
