### ISSUE TITLE
Build Error: Property typeName of TSTypeReference expected node to be of a type ["TSEntityName"] but instead got "MemberExpression"

### ISSUE THREAD

**Issue by snewcomer** [emberjs/data#7201]
I'm getting this build error across a couple of repos.  See links below.  The error has nothing to do with `ember data`.  However, since the error emanates from `system/core-store`, I thought filing this issue to track fixes in (likely) a broccoli repository would help others quickly identify a source.

> /home/runner/work/data/data/packages/unpublished-fastboot-test-app/-private/system/core-store.ts: Property typeName of TSTypeReference expected node to be of a type ["TSEntityName"] but instead got "MemberExpression"

https://travis-ci.org/github/poteto/ember-changeset/jobs/692401091
https://github.com/emberjs/data/pull/7171/checks?check_run_id=719006901

**Comment by richard-viney** [comment]
I think that this is a regression from the recent `ember-cli-babel@7.20.1` update, see babel/ember-cli-babel#338.

Something to do with `type = import('...')` syntax used by `ember-data` seems like a possible culprit here.

**Comment by rwjblue** [comment]
https://github.com/babel/ember-cli-babel/releases/tag/v7.20.2 is out with the fix for the TS issue (thank you @fivetanley#8581!).
