### ISSUE TITLE
Add active-model-adapter to partner tests

### ISSUE THREAD

**Issue by igorT** [emberjs/data#7218]
Especially as we will be refactoring the adapter/serializer area soon

**Comment by dcyriller** [comment]
@igorT I've started to look into this. I'm interested - being a user of `active-model-adapter`.

To add active-model-adapter to partner tests, I will open a PR to remove bower usage there.

But I also have a question... Is it ok to also not publish anymore the package on rubygems? Indeed, it looks that active-model-adapter is published on rubygems under the name [active-model-adapter-source](https://rubygems.org/gems/active-model-adapter-source). It would be used by the [ember-rails project](https://github.com/emberjs/ember-rails) to add frontend capabilities to a rails app. None of the projects are deprectated, but I assume that consumming an ember addon through the ruby gem is not recommended anymore - and difficult to support. After that, we'd release a 3.x version. If any patch needs to be applied on active-model-adapter-source, it would be done on a 2.x branch.

**Comment by dcyriller** [comment]
I see a PR has already been started to drop bower 🎉 https://github.com/ember-data/active-model-adapter/pull/121

**Comment by runspired** [comment]
closing in favor of #7529 7529
