### ISSUE TITLE
Fetch + fastboot + jquery detection problem

### ISSUE THREAD

**Issue by vlascik** [emberjs/data#7219]
If an app has `ember-cli-fastboot`, `ember-fetch` and `@ember/jquery` as dependencies, code in https://github.com/emberjs/data/blob/35b8abfb7d0fb23ae07a723955d5364d8eee398c/packages/adapter/addon/rest.js#L312-L323 doesn't seem to end up with `fetch`, and uses `najax` instead. Which leads to errors like `najax: method jqXHR."getAllResponseHeaders" not implemented`

Ideally, fetch would be used instead, perhaps with additional check like
```javascript
    if (this.fastboot && hasFetch) {
      return true;
    } else if (jQueryIntegrationDisabled) { 
```

Seems this method was added in https://github.com/emberjs/data/pull/6094/

Not sure if there is a reason for current logic though, or how to proceed.

**Comment by rwjblue** [comment]
Since `ember-data` added support via `najax` long before `fetch` support **and** `ember-fetch` was already commonly in use when we added support for `fetch` we were forced to preserve the priority fallback order (otherwise it would have been arguably a breaking change).

**Comment by rwjblue** [comment]
I think the easiest thing to do would be to override `useFetch` in your application adapter (to be `true`).

**Comment by vlascik** [comment]
Yep, that's what I ultimately did, but the current situation is confusing, maybe this should have at least a warning, documentation, or a more permanent solution, like `najax` deprecation? Don't think that library is used by many anymore.

**Comment by snewcomer** [comment]
I was looking at this too at some point so thanks for the explanation!  Is it worth making an issue to remind us to change for the 4.0 release?

**Comment by rwjblue** [comment]
I agree with @vlascik, we can (and probably) should issue a deprecation when we detect that we are going to fallback to the `najax` side of things. Though we'll have to take care to ensure that the deprecation is triggered in both FastBoot and normal browser runtimes (deprecation in FastBoot alone is much less like to actually be seen unless parsing through server logs).
