### ISSUE TITLE
Cannot import PromiseObject and PromiseArray

### ISSUE THREAD

**Issue by nezmen** [emberjs/data#7229]
The docs make it appear as though you should import using `import { PromiseArray } from '@ember-data/store;` but it comes back undefined.

When looking at tests, it looks like we should use
`import { PromiseArray } from '@ember-data/store/-private';`

But that fails lint rules due to the private module.

It looks like it should be available here - [https://api.emberjs.com/ember-data/3.18/classes/PromiseArray](https://api.emberjs.com/ember-data/3.18/classes/PromiseArray) and [https://api.emberjs.com/ember-data/3.18/modules/@ember-data%2Fstore](https://api.emberjs.com/ember-data/3.18/modules/@ember-data%2Fstore)

What is proper way to use these?  We like to use the promises since they have the pending/state hooks.

**Comment by runspired** [comment]
@nezmen these classes were intentionally given no import syntax of their own. Either use them via the `DS` namespace (which will eventually be deprecated) or create them within your app if still required.

That said, better patterns exist using async/await, generators, ember-concurrency, and tracked that do not require you to wrap async values in this way for templates.
