### ISSUE TITLE
[Proposal]: Pass through `fields` option to findRecord and findAll query parameters

### ISSUE THREAD

**Issue by snewcomer** [emberjs/data#7233]
A low impact addition (similar to `include`) to the library would be to pass along sparse fieldsets to the query parameters for a request.

JSONAPI spec: https://jsonapi.org/format/#fetching-sparse-fieldsets

ref https://github.com/emberjs/data/issues/3596

**Comment by runspired** [comment]
I'm unsure about this though I'll bring it up at the team meeting. There's a few ways forward here:

- loosen the restriction on what goes in params
- tell folks to use adapterOptions
- add adapterOptions.fields support "built in"
- do nothing, folks should use query/queryRecord for this

One of the concerns I have is around user expectations for the cache. Repeated calls to findRecord with different fields arguments would need to determine whether those fields are satisfied. Users could likely solve this today by using adapterOptions and implementing shouldReloadRecord wherein snapshot.adapterOptions can be accessed and used to determine if additional fields are required to be loaded.

**Comment by snewcomer** [comment]
> I have is around user expectations for the cache

I'm guessing this is also a problem for `include` then as well?
