### ISSUE TITLE
Date transform not deserialized after saving new record

### ISSUE THREAD

**Issue by charlesfries** [emberjs/data#7246]
```cli
DEBUG: -------------------------------
DEBUG: Ember             : 3.18.1
DEBUG: Ember Data        : 3.18.0
DEBUG: jQuery            : 3.5.1
DEBUG: Ember Simple Auth : 3.0.0
DEBUG: EmberFire         : 3.0.0-rc.6
DEBUG: Firebase          : 7.15.2
DEBUG: -------------------------------
```

```js
export default class UserModel extends Model {
  @hasMany('shift') shifts;
}
```

```js
export default class ShiftModel extends Model {
  @belongsTo('user') user;
  @attr('date') inAt;
  @attr('date') outAt;
}
```

Here is the issue:

```js
let shift = user.shifts.createRecord();
shift.inAt = new Date();
console.log(shift.inAt); // Date Mon Jul 06 2020 15:15:51 GMT-0700 (Pacific Daylight Time)
await shift.save();
console.log(shift.inAt); // 2020-07-06T22:15:51.463Z
```

For some reason, after a new model is saved, attributes of type `date` are not deserialized properly.  I can get around this by first saving the model with a null `inAt` attribute:

```js
let shift = user.shifts.createRecord();
await shift.save();
console.log(shift.inAt); // null
shift.inAt = new Date();
console.log(shift.inAt); // Date Mon Jul 06 2020 15:15:51 GMT-0700 (Pacific Daylight Time)
await shift.save();
console.log(shift.inAt); // Date Mon Jul 06 2020 15:15:51 GMT-0700 (Pacific Daylight Time)
```

If `save()` is omitted altogether, or if the record is created and saved before `inAt` is set, `console.log` outputs the proper, deserialized attribute. Is this expected behavior?

**Comment by snewcomer** [comment]
@charlesfries 👋 Thank you for the detailed issue.  Just to check before I look into this.  Do you have your own transform that you extend?  Or your own serializer/adapter work that could be causing this issue?

**Comment by charlesfries** [comment]
@snewcomer Thanks for the reply. After further testing I've realized it's an issue with Emberfire. I'm not extending/using any custom transforms, but I *am* using an adapter and a serializer imported from Emberfire, which seem to be causing the issue. Closed
