### ISSUE TITLE
API docs do not match Octane blueprints 

### ISSUE THREAD

**Issue by maxwondercorn** [emberjs/data#7256]
The API docs do not reflect the native classes generated with Octane. I didn't see any open issues on this and didn't know if this is in the works or something that's looking for a volunteer? 

I see some of the example code has been updated in 3.20.

edit - add package checklist

Packages:
- [x] adapter - pr #7286
- [x] model - pr #7292 
- [x] serializer - pr #7296
- [x] store - #7297

**Comment by igorT** [comment]
@maxwondercorn oops, missed this. Yeah this would be a great volunteer effort. Do you have time to work on this?

**Comment by maxwondercorn** [comment]
Yes, I can find time to work on this. If it's okay I may want to submit multiple PRs rather than trying to do everything in one large PR. Easier to do and easier to review the PRs.

**Comment by igorT** [comment]
Yup, that sounds like a great way to do it
