### ISSUE TITLE
Bypass promise cache in reload/reloadHasMany

### ISSUE THREAD

**Issue by iamareebjamal** [emberjs/data#7268]
We use this library https://github.com/mdehoog/ember-data-has-many-query to write queries with nested has many items with filters. For example, an event with ID 1 can have multiple speakers. If we want to only show featured speakers with sessions included and page size 6, we write

```js
await event.query('speakers', {
  include      : 'sessions',
  filter       : [{ featured: true }],
  'page[size]' : 6
});
```

There is no alternative in documentation which lets us achieve this behavior which is quite common in apps. This is why we had to resort to this library which is now unmaintained. 

This library depends on `reloadHasMany` to reload the linked resource if the passed parameters have changed. But as you can see here:

https://github.com/emberjs/data/blob/a3fd90fe3c5c700ee90ef60bc53d2eb1b8f46344/packages/store/addon/-private/system/model/internal-model.ts#L836-L840

If there already is a pending promise with `speakers` key in cache, it returns that. Leading to this bug: https://github.com/emberjs/data/issues/7074

The method has no knowledge that these 2 promises were of completely different queries, because it only cares about property name/key. In a perfect world where a related resource is queried with same parameters always, it might work, but that is rare for any application. 

Is there any other pattern which makes it possible to query one to many resources with custom query parameters? Or else there must at least be a way in passed in options to bypass the promise cache so that we can at least build our own buggy abstractions to overcome the limitations?

```js
let loadingPromise = this._relationshipPromisesCache[key];
if (loadingPromise && !options.forceReload) {
  return loadingPromise;
}
```

**Comment by runspired** [comment]
It's relatively trivial to simply use `query` for this use case instead of relying on relationship infrastructure at all. A relationship that gets blown away any time you want to change the slice of data you are looking at isn't a relationship at all.

**Comment by iamareebjamal** [comment]
That means our implementation of `/events/[id]/speakers` never gets used and was implemented for no reason and we always use `/speakers?filter[event]=[id]` which may have different semantics than the previous API and not be possible everywhere, and not to mention less easier and obvious as well

**Comment by runspired** [comment]
@iamareebjamal Not at all!

I'd suggest learning more about writing (and customizing) adapters as well as the options that are able to be passed through.

https://api.emberjs.com/ember-data/3.26/classes/MinimumAdapterInterface/methods/query?anchor=query

Here's an example of adding a `query` API to a record that does exactly this. https://ember-twiddle.com/82142e38819bd4a3bb645a9c12a38f23?openFiles=adapters.application%5C.js%2C

**Comment by iamareebjamal** [comment]
Cool. I'll check it out and see if it solves y usecase
