### ISSUE TITLE
Synchronous belongsTo relationships not materializing when new records are pushed to store.

### ISSUE THREAD

**Issue by arenoir** [emberjs/data#7279]
I am having an issue with how ember-data loads synchronous relationships.   I have a customer model that synchronously belongs to an address.  The customer json payload always includes the address.   However I am intermittently getting `the associated records were not loaded` error.   It is random and frustrating.  

It is a fairly large list of customer and address records (150+). If I change the relationship to async it works and incidentally doesn't try to fetch the address records that it thinks are not included in the payload.
I am trying to move away from async relationships as they don't work well with es5 getters and tracked properties.

It looks like the customer records that are returned from the routes model hook via this.store.peekAll('customer') method is returning models that are not finished materializing?

### Reproduction

You can reproduce this issue by creating a `RecordArrays` using the the store `peekAll` method.  Then rendering a list and then fetching more records.   The rendered list will try to re-render but fail.

```javascript
test('it render synchronous belongs-to immediately',  async function(assert) {
    let people = store.peekAll('person');
    this.set('people', people);

    let factory = makePeopleWithAddressRelationshipData(200);
    store.push(factory.dataHash);

    await render(hbs`
      <ul>
        {{#each this.people as |person|}}
          <li class="person">{{person.name}} @ {{person.address.lineOne}}</li>
        {{/each}}
      </ul>
    `);

    assert.dom('li').exists({ count: 200 }, 'list has first fetched results'); // Passes test!

    let factory2 = makePeopleWithAddressRelationshipData(200, 200);
    store.push(factory2.dataHash);
    await settled();
  
    assert.dom('li').exists({ count: 400 }, 'collection is updated');  // Fails test!
  });
```

### Description

Pushing new records with synchronous belongsTo relationships to the store does not update `RecordArrays` properly and returns an error.

```
Uncaught Error: Assertion Failed: You looked up the 'address' relationship on a 'customer' with id 8 but some of the associated records were not loaded. Either make sure they are all loaded together with the parent record, or specify that the relationship is async (`belongsTo({ async: true })`)
```

### Versions

```cli
ember-source@3.20.4
ember-cli@3.20.0
ember-data@3.20.0 
```

**Comment by arenoir** [comment]
I have been unable to reproduce this in the ember-data test suite.  It is occurring in my application quite frequently but not constantly.  

Upgrading to 3.22.0-alpha.0 seems to fix it.

**Comment by arenoir** [comment]
I'm closing this until I can reproduce it in the ember-data test suite.  After upgrading my application to the latest ember and ember-data it is better but still happening every once in a while.

**Comment by arenoir** [comment]
Post mortem of being off in the weeds. 

The root cause of my issue was there were `job` records  loaded into the store that did not include their respective relationships `address`. These invalid records were loaded when the application first rendered.  

The issue arose when rendering  a list of `jobs` via the `store.peekAll('job')` method after querying for additional `job` records with the included `address`.  Its obvious now that the `peekAll` method returned the incomplete records.  

Incidentally the query loaded a payload that included the same records that were incomplete. So when inspecting the error and looking at the payload I incorrectly concluded ember-data was failing to load the payload.  

I apologize for being so quick to blame ember-data. 

@igorT what do you think about throwing an exception when loading payload that is missing the required included records?

**Comment by arenoir** [comment]
@igorT Nvm that is a bad idea the current implementation of throwing the error on access is best.  Otherwise we lose the power to load relationships at will.

**Comment by igorT** [comment]
@arenoir thanks for the quick update!
Is there a way that the error message could have been more useful/have given you more context to debug this?

 fwiw the reasoning for originally arguing for async relationships by default was that otherwise you might have random and hard to track problems

**Comment by arenoir** [comment]
@igorT reading the message in hindsight it makes total sense.  I do think it could be more verbose regarding how to fix it. Saying to either load the records together or change the relationship to async implies that it is only an issue with the payload.  Mentioning the record is already in the store would be helpful.  

Maybe something like:

```
You looked up the 'address' relationship on a 'customer' with id 8 but the associated record has yet to be loaded.  Either load the relationship with the parent, load it manually, or check if the relationship is loaded using "some method" before accessing it.  
```
