### ISSUE TITLE
Issues detected with ember array proxies with Ember 3.20.4

### ISSUE THREAD

**Issue by igorT** [emberjs/data#7281]
Tracking issue for https://github.com/emberjs/ember.js/issues/19105 https://github.com/emberjs/ember.js/issues/19101 cc @rwjblue @pzuraq

**Comment by igorT** [comment]
Fix in https://github.com/emberjs/ember.js/pull/19111

**Comment by snewcomer** [comment]
closing as we haven't had any reported issues since.
