### ISSUE TITLE
Adapter import inconsistencies

### ISSUE THREAD

**Issue by maxwondercorn** [emberjs/data#7299]
The api's document four adapters type:  base, JSONAPI, JSON and REST.  Generating an `application` adapter creates an adaptor importing from the JSONAPIAdapter
```
# ember g adapter application

// generated import statement
import JSONAPIAdapter from '@ember-data/adapter/json-api';
```

Generating any other adapter (data 3.16) creates:
```
# ember g adapter post

// generated import
import ApplicationAdapter from './application';
```
which I assume is the base adapter but it's documented in the API as:

```javascript
import Adapter from '@ember-data/adapter';
```
(There are one or two api examples using the import from `./application`). The blueprint should be generating the ` @ember-data/adapter'. 

Additionally, the guides [document](https://guides.emberjs.com/release/models/customizing-adapters/) that adapters  default to `JSONAPIAdapter` when a new one is generated

It might be nice to have an optional argument to specify the adapter type. Default would be JSONAPI and you would specify others as needed.  I'm not sure what the `--base-class` argument  is used for but it does not seem to work in this manner.

As I indicated this issue is with Data 3.16 but I seem to remember that the `./application` imports were also being generated in Data 3.12

**Comment by runspired** [comment]
generating from `./application` by default for anything other than the application adapter seems to be correct to me. I believe there already is a base class argument (something like `--base-class`)
