### ISSUE TITLE
Removing error from Model.errors is not autotracked in ember 3.20.5

### ISSUE THREAD

**Issue by andreyfel** [emberjs/data#7310]
Originally I've opened the issue within Ember itself https://github.com/emberjs/ember.js/issues/19097, but the fix was done on the ED side https://github.com/emberjs/data/pull/7273.

It seems that the issue wasn't fixed completely as the errors are not re-rendered when I do `model.errors.remove(attr)`.
See the integration test in the reproduction repo https://github.com/andreyfel/ember-data-errors-autotracking-bug.

**Comment by andreyfel** [comment]
cc: @pzuraq and @igorT who were involved in the first fix.

**Comment by igorT** [comment]
Thanks for the report, can you please make a reproduction PR that we can test against, that would be super helpful

**Comment by andreyfel** [comment]
@igorT the test is in the separate repo https://github.com/andreyfel/ember-data-errors-autotracking-bug. Do you want to have it as a PR for ember-data repository?

**Comment by igorT** [comment]
That would be great

**Comment by andreyfel** [comment]
Created PR with reproduction https://github.com/emberjs/data/pull/7313

**Comment by andreyfel** [comment]
@snewcomer @igorT thank you for this fix!
Can you guys make a patch release for 3.20.* with this fix?

**Comment by igorT** [comment]
@andreyfel I think @snewcomer is planning to
