### ISSUE TITLE
ED + Octane: ManyArray inside POJO is not tracked

### ISSUE THREAD

**Issue by urbany** [emberjs/data#7311]
### Reproduction
https://ember-twiddle.com/26f68cde34e59c46c0c4b8c47d808c42

### Description
Hi, when I sort/filter a ManyArray inside a POJO (check the route) it is not autotracked when adding new elements (in tiwddle: `sortedServices`). If instead I access the ManyArray directly from another model it works correctly (in tiwddle: `sortedThroughBusinessServices`). If I use the old computed sort helper it also works (in twiddle: `sortedServicesComputed`)

@pzuraq said on Discord I should create the issue in ED and also this:
> objectAt is not entangling properly..

Thanks in advance!

### Versions

The twiddle does not have the latest version of ember-source but i tried this in my project today with latest version of cli, source and data.

```cli
ember-cli@3.21.0
ember-data@3.21.0
ember-source@3.21.1
```

**Comment by urbany** [comment]
I just noticed that if a add `get(this.model, 'services.length')` to the sortedServices getter it starts receiving updates of new services added to the ManyArray.

**Comment by igorT** [comment]
@pzuraq is this similar to the bug you were already working on

**Comment by urbany** [comment]
Hi, sorry to bother I know you guys help on your free time, but anyway i can make this easier for you to check if at least it is a bug? Thanks again!

**Comment by pzuraq** [comment]
I haven't had time to dig in, but all that needs to happen is that we should call `get(this, '[]')` at least once whenever the values in the array are accessed. I'm not sure what the best place would be to add that code.
