### ISSUE TITLE
"Maximum call stack size exceeded" on set and deleteRecord  in one to one relationship.

### ISSUE THREAD

**Issue by Baael** [emberjs/data#732]
When using RESTadapter in one to one relationship:

``` javascript
App.Post = DS.Model.extend
  author:   DS.belongsTo('App.Author')

App.Author = DS.Model.extend
  post:      DS.belongsTo('App.Post')

author = App.Author.find(1) 
post = author.get('post')
```

post and author are valid objects

``` javascript
post.deleteRecord()
```

or 

``` javascript
author.set('post',null)
```

returns: `RangeError: Maximum call stack size exceeded`

suspect:
https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/model/model.js#L135
:)

Trying to fix and provide tests, however for now I wasn't able to find it in issues, also newest revision of ember-data has same problem.

**Comment by plicjo** [comment]
I had this issue because of `EmbeddedRecords`.

I solved it with help from [this thread](https://discuss.emberjs.com/t/save-gives-ember-debug-js-6838-uncaught-rangeerror-maximum-call-stack-size-exceeded/11130).

It does not appear to be exactly relevant to the OP, but it's related.

> The model has a lot of relations so I have changed in the serializer the attributes from embedded: 'always' to serialize: 'ids',deserialize: 'records'
