### ISSUE TITLE
Adapter Documentation is missing 5th parameter

### ISSUE THREAD

**Issue by Benjy1979** [emberjs/data#7334]
Hi, I was asked to resubmit this in ember data rather than the guides documentation. 

For query() and queryRecord() there is a fifth parameter (adapterOptions) that are not conveyed by the documentation.

https://api.emberjs.com/ember-data/3.21/classes/Adapter/methods/queryRecord?anchor=query

**Comment by snewcomer** [comment]
Hi @Benjy1979.  Is this something you would like to submit a PR for?  I'm happy to do it as well.

**Comment by Benjy1979** [comment]
I'm on my lunch, I will try.

**Comment by Benjy1979** [comment]
I've created my first ever pull request to the code (once I realised the documentation comes from the code commenting - I hope).
https://github.com/emberjs/data/pull/7341
