### ISSUE TITLE
resetAttributes() not calling rolledBack()

### ISSUE THREAD

**Issue by BlueRaja** [emberjs/data#7344]
### Reproduction

Call `resetAttributes()` on any model with a `rolledBack()` function

### Expected Results

`rolledBack()` is called automatically, as it's listed as [one of the model events](https://api.emberjs.com/ember-data/2.18/classes/DS.Model/events/ready?anchor=ready)

### Actual results

It's not called.

### Versions

```cli
ember-source@3.16.8
ember-cli@3.16.2
ember-data@3.16.9
```

**Comment by runspired** [comment]
We have tests that show it is called correctly, mind sharing your setup a bit more?

**Comment by BlueRaja** [comment]
Unfortunately I no longer have access to the code
