### ISSUE TITLE
[ember-data@3.22.0] Error on build: Imported DEPRECATE_NAJAX ... which is not a supported flag

### ISSUE THREAD

**Issue by urbany** [emberjs/data#7361]
Hi everyone, after updating from fom previous stable to 3.22.0 I'm seeing this error when building:
```
Build Error (broccoli-persistent-filter:Babel > [Babel: @ember-data/adapter]) in @ember-data/adapter/rest.js

/my-project/@ember-data/adapter/rest.js: Imported DEPRECATE_NAJAX from @ember-data/private-build-infra/deprecations which is not a supported flag.
```
Also have latest stable ember-cli.

Thanks in advance

**Comment by urbany** [comment]
Found this similar bug https://github.com/emberjs/data/issues/7221#issuecomment-669872966

`rm -rf node_modules && npm install` solved the problem, you can close this issue if you think everything is fine

**Comment by rwjblue** [comment]
FWIW, this is due to caching with `esm` (which we are using to discover these feature and deprecation flags). We disabled that caching over in https://github.com/emberjs/data/pull/7322, but I don't know if that has landed in 3.22.

@snewcomer - Do you recall?

**Comment by snewcomer** [comment]
Hi all!  There are two things that would still result in this error after bumping to 3.22 (`esm` cache is disabled)...

1.  If you update from a version that has the `esm` cache enabled, you will see this error.
2. If you are updating from `release` (3.21 `esm` cache disabled) and never blew away your node_modules and subsequently upgraded to a release with a new flag, you will see this error.

Glad you got around the error.

**Comment by srsgores** [comment]
Running `npm ci` fixed this for me.
