### ISSUE TITLE
Asserts thrown in `didSaveRecord` don't put the record in the correct rejected state

### ISSUE THREAD

**Issue by igorT** [emberjs/data#7371]
If you hit https://github.com/emberjs/data/blob/1428e26cb49181bf38cc62b98eaa40d255ef7d11/packages/store/addon/-private/system/core-store.ts#L2603, the record will end up in a half broken state, rather than putting it in a correct error state, the way it would if the request rejected earlier in the pipeline.

**Comment by runspired** [comment]
This is potentially resolved due to recent refactoring
