### ISSUE TITLE
Using a belongsTo relationship in a LinkTo doesn't work

### ISSUE THREAD

**Issue by mansona** [emberjs/data#7380]
### Description

I noticed this while working on a [recent change in empress-blog](https://github.com/empress/empress-blog/pull/96) to try and workaround an issue where we [can't rely on the sort order of hasMany relationships](https://discuss.emberjs.com/t/manual-pagination-in-ember-data-relationships/18087)

Essentially this issue is quite simple to explain, and I have a feeling that it is one of those issues that quite a few people might be facing but because the workaround is so simple it likely gets overlooked. In my case it would end up being a breaking change to empress-blog and something that bleeds into the empress-blog-template ecosystem 🙈  so I would prefer to avoid the "workaround" of saying "just pass the id into the link". 

The situation is that I have a post object that has a relationship to `primaryTag` and I want to link to the "tag page" of the primaryTag (showing all other content with this same tag) and I try to do something like this: 

```
<LinkTo @route="tag" @model={{@model.tag}}>{{@model.tag.title}}</LinkTo>
```

but when you do that you get the following in the console: 

```
Uncaught Error: Assertion Failed: You attempted to generate a link for the "tag" route, but did not pass the models required for generating its dynamic segments. You must provide param `id` to `generate`.
```

### Reproduction

I created a github repo with a simple reproduction, and a PR that "introduces the bug" to the main branch 😂 

https://github.com/mansona/ember-data-bug-reproduction/pull/1

It is being deployed to netlify so you can see it doesn't work if you check the preview deploy 👍 

### Versions

```cli
➜  ember-data-relationship-link git:(main) npm list ember-source && npm list ember-cli && npm list ember-data
ember-data-relationship-link@0.0.0 /Users/mansona/temp/ember-data-relationship-link
└── ember-source@3.18.1

ember-data-relationship-link@0.0.0 /Users/mansona/temp/ember-data-relationship-link
└── ember-cli@3.18.0

ember-data-relationship-link@0.0.0 /Users/mansona/temp/ember-data-relationship-link
└── ember-data@3.18.0
```

Note: I have tested this (using ember-try) on lots of other versions of ember and ember-data, this test app just seems a little behind. Let me know if you would like me to test this in a more recent ember-data 👍

**Comment by snewcomer** [comment]
@mansona Hi Chris!  Thx for the issue.  This looks to be a bug in serializing Ember `routeInfos` when the target is a `Proxy` where `key in target` fails.  I put up a quick PR (will come back and check the tests before my comp shuts down).

https://github.com/emberjs/ember.js/pull/19298
