### ISSUE TITLE
peekRecord dont work in 3.21, 3.22

### ISSUE THREAD

**Issue by eduscrakozabrus** [emberjs/data#7381]
### Reproduction

this is dont work
    let chat = this.store.peekRecord("record", this.args.record);

but this is work:
    this.store.peekAll("record").mapBy("id");
    let chat = this.store.peekRecord("record", this.args.record);

### Description

only if call     this.store.peekAll("record").mapBy("id") before peekRecord work
### Versions

3.21, .3.22

**Comment by snewcomer** [comment]
@eduscrakozabrus Hi!  Do you have a reproducible example for us to test? I want to make sure we have the context correct before digging into the issue.

**Comment by igorT** [comment]
Hi @eduscrakozabrus , I am going to close this for now, please reopen if you manage to get more context/reproduce the problem.
