### ISSUE TITLE
3.23

### ISSUE THREAD

**Issue by jcardali** [emberjs/data#7400]
Ember (and supposedly ember-data) 3.23 have been released, but the 3.23 branch isn't in master yet. Is that expected to change soon or is there something holding it up?

**Comment by snewcomer** [comment]
@jcardali Hi! I'm seeing the commits that were including in 3.23 in the master branch.  Is there a specific PR you see missing?

https://github.com/emberjs/data/commits/v3.23.0

**Comment by jcardali** [comment]
I would expect to see the changelog updated in master and a release for 3.23.0

**Comment by snewcomer** [comment]
Ah yep.  I've been eyeing this change the past month.  I was looking to make sure this was up to date once we release 3.24.0 this week.   @igorT 

Thanks for the issue!
