### ISSUE TITLE
PATCH requests using a related links URL

### ISSUE THREAD

**Issue by ziali088** [emberjs/data#7404]
### Description

I want to patch a relationship by making a request to the URL provided in the `links` object in the resources relationships:

```json
{
  "type": "appointments",
  "id": "1",
  "attributes": {},
  "relationships": {
    "status": {
      "links": {
        "self": "/api/appointments/1/relationships/status",
        "related": "/api/appointments/1/status"
      },
      "data": {
        "type": "statuses",
        "id": "1"
      }
    }
  }
}
```

Given the above I want to issue the `PATCH /api/appointments/1/relationships/status` request.

```js
// model/appointment.js
import Model, { attr, belongsTo, hasMany } from '@ember-data/model';
export default class AppointmentModel extends Model {
  @belongsTo('status') status;
};
```

```js
// model/status.js
import Model, { attr, hasMany } from '@ember-data/model';
export default class StatusModel extends Model {
  @hasMany('appointment') appointments;
  @attr('string') name;
}
```

What I'm trying to do is:

```js
const appointment = this.store.findRecord('appointment', id);
appointment.status = newStatus;
return appointment.get('status').save();
```

However the above returns an error saying `save() is not a function` on the status object (the status object is a ember Proxy object).

I know I can do:

```js
const status = this.store.peekRecord('status', appointment.get('status.id'));
return status.save();
```

But that is not what I want to request. That would make a request to `/api/statuses/1`, which has no context of an appointment, the primary resource.

I also know that I can just save the appointment and get the relationship updates, but that would make the `links` I've setup completely useless. I want to be able to request the links I've setup for the relationships.

Essentially I want to be able to follow this part of the JSON:API spec: [Updating Relationships][1].

How can I make a `save()` request to a relationship which uses the relationship links?

  [1]: https://jsonapi.org/format/#crud-updating-relationships
### Versions

```cli
ember-source@3.23.1
ember-cli@3.23.0
ember-data@3.23.0
```

**Comment by snewcomer** [comment]
> const appointment = this.store.findRecord('appointment', id);

@ziali088 👋  `findRecord` will return a Promise Proxy object.  Just as a first check, did your original code above take into account this async behaviour?

```
const appointment = await this.store.findRecord('appointment', id);
```

**Comment by ziali088** [comment]
@snewcomer hello, yes it does. I forgot the await when writing the example but I use it in my code

**Comment by snewcomer** [comment]
@ziali088 `belongsTo` relationships are async by default. `appointment.status` will return a Promise proxy.  So the following should work...

```
const appointment = await this.store.findRecord('appointment', id);
appointment.status = newStatus;
let status = await appointment.status;
status.save();
```

**Comment by ziali088** [comment]
Hi @snewcomer,

That will make a request to `/api/statuses/:id`, which is not what I'm after. That is making a request to update the `status` itself, which is not what has changed - it's the appointment that has changed its status. Server side, this is essentially updating a foreign key column, which is why status is a relationship.

I'm currently doing this to update the status:

```js
const appointment = await this.store.findRecord('appointment', id);
appointment.status = newStatus;
appointment.save();
```

Which is making a PATCH request to `/api/appointments/:id`. I'm fine doing this, however it means that on the server side this endpoint becomes the single endpoint that deals with updating the appointment attributes as well as any relationships. I have  other relationships for this model which are has-many relationships, so I'm imagining how that endpoint will become very cluttered.

My ideal workflow would be:

```js
const appointment = await this.store.findRecord('appointment', id);
appointment.status = newStatus;
appointment.status.save();
```

Where calling the `save` method on the relationship will execute a PATCH request to `/api/appointments/:id/relationships/status`, where I can update just that relationship.

Currently, if I try `appointment.status.save()` it returns an error saying 'save is not a function', so I'm guessing there currently isn't a way to make the above request. If you're aware of how to make a PATCH request to the following please let me know:

```json
{
  "type": "appointments",
  "id": "1",
  "attributes": {},
  "relationships": {
    "status": {
      "links": {
        **"self": "/api/appointments/1/relationships/status",**
        "related": "/api/appointments/1/status"
      },
      "data": {
        "type": "statuses",
        "id": "1"
      }
    }
  }
}
```

**Comment by snewcomer** [comment]
Ah ok thx for the explanation. So we have two problems.

> if I try appointment.status.save() it returns an error saying 'save is not a function'

1. I think we have resolved this problem.  Relationships by default return a promise proxy (`{ async: true }`).  That is why `save` does not exist yet.

2. I believe links are preferred over data if provided when `finding` a resource.  However, updating isn't something that comes out of the box.  I think you have hand roll with `adapterOptions` and `adapter.urlForUpdateRecord`.

```
// call site
let status = await appointments.status;
status.save({ adapterOptions: { link: model.relationships.status.links.related } });
```

```
// app/adapters/status.js
import JSONAPIAdapter from '@ember-data/adapter/json-api';

export default class extends JSONAPIAdapter {
  urlForUpdateRecord(id, modelName, snapshot) {
    let originalUpdateURL = super.urlForUpdateRecord(...arguments);
    let { adapterOptions } = snapshot;
    if (adapterOptions?.link?) {
      return adapterOptions.link;
    }

    return originalUpdateURL;
  }
}
```

**Comment by ziali088** [comment]
Yeah, I also found that the relationship links were being used only for GET requests, was expecting the same for the other http methods.

I'll use the adapter options then, thanks for your help
