### ISSUE TITLE
`coalesceFindRequests: true` regression when using classic `RESTAdapter`

### ISSUE THREAD

**Issue by nag5000** [emberjs/data#7438]
### Reproduction

- create "classic" RESTAdapter in `app/adapters/application.js`:
  ```
  export default RESTAdapter.extend({
      coalesceFindRequests: true
  });
  ```
- Run app
- Check `lookup('adapter:application').coalesceFindRequests` at runtime: it's `false`. Expected `true`.

### Description

I have upgraded ember-data from 3.10 to 3.24. And now `coalesceFindRequests: true` doesn't work.
It seems that `coalesceFindRequests` is overridden in constructor: 
![image](https://user-images.githubusercontent.com/4932134/111203613-0d2e2680-85e7-11eb-8c03-fb0ff0c694bb.png)

### Versions

ember-data 3.10 - `coalesceFindRequests: true` works.
ember-data 3.24 - `coalesceFindRequests: true` doesn't work.

**Comment by snewcomer** [comment]
Thanks @nag5000 for the detail issue!  I've done some work in this area.  I'll look today to see what we can do.

**Comment by snewcomer** [comment]
@nag5000 This will be fixed soon.  I'm just waiting for a few PRs to go in to fix the test suite.  Perhaps you already have, but if you are able to, you can convert your adapter to class syntax to fix this error.  Lmk if you have any other questions!

**Comment by nag5000** [comment]
@snewcomer Good to hear, thanks!
I've temporarily fixed this with the `init()`, but I'm going to switch to class syntax soon.

**Comment by igorT** [comment]
@nag5000 we are unblocked and actively working on the fix
