### ISSUE TITLE
wrong JSONAPISerializer imports

### ISSUE THREAD

**Issue by rinoldsimon** [emberjs/data#7479]
### Description

All the `JSONAPISerializer` imports over here https://api.emberjs.com/ember-data/3.26/classes/JSONAPISerializer/methods/serialize?anchor=serialize points to `@ember-data/serializer/json`.

It should be from `@ember-data/serializer/json-api` ?
### Versions
```
"ember-data": "3.26"
```

**Comment by runspired** [comment]
@skaterdav85 this could be an easy one for you

**Comment by skaterdav85** [comment]
@runspired thanks! will work on it this weekend.
