### ISSUE TITLE
Convert to new type import syntax

### ISSUE THREAD

**Issue by runspired** [emberjs/data#7536]
Currently we enforce type-only imports be declared using the following syntax:

```ts
type Foo = import("./path").default;
type Boo = import("./path").Bar;
```

This has a few disadvantages

1) Some type information is lost
2) The syntax can be a bit unweidly
3) Named imports each require their own line

Fortunately there is a new type-only import syntax we can use:

```ts
import type Foo { Bar } from './path';
```

We should be able to do an automatic conversion by [removing our lint rule](https://github.com/emberjs/data/blob/master/packages/unpublished-eslint-rules/src/rules/prefer-type-only-import.js) and configuring the one that [eslint typescript now provides](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/consistent-type-imports.md)

**Comment by adarshnanwani** [comment]
Hi. I have never contributed before. Can I take this up?

**Comment by runspired** [comment]
@adelcambre that would be awesome!

**Comment by adarshnanwani** [comment]
Great! Thank you!

**Comment by runspired** [comment]
@adarshnanwani how is it going? need any help?
