### ISSUE TITLE
Confusing error message if `Model` is imported as a named export instead of default

### ISSUE THREAD

**Issue by pgengler** [emberjs/data#7565]
### Reproduction
https://ember-twiddle.com/211fe28d7f48aedf03bb07ab7464f9f5?openFiles=models.thing%5C.js%2C (check the browser console for the error)

### Description
If `Model` is imported like this:
```js
import { Model } from '@ember-data/model';
```

instead of as a default export (`import Model from '@ember-data/model';`), then the result builds correctly but fails to work, with the confusing runtime error message "Uncaught TypeError: Class extends value undefined is not a constructor or null" in the browser console. (For builds when IE11 is included in `config/targets.js`, the error message is different but also confusing.)

### Versions

Happens with both Ember Data 3.18 in ember-twiddle and 3.27.1 locally.

Run the following command and paste the output below: `yarn list ember-source && yarn list ember-cli && yarn list --pattern ember-data`.

```cli
$ yarn list ember-source && yarn list ember-cli && yarn list --pattern ember-data
yarn list v1.22.10
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ ember-source@3.27.2
✨  Done in 0.95s.
yarn list v1.22.10
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ ember-cli@3.26.1
✨  Done in 0.98s.
yarn list v1.22.10
├─ @ember-data/adapter@3.27.1
├─ @ember-data/canary-features@3.27.1
├─ @ember-data/debug@3.27.1
├─ @ember-data/model@3.27.1
├─ @ember-data/private-build-infra@3.27.1
├─ @ember-data/record-data@3.27.1
├─ @ember-data/rfc395-data@0.0.4
├─ @ember-data/serializer@3.27.1
├─ @ember-data/store@3.27.1
├─ babel-plugin-ember-data-packages-polyfill@0.1.2
└─ ember-data@3.27.1
✨  Done in 0.98s.
```

**Comment by runspired** [comment]
This is where using typescript or eslint rules for imports will help you. There's not much we can do about the build tool in use not erring when it should have.

@rwjblue may have some thoughts, but generally I think this is a "can't fix".

**Comment by pgengler** [comment]
Yeah I realized when I was trying out some stuff later that it's more of the build tool and not ember-data (I had thought it was maybe exporting something weird as the named `Model` export). [As an aside, unrelated to ember-data, I'm finding the tooling around imports/exports less helpful than it used to be - you can import something that's not exported by a module and not get any errors; I could have sworn that at some point there was an error message about that.]

It's not a "fix", per se, but maybe a workaround could be to export the default thing as a named export too?

e.g., for https://github.com/emberjs/data/blob/master/packages/model/addon/index.ts#L40
```diff
-export { Model as default, attr, belongsTo, hasMany } from './-private';
+export { Model as default, Model, attr, belongsTo, hasMany } from './-private';
```

This seems to work but I don't know if it's just a quirk of the build tooling and not something that is supposed to work, or if it's worth the effort to make that sort of change.

I might have a look at how feasible it is to write an eslint for this.

Thanks!

**Comment by runspired** [comment]
@pgengler exporting multiple times leads to fairly hard to manage expectations and learning experiences on top of making tree-shaking somewhat more difficult. I definitely don't think we should add an extra named re-export for default exports.

For non-typescript users there's an existing rule that by default ignores node_modules, which is probably why this doesn't feel helpful and which is probably not able to be configured the best for ember apps to be helpful given how ember addons work today: https://github.com/benmosher/eslint-plugin-import/issues/765#issuecomment-316032288. It does come with configuration options that could potentially be tweaked to make the imports resolvable: https://github.com/benmosher/eslint-plugin-import/blob/master/README.md#settings

**Comment by runspired** [comment]
I'm going to close this since this is a tooling issue and not an ember-data issue, but I opened https://github.com/ember-cli/eslint-plugin-ember/issues/1223 as one potential tooling upgrade we could do.
