### ISSUE TITLE
Some usages of assert are incorrectly specifying a third param

### ISSUE THREAD

**Issue by runspired** [emberjs/data#7580]
For instance:

```ts
    assert(this.warnMessageForUndefinedType(), !isNone(resourceHash.type), {
      id: 'ds.serializer.type-is-undefined',
    });
```

This has the effect of making typescript think the remaining code is unreachable, because typescript treats too-many args as matching the first overload signature, which in this case is a `never`

[Demo](https://www.typescriptlang.org/play?ssl=33&ssc=1&pln=1&pc=1#code/GYVwdgxgLglg9mABAQwM6oKYCcoAoAmGqEAXIqlFjGAOYCUZYGAbtgNwBQoksCK62PIWJkKVWgBpEUIlDLgA1mDgB3MA36YcqabM7do8JGi1CipcpWo0pMigH55YJavVkTgnXaiIA3h0RAxBhgRFwAQm86PwCgwKgACyxVRGEITjiAXw5srnBDPghkABtigEZcaP84jxxcAANgODh6ugygiARUOGKMADpiuBpcAHIsDGQIBOQAI16RtsQAeiXgnWUfccnpuYx+RBU9gFtkKCnpBL2mVixyGBowU5BxvpyOPJ4jRCLSgCZKmI1AR1RrNeq2LAgDBtWKBTpgbq9AZDUZbKazeaLFZrRBona9faHRAnM4JC57RTKNR3B5PF5vD4FJA-YoAZgB1SCtTwoJaUmAJUwMLi8MR-UGwzGE3RuwWbGWqxg6zgm2l+L2aGkOhcKh0RO5ugoDIMvGZJWKABZcFMMBAFGQZs1esh1ICucCeU0+d9LnapL5MsKOl0euKUVLthiMHKFTiNri1VH9lAdJgMEcvHBpFsfBgAB6UZAoLA0LyXcjII4azNZ4AYFTF0uIZ34azSLOJK4sbCIOA3QbIfDE05TayvXImr4sgCsHNhmkEDS94OzUP9gfacJDSIlqMTsqxiuVqsju2TqYw6cz2YmuYLWCLyBLZb2qEr1fbtfrjZ0LbbUA7ctrh7PtsAHIcSVHWhxw4IA)

I don't think passing this third arg to assert has ever worked, though it is common enough maybe it did at some point. It certainly does not work anymore: 

https://github.com/emberjs/ember.js/blob/79f130f779a58969b98d079acf7d0e83c81dae63/packages/%40ember/debug/index.ts#L165-L169

cc @chriskrycho for type-signature fun (also cc @rwjblue, any context on why we maybe thought a third arg worked here for quite a long time?)

**Comment by runspired** [comment]
At least some of these are resolved by #7585

**Comment by rwjblue** [comment]
RE: `assert(message, test, options)`: I do think it would be a good API for us to support (we could tag the thrown error with those options, making it somewhat easier to see what addon did the assertion), but its definitely a new API / RFC.

**Comment by runspired** [comment]
there are no longer any asserts with a third option
