### ISSUE TITLE
Should `normalizeErrorResponse` set error `status` as a string?

### ISSUE THREAD

**Issue by nlfurniss** [emberjs/data#7590]
In the rest adapter, `normalizeErrorResponse` sets the `status` on the [error as a string](https://github.com/emberjs/data/blob/master/packages/adapter/addon/rest.ts#L1278). This seems odd, as all other instances of status in the adapter expect a number, and I believe most devs would as well.

Changing this seems like a breaking change, but happy to make the change if there isn't a good reason to keep it a string.

**Comment by snewcomer** [comment]
Thank you for pointing this out!  So this luckily, the stringified numeric HTTP status code aligns with how JSON-API specifies the errors array should be.

> status: the HTTP status code applicable to this problem, expressed as a string value.

Overall, I agree with your initial thought.  However, this may have been a standard they finished on early in the process

https://jsonapi.org/format/#errors

**Comment by nlfurniss** [comment]
Thanks, would not have guessed!

how would you feel about a PR adding a comment relaying the above info?
