### ISSUE TITLE
3.28: Awaiting async relationships does not work anymore

### ISSUE THREAD

**Issue by Turbo87** [emberjs/data#7684]
### Reproduction

- clone https://github.com/rust-lang/crates.io/pull/3852
- `yarn install`
- `yarn start:live`
- http://localhost:4200/tests/?mirageLogging&filter=visiting%20a%20crate%20page%20from%20the%20front%20page
- observe that `versions = await crate.get('versions');` resolves before the network request has been performed

### Description

Just like in previous Ember Data releases I expected to be able to `await` async relationships to be able to wait until the content has loaded before continuing, but this appears to have broken with v3.28 by resolving before the network request has resolved.

### Versions

Run the following command and paste the output below: `yarn list ember-source && yarn list ember-cli && yarn list --pattern ember-data`.

```cli
❯ yarn list ember-source && yarn list ember-cli && yarn list --pattern ember-data
yarn list v1.22.4
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ ember-source@3.28.0
✨  Done in 1.21s.
yarn list v1.22.4
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ ember-cli@3.28.0
✨  Done in 0.90s.
yarn list v1.22.4
├─ @ember-data/adapter@3.28.0
├─ @ember-data/canary-features@3.28.0
├─ @ember-data/debug@3.28.0
├─ @ember-data/model@3.28.0
├─ @ember-data/private-build-infra@3.28.0
├─ @ember-data/record-data@3.28.0
├─ @ember-data/rfc395-data@0.0.4
├─ @ember-data/serializer@3.28.0
├─ @ember-data/store@3.28.0
├─ babel-plugin-ember-data-packages-polyfill@0.1.2
└─ ember-data@3.28.0
✨  Done in 0.90s.
```

**Comment by igorT** [comment]
Thanks for the detailed issue report, it seems like a few people have run into this, we are working on a fix in https://github.com/emberjs/data/pull/7691
