### ISSUE TITLE
optional root for RESTAdapter

### ISSUE THREAD

**Issue by necronet** [emberjs/data#771]
Hello I had this problem when implementing the RESTAdapter, since I do not send the type as a parameter of my services calls as ember-data currently does:

```
{"person":{"atribute1":"jjj","atribute2":"jjj"}}
```

Is more like

```
{"atribute1":"jjj","atribute2":"jjj"}
```

I did not find any easy way to override this behaviour so I had to reimplement the same code of the Adapter createRecord but without the root. I am not a mastering in front-end so might be a good idea to put a jsonWithRoot or some similar property to RESTAdaper to easly handle this case.

Here is the Stackoverflow 

http://stackoverflow.com/questions/15126081/ember-data-customs-serializing

**Comment by jiminikiz** [comment]
> In most cases you really should have a rooted JSON, as that gives you much more flexibility as you develop your API.

No. Please just stop.
