### ISSUE TITLE
After destroyRecord(), references to objects obtained through belongsTo relationships no longer work

### ISSUE THREAD

**Issue by pgengler** [emberjs/data#7711]
### Reproduction
[This ember-twiddle](https://ember-twiddle.com/83ed7772daf1e60dc48f216a6674b5b6?openFiles=components.my-component%5C.js%2C&route=%2F1) can be used to reproduce the problem; I have changed the `twiddle.json` to use ember-data 3.28.3. You can change the ember-data version to anything lower that that to see the "working" behavior.

#### Steps to reproduce using the twiddle
* Click on any of the links on the displayed `"B" index` route.
* Click the "Delete" button.
* Note that you remain on the same route and there's an error in the console:
  > Uncaught (in promise) Error: Assertion Failed: Cannot create a new tag for `<(unknown):ember175>` after it has been destroyed.
* The expected behavior is that that no error occurs and you are returned to the `"B" index` route.

### Description
If I have saved a reference to an ember-data model via a `belongsTo` relationship on object `A`, and then call `destroyRecord` on object `A`, I am no longer able to use the saved reference. My particular use case is that when I delete a child model, I want to redirect back to the index route for the parent model, e.g.,
```js
const child = this.args.child;
const parent = child.parent;
    
await child.destroyRecord();
this.router.transitionTo('parent', parent.get('id'));
```

This worked in ember-data up to and including 3.27.

### Versions

Run the following command and paste the output below: `yarn list ember-source && yarn list ember-cli && yarn list --pattern ember-data`.

```cli
yarn list v1.22.10
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ ember-source@3.28.1
✨  Done in 0.91s.
yarn list v1.22.10
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ ember-cli@3.28.0
✨  Done in 0.93s.
yarn list v1.22.10
├─ @ember-data/adapter@3.28.3
├─ @ember-data/canary-features@3.28.3
├─ @ember-data/debug@3.28.3
├─ @ember-data/model@3.28.3
├─ @ember-data/private-build-infra@3.28.3
├─ @ember-data/record-data@3.28.3
├─ @ember-data/rfc395-data@0.0.4
├─ @ember-data/serializer@3.28.3
├─ @ember-data/store@3.28.3
├─ babel-plugin-ember-data-packages-polyfill@0.1.2
└─ ember-data@3.28.3
✨  Done in 0.88s.
```

**Comment by runspired** [comment]
Likely this is exactly the issue here. We had a bug previously in which destroyRecord was not cleaning up the destroyed record, now it does. So the promise proxy that the child owns would also be cleaned up. You'll want to await the parent or access the parentId prior to destroying the child if you want to work with it.

As this is a damned either way scenario (we fixed a bad long-term bug, but that bug made this pattern unfortunately possible) I'm not sure there's a path forward here other than to tell you how to fix it.
