### ISSUE TITLE
Cleanup for 4.0 release

### ISSUE THREAD

**Issue by snewcomer** [emberjs/data#7724]
- [x] Remove feature flag app code that is enabled - https://github.com/emberjs/data/blob/master/packages/canary-features/addon/default-features.ts
- [x] Object.assign deprecation - https://github.com/emberjs/data/pull/7722
- [x] Drop IE11 from CI suite and build
- [x] [record.toJSON](https://deprecations.emberjs.com/ember-data/v3.x/#toc_record-toJSON)

Work in Progress.  If you know of other items to add (there are many more), let me know in discord or comment here!

**Comment by SergeAstapov** [comment]
@snewcomer [`record.toJSON`](https://deprecations.emberjs.com/ember-data/v3.x#toc_record-toJSON) is still in the codebase and deprecation targets `4.0.0` so should be added to the list
