### ISSUE TITLE
hasMany fails if the parent model is requested simultaneously in separate places (tested for links)

### ISSUE THREAD

**Issue by tschoartschi** [emberjs/data#7731]
### Reproduction
- a PR linking to this issue with a failing test showing the issue: since I do not know the root cause of the problem I'm not able to submit a failing test but I hope that the github repository helps
- a github repository: [https://github.com/tschoartschi/ember-data-3-28-has-many-regression](https://github.com/tschoartschi/ember-data-3-28-has-many-regression)

### Description

I think it's a regression from version 3.27.1 to 3.28. In 3.27.1 everything works as expected but in 3.28 our app breaks. I created a detailed description in the github repository. You can read it in the [README.md](https://github.com/tschoartschi/ember-data-3-28-has-many-regression/blob/main/README.md).

I think the new version has problems if you try to fetch a model simultaneously in separate places in the app. I tried to mimic this behavior with an `Ember later` call.

I only tried it with `async` relationships which are specified as `links` in the returned JSON of the API because this is how our backend returns that data.

### Versions

Run the following command and paste the output below: `yarn list ember-source && yarn list ember-cli && yarn list --pattern ember-data`.

```cli
├─ @ember-data/adapter@3.28.3
├─ @ember-data/canary-features@3.28.3
├─ @ember-data/debug@3.28.3
├─ @ember-data/model@3.28.3
├─ @ember-data/private-build-infra@3.28.3
├─ @ember-data/record-data@3.28.3
├─ @ember-data/rfc395-data@0.0.4
├─ @ember-data/serializer@3.28.3
├─ @ember-data/store@3.28.3
├─ babel-plugin-ember-data-packages-polyfill@0.1.2
└─ ember-data@3.28.3
```

**Comment by runspired** [comment]
I'm going to consolidate this with #7684
