### ISSUE TITLE
Relationship link with query params regression

### ISSUE THREAD

**Issue by jherdman** [emberjs/data#7822]
### Reproduction

https://github.com/jherdman/ed-relationship-bug-repro

1. Start app
2. Visit a car in the list
3. Note the list of associated colours with the car
4. Click "Back"
5. Visit a different car in the list

#### EXPECTED

You see the list of colours associated with the second car

#### ACTUAL

The list of colours associated is not rendered, but rather the bug indicator. This means the relationship of colours isn't loaded.

### Description

Prior to Ember Data 3.28 relationships that were defined as a link _with_ query params worked as any normal relationship wold. As of v3.28 this is no longer the case as demonstrated by the repro.

### Versions

Run the following command and paste the output below: `yarn list ember-source && yarn list ember-cli && yarn list --pattern ember-data`.

```cli
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ ember-source@3.28.8
✨  Done in 0.81s.
yarn list v1.22.17
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ ember-cli@3.28.5
✨  Done in 0.81s.
yarn list v1.22.17
├─ @ember-data/adapter@3.28.6
├─ @ember-data/canary-features@3.28.6
├─ @ember-data/debug@3.28.6
├─ @ember-data/model@3.28.6
├─ @ember-data/private-build-infra@3.28.6
├─ @ember-data/record-data@3.28.6
├─ @ember-data/rfc395-data@0.0.4
├─ @ember-data/serializer@3.28.6
├─ @ember-data/store@3.28.6
├─ babel-plugin-ember-data-packages-polyfill@0.1.2
└─ ember-data@3.28.6
```

**Comment by sandstrom** [comment]
Is this by any chance solved in 3.28.8? I know there were some bug fixes related to relationships in that release.

**Comment by jherdman** [comment]
Unfortunately I'm AFK for a while and won't be able to investigate. I'll reach out to a colleague to see if they can test and follow up with this.

**Comment by jherdman** [comment]
@sandstrom AFIK ember-data v3.28.6 is the latest available release, and was published 22 days ago. Sadly the above repro is still valid.

**Comment by sandstrom** [comment]
I was wrong, I meant to write 3.28.7. That version should be out.

Not sure if it contains any fix for your issue though: 
https://github.com/emberjs/data/compare/v3.28.6...v3.28.7

**Comment by jherdman** [comment]
Whoa. 3.28.7 seems to have resolved the bug in my repro. I'll poke someone at my employer to see if they can test in one of our apps.

**Comment by sandstrom** [comment]
happy to hear @jherdman

**Comment by sandstrom** [comment]
If your Ember Data is important to your employer, consider sponsoring some of the people that are working on Ember Data. A little money can go a long way, and if many companies can group up and pool money towards Ember and Ember Data, the return for those companies will be many multiples of what's being spent.

My employer is sponsoring runspired, rwjblue and snewcomer (though there are more good candidates, see https://github.com/emberjs/data/graphs/contributors) with a few hundred a month (aggregated).

**Comment by jherdman** [comment]
Indeed. We actually sponsored work by @igorT a long time back to make polymorphic relationships work better. Have no fear, we're not strangers to this 😄

**Comment by sandstrom** [comment]
@jherdman Sounds good! I was thinking of the recurring once-a-month sponsoring (not tied to any particular feature/work). But maybe that's what you're already doing?

**Comment by runspired** [comment]
To be honest the small contributions I get towards working on OSS via github sponsorship is why I do still maintain and contribute to EmberData whenever I get a chance. I don't have much time for it and at work we aren't currently in a place where I can justify investing in it directly for work. I'm sure other core team members feel similarly.

**Comment by runspired** [comment]
@jherdman can I close this?

**Comment by jherdman** [comment]
Absolutely. Thanks everyone!
