### ISSUE TITLE
Queries generated by adapter are putting "+" instead of "%20"

### ISSUE THREAD

**Issue by alechirsch** [emberjs/data#7824]
### Description
We are upgrading from ember data 3.20 to 3.28 and came across a breaking change in the way the ember data generates its urls. There seems to have been a change where ember data now uses `fetch` to make the queries, where as before you were using ajax.

We have been able to get around this issue temporarily by setting `useFetch` on the adapter to `false`, however we would like to use fetch in the future and this issue poses a problem.

When ajax generates the url for the request, it encodes spaces as `%20`, which is what we expect. However, with the change to fetch, ember data needed to generate its own query parameters [](https://github.com/emberjs/data/blob/v4.0.2/packages/adapter/addon/-private/utils/serialize-query-params.ts#L44).
I saw that you are explicity converting `%20` to `+`. This is not backwards compatible with the way ajax encodes the urls.
```
  return buildParams('', queryParamsObject).join('&').replace(/%20/g, '+');
```

We are aware that `+` indicates a space, but we prefer to use the encoding and this is a breaking change.

**Comment by snewcomer** [comment]
Looks like according to the spec, `+` is only allowed if we are posting form data.

```
headers: {
  'Content-Type': 'application/x-www-form-urlencoded',
},
```

https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.1

Also, this is what `encodeURI` does.  I suspect when the code was implemented/partially copied from Ajax, this was just an oversight.

So overall, this seems like an bug.  But just jumping in and changing this could in theory break for some folks....
