### ISSUE TITLE
The becomeDirty action does not set hasDirtyAttributes to true anymore

### ISSUE THREAD

**Issue by KroneckerDeIta** [emberjs/data#7851]
### Reproduction

Clone the following repository:

https://github.com/KroneckerDeIta/ember-dirty-bug

Then run:

$ npm install
$ npm start

Navigate to localhost:4200

Click "Save a comment"
Click "Become Dirty"

See that it doesn't have dirty attributes, but the internal model is dirty.

### Description

It looks like the issue stems from the fact that CUSTOM_MODEL_CLASS is now set to true and it is now using ___recordState instead of the _internalModel.currentState. It looks like CUSTOM_MODEL_CLASS was set to true in 3.28.0-beta.1 and looks like things worked before that point. If I manually set CUSTOM_MODEL_CLASS to false in node_modules/@ember-data/canary-features/addon/default-features.ts then things work fine. 

I guess I would be happy with one of the following:

- Calling becomeDirty action works as it did before.
- Clear instructions on how to set CUSTOM_MODEL_CLASS to false. I have tried what is in guide https://api.emberjs.com/ember-data/3.28/modules/@ember-data%2Fcanary-features but setting a window variable doesn't seem to work and adding things to config/environment.js doesn't work either.
- Or there is some other way to mark a model as being dirty?

### Versions

```cli
`-- ember-source@3.28.8
`-- ember-cli@3.28.5
`-- ember-data@3.28.7
```

**Comment by snewcomer** [comment]
@KroneckerDeIta Thank you for the issue!  Would you mind trying one thing and we can go from there?

`set(this, 'comment.message', 'Edited mesage');`

Also perhaps remove everything below the hack part and test again?  If you happen to be able to push an example repo, that would be greatly appreciated as well!

**Comment by KroneckerDeIta** [comment]
I have updated my original comment to now include a link to a repository showing the issue. I have removed the commented out call to set the message on the comment model as that didn't have anything to do with the issue as was just there to show that editing the message made the model dirty. The becomeDirty action not making hasDirtyAttributes true is the issue here. Hopefully that is clear with the example. After you press the two buttons the template shows what has and hasn't become dirty. 

My workaround:

It looks like observers watching hasDirtyAttributes get fired when becomeDirty action is called, but as mentioned above it stays false so the I have I have created computed properties that look like:

```
containsDirtyAttributes: computed("hasDirtyAttributes", function() {
    return this.hasDirtyAttributes || this._internalModel.currentState.isDirty;
})
```

**Comment by KroneckerDeIta** [comment]
Anyone had chance to look into this yet?

**Comment by runspired** [comment]
@KroneckerDeIta manually setting the model to dirty in this way is not a public API. That the internal-model state-machine gets out-of-sync with the new state-machine when hacked in this way is expected: the old state-machine only exists as a reference for us during a transition period (which fwiw has now ended, that code will be getting deleted soon).
