### ISSUE TITLE
BelongsTo-Relation changes throw error in Store -> unsubscribe

### ISSUE THREAD

**Issue by Timbuktu1982** [emberjs/data#7857]
Hi there,

i have a existing model with attributes and relationships. For example this model has a existent belongsTo relationship named "gender". 

When i set this belongsTo to null, all good at the moment, i get no error.

And if I now but change this nullified belongsTo to another relation, i get a error from stores record-notification-manager like "Passed unknown unsubscribe token to unsubscribe". 

If i change this belongsTo directly to a new relation, i get no error.

In the case that I have loaded an existing model where the belongsTo "gender" is null and I set to a relation, I don't get an error.

This is a bug that I don't think appeared before ember 4. I think the problem comes with this change https://github.com/emberjs/data/commit/856f7b33ab60b9327839fe80b7ae3588e863f657.

I use:
ember-cli 4.1.1
ember-source 4.1.0
ember-data 4.1.0

**Comment by Timbuktu1982** [comment]
I forgot to say that the app stops at this error and further work is not possible....

**Comment by runspired** [comment]
@Timbuktu1982 are you using the references API at all?

**Comment by Timbuktu1982** [comment]
> are you using the references API at all?

Sorry, I don't understand. What do you mean?

**Comment by runspired** [comment]
@Timbuktu1982 I tried to replicate this via multiple relationship configurations and could not. Could you create a reproduction or describe more about the setup?

**Comment by Timbuktu1982** [comment]
Hi Chris, 
thank you for your help.
Our structure is a little bit too complex to describe the complete structure in a bit of words.
But i give the best to describe the situation :-) and use a not so complex sample.

Model "user":
`import Model, { attr, belongsTo } from "@ember-data/model";

export default class UserModel extends Model {
    /**
     * Attributes
     */
    @attr("boolean") acceptance;
    @attr("String") email;
    @attr("String") mobilephone;
    @attr("String") password;
    @attr("String") phone;
    @attr("String") prename;
    @attr("String") primaryClient;
    @attr("String") salutation;
    @attr("String") surname;
    @attr("String") username;
    @attr("String") userUni;

    /**
     * BelongsTo
     */
    @belongsTo("client") client;
    @belongsTo("gender") genderSalutation;
    @belongsTo("user-category") usercategory;
    @belongsTo("user-group") userGroup;
}
`
In the gui we have diverse of elements to handle and visualize the attributes and relations (e.g. input-fields for attributes, select-fields for belongsTo etc.).

e.g. the belongsTo "genderSalutation" is represented as a select field. All available settings for this relationship has a own select entry in this field. To reset this relationship, the user can select a default select entry like "please select...". 

If the user now want to edit a data set of the model "user" and want to change to this select entry ("please select..."), the field set the value for this belongsTo to NULL. Up to here everything works normally. (notice: at this moment the user has not saved his changes)

Now the user change this belongsTo to another defined setting that is available for this belongsTo (e.g. like "male"). Now you get the error "Passed unknown unsubscribe token to unsubscribe".

Always when i change a belongsTo to null and after that to a new relation, then i became this error.

One more special feature caught my eye: If the user do the things as described, but the model (e.g. "user") is already dirty due to a change of one or more attributes, this error does not happen. 
The error only occurs if the model is not dirty and you set the belongsTo to NULL and then to a relation.

**Comment by Timbuktu1982** [comment]
And as I said, before the above change, everything was running flawlessly.
https://github.com/emberjs/data/commit/856f7b33ab60b9327839fe80b7ae3588e863f657

**Comment by Timbuktu1982** [comment]
Sorry, on thing i forgot to say: We use one specific extension for ember-data, the change tracker "https://github.com/danielspaniel/ember-data-change-tracker".

Do you need more information?

**Comment by urbany** [comment]
I'm also seeing this arror, and also using the ember-data.change-tracker addon

**Comment by Timbuktu1982** [comment]
Hi there,
for the moment you can use https://github.com/Timbuktu1982/ember-data/commit/780ac886b8cf8b8a731f72af8017269c92be8b42... I will keep this git up to date...

**Comment by urbany** [comment]
> Hi there, for the moment you can use [Timbuktu1982@780ac88](https://github.com/Timbuktu1982/ember-data/commit/780ac886b8cf8b8a731f72af8017269c92be8b42)... I will keep this git up to date...

how do i use this?

I tried liek this: 
`
    "ember-data": "github:Timbuktu1982/ember-data#780ac886b8cf8b8a731f72af8017269c92be8b42",
`

but I'm getting this error on start:
```
Missing npm packages: 
Package: ember-data
  * Specified: github:Timbuktu1982/ember-data#780ac886b8cf8b8a731f72af8017269c92be8b42
  * Installed: (not installed)
```

Already did npm install and it exists in node_modules/ember-data

Thanks in advance!

**Comment by runspired** [comment]
The bug here is with ember-data change tracker. Haven't spent time looking for a fix.

**Comment by urbany** [comment]
@runspired thanks anyway, if you can point me in any direction I can try to fix it there

**Comment by Timbuktu1982** [comment]
> > Hi there, for the moment you can use [Timbuktu1982@780ac88](https://github.com/Timbuktu1982/ember-data/commit/780ac886b8cf8b8a731f72af8017269c92be8b42)... I will keep this git up to date...
> 
> how do i use this?
> 
> I tried liek this: `"ember-data": "github:Timbuktu1982/ember-data#780ac886b8cf8b8a731f72af8017269c92be8b42",`
> 
> but I'm getting this error on start:
> 
> ```
> Missing npm packages: 
> Package: ember-data
>   * Specified: github:Timbuktu1982/ember-data#780ac886b8cf8b8a731f72af8017269c92be8b42
>   * Installed: (not installed)
> ```
> 
> Already did npm install and it exists in node_modules/ember-data
> 
> Thanks in advance!

Hi urbany, see instructions in section "Testing ember data source directly" on https://github.com/emberjs/data/blob/master/CONTRIBUTING.md...

**Comment by olyckne** [comment]
We've started to see this error pop up in different places in our app in our bug tracker after updating to 3.28 (specifically 3.28.10).
I haven't managed to reproduce it though and not sure how to debug it at all. We are **not** using ember-data-change-tracker.

**Comment by Timbuktu1982** [comment]
Hi. At the moment, I don't think it is certain that ember-data-change-tracker is the problem.
Ember-data-change-tracker is a good and useful tool, so I would like to use the addon also in the future....
What can I do to help you better understand the problem?

**Comment by validkeys** [comment]
Im also getting this error after upgrading from 3.27 to 3.28. I am not using the ember-data-change-tracker addon. The error for me results from the following:

I have a model called "Asset" and a model called "Team". An asset can optionally belong to a team. On the assets model I have a getter that returns an array of the foreign keys on the asset:

```
get foreignKeys() {
  const user = this.belongsTo("user").id()
  const team = this.belongsTo("team").id()
  return [ user, team ]
}
```

If I remove set the team to null on the asset everything is fine. When I try to add the team back on to the asset (asset.team = team) that's where I get the error: `Uncaught Error: Passed unknown unsubscribe token to unsubscribe`

If I comment out the ` const team = this.belongsTo("team").id()` in my getter, I know longer receive the error. It feels like there's some sort of caching issue where it's not picking up the updated relationship but I can't be sure

**Comment by jherdman** [comment]
I can confirm a use case quite similar to @validkeys keys using Ember Data v3.28. I'll illustrate the use case. Hopefully I can put together a repro shortly:

* I have a Document and Bookmark which have a belongs to relationship to each other
* I want to add a Bookmark to a Document
  * If the Document doesn't have a Bookmark I create a new bookmark
  * If there is a Bookmark already, destroy it, and then add a new one (i.e. you can toggle a Bookmark)

The code is as simple as this:

```javascript
if (document.belongsTo('bookmark').id()) {
  const bookmark = await document.bookmark;
  await bookmark.destroy();
} else {
  const newBookmark = this.store.createRecord('bookmark', { document });
  await newBookmark.save();
}
```

The above code expresses the bug. If I change it to the following I work around the bug:

```javascript
const bookmark = await document.bookmark;

if (bookmark) {
  await bookmark.destroy();
} else {
  const newBookmark = this.store.createRecord('bookmark', { document });
  await newBookmark.save();
}
```

**Comment by jherdman** [comment]
Reproduction https://github.com/jherdman/ember-data-issue-7857

**Comment by runspired** [comment]
Thanks folks. Think I have enough here to find the bug.

**Comment by runspired** [comment]
I suspect #8116 fixes though I haven't added a test capable of failing yet and have not verified against @jherdman's reproduction.

**Comment by runspired** [comment]
Added a test.
