### ISSUE TITLE
Problems with embroider-optimized?

### ISSUE THREAD

**Issue by jherdman** [emberjs/data#7860]
### Reproduction

https://github.com/adopted-ember-addons/active-model-adapter/pull/167

### Description

Ember Data v3.28 under the Embroider Optimized scenario is not happy. As far as I can tell something is a bit goofy with how the code is being transpiled. Can anyone confirm this?

### Versions

```cli
yarn list v1.22.17
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ ember-source@3.28.8
✨  Done in 0.92s.
yarn list v1.22.17
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ ember-cli@3.28.5
✨  Done in 0.89s.
yarn list v1.22.17
├─ @ember-data/adapter@3.28.8
├─ @ember-data/canary-features@3.28.8
├─ @ember-data/debug@3.28.8
├─ @ember-data/model@3.28.8
├─ @ember-data/private-build-infra@3.28.8
├─ @ember-data/record-data@3.28.8
├─ @ember-data/rfc395-data@0.0.4
├─ @ember-data/serializer@3.28.8
├─ @ember-data/store@3.28.8
├─ @types/ember-data__adapter@4.0.0
├─ @types/ember-data__model@4.0.0
├─ @types/ember-data__serializer@4.0.0
├─ @types/ember-data__store@4.0.0
├─ @types/ember-data@4.0.0
├─ babel-plugin-ember-data-packages-polyfill@0.1.2
└─ ember-data@3.28.8
```

**Comment by jrjohnson** [comment]
I'm [seeing the same problem with embroider optimized scenario](https://github.com/ilios/common/runs/5120854529?check_suite_focus=true#step:5:43) as `Error: Could not find module @ember-data/model/-private imported from (require)` also in an addon (if that helps)/

**Comment by jrjohnson** [comment]
This was resolved for use with Embroider 1.2.0.

**Comment by jherdman** [comment]
I can confirm the above solution works for me as well. Specifically @embroider/test-setup@^1.2.0

**Comment by runspired** [comment]
Closing since fixed upstream. Our work to support embroider first-class is tracked elsewhere.
