### ISSUE TITLE
[Bug] Creating multiple records without saving delete the relationship

### ISSUE THREAD

**Issue by khaled-s** [emberjs/data#7915]
I'm using a button to create multiple records on the client-side and store them in a list
these records have a relationship with other models, 
each time I create a record, the previously created record set the relation to null if it's the same id 

for example:

```
let commentList = [] \n
for(let x=0, x<3, x++) {
    let comment = this.store.createRecord('comment', {
                data: {id:2}, // not fixed
                post: {id: 1}, // fixed id
            });
   commentList.push(comment)
}
```

printing this list shows that the first two records post ids are null and the third is set to 1

- Ember: 3.28
- Node.js/npm: 14.16.1
- OS: Ubuntu
- Browser: Chrome

**Comment by runspired** [comment]
What is the relationship definition on Post? And how are you mapping these records back to the original in the response on save if you are saving them together?

**Comment by khaled-s** [comment]
the relation is "belongsTo"
and I'm using "ember-data-json-api-bulk-ext" for sending the data to the server
if the id is not the same the problem will not happen

**Comment by runspired** [comment]
@khaled-s this is expected, if the relationship is a belongsTo then there can only be one related record, not 3.
