### ISSUE TITLE
JSONAPISerializer should preserve `lid` in payloads

### ISSUE THREAD

**Issue by runspired** [emberjs/data#7956]
While we don't care to maintain that serializer that much, we should make sure it takes advantage of the feature if someone is using it and configures their API :)

**Comment by sly7-7** [comment]
🤦 I think this is the one I hit. So I'm making a PR.

**Comment by runspired** [comment]
@sly7-7 thanks! meant to tell you that earlier, glad you realized 🤦‍♂️
