### ISSUE TITLE
[DOC] Update hasMany import path in code samples

### ISSUE THREAD

**Issue by jenweber** [emberjs/data#8001]
### Description

In [has-many.js](https://github.com/emberjs/data/blob/master/packages/model/addon/-private/has-many.js), we reference a decorators package. Instead, we should import from model.

Before:

```
import { hasMany } from '@ember-decorators/data';
```

After:

```
import Model, { hasMany } from '@ember-data/model';
```

To do:
- Search for any uses of `@ember-decorators/data` and update the import path

**Comment by jenweber** [comment]
We noticed this while reviewing the new examples in https://github.com/ember-learn/guides-source/pull/1817/files

**Comment by Harixomxsingh** [comment]
hey is this issue is open if yes then, please add I want to cotribute

**Comment by jenweber** [comment]
Yes it is still open. Thanks for you help! Please @ me when you have opened a PR for this.
