### ISSUE TITLE
loop(max stack size exceeded) if creating an record, whose type was not loaded yet. and ember-inspector open

### ISSUE THREAD

**Issue by patricklx** [emberjs/data#8006]
createRecord will end up calling watchTypeIfUnseen ,
watchTypeIfUnseen is calling wrapModelType , which calls getRecords, which proceeds to do a sync, which then ends up calling watchTypeIfUnseen. See the stack strace in the description

### Reproduction

need to have ember-inspector open

this.store.createRecord('my-record', my-data).save();

### Description

-private.js:733 Uncaught RangeError: Maximum call stack size exceeded
    at get type [as type] (-private.js:733:1)
    at store._createRecordData (index.js:70:1)
    at InternalModel.get (-private.js:6136:1)
    at InternalModel._isRecordFullyDeleted (-private.js:5126:1)
    at InternalModel.isHiddenFromRecordArrays (-private.js:5120:1)
    at shouldIncludeInRecordArrays (-private.js:6936:1)
    at RecordArrayManager._visibleIdentifiersByType (-private.js:7095:1)
    at RecordArrayManager._syncLiveRecordArray (-private.js:7034:1)
    at RecordArrayManager.liveRecordArrayFor (-private.js:7076:1)
    at Store.peekAll (-private.js:9691:1)
<html>
<body>

  | function | @ | file
-- | -- | -- | --
  | get type | @ | -private.js:733
  | store._createRecordData | @ | index.js:70
  | get | @ | -private.js:6136
  | _isRecordFullyDeleted | @ | -private.js:5126
  | isHiddenFromRecordArrays | @ | -private.js:5120
  | shouldIncludeInRecordArrays | @ | -private.js:6936
  | _visibleIdentifiersByType | @ | -private.js:7095
  | _syncLiveRecordArray | @ | -private.js:7034
  | liveRecordArrayFor | @ | -private.js:7076
  | peekAll | @ | -private.js:9691
  | getRecords | @ | index.js:187
  | wrapModelType | @ | data_adapter.js:481
  | watchTypeIfUnseen | @ | index.js:111
  | store._createRecordData | @ | index.js:70
  | get | @ | -private.js:6136
  | _isRecordFullyDeleted | @ | -private.js:5126
  | isHiddenFromRecordArrays | @ | -private.js:5120
  | shouldIncludeInRecordArrays | @ | -private.js:6936
  | _visibleIdentifiersByType | @ | -private.js:7095
  | _syncLiveRecordArray | @ | -private.js:7034
  | liveRecordArrayFor | @ | -private.js:7076
  | peekAll | @ | -private.js:9691
  | getRecords | @ | index.js:187
  | wrapModelType | @ | data_adapter.js:481
  | watchTypeIfUnseen | @ | index.js:111
  | store._createRecordData | @ | index.js:70
  | get | @ | -private.js:6136
  | _isRecordFullyDeleted | @ | -private.js:5126
  | isHiddenFromRecordArrays | @ | -private.js:5120
  | shouldIncludeInRecordArrays | @ | -private.js:6936

</body>
</html>

### Versions

"ember-data": "^4.4.0",
"ember-source": "^4.4.0",

**Comment by spruce** [comment]
I just ran into this problem as well.

**Comment by runspired** [comment]
I'll backport this  fix to 3.28
