### ISSUE TITLE
Installation with yarn 1.22.18 fails

### ISSUE THREAD

**Issue by Turbo87** [emberjs/data#8088]
### Reproduction

https://github.com/rust-lang/crates.io/pull/4801

### Description

When an older yarn version is used then installation of `ember-data` v4.6.0 fails with:

> ember-data@4.6.0: The engine "yarn" is incompatible with this module. Expected version "1.22.19". Got "1.22.18"

This appears to be caused by https://github.com/emberjs/data/pull/8027/files#diff-336570c014b223552c15564402521af39202b04432d7fdc3c0081ed6d3540373R91, which introduced a very restrictive `engines.yarn` key in the `package.json` file.

**Comment by runspired** [comment]
We should remove the yarn key from the individual packages, it probably only needs to be in the root. While it's nice for folks not using Volta it's obviously bad to hoist that onto outside installs.

**Comment by ef4** [comment]
This is currently breaking in Embroider's CI if somebody wants to see the failure: 

https://github.com/embroider-build/embroider/runs/7566490423?check_suite_focus=true

**Comment by runspired** [comment]
@ef4 working on removal and back port now. Was not the intention to foist a yarn version on the community 😓

**Comment by runspired** [comment]
Released as 4.6.1 and 4.7 beta 1 and 4.8 alpha 1

**Comment by Turbo87** [comment]
thank you :)
