### ISSUE TITLE
Attempted to call store.adapterFor() but store destroyed

### ISSUE THREAD

**Issue by amk221** [emberjs/data#8105]
### Reproduction

Github repository with failing test:
https://github.com/amk221/-ember-willdestroy-promiseproxy/blob/main/app/components/my-component.js#L9

### Description

When a component is destroyed, this error happens (in the _test suite only_).

`Attempted to call store.adapterFor(), but the store instance has already been destroyed`

Further info:

`isDestroyed` is true on a `hasMany` promise array in the test environment
But that same boolean is false when run through the same scenario in the dev environment.

### Versions

Run the following command and paste the output below: `yarn list ember-source && yarn list ember-cli && yarn list --pattern ember-data`.

```cli
▶ yarn list ember-source && yarn list ember-cli && yarn list --pattern ember-data
yarn list v1.22.19
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ ember-source@4.6.0
✨  Done in 1.35s.
yarn list v1.22.19
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ ember-cli@4.6.0
✨  Done in 1.49s.
yarn list v1.22.19
├─ @ember-data/adapter@4.4.1
├─ @ember-data/canary-features@4.4.1
├─ @ember-data/debug@4.4.1
├─ @ember-data/model@4.4.1
├─ @ember-data/private-build-infra@4.4.1
├─ @ember-data/record-data@4.4.1
├─ @ember-data/rfc395-data@0.0.4
├─ @ember-data/serializer@4.4.1
├─ @ember-data/store@4.4.1
├─ babel-plugin-ember-data-packages-polyfill@0.1.2
└─ ember-data@4.4.1
✨  Done in 1.45s.
```

**Comment by runspired** [comment]
Closing as user code that may make network requests during destroy should guard for app destroy. This said post-5.0 we may want to redesign our teardown experience.
