### ISSUE TITLE
v4.6.1 Error: [object Object] was already assigned a value for fetch-options

### ISSUE THREAD

**Issue by jrjohnson** [emberjs/data#8110]
### Reproduction

Please provide one of the following:

I've been unable to create a minimal reproduction, I'm guessing I'm just not creating data in the right way to trigger it in a simple app. I'm actively working on this, but wanted to open this issue in case the solution is clear from the error message.

It's failing in our update PR at https://github.com/ilios/common/pull/2980

### Description

In updating from v4.3.0 to v4.6.1 our app is dying loading some specific model's data with the error `Error: [object Object] was already assigned a value for fetch-options` (note: #7997 prevented us from testing 4.4/4.5 so I'm not sure when this started happening).

@runspired identified this as coming from https://github.com/emberjs/data/blob/ebe2c1acb4947f69c7ec8f671e74c5da6971dea1/packages/store/addon/-private/weak-cache.ts#L102 in [discord](https://discord.com/channels/480462759797063690/486549196837486592/1002557723684126811)

### Versions

```cli
npm list ember-source && npm list ember-cli && npm list --pattern ember-data
ilios-common@69.2.1 /Users/jrjohnson/Documents/code/upstreamilios/common
├─┬ @ember/render-modifiers@2.0.4
│ └── ember-source@4.3.0 deduped
├─┬ @ember/test-helpers@2.8.1
│ └── ember-source@4.3.0 deduped
├─┬ @embroider/util@1.8.3
│ └── ember-source@4.3.0 deduped
└── ember-source@4.3.0

ilios-common@69.2.1 /Users/jrjohnson/Documents/code/upstreamilios/common
├─┬ ember-cli-dependency-checker@3.3.1
│ └── ember-cli@4.3.0 deduped
└── ember-cli@4.3.0

ilios-common@69.2.1 /Users/jrjohnson/Documents/code/upstreamilios/common
├─┬ ember-cli-mirage@3.0.0-alpha.3
│ └── ember-data@4.6.1 deduped
└── ember-data@4.6.1
```

**Comment by runspired** [comment]
I'm fairly sure the reproduction is to trigger multiple find requests for one record. Typically this requires separate `include` options per request to hit this codepath iirc.

**Comment by jrjohnson** [comment]
Thanks. Still not having any luck with a small reproduction, but I can confirm that commenting out a single line at https://github.com/ilios/common/blob/master/addon/services/data-loader.js#L43 does help.

```javascript
this.#coursesSchools[id] = this.store.findRecord('school', id, {
  //include: 'sessionTypes',
  reload: true,
});
```

interestingly *what* is included doesn't seem to matter so: 
```javascript
this.#coursesSchools[id] = this.store.findRecord('school', id, {
  include: '',
  reload: true,
});
```
doesn't help.
