### ISSUE TITLE
Documentation of dreprecations is missing in ember-data 5.x

### ISSUE THREAD

**Issue by Timbuktu1982** [emberjs/data#8119]
Hey there,

https://deprecations.emberjs.com/ is very useful, but deprecations since ember-data 4 are not described. Gives another source for deprecations of ember-data?

Thank you

**Comment by runspired** [comment]
I never remember what special place we have to make those PRs, @locks might be of help. I've been considering documenting them inline, which would make them show up here: https://api.emberjs.com/ember-data/release/modules/@ember-data%2Fdeprecations

**Comment by locks** [comment]
You can find the repo at https://github.com/ember-learn/deprecation-app/ !

**Comment by Timbuktu1982** [comment]
Hey there,
so i can hope for a actualization of documentation now?
Thank you so much

**Comment by runspired** [comment]
@Timbuktu1982 will probably take a bit to PR something. Is there a particular deprecation you're curious about? most of the deprecation descriptions say exactly what to do and the associated RFC typically has a more detailed description.

**Comment by runspired** [comment]
Going to close this issue since documentation for individual deprecations is tracked in #8086
