### ISSUE TITLE
no models in ember inspector -> typesMapFor has no entries

### ISSUE THREAD

**Issue by patricklx** [emberjs/data#8205]
currently ember inspector often does not show any models because typesMapFor does not have any entries.

https://github.com/emberjs/data/blob/master/packages/debug/addon/index.js#L85

ember data: 4.7.0

Was it always an initializer? I load most of my data in an initializer .

**Comment by runspired** [comment]
I believe this line needs to be updated to work with 4.7+
https://github.com/emberjs/data/blob/24645d3391c4d5a0b7e3c6fef0e7cd3752685845/packages/debug/addon/setup.js#L17

**Comment by patricklx** [comment]
@runspired I just tested the change and its not working. its only setup once inspector is opened. it will not see any model types created before
