### ISSUE TITLE
[Ember Data 4.7] Error: Assertion Failed: Expected to receive a stable Identifier to subscribe to

### ISSUE THREAD

**Issue by mkszepp** [emberjs/data#8262]
### Reproduction

1. Use a stored ember data model, which was returned from server
2. add in a hasMany (which has already some stored models) a new ember model with `createRecord` without saving
3. remove added model with `destroyRecord`
4. `Error: Assertion Failed: Expected to receive a stable Identifier to subscribe to` by accessing the function `some`, `filter`....

The problem doens't appear when i use in step 3 `rollbackAttributes` instead of `destroyRecord`/`deleteRecord`

### Description

For better understanding i have created a new clean ember project with a example (branch identifier-subscribe).
Example repo: https://github.com/mkszepp/ember-stable-identifier/tree/identifier-subscribe

So i have check the difference between `rollbackAttributes` and `destroyRecord` i found a possible reason.

The difference is, that the `unloadRecord` calls immidiatly the `unloadRecord` while `deleteRecord` in the next run loop.

https://github.com/emberjs/data/blob/c165e7efd062e186d53bb4ed689116c1ddb9d836/packages/model/addon/-private/model.js#L848-L860

https://github.com/emberjs/data/blob/c165e7efd062e186d53bb4ed689116c1ddb9d836/packages/store/addon/-private/store-service.ts#L632-L649

Is it possible, that the reported bug is a timing problem?

An other problem is, when i create a new record and delete it (with deleteRecord) the model stays in the store and the states (isNew, isDeleted...) are false and dirtyType is empty string. Maybe those two problems are interconnected

### Versions

Ember Js: 4.7.0+
Ember Data: 4.7.3

**Comment by runspired** [comment]
I suspect you haven't diagnosed what has gone wrong here quite right yet, the reason it appears there are separate run-loops is because we immediately fully dismantle everything for new records when any of `unloadRecord/deleteRecord/rollbackAttributes/destroyRecord` are called. Any one of these when called should fully complete the process.

**Comment by runspired** [comment]
I'm unable to reproduce this using the repo you provided

**Comment by mkszepp** [comment]
@runspired i'm using npm v14

The error occures, when i access to a deleted model, like in the provided repo.

https://github.com/mkszepp/ember-stable-identifier/blob/241d3f25559f98068a465c1c25a565af90f05af6/app/controllers/application.js#L61-L66

**Comment by runspired** [comment]
@mkszepp yes, what I am saying is that the provided reproduction does not reproduce the error at all for me. If it does for you, then there's likely something wrong with your install as that would be the only difference.

**Comment by mkszepp** [comment]
@runspired i have now updated nodejs version to `v18.12.0` & npm to `v8.19.2`, because nodejs `v14.x` brings only npn `v6.14.17`

I have now commitet the package.lock, but the update has not solved my probleme.

![grafik](https://user-images.githubusercontent.com/19845290/199429117-3a313815-d11a-48bb-857f-0f15374182ae.png)

**Comment by mkszepp** [comment]
I have tried to update to `v4.8.3` (removing embroider, cause of adapter problem), but the problem is still present.

**Comment by runspired** [comment]
still not sure how to replicate this, the repo provided did not replicate this for me with the steps provided. Would be happy to setup a video call to go through it together since probably I'm missing some context.

**Comment by mkszepp** [comment]
@runspired Thank you for your patience. Yes this woud be great, so i can show you the bug on my computer. How can we get in contact? Which channel do you prefer?

**Comment by mkszepp** [comment]
@runspired it would be great to geat a release with this and also other bugfixes in LTS 4.8.x
