### ISSUE TITLE
[Ember Data 4.7] Models disappear when more than 2400 instances

### ISSUE THREAD

**Issue by mkszepp** [emberjs/data#8263]
### Description

While creating the example repository for a other bug (https://github.com/emberjs/data/issues/8262) i have deteced this bug (which is present in the repository https://github.com/mkszepp/ember-stable-identifier)
When i have 2400 models in store and add model n. 2401, other models will be lost.
After removing a model all other models return.
When i readd model n. 2401, the `.length` returns a wrong number of models.
This problem is not present in ember 4.4 with ember data 4.4.

### Versions
Ember Js: 4.7.0+
Ember Data: 4.7.3
Test on Browser: latest Chrome + Firefox

**Comment by runspired** [comment]
do you have a reproduction for this?

**Comment by runspired** [comment]
Found bug, have fix
