### ISSUE TITLE
Using peekAll after unloadRecord returns incorrect length

### ISSUE THREAD

**Issue by mrloop** [emberjs/data#8286]
### Reproduction

Here's a minimal reproduction https://github.com/mrloop/ember-unload-bug
The second commit has the reproduction https://github.com/mrloop/ember-unload-bug/commit/0eb0e2b82187f149728a43edcf5c8585e04e3160

```js
    assert(
      'There should be 0 models before createRecord',
      this.store.peekAll('my-model').length === 0
    );
    let model = this.store.createRecord('my-model');
    model.unloadRecord();
    assert(
      'There should be 0 models after unloadRecord',
      this.store.peekAll('my-model').length === 0
    );
```

The second commit shows a workaround https://github.com/mrloop/ember-unload-bug/commit/c38f4393a00e835cde887e3de675836b18ba1ad3

```diff
    let model = this.store.createRecord('my-model');
+   this.store.peekAll('my-model').length;
    model.unloadRecord();
```

### Description

After creating a record and then unloading the record I expect `this.store.peekAll('my-model').length` to show correct count of records.
The most recent version which worked as expected is `4.6.4`

### Versions

```cli
ember-unload-bug@0.0.0 /home/ewan/projects/qonto/ember-unload-bug
├─┬ @ember/test-helpers@2.8.1
│ ├─┬ @embroider/util@1.9.0
│ │ └── ember-source@4.7.1 deduped
│ └── ember-source@4.7.1 deduped
└── ember-source@4.7.1

ember-unload-bug@0.0.0 /home/ewan/projects/qonto/ember-unload-bug
├─┬ ember-cli-dependency-checker@3.3.1
│ └── ember-cli@4.7.0 deduped
└── ember-cli@4.7.0

ember-unload-bug@0.0.0 /home/ewan/projects/qonto/ember-unload-bug
└── ember-data@4.7.3
```

**Comment by runspired** [comment]
I suspect this and #8299 are the same

**Comment by runspired** [comment]
Going to close in favor of #8299
