### ISSUE TITLE
Bad shebang in pre-commit hook

### ISSUE THREAD

**Issue by luxferresum** [emberjs/data#8302]
This is purely about the developer experience of `ember-data` itself.
When commiting `ember-data` has a pre-commit hook: `.git/hooks/pre-commit`, which calls a little script: `./node_modules/pre-commit/hook`.

*Both* files have a problematic shebang: `#!/bin/bash`, while the correct shebang would be `#!/usr/bin/env bash`
This is especially problematic on some linux distributions such as NixOS, where `/usr/bin/env` does not exist.

**Comment by luxferresum** [comment]
This seems to be caused by an [upstream issue](https://github.com/observing/pre-commit/issues/153)

**Comment by runspired** [comment]
We should just remove this script anyway, it no longer provides meaningful value
