### ISSUE TITLE
A record.destroyRecord() removes another record from the PromiseArray returned by a store.findAll 

### ISSUE THREAD

**Issue by eodb** [emberjs/data#8327]
### Reproduction

Unfortunately until now, after several attempts, I could not reproduce the issue in a small unit test. Hopefully the indication below pinpointing the code lines were I assume things might go wrong can give you a clear indication what might be the problem.

### Description

Sometimes in some particular scenarios where one or more records are destroyed, another record of the same type within the store also gets removed together with the record(s) that is(are) being destroyed.

However it is only the list of records that is affected. More particular the array of records that is returned from a `store.findAll()` (PromiseArray) or the array returned by a `store.peekAll()` of the given type that doesn't contain this "lost" record anymore.
The record itself however is still present in the store and is also fully returned with a `store.peekRecord()`.

So we end up with the following:
```
store.peekRecord('job', '0.J20221129110517012').id. ==> '0.J20221129110517012'
store.peekAll('job').length ==> 0
store.findAll('job').then(function(jobs) { jobs.forEach((job) => { console.log(job.id); }); })  ==> no output
```

In other words the "lost" record that was present for the type before the `destroyRecord` was called, is still in the store but is not found anymore with `peekAll()` and `findAll()`.

The reason might be found in the `record-array-manager` in following code lines in the `sync` method:
```
removes.forEach((i) => {
        state.splice(state.indexOf(i), 1);
      });
```
Each time the problem occurs, we hit the `state.splice()` line with the `StableRecordIdentifier` of the record that was destroyed but which is not part of the state collection (anymore?) and by consequence 'state.indexOf(i)' returns '-1' deleting the last element of the state array (i.e. our "lost" record that is not returned anymore by the peekAll and findAll methods).

One more thing I noticed and which might give you a hint, is that when we access one or more records with a `peekAll()` call in the code **before** a record is destroyed, we also pass the `state.splice()` line mentioned above but the problem does not occur (i.e. all `StableRecordIdentifier` are part of the collection)..
In other words, doing following call in the code (or debugger console) before the scenario to destroy a record is started, "avoids" the issue:
```
store.peekAll('job').map((job) => job.id).join(',')}
```
A call which one expects to have no side effects on the further scenario. 

### Versions

```cli
DEBUG: Ember      : 4.8.2
DEBUG: Ember Data : 4.8.3
```

**Comment by runspired** [comment]
We try to intelligently patch the arrays as they are often massive in size. Sounds like we missed a case here. We should figure out why remove could happen more than once, it might be valid. Probably good to at least assert the invalid index if we don't think it's valid that remove is called more than once.

**Comment by runspired** [comment]
probably the issue is somewhere along the lines of "we remove when unloaded" and "destroy is two pass", likely each pass calls remove in some situations and if the intermediate state is observed you end up broken.

**Comment by runspired** [comment]
Note: we don't seem to have gotten #8336 into any stable releases yet, so currently 4.12 will be the first version with a fix. Happy to do a patch for older versions if needed. Alternatively, use `unloadRecord` for removing `isNew` records.

**Comment by navels** [comment]
Wondering if this is related to an issue we ran into when upgrading from 3.26 to 3.28.  Here is a test:

```
import Model, { attr } from '@ember-data/model';
import { setupTest } from 'ember-qunit';
import { module, test } from 'qunit';

let store;

module('Unit | Model | Destroy model', function(hooks) {
  setupTest(hooks);

  hooks.beforeEach(function () {
    class Company extends Model {
      @attr('name') name;
    }

    this.owner.register('model:company', Company);
    store = this.owner.lookup('service:store');
  });

  test('deleteRecord twice', function (assert) {
    assert.expect(0);
    store.createRecord('company', { name: 'Acme' });
    store.createRecord('company', { name: 'Initech' });
    store.peekAll('company').forEach((company) => {
      company.deleteRecord();
    });
  });

  test('unloadRecord twice', function (assert) {
    assert.expect(0);
    store.createRecord('company', { name: 'Acme' });
    store.createRecord('company', { name: 'Initech' });
    store.peekAll('company').forEach((company) => {
      company.unloadRecord();
    });
  });
});
```

Results:
- Ember 3.27: both tests pass
- Ember 3.28: first test throws `Cannot read properties of undefined (reading 'deleteRecord')`, second test passes.
- Ember 4.8: both tests throw `Cannot read properties of undefined`

**Comment by runspired** [comment]
New issue please this sounds unrelated

**Comment by navels** [comment]
Done: https://github.com/emberjs/data/issues/8583
