### ISSUE TITLE
ember-try: Unexpected token '.' in private-build-infra

### ISSUE THREAD

**Issue by jlami** [emberjs/data#8328]
### Description

We use ember-data in our add-on testing and ember-try to setup the `latest`, `beta` and `canary` versions. We are getting the following error:

```
home/runner/work/ember-pouch/ember-pouch/node_modules/@ember-data/private-build-infra/src/addon-build-config-for-data-package.js:178
      const options = host.options['@embroider/macros']?.setConfig?.[name];
                                                        ^

SyntaxError: Unexpected token '.'
```

https://github.com/pouchdb-community/ember-pouch/actions/runs/3573652697/jobs/6007989261#step:5:115

You can find our ember-try.js config setup here:
https://github.com/pouchdb-community/ember-pouch/blob/master/config/ember-try.js

Did something change in your deployment? Do we have to use a different method to specify those builds?

**Comment by runspired** [comment]
@jlami what version of `node` are you on? it appears whichever version it is doesn't allow optional chaining. Our minimum supported node is 14 and optional chaining is supposed to available in all 14.x versions.

**Comment by jlami** [comment]
You are completely right. For some reason we still had 12. Just tested it with 14 and now it works again.
