### ISSUE TITLE
undefined when fetching the ID of a belongsTo relationship via get(obj, "relObj.id") when relObj is not loaded

### ISSUE THREAD

**Issue by cah-brian-gantzler** [emberjs/data#8331]
When fetching the id for an object of a belongsTo relationship, get(obj, "relObj.id") returned the id of the relationship object even when the object was not yet loaded into the store. (It may have triggered a fetch call, even though it was not needed). Under 4.7+ this now returns undefined. This is a bug.

I can not find it documented, but at one time I used obj.belongsTo('relObj').id() to get the id and avoid triggering the fetch.  Given that a relationship object may or may not be loaded in the store, what is the correct way to get the id of a relationship object if that is the only piece of information you need? Should we be doing this in the future? Is the intention is to deprecate the ability to do get(obj, "relObj.id").

**Comment by runspired** [comment]
- `record.belongsTo(<key>)` docs: https://api.emberjs.com/ember-data/4.7/classes/Model/methods/belongsTo?anchor=belongsTo
- `reference.id()` docs: https://api.emberjs.com/ember-data/4.7/classes/BelongsToReference/methods/id?anchor=id

The intention is to deprecate async relationships entirely. There's been some debate on whether to deprecate the existing relationships separately from or at the same time as deprecating Model: this deprecation is coming in the next month or two but obviously the replacement has not yet been made available. The replacement will allow sync access to the membership when desired without triggering load.

Using the references API is the correct approach here. I think `obj.relObj.id` also works (`get(obj, <complex.path>)` may be broken here for some classic chain interop issues we probably can do nothing about), we should look into it, though it's generally speaking been an accident that this ever worked. I believe this probably the same issue report as #8024 wherein the author had been apparently relying on this to allow eager rendering of just the id.

**Comment by cah-brian-gantzler** [comment]
Thanks for the links, I knew I read it somewhere, it would be nice if this was talked in the actual guide though, rather than having to read ever method looking for this.  I dont remember ever having to check the remoteType as in `(userRef.remoteType() === "id")` which means I probably need to change more code. 

While I can certainly change by code (that I found) to the object.belongsTo('relObj').id() (with the remoteType if check, which I never was doing), I only know where this is happening when I actually have a test, any other places are now going to fail where they didnt before. 

While I might not have been doing it the correct way, the docs do say a way to get it, but the previous guides never really talked about it being the only or correct way to get the id. It seems reasonable that `get(obj, "relObj.id") would work (and it did, using get because it was probably code written pre ember 3.1), so there was really no reason to think that was the wrong way. 

obj.relObj.id does not work under 4.7+ it returns undefined because relObj is a proxy and id on that is undefined.

obj.relObj.id 4.6- yields the following error
```
You attempted to access the `id` property (of <(unknown):ember263>).
Since Ember 3.1, this is usually fine as you no longer need to use `.get()`
to access computed properties. However, in this case, the object in question
is a special kind of Ember object (a proxy). Therefore, it is still necessary
to use `.get('id')` in this case.
```
Which if you read, seems to lead you to the solution I was using, get.  Only in this case its suggesting obj.relObj.get('id) which is really the same thing, which works in 4.6 but yields undefined in 4.7+

Good to know on the intention of deprecating async relationships, although wondering how relationships are going to be handled without somehow fetched ALL records that make up all models.

**Comment by runspired** [comment]
the docs there could be cleaned up, references are pretty old and best practices around them have certainly evolved. You don’t need to use/check remoteType. Also your usage of id is autotracked provided the initial value is not null (there’s a bug currently in auto tracking when initial value is null)

**Comment by runspired** [comment]
one thing I’d note is I don’t think we changed the promise-proxy implementation for 4.7 for async belongsTo. Something feels off on that. We left that one alone for reasons and changed all the others.

maybe that’s at the root of whatever is in the other issue for hasMany as well, maybe something in the legacy stuff stopped working. Can investigate.

you’ll still be able to async load related data, and pagination/filtering/sorting support will be built in (see the cache and RequestManager rfcs). But it’s not going to auto fetch, it won’t proxy through the promise, and it’s going to structurally look a little different.

**Comment by cah-brian-gantzler** [comment]
Thanks.   Am aware that both PromiseObject and PromiseArray are deprecated. 

Is there a bug when the initial value is undefined? I would have to assume that is what happens with a createRecord and an optional relationship. 

I will have to look to see if we have any optional relationships loaded from the backend and the value is null. Backend is java so its likely. When does that bug start showing up? 4.7 or 4.8?

**Comment by runspired** [comment]
@cah-brian-gantzler I looked into this a bit more and confirmed the belongsTo proxy has not changed at all. I suspect this means that the actual issue is a bit ... more interesting.

For some time we accidentally set the content to another promise-proxy, so if a fetch had been triggered it would be a promise proxy whose content was itself the findRecord promise proxy. At some point as we were cleaning things up this bug got rectified, but as Hyrum's law goes all observable behaviors, intentional-or-not, of EmberData are depended on in some way.

I suspect it was this dual promise-proxy that allowed eager access to the ID. We definitely do not want to restore that, plus it would end up being deprecated anyway as accessing id on that promise proxy is now deprecated.

Perhaps for now the answer is to restore this via a deprecated getter to mimic the behavior.

**Comment by cah-brian-gantzler** [comment]
Thanks so much. I figured something like that would be the solution. However you said via a deprecated getter. Didnt see where this getter was deprecated.  I will use that deprecation to help find all the other places I need to fix. 

However if you deprecate the getter, you would have to issue the deprecate only when `value()` was null, else you would get the deprecation on every access to the id, even when the object was loaded.

**Comment by runspired** [comment]
@cah-brian-gantzler chose to not deprecate it just yet. I’ll deprecate it when we remove the full async proxy.
