### ISSUE TITLE
Move @ember/string to peerDep?

### ISSUE THREAD

**Issue by kategengler** [emberjs/data#8393]
In 4.10, ember-source is deprecating the internal @ember/string and pointing users to the addon @emberjs/octane-strike-team 

`ember-resolver` uses `@ember/string` and will be adding the package as a peerDep. The CLI blueprint in 4.10 will have `@ember/string` as a dependency.

**Comment by kategengler** [comment]
It is in dependencies here https://github.com/emberjs/data/blob/5fdfd6aed41913d0c0ab90463b9762ff1327bab3/packages/-ember-data/package.json#L30

**Comment by javve** [comment]
Thanks, @kategengler! Good temporary solution!

**Comment by runspired** [comment]
resolved by #8422 and #8423
