### ISSUE TITLE
[Bug] Ember data doens't work with embroider starting with 4.8.x

### ISSUE THREAD

**Issue by mkszepp** [emberjs/data#8396]
### Description

There is not anymore possible to use ember-data with embroider, starting with 4.8.x.

In v4.9.1 we get this error:
Error `Error while processing route: index Assertion Failed: Expected store.createRecordDataFor to be implemented but it wasn't`

https://github.com/emberjs/data/blob/f8acfc162fb126efe8e2603359438b551347de41/packages/store/addon/-private/store-service.ts#L2392-L2406

This is because the private-build-infra `HAS_RECORD_DATA_PACKAGE` says, that the package `@ember-data/record-data` is not present.

https://github.com/emberjs/data/blob/f8acfc162fb126efe8e2603359438b551347de41/packages/private-build-infra/addon/available-packages.ts#L5

### Fix
We can fix this problem by replacing the line with `HAS_RECORD_DATA_PACKAGE: '@ember-data/record-data/-private',`

**Comment by mkszepp** [comment]
In `ember-data v4.10.x` there is necessary to replace all `moduleExists("@ember-data/json-api")` with `moduleExists("@ember-data/json-api/-private")`, so it works also for embroider

**Comment by mkszepp** [comment]
I have checked again this problem and the fix for this issue is better to add `index.ts` in `package/record-data` and replace all imports of `@ember-data/record-data/-private` with `'@ember-data/record-data'` in `v4.9.1`. After that the `record-data` packages works also with embroider.

I think we can do the same thing for `@ember-data/json-api` in `v.4.10.x`.

**Comment by ztjohns** [comment]
> I have checked again this problem and the fix for this issue is better to add `index.ts` in `package/record-data` and replace all imports of `@ember-data/record-data/-private` with `'@ember-data/record-data'` in `v4.9.1`. After that the `record-data` packages works also with embroider.
> 
> I think we can do the same thing for `@ember-data/json-api` in `v.4.10.x`.

Is this something we would need to do on a developers side while trying to update to the latest stable tag or is this more internal to embroider and ember-data.

I recently asked about this issue and discord and was told to roll back to 4.7.3 for ED for the time being. 

Thank you!

**Comment by mkszepp** [comment]
@ztjohns the bug for v4.9 must be fixed in ember-data (pr is already open)... after that, it should be possible to use with embroider without workaround in your project.

For v4.10 we need changes in embroider + the fix in ember data. See https://github.com/embroider-build/embroider/issues/1322#issuecomment-1386857904

I'm atm on 4.4, because 4.7 has varios bugs, which will not be backportet from 4.8/4.9 (for example identifier bug + problem with more than 1500 records). Beginning with 4.5+ my app was always buggy, so i recommend you to stay on 4.4.

When this bug is fixed in latest relesed ember-data version, i think that we should also backport all fixes to the lts 4.8.

A workaround in your project for 4.9 could be to create the index.ts or replace the package check string while build process. I think more is not necessary.

**Comment by Turbo87** [comment]
related: https://github.com/emberjs/data/issues/8296#issuecomment-1336142997 :)

**Comment by runspired** [comment]
the issue here is likely in embroider.  These addons function as normal traditional ember addons. Its unclear why that would break in more recent embroider versions, especially when the embroider tests in this repo are passing...

**Comment by mkszepp** [comment]
@runspired atm ember data has only one test for embroider if the build works, but it is no test for accessing to a model/store... right?
Maybe there is necessary to add some tests for that, so also ember data will be failed under embroider...

Normally other packages are using the same test like without embroider, but ember data doens't do this atm...

**Comment by rreckonerr** [comment]
The same issue is blocking me from upgrading from 4.4 to 4.8

**Comment by runspired** [comment]
@mkszepp are you on discord? would love to sync up and see if we can get to the root of some of this

**Comment by runspired** [comment]
pretty sure @embroider/test-setup is not compatible currently with EmberApp (only EmberAddon) and therefore isn't usable by us. See https://github.com/glimmerjs/glimmer.js/issues/406 for an error encountered trying to setup that way.

**Comment by mkszepp** [comment]
@runspired thank, confirm that it works without any workaround, package rules... in `v4.11.x`.
