### ISSUE TITLE
[Bug] `package.json` has wrong version in 4.9.1

### ISSUE THREAD

**Issue by mkszepp** [emberjs/data#8401]
I have seen, that the `4.9.1` has in `package.json` as version `4.9.0-alpha-14`.

https://github.com/emberjs/data/blob/f8acfc162fb126efe8e2603359438b551347de41/package.json#L1-L8

I think it was forget to replace...

**Comment by runspired** [comment]
@mkszepp that package.json is not used, though it is incorrectly synced (a bug that's since been fixed)

The published packages have the correct version: https://github.com/emberjs/data/blob/v4.9.1/packages/-ember-data/package.json
