### ISSUE TITLE
`normalizeErrorMessage` is interpolating error detail fields, leading to lost information

### ISSUE THREAD

**Issue by ososkp** [emberjs/data#8441]
I'm pretty sure [this line](https://github.com/emberjs/data/blob/36366ee779e27486a24635a02e609951429e4580/addon/adapters/rest.js#L1139) shouldn't be interpolating the payload and should instead be stringifying it or just sending it as an object? On my team every time we have an adapter that needs backend error details we end up overriding that method to just send the object.

What we're getting now is equivalent to the subject of [this issue](https://github.com/ember-cli/ember-ajax/issues/22) from 2015.

**Comment by runspired** [comment]
The code you pointed to is from pre ~3.11 ember-data, though the current code is similar. Broadly speaking what it does is correct from the sense of being a general attempt at coercing errors into the JSON:API format.

If you are overriding that hook you need it to still return an error with errors in the JSON:API format.

If you are using a recent version of EmberData (4.x, I think starting around 4.6) you may be hitting a cleanup which now enforces this more clearly, as before there was a lot of intimate API. 
The relevant code is here: https://github.com/emberjs/data/blob/686e619280bfe6d29554a8780aad98a772e48092/packages/store/src/-private/store-service.ts#L2726-L2736

and here: https://github.com/emberjs/data/blob/686e619280bfe6d29554a8780aad98a772e48092/packages/serializer/src/json.js#L1470

The legacy adapters are at this point frozen, we won't be making changes to them outside of some work to ensure they align into the [request-manager](https://api.emberjs.com/ember-data/release/modules/@ember-data%2Frequest) legacy handlers once we ship those. Adapters broadly speaking are entirely up-to-the-app to implement however they want as long as they conform to the [expected interface](https://api.emberjs.com/ember-data/release/classes/MinimumAdapterInterface) (which `normalizeErrorResponse` is not part of fwiw, that "hook" is an incidental detail of the specific Adapter you are using)/
