### ISSUE TITLE
`.setObjects` prints `.clear` deprecation message

### ISSUE THREAD

**Issue by Windvis** [emberjs/data#8450]
While updating an older app I ran into one of the Ember Data deprecations:

```
The `clear` method on the class ManyArray is deprecated. Use the native array method `length = 0` instead.
```
We didn't use `clear` in our code, so I inspected the stack trace and it seems that `setObjects` prints the deprecation message for the `clear` method instead.

https://github.com/emberjs/data/blob/bd8f7f46dca79d9d3295e9dc81f960903885aa7b/packages/store/src/-private/record-arrays/identifier-array.ts#L776-L777

**Comment by runspired** [comment]
Thanks <3
