### ISSUE TITLE
Since 4.12.0-alpha.9 `this.requestManager is undefined`

### ISSUE THREAD

**Issue by Jopie01** [emberjs/data#8491]
First, thanks for all the work on Ember-Data!

As a side project I'm trying to build a store with models and fields defined by a backend. This works perfectly even with the alpha versions which I'm following closely. But now I ran in to a problem ... When upgrading to 4.12.0-alpha.9 I got an error 

```Error while processing route: index this.requestManager is undefined```

Everything worked well in 4.12.0-alpha.8 but it seems that #8472 made some changes which is missing the creation of a `requestManager`? Not a big deal to create one myself, but the thing is that I'm using a custom adapter with a Ember service to connect to the backend. And I don't have any clue how to wire everything.

**Comment by runspired** [comment]
@Jopie01 sounds like you are consuming `@ember-data/store` directly and not `ember-data` ? When consuming `@ember-data/store` directly yes, you need to specify the `requestManager` instance yourself. This is because we leave it to the app to decide whether the request-manager is the same or a different instance as the app may choose to use elsewhere in the app. For legacy, we have `ember-data` wire one up in `ember-data/store` to keep folks using that package working.

**Comment by runspired** [comment]
@Jopie01 ah yes, if you import from `@ember-data/store` you get a different store than if you just relied on `ember-data` bringing the store. If you want what `ember-data` brings you want `ember-data/store`, I need to go fix the lint stuff to not yell at folks for using that.

**Comment by Jopie01** [comment]
@runspired, I was able to get it somewhat working. I worked through the README of the `requestManager` and found the section how to get it working with legacy `ember-data` (link https://github.com/emberjs/data/tree/main/packages/request#using-with-ember-data). However the displayed imports are not working and wrongly named. What I had to do:

1. install `@ember-data/legacy-compat` package
2. import the `LegacyNetworkHandler` with `import { LegacyNetworkHandler } from '@ember-data/legacy-compat';`
3. Let the `requestManager` use this with `this.requestManager.use([LegacyNetworkHandler]);`

By doing the above I was able to get my `StoreService` running, but got a warning and an error:

- I get the warning `Cannot deep-freeze StoreService`. The `StoreService` is my Ember Service which extends the Store with `export default class StoreService extends Store { ... }`. The service contains only the constructor and the `requestManager`
- I get an error when I want to access the data of a relational field. In this case a `belongsTo`. The error is
    ```
    Uncaught (in promise) TypeError: this.store._fetchManager is undefined
    ```

**Comment by runspired** [comment]
At the moment your store class still needs the class name to be Store because deepFreeze is doing a fairly dumb check to know it's the store

If you look in the ember-data package I believe there's a private api hack in the store to instantiate the FetchManager. That won't be necessary once I land the legacy relationships op PR but is until then.

**Comment by runspired** [comment]
> As a side project I'm trying to build a store with models and fields defined by a backend.

TBH if doing this you probably should remove adapter/serializer/model and legacy-compat. Can help you figure out what that looks like but basically if you're already schema driven there's no sense defining legacy models.

**Comment by Jopie01** [comment]
Both suggestions are unfortunately not working.

> At the moment your store class still needs the class name to be Store because deepFreeze is doing a fairly dumb check to know it's the store:

>  If you look in the ember-data package I believe there's a private api hack in the store to instantiate the FetchManager. That won't be necessary once I land the legacy relationships op PR but is until then.

The first gives:
```
Uncaught TypeError: class heritage _store.Store is not an object or null
```
The second gives:
```
Uncaught (in promise) TypeError: _private.FetchManager is not a constructor
```
I think I'm doing something wrong here, I will wait until the PR has landed and a new alpha version is created.

> TBH if doing this you probably should remove adapter/serializer/model and legacy-compat. Can help you figure out what that looks like but basically if you're already schema driven there's no sense defining legacy models.

This side project is already running for many years :grinning: . 
The backend (www.tryton.org) has an ORM where basically everything is defined. The models with the different fields and their relationships and the list / tree / form views. The backend can be queried by JSON-RPC and also have a few calls to get the models, fields and views. Based on the models and fields with their relationships I build everything in `Ember-Data` which is working pretty well. I create everything in advance. When fetching the 'real' data there is no information about the fields, it's just a JSON payload.

Using the `Ember-Data` models I'm also able to define the relationships and go from one model to the other. I rely on that property to go deep into the Model tree which is required by the views.
For example I start in the model `sale`, that model has a field `lines` which is a `hasMany` to the model `salelines` and each `salelines` has a `belongsTo` with `product`. Now I can start at `sale` and drill down to the `product` to see the details of the product. All goes through the store. I don't see at the moment how this all will work without the `@ember-data/model`.

I use the serializer to build the JSON-RPC payload, the adapter to build the query and an Ember Service to do the communication with the backend. Also I have some `Transform`s to make data JSON serializable.

**Comment by runspired** [comment]
yeah this is an excellent candidate for not using `@ember-data/model` `@ember-data/adapter` nor `@ember-data/serializer` at all.  The schema service already enabled just-in-time dynamic adding of new schema information from your API. The Graph will "just work" with that schema. A pretty basic proxy created in the `instantiateRecord` hook that takes the schema and constructs things via it from cache state would be 👨🏻‍🍳 💋

**Comment by runspired** [comment]
@Jopie01 use `v4.12.0-alpha.12`

- For FetchManager you will no longer need to import or do anything.
- `import { RequestManager } from '@ember-data/request';` => `import RequestManager from '@ember-data/request';`
- `import { Fetch } from '@ember-data/request/fetch';` => `import Fetch from '@ember-data/request/fetch';`
- for Store immutability can you  confirm you used this import? `import BaseStore from '@ember-data/store';`

For the current setup you have, if you aren't looking to shed weight / use the simpler APIs then I'd suggest extending `ember-data/store` instead of `@ember-data/store`, this would result in you not needing to configure anything for RequestManager / LegacyNetworkHandler

**Comment by Jopie01** [comment]
Oh-oh, someone got exited .... It seems that I have to start over again (no problem!) and work my way through the `fetchManager` the `schemaService` and `Store`. Do you have any pointers where to look (code, documentation)? In particular how to define relationships and later `Cache`?

In the end performance is key because at the moment I'm building all the models from the backend in one swoop. So the more models, the slower building becomes. Also I don't like keep using legacy which is going away in the future. Also if everything can become much easier and let the new `ember-data` handle things the better.

I will upgrade the package to `alpha.12` and report back.

**Comment by runspired** [comment]
#### Schema Service API Docs

> **Note** The Schema Service has been available since ~3.28

- [SchemaDefinitionService (Interface)](https://api.emberjs.com/ember-data/4.11/classes/SchemaDefinitionService)
- [Store.registerSchemaDefinitionService](https://api.emberjs.com/ember-data/4.11/classes/Store/methods/registerSchemaDefinitionService?anchor=registerSchemaDefinitionService)

**Comment by Jopie01** [comment]
>I will upgrade the package to alpha.12 and report back.

Not out of the woods yet. Another error popped up. Did some testing with different imports but that doesn't matter they all came to the same step.

```javascript
import BaseStore from '@ember-data/store';
import RequestManager from '@ember-data/request';
import { LegacyNetworkHandler } from '@ember-data/legacy-compat';

export default class StoreService extends BaseStore {
  requestManager = new RequestManager();

  constructor(args) {
    super(args);
    this.requestManager.use([LegacyNetworkHandler]);
  }
}
```
I changed the `BaseStore` back to `Store` and imported both once from `@ember-data/store` and `ember-data/store`.

The error comes up after I want to go into the details of a record. So to stay with the `sale` in https://github.com/emberjs/data/issues/8491#issuecomment-1484894383, I first get a list of the sales. Then I select a sale and click a button to get all the details of that sale like the party, address, dates, salelines etc. When I'm doing that I switch from a list view to a form view and I do a reload of the record to get the data for the needed fields.
```javascript 
selectedRecord.reload({
  adapterOptions: {
    include: {
      fields: this.saleFields
    }
  }
});
```
I don't want to get all the data from all the fields because not everything is needed and will impact performance. The fetched data is then pushed into the `Store` and displayed to the user.

The error:
```
Uncaught Error: No handler was able to handle this request.
```
When commenting out the `reload()` everything works, but the fields stays empty.

**Comment by runspired** [comment]
reload ought to hit the legacy handler with a "findRecord" op 🤔. I'd be less surprised at there being an error like this of the initial findAll was also failing. The heuristic in use here by the handler is "is there an op and is there no url" otherwise it passes on. This suggests you either have no op or have a url... both of which are surprising given the pasted code. 

Any chance you could pair to debug later?

**Comment by Jopie01** [comment]
> Any chance you could pair to debug later?

I discovered that also `ember-concurrency` is involved and the whole structure of the app is ..... a mess. I have also a hard time to track changes made to the records. So I started a new app from scratch and are now slowly moving to the new `@ember-data`. IMO trying to debug this is a waste of time, but if you insist I can try to make a reproduction with a simple app.

**Comment by Jopie01** [comment]
Ha @runspired , you seem to have fixed the bug by accident :rofl: . In my 'old' repo I reverted all my changes and then upgraded to `alpha.14`. Made only a few changes to my `store` service.
```javascript
import Store from '@ember-data/store';
import RequestManager from '@ember-data/request';
import { LegacyNetworkHandler } from '@ember-data/legacy-compat';

export default class StoreService extends Store {
  requestManager = new RequestManager();

  constructor(args) {
    super(args);
    this.requestManager.use([LegacyNetworkHandler]);
  }
}
```
Ran the server and believe it or not, it all worked! :partying_face: Clicked through different things from lists to views back and forth, it works like expected. So no debugging needed anymore and if you want you can close this.
