### ISSUE TITLE
Missing deprecation removal documentation

### ISSUE THREAD

**Issue by Yelinz** [emberjs/data#8493]
### Description
After updating an ember engine from ember-data 3.28 to 4.11 most of the test were broken, but the application still worked.
Integration and Unit tests were erroring with this message
```
 application.registerOptionsForType is not a function
```
With some digging through the code I found that there was a deprecation removal in version 4.1 but no mentions of it in the Changelog.
https://github.com/emberjs/data/pull/7757
https://github.com/emberjs/data/blob/main/CHANGELOG.md#v410-2021-12-30
https://github.com/emberjs/data/compare/v4.1.0-alpha.12...v4.1.0-alpha.13

Im not sure why this deprecation removal affects the tests, as all the ember-data versions are the same and none of the installed addons seem to call this function.

### Reproduction

- https://github.com/projectcaluma/ember-alexandria/pull/414

### Versions

```cli
$ yarn why ember-data
yarn why v1.22.19
[1/4] Why do we have the module "ember-data"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "ember-data@4.11.3"
info Has been hoisted to "ember-data"
info Reasons this module exists
   - Specified in "dependencies"
   - Hoisted from "ember-localized-model#ember-data"
info Disk size without dependencies: "2.57MB"
info Disk size with unique dependencies: "37.44MB"
info Disk size with transitive dependencies: "134.25MB"
info Number of shared dependencies: 248
Done in 1.76s.
```

**Comment by runspired** [comment]
@Yelinz that deprecation was from a 3.x deprecation, it was removed in 4.1 as part of the 4.x cleanup.  I forget where the deprecation guide was but it means you're using a deprecated version of `@ember/test-helpers` (possibly as `ember-test-helpers` and potentially still using the older `moduleFor` style of testing.

**Comment by runspired** [comment]
opened up a PR for you, I believe the linked project had never resolved the ember / test-helpers deprecations around using autoboot in tests. https://github.com/projectcaluma/ember-alexandria/pull/415
