### ISSUE TITLE
[Store] Adding requestManager from a service can give Cache errors

### ISSUE THREAD

**Issue by Jopie01** [emberjs/data#8508]
The changes in the docs of PR #8505 says that the `requestManager` can be added as a service in the store like:
```javascript
import Store from '@ember-data/store';
import { service } from '@ember/service';

export default class extends Store {
  @service('request') requestManager
}
```
However, when you use the `requestManager` also for other services like authentication which are not going through the store, you will get an error:
```
Error while processing route: index `RequestManager.useCache(<handler>)` May only be invoked prior to any request having been made. 
```
This error pops up when I first logged in using `ember-simple-auth` and then did a `this.store.findAll('ui.menu')`

**Comment by runspired** [comment]
Thanks! This could be fixed by a better docs example showing how to ensure the store in this case has added its cache handler(s) in time, but probably the constraint for the timing on this one can be relaxed.

**Comment by Jopie01** [comment]
> example showing how to ensure the store in this case has added its cache handler(s) in time

Can you give that example? I'm now calling my own jsonrpc `requestManager` directly in a `this.store.findAll('ui.menu')` but it bypasses everything so the `instantiateRecord` is not called. I suppose it must go through the `requestManager` of the store to get all the magic working. And instead of duplicating code it would be nice to ensure the store has added its cache handler.

**Comment by Jopie01** [comment]
Hmm, I got is working, however had to do a bit more. I added a `nop` in the store so I could call that before anything else. The store is now called first and calling the `_registerCacheHandler()` seems to add the Cache.

```javascript
// routes/application.js
import Route from '@ember/routing/route';
import { service } from '@ember/service';

export default class ApplicationRoute extends Route {
  @service jsonrpc;
  @service session;
  @service store;

  async beforeModel() {
    this.store.nop();  // dumb call to the store
    await this.session.setup();
    return await this._loginUser();
  }

  async model() {
    const version = await this.jsonrpc.makeRequest(
      'common.server.version',
      [],
      null,
      false,
      {}
    );
    console.log(version);
  }
}

// services/store.js
import Store, { recordIdentifierFor } from '@ember-data/store';
import Cache from '@ember-data/json-api';
import { service } from '@ember/service';

export default class StoreService extends Store {
  @service('jsonrpc') requestManager;

  constructor(...args) {
    super(...args);
    this._registerCacheHandler();
  }

  nop() {}
}
```
But I still got an error when I do `this.store.findAll('ui.menu')` in the `model` hook of the `application` route.
```
Error while processing route: index store is undefined calcShouldFetch
```
And indeed the store is not defined when calling the `calcShouldFetch`.

Another thing: In the documentation I also read to setup a Cache with
```javascript
import Store from '@ember-data/store';
import Cache from '@ember-data/json-api';

class extends Store {
  createCache(storeWrapper) {
    return new Cache(storeWrapper);
  }
}
```
But when I'm doing that, this function is never called. Or is this after the response came back from the backend and this will create a cache for it?
