### ISSUE TITLE
[Store / Cache] CacheHandler still takes the working key even `cacheOptions.key` is available

### ISSUE THREAD

**Issue by Jopie01** [emberjs/data#8530]
Related to #8516 (I can't reopen that issue), the request in the CacheHandler is still taking the wrong key. 
https://github.com/emberjs/data/blob/d0fc75d3f928fc528ebec97e4361cdd9ff78d92a/packages/store/src/-private/cache-handler.ts#L123-L157 I'm creating the key myself based on the different params, but these params are exactly the same on each request hence the key is also exactly the same.

When I force line 132 to use only the `cacheOptions.key` it works perfectly. Just to mention that the `method` is `POST`.

I updated my repo with two routes, each fetching data through the store. Without my change, each time you visit the route, the backend is called. With my change, the backend is called the first time, the next times it is getting the data from cache.

**Comment by runspired** [comment]
Thanks. Need to run this through the new identifier generation hook and it should just work.

**Comment by Jopie01** [comment]
I think when this fix is in, that most of the loose ends for fetching data with a model and schema-less Ember Data are connected. 

Of course the next step could be mutation of data, but I would rather get dirty with the `SchemaDefinitionService` and `Models`. At some point I will go mutate data. On the other hand, what do you prefer? Because this is a side project, no pressure just a point on the horizon. "And the way to it goes through dark valleys and is full of twists and sharp bends" .... ahum ..
