### ISSUE TITLE
 [Cache] attributes of records got missing again (related #8519)

### ISSUE THREAD

**Issue by Jopie01** [emberjs/data#8535]
After upgrading to `alpha.18` I got the same issue as in #8519. I did only the upgrade no code changes. The first time the data is fetched from the backend, the next time returned from the `cache` but got only the `id`, `lid` etc back, but no `attributes`.

**Comment by runspired** [comment]
@Jopie01 I think this is expected based on the setup you had iirc, happy to dig at it though

**Comment by Jopie01** [comment]
I am completely lost :cry: Going back to older `alpha` versions give the same behavior even if I force using the `cacheOptions.key`. Seems I have had some caching issues ......

The strange thing is that when the data is fetched from the backend, it is converted to an JSON-API structure and `put` into the `cache`. Then the `instantiateRecord` is called and the data is returned. As said this works for the first time when getting data from the backend. But the second time when the data should come from the `cache`, I get no data. So it seems that the data is not cached at all which is weird because enabling debugging shows that a record is created.
https://github.com/emberjs/data/blob/4ff247ad915e671910e83d707a88fc564ee2c972/packages/store/src/-private/caches/instance-cache.ts#L284
What I noticed though is that `properties` is `undefined`, no idea if that's a problem.

**Comment by Jopie01** [comment]
@runspired, can you take a look at `getHydratedContent`?
https://github.com/emberjs/data/blob/e316aeca96f59e46a37723006a76f0120d5b276a/packages/store/src/-private/cache-handler.ts#L26-L53
And in particular line 45. When I comment out that line everything seems to work ....... This time I removed all the installed `@ember-data` packages, pruned the node_modules directory to make sure nothing left and installed the packages again and made that one change. I also emptied the browser caches from both FireFox and Chrome to make sure no caches are left. Both browsers did gave the same output (although Chrome always requested the `favicon`).

**Comment by runspired** [comment]
@Jopie01 yeah I can take a peek there, I've changed that in #8539 anyway and will make sure to add some additional tests for cache hits.
