### ISSUE TITLE
[SchemaDefinitionService] Graph expects a 'Model' Object layout

### ISSUE THREAD

**Issue by Jopie01** [emberjs/data#8554]
I had some trouble with the `relationshipsDefinitionFor` in the `SchemaDefinitionService`. As it turns out you have to return an Object with the same keys and layout at the `Model` in `@ember-data/model`.

Maybe something to document?

**Comment by runspired** [comment]
@Jopie01 It's less a 'Model' object layout and more a constraint on simple keys. The schema is in fact documented :D though I think the documentation is better in 4.12 for it than it was in 4.11. 

See https://api.emberjs.com/ember-data/4.11/classes/SchemaDefinitionService/methods/relationshipsDefinitionFor?anchor=relationshipsDefinitionFor

We may at some point simplify the schema service a bit, there's some redundancy that's not needed and (importantly) there's also no clear way to do nested schemas other than to overload attribute / relationship paths or eject with custom options. Broadly speaking though, we've been able to build GraphQL support in the past using this, so advanced scenarios are possible though ... unwieldy if done manually.

**Comment by Jopie01** [comment]
Thanks for the link to the documentation. I must have been blind :disappointed:
