### ISSUE TITLE
Error: can't locate @ember-data/record-data/-private referred to in module rules

### ISSUE THREAD

**Issue by Turbo87** [emberjs/data#8560]
### Reproduction

https://github.com/rust-lang/crates.io/pull/6285

### Description

Trying to build the project fails with:

```
Error: can't locate @ember-data/record-data/-private referred to in module rules:{
  "dependsOnModules": [
    "@ember-data/record-data/-private"
  ]
}
```

### Versions

Ember.js and CLI are at 4.12.0. The issue start when upgrading Ember Data from 4.11.x to 4.12.0.

**Comment by runspired** [comment]
@Turbo87 iirc you build with embroider? this is an upstream embroider bug
