### ISSUE TITLE
4.12 LegacyRelationshipSupport caches first accessed async relationship instead of by-field

### ISSUE THREAD

**Issue by runspired** [emberjs/data#8579]
Reported in discord

Problematic code: https://github.com/emberjs/data/blob/21d5a32e29a3475bbfdac0c938f4afa744400444/packages/model/src/-private/legacy-relationships-support.ts#L503-L508

**Comment by cah-brian-gantzler** [comment]
@runspired Hey, just ran into this issue. See that it was merged after 4.12 was released. Could we get a 4.12.1 please

**Comment by runspired** [comment]
@cah-brian-gantzler 4.12.1 is in the works, one of the fixes is tricky to backport and still in-flight

**Comment by cah-brian-gantzler** [comment]
Thanks for the update

**Comment by cah-brian-gantzler** [comment]
Confirming that 4.12.1 works for me. Thanks
