### ISSUE TITLE
Broken links in API class documentation

### ISSUE THREAD

**Issue by aliokan** [emberjs/data#8586]
### Description

All `Defined in:` and `Edit on Github` links are broken in `ember-data` API classes documentation. 

There is an extra `package` added in the url. 

Example: 
- [ Class \<Interface\> Adapter](https://api.emberjs.com/ember-data/4.12/classes/%3CInterface%3E%20Adapter)
  - Defined in: [../ember-data-types/q/minimum-adapter-interface.ts:20](https://github.com/emberjs/data/tree/v4.12.0/packages/ember-data-types/q/minimum-adapter-interface.ts#L20)
  - Edit on Github: https://github.com/emberjs/data/edit/release/packages/ember-data-types/q/minimum-adapter-interface.ts#L20
- [Class AbortError](https://api.emberjs.com/ember-data/4.12/classes/AbortError)
  - Defined in: [../packages/adapter/src/error.js:219](https://github.com/emberjs/data/tree/v4.12.0/packages/packages/adapter/src/error.js#L219)
  - Edit on Github: https://github.com/emberjs/data/edit/release/packages/packages/adapter/src/error.js#L219

Errors appear in v4.8

### Investigation

[Between 4.7.3 and 4.8.8](https://github.com/emberjs/data/compare/v4.7.3...v4.8.8) docs generation migrate from `ember ember-cli-yuidoc` to embedded solution `cd ./docs-generator && node ./compile-docs.js`

The docs generation was before executed from [packages/-ember-data/package.json](https://github.com/emberjs/data/compare/v4.7.3...v4.8.8#diff-336570c014b223552c15564402521af39202b04432d7fdc3c0081ed6d3540373) and now from [package.json](https://github.com/emberjs/data/compare/v4.7.3...v4.8.8#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) 

Error visible in json-doc : 
- `"file": "../packages/adapter/src/error.js",` https://api-store.emberjs.com/json-docs/ember-data/4.8.8/classes/ember-data-4.8.8-AbortError-a0be69d9f2.json
- `"file": "../adapter/addon/error.js",` https://api-store.emberjs.com/json-docs/ember-data/4.7.3/classes/ember-data-4.7.3-AbortError-48bf0f041d.json

**Comment by runspired** [comment]
Thanks for the spelunking!
