### ISSUE TITLE
Typescript doesn't match runtime

### ISSUE THREAD

**Issue by BryanCrotaz** [emberjs/data#8599]
Using `store.peekAll()`, docs say that I should use objectAt:
> It's important to note that RecordArray is not a JavaScript array, it's an object that implements [MutableArray](https://api.emberjs.com/ember/release/classes/MutableArray). This is important because, for example, if you want to retrieve records by index, the [] notation will not work--you'll have to use objectAt(index) instead.

At runtime, objectAt is undefined and I get a `Proxy<Array<any>>`, and plain `array[0]` syntax works. But this doesn't match with the typescript definitions

```ts
// in my test I have to write this mess to use array[0] syntax

    // should have created a new org
    let allOrgs = store.peekAll('organisation') as unknown as Array<OrganisationModel>;
    assert.strictEqual(allOrgs.length, 1);
    let org: OrganisationModel = allOrgs[0] as OrganisationModel;
    assert.strictEqual(org.name, newOrgName);
```

**Comment by runspired** [comment]
Thanks, will fix the docs. However, we don't ship or maintain types for EmberData currently. I am able to merge fixes to them though if you're willing to open a PR to the community types, I'm also willing (and looking) for anyone that wants to take ownership of bringing those community types into the project and updating them / helping us iterate on them until we can ship stable TS support.

**Comment by runspired** [comment]
Ah, this is an issue with the guides being out of date. https://guides.emberjs.com/v4.12.0/models/finding-records/

Going to link this to the epic for better guides and close.
