### ISSUE TITLE
helpful errors out of date

### ISSUE THREAD

**Issue by BryanCrotaz** [emberjs/data#8600]
Setting up a route then navigating to `user/1`:
```ts
import Route from '@ember/routing/route';

export default class UserRoute extends Route {}
```

_Error: Assertion Failed: You used the dynamic segment `user_id` in your route `user` for which Ember requires you provide a data-loading implementation. Commonly, that is done by adding a model hook implementation on the route (`model({user_id}) {`) or by injecting an implemention of a data store: `@service store;`._

Following the instructions:
```ts
import Route from '@ember/routing/route';
import { service } from '@ember/service';

export default class UserRoute extends Route {
  @service store;
}
```

Now I get:
_Error: Assertion Failed: store.find has been removed. Use store.findRecord instead._

**Comment by runspired** [comment]
@BryanCrotaz I think you want to open this in Ember itself, this is not an EmberData behavior. Or if @chriskrycho or @wagenet is maybe able to just transfer this over?

**Comment by runspired** [comment]
Given this is deprecated upstream I think closing is fine. Having the error points you towards needing to implement the model hook which addresses the deprecation as well.  https://github.com/emberjs/rfcs/pull/774
