### ISSUE TITLE
Defaults for `async` and `inverse` no longer works on `5.0.0`

### ISSUE THREAD

**Issue by esbanarango** [emberjs/data#8646]
For `ember-data > 5.0.0`, is it now required to *always* set the value of  `async` and `inverse`? 

I bumped a project to `ember-data 5.0.0`, and now I'm getting these errors:

<img width="580" alt="async" src="https://github.com/emberjs/data/assets/1156865/a1e4551a-a420-44e3-be6b-38c83a0fe8ac">
<img width="557" alt="Signal" src="https://github.com/emberjs/data/assets/1156865/ccf65636-21d6-4d07-999a-2d86dd15b394">
<img width="896" alt="Signal" src="https://github.com/emberjs/data/assets/1156865/c963143a-2867-48e7-a022-7b9b176ee99e">

**Comment by runspired** [comment]
Yes, the old behaviors were RFC'd to deprecation a few years back, that deprecation was implemented in 4.7 iirc, and then removed in 5.0
