### ISSUE TITLE
Max stack call error in prod mode with asserts (v5, v4)

### ISSUE THREAD

**Issue by lifeart** [emberjs/data#8710]
At the moment, if debug data is not stripped from prod build, we have recursion error.

Given: Prod build, `assert` function is not stripped.

1. Trying to access any key (`id`, for example) on just created model.
2. This code part is executed: https://github.com/emberjs/data/blob/7243558cdf4817ef1c41db1bae41f4b63e648c8e/packages/model/src/-private/attr.js#L130
3. And here we calling `toString` on record:
https://github.com/emberjs/data/blob/7243558cdf4817ef1c41db1bae41f4b63e648c8e/packages/store/src/-private/caches/instance-cache.ts#L68

5. And we going here: https://github.com/emberjs/data/blob/7243558cdf4817ef1c41db1bae41f4b63e648c8e/packages/model/src/-private/model.js#L501

Where we access `this.id` and here is GOTO: 1.

**Comment by lifeart** [comment]
It's not an real issue, but may appear on non ember-cli/embroider envs.

In codebase we have quite alot of cases, referring to model `id`.
One of possible workarounds - try to prevent nested toString calls on model.


```js
{
  #isToStringInProgress = false;
  toString() {
    if (this.#isToStringInProgress) {
      return `<${this.constructor.modelName}:unknown>`;
    }
    this.#isToStringInProgress = true;
    try {
      return  `<model::${this.constructor.modelName}:${this.id}>`; 
    } finally {
      this.#isToStringInProgress = false;
    }
  }
}
```

**Comment by runspired** [comment]
this is why non ember-cli/embroider envs still need a build config (and build plugin). Not running our final build step will produce a very un-tested and dramatically different library with significantly degraded performance characteristics

**Comment by runspired** [comment]
Closing as nothing for us to do here on this ticket, tracking for broader compat is in #8147 and for embroider/vite is in #8103
