### ISSUE TITLE
Unmet peerDep in Ember Data Model when using ember-source v5 (`ember-cached-decorator-polyfill`)

### ISSUE THREAD

**Issue by mkszepp** [emberjs/data#8735]
Ember Data Model brings atm as dependency [ember-cached-decorator-polyfill](https://github.com/ember-polyfills/ember-cached-decorator-polyfill)

https://github.com/emberjs/data/blob/71f35504ef2f75dd7b6596e48f6e787e445be3d8/packages/model/package.json#L62-L71

ember-cached-decorator-polyfill has as peerDependency "ember-source": "^3.13.0 || ^4.0.0"

Ember.Js has added the `@cached` decorator in [v4.1.0](https://github.com/emberjs/ember.js/blob/main/CHANGELOG.md#v410-december-28-2021)

Is this polyfill still necessary? If yes, we should add ember-source v5 to `ember-cached-decorator-polyfill`

PNPM output:
└─┬ ember-data 5.1.0
  └─┬ @ember-data/model 5.1.0
    └─┬ ember-cached-decorator-polyfill 1.0.1
      └── ✕ unmet peer ember-source@"^3.13.0 || ^4.0.0": found 5.1.

**Comment by runspired** [comment]
While officially EmberData only supports the last two ember-source LTS releases at the point that we release a version, we prefer (if possible) to keep the effective range of support much wider. In this case, we've tried to stay compatible with the 3.28 to help teams upgrade more easily.

We could drop it, but tbh ember-cached-decorator-polyfill should bump the peer-dep range for the same reason. Lots of addons (like vertical-collection) try to keep massive support ranges when it is trivial to do so, and this is one of those cases where it is.

**Comment by runspired** [comment]
cc @NullVoxPopuli I think you were going to look at this for ember-cached-decorator-polyfill?

**Comment by NullVoxPopuli** [comment]
A new version of that package has been released, so hopefully updating it in the lockfile fixes the issue

**Comment by mkszepp** [comment]
@NullVoxPopuli @runspired thanks, looks good 🙃.

@runspired whats the plan for ember data? Keep the dependency or remove? If keep, we can close this issue.

**Comment by runspired** [comment]
@mkszepp planning to keep since I happen to know some folks have been working with 3.28 ember and latest ember-data (and we're still testing against 3.28 even though technically we dropped support a long time ago). Since this is just a warning I'm not going to backport the fix but I will bump our version once the fix is available (got merged and tagged but renovate hasn't seen it yet...)
