### ISSUE TITLE
Remove Embroider workarounds in test `embroider-basic-compat`

### ISSUE THREAD

**Issue by mkszepp** [emberjs/data#8748]
In EmberData there are some workarounds for embroider. Cause of this workaround the `ember-data` embroider tests were not failed in v4.12.x and this has produced this side-effect https://github.com/embroider-build/embroider/issues/1506#issuecomment-1634038979 in consumer app.

For EmberData v5 there makes no different, but ember data v4.12.x (maybe also 4.11.x) there is necessary to add workaround in consumer app to get run ember-data.

https://github.com/emberjs/data/blob/96cad26696ceb4535c2ff5ea352962c9d9ebdae9/tests/embroider-basic-compat/ember-cli-build.js#L35-L55

We should remove this lines for ember-data v5 & after embroider release also for ember-data v4

**Comment by runspired** [comment]
These lines are here because we are not compatible with embroider if embroider is secretly trying to fix things. Embroider should never be providing a compat adapter 4.12+.
