### ISSUE TITLE
3.28.8 non-attr() properties and createRecord() Behavior Change

### ISSUE THREAD

**Issue by kdagnan** [emberjs/data#8778]
Hi all, I am seeing new behavior that I believe was introduced [here](https://github.com/emberjs/data/commit/fa979a3eed2d23706eed50a246d6cbd1a6ced391) 

I can reproduce on Ember-data 3.28.8 but not 3.28.7. 3.28.13 is the latest LTS patch we’d like to be using.

**Essentially, any properties not labeled as attr() are not persisted from createRecord()**

### Code Example
Post
```
Model.extend({
   status: attr(“string”, { defaultValue: “PENDING”})
   recent: false // notice not an attr()
})
```

`const post = store.createRecord(‘post’, { status: “DRAFT”, recent: true })
`

#### 3.28.7
`post = { status: “DRAFT”, recent: true }
`
#### 3.28.8
`post = { status: “DRAFT”, recent: false }
`

Sorry for poor formatting, believe it or not I’m torturing myself on mobile currently. 

Is this behavior change intentional?

**Comment by runspired** [comment]
Created a test in #8779 that shows that in 3.28 everything is functioning as intended here and the scenario you described above does in fact work. There's either a nuance not shown in the report or something specific to your app (or an addon in use) changes the behavior of EmberData.

**Comment by kdagnan** [comment]
You are indeed correct, thank you for the quick and helpful response. 

We were overriding init() and were not passing the args to super(). Surprised this ever worked without it...
