### ISSUE TITLE
Assertion Failed: Do not use A() on an EmberData PromiseManyArray

### ISSUE THREAD

**Issue by patricklx** [emberjs/data#8847]
But i'm not using A() on PromiseManyArray...

this is the stack trace:
```
index.js:81 Uncaught (in promise) Error: Assertion Failed: Do not use A() on an EmberData PromiseManyArray
    at assert (index.js:81:13)
    at PromiseManyArray.meta.hasMixin (index-372d2028.js:1006:30)
    at Mixin.detect (mixin.js:490:17)
    at isArray (index.js:123:40)
    at toBool (index.js:3274:14)
    at runtime.js:1972:37
    at reference.js:106:35
    at track (validator.js:587:5)
    at valueForRef (reference.js:105:21)
    at Object.evaluate (runtime.js:1937:23)
```

### Description

this is caused by checking the PromiseManyArray with an if statement in hbs:
```hbs
{{#if this.book.authors}}
  <div></div>
{{/if}}
```

can be fixed by using .length
```hbs
{{#if this.book.authors.length}}
  <div></div>
{{/if}}
```

but error message is misleading

### Versions

devDependencies:
ember-source 5.2.0
ember-cli 5.2.1
ember-data 5.2.0

**Comment by runspired** [comment]
wrap it in `equals`, this looks like a bug in `if`

**Comment by runspired** [comment]
Going to close since the refactor is to do the right thing (use length) and supporting empty arrays being considered falsey is out of scope here

**Comment by patricklx** [comment]
I don't fully agree.
I know that there is talk about getting hbs `if` aligned. But that's not the case yet.
And even then,
. length is only valid for this case. If i just want to check if the property is set, then it won't work.
And also, the issue remains that the error message is misleading

**Comment by patricklx** [comment]
How about overwriting 
`meta.addMixin` instead?

**Comment by patricklx** [comment]
Here it checks if it's an array:
https://github.com/emberjs/ember.js/blob/f8001db8bf267c1789357bc11cb51e8001f13f5e/packages/%40ember/-internals/glimmer/lib/utils/to-bool.ts#L12
Then later calls
Arrax.isArray() || EmberArray.detect()
The detect then causes the assertion to appear.

I think removing the assertion would be enough for this case 
No need to make the promise array be handled as a native or ember array.

**Comment by runspired** [comment]
> If i just want to check if the property is set, then it won't work.
And also, the issue remains that the error message is misleading

the property is always set, hasMany relationships always have a value

**Comment by patricklx** [comment]
Not if i  set it to other objects

**Comment by runspired** [comment]
> Not if i pass it to other objects

Not sure what you mean. hasMany relationships literally always have a value. Once accessed they are always either an instance of PromiseManyArray or IdentifierArray

**Comment by patricklx** [comment]
I mean that i could set that value on an object of my choice. Where the property is undefined or of some other kind. If i later set it to an PromiseManyArray and do check it with an hbs if. It will fail.

**Comment by runspired** [comment]
I think I see. This isn't about "do I have length" but "am I set". I can buy that argument. I'd been mulling over the PR you submitted, only reason I haven't accepted is I can't remember if there's a test, was there one that failed when you removed the original assert?

**Comment by patricklx** [comment]
Hi, no, i didn't test without overwrites
