### ISSUE TITLE
tracking: road to public EmberData typescript support

### ISSUE THREAD

**Issue by gitKrystan** [emberjs/data#8852]
This issue exists for tracking at https://github.com/orgs/emberjs/projects/9

Notes from @chriskrycho:

There are, broadly speaking, two ways to do this:
    
1. Update the existing ambient type definitions to work with the definitions published from `ember-source`. This can be done either in `@types` or published from `ember-data` the same way that Ember did during its preview period.

2. Publish types straight from `ember-data`'s own source. This will be the cleanest approach, but also comes with the necessary up-front work of updating Ember Data to use Ember's types instead of the `@types` types. (Notably, that work needs to be done *anyway*, but also may be non-trivial!)

**Comment by BryanCrotaz** [comment]
how hard is (2)? I may be able to spend some time on it as not having types has bitten me in the bum trying to learn ED 5

**Comment by runspired** [comment]
We now publish types with canary releases and as a separate set of packages that can be installed by users of older versions. Note that these types won't be perfectly accurate for older versions, we recommend using 4.7+ to consume them, ideally 4.12.

**Comment by runspired** [comment]
going to close this as the road is well paved now, at this point we just need folks to dogfood the types to improve their quality so we can mark them as stable.
