### ISSUE TITLE
Refactor: Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by Agnik7** [emberjs/data#8962]
### Description
The different sections of the `CONTRIBUTING.md` file are linked to different markdown files. It would be highly efficient to put all the information in a single place instead of multiple such locations, where it is becoming difficult to navigate.

**Comment by Agnik7** [comment]
Requesting the project maintainers to assign this issue to me

**Comment by runspired** [comment]
Hi! I definitely welcome suggestions on the contributing guide and have been meaning to put more work into docs for "getting setup for development" and the project's architecture. However, I suspect we want to keep it as separate files. We used to have it as one file and that really just made it more of a mess, and separate files will makes it easier to use a docs builder to create a site.

**Comment by Agnik7** [comment]
Oh alright

**Comment by runspired** [comment]
To be clear, open to any improvements you have mind! We have *a lot* of needed contributor documentation.

I went ahead and scaffolded a little bit of additional contributing materials here as a brain dump https://github.com/emberjs/data/pull/8963

**Comment by Agnik7** [comment]
hey @runspired , how about linking the `CODE_OF_CONDUCT.md` to the CONTRIBUTING.md file? This is because the repository visitors usually look into only 2 files first: the README.md and the CONTRIBUTING.md. So having a link to the code of conduct there, albeit a minor change, is really important.

**Comment by runspired** [comment]
seems good

**Comment by Agnik7** [comment]
Ok, then I'm on it! Sending a pr by morning

**Comment by Agnik7** [comment]
@runspired I've raised a PR #8966 . Requesting your review to the PR. Apologies for any inconvenience caused.

**Comment by runspired** [comment]
@Agnik7 no inconvenience at all!
