### ISSUE TITLE
RequestInfo and Future are not exported as types

### ISSUE THREAD

**Issue by BryanCrotaz** [emberjs/data#9103]
`RequestManager.request` needs to be overridden to do anything interesting, but the signature involves `RequestInfo` and `Future`. These types need to be in the public API.

Additionally neither of them are documented, so as a developer I don't know how to add data to them. In my case I want to add an Authorization header but don't know how.

**Comment by runspired** [comment]
you should never override RequestManager.request. It is absolutely not necessary. Future and RequestInfo are both documented in the api docs, we don't ship types and thus no, there would not be any types to import.

**Comment by BryanCrotaz** [comment]
https://api.emberjs.com/ember-data/release/classes/RequestInfo

RequestInfo is not documented like the other classes are

**Comment by runspired** [comment]
RequestInfo isn't a class is why, its just a typescript interface. We have special cased a few key interfaces to show in the docs as classes but generally there's no good way for types to be documented in the api docs with the current stack used there.
