### ISSUE TITLE
Broken docs link

### ISSUE THREAD

**Issue by BryanCrotaz** [emberjs/data#9104]
[https://api.emberjs.com/ember-data/release/modules/@ember-data%2Fjson-api%2Frequest](https://api.emberjs.com/ember-data/release/modules/@ember-data%2Fjson-api%2Frequest)

Available builders section - all links break - e.g.

[https://api.emberjs.com/ember-data/release/functions/@ember-data%2Fjson-api/findRecord](https://api.emberjs.com/ember-data/release/functions/@ember-data%2Fjson-api/findRecord)

=> WHOOPS! SOMETHING WENT WRONG.

**Comment by runspired** [comment]
some bad copy pasta, its the links under `functions` below those that do work and are for the same thing.
