### ISSUE TITLE
broken docs link

### ISSUE THREAD

**Issue by BryanCrotaz** [emberjs/data#9111]
https://api.emberjs.com/ember-data/5.3/modules/@ember-data%2Fjson-api

At the bottom:
```For the full list of APIs available read the code documentation for [Ember**Data** Cache](https://github.com/emberjs/data/blob/main/ember-data-types/cache/cache.ts)```

This link is broken.

**Comment by runspired** [comment]
unfortunately links from within the api docs can't tag a specific version of the code on github and on canary that has indeed moved. We should update the link for the next release to the new spot if we haven't yet but not sure there's anything we can do for old spots. @jaredgalanis any thoughts?

**Comment by BryanCrotaz** [comment]
I don't think you should refer people to the source - the docs embedded in the source should be surfaced in the api docs instead

**Comment by runspired** [comment]
there's no other option in these situations
