### ISSUE TITLE
docs: turning store.request document into record(s) is not documented

### ISSUE THREAD

**Issue by BryanCrotaz** [emberjs/data#9114]
As per the new way of using ember data:

`store.request(findrecord('person', 2));`

returns a document.

How do you turn that into a record? In my case I have a `Person` model in `models/person.ts`

This appears to be undocumented, or if documented isn't linked from anywhere obvious

**Comment by runspired** [comment]
when you use `store.request` instead of `requestManager.request` this is automatically done. the result will have a content property that is the json-api document, and its data property will be the record instance.

Note, above `2` should be `"2"` as in `store.request(findrecord('person', '2'));`
