### ISSUE TITLE
bug: typescript error when using computed properties in conditionals

### ISSUE THREAD

**Issue by libmartinito** [emberjs/data#9146]
### Reproduction

[Here](https://github.com/libmartinito/comp-property-type-error) is a github repo with the minimum required to see the error.

You can easily see the typescript error when opening the user model in an editor with typescript linting/LSP.

<img width="1559" alt="Screenshot 2023-11-30 at 2 14 22 AM" src="https://github.com/emberjs/data/assets/62695092/8fc5cf56-2528-4667-9b69-a1b6e77ac0f3">

### Description

The expected result in this case is that typescript recognizes that isNew is a computed property that returns a boolean type. There is a workaround to use the get() helper in accessing computed properties, but it seems that that approach is deprecated as there is an ember/no-get lint rule. It seems that this problem was planned to be fixed on version 4 according to [this](https://github.com/typed-ember/ember-cli-typescript/issues/969) closed issue. 

### Versions

```
comp-prop-type-error@0.0.0 /Users/libmartinito/personal/comp-prop-type-error
├─┬ @ember/test-helpers@3.2.1
│ └── ember-source@5.2.0 deduped
├─┬ ember-cli-app-version@6.0.1
│ └── ember-source@5.2.0 deduped
├─┬ ember-data@5.2.0
│ └─┬ @ember-data/model@5.2.0
│   └─┬ ember-cached-decorator-polyfill@1.0.2
│     └── ember-source@5.2.0 deduped
├─┬ ember-modifier@4.1.0
│ └── ember-source@5.2.0 deduped
├─┬ ember-page-title@8.1.0
│ └── ember-source@5.2.0 deduped
├─┬ ember-qunit@7.0.0
│ └── ember-source@5.2.0 deduped
├─┬ ember-resolver@11.0.1
│ └── ember-source@5.2.0 deduped
└── ember-source@5.2.0

comp-prop-type-error@0.0.0 /Users/libmartinito/personal/comp-prop-type-error
├─┬ ember-cli-dependency-checker@3.3.2
│ └── ember-cli@5.2.1 deduped
└── ember-cli@5.2.1

comp-prop-type-error@0.0.0 /Users/libmartinito/personal/comp-prop-type-error
└── ember-data@5.2.0
```

**Comment by runspired** [comment]
This project does not ship types, its likely you want to open an issue or add a fix to the community types in DefinitelyTyped's repo
