### ISSUE TITLE
Feat - Additional Functionality Support in RequestManager for handler for Dynamic Handling beyond 'request'

### ISSUE THREAD

**Issue by lakshmxn** [emberjs/data#9195]
We are currently utilizing the RequestManager in Ember Data to manage authentication and fetching within the handler chain. However, we've encountered a scenario where authentication needs to be dynamically performed based on the response after fetching. The current implementation in the documentation primarily focuses on authentication based on headers or cookies, and we've found limitations in passing the response between handlers, often requiring an additional fetch.

To address this requirement, we suggest enhancing the RequestManager to support authentication based on the fetch response. This enhancement could be achieved by introducing an additional function or by providing the ability to pass the entire context (response, request) rather than just the context.request to other handlers.

```
import RequestManager from '@ember-data/request';
import Fetch from '@ember-data/request/fetch';
import Auth from 'ember-simple-auth/ember-data-handler';

export default class extends RequestManager {
  constructor(createArgs) {
    super(createArgs);
    this.use([Auth, Fetch]);
  }
}
```

In the above example, the authentication is currently done before fetching. We need the ability to perform authentication based on the fetch response, enabling more flexibility in handling authentication scenarios.

` constructor(args: any) {
    super(args);
    this.requestManager.use([AuthHandler,FetchHandler]);
  }`

By enhancing the RequestManager, we aim to provide a more comprehensive solution for handling authentication scenarios where the authentication process depends on the response received after fetching.

**Comment by Baltazore** [comment]
If you need to do anything extra in `AuthHandler` after fetch was done, you should await the result of fetch.

here is quick example

```ts
const AuthHandler = {
  async request({ request }, next) {
    const headers = new Headers(request.headers);
    headers.append(
      'Authorization',
      `Bearer ${someJWT}`,
    );

    const { content, request } = await next(Object.assign({}, request, { headers }));
    // do anything with result
    // content will have JSON payload from server
    // in request you can still find request context
    return someAdditionalValidation(content, request);
  },
};
```

**Comment by runspired** [comment]
@Baltazore is correct here. All handlers have access to the full request and response. To get the response you just have to await or `.then` the call to `next`.

Whatever you return then becomes the response for the preceding handler.

**Comment by lakshmxn** [comment]
Thanks for the response @Baltazore @runspired  awaiting the result of fetch is working.
