### ISSUE TITLE
Understanding polymorphism

### ISSUE THREAD

**Issue by Jopie01** [emberjs/data#9217]
I'm trying to understand polymorphism and how it works, but I can't get my head around how I can use it in my situation. My situation is that I have a `belongsTo` field which can hold a record from different models. The problem is that I'm using the `SchemaService` to get all field data from the backend, so I don't define any model.

```javascript

menu model:
{
  action: {
    name: 'action',
    kind: 'belongsTo',
    polymorphic: true,
-->    type: // what should I put here? Can this be a list of models?
  }
}
```
The `type` is normally used to define the relation with the other model, but now I want to relate multiple models.

I get all the needed data from the backend and just have to translate it into something the store accepts. At the moment I'm just using an attribute but this impacts performance because I need to do some extra requests to get the data.

Versions:
```
"ember-source": "~5.6.0",
"@ember-data/debug": "5.5.0-alpha.11",
"@ember-data/graph": "5.5.0-alpha.11",
"@ember-data/json-api": "5.5.0-alpha.11",
"@ember-data/request": "5.5.0-alpha.11",
"@ember-data/store": "5.5.0-alpha.11",
"@ember-data/tracking": "5.5.0-alpha.11",
```

**Comment by Jopie01** [comment]
OK, digged a bit deeper through the code and specifically https://github.com/emberjs/data/blob/5a48f52a08587e59cb529575577880daf678ae00/packages/store/src/-types/q/schema-service.ts the last portion. As it turns out I have the `polymorphic: true` at the wrong level. It should be in the `options`

```javascript
menu model:
{
  action: {
    name: 'action',
    kind: 'belongsTo',
    options: {
        polymorphic: true,
        async: true,
        inverse: null
    }
  }
}
```
Seems like I don't have to specify a `type` because with this I'm able to push data into the store and then I can happily request it from the store without errors. The only extra thing I have to do is to make sure the models exists when data is pushed, so first fetch the model before pushing into the store.

**Comment by runspired** [comment]
For `inverse: null` yes, there is nothing additionally needed though you are missing the abstract type and should make sure you include it.

```diff
{
  action: {
    name: 'action',
    kind: 'belongsTo',
+   type: 'action', // I'm guessing here that the abstract type is also "action"
    options: {
        polymorphic: true,
        async: true,
        inverse: null
    }
  }
}
```

For `inverse: <some-prop>` the corresponding field on the other record must specify the abstract type. So for instance, assume menu said this:

```diff
{
  action: {
    name: 'action',
    kind: 'belongsTo',
+   type: 'action',
    options: {
        polymorphic: true,
        async: true,
+       inverse: 'lists'
    }
  }
}
```

Then any record that satisfies "action" must have the below field def:

```ts
// "add-item" action
{
  lists: {
    name: 'lists',
    kind: 'hasMany',
    type: 'menu',
    options: {
      async: true,
      inverse: 'action',
      as: 'action'
    }
  }
}
```

`as` here is what allows any type to act as the abstract type. Note, the entire field configuration must identically match across all types that satisfy this polymorphic trait.
