### ISSUE TITLE
Breaks yarn install on Windows

### ISSUE THREAD

**Issue by vlascik** [emberjs/data#9255]
ember-data 5.3.x+  breaks `yarn install` on Windows

```
➤ YN0000: ┌ Link step
➤ YN0001: │ Error: While persisting /P:/Project/.yarn/cache/ember-data-npm-5.3.3-dfa32911e3-64db95b5ef.zip/node_modules/ember-data/ -> /P:/Project/node_modules/ember-data ENOENT: no such file or directory, open 'P:\Project\node_modules\ember-data\dist\docs\classes\<Interface> Adapter.html'
```

Some filenames in `dist/docs` contain `<` `>`, which are illegal characters on Windows filesystems.

**Comment by runspired** [comment]
looks to be a pnpm bug https://github.com/pnpm/pnpm/issues/5119#issuecomment-1990643640

**Comment by vlascik** [comment]
It's still happening in 5.4.0-alpha.49 from 2 days ago.

**Comment by runspired** [comment]
@vlascik give alpha.50 a try

**Comment by vlascik** [comment]
It works, thank you.

**Comment by vlascik** [comment]
The files (and the error) are back in v5.4.0-alpha.73

**Comment by runspired** [comment]
I think now that we are a v2-addon we can't rely on any variant of files and ignores working correctly so the only solution is to stop shipping the docs in dist. Need @jaredgalanis or @mansona to confirm this is safe.

**Comment by vlascik** [comment]
You could also change the whatever process is generating docs files with illegal Windows filesystem names like `<` `>` `:` etc. to... not do that.

**Comment by runspired** [comment]
@vlascik that would require rewriting a very old and large legacy project ;) https://yui.github.io/yuidoc/

**Comment by runspired** [comment]
@mansona lets update it to look for it in `packages/-ember-data/tmp/docs/data.json` going forward. You'd probably have to do a version based switch. `5.4` is the version at which to use the new path. I'll comment back here once I've made the change and reconfirm the new path.
