### ISSUE TITLE
Build broken after update from `5.3.0` to `5.3.3` 

### ISSUE THREAD

**Issue by villander** [emberjs/data#9262]
### Reproduction

It's impossible to reproduce, given we have some private packages 

### Description

Updated the package.json with `ember-data` from 5.3.0 to 5.3.3:

```
webpack 5.90.3 compiled with 8 errors in 26990 ms
Build Error (PackagerRunner) in node_modules/.pnpm/@ember+test-helpers@3.3.0_@glint+template@1.3.0_ember-source@5.7.0_webpack@5.90.3/node_modules/@ember/test-helpers/-internal/debug-info.js

Module not found: Error: Can't resolve '@ember/test-waiters' in '$TMPDIR/embroider/2012c7/node_modules/.pnpm/@ember+test-helpers@3.3.0_@glint+template@1.3.0_ember-source@5.7.0_webpack@5.90.3/node_modules/@ember/test-helpers/-internal/debug-info.js'


Stack Trace and Error Report: /var/folders/0v/jpdg1flj3qscvbvt728pgt8c0000gn/T/error.dump.b70e28c6f9bdad3f611fb40f95f6218c.log
```

### Versions

Run the following command and paste the output below: `pnpm list ember-source && pnpm list ember-cli && pnpm list --pattern ember-data`.

```cli
ember-cli 5.7.0
ember-source 5.7.0
ember-data 5.3.3
```

**Comment by runspired** [comment]
this looks like an issue with your pnpm/pnpm version, likely some dependency group didn't dedupe properly. I'd try manually running dedupe and force installing to get cleaner node_modules.

**Comment by villander** [comment]
I've tried `pnpm dedupe` + `pnpm install --force` didn't work.

**Comment by runspired** [comment]
Since this feels like an issue with a specific setup, closing for now
