### ISSUE TITLE
The kind `collection` is missing in schema-record

### ISSUE THREAD

**Issue by Jopie01** [emberjs/data#9462]
I'm working to migrate more and more into the new Warp-Drive with `schema-record`. I've extended the `SchemaService` because I fetch the schema data from my backend and then build the schema myself. To build the schema I'm using RFC1027 (https://github.com/runspired/rfcs/blob/ember-data_schema-service/text/1027-ember-data-schema-service.md) for the right layout and keys.

In the RFC I read that:
1. `belongsTo` becomes `resource`
2. `hasMany` becoms `collection`

So I created my relational fields accordingly. However when fetching the data with the `instantiateRecord` hook from `@warp-drive/schema-record/hooks` I get the error:

```
Uncaught (in promise) Error: Field 'childs' on 'ui_menu' has the unknown kind 'collection'
```
Looking where this is coming from, I noticed that the switch statement https://github.com/emberjs/data/blob/55654008c9605726bf47c030d0edbc87df36b774/packages/schema-record/src/record.ts#L473 is missing the case for `collection`. Is this missing or intentional?

**Comment by runspired** [comment]
You're just early, it hasn't been implemented yet

**Comment by Jopie01** [comment]
Whoops, yeah that's another possibility.
