### ISSUE TITLE
"Cannot supply a different store via context than was used to create the request" on autorefresh

### ISSUE THREAD

**Issue by MichalBryxi** [emberjs/data#9478]
### Reproduction

- Branch [mb/different-store on my project](https://github.com/vast-ch/the-mountains-are-calling/tree/mb/different-store) should give reproduction.

### Description

- Assume following `<Request>` that has "autorefresh":

```gjs
  <template>
    <Request
      @request={{this.request}}
      @autorefresh={{true}}
      @autorefreshBehavior='refresh'
      @autorefreshThreshold={{1}}
    >
      <:loading>
        {{t 'map.loading'}}
      </:loading>

      <:content as |result state|>
        {{yield (hash result=result)}}
      </:content>
    </Request>
  </template>
```

1. Run the app
2. Switch to other tab and after `1 second` (or more) switch back

#### What should happen:

- Data is refreshed and the app shows new data.

#### What happens instead:

```
Error: Cannot supply a different store via context than was used to create the request
```

![Screenshot 2024-06-14 at 16 56 46](https://github.com/emberjs/data/assets/847473/bd4a87c4-f915-4166-9871-b4876a596b48)

#### Notes

- I tried to debug the test that is causing this and seems like the `store` is for some reason different than what it expects it to be. But I am not (intentionally) changing store anywhere.

![Screenshot 2024-06-14 at 16 36 41](https://github.com/emberjs/data/assets/847473/42b191c7-4e60-42c3-99e5-527d0998937f)

- But(!) I [do use a custom store service](https://github.com/vast-ch/the-mountains-are-calling/blob/mb/different-store/app/services/mountains-store.ts). But I can't tell why would that be a problem? My hunch would be that the test function is incorrect.

### Versions

Run the following command and paste the output below: `pnpm list ember-source && pnpm list ember-cli && pnpm list "*ember-data*"`.

```cli
Legend: production dependency, optional only, dev only

the-mountains-are-calling@0.0.0 /Users/michal/vast.ch/the-mountains-are-calling

devDependencies:
ember-source 5.6.0
Legend: production dependency, optional only, dev only

the-mountains-are-calling@0.0.0 /Users/michal/vast.ch/the-mountains-are-calling

devDependencies:
ember-cli 5.6.0
Legend: production dependency, optional only, dev only

the-mountains-are-calling@0.0.0 /Users/michal/vast.ch/the-mountains-are-calling

dependencies:
@ember-data-types/adapter 5.4.0-alpha.84
@ember-data-types/graph 5.4.0-alpha.84
@ember-data-types/json-api 5.4.0-alpha.84
@ember-data-types/legacy-compat 5.4.0-alpha.84
@ember-data-types/model 5.4.0-alpha.84
@ember-data-types/request 5.4.0-alpha.84
@ember-data-types/request-utils 5.4.0-alpha.84
@ember-data-types/serializer 5.4.0-alpha.84
@ember-data-types/store 5.4.0-alpha.84
@ember-data-types/tracking 5.4.0-alpha.84
```

**Comment by runspired** [comment]
`ember-data` gives you the `store` service automatically, and the Request component expects to find that the store on the request matches the current context's store service (which if using the context addon is supplied by the context else we use the service named `store`)

so in effect, your app had both `mountain-store` and `store`, the latter being the re-exported one from `ember-data`, and thus two instances.

I'd recommend renaming `mountain-store` to `store`. If that does not work, it may be due to a classic ember-cli typescript bug when using an addon that provides a re-exported service. Try changing the file to a js file and likely it'll start working.

**Comment by MichalBryxi** [comment]
Ha! Yes! 

- I need to use `store.js` and not `mountains-store.ts` because of the two instances problem
- I need to use `store.js` and not `store.ts` because of the TS issue
