### ISSUE TITLE
[5.3.4] EmberData deprecation for `ember-inflector` is incorrect

### ISSUE THREAD

**Issue by mkszepp** [emberjs/data#9484]
Like shortly discussed in [discored](https://discord.com/channels/480462759797063690/1251363184556642365), the deprecation link for `ember-inflector` is not correctly

https://github.com/emberjs/data/blob/7761b44b04ba6a09f8087aea98d52bf6cf47501c/packages/request-utils/src/deprecation-support.ts#L37

The link should should be https://api.emberjs.com/ember-data/release/classes/CurrentDeprecations instead of https://deprecations.emberjs.com/id/warp-drive.ember-inflector

In additional the wrong package name was specified. It should be `@ember-data/request-utils` not `@warp-drive/request-utils'

https://github.com/emberjs/data/blob/7761b44b04ba6a09f8087aea98d52bf6cf47501c/packages/request-utils/src/deprecation-support.ts#L27

The import for `singular` (also for `plural`...) should be `import { singular } from '@warp-drive/request-utils/string';`, because its not exported in `index.ts` https://github.com/emberjs/data/blob/v5.3.4/packages/request-utils/src/index.ts

**Comment by runspired** [comment]
The link is correct, there’s just no guide yet. Because the deprecation guides are a separate project we have to add the link before it exists.
