### ISSUE TITLE
inspector cannot inspect ember-data - ember-data/debug is missing app-reexports

### ISSUE THREAD

**Issue by patricklx** [emberjs/data#9493]
### Reproduction

* create a new app with ember-cli new
* start it
* open inspector
* no data tab

ember data debug is missing app re-exports.
https://www.npmjs.com/package/@ember-data/debug?activeTab=code

inspector expects to find data-adapter inside app, https://github.com/emberjs/ember-inspector/blob/main/ember_debug/data-debug.js#L20

### Description

inspector cannot show data records because it cannot find the adapter.
https://github.com/emberjs/ember-inspector/issues/2578

manually adding `app/data-adapter.js` with `export { default } from '@ember-data/debug';` fixes the issue

### Versions
ember-data: ~5.3.3
"ember-source": "~5.9.0"
"ember-cli": "~5.9.0",

**Comment by runspired** [comment]
hrm, this one is kinda tricky because I don't think we can safely add it as an app re-export and support configuring it correctly. With it being a v2-addon now its likely you should *have* to explicitly add it to your build.

**Comment by patricklx** [comment]
the v2 addons do have app re exports with the provided rollup addons from embroider.
Can you not use those?

**Comment by Baltazore** [comment]
Hey @patricklx if you can point me to that I can spend some1 time adding those if you ok with it @runspired

**Comment by patricklx** [comment]
Sure. It's in the default blueprint:
https://github.com/embroider-build/addon-blueprint/blob/cb4d7eee319b15cd2aae822653009a96d10baab4/files/__addonLocation__/rollup.config.mjs#L29

**Comment by patricklx** [comment]
I think it should have at least a deprecate step. So it could also be part of -ember-data package. With some macro condition?

**Comment by runspired** [comment]
We can't use app re-export from the V2 add-on at all, we could maybe guard the import in -ember-data but regardless we'll have to break the existing config setting

**Comment by patricklx** [comment]
Why not? Some constraints by ember data internals?

**Comment by runspired** [comment]
@patricklx because we have an existing config setting used to keep it in the build in v1, the default is that its not included in the build, and vite/embroider don't have a clean production-only-import concept so I'm not sure the path forward here.

**Comment by runspired** [comment]
should be resolved on main. Will result in the module still being present unfortunately, though empty.

**Comment by patricklx** [comment]
Thanks 👍.
Will this be back ported to 5.3 lts?
