### ISSUE TITLE
[5.3.7] Issue with use in nested addon

### ISSUE THREAD

**Issue by jrjohnson** [emberjs/data#9498]
### Reproduction

This is reproducible in any app which consumes an addon that provides ember data, you can see it in our [CI build failure](https://github.com/ilios/frontend/actions/runs/9602825790/job/26484544326?pr=7901#step:6:14) when [upgrading ember-data pin Ilios](https://github.com/ilios/frontend/pull/7901) 

However it's most easily seen in the `test-app` of a monorepo embroider v2 addon with:

```cli
ember addon test-addon -b @embroider/addon-blueprint --pnpm
cd test-addon
pnpm --filter=test-addon install ember-data webpack
pnpm start:test-app
```

### Description

Installing `ember-data` after 5.3.4 in an add-on and consuming that add-on from an app causes a build failure with the error:
`Cannot read properties of undefined (reading 'project')` which comes from `const dirname = app.project.root;` in [addon-main.cjs](https://github.com/emberjs/data/blob/bf1f992490d5b8b4637cbb748c01aa5109497786/packages/-ember-data/addon-main.cjs#L20) which was added in #9477.

I've seen this issue worked around before with something like the `findApp` method in [ember-cli-babel](https://github.com/emberjs/ember-cli-babel/blob/dff2a54370dd92d7f9b3fe3fcb9b02f344eebbaa/lib/find-app.js#L3) because you need to traverse up the tree before you get to the actual app.

I've also used the slightly messy:

```javascript
let current = this;
let app;
// Keep iterating upward until we don't have a grandparent.
// Has to do this grandparent check because at some point we hit the project.
do {
  app = current.app || app;
} while (current.parent.parent && (current = current.parent));
```

### Versions

```cli
ember-source 5.9.0
ember-cli 5.9.0
ember-data 5.3.7
```

**Comment by runspired** [comment]
I'm not sure this can be worked around but feel free to try. Unfortunately we don't have a real addon-main in v2 addons, its far more restricted.

**Comment by jrjohnson** [comment]
Thanks, this works if a copy it into a project so I have high hopes! I'll test as soon as it's released (should I back port it?) and can tweak it with a PR if needed. The complication with v2 adding is what prevented me from making any attempt at this myself, I'm just not familiar with the rules there yet.

**Comment by runspired** [comment]
is already released!

**Comment by jrjohnson** [comment]
Yeah it is!  The process here has gotten super fast, LOVE IT!
