### ISSUE TITLE
Error: Could not find module `@ember-data/adapter/rest`

### ISSUE THREAD

**Issue by lozjackson** [emberjs/data#9504]
### Reproduction

Steps to repro:

- Created a new app with ember-cli
- update ember-data to 5.3.8
- install active-model-adapter
- Start the app

### Description

Since upgrading ember-data to 5.3.8,  I'm getting an error in the console that is preventing the app from starting

> Error: Could not find module `@ember-data/adapter/rest` imported from `active-model-adapter/active-model-adapter`

I'm guessing something changed with the exports that is causing this error

### Versions

ember-cli 5.8.1
ember-source 5.8.0
ember-data 5.3.8
active-model-adapter 4.0.1

I've also created an issue in the active-model-adapter repo here: https://github.com/adopted-ember-addons/active-model-adapter/issues/189

**Comment by runspired** [comment]
issue is with active-model-adapter not specifying any dependencies https://github.com/adopted-ember-addons/active-model-adapter/issues/189#issuecomment-2200867329
