### ISSUE TITLE
Latest LTS is incompatible with `ember-cli` v5.12.0

### ISSUE THREAD

**Issue by mkszepp** [emberjs/data#9545]
The latest EmberData package (v5.3.8) is not anymore compabile with latest `ember-cli` version (5.12.0).

This is because `ember-cli` has updated all dependency to latest.

When you try to create a new app you will run immediately into an error while build.

Steps to reproduce:
1. `ember new my-app --embroider`
2. `ember s`

Error: 
```
Some V1 ember addons are resolving as incorrect peer dependencies. This makes it impossible for us to safely convert them to v2 format.

  👇 👇 👇
👉 See https://github.com/embroider-build/embroider/blob/main/docs/peer-dependency-resolution-issues.md for an explanation of the problem and suggestions for fixing it.
  👆 👆 👆

my-app@0.0.0 (dev)-> ember-data@5.3.8 -> @ember-data/request-utils@5.3.8
    sees peerDep @ember/string@3.1.1
      at /home/user/projects/test/my-app/node_modules/ember-data/node_modules/@ember/string
    but my-app@0.0.0 is using @ember/string@4.0.0
      at /home/user/projects/test/my-app/node_modules/@ember/string



  👇 👇 👇
👉 See https://github.com/embroider-build/embroider/blob/main/docs/peer-dependency-resolution-issues.md for an explanation of the problem and suggestions for fixing it.
  👆 👆 👆


Stack Trace and Error Report: /tmp/error.dump.0ff588b5e8449e76c30d9508b6ecbc5c.log
```

This occures because ember-data has in LTS no support for `@ember/string` v4.0.0

## Fix
Backporting the allow of peerDependency as patch should resolve everythink for now, since ember-data is shipping next minor version
- https://github.com/emberjs/data/pull/9511
- https://github.com/emberjs/data/pull/9519
- https://github.com/emberjs/data/pull/9525

## Workaroud
Apps must downgrade `@ember/string` for compatiblity or using `overrides` to fix this issue

**Comment by runspired** [comment]
Resolved in 5.3.9
