### ISSUE TITLE
v4.12.8 (v4 LTS) uses ember-inflector v4 as peer dependency which is incompatible with Embroider

### ISSUE THREAD

**Issue by lfloyd117** [emberjs/data#9584]
### Reproduction & Description

- Install ember-data v4.12.8 in an Embroider app
- Internal dependencies such as @ember-data/serializer list `ember-inflector@^4.0.3` as a peer dependency
- `ember-inflector@^4.0.3` is incompatible with Embroider due to the `require('./package').name` in its `index.js` file
    - this is fixed in v5
- Since Embroider cannot reconcile incorrect peer dependencies, an Embroider app cannot build if pulling v5 of ember-inflector (as we have to circumvent this issue with v4 & Embroider), but we cannot use v4 of ember-inflector as it blows up at runtime

### Versions

We have Embroider working with ember-data 4.6.4 right now, but it was in later 4.* versions that ember-inflector at v4 was listed as a peer dependency, breaking the build. 

```cli
Legend: production dependency, optional only, dev only

my-app@0.4.0 /path/to/repo/apps/my-app

devDependencies:
ember-source 4.12.4
Legend: production dependency, optional only, dev only

my-app@0.4.0 /path/to/repo/apps/my-app

devDependencies:
ember-cli 4.12.3
Legend: production dependency, optional only, dev only

my-app@0.4.0 /path/to/repo/apps/my-app

devDependencies:
@types/ember-data 4.4.16
@types/ember-data__adapter 4.0.6
@types/ember-data__model 4.0.5
@types/ember-data__serializer 4.0.6
@types/ember-data__store 4.0.7
ember-data 4.6.5
```

---

I believe this is fixable by a patch version to the packages listing ember-inflector as a peer dependency to bump it to v5 (changing it from a v1 addon to a v2 addon and fixing the Embroider incompatibilities)

**Comment by runspired** [comment]
the v4-main branch which will release as v4.13 has a fix for this including. Keep an eye out for that release, should be soon.
