### ISSUE TITLE
EmberJS model doesn't detect deleted records from the DB 

### ISSUE THREAD

**Issue by ddewaele** [emberjs/data#962]
I have a very simple CRUD app  (https://github.com/ddewaele/emberjs-crud-rest) using EmberData, the REST adapter, and a Ember.JS compatible REST backend that exhibits the following problem : 

When records are deleted from the DB outside of the EmberApp (ex: through the DB console) , EmberJS never detects that the record or records are deleted.

A call to App.WhateverModel.find() keeps returns these deleted records despite the fact that  I see the find() call going to the REST backend.

So it should know that these records got deleted.

As the find() call is capable of detecting new records (App.WhateverModel.find() sees records that were inserted in the DB outside of the Ember.JS app), I wonder if this is a bug.

If it's not a bug, it's not clear to me howto "reset" the model so that it picks up the new data.

The only workaround right now is to do a full page refresh using the browser F5.

**Comment by cresg820** [comment]
@johnnyoshika when i call unloadAll before reload the data from backend I see a 'flickering' on template that is displaying my model. How can I avoid the 'flickering'?

**Comment by johnnyoshika** [comment]
@cresg820, can you create a jsbin that demonstrates the problem?

**Comment by cresg820** [comment]
@johnnyoshika I create a simple demo at http://emberjs.jsbin.com/jebiqijimo/1/edit
When you click on refresh you see a fast blinking in template.

**Comment by NotSqrt** [comment]
I have a similar situation : need to reflect in the local store that some remote objects are no longer there.

I am thinking of a mechanism : storing a "lastSync" date in each instance. After the refresh, if the "lastSync" is older that the moment where the client started the refresh, I can call "unloadRecord".

A better idea ?

**Comment by lolmaus** [comment]
My take based on @cresg820's jsbin: http://emberjs.jsbin.com/tinugi/3/edit?html,js,output

No flickering! :D

Be careful, it's gonna delete all records that do not exist on the backend, including those that the user might have created clientside but hasn't saved yet.

**Comment by jordanblink** [comment]
Yeah this is really depressing, I was banging my head against the head for so so long ,and I figured it was something simple I was unable to do ,an action leads to an API call which deletes certain records in the server document and returns the updated document, but the model wont delete existing documents.

I

**Comment by runspired** [comment]
@jordanblink it won't detect server side deletes, it knows about things you tell it you've deleted.

**Comment by jordanblink** [comment]
I am deleting the records on the server side and returning back the updated model as part of the response of the API call ,if I add records in the response , the records get added to the model but if I delete records and send the new document in the response,  the model wont delete the record.

**Comment by runspired** [comment]
@jordanblink ping me in the ember community slack and I'll walk you through it.

Generate an Invite: https://ember-community-slackin.herokuapp.com/
Slack: embercommunity.slack.com

**Comment by gilfanovrrPaker** [comment]
this works for me:
server response includes deleted records with check fields (amount or active)
\app\orders-monitor\controller.js
```
export default Ember.Controller.extend({
    orders: Ember.computed(function() {
        return this.get('store').findAll('order');
    }),
    activeOrders1: Ember.computed.filter('orders.@each.amount',
         (order, index, array) => { return (order.get('amount') > 0); }),
    activeOrders2: Ember.computed.filterBy('orders', 'active')
});
```

\app\models\order.coffee
```
export default DS.Model.extend
  amount: DS.attr('number')
  active: Ember.computed 'amount', () -> @get('amount') > 0
```
