### ISSUE TITLE
Computed properties depending on isDirty, isDeleted, isNew are interconnected

### ISSUE THREAD

**Issue by sandstrom** [emberjs/data#966]
When an object goes from the _loaded state_ to the _dirty state_ any computed property depending on `isDirty` is correctly recalculated. However, any computed property depending on `isDeleted` is also recalculated, which is less good (this `isDeleted` is false both before and after).

This is due to how `retrieveFromCurrentState` is implemented, since it depend on the state.
https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/model/model.js#L8

I can think of two ways to solve this:
1. Rewrite `retrieveFromCurrentState` somehow
2. Change computed properties to only propagate changes if their output changed, i.e. a computed property would know it's last value, and only notify those depending on it if it's value changed upon calculation (unless there are side-effects to this change, which I haven't thought of).

**Comment by Charizard** [comment]
@fishermand46 I too have bumped into the same issue. Can you share your custom filter function?
