### ISSUE TITLE
Reserved attribute names in models

### ISSUE THREAD

**Issue by scardine** [emberjs/data#973]
I have a Post model with the following fields:

```
BlogApp.Post = DS.Model.extend({
    author: DS.attr('string'),
    title: DS.attr('string'),
    preamble: DS.attr('string'),
    content: DS.attr('string'),
    created: DS.attr('date'),
    comments: DS.hasMany('BlogApp.Comment'),
    lastUpdate: DS.attr('date')
});
```

After rendering, instead of the Post.content, the result is like:

```
<BlogApp.Post:ember272:1>
```

Other fields rendering are OK. I'm very new to Ember, but I guess `content` is conflicting with some internal property.
1. is there any workarround when the REST API has names that conflict with Ember internals?
2. are there other forbidden attribute names? (we should list them in the docs)

Perhaps all reserved attribute names should be prefixed by an underscore in order to avoid conflicts with user created properties.

**Comment by jwhitmarsh** [comment]
:+1: for logging a warning. Came across this in Component as well where 'trigger' and 'container' are reserved but both are used in Bootstraps popovers.

**Comment by humanchimp** [comment]
An alternative approach could mangle the keys used for the data fields when setting and retrieving them.  So if my data has the key `attributes` in it, internally, Ember could store that key as `~attributes`. Then when I call `model.get('attributes')`, internally, Ember could look up the key as `~attributes`. That way, data keys can't clash with public API, and this unfortunate namespace overloading would not be exposed to user code. Might something like this work well?

**Comment by runspired** [comment]
I personally believe the model's data should be stored on `record.data` and accessed there explicitly to prevent collisions with needed keywords.

**Comment by igorT** [comment]
@runspired we considered following json api and having `.attributes` and `.relationships` but feared the upgrade emo would be too much

**Comment by les2** [comment]
At the very least:
- All reserved keys (present and anticipated future keys) should be listed in reference documentation a completely impossible to miss manner. 
- Ember should warn when models are defined with reserved attribute names (similar to the deprecation warnings); in fact, it should just refuse to define attributes this way.

Better would be a design that made collisions impossible, this includes approaches like:
- Namespacing (e.g., `model.data.foo`)
- Magic prefixes, e.g., `model.$errors` (a la angular)
- Prefixes can work in the reverse manner: e.g., `model.errors` is the ember builtin that shadows model attribute: `model.$errors` would get to the attribute; it's just an alias, so all model attributes could be accessed as `model.$content`, `model.$store`, `model.$firstName`, etc., as needed.

**Comment by mattcl** [comment]
This really should not have been closed. Just ran into an issue today where some attributes named data_* weren't showing up due to that being reserved. :/

**Comment by ldong** [comment]
```js
import DS from 'ember-data';
export default DS.Model.extend({
  type: DS.attr('string'),
});

```

`type` itself is also reserved. Weird.

**Comment by les2** [comment]
my guess would be that `id` refers to a json api resource identifier and not the model attribute. the resource identifier consists of a `type` and `id`.

**Comment by Amerr** [comment]
@ldong i have used 'type'  as an attribute in my model as String , i didnt face any issue.

**Comment by nolman** [comment]
I believe `reason` is also a reserved word for ember data. Are these reserved words documented anywhere? I have personally spent a lot of time discovering these landmines. It would really improve the usability of ember data to have a list of these words documented somewhere.

When you conflict with one of these reserved words it is really brutal to try to debug.

**Comment by sdhull** [comment]
We've found more reserved words that cause ember data to fail silently with no feedback:

`reason`
`protected`
`trigger`

This is an enormous stumbling block for developers. When you set up everything correctly (db, serializers on server, ember data models, router, route, template) and your attribute just doesn't show up on the page and there are no errors -- what are you supposed to think as a developer? "Somewhere along the line I probably fat-fingered something," right? So you bang your head against the wall going over and over and over your code only to eventually realize "oh I can't name my attribute this -- WHY DIDN'T ANYONE TELL ME??"

I'm sure there are more reserved words lurking out there for me to stumble on. Could there at least be a list somewhere?

/cc @wycats @tomdale because I know you guys care about developer ergonomics

**Comment by sly7-7** [comment]
@igorT Does your model-data branch will handle this ?
